### ISSUE TITLE
BungeeCord Prompt problems.

### ISSUE THREAD

**Issue by ShockwaveMC1** [SpigotMC/BungeeCord#1147]
When ever I open the command prompt to run bungee cord.
It says all these errors and wants me to install ubuntu or debian. And I don't want that!
It won't work properly, Please respond as soon as possible!
This is my problem

C:\Users\Carson Minecraft\Desktop\ShockHub\Hub 2>java -Xms512M -jar BungeeCord.j
ar
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
17:18:22 [INFO] Unable to initialize fancy terminal. To fix this on Windows, ins
tall the correct Microsoft Visual C++ 2008 Runtime
17:18:22 [INFO] NOTE: This error is non crucial, and BungeeCord will still funct
ion correctly! Do not bug the author about it unless you are still unable to get
 it working
17:18:22 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
17:18:22 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.7-SNAPSHOT
:"74f5ffd":967
17:18:22 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
17:18:22 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
17:18:22 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
17:18:22 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
17:18:22 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
17:18:22 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
17:18:22 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.7-SNAPSHOT:"74f5
ffd":967 by SpigotMC
17:18:22 [INFO] Loaded plugin cmd_find version git:cmd_find:1.7-SNAPSHOT:"74f5ff
d":967 by SpigotMC
17:18:22 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.7-SNAP
SHOT:"74f5ffd":967 by SpigotMC
17:18:22 [INFO] Loaded plugin cmd_server version git:cmd_server:1.7-SNAPSHOT:"74
f5ffd":967 by SpigotMC
17:18:22 [INFO] Loaded plugin cmd_send version git:cmd_send:1.7-SNAPSHOT:"74f5ff
d":967 by SpigotMC
17:18:22 [INFO] Loaded plugin cmd_list version git:cmd_list:1.7-SNAPSHOT:"74f5ff
d":967 by SpigotMC
17:18:23 [SEVERE] Exception in thread "main"
17:18:23 [SEVERE] java.lang.IllegalArgumentException: No enum constant net.md_5.
bungee.conf.YamlConfig.DefaultTabList.LOCAL
17:18:23 [SEVERE]     at java.lang.Enum.valueOf(Unknown Source)
17:18:23 [SEVERE]     at net.md_5.bungee.conf.YamlConfig$DefaultTabList.valueOf(
YamlConfig.java:39)
17:18:23 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig
.java:216)
17:18:23 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.j
ava:73)
17:18:23 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:226)
17:18:23 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:65)

Please help me!

**Comment by Magnusdb** [comment]
Check that all your port matches ;)
