### ISSUE TITLE
Epoll BungeeCord hangs

### ISSUE THREAD

**Issue by minecrafter** [SpigotMC/BungeeCord#1171]
This issue appeared when we switched to Epoll. We have moved back to NIO for stability.

Every few minutes, the proxy would hang. During this time, events were being received by plugins but player input was not responding. These hangs *did not* occur when we used NIO.

I am doubtful this is a plugin issue, due to events responding (from our main administration plugin logging player UUIDs).

I don't have logs of the hang but the pattern was like this:

`[Plugin] Blabla`
`[Plugin] Lorem ipsum`
`[Plugin] Blabla`
`[Plugin] Lorem ipsum`
`[Plugin] Blabla`
`[Plugin] Lorem ipsum`
`[etc.]`
`<sudden torrent of InitialHandler messages>`

Information:

* **OS**: Ubuntu 14.04.1 LTS (kernel: 3.13.0-33-generic)
* **Java**: java version "1.8.0_11" (Oracle JRE)
* **Bungee**: 978

**Comment by minecrafter** [comment]
@md-5 these issues are still occurring for me.

**Comment by minecrafter** [comment]
I believe @ninja- has made progress on this issue (removing https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/PipelineUtils.java#L124?).

@md-5 want to weigh in?

**Comment by minecrafter** [comment]
Pushed https://github.com/minecrafter/BungeeCord/tree/epoll-fix and running it on one of my Bungees

**Comment by ninja-** [comment]
@minecrafter you should be fine now without ip tos. but I didn't observe any performance improvements with using epoll.

**Comment by minecrafter** [comment]
@ninja- I observe a mild reduction in CPU usage.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
