### ISSUE TITLE
BungeeCord thinks session servers are still offline

### ISSUE THREAD

**Issue by ItsHarry** [SpigotMC/BungeeCord#1230]
The session servers went offline, and after they came back online, I was getting the error message "Error contacting login servers, are they online?" I tried flushing DNS, tried waiting for over 30 minutes, but only a complete BungeeCord restart fixed the issue.

This was the error I was getting, the IP that is shown does not match the actual IP of sessionserver.mojang.com so I think there is still an address caching issue (#1221):

When I pinged sessionserver.mojang.com from SSH, it was showing the correct IP which is 50.19.211.59, but BungeeCord still thought it was 23.23.154.75 (see error below) until it was restarted.

``` java
14:23:32 [SEVERE] Error authenticating simonstar33 with minecraft.net
io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/23.23.154.75:443
    at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:213)
    at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by SnakeDaoust1232** [comment]
I'm getting the same exact thing. Any resolution?

**Comment by ItsHarry** [comment]
Turn off the default Java DNS cache.

**Comment by SnakeDaoust1232** [comment]
Did that fix the issue you were having?

**Comment by Janmm14** [comment]
This commit removes entry from cache if an error occurred: https://github.com/SpigotMC/BungeeCord/commit/a0f2c42d38aeb768ee7a1d86543eb42ddade7494
If you still have issues that you do not get connection to mojang after mojang servers are back up, you might want to turn off the java dns cache. Not a bungeecord bug (anymore).

**Comment by SnakeDaoust1232** [comment]
I know but how xD I've been searching

**Comment by Janmm14** [comment]
http://docs.oracle.com/javase/6/docs/technotes/guides/net/properties.html#nct

**Comment by SnakeDaoust1232** [comment]
How do i edit my java properties. Im on a debian box. My servers are ran in tmux.

**Comment by SnakeDaoust1232** [comment]
Will my boxes need to be rebooted for this to take effect?

**Comment by SnakeDaoust1232** [comment]
Just to confirm, is this what it needs to look like? https://gyazo.com/380d364ab173729ccd31882bb81eac82

**Comment by SnakeDaoust1232** [comment]
So i tried changing the values to 0 and rebooting both boxes, it didn't seem to work. Currently trying the same thing but just putting hashtags in front of the values. Disabling it entirely.

**Comment by Janmm14** [comment]
You need to set these values in the startup process.
```-D<name>=<value>``` before the ```-jar``` argument while starting up bungeecord. I think.

**Comment by PhanaticD** [comment]
has this issue today
