### ISSUE TITLE
Live adding, removing, enabling, disabling servers

### ISSUE THREAD

**Issue by misiek08** [SpigotMC/BungeeCord#1240]
Is it possible to add to BungeeCord Plugin API and/or command to allow administrators change server config live?
For example I have at average 1000-1500 players and restarting bungeecord to add few lobby servers for minigames is painful.

**Comment by stefan01** [comment]
No, you have to write a custom BungeeCord Plugin. The right way to add a Server in a Plugin is the following:

```
public void addServerToBungee(String name, String adress, String motd, Boolean restricted)
{
		getProxy().getInstance().getServers().put(name, getProxy().getInstance().constructServerInfo(name, net.md_5.bungee.Util.getAddr(adress), motd, restricted));
}
```

Now you can just call the method "addServerToBungee()" to add a new Server.
I didn't test it, but it should work.

**Comment by SysVoid** [comment]
*cough*
https://github.com/SysVoid/Cord

**Comment by Janmm14** [comment]
@SysVoid

> cough
> https://github.com/SysVoid/Cord

You necro'd a very old post, containing a solution already. Also it looks like your post is just advertisment for your project.

**Comment by SysVoid** [comment]
@Janmm14 LOL! Didn't even realise that this was old. I saw 4th and I was like "Totally 4th of November."

Sorry guys, I goofed this time.
