### ISSUE TITLE
[Bug] Logging out in other dimension causes client crash on login (Cauldron/Forge)

### ISSUE THREAD

**Issue by vizerei** [SpigotMC/BungeeCord#1249]
If you go to another dimension, say Galacticraft Asteroids (DIM-30) and log out.  When you log back in you are given the error below.  A Forge based multiplayer server has to register the dimensions with the client.  The packet that does this is described in the Forge changelogs.  It seems that bungeecord is not correctly forwarding this packet.

Crash Log: http://pastebin.com/n7P73mu1

**Comment by Yorkforce** [comment]
Is this issue ever going to be fixed?

Were having serious problems with it on the Sky Factory 2 modpack, which does not have Galacticraft.
