### ISSUE TITLE
Could not connect to default or fallback server, please try again later: java.net.ConnectException 

### ISSUE THREAD

**Issue by MinecraftShqip** [SpigotMC/BungeeCord#1263]
Hello, 
I have tried EVERYTHING to get Bungee to work but it's not. Here's my error: Could not connect to default or fallback server, please try again later: java.net.ConnectException. Now here's my config: 
groups:
  md_5:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: 10
stats: fc9ecafc-a0a2-42f5-80d7-71537760a9d6
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- max_players: 10
  fallback_server: lobby
  host: localhost:25575
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  default_server: lobby
  forced_hosts:
    pvp.md-5.net: pvp
  tab_size: 60
  force_default_server: false
  motd: '&1Another Bungee server'
  query_enabled: false
  query_port: 25577
timeout: 30000
connection_throttle: 4000
servers:
  lobby:
    address: localhost:25565
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
ip_forward: false
online_mode: true

**Comment by YousiFM123** [comment]
How you are fixed it ?

**Comment by YousiFM123** [comment]
Please i need anyone know how to fix it ... i am dieing

**Comment by Janmm14** [comment]
> 
> 
> Please i need anyone know how to fix it ... i am dieing

do not answer on 6 year old issues and instead use spigotmc.org forums for configuration support
