### ISSUE TITLE
BungeeCord still thinks Mojang logins are down after they come up

### ISSUE THREAD

**Issue by Spurlex** [SpigotMC/BungeeCord#1268]
Hi,

I run two Bungeecords and I noticed Mojang was down. After Mojang came back up only one Bungeecord accepted connections. Mojang has been up for 20 minutes now since I have been watching and the Bungeecord is still denying connections.

http://pastebin.com/EGnr7nzA

The other Bungeecord has come up fine.

After restarting the Bungeecord that wasn't accepting connections it works fine.

I have reported this issue before and a fix was added https://github.com/SpigotMC/BungeeCord/issues/1221 but it doesn't seem to work.

**Comment by Spurlex** [comment]
@md-5 This still occurs.

**Comment by TheOnlyRealTGS** [comment]
Happened to me too.
