### ISSUE TITLE
team scoreboard not work and kick to start server

### ISSUE THREAD

**Issue by LionGamer** [SpigotMC/BungeeCord#1273]
if you have a scoreboard on a team with color X (example: gold, blue, red...) and set this "/scoreboard objectives setdisplay sidebar.team.gold objective1" sidebar for the team with that color
you will get instant kicked from the server and you can no longer join before this sidebar scoreboard is no longer displayed for the team with this color.

example:
https://www.youtube.com/watch?v=Ah4TW5SwDWI&feature=youtu.be

**Comment by Phoenix616** [comment]
This problem is still persisting in the latest Spigot 1.8 + Bungeecord. It works fine pure Spigot without Bungeecord so it is definetly a Bungeecord issue.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
