### ISSUE TITLE
[Minecraft Forge 1.8] It login impossible to BungeeCord server.

### ISSUE THREAD

**Issue by BlackYamato** [SpigotMC/BungeeCord#1277]
With the introduction of the Minecraft Forge 1.8, it's not able to log in to BungeeCord server.
Minecraft 1.8 of the standard state is possible log in to the server.

Image of when I logged to the server.
　http://gyazo.com/e93a9a12123407b3fee6507c551491cc

Server Environment:
　・BungeeCord build1020
　・Spigot 1.7.9-R0.2-208-ge0f2e95 (MC: 1.7.10)

BungeeCord (config.yml):
　ip_forward: true

Spigot (spigot.yml):
　bungeecord: true

**Comment by dualspiral** [comment]
Should be fixed in the latest build - @md-5, this can be closed.
