### ISSUE TITLE
BungeeCord Chat: HoverEvent.Action.SHOW_ENTITY missing

### ISSUE THREAD

**Issue by Black-Hole** [SpigotMC/BungeeCord#1300]
HoverEvent.Action.SHOW_ENTITY and it's implementation is missing.

**Comment by games647** [comment]
This issue can be closed now. See [commit](https://github.com/SpigotMC/BungeeCord/commit/fa3678bcdddb2ddbe19e27674498d84cf64270bc#diff-a20b2f85e7838cf5d8df5393e05573c9R22)
