### ISSUE TITLE
Onlinemode true causes high cpu usage

### ISSUE THREAD

**Issue by Darkblader24** [SpigotMC/BungeeCord#1306]
Since Bungeecord Build 1016 the cpu usage is very high at players first join after restart in online-mode true. After reconnect of that user, the cpu doesn't as high as on the first join.

cpu-usage on first join: ~50% for a few seconds
cpu-usage on later joins: ~2%

When tested with online mode false, the cpu doesn't get over 5% on join.

Tested without any plugins, a fresh configuration and one player.

System:
Ubuntu 12.04LTS
Java OpenJDK 7 JDK

Intel Xeon E5-1620v2 @ 4x3,7GHz
64 GB DDR3 ECC 1600MHz

java -Xms4G -Xmx4G -jar BungeeCord.jar

**Comment by Smove** [comment]
remove the native-cipher doesn't help

**Comment by md-5** [comment]
I don't see any actual issue with this:
http://files.md-5.net/s/Yffvut7.png

**Comment by Smove** [comment]
When there isn't any issue, why this is confirmed on 3 machines?
