### ISSUE TITLE
Feature: Disable Plugin

### ISSUE THREAD

**Issue by java3ever** [SpigotMC/BungeeCord#1319]
Hey,

I want to deactive a plugin in Bungeecord, but there isn't a possibility to do that. I wrote this code:
http://hastebin.com/ludaxijola.avrasm to deactive a plugin, maybe it works, maybe not!

**Comment by Zeryther** [comment]
Why don't you submit a Pull Request?

**Comment by java3ever** [comment]
'cause Eclipse hates me and doesn't import Bungee correctly - Switchin' to
Netbeans ATM
Am 21.01.2015 11:43 schrieb "Mehdi B." <notifications@github.com>:
