### ISSUE TITLE
Server is in online mode error

### ISSUE THREAD

**Issue by xNoLo** [SpigotMC/BungeeCord#1321]
Hi so i keep getting a error that my server is in online mode when i checked all of them and there all in offline mode and im not sure what the solution is.
Here is my config
http://pastebin.com/3KpGqpFq 
NOTE i did make sure all servers were in offline mode except the bungee coord server

**Comment by greatman** [comment]
gg at giving your backend ips.

For the real issue, turn ip_forward to true and follow here: http://www.spigotmc.org/wiki/bungeecord-installation/#post-installation

**Comment by xNoLo** [comment]
Oh my gosh i forgot about the ips completely , but thank you for the quick respond and help ive been trying to solve this problem for a bit now and you pretty much solved it.
Ty <3
