### ISSUE TITLE
Occasional crash

### ISSUE THREAD

**Issue by Simo389** [SpigotMC/BungeeCord#1329]
So my proxy is crashing every few hours for no apparent reason.

I only have 40-50 players on, and run 2 or 3 bungeecord plugins that control things like chat.

I'm guessing this is BungeeCord causing this? Although apologies if it's something else.

**Comment by Janmm14** [comment]
Looks like parts of ram are pretty full:

Heap
 PSYoungGen      total 349696K, used 144133K [0x00000000e0000000, 0x0000000100000000, 0x0000000100000000)
  eden space 175104K, 82% used [0x00000000e0000000,0x00000000e8cc15c0,0x00000000eab00000)
  from space 174592K, 0% used [0x00000000eab00000,0x00000000eab00000,0x00000000f5580000)
  to   space 174592K, 0% used [0x00000000f5580000,0x00000000f5580000,0x0000000100000000)
 ParOldGen       total 1048576K, used 1048377K [0x00000000a0000000, 0x00000000e0000000, 0x00000000e0000000)
  object space 1048576K, 99% used [0x00000000a0000000,0x00000000dffce750,0x00000000e0000000)
 PSPermGen       total 23552K, used 23199K [0x000000009ae00000, 0x000000009c500000, 0x00000000a0000000)
  object space 23552K, 98% used [0x000000009ae00000,0x000000009c4a7d08,0x000000009c500000)


Try updating to java 8 as the memory handling is optimized there.

**Comment by Janmm14** [comment]
Oh, just sawn your error log is partly truncatef by multicraft, see the bungeecord log files for the full ones

**Comment by Simo389** [comment]
Ok, thanks for the info. I've updated to java 8, I'll post here with the full logs/errors if it happens again.

**Comment by Simo389** [comment]
The update to 1.8 seems to have solved this, thanks for the suggestion.
