### ISSUE TITLE
ConcurrentModificationException when disabling plugins

### ISSUE THREAD

**Issue by minecrafter** [SpigotMC/BungeeCord#1330]
11:53:17 [SEVERE] Exception in thread "Shutdown Thread" 
    11:53:17 [SEVERE] java.util.ConcurrentModificationException
    11:53:17 [SEVERE]       at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
    11:53:17 [SEVERE]       at java.util.HashMap$KeyIterator.next(HashMap.java:1453)
    11:53:17 [SEVERE]       at com.google.common.collect.AbstractMapBasedMultimap$WrappedCollection$WrappedIterator.next(AbstractMapBasedMultimap.java:486)
    11:53:17 [SEVERE]       at net.md_5.bungee.scheduler.BungeeScheduler.cancel(BungeeScheduler.java:54)
    11:53:17 [SEVERE]       at net.md_5.bungee.BungeeCord$4.run(BungeeCord.java:388)`

**Comment by md-5** [comment]
Version? Didn't *you* fix this somewhat recently?

**Comment by minecrafter** [comment]
I am using the latest BungeeCord, and no, I didn't fix this!

I'll see what I can do about fixing this myself.

**Comment by minecrafter** [comment]
Further details: This ended up being caused by scheduling a task whilst shutting down. I noticed this while shutting down a HikariCP pool. The latest builds do not cause the error to happen.
