### ISSUE TITLE
crash players on switch server lobby -> second server

### ISSUE THREAD

**Issue by x0dus** [SpigotMC/BungeeCord#1332]
how to fix this ?

http://pastebin.com/VqnQv6UK

**Comment by njb-said** [comment]
This looks more like a issue within your servers rather than bungeecord

**Comment by Zeryther** [comment]
"Team DiDi already exists in this scoreboard" says it. There is an error in one of your server plugins, which tries to add a team into a scoreboard, which already exists. That's not a bug of Bungee, as @njb-said already said ;)

**Comment by kamcio96** [comment]
Pluginy nie powinny wysyłać pakietów z teamami od razu przy wejściu na serwer, potrzebna jest krótka przerwa ;) Zmień plugin

Plugins shouldn't send team's packets on join, little break is needed
So change plugin

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
