### ISSUE TITLE
[Bug] Display name cannot be longer than 16 characters

### ISSUE THREAD

**Issue by Spirit55555** [SpigotMC/BungeeCord#1335]
I get this error when I try to add a color to the display name of a player with a username length of 16.

Is there a reason why the display name can't be more than 16 characters?

**Comment by yawkat** [comment]
What error? I believe it's a minecraft limitation.

**Comment by Spirit55555** [comment]
I don't have the same problem in Bukkit, so that's why I'm asking.

**Comment by thinkofdeath** [comment]
Bungee's display name is equal to setPlayerListName in bukkit which also had a 16 character limit in 1.7.10, in 1.8 this limit could be removed but bungee still supports both 1.7.10 and 1.8

**Comment by Spirit55555** [comment]
I only use 1.8, so if I remove the check [here](https://github.com/SpigotMC/BungeeCord/blob/28496e0471237448db017115c769e684ecd76abc/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L190), would it work?

**Comment by thinkofdeath** [comment]
yes

**Comment by Spirit55555** [comment]
The 16 char limit was set because of GLOBAL and GLOBAL_PING tab_list, right? That is disabled and the only other place getDisplayName() is being used, is when running /glist.

So is there a reason why the limit can't be removed?

**Comment by sebastianbinder** [comment]
Is there any "best-practice" way to bypass this limit in my plugin?

**Comment by Janmm14** [comment]
The best practise way is to create a PR to bungeecord.

**Comment by Black-Hole** [comment]
Issue is still valid. I think once the 1.7 support is dropped, this check could be removed, too.

**Comment by sebastianbinder** [comment]
@Thinkofname Is there any update for us in terms of fixing this in those new Bungeecord releases for 1.9?

**Comment by md-5** [comment]
^^

**Comment by sebastianbinder** [comment]
@md-5 Great man! That was within a minute!!! xD
