### ISSUE TITLE
BungeeCord not connecting to backend servers on private network. 

### ISSUE THREAD

**Issue by soulcedric** [SpigotMC/BungeeCord#1337]
Hello, I rent two servers connected by a private network on the same rack at my host. I am unable to connect to my backend servers hosted on the remote machine using BungeeCord and my private network IP.

I binded the backends to the local IP address provided to us, and nmap on the front end machine was showing the port being open on the local address (backend), however Bungee was unable to reach our backend IP/port.

**Comment by md-5** [comment]
Can you provide more info such as error messages.

**Comment by forairan** [comment]
Tried turning off "bind_local_address" in the Bungee config? We had this same issue back in mid-2013 and came to find out that having that option on means that Netty tries to force use of the public network interface, preventing communications over the private network.
