### ISSUE TITLE
Bungeecord offline, online issue

### ISSUE THREAD

**Issue by greeves12** [SpigotMC/BungeeCord#1339]
Ok, I know I know you need the damn thing in offline mode, but why? I have seen lots of other servers that use bungeecord and have online servers. So how is that possible, I have messed with every option in the config still you need offline, wtf. If there is any possible way I could make my server online that would be fantastic or can I have the source code and do it myself?

**Comment by Absentee23** [comment]
bungeecord should be in online mode with ip forwarding enabled, and spigot should be in offline mode. read the wiki.

**Comment by HeroCC** [comment]
Follow this guide:http://www.spigotmc.org/wiki/bungeecord-ip-forwarding/ 

Then set online to false in your Spigot instance, then set bungee-cord to true. In bungee, change online to true, and your server will be in online mode and forward UUIDs.
