### ISSUE TITLE
Severe Exception in Main - multiple servers but works with just one 

### ISSUE THREAD

**Issue by lumber2323** [SpigotMC/BungeeCord#1340]
Ok so my bungee works good when i have just for example one server connected to it like lets say a Lobby server. But when I try and connect multiple servers like Hub, Prison, KitPvP here is what I get from the console and here is my config thank you for the time! 

CONSOLE 

23.01 10:27:59 [Server] SEVERE Exception in thread "main" 
23.01 10:27:59 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
23.01 10:27:59 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
23.01 10:27:59 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
23.01 10:27:59 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
23.01 10:27:59 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
23.01 10:27:59 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
23.01 10:27:59 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
23.01 10:27:59 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
23.01 10:27:59 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
23.01 10:27:59 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
23.01 10:27:59 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
23.01 10:27:59 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
23.01 10:27:59 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"28496e0":1036
23.01 10:27:59 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
23.01 10:27:58 [Multicraft] Loaded config for "Default"
23.01 10:27:58 [Multicraft] Starting server!
23.01 10:27:58 [Multicraft] Loading server properties
23.01 10:27:58 [Multicraft] Server stopped
23.01 10:27:58 [Multicraft] Server shut down
23.01 10:27:58 [Multicraft] Received restart command
23.01 10:27:58 [Server] INFO Saving chunks for level 'world'/Overworld
23.01 10:27:58 [Server] INFO Saving worlds
23.01 10:27:58 [Server] INFO Saving players
23.01 10:27:58 [Server] INFO Stopping server
23.01 10:27:58 [Server] INFO Saving chunks for level 'world_the_end'/The End
23.01 10:27:58 [Server] INFO Saving chunks for level 'world_nether'/Nether
23.01 10:27:58 [Server] INFO Saving chunks for level 'world'/Overworld
23.01 10:27:58 [Server] INFO Saving worlds
23.01 10:27:58 [Server] INFO Saving players
23.01 10:27:58 [Server] INFO Stopping server
23.01 10:27:58 [Server] INFO CONSOLE: Stopping the server..
23.01 10:27:58 [Server] INFO CONSOLE: Forcing save..
23.01 10:27:58 [Multicraft] Stopping server!
23.01 10:27:58 [Multicraft] Received restart command
23.01 10:25:39 [Multicraft] Loading server properties
23.01 10:24:45 [Server] INFO World saved.
23.01 10:24:45 [Server] INFO CONSOLE: Forcing save..
23.01 10:24:45 [Server] INFO CONSOLE: Enabled level saving..
23.01 10:24:45 [Multicraft] Auto-saving world...
23.01 10:14:37 [Server] INFO World saved.
23.01 10:14:37 [Server] INFO CONSOLE: Forcing save..
23.01 10:14:37 [Server] INFO CONSOLE: Enabled level saving..
23.01 10:14:37 [Multicraft] Auto-saving world...
23.01 10:04:29 [Server] INFO World saved.
23.01 10:04:28 [Server] INFO CONSOLE: Forcing save..
23.01 10:04:28 [Server] INFO CONSOLE: Enabled level saving..
23.01 10:04:28 [Multicraft] Auto-saving world...
23.01 10:01:59 [Disconnect] User /198.27.83.157:47406 has disconnected, reason: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
23.01 09:54:20 [Server] INFO World saved.
23.01 09:54:20 [Server] INFO CONSOLE: Forcing save..
23.01 09:54:20 [Server] INFO CONSOLE: Enabled level saving..
23.01 09:54:20 [Multicraft] Auto-saving world...
23.01 09:44:12 [Server] INFO World saved.
23.01 09:44:12 [Server] INFO CONSOLE: Forcing save..
23.01 09:44:12 [Server] INFO CONSOLE: Enabled level saving..
23.01 09:44:12 [Multicraft] Auto-saving world...
23.01 09:34:04 [Server] INFO World saved.
23.01 09:34:04 [Server] INFO CONSOLE: Forcing save..
23.01 09:34:04 [Server] INFO CONSOLE: Enabled level saving..
23.01 09:34:04 [Multicraft] Auto-saving world...
23.01 09:23:56 [Server] INFO World saved.
23.01 09:23:56 [Server] INFO CONSOLE: Forcing save..
23.01 09:23:56 [Server] INFO CONSOLE: Enabled level saving..
23.01 09:23:56 [Multicraft] Auto-saving world...
23.01 09:22:34 [Server] INFO CONSOLE: Opped lumber2323
23.01 09:13:48 [Server] INFO World saved.
23.01 09:13:48 [Server] INFO CONSOLE: Forcing save..
23.01 09:13:48 [Server] INFO CONSOLE: Enabled level saving..
23.01 09:13:48 [Multicraft] Auto-saving world...
23.01 09:03:52 [Server] Startup Done (1.638s)! For help, type "help" or "?"
23.01 09:03:52 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
23.01 09:03:52 [Server] INFO Preparing start region for level 2 (Seed: -277658391526779302)
23.01 09:03:51 [Server] INFO Preparing start region for level 1 (Seed: -277658391526779302)
23.01 09:03:51 [Multicraft] Skipped 81 lines due to rate limit (30/s)
23.01 09:03:50 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
23.01 09:03:50 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16
23.01 09:03:50 [Server] INFO Wheat Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Sapling Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Pumpkin Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Mushroom Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Melon Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Cane Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Cactus Growth Modifier: 100%
23.01 09:03:50 [Server] INFO Nerfing mobs spawned from spawners: false
23.01 09:03:50 [Server] INFO Replace Blocks: [1, 5]
23.01 09:03:50 [Server] INFO Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
23.01 09:03:50 [Server] INFO Engine Mode: 1
23.01 09:03:50 [Server] INFO Anti X-Ray: true
23.01 09:03:50 [Server] INFO Mob Spawn Range: 4
23.01 09:03:50 [Server] INFO -------- World Settings For [world] --------
23.01 09:03:50 [Server] INFO Preparing level "world"
23.01 09:03:50 [Server] INFO **** Beginning UUID conversion, this may take A LONG time ****
23.01 09:03:50 [Server] WARN To change this, set "online-mode" to "true" in the server.properties file.
23.01 09:03:50 [Server] WARN While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
23.01 09:03:50 [Server] WARN The server will make no attempt to authenticate usernames. Beware.
23.01 09:03:50 [Server] WARN **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
23.01 09:03:50 [Server] INFO Starting Minecraft server on 76.164.208.106:25565
23.01 09:03:50 [Server] INFO Generating keypair
23.01 09:03:50 [Server] INFO Using 4 threads for Netty based IO
23.01 09:03:50 [Server] INFO Server Ping Player Sample Count: 12
23.01 09:03:50 [Server] INFO This server is running CraftBukkit version git-Spigot-1544 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
23.01 09:03:50 [Server] INFO Default game type: SURVIVAL
23.01 09:03:50 [Server] INFO Loading properties
23.01 09:03:50 [Server] INFO Starting minecraft server version 1.7.10
23.01 09:03:40 [Multicraft] Loaded config for "Spigot"
23.01 09:03:40 [Multicraft] Starting server!
23.01 09:03:40 [Multicraft] Loading server properties
23.01 09:03:40 [Multicraft] Server stopped
23.01 09:03:40 [Multicraft] Server shut down
23.01 09:03:40 [Server] INFO Saving chunks for level 'world'/Overworld
23.01 09:03:40 [Server] INFO Saving worlds
23.01 09:03:40 [Server] INFO Saving players
23.01 09:03:40 [Server] INFO Stopping server
23.01 09:03:40 [Server] INFO Saving chunks for level 'world_the_end'/The End
23.01 09:03:40 [Server] INFO Saving chunks for level 'world_nether'/Nether
23.01 09:03:39 [Server] INFO Saving chunks for level 'world'/Overworld
23.01 09:03:39 [Server] INFO Saving worlds
23.01 09:03:39 [Server] INFO Saving players
23.01 09:03:39 [Server] INFO Stopping server

CONFIG 

groups:
  lumber2323:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: -1
stats: 4df4a244-53ae-435c-84bb-7027d3321171
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- query_port: 25577
  motd: '&7MayhemPvP&bNetwork &a Join us @ mayhempvp.net'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  default_server: lobby
  bind_local_address: true
  fallback_server: lobby
  host: 76.164.208.106:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
timeout: 30000
connection_throttle: 4000
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 192.99.25.248:25565
    restricted: false
ip_forward: false
online_mode: true
  prison:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 72.46.154.77:25565
    restricted: false
ip_forward: false
online_mode: true

**Comment by lumber2323** [comment]
<p> groups:
  lumber2323:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: -1
stats: 4df4a244-53ae-435c-84bb-7027d3321171
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- query_port: 25577
  motd: '&7MayhemPvP&bNetwork &a Join us @ mayhempvp.net'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  default_server: lobby
  bind_local_address: true
  fallback_server: lobby
  host: 76.164.208.106:25565
  max_players: 100
  tab_size: 60
  force_default_server: false
timeout: 30000
connection_throttle: 4000
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 192.99.25.248:25565
    restricted: false
ip_forward: false
online_mode: true
  prison:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 72.46.154.77:25565
    restricted: false
ip_forward: false
online_mode: true
  </p>

**Comment by portalBlock** [comment]
It seems that you went from a spigot server(Backend) to a bungee server(Multicraft messes that up often). 

I would say do this as it says to do:
"23.01 10:01:59 [Disconnect] User /*.*.*.*:47406 has disconnected, reason: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!"

And make sure that when you connect you are not connecting to a backend instance but the bungee (do /bungee to check).

**Comment by lumber2323** [comment]
So i should turn bungee to false in my spigot.yml? I have had the same issue even when it was false.

**Comment by portalBlock** [comment]
No turn it to true and set ip_forward true in bungee.yml.

**Comment by lumber2323** [comment]
Still broken

**Comment by lumber2323** [comment]
I still get the console message 

02.02 09:42:00 [Server] SEVERE Exception in thread "main"
