### ISSUE TITLE
[SEVERE] Error In Config

### ISSUE THREAD

**Issue by computerkiller** [SpigotMC/BungeeCord#1341]
I keep getting the following in my console - \

18:34:27 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
18:34:27 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"e68ed48":1038
18:34:28 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
18:34:28 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
18:34:28 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
18:34:28 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
18:34:28 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
18:34:28 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
18:34:28 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"e68ed48":1038 by SpigotMC
18:34:28 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"e68ed48":1038 by SpigotMC
18:34:28 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"e68ed48":1038 by SpigotMC
18:34:28 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"e68ed48":1038 by SpigotMC
18:34:28 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"e68ed48":1038 by SpigotMC
18:34:28 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"e68ed48":1038 by SpigotMC
18:34:28 [SEVERE] Exception in thread "main" 
18:34:28 [SEVERE] mapping values are not allowed here
 in 'reader', line 55, column 11:
      minotaur:
              ^

18:34:28 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:143)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:226)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:155)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
18:34:28 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
18:34:28 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:61)
18:34:28 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:59)
18:34:28 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:234)
18:34:28 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:50)
18:34:28 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by computerkiller** [comment]
Here is my config? I'm sort of a noob with this stuff.

http://pastebin.com/eBNqthwX

**Comment by computerkiller** [comment]
Please Help!

**Comment by minecrafter** [comment]
GitHub help is not instant and you should have posted on the forums.

The "minotaur" server section is misplaced.
