### ISSUE TITLE
Ip fowarding problem

### ISSUE THREAD

**Issue by bros1083** [SpigotMC/BungeeCord#1342]
My server turns on perfectly and I can log in. But when I do /server Factions it says Ip-Fowarding in you config. So I do that, then I restart. I press join server. Then it waits at "Logging in" then after 30 seconds it says Disconnect. I do have 1 ip with Infinate ports and also ITs a dedicated server with 24 GB ram, and a dual core Zeon procesor so Its not crappy. lol. Please help

**Comment by bros1083** [comment]
Also please note only after I do Ip fowarding true.

**Comment by bros1083** [comment]
I tried multiple times as well.

**Comment by njb-said** [comment]
You need to enable bungee cord in your spigot config

**Comment by CodeLuca** [comment]
*Facepalm*

**Comment by LukeyBoyIsXen** [comment]
That Zeon processor doe...
