### ISSUE TITLE
BungeeCord & TeleportSigns

### ISSUE THREAD

**Issue by Matroyzy** [SpigotMC/BungeeCord#1343]
Hello, I can only teleport back to my spawn with Teleportsigns, but i can't teleport from spawn to the survival server :S

I can teleport when I'm OP tho :S 
I've followed the tutorial step by step and I still can't use the sign to teleport to my offline-set server :S 

Please help me! :'(

This might help, idk:
*Bongee online-mode set to true
*Bongee Default fallback server online-mode set to false
*Survival server online-mode set to false.

""I can Teleport from Survival server to 'Bongee Default Fallback Server' but not otherwise.

*I can teleport from both when I'm an OP.
*I posted this thread on Bukkit Forums (I'm Running Spigot 1.8) and they said:
"We do not support offline servers"

But it has to work in any way? :S 
Can i tell them to teleport using any command? something?

Please, I'll love u forever if u help me, I can't stand working on this issue no longer :'(

**Comment by Matroyzy** [comment]
**EDIT**

Found out "/server <name>" worked.
But the Teleportsigns, any way? anyone?

**Comment by minecrafter** [comment]
Make sure you're connecting to BungeeCord, if that doesn't help take it up with the author of the plugin.

**Comment by Matroyzy** [comment]
I got it working on one server now, no idea how i did it tho :S

**Comment by Matroyzy** [comment]
But another ain't working to teleport to
