### ISSUE TITLE
Please add IP-Ban fuction in BungeeCord to avoid attack

### ISSUE THREAD

**Issue by skycatcher** [SpigotMC/BungeeCord#1346]
Today my friend use Minecraft-protocol's flaw, imitation lots of fake players to connect and disconnect my server by a software. and I found my bungeecord-proxy spam a lot of connecting information(like the image)
![bungee](https://cloud.githubusercontent.com/assets/7446220/5921905/34ca7a7c-a682-11e4-8f31-2a691e5e45af.png)
More and more fake players use lots of memory and CPU resources, and after few minutes, the bungeecord crashed.... 
Infact I set connection_throttle: 2000 in config.yml, but It seems in vain, I don't know whether this is related to Minecraft-protocol, and the attacker are fake players.
So I suggest that the BungeeCord may add an IP-Ban function? or limit the connections with same IP in short time.
By the way, could you please add a function that verify join players' name by regular?

**Comment by njb-said** [comment]
A limit on connections per IP would be a good addition to bungee.
I think there might be a resource on the forums that does something like this though.

**Comment by portalBlock** [comment]
Since this is happening on the InitialHandler there is not much you can do, best thing would be to see if your server OS supports IP rate limiting. Example for linux based servers: http://unix.stackexchange.com/questions/139285/limit-max-connections-per-ip-address-and-new-connections-per-second-with-iptable

**Comment by kamcio96** [comment]
In 99% of cases connections are from proxy, so it is unless.

Plugin is good idea for it ;)

**Comment by minecrafter** [comment]
How about not running an offline mode server? That significantly reduces your vectors of attack (although there are public alts out there, but it's a rather limited pool).

**Comment by skycatcher** [comment]
Actually I used Windows Server 2012r2, so I don't know how to limit IP rate like linux.

**Comment by njb-said** [comment]
@skycatcher why not use linux, there are loads of positives in switching
