### ISSUE TITLE
Please update netty. https://github.com/netty/netty/pull/3264

### ISSUE THREAD

**Issue by anyperson** [SpigotMC/BungeeCord#1347]
https://github.com/netty/netty/pull/3264

I tried to update, but I think I broke the protocol...
https://gist.github.com/anyperson/5edcb1e8a13d32591fa4

**Comment by yawkat** [comment]
Why is this update necessary?

**Comment by anyperson** [comment]
I put the profiler and it is this problem causes problems with memory, I can make a screenshot of tomorrow, in full load bungeecord, if needed.

**Comment by anyperson** [comment]
http://s16.postimg.org/ksbx9axr7/124124124124.jpg

**Comment by anyperson** [comment]
http://s21.postimg.org/b4xxr3gg6/214124124.jpg

http://s11.postimg.org/8egzb02xu/421414.jpg

**Comment by md-5** [comment]
wat.

We don't even use composite byte bufs. How do you know this netty update changes anything?

**Comment by md-5** [comment]
Also 172 megabytes is hardly extreme memory usage......

I think that you don't know how to use a profiler

**Comment by anyperson** [comment]
Sorry, do not know why bungeecord use all my memory w/o plugins.

**Comment by md-5** [comment]
How much is "all your memory". The screenshots you have don't show anything significant. You can run BungeeCord just fine: java -Xmx512M -jar BungeeCord.jar

**Comment by anyperson** [comment]
java -jar -Xss228k -Xmx9G -Djline.terminal=jline.UnsupportedTerminal BungeeCord.jar

Sometimes uses more 7-8 GB and then the process of GC use 300-600% CPU. Sorry if the ticket is wrong, just do not know where to look, you can tell me. Thank you.

**Comment by yawkat** [comment]
Why are you giving bungee 9GB of ram? that's insane.

**Comment by anyperson** [comment]
Do you think this is the problem?

**Comment by yawkat** [comment]
Yes

**Comment by anyperson** [comment]
Thank you very much, I'll try on the recommendation of md-5. java -Xmx512M -jar BungeeCord.jar
