### ISSUE TITLE
BungeeCord 1.8 (Connection Exception)

### ISSUE THREAD

**Issue by CDSnipez** [SpigotMC/BungeeCord#1349]
I recently have bungeecorded 2 servers. One is acting as a Hub/Prison server while the other one is a factions server. When i connect through the bungee proxy, I appear in the Prison server. When I perform /server factions it tries to log in and says: "Downloading Terrain." After a while, I'm disconnected from it and sent back to the prison server. The console shows me logging in, displays my UUID, and the Proxy IP. Then after trying to connect again, I'm given this error: http://gyazo.com/2cd93b22ff2740c4af07417ba879562e

One time the factions server actually crashed for no reason and spewed out tons of errors. Listed here: http://pastebin.com/HA2qutuL

I've tried all morning to look for an answer and I couldn't find it. I'm using the latest build of spigot and the latest build of BungeeCord. Also, both servers connection throttle is set to -1. I can log into the factions server using the normal IP, but I cannot connect using the Proxy. It's really frustrating, as the past few days, my dev has tried doing bungeecord to no avail, and now it works only slightly.

Any help is greatly appreciated. 

Thanks

**Comment by minecrafter** [comment]
28.01 03:33:10 [Server] ERROR com.gmail.logout400.Heads.listeners.HeadsUpdateListener.onPlayerJoin(HeadsUpdateListener.java:31)
    28.01 03:33:10 [Server] ERROR com.gmail.logout400.Heads.util.PluginVersion.updateNeeded(PluginVersion.java:35)

Figure it out from here.

**Comment by CDSnipez** [comment]
Thank you for pointing this out :). I guess we'll see if it works or not
