### ISSUE TITLE
Crash, unable to connect issue

### ISSUE THREAD

**Issue by Scrufdog** [SpigotMC/BungeeCord#1352]
Server was up and running just fine using #1039 for about 4 days. Noticed no one had logged on the entire day. Tried to login and received the message, Unable to connect, are login servers down?

Tried again, same error. Logged into a different server, no problem, meaning minecraft Auth servers were fine, and client side was fine. Checked bungeecord log and found this...

http://pastebin.com/qUu6STM8

Restarted bungeecord and i was able to connect right in. Looked back into the log files and found out it had been erroring out all day when people tried to connect. 

Found a different error a bit back in the log on connection attempt. Changed the player's name to PlayerName in the log...

http://pastebin.com/BpteGb9S

Ideas?

Thanks

**Comment by greatman** [comment]
It happens when mojang's auth server derps. For some reason, bungee can't connect after that. A restart usually fix it.
