### ISSUE TITLE
Could not authenticate with mojang.net timed out

### ISSUE THREAD

**Issue by PhanaticD** [SpigotMC/BungeeCord#1355]
The error in the title just happened to me, and the session servers were not actually down. I restarted bungee and it was immediately fixed.

**Comment by LaxWasHere** [comment]
^ Happened to me earlier.

**Comment by PhanaticD** [comment]
actually i think the session servers might have just gone down

**Comment by LaxWasHere** [comment]
Well, I was able to login on other servers but I couldn't on mine until I restarted bungee.

**Comment by Spurlex** [comment]
https://github.com/SpigotMC/BungeeCord/issues/1268

**Comment by Theepwner** [comment]
Same here: http://www.spigotmc.org/threads/bungeecord-error-authenticating-name-with-minecraft-net.47785/#post-538207

Though my issue was a bit different.  Restarting bungee did not fix immediately.

**Comment by cybertiger** [comment]
Java caches DNS lookups forever if a securitymanager is set.

Workaround: add -Dnetworkaddress.cache.ttl=60 to your bungee startup.

**Comment by PhanaticD** [comment]
@cybertiger this actually does not work, and it is by default in newer versions set to 30 seconds, read more here: http://stackoverflow.com/questions/1256556/any-way-to-make-java-honor-the-dns-caching-timeout-ttl

**Comment by Harry5573** [comment]
Same happened here. Session servers went down, could not connect to any server Bukkit or Bungee. They came back, could connect to Bukkit servers just fine, but still could not connect to bungee until rebooting the it.

**Comment by thinkofdeath** [comment]
#1268
