### ISSUE TITLE
UUIDs in the config.yml

### ISSUE THREAD

**Issue by TheOnlyRealTGS** [SpigotMC/BungeeCord#1356]
Some might say that we should use UUIDs now that you can change your name in the bungee config.

**Comment by johnnywoof** [comment]
I would like this as well.

**Comment by johandrex** [comment]
Same

**Comment by Janmm14** [comment]
Because of the possiblity to change Minecraft usernames, the bungeecord config's permissions part should accept both names and uuids for now, with a hint that uuids should be used.

**Comment by TheOnlyRealTGS** [comment]
Yeah, sorry I was lazy.

**Comment by Techcable** [comment]
Another possibility would be to accept both usernames and uuids and auto-convert to uuids.
This would allow users to manually edit the config file, while maintaining the uniqueness of accounts.

**Comment by kamcio96** [comment]
#1436

**Comment by Phineas-0510** [comment]
Great idea, I would like this as well @md_5

**Comment by Phineas-0510** [comment]
@md-5 **

**Comment by Nubebuster** [comment]
I was about to report this. The names are CaSe SenSitive aswell. Very annoying as my staff likes to fuck around with capatalizations

**Comment by Techcable** [comment]
@Nubebuster 
Automatically converting to UUIDs would handle the case sensitivity issue.
Requesting these examples from mojang:
- ['TECHCABLE'](https://api.mojang.com/users/profiles/minecraft/TECHCABLE)
- ['techcable'](https://api.mojang.com/users/profiles/minecraft/techcable)
- ['tEChcABLe'](https://api.mojang.com/users/profiles/minecraft/tEChcABLe)
All return:
````json
{"id":"613517d731bb47bdbc337870d4f3adc5","name":"Techcable"}
`````

As you can see this will fix multiple issues.

**Comment by kamcio96** [comment]
if we talking about premium accounts, it doesn't matter. Mojang doesn't change theirs uuids, so they can change their username freely. 

Issue should be closed.

**Comment by TheOnlyRealTGS** [comment]
@kamcio96
This was not the point of the ticket. The point was to be able to use uuids instead of the old name system in the bungee configuration file.
If this isn't already implemented I don't see the reason to close this ticket.

**Comment by kamcio96** [comment]
https://github.com/SpigotMC/BungeeCord/commit/81d1c46a0dd5505ab8b78c1f54b13f5353e36b41

**Comment by TheOnlyRealTGS** [comment]
Ah sweet thank you!
