### ISSUE TITLE
BungeeCord not passing on correct UUID's after username changes.

### ISSUE THREAD

**Issue by Simo389** [SpigotMC/BungeeCord#1358]
So I'm running Bungeecord with 'ip_forward: true' and have been doing so for a while.

It looks like when a user changes their username, when using 'player.getUniqueId()' in Bukkit plugins, a new UUID is generated - it doesn't pass the correct one.

This looks like a pretty major bug to me, as it breaks any plugins using this 'getUniqueId()' method for players that have changed their usernames. Please fix ASAP, querying the Mojang API directly isn't an option as I get blacklisted within minutes due to too many requests - even with my own 24 hour cache system.

**Comment by yawkat** [comment]
This sounds very much like you have offline mode somewhere in the chain. Make sure bungee is online mode and ip forwarding is functioning properly. Please also attach sample uuids.

**Comment by Shevchik** [comment]
You didn't set bungeecord to true in spigot yml config

**Comment by Simo389** [comment]
Looks like this is an issue with the cache I'm using, my apologies.
