### ISSUE TITLE
Severe Exception in Main - multiple servers but works with just one #2

### ISSUE THREAD

**Issue by lumber2323** [SpigotMC/BungeeCord#1360]
This is a second to my issue that was closed incorrectly i think
https://github.com/SpigotMC/BungeeCord/issues/1340

Follow up from the last post by a helper

Still is not fixed I recieve the error still

**Comment by Dead-i** [comment]
Hi,

ip_forward and online_mode need to go **once** at the **very bottom** of your config.yml, and not for each server. Please amend your configuration accordingly and try again.

Additionally, the GitHub issues section is not meant to be a support section, and is meant for serious bugs with BungeeCord. Therefore, please can I ask that you ask any further questions on either the Spigot Forums or on IRC?

https://irc.spi.gt/iris
