### ISSUE TITLE
#1042

### ISSUE THREAD

**Issue by cuddylier** [SpigotMC/BungeeCord#1362]
Hi

Build 1042 shows this error on startup: http://pastie.org/private/bn7b9z3n6yelixafwulova

Deleting those files from /tmp did not help.

**Comment by cuddylier** [comment]
Build 1040 works fine.

**Comment by yawkat** [comment]
Try installing zlib

**Comment by cuddylier** [comment]
What is the apt-get on ubuntu for it? It isn't apt-get install zlib

**Comment by yawkat** [comment]
zlib1g

**Comment by cuddylier** [comment]
It says that is already installed.

**Comment by yawkat** [comment]
no idea then

**Comment by chdxD1** [comment]
I do get the same when compiling BungeeCord on a Ubuntu 14.04.1 LTS machine (Linux **** 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux).

It does happen when the tests for BungeeCord-Native are running. 
http://paste.md-5.net/bexagabado.txt

zlib1g and also zlib1g-dev (however should not matter) are installed.

**Comment by chdxD1** [comment]
Just a small update: I compiled the native libs with stdlib and it worked for me.
