### ISSUE TITLE
Error has occured while contacting login servers, are they down?

### ISSUE THREAD

**Issue by ajbboy123** [SpigotMC/BungeeCord#1363]
Every 12-36 Hours, when I try and join the Network, it says "Error has occured while contacting login servers, are they down?"

I have to reboot the Bungee Server for it to let me and any other users login again.

And I know this isn't a Mojang sided Issue, cause the Servers all Online, cause I can join other MC Networks. People have always been saying this isn't a Bungee Issue, well it only has happened when I have a Bungee Server/Network.... So... Yeah, Please help me. 

Thanks in Advance

**Comment by md-5** [comment]
Update bungee
