### ISSUE TITLE
Error - packet-encoder

### ISSUE THREAD

**Issue by MrWakeCZ** [SpigotMC/BungeeCord#1366]
Hi,
I have big server 800+ slots and if players are connecting in the BungeeCord console is this error. 
http://pastebin.com/w9R3BKei after all players get huge lags.

Bungeecord #1045, development
Plugins: BungeeYAML, BungeeStatus, UltimateBungee, BungeeAuthMeBridge, AnimatedMOTD, AdressLimit, OphionProtection, Yamler

Thanks :X

**Comment by AnodyneEntity** [comment]
Backdate to 1044, it's an encoding issue.

**Comment by Janmm14** [comment]
Maybe here is the reason for that issue: https://github.com/OvercastNetwork/BungeeCord/commit/2b06ebc7508ed385e0d3f4131b248856f4d378c5

**Comment by md-5** [comment]
"ignoring" is generally not a fix @Janmm14

**Comment by Janmm14** [comment]
@md-5 I just meant that this could be the reason, I did not want to say that ignoring helps.
> // Sometimes packet-encoder is not in the pipeline, probably when the client disconnects soon after connecting

**Comment by JamesHooks90** [comment]
So?

**Comment by Xayanix** [comment]
Same here.

**Comment by md-5** [comment]
#1489

**Comment by Xayanix** [comment]
Fixed by md-5 in newest build.

**Comment by JamesHooks90** [comment]
I will check it :) Thanks
