### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by SaroxDE** [SpigotMC/BungeeCord#1371]
Hello,
when i try to login i get this error:

04:54:12 [SEVERE] Error authenticating SaroxDE with minecraft.net
io.netty.handler.timeout.ReadTimeoutException

But i have this only at my bungeecord server.

**Comment by md-5** [comment]
Fix your connection to the Mojang servers and check they are up

**Comment by SaroxDE** [comment]
And i i can fix them ?

**Comment by bcurtiswx** [comment]
How do you "Fix your connection to the Mojang servers" on BungeeCord ?

**Comment by Janmm14** [comment]
This is no bungeecord error but either mojang servers are down or your server can't access them for some reason.
Did you tried updating to the lastest BungeeCord version? BungeeCord recently started to clear the address cache if a connection failed.
