### ISSUE TITLE
Internal Server Error when not using Vanilla Launcher

### ISSUE THREAD

**Issue by tr0nlegacy2012** [SpigotMC/BungeeCord#1376]
Hello,

My name is tyler and I am the owner of the Tronopolis Modded Server Network. I have been trying to setup a multi-pack bungee/hub for some time. I can connect to the hub fine via the vanilla launcher, but as soon as I log into a launcher with mods (which shouldn't affect the ability to join a vanilla server), it instantly kicks me with an "Internal Server Error" 
 Note:
All servers are on the same box. 

Versions:
ModSauce/SkyFactory/DireWolf20 1.7.10 running Cauldron-MCPC-Plus version git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT). Spigot: This server is running CraftBukkit version git-Spigot-1646 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT) and Spigot version: BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"62981e4":1049 by md_5

Config.yml of bungee: https://pste.me/#/bungee

in spigot.yml, bungee = true ; 

If you need anymore information, please let me know.
Hope to find an issue.

**Comment by Janmm14** [comment]
It just says "Internal server error." Nohing more? Anything in the console? Does it work without bungee inbetween?

**Comment by tr0nlegacy2012** [comment]
I am able to connect without the bungee, nothing notable in console. Just internal server error.

**Comment by md-5** [comment]
Insufficient info
