### ISSUE TITLE
Offline Mode: You are already connected to this server!

### ISSUE THREAD

**Issue by TagCraftMC** [SpigotMC/BungeeCord#1382]
I have updated everything to the latest and the issue still persists(#1381)
BungeeCord Version: "e1951c5":1050 (0 Plugins)
Client Version: Tested with 1.8.3 (vanilla) and 1.8.1 (vanilla)
Server Versions: Spigot 1.8 R0.1 6ee12f6-33de3 (0 Plugins, bungeecord: true)
Bungee Config: http://pastebin.com/8Vnc88wx (config regenerated) 
Bungee Log: http://pastebin.com/xYDQyD66
Screenshot of consoles + Clients: http://i.gyazo.com/5806498fbc96b89afc734fa48669e4b4.png (the client with "Connection Lost" was the original/first client on bungeecord)

To re-cap on what was said in #1381 , Chalkie is connected to a server in bungee, another player attempts to connect as Chalkie as well, both players are kicked or the original Chalkie is kicked and the second Chalkie is able to join.
This issue was not present in BungeeCord #1045 but became an issue in #1048 (#1046)

I hope this is now sufficient information md_5. Please let me know if there is anything else that is needed.
Thanks.

**Comment by md-5** [comment]
>online_mode: false

This will not work with 1.8.3 due to a bug in the 1.8.3 client. Downgrade your client, or enable online mode.

**Comment by TagCraftMC** [comment]
If it's an issue with the client, why did the issue appear after the bungee #1045 update?
When using bungee #1045 and 1.8.3 client, it works correctly, only when update bungee paste  #1045 is the issue present.
Screen shot of running 1.8.3 clients, 1.8 servers and 1045 bungee with it working correctly.
http://gyazo.com/c0c4d397d8f1720f44c6f7112f197ecb
I think the issue may lye in the recent commit found here: https://github.com/SpigotMC/BungeeCord/commit/3776feb559f1b79eb47625beef8a29ce75323ed3

**Comment by md-5** [comment]
@TagCraftMC I thought this was describing a different issue, this one has been fixed. I am however curious as to why you are stealing Mojang's work, offline mode should really just be removed....

**Comment by LaxWasHere** [comment]
^ nobody is stopping you md_5, simply open your IDE. :+1:

**Comment by TagCraftMC** [comment]
My apologizes for not sufficiently describing the issue and thank you for fixing it.
