### ISSUE TITLE
Connect twice to the same bungee instance

### ISSUE THREAD

**Issue by MichelDeStar** [SpigotMC/BungeeCord#1383]
Since the new version, 1051, it is possible to have on a offline server have one player twice.

If someone is online in for example a creative server, and a new player joins with the same name, they are both able to play, the freshly joined player won't receive a kick with already connnected.

**Comment by yawkat** [comment]
Do they have different case in their name or something?

**Comment by MichelDeStar** [comment]
Nope, exactly the same name.
