### ISSUE TITLE
Bungeecord stopped letting Players in

### ISSUE THREAD

**Issue by McLive** [SpigotMC/BungeeCord#1390]
Suddenly, Bungeecord doesn't allow new connections. There are no errors in the console, you simply can't connect to port 25565. (http://img.mclive.eu/20150306145727.png)

There are still players connected but glist shows the wrong playercounts.

Connected to skyblock: "There are 12 out of maximum 200 players online."

glist says: skyblock: 18

I've got a profiler report. Download: http://www.mclive.eu/profiler/Bootstrap-2015-03-06.snapshot (YourKit Java Profiler)

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"e6da9cb":1040 by md_5

**Comment by McLive** [comment]
Just happened again.

**Comment by McLive** [comment]
And again. Anyone?

**Comment by md-5** [comment]
<McLive> does anyone reply to bungeecord tickets?

No, because generally they are not bugs in Bungee, but rather bugs in your software or configuration.

In this case, FreeCraftNames (your plugin) is locking up Bungee with HTTP connections.
