### ISSUE TITLE
My BungeeCord is not pinging but its working please help mc: 1.7.5

### ISSUE THREAD

**Issue by Raymart23** [SpigotMC/BungeeCord#1395]
my server is hosted by shockbyte and the servers at bungeecord is spigot
kindly help me when im pinging the server its not working 

Console : http://pastebin.com/kpRnHvYd

my server is pinging within 30-35 seconds help mehhh

**Comment by tf101-wizard** [comment]
Update Minecraft......

**Comment by Janmm14** [comment]
I suggest @md-5 or @thinkofdeath should close thiscause of the date @Katelyn-SN
