### ISSUE TITLE
Error with Ping Handler

### ISSUE THREAD

**Issue by AnodyneEntity** [SpigotMC/BungeeCord#1398]
Issue with the Ping Handler apparently, using the latest BungeeCord build as well.

http://pastebin.com/w51qQcth

**Comment by minecrafter** [comment]
`com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $`

By any chance are you using versions of Spigot before 1.7.x?

**Comment by AnodyneEntity** [comment]
Nope, using Spigot 1.7.10.

**Comment by Brian-Graham** [comment]
We also had this problem when updating BungeeCord to the latest version which promptly caused us to downgrade.

Latest Version (as of this post): 1054
Working Version (1.7.10 -> 1.8.x): 1035

Here is the same error on our end: https://paste.netcoding.net/rohahajo.avrasm

Could it be that you updated the Gson version between the above builds?
