### ISSUE TITLE
crashes - VarInt too big, length wider than 21-bit

### ISSUE THREAD

**Issue by GEJMRovec** [SpigotMC/BungeeCord#1399]
Hello,
I have problems with my bungeecor servers. They always crash on one of these errors.

http://pastebin.com/qkyS2v2N
http://pastebin.com/1iRxWM6t

Im using lastest version of bungee.

Any tips are appraciated.
- Thanks

**Comment by Phineas-0510** [comment]
This is a Spigot server-side issue, not BungeeCord. Post it in the Spigot issues section instead?

**Comment by Janmm14** [comment]
@GEJMRovec

**Comment by GEJMRovec** [comment]
hmm wierd... This error is from bungeecord log. But this was in time when my server was under attack. Now Im fine and bungeecord do NOT crashes anymore.
