### ISSUE TITLE
BungeeCord network crashing ramdomly, with CPU's usage up to 1000% and memory leaking, it can be a bot attack or whats the problem?

### ISSUE THREAD

**Issue by ignorantcross** [SpigotMC/BungeeCord#1402]
I have a big issue with my minecraft network, i dont found help from fadehost.com, my server host provider...

The last week, the server was reaching to 250 players online, and all great, thankyou for creating bungeecord!!

But since 2 days, at 8 o clock for Saturday 14th the server started to lag, and kick all players from network, and i checked the bungee server status, and i Seen a SUOERINCREMENT for CPU, and RAM memory usage, i have 1GB for it, no preoblems, until this happens..

I sen this screenshot:
![captura de pantalla 32](https://cloud.githubusercontent.com/assets/8921248/6672991/8cbad8bc-cbd5-11e4-8a7b-e836acb67abc.png)

Did you can see the cpu activity for 14 of march, to 20 hour aprox, there was a increment for CPU usage...

And in this screenshot do yo can see that for yesterday Sunday 15 at 12:52 hours - 1:11 hours (19 minutes after startup) there were only 50 players connected and server gots up 998 MB of RAM usage, as a Memory leak...
![captura de pantalla 43](https://cloud.githubusercontent.com/assets/8921248/6673039/ecdce8e8-cbd5-11e4-85b8-706f37634139.png)

Now STUPIDLY the server CPU gots up to 1138%, .________.
...
![captura de pantalla 45](https://cloud.githubusercontent.com/assets/8921248/6673088/4bc6619a-cbd6-11e4-84b1-987aaeeef2b2.png)

After some hours of server working...
Do you can see the graph? Its the last, server is on but connection handler closed.. the server its freezed with "pinging"..
![captura de pantalla 46](https://cloud.githubusercontent.com/assets/8921248/6673186/da4a661e-cbd6-11e4-9949-ad4bcc168b24.png)

Here its the log:

The question is... Its a bot attack? Ddos? My network was working fine with no issue in 3 months..
its a mexican network: mc.risingbattles.com

![10168132_359279427592227_722929743597350060_n](https://cloud.githubusercontent.com/assets/8921248/6673250/3fa02012-cbd7-11e4-8d14-7df15c0f8f07.jpg)

16.03 12:16:00 [Server] INFO Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Netty IO Thread #21"
 
16.03 12:03:38 [Server] INFO Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Netty IO Thread #7"
 
16.03 11:57:28 [Server] WARNING No client connected for pending server!
 
16.03 11:56:42 [Server] INFO -> UpstreamBridge has disconnected
 
16.03 11:56:42 [Multicraft] Skipped 6 lines due to rate limit (30/s)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:570)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:56:19 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:56:19 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:226)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:56:19 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:226)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:56:19 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:56:19 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:53)
 
16.03 11:56:19 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:54)
 
16.03 11:56:19 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
 
16.03 11:56:19 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
 
16.03 11:56:19 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
 
16.03 11:56:19 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483)
 
16.03 11:56:19 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
16.03 11:56:19 [Server] INFO at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
 
16.03 11:56:19 [Server] INFO at me.vik1395.PlayerThrottleBungee.main.onLeave(main.java:135)
 
16.03 11:56:19 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
 
16.03 11:56:19 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
 
16.03 11:56:19 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
 
16.03 11:56:19 [Server] INFO java.util.ConcurrentModificationException
 
16.03 11:56:19 [Server] INFO WARNING: Error dispatching event PlayerDisconnectEvent(player=Victor_GamerXD) to listener me.vik1395.PlayerThrottleBungee.main@13b6aecc
 
16.03 11:56:19 [Server] SEVERE Mar 16, 2015 11:51:05 AM net.md_5.bungee.event.EventBus post
 
16.03 11:53:19 [Server] INFO -> UpstreamBridge has disconnected
 
16.03 11:53:19 [Multicraft] Skipped 6 lines due to rate limit (30/s)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe$5.run(AbstractChannel.java:570)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:769)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:52:37 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:52:37 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:226)
 
16.03 11:52:37 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:52:36 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:52:36 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:226)
 
16.03 11:52:36 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:52:36 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:52:36 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:53)
 
16.03 11:52:36 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:54)
 
16.03 11:52:36 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
 
16.03 11:52:36 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
 
16.03 11:52:36 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
 
16.03 11:52:36 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483)
 
16.03 11:52:36 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
16.03 11:52:36 [Server] INFO at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
 
16.03 11:52:36 [Server] INFO at me.vik1395.PlayerThrottleBungee.main.onLeave(main.java:135)
 
16.03 11:52:36 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
 
16.03 11:52:36 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
 
16.03 11:52:36 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
 
16.03 11:52:36 [Server] INFO java.util.ConcurrentModificationException
 
16.03 11:52:36 [Server] INFO WARNING: Error dispatching event PlayerDisconnectEvent(player=Nyla0103) to listener me.vik1395.PlayerThrottleBungee.main@13b6aecc
 
16.03 11:52:36 [Server] SEVERE Mar 16, 2015 11:49:37 AM net.md_5.bungee.event.EventBus post
 
16.03 11:51:11 [Server] INFO disconnected with: ReadTimeoutException : null
 
16.03 11:50:48 [Server] WARNING -> UpstreamBridge - read timed out
 
16.03 11:49:48 [Server] INFO disconnected with: [Proxy] Desconectado de RisingBattles Network.
 
16.03 11:49:29 [Server] INFO disconnected with: ReadTimeoutException : null
 
16.03 11:48:48 [Server] WARNING -> UpstreamBridge - read timed out
 
16.03 11:48:01 [Server] INFO disconnected with: ReadTimeoutException : null
 
16.03 11:44:36 [Multicraft] Skipped 14 lines due to rate limit (30/s)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:44:33 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelInactive(ReadTimeoutHandler.java:144)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:44:33 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:226)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:44:33 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:226)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:219)
 
16.03 11:44:33 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:233)
 
16.03 11:44:33 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:53)
 
16.03 11:44:33 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:54)
 
16.03 11:44:33 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
 
16.03 11:44:33 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
 
16.03 11:44:33 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
 
16.03 11:44:33 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483)
 
16.03 11:44:33 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
16.03 11:44:33 [Server] INFO at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
 
16.03 11:44:33 [Server] INFO at me.vik1395.PlayerThrottleBungee.main.onLeave(main.java:135)
 
16.03 11:44:33 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1461)
 
16.03 11:44:33 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1463)
 
16.03 11:44:33 [Server] INFO at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429)
 
16.03 11:44:33 [Server] INFO java.util.ConcurrentModificationException
 
16.03 11:44:33 [Server] INFO WARNING: Error dispatching event PlayerDisconnectEvent(player=pacheco) to listener me.vik1395.PlayerThrottleBungee.main@13b6aecc
 
16.03 11:44:33 [Server] SEVERE Mar 16, 2015 11:44:28 AM net.md_5.bungee.event.EventBus post
 
16.03 11:44:27 [Server] INFO disconnected with: [Error] Password Incorrecto
 
16.03 11:44:23 [Server] INFO 181.160.124.94
 
16.03 11:44:23 [Multicraft] Skipped 25 lines due to rate limit (30/s)
 
16.03 11:44:18 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 
16.03 11:44:18 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
 
16.03 11:44:18 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
 
16.03 11:44:18 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 
16.03 11:44:18 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:161)
 
16.03 11:44:18 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:319)
 
16.03 11:44:18 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:333)
 
16.03 11:44:18 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
 
16.03 11:44:18 [Server] INFO at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
 
16.03 11:44:18 [Server] INFO at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:362)
 
16.03 11:44:18 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:367)
 
16.03 11:44:18 [Server] INFO at net.md_5.bungee.event.EventBus.post(EventBus.java:47)
 
16.03 11:44:18 [Server] INFO at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
 
16.03 11:44:18 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:483)
 
16.03 11:44:18 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 
16.03 11:44:18 [Server] INFO at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
 
16.03 11:44:18 [Server] INFO at me.vik1395.PlayerThrottleBungee.main.onPlayerPreLogin(main.java:100)
 
16.03 11:44:18 [Server] INFO at java.util.HashMap$EntryIterator.next(HashMap.java:1461)

**Comment by ignorantcross** [comment]
I tried with no plugins and installing PlayerThrottleBungee, antibots , antijoin proxy etc etc, and nothing solves this issue :(

**Comment by minecrafter** [comment]
Please post in the [BungeeCord Help](http://www.spigotmc.org/forums/bungeecord-help.70/) forum and be more descriptive.

**Comment by mastergberry** [comment]
Looks like a DDOS attack. DDOS attacks leak memory badly on Bungee, I don't know why but they do.

**Comment by md-5** [comment]
Cannot accept rate limited or plugin filled logs.
