### ISSUE TITLE
Scheduler memory leak

### ISSUE THREAD

**Issue by Szperak** [SpigotMC/BungeeCord#1405]
Calling scheduler to create a new task every 10 seconds for every player...
Maybe it's a bad solution for making auto-refreshing TAB list, but this bug still exists in #1054.
I use scheduler to handle players switching between servers.

**Comment by yawkat** [comment]
Code?

**Comment by Szperak** [comment]
It's probably a bug in my code, i've modified it to register the (repeating) task once and uploaded it to https://github.com/Szperak/taberr
The bug still exists, but it's not in BungeeCord.

**Comment by yawkat** [comment]
You can close issues yourself

**Comment by Szperak** [comment]
Where?

**Comment by Szperak** [comment]
Oh, ok :D

**Comment by Szperak** [comment]
This bug exists even without plugins, here's a memory usage stats:
[0 players] No players [4MB]
[1 player] Player joins [6MB]
[0 players] Player disconnects [6MB]
[1 player] Player joins [8MB]
[0 players] Player disconnects [8MB]

I've tested it with System.gc() and -verbosegc.

**Comment by yawkat** [comment]
There are a lot of places that could happen, for example with soft caches or netty. RAM usage is no indication of a memory leak at those levels. If you can confirm this using heap dumps, that's a different story.

**Comment by Szperak** [comment]
But after 4 hour - server lags, players can't play, you can see it on nesteria.pl:25565.

**Comment by yawkat** [comment]
Well we can't do anything about that without some proper proof and info.

**Comment by Szperak** [comment]
OK, i'll give some logs soon.

**Comment by Szperak** [comment]
Testing with max 20MB gives still 3MB usage, it's a mistake on my side.
