### ISSUE TITLE
Error in console - To many open files. Crashed the server.

### ISSUE THREAD

**Issue by Duqino** [SpigotMC/BungeeCord#1407]
Hi,

I did see this for a while now but didnt do anything about it. It just popped up a few times in 1 hour.
Last few weeks i didnt do any maintenance because everything was running great until today.

Bungee stopped working and got this error in console -> http://gyazo.com/a30c232c28e39d2a11af2480edc95bba
Like 1000 times.

What can i do to fix this?

King regards

Dutchy.

**Comment by yawkat** [comment]
For a temporary fix, you can raise the soft nofile ulimit.

Also check if you have any plugins leaking fds and have proper ddos mitigation.

**Comment by Duqino** [comment]
To make it a bit easier a full console log when the server is starting up -> http://pastebin.com/zbLzx3Mk

And how can i raise the soft nofile ulimit ?

**Comment by yawkat** [comment]
ulimit -S -n 4096

**Comment by Duqino** [comment]
Only thing i have to do is just run that command in putty?

**Comment by yawkat** [comment]
Sorry, this is an issue tracker, not a support line.

**Comment by Duqino** [comment]
You got a point. Ill figure it out. Thanks for the support!
