### ISSUE TITLE
Cant connect to some servers through bungee

### ISSUE THREAD

**Issue by Greenpls** [SpigotMC/BungeeCord#1410]
Hi could someone pleas go over my config and let me know why i can connect to my factions server. I can connect to the lobby and the survival games one just fine. but for some reason when i get in game and do /server factions i get the error "could not connect to default or fallback server, pleas try again later: java.net.ConnectException" any help would be great thanks! ( all my servers are in offline mode )

http://pastebin.com/UZhqNJhs config

p.s. im not just coming here first i have bean looking around all day and i found lots of people with the same error but when i did what they did to fix it it still wouldn't work

**Comment by kamcio96** [comment]
online_mode in server config?

**Comment by md-5** [comment]
Your servers arent up or reachable from Bungee.
