### ISSUE TITLE
Server wont start up... Console SEVERE error

### ISSUE THREAD

**Issue by Dinodudeishgamer** [SpigotMC/BungeeCord#1412]
C:\Users\DeanAlan\Desktop\BungeeCord Server>java -Xmx1024M -jar BungeeCord.jar -
o true
14:17:53 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
14:17:53 [INFO] Using standard Java compressor. To enable zero copy compression,
 run on 64 bit Linux
14:17:53 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"3973c51":1055
14:17:53 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
14:17:53 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
14:17:53 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
14:17:53 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
14:17:53 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
14:17:53 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
14:17:53 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"3973c51":1055 by SpigotMC
14:17:53 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"3973c5
1":1055 by SpigotMC
14:17:53 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"39
73c51":1055 by SpigotMC
14:17:53 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"3973
c51":1055 by SpigotMC
14:17:53 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"3973c5
1":1055 by SpigotMC
14:17:53 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"3973c5
1":1055 by SpigotMC
14:17:53 [SEVERE] Exception in thread "main"
14:17:53 [SEVERE] java.lang.IllegalArgumentException: Default server lobby is no
t defined
14:17:53 [SEVERE]     at com.google.common.base.Preconditions.checkArgument(Prec
onditions.java:145)
14:17:53 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.j
ava:111)
14:17:53 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:242)
14:17:53 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLaunc
her.java:54)
14:17:53 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

What do I do? Please help!

**Comment by hibo98** [comment]
Please post your Config

**Comment by nikosgram13** [comment]
Hey, try to install the java from the oracle repository.

## Installing Oracle JDK

The Oracle JDK is the official JDK; however, it is no longer provided by Oracle as a default installation for Ubuntu.

You can still install it using apt-get. To install any version, first execute the following commands:

```shell
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
```

### Oracle JDK 7

This is the latest stable version.
```shell
sudo apt-get install oracle-java7-installer
```

## Managing Java (optional)

When there are multiple Java installations on your Droplet, the Java version to use as default can be chosen. To do this, execute the following command:

```shell
sudo update-alternatives --config java
```

It will usually return something like this if you have 2 installations (if you have more, it will of course return more):

```shell
There are 2 choices for the alternative java (providing /usr/bin/java).

Selection    Path                                            Priority   Status
------------------------------------------------------------
* 0            /usr/lib/jvm/java-7-oracle/jre/bin/java          1062      auto mode
  1            /usr/lib/jvm/java-6-openjdk-amd64/jre/bin/java   1061      manual mode
  2            /usr/lib/jvm/java-7-oracle/jre/bin/java          1062      manual mode

Press enter to keep the current choice[*], or type selection number:
```

More here: https://www.digitalocean.com/community/tutorials/how-to-install-java-on-ubuntu-with-apt-get
