### ISSUE TITLE
Add METHOD_EXECUTE on the ClickEvent of TextComponents

### ISSUE THREAD

**Issue by Jannik8500** [SpigotMC/BungeeCord#1413]
Please add a function to the ClickEvent of TextComponents to execute a method on click.

It would be very nice to ask if a player whats really destroy a party, guild and more...

I imagined that it works like this:
TextComponent yes_message = new TextComponent(ChatColor.RED + "§lYES");
yes_message.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("lorem ipsum").create()));
yes_message.setClickEvent(new ClickEvent(ClickEvent.Action.EXECUTE_METHOD, mycustomfunction()));
p.sendMessage(yes_message);

**Comment by thinkofdeath** [comment]
Not possible, we are limited by the client

**Comment by kamcio96** [comment]
Use commands ;)

**Comment by Jannik8500** [comment]
kamcia96, i do it currently, but it's not very good to ask if a player wants really remove her guild.
Currently i using:
/guild remove -> ask in the chat, on click "yes", execute command "/guild remove really" ^^

But it's not very good, because every player can say: "Make /guild remove really" ...

**Comment by iKeirNez** [comment]
@Jannik8500 Use a List, add the player to the list when they use "/guild remove", only allow them to use "/guild remove really" if they are in the List.

**Comment by kamcio96** [comment]
Yes, it is best way. you can also add info "click there or write /g remove really"
