### ISSUE TITLE
Ping forwarding does not work with legacy 1.6.x ping

### ISSUE THREAD

**Issue by vemacs** [SpigotMC/BungeeCord#1414]
For example, Buycraft's. The max-players do not correspond to the actual max-players on the forwarded ping, and the online players as well.

1.7 SLP (mcstatus.py):

```
python mcstatus.py play.chaospvp.org
INFO 2015-03-24 10:09:16,906 mcstatus.py:159: querying play.chaospvp.org:25565
INFO 2015-03-24 10:09:17,213 mcstatus.py:167: available, 35/300 online:
```

1.6 SLP (Buycraft):
![](http://i.imgur.com/K9QQ9Nb.png)

**Comment by phase** [comment]
Is it only displaying the max number of players wrong?

**Comment by vemacs** [comment]
Nope, it's displaying the full motd incorrectly.

**Comment by Phineas-0510** [comment]
Is your resolv.conf configured correctly?

**Comment by vemacs** [comment]
Thia has nothing whatsoever to do with DNS?

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
