### ISSUE TITLE
Fallback server bug/idea

### ISSUE THREAD

**Issue by ArtificialTruth** [SpigotMC/BungeeCord#1417]
So if your default server is down you will connect to the fallback server instead. But if the default server goes down while you are on the network, you will just get kicked. You should be moved to the fallback server, that would make sense.

**Comment by marium0505** [comment]
I agree.

**Comment by M64mc** [comment]
Have a look at MoveMeNow.

**Comment by TheOnlyRealTGS** [comment]
Already using it. Not solving the problem
