### ISSUE TITLE
New Unix Process in BungeeCord Plugin

### ISSUE THREAD

**Issue by stefan01** [SpigotMC/BungeeCord#1421]
I am trying to write a Server Wrapper like Programm, that starts and stops Server then needed.
To start them I am using the Process Object, but it gives me this error Message:

```
14:27:11 [WARNUNG] Plugin performed restricted action, please inform them to use proper API methods: Illegal
 thread group access
java.security.AccessControlException: Plugin violation: Illegal thread group acc
    at net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManag
    at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.j
    at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)
    at java.lang.Thread.init(Thread.java:391)
    at java.lang.Thread.init(Thread.java:349)
    at java.lang.Thread.<init>(Thread.java:675)
    at java.lang.UNIXProcess.lambda$null$267(UNIXProcess.java:229)
    at java.lang.UNIXProcess$$Lambda$5/1447689627.newThread(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.<init>(ThreadPoolExecutor.
    at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java
    at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1
    at java.lang.UNIXProcess.initStreams(UNIXProcess.java:289)
    at java.lang.UNIXProcess.lambda$new$269(UNIXProcess.java:259)
    at java.lang.UNIXProcess$$Lambda$6/1234776885.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:258)
    at java.lang.ProcessImpl.start(ProcessImpl.java:134)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
    at java.lang.Runtime.exec(Runtime.java:620)
    at java.lang.Runtime.exec(Runtime.java:450)
    at java.lang.Runtime.exec(Runtime.java:347)
    at .....................................................................................................
    at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.jav
    at java.lang.Thread.run(Thread.java:745)
```

This is my Code:

```
public void startServer()
	{
		
		ProxyServer.getInstance().getScheduler().runAsync(SM, new Runnable()
		{
			@Override
			public void run()
			{
				try
				{
					ProcessBuilder builder = new ProcessBuilder("/bin/bash");
					builder.redirectErrorStream(true);
					
					Process process = builder.start();
					outStream = process.getOutputStream();
					streamWriter = new BufferedWriter(new OutputStreamWriter(outStream));
					inStream = process.getInputStream();
					streamReader = new BufferedReader(new InputStreamReader(inStream));
					
					streamWriter.write("Screen -S " + name);
					streamWriter.write("java " + startParameter + " -jar " + path + " --port " + port);
					
					String line;
					while ((line = streamReader.readLine ()) != null) 
					{
						System.out.println (line);
					}
						
				} catch (IOException e) 
				{
					e.printStackTrace();
				}
			}
		});
```

I think it throws this error, because the Method "builder.start()" starts a new Thread, that (of cause) isn't using the BungeeCord API (ProxyServer.getInstance().getScheduler().runAsync())

Do you know, how I can fix this error?

**Comment by BjoernAkAManf** [comment]
Bungeecord implements a custom SecurityManager, that disallows such things. A fast way to make this easier would be to create an external service (such as a custom java application) with an api (e.g. REST) to start new Servers on demand. 

There are good reasons to block this functionality for plugins.

**Comment by stefan01** [comment]
Is there no Method, to make the Process use the Bungeecord  Scheduler instead of the normal Java Thread?

**Comment by yawkat** [comment]
No

**Comment by stefan01** [comment]
Thanks. Isn't it possible to include the spigot.jar and call the Main Method to start a new Server?

**Comment by yawkat** [comment]
No

**Comment by kamcio96** [comment]
Change it by reflection ;)https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeSecurityManager.java#L12

btw Runtime is from java.lang so it should work.

**Comment by yawkat** [comment]
You can't disable the security manager with reflection

**Comment by stefan01** [comment]
Thanks, kamcio96, can you give me an example? Why do you think, its not possible yawkat?

**Comment by yawkat** [comment]
I've done it and it's not possible to disable the security manager through simple reflection.

**Comment by mooman219** [comment]
Use instrumentation to disable bungee's security manager. You can modify the bungee code before it's loaded by the classloader and modify the validation method to just return when it's called. I recommend using javassist as you can simple use insertBefore("return;") on the method.

Write a class to use premain (It's like main but gets called before it):

    public class Yourclass {
        public static void premain(final String arg, Instrumentation instr) {
            // Use the Instrumentation  object to remove the security manager code
        }
    }


Use maven to compile your class (Need to clarify your jar has a premain):

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.3.1</version>
                <configuration>
                    <archive>
                        <index>true</index>
                        <manifest>
                            <addClasspath>true</addClasspath>
                        </manifest>
                        <manifestEntries>
                            <Premain-Class>whatever.package.Yourclass</Premain-Class>
                            <Can-Redefine-Classes>true</Can-Redefine-Classes>
                            <Can-Retransform-Classes>true</Can-Retransform-Classes>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>

Use the ```-javaagent:"yourjar.jar"``` flag when running bungee (So your premain gets called before the actual jar your running gets loaded by the classloader).

**Comment by yawkat** [comment]
Well if you really really need to you can use unsafe to disable the security manager. Or just fork bungee.

**Comment by mooman219** [comment]
You cannot use unsafe to disable the security manager >.<, that's the point of the security manager. Not reflection nor anything can disable it after it's been started really. 

Instrumentation runs before most things, so using it to disable is one of the few options. Additionally, you can try to mess with the flag ```-Djava.security.manager``` when starting Bungee.

Remember, the point of the security manager was so applets on the web couldn't harm your computer. Sun put a lot of time into making sure the security manager was actually secure before implementing it.

**Comment by yawkat** [comment]
You can actually! https://github.com/yawkat/reflect/blob/master/src/main/java/at/yawk/reflect/Unsafes.java

**Comment by mooman219** [comment]
Then say bungee modifies their permissions to reject you from using reflection on Unsafe.

**Comment by yawkat** [comment]
Hey, I'm not exactly recommending this way. The classloader PR is still a better solution.

**Comment by kamcio96** [comment]
you can compile bungee without security manager

who know why it doesn't work without it?

**Comment by yawkat** [comment]
Well, ProcessBuilder uses threads for monitoring outs of the applications.

**Comment by kamcio96** [comment]
but it is from java.* so it should work

**Comment by yawkat** [comment]
No, java.* isn't excluded in any way

**Comment by kamcio96** [comment]
BungeeSecurityManager.java:30?

**Comment by yawkat** [comment]
That excludes non-java.* classes on a null security manager.

**Comment by kamcio96** [comment]
. ok, so changing ENFORCE field is half of solution
somebody has to fix it :D

**Comment by BjoernAkAManf** [comment]
Why making such a mess if it's much easier and cleaner to create a seperate deamon?

**Comment by yawkat** [comment]
Because that'd be a good solution, nobody wants good solutions!

**Comment by md-5** [comment]
This shouldn't be happening, I'll look into it.

Please keep stuff on the bug tracker relevant to properly fixing the issue. As an aside this is just a WARNING, it doesn't stop anything. Changing ENFORCE to true actually stops it (ie: the reverse of what you want).

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
