### ISSUE TITLE
Server is lagging with 20 TPS

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1422]
Hi,

my servers are laggy when I have maybe 20 players, and I have 20 TPS. Why?
Build: 985

**Comment by kamcio96** [comment]
PL: pluginy na bungee, wersja serwera, pluginy na serwerze? 
EN: plugins on bungee, server version, plugins on server?

**Comment by CzlowiekKuktas** [comment]
Dostałem info, że to przez chujowy serwer i testuję inny hosting.

**Comment by kamcio96** [comment]
to zamknij issue ;) 

so close issue ;)

**Comment by CzlowiekKuktas** [comment]
Nie wiem czy to rozwiązanie. ;)

I don't know if this is the solution. ;)
