### ISSUE TITLE
Store messages.properties in bungeecord folder, not in the jarfile

### ISSUE THREAD

**Issue by Phreag** [SpigotMC/BungeeCord#1423]
It would be really useful if you could place the message.properties somewhere else, but not in the jarfile.

its stupid to change one file in the jar every time you update bungeecord. 
would that be possible?

**Comment by yawkat** [comment]
You could also try adding another jar to the classpath which just contains that properties file. Or make a script to automatically add it to the jar when needed.

**Comment by md-5** [comment]
Already an issue for this
