### ISSUE TITLE
IndexOutOfBoundsException - readerIndex

### ISSUE THREAD

**Issue by Kainzo** [SpigotMC/BungeeCord#1425]
14:11:51 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"3973c51":1055 by md_5
http://pastie.org/private/vm9xlji0fvctw91tla9ng

**Comment by kamcio96** [comment]
like #1424

**Comment by ninja-** [comment]
unrelated to #1424

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
