### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by kamcio96** [SpigotMC/BungeeCord#1427]
http://pastebin.com/raw.php?i=GeFribED

**Comment by cindyker** [comment]
You ran out of memory. Add more or review your plugins for high memory usage.

**Comment by kamcio96** [comment]
I have 12GB ram and only two plugins. They aren't memory consuming.
Before OutOfMemory:
http://pastebin.com/raw.php?i=Frcj6CYR

**Comment by defabricated** [comment]
Google "whois <ip from second paste>" - it explains everything. :)

Try add these rules to iptables - it should drop invalid packets:
iptables -A INPUT -m state --state INVALID -j DROP
iptables -A FORWARD -m state --state INVALID -j DROP
iptables -A OUTPUT -m state --state INVALID -j DROP

Write if BungeeCord will be still crashing. ;D

**Comment by ninja-** [comment]
effect of attack using #1424, notice the China etc. ips

**Comment by md-5** [comment]
You should look into DDoS protection or increasing direct memory:
-XX:MaxDirectMemorySize=256m

**Comment by kamcio96** [comment]
still
it isnt ddos
