### ISSUE TITLE
Cant connect Server

### ISSUE THREAD

**Issue by fabm3n** [SpigotMC/BungeeCord#1429]
I cant join my server, nothing is displayed in the chat and nothing is in the log
Log: 20:24:10 [INFORMATION] [fabm3n] <-> ServerConnector [Modded] has connected
20:24:10 [INFORMATION] [fabm3n] <-> ServerConnector [Modded] has disconnected

**Comment by kamcio96** [comment]
server version? do you have all mods?

**Comment by fabm3n** [comment]
Server Version 1.7.10 i have all mods

**Comment by kamcio96** [comment]
modded server is default bungee server? try connect to server without bungee

**Comment by fabm3n** [comment]
Yesterday i joinen my server via bungeecord but i will test

**Comment by fabm3n** [comment]
Ok i can join but why i cant join with bungeecord?

**Comment by Smove** [comment]
What server software you are using? Is there any throttle setting(like in bukkit.yml)? If yes, you have to set it to -1. Please check that your server is online-mode false behind a BungeeCord.

**Comment by draksterau** [comment]
Hey Im getting the same, with forge/cauldron v1.7.10 .... Connect and disconnect in logs, with an insta-crash for client.

Works fine without bungee...

**Comment by Smove** [comment]
Can you attach the Client crash report via hastebin?

**Comment by draksterau** [comment]
As requestedhttp://pastebin.com/QuyZaqn3

**Comment by draksterau** [comment]
Sorry thought this was my issue just created, #1432 is for that crash i just linked.

**Comment by Smove** [comment]
I think this pull request can fix the error : 
https://github.com/SpigotMC/BungeeCord/pull/1283

**Comment by draksterau** [comment]
That looks like it!!!! Blood told me about the DimensionRegister :D 

Is there any way I can build a copy of bungee with that?

**Comment by Smove** [comment]
You have to setup an build environment with Maven and Java JDK 1.7(or 1.8).  Or you can setup your own ci.  
If you like,  i can build BungeeCord with this fix later and upload/send you the BungeeCord.jar

I think you have to ask @md_5 about the merge of this pull request.

**Comment by draksterau** [comment]
Could u send it to me please? Id really appreciate it!

@md-5  If you want to include it anyone with cauldron will appreciate it greatly :D

**Comment by Smove** [comment]
I have something to do now.  Later i will build it :)

**Comment by kamcio96** [comment]
jdk 1.7, lombok doesn't work with jdk 1.8

**Comment by Smove** [comment]
@draksterau http://files.jandelius.eu/BungeeCord_w_1283.jar
Please save this file on your computer. I will remove it in a few days. This is the current BungeeCord master branch from SpigotMC and the pull request #1283 .

**Comment by draksterau** [comment]
YOU ROCK MATE!!!!! Thank you so much!  :)

**Comment by draksterau** [comment]
@md-5 Hey mate, I've tested the 1283 pull request and it works beautifully with cauldron, could you please implement in the official version?
