### ISSUE TITLE
Exclusion of all possible commands plugin.

### ISSUE THREAD

**Issue by KubaOjczyk** [SpigotMC/BungeeCord#1431]
Hi, I bungeecord server, and the server, and I want to lobby to lobby could not enter any commands, or the operator can use the command
thank you.

**Comment by md-5** [comment]
This isn't a bug. Maybe use the forums to request a plugin?

**Comment by KubaOjczyk** [comment]
I know that this is not a bug, but it needs this plugin, if you know this plugin, let them write the name of the
Thank you.

**Comment by md-5** [comment]
Ask forums, might be better help: http://www.spigotmc.org/

**Comment by KubaOjczyk** [comment]
I wrote ..
I was looking at bukkit.org, and spigotmc.org and nothing.

**Comment by md-5** [comment]
Make a thread and ask on spigotmc.org

**Comment by KubaOjczyk** [comment]
i wrote and nothing

**Comment by Janmm14** [comment]
You need to wait.
