### ISSUE TITLE
Bungee doesn't disconnect players correctly

### ISSUE THREAD

**Issue by McLive** [SpigotMC/BungeeCord#1435]
For some reason some players can't connect to the server anymore. They are getting the "Already connected" message while joining.

They aren't connected to any of the backend servers but they are still listed in "/glist" and I can see them with "/find".

Screenshot:
![](http://img.mclive.eu/20150413183302.png)

**Comment by McLive** [comment]
bump

**Comment by GingerGeek** [comment]
OK, so we could do with more info. Is this the only time this has happened? Does it happen to the same people after a restart? What plugins do you use? Does only happen to certain players?

**Comment by McLive** [comment]
No, it wasn't the only time. Happens randomly and to more than one player.

Pluginlist:
![](http://img.mclive.eu/20150419002625.png)

**Comment by McLive** [comment]
Just happened again to lots of players.

**Comment by acecheese** [comment]
It could ve movemenow? I've experienced similar issues with a plugin that has features alike.

**Comment by ringolam** [comment]
@acecheese I don't think so. I have encountered this issue as well, but I don't have movemenow.

**Comment by McLive** [comment]
It was also working fine with earlier versions of bungeecord and the same movemenow version.

**Comment by Katelyn-SN** [comment]
Which build number are disconnects working on @McLive ?

**Comment by McLive** [comment]
I think this issue started happening with https://github.com/SpigotMC/BungeeCord/commit/f2673c5876551214cfa0f1915b21936787b0e20b or https://github.com/SpigotMC/BungeeCord/commit/f2d17cb216369a0bee0f038348328918acd0d86a

**Comment by acecheese** [comment]
I'm going to throw this here as well.

https://gist.github.com/acecheese/b94a29b87e5aae39d8c1

Appears to fix this in @McLive's case.

**Comment by McLive** [comment]
So this is fixed now?

**Comment by Katelyn-SN** [comment]
No its not

**Comment by McLive** [comment]
bump
