### ISSUE TITLE
You are already connected to this server!

### ISSUE THREAD

**Issue by gal499605076** [SpigotMC/BungeeCord#1441]
Bungeecord is #1059
Maybe a bug?
Player join the game.. sometimes later player lost connect with 
  (  Internal Exception: io.netty.handler.timeout.ReadTimeoutException )
 , when try connect again...It say You are already connected to this server！
Even wait for a long time...It also say You are already connected to this server...

use /find player it tell player is on server XXX.
Restart that server is invalid...Unless restart bungee...But there are almost 800-900 player still in game......And today there are at least ten players feedback the problem
![image](https://cloud.githubusercontent.com/assets/11988883/7444996/cb7f8cb0-f1d1-11e4-93ac-9c9b49af472c.png)

**Comment by McLive** [comment]
I can confirm this. https://github.com/SpigotMC/BungeeCord/issues/1435

**Comment by gal499605076** [comment]
Yes the same problem!

**Comment by kukubaczek** [comment]
Use RedisBungee.

**Comment by McLive** [comment]
I doubt RedisBungee will fix this bug.

**Comment by Katelyn-SN** [comment]
No it does not we have been having this issue with our proxy recently. Its happening under all conditions sadly. 0 plugins installed server or bungee side its very broken @md-5 You need to deal with this BungeeCord is unusable under these conditions players just stay logged in hogging server resources and die sometimes due to mobs.

**Comment by acecheese** [comment]
http://www.spigotmc.org/threads/upstreambridge-please-help.64073/#post-705143

**Comment by acecheese** [comment]
What's the earliest build this happens with?

**Comment by McLive** [comment]
I think it started with https://github.com/SpigotMC/BungeeCord/commit/f2673c5876551214cfa0f1915b21936787b0e20b or https://github.com/SpigotMC/BungeeCord/commit/f2d17cb216369a0bee0f038348328918acd0d86a

**Comment by acecheese** [comment]
I'd say that's what's causing the kick, but the player isn't being unloaded?

**Comment by gal499605076** [comment]
Yes..lost connect and isnt being unloaded. Then player cant connect until restart bungee

**Comment by acecheese** [comment]
https://gist.github.com/acecheese/b94a29b87e5aae39d8c1

Appears to fix this in @McLive's case.

**Comment by Katelyn-SN** [comment]
It does not fix it in my case in fact that event never fires.

**Comment by acecheese** [comment]
@Katelyn-SN if that's not firing then something major is wrong. Just to confirm. It is a BungeeCord plugin, the plugin is being enabled, and you have this problem in the first place..

Like I said, it's potentially resolved the issue for Mr. Live.

**Comment by Videog4mer** [comment]
This isn't working for me either.
The FuckOff Plugin isn't helping. The same problem is happening to me as the original poster.
~Videog4mer

**Comment by PhanaticD** [comment]
I was trying to find out why some players were becoming invisible on my server, and noticed that every player reported as invisible had this issue, "You are already connected to this server!" however they were still able to log on. Also I noticed they disconnect then reconnect in the same instant due to this, its like they log in twice

**Comment by gal499605076** [comment]
。。。build 1065 also has this problem!

**Comment by Katelyn-SN** [comment]
Yeah @acecheese Its for sure not working the event never ever fires i need to make a plugin that logs all event fires so we can see where its happening.

**Comment by acecheese** [comment]
Not that I don't trust you.. I just don't think it's compiled correctly.. If that event is not being fired there is a massive problem! 

https://dl.dropboxusercontent.com/u/64069713/FuckOff.jar

**Comment by Katelyn-SN** [comment]
@acecheese I tried that jar from the Spigot post after it didn't fire i'm not a idiot when it comes to this stuff it is initialized correctly i checked multiple times it is not firing.

**Comment by acecheese** [comment]
Ping TOD, not me. xD That problem seems rather drastic.

**Comment by Xayanix** [comment]
I can confirm this bug.

**Comment by Janmm14** [comment]
@thinkofdeath

**Comment by PhanaticD** [comment]
bump as well

**Comment by McLive** [comment]
bump

**Comment by 9190281** [comment]
Happening to me too.

**Comment by CrazyFlasherTDB** [comment]
bump

**Comment by Xayanix** [comment]
asd

**Comment by Janmm14** [comment]
pmub

**Comment by McLive** [comment]
bump

**Comment by brainscript** [comment]
+1

**Comment by kamcio96** [comment]
me too, it is when client close connection. 
The most important thing for devs: don't block PostLoginEvent,
In other situations I don't know why bungee doesn't detect it.

**Comment by CrazyFlasherTDB** [comment]
i don't know about you guys, but removing a plugin called AutoIn from bukkit servers(it's still on bungee and lobby server) and updating all bukkit servers to 1.8.7 seemed to fix this issue in my case.

**Comment by kamcio96** [comment]
and don't use epoll, sometimes it could be a reason

**Comment by McLive** [comment]
bump

**Comment by PhanaticD** [comment]
I was able to reproduce this happening by clicking my server multiple times in the minecraft client server list, it seemed like the login was sent twice

**Comment by 04130340** [comment]
bump 
Terrible problem
It appears to me

**Comment by 04130340** [comment]
All the reasons to: Auto-IN This plugin

It is difficult to choose the

When I installed AutoIn, bungeecord will not function properly

But Autoin function is very important
Who knows how to replace?

**Comment by Xayanix** [comment]
I know.
Online mode true

2015-09-18 16:45 GMT+02:00 04130340 <notifications@github.com>:

**Comment by McLive** [comment]
Also happens without Auto-IN.

**Comment by i9hdkill** [comment]
Please open a new ticket, if this issue still persists in the latest version

**Comment by GoDragonGoGo** [comment]
f

**Comment by ZTJun** [comment]
bump

**Comment by Janmm14** [comment]
> Please open a new ticket, if this issue still persists in the latest version

**Comment by EagAnarchy** [comment]
maybe turn off online mode?

**Comment by EagAnarchy** [comment]
bump

**Comment by EagAnarchy** [comment]
bump

**Comment by Outfluencer** [comment]
@EagAnarchy  are you okay?

**Comment by Janmm14** [comment]
lock replies, mark as replies as offtopic/spam

**Comment by Outfluencer** [comment]
what??

**Comment by EagAnarchy** [comment]
@Outfluencer yes I am
