### ISSUE TITLE
This look like a Bungee BotNet DOS Attack

### ISSUE THREAD

**Issue by BeastPsycho** [SpigotMC/BungeeCord#1444]
Do you renember me?

I beleive im receiving a lot of bot attacksI 
I looked at log files and there were, 10 log files of 16MB, today my network was down from server host, I manage 5GB of RAM, my last issue was with only 512mb, and it "was fixed partialy" today my network got down and at this screenshot you can see around 6000+ conections from same IP:

 
![captura de pantalla 282](https://cloud.githubusercontent.com/assets/8921248/7223752/03383e62-e6ed-11e4-8767-6ed813473f88.png)

I dont know what happen this, I might ren a Anti-DDos Service? Do you can help me to solve this? Whats happen? :/

**Comment by PhanaticD** [comment]
block it in a firewall
