### ISSUE TITLE
Add a packet interception API 

### ISSUE THREAD

**Issue by Techcable** [SpigotMC/BungeeCord#1445]
I propose an API to intercept and send packets is added.
The minecraft protocol is somewhat stable and is [fully documented](wiki.vg). A packet api would be implementation-independent, but not version-independent making it of course, unsafe for normal use by plugins. Many plugin developers, would like to modify sent packet on the bungeecord side. Adding a packet api like [ProtocolLib](https://github.com/aadnk/ProtocolLib) would allow developers greater (although unsafe) control.

The requirements for this are:
- [ ] Define all packets
- [ ] Add events for packet sending and receiving

I hope you agree that many developers could benefit from a packet interception API and a packet sending API.
_________________________________________
If you approve this i'm willing to PR an implementation.

**Comment by md-5** [comment]
Too much overhead, and packets are an internal thing - see same reason why Bukkit has no protocol API.

**Comment by Techcable** [comment]
Would defining all packets be accepted?
