### ISSUE TITLE
[SEVERE] Exception in thread "main"

### ISSUE THREAD

**Issue by XxTheEnderGodxX** [SpigotMC/BungeeCord#1446]
Hello, I am XxTheEnderGodxX, I am trying to create a Bungee cord server but the console always ends up with the [SEVERE] type things. It says [SEVERE] Exception in thread "main". I dont know how to fix this and I really need help. I am trying to run this server on my desktop and also tried looking on the internet to find an answer but can never find one. I really need help to fix this so i can run my server. The config for the server is perfectly fine i checked and its ok. But the last errors ([Severe]'s) are really making me mad. Please help me out, XxTheEnderGodxX.

**Comment by kamcio96** [comment]
Could you send log? Without it we can't help :)

**Comment by XxTheEnderGodxX** [comment]
Log?
like what my console says?

**Comment by XxTheEnderGodxX** [comment]
well Here is what my console says:

**Comment by XxTheEnderGodxX** [comment]
C:\Users\XxTheEnderGodxX\Desktop\Minecraft Server\Proxy>java -Xmx1024M -jar Bung
eeCord.jar -o true
16:23:55 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
16:23:55 [INFO] Using standard Java compressor. To enable zero copy compression,
 run on 64 bit Linux
16:23:55 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"fa828eb":1059
16:23:55 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
16:23:55 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
16:23:55 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
16:23:55 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
16:23:55 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
16:23:55 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
16:23:55 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"fa82
8eb":1059 by SpigotMC
16:23:55 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"fa828e
b":1059 by SpigotMC
16:23:55 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"fa828eb":1059 by SpigotMC
16:23:55 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"fa
828eb":1059 by SpigotMC
16:23:55 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"fa828e
b":1059 by SpigotMC
16:23:55 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"fa828e
b":1059 by SpigotMC
16:23:55 [SEVERE] Exception in thread "main"
16:23:55 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast
to java.util.Map
16:23:55 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:89
)
16:23:55 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.j
ava:59)
16:23:55 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:245)
16:23:55 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLaunc
her.java:54)
16:23:55 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by XxTheEnderGodxX** [comment]
My Config looks like:

**Comment by XxTheEnderGodxX** [comment]
{
  "player_limit": 100, 
  "Stats": "153c7d3c-a0e4-4c06-aa30-fd64a4805bb1", 
  "groups": "XxTheEnderGodxX, - admin", 
  "online_mode": true, 
  "ip_forward": true, 
  "connection_throttle": 4000, 
  "servers": {
    "Factions": {
      "restricted": false, 
      "motd": "", 
      "address": "72.181.123.174:25567"
    }, 
    "Hub": {
      "restricted": false, 
      "motd": "&cTest", 
      "address": "72.181.123.174:25566"
    }
  }, 
  "disabled_commands": [
    "disabledcommandhere"
  ], 
  "listeners": [
    {
      "tab_list": "GLOBAL_PING", 
      "motd": "BungeeCord Proxy", 
      "default_server": "Hub", 
      "forced_hosts": "ThunderCraftMC.serveminecraft.net", 
      "tab_size": 60, 
      "query_port": 25565, 
      "bind_local_address": false, 
      "host": "72.181.123.174:25565", 
      "query_enabled": false, 
      "force_default_server": false, 
      "fallback_server": "Hub", 
      "max_players": 100, 
      "ping_passthrough": false
    }
  ], 
  "timeout": 30000, 
  "permissions": {
    "default": [
      "bungeecord.command.server", 
      "bungeecord.command.list"
    ], 
    "admin": [
      "bungeecord.command.alert", 
      "bungeecord.command.end", 
      "bungeecord.command.ip", 
      "bungeecord.command.reload"
    ]
  }
}

**Comment by md-5** [comment]
Look at the example config.

**Comment by XxTheEnderGodxX** [comment]
I did but i used Yaml parser
Then i copied and pasted this. I got the same error when i used the normal way

**Comment by XxTheEnderGodxX** [comment]
but i will try

**Comment by XxTheEnderGodxX** [comment]
it did the same error

**Comment by XxTheEnderGodxX** [comment]
Here is what my new config looks like:

**Comment by XxTheEnderGodxX** [comment]
groups-
  XxTheEnderGodxX,
 - admin
disabled_commands-
- disabledcommandhere
player_limit- 100
stats- 153c7d3c-a0e4-4c06-aa30-fd64a4805bb1
permissions-
  default-
  - bungeecord.command.server
  - bungeecord.command.list
  admin-
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners-
- max_players- 100
  fallback_server- Hub
  host- 72.181.123.174:25565
  bind_local_address- false
  ping_passthrough- false
  tab_list- GLOBAL_PING
  default_server- Hub
  forced_hosts-
    ThunderCraftMC.serveminecraft.net
  tab_size- 60
  force_default_server- false
  motd- 'BungeeCord Proxy'
  query_enabled- false
  query_port- 25565
timeout- 30000
connection_throttle- 4000
servers-
  Hub-
    address- 72.181.123.174:25566
    restricted- false
    motd- '&cTest'
  Factions-
    address- 72.181.123.174:25567
    restricted- false
    motd- ''
ip_forward- true
online_mode- true

**Comment by XxTheEnderGodxX** [comment]
whoa
tht kind of messed up copying and pasting

**Comment by XxTheEnderGodxX** [comment]
groups-
  XxTheEnderGodxX,
 - admin
disabled_commands-
- disabledcommandhere
player_limit- 100
stats- 153c7d3c-a0e4-4c06-aa30-fd64a4805bb1
permissions-
  default-
  - bungeecord.command.server
  - bungeecord.command.list
  admin-
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners-
- max_players- 100
  fallback_server- Hub
  host- 72.181.123.174:25565
  bind_local_address- false
  ping_passthrough- false
  tab_list- GLOBAL_PING
  default_server- Hub
  forced_hosts-
    ThunderCraftMC.serveminecraft.net
  tab_size- 60
  force_default_server- false
  motd- 'BungeeCord Proxy'
  query_enabled- false
  query_port- 25565
timeout- 30000
connection_throttle- 4000
servers-
  Hub-
    address- 72.181.123.174:25566
    restricted- false
    motd- '&cTest'
  Factions-
    address- 72.181.123.174:25567
    restricted- false
    motd- ''
ip_forward- true
online_mode- true

**Comment by XxTheEnderGodxX** [comment]
well
it looks normal in the config

**Comment by XxTheEnderGodxX** [comment]
![hi](https://cloud.githubusercontent.com/assets/12076356/7329704/43260d62-ea97-11e4-94be-c6701cab19d2.jpg)

**Comment by XxTheEnderGodxX** [comment]
there we go

**Comment by Janmm14** [comment]
@XxTheEnderGodxX just look atthe example config and compare the syntax

**Comment by XxTheEnderGodxX** [comment]
atthe? Im sorry i dont know what that is. Also Compare the syntax?

**Comment by XxTheEnderGodxX** [comment]
Can someone pls reply i really want my server up and running and people are asking me to turn it on. I want to but i cant until this is done

**Comment by kamcio96** [comment]
http://pastebin.com

**Comment by XxTheEnderGodxX** [comment]
If you want to see my configuration I have sent it in on a screen pic already
From the earlier comments

**Comment by XxTheEnderGodxX** [comment]
If you want to see my configuration I have sent it in on a screen pic already
From the earlier comments
here is a link to my config.
https://cloud.githubusercontent.com/assets/12076356/7329704/43260d62-ea97-11e4-94be-c6701cab19d2.jpg

**Comment by XxTheEnderGodxX** [comment]
If you want to see my configuration I have sent it in on a screen pic already
From the earlier comments
here is a link to my config.
https://cloud.githubusercontent.com/assets/12076356/7329704/43260d62-ea97-11e4-94be-c6701cab19d2.jpg

**Comment by XxTheEnderGodxX** [comment]
If you want to see my configuration I have sent it in on a screen pic already
From the earlier comments
here is a link to my config.
https://cloud.githubusercontent.com/assets/12076356/7329704/43260d62-ea97-11e4-94be-c6701cab19d2.jpg

**Comment by XxTheEnderGodxX** [comment]
Whoops

**Comment by kamcio96** [comment]
remove it, and edit new one

**Comment by XxTheEnderGodxX** [comment]
Ok so like make a new configuration file right?

**Comment by kamcio96** [comment]
yes

**Comment by XxTheEnderGodxX** [comment]
Ok

**Comment by XxTheEnderGodxX** [comment]
Ok so i have done this and reset it. The problem was the config itself so i had to fix it again. But even when there was errors in the Config, there was the same error Here is my console and what it said

**Comment by XxTheEnderGodxX** [comment]
C:\Users\XxTheEnderGodxX\Desktop\Minecraft Server\Proxy>java -Xmx1024M -jar Bung
eeCord.jar -o true
20:22:36 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
20:22:36 [INFO] Using standard Java compressor. To enable zero copy compression,
 run on 64 bit Linux
20:22:36 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"fa828eb":1059
20:22:36 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
20:22:36 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
20:22:36 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
20:22:36 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
20:22:36 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
20:22:36 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
20:22:36 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"fa82
8eb":1059 by SpigotMC
20:22:36 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"fa828e
b":1059 by SpigotMC
20:22:36 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"fa828eb":1059 by SpigotMC
20:22:36 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"fa
828eb":1059 by SpigotMC
20:22:36 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"fa828e
b":1059 by SpigotMC
20:22:36 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"fa828e
b":1059 by SpigotMC
20:22:36 [SEVERE] Exception in thread "main"
20:22:36 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast
to java.util.Collection
20:22:36 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig
.java:188)
20:22:36 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.j
ava:73)
20:22:36 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:245)
20:22:36 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLaunc
her.java:54)
20:22:36 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by XxTheEnderGodxX** [comment]
Wow just looked back at my config and it went all over the place
But i know for sure that the config isnt the problem here this error does not occur in the config because this would my 4th time changing my config and this same [SEVERE] Exception in thread "main" pops up. I truly dont think its the config

**Comment by XxTheEnderGodxX** [comment]
disabled_commands: null
ip_foward: true
listeners:
 max_players- 100
 fallback_server- Hub
 host- 192.168.1.13:25565
 bind_local_address- true 
 ping_passthrough- false
 tab_list- GLOBAL_PING
 default_server- Hub
 forced_hosts-
 tab_size- 60
 force_default_server- true
 motd- '&1Another Bungee server'
 query_enabled-
 false query_port- 25565
 timeout- 30000
 connection_throttle- 4000
 servers-
 Hub-
 address- 192.168.1.13:25566
 restricted- false
 motd- '&1Just another BungeeCord - Forced Host'
 Factions-
 address- 192.168.1.13:25567 
 restricted- false
 motd- '&1Just A Test'
 online_mode- true
player_limit: -1
stats: 16af2c09-a338-49e6-8d53-2e03ab219e20
 permissions-
 default-
 - bungeecord.command.server
 - bungeecord.command.list
 admin-
 - bungeecord.command.alert
 - bungeecord.command.end
 - bungeecord.command.ip
 - bungeecord.command.reload
permissions: {}
groups:
  XxTheEnderGodxX:
  - admin

**Comment by XxTheEnderGodxX** [comment]
that was my config after fixing it

**Comment by kamcio96** [comment]
why do you use -  instead of : ?

**Comment by XxTheEnderGodxX** [comment]
The console told me to replace it and it said could not code it with :

**Comment by XxTheEnderGodxX** [comment]
so i used this and it worked

**Comment by XxTheEnderGodxX** [comment]
20:22:36 [SEVERE] at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig
.java:188)
20:22:36 [SEVERE] at net.md_5.bungee.conf.Configuration.load(Configuration.j
ava:73)
20:22:36 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:245)
20:22:36 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLaunc
her.java:54)
20:22:36 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by XxTheEnderGodxX** [comment]
this is the error
I dont understand what this means

**Comment by kamcio96** [comment]
you have wrong config, check it on online yaml parser, and you should edit it by notepad++
eot

**Comment by XxTheEnderGodxX** [comment]
i dont have notepad++ but i have notepad so i will use that.
And also i will try to use the yaml parser website.

**Comment by XxTheEnderGodxX** [comment]
It actually wont let me use notepad on it... i just tried and it doesnt make the list like this:
disabled_commands: null
ip_foward: true
listeners:
 max_players- 100
 fallback_server- Hub
 host- 192.168.1.13:25565
 bind_local_address- true 
 ping_passthrough- false
 tab_list- GLOBAL_PING
 default_server- Hub
 forced_hosts-
 tab_size- 60
 force_default_server- true
 motd- '&1Another Bungee server'
 query_enabled-
 false query_port- 25565
 timeout- 30000
 connection_throttle- 4000
 servers-
 Hub-
 address- 192.168.1.13:25566
 restricted- false
 motd- '&1Just another BungeeCord - Forced Host'
 Factions-
 address- 192.168.1.13:25567 
 restricted- false
 motd- '&1Just A Test'
 online_mode- true
player_limit: -1
stats: 16af2c09-a338-49e6-8d53-2e03ab219e20
 permissions-
 default-
 - bungeecord.command.server
 - bungeecord.command.list
 admin-
 - bungeecord.command.alert
 - bungeecord.command.end
 - bungeecord.command.ip
 - bungeecord.command.reload
permissions: {}
groups:
  XxTheEnderGodxX:
  - admin

**Comment by XxTheEnderGodxX** [comment]
it makes it in one row
So im going to use word pad

**Comment by XxTheEnderGodxX** [comment]
YOU ARE DA BEST!!!!

**Comment by XxTheEnderGodxX** [comment]
OMG THANKS SO MUCH TO U ALL IT WORKED!!! I LOVE U ALL :D

**Comment by XxTheEnderGodxX** [comment]
If you like minecraft a lot and want to join my server u can when its done :D

**Comment by XxTheEnderGodxX** [comment]
And if u would like i will give u staff or something yall are the best

**Comment by XxTheEnderGodxX** [comment]
Hi guys
Im back with a new problem... I dont know why but my server was perfectly running without any problems until today when i tried to turn on my server it would only let me connect. I have the same config and i did update it(BungeeCord).
I do have a custom ip but it wont work. Only my ip address and the ip address doesnt even work if someone else is connected to the wi-fi. It is also set up, I did Ip forward it but it wont work.
I really need help to get my server back to normal. Im going to send my console and my config under this message
---------------------------------------------------------------------------------

**Comment by XxTheEnderGodxX** [comment]
C:\Users\XxTheEnderGodxX\Desktop\Minecraft Server\Proxy>java -Xmx1024M -jar Bung
eeCord.jar -o true
17:25:55 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
17:25:55 [INFO] Using standard Java compressor. To enable zero copy compression,
 run on 64 bit Linux
17:25:55 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"9cf57ca":1068
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"9cf5
7ca":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"9cf57ca":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"9c
f57ca":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
17:25:55 [WARNING] Forced host server pvp is not defined
17:25:55 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"9cf
57ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNA
PSHOT:"9cf57ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"9
cf57ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
17:25:55 [INFO] Listening on /192.168.1.13:25565
17:26:00 [INFO] [/192.168.1.13:53589] <-> InitialHandler has connected
17:26:00 [INFO] [/192.168.1.13:53585] <-> InitialHandler has connected
>

**Comment by XxTheEnderGodxX** [comment]
----------------------------------------------------------------------------------
This was my console and what it said ^

**Comment by XxTheEnderGodxX** [comment]
---------------------------------------------------------------------------------
This is my config down below |
                                              V

**Comment by XxTheEnderGodxX** [comment]
groups:
  XxTheEnderGodxX:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: 100
stats: bba52443-b1f1-47d7-a846-5ca34e81b0d7
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- max_players: 100
  fallback_server: Hub
  host: 192.168.1.13:25565
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  default_server: Hub
  forced_hosts:
    pvp.md-5.net: pvp
  tab_size: 60
  force_default_server: true
  motd: '&1ThunderCraftMC: &b24/7| Invite Friends!!'
  query_enabled: false
  query_port: 25565
timeout: 30000
connection_throttle: 4000
servers:
  Hub:
    address: 192.168.1.13:25566
    restricted: false
    motd: '&1ThunderCraftMC: &bNow With Hub!'
  Factions:
    address: 192.168.1.13:25567
    restricted: false
    motd: '&1ThunderCraftMC: &bNow With Hub!'
  Marry:
    address: 192.168.1.13:25568
    restricted: false
    motd: '&1ThunderCraftMC: &bNow With Hub!'
ip_forward: false
online_mode: true

**Comment by XxTheEnderGodxX** [comment]
![myconfigpic png](https://cloud.githubusercontent.com/assets/12076356/7693313/7cc3e382-fd84-11e4-9d88-c10945d9e739.jpg)

**Comment by Janmm14** [comment]
maybe you should put this with a better description in a spogotmc.org forum post (or in a new issue)

**Comment by XxTheEnderGodxX** [comment]
i will create a new issue post thx

**Comment by benaryorg** [comment]
I just want to add one (or a few more) thing(s): this is not Twitter, you **can** put multiple sentences into a single comment without running into a limit.

You also really want to **use Notepad++**, you just don't know yet.

And please for the sake of the people trying to actually help you, **use [pastebin](http://pastebin.com).

By the way, you should have a look at *Markdown* and how to properly use it on GitHub (just google `github flavoured markdown`).


Thank you.
