### ISSUE TITLE
Bungee Cord Crash

### ISSUE THREAD

**Issue by nuno1212s** [SpigotMC/BungeeCord#1447]
Hello, I am getting some severe crashes in my bungee cord instance, combined with tons of error messages saying:
Query: Incorrect Magic! 127.0.0.1:(random ass port, that varies)

I have searched the all mighty interweb but found no issue like mine, I only have my plugin, which does not make any query requests (Only to the MongoDB instance, that also has an error, but it still works, if you need me to post it, please ask :P!)
Thank you!

**Comment by acecheese** [comment]
This is most likely someone sending bad query requests to your server in order to down it.

Disable query in the config.yml

**Comment by Janmm14** [comment]
The whole log often helps.

**Comment by nuno1212s** [comment]
I have fixed it, just disabled query. Thanks anyways
