### ISSUE TITLE
BungeeCord using extremly much CPU%

### ISSUE THREAD

**Issue by johandrex** [SpigotMC/BungeeCord#1448]
Hello, recently my BungeeCord server has been using extremly much CPU from my dedicated server. Here's the dedicated server I'm using for BungeeCord plus my 12 Minecraft servers: http://www.ovh.ie/dedicated_servers/enterprise/2014-MG-128.xml and the bungeecord is only having lag spikes when it's 400-500 players on the network.

For example when I log on my Minecraft server and spams "/Pong Test" it is working fine. But when I log on the BungeeCord server and spams the same thing the messages is slowly coming out at once since the BungeeCord is having lag spikes.

Please view the pictures down below, which were taken with 5-10 seconds between.
http://embed.gyazo.com/64338fe37caa6bf0e0a3cde51860b4f0.png
http://embed.gyazo.com/5900952e67e1f7deaac54693fffe4364.png
http://embed.gyazo.com/c78c59cab3371a0d7462ef484c85ce70.png
http://embed.gyazo.com/4bf0891fcc715f45fd1366e586b38716.png
http://embed.gyazo.com/ab6573a2b42f94fdd4e1f8756995a7b9.png

BungeeCord plugins: AdressLimit, AdvancedBungeeAnnouncer, BungeeAdminTools, BungeeOnlineTime, BungeeTabListPLus, BungeeWeb, COmmandControl, CommandFo, CommandSyncServer, EMPBungee, MaximumOnline, MyPing, ServerListPlusUniversal, UltimateBungee, YamlerBungee

**Comment by Phineas-0510** [comment]
How much RAM do you have dedicated to BungeeCord?

**Comment by johandrex** [comment]
Currently 4 GB since I though that would help

**Comment by Phineas-0510** [comment]
When you say "For example when I log on my Minecraft server", do you mean directly to the Minecraft server without connecting to the proxy in any way?

**Comment by johandrex** [comment]
Yeah, I were currently disabling IPWhitelist for the test.

**Comment by Phineas-0510** [comment]
Hmm... is the Bungee on a separate Linux server to the Minecraft servers?

**Comment by johandrex** [comment]
No it's not.

**Comment by johandrex** [comment]
It was BungeeOnlineTime that were the issue. Thanks for the help though

**Comment by Janmm14** [comment]
Let's link the spigotmc thread: http://www.spigotmc.org/threads/bungeecord-using-extremly-much-cpu.61769

**Comment by johandrex** [comment]
Not needed anymore, thanks though
