### ISSUE TITLE
Genesis server - Client crash to desktop attempting to break tesseract.

### ISSUE THREAD

**Issue by Halikar** [SpigotMC/BungeeCord#1449]
Log was requested by trcx.

Pastbin of log is here:

http://pastebin.com/Ztw1SJYG

**Comment by md-5** [comment]
Don't specifically support mods, see other cofh tickets

**Comment by Halikar** [comment]
While I do understand that, trcx specifically requested this log in the OTE IRC channel. I assume he wants it for comparison.

**Comment by md-5** [comment]
Not sure who trcx is or what OTE is, maybe you should report it to their tracker
