### ISSUE TITLE
High cpu usage then crash

### ISSUE THREAD

**Issue by Yselith** [SpigotMC/BungeeCord#1453]
Hello,

I'm hosting modded cauldron servers and i'm using bungeecord, since 4 mounth i use a custom version that prevent the crash from the multiverse without troubles. Yesterday started a high cpu usage, it can go to 700% and i don't find the cause.

With the last bungeecord version it does the same thing, when i start it's ok and after few minutes the usage increase and then down, again and again... 

Two day ago 79 players was online and i got no problems at all. And today with 9 players i get lag spike then crash..

My questions are :

If it was my bungeecord version, why this thing started after 4 mounth without anychange. With or without plugin it still happens, with some version of bungeecord too.

Somes are talking about DDOS but i can't detect it.

VisualVM:
http://img11.hostingpics.net/pics/516193visu.png

CPU Usage:
http://img11.hostingpics.net/pics/861620400.png

Plugins BungeeCord:
BungeeAdminTools - BungeeTabListPlus -BungeeWeb - BungeeYAML - Mineversechat -  PlayerTabComplete - SwiftMOTD - YamlerBungee

Edit 1: It seem to be a memory leak, actually with 45 players bungee using 7g

**Comment by Yselith** [comment]
I found the problem, memory leak of bungeecord caused by a mod : OpenModularTurrets-1.7.10-1.3.4-27.jar

I don't know if it's a bungeecord issue or openmodularturrets, https://github.com/Poenjabiesous/OpenModularTurrets/issues/60

**Comment by md-5** [comment]
Reopen with a memory dump
