### ISSUE TITLE
Bungee Huge Lags on #1059 build.

### ISSUE THREAD

**Issue by IlPicasso** [SpigotMC/BungeeCord#1455]
Huge lags & large amount of player disconnects at build #1059 
http://hastebin.com/oxuwokuhuw.avrasm

**Comment by mcraftpete** [comment]
Hi IIP , did you solve any of this , the more recent versions of bungeecord I too have been experiencing problems with high cpu and high memory as well as these odd lag spikes , on 1059 my server eats up memory over time and eventually after a few hours starts to lag out the individual servers , am considering downgrading bungee see if it fixes and wondered if you had already tried something similar ?

**Comment by Janmm14** [comment]
At first I suggest looking at plugins, removing one by one and test ifthat plugin did it.

**Comment by Xayanix** [comment]
It's bungeecord issue, md_5 can't fix at now because He dont know what is causing this issue.
You can ignore this error with this commit https://github.com/OvercastNetwork/BungeeCord/commit/2b06ebc7508ed385e0d3f4131b248856f4d378c5

Server won't kick players but ignoring is not a fix.

**Comment by minecrafter** [comment]
Are you sure @Xayanix? md_5 closed _many_ issues like this one with cc3a8c06.

**Comment by Xayanix** [comment]
Yes im sure, i compiled own BungeeCord with https://github.com/OvercastNetwork/BungeeCord/commit/2b06ebc7508ed385e0d3f4131b248856f4d378c5 and i have no problems at now.

**Comment by minecrafter** [comment]
The fix of OvercastNetwork@2b06ebc and md_5's cc3a8c0 are _very_ different.

**Comment by md-5** [comment]
They do the same thing, only mine does it properly.
