### ISSUE TITLE
ProxiedPlayer add visual location.

### ISSUE THREAD

**Issue by nikosgram13** [SpigotMC/BungeeCord#1457]
It would be very useful to create a method on the player where it can get their location, but not change it. It is not relatively difficult nor wants any great effort to be added.

Can we get a packet where it steals from the connection between the player and the server the packet with id `0x04`.

Minecraft protocol: http://wiki.vg/Protocol#Player_Position

It is useful because we can run effects from the proxy to all players on all servers. #1292.

@md-5 think about it.

API Example:
```java
proxiedPlayer.getPosition();

proxiedPlayer.playEffect(effect, proxiedPlayer.getPosition(), volume, pitch);

@Data
public class Position{
    int x;
    int y;
    int z;
}
```

**Comment by yawkat** [comment]
not sure if this is really bungees job and it has little sense without implementing other packets. maybe implement it using plugin messages instead.

**Comment by nikosgram13** [comment]
#### Testing:

![screenshot 267](https://cloud.githubusercontent.com/assets/3318873/7445861/4fb050a0-f1cd-11e4-84ea-8566be7922ba.png)

**Comment by xxyy** [comment]
This might be useful, but I agree that it seems out of scope for Bungee.
Such functionality could possibly be handled by a plugin/external module
comparable to ProtocolLib on Spigot, which would open some new
possibilities with BungeeCord.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included. For free!

**Comment by acecheese** [comment]
http://www.spigotmc.org/resources/api-bungeepacketlistenerapi.6155/

**Comment by Samistine** [comment]
@nikosgram13 Where can you get the plugin you made, or any related info.

**Comment by nikosgram13** [comment]
@Samistine I don't have this code anymore.

**Comment by Samistine** [comment]
I am trying to pass data very similar to what you are doing here. In my case, I want to cache player rank data on bungeecord, when a player joins a server it sends back there group and caches it, so I can spin up a rest service on bungeecord that exposes players ranks

**Comment by nikosgram13** [comment]
I used the DefinedPacket. Example: (protocol module)

```java
package net.md_5.bungee.protocol.packet;

import io.netty.buffer.ByteBuf;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import net.md_5.bungee.protocol.AbstractPacketHandler;
import net.md_5.bungee.protocol.DefinedPacket;
import net.md_5.bungee.protocol.ProtocolConstants;

@Data
@ToString
@NoArgsConstructor
@EqualsAndHashCode( callSuper = false )
public class PlayerPosition extends DefinedPacket
{
    double  x;
    double  y;
    double  z;
    boolean onGround;

    @Override
    public void read( ByteBuf buf, ProtocolConstants.Direction direction, int protocolVersion )
    {
        x = buf.readDouble();
        y = buf.readDouble();
        z = buf.readDouble();
        onGround = buf.readBoolean();
    }

    @Override
    public void write( ByteBuf buf, ProtocolConstants.Direction direction, int protocolVersion )
    {
        buf.writeDouble( x );
        buf.writeDouble( y );
        buf.writeDouble( z );
        buf.writeBoolean( onGround );
    }

    @Override
    public void handle( AbstractPacketHandler handler ) throws Exception
    {
        handler.handle( this );
    }
}
```

Then I append this code to `net.md_5.bungee.protocol.AbstractPacketHandler`:
```java
public void handle( PlayerPosition playerPosition ) throws Exception { }
```

And end I add the method `handle( PlayerPosition playerPosition )` to `net.md_5.bungee.connection.UpstreamBridge`:
```java
@Override
public void handle( PlayerPosition playerPosition ) throws Exception
{
    //Change the Connection's location.
}
```

**Comment by nikosgram13** [comment]
HEH :smile: Also I add the protocol to `net.md_5.bungee.protocol.Protocol`

```java
...
GAME {
	{
		...
		TO_SERVER.registerPacket(0x01, Chat.class);
		TO_SERVER.registerPacket(0x04, PlayerPosition.class);
		TO_SERVER.registerPacket(0x14, TabCompleteRequest.class);
		...
	}
},
...
```

**Comment by acecheese** [comment]
May I just reiterate that there is an API that allows you to add custom handlers, instead of editing the main code?

**Comment by nikosgram13** [comment]
Try this: http://www.spigotmc.org/resources/api-bungeepacketlistenerapi.6155/
