### ISSUE TITLE
Is it possible to remove "InitialHandler has connected" on every ping

### ISSUE THREAD

**Issue by Fishy246** [SpigotMC/BungeeCord#1459]
Is there a option to turn of this feature, as it makes the console very spammy, and quite possibly takes up a lot of log room

An example of the console spam that i am receiving is something like this

20:01:21 [INFO] [/127.0.0.1:57259] <-> InitialHandler has connected
20:01:22 [INFO] [/127.0.0.1:57266] <-> InitialHandler has connected
20:01:22 [INFO] [/127.0.0.1:57273] <-> InitialHandler has connected
20:01:23 [INFO] [/127.0.0.1:57280] <-> InitialHandler has connected
20:01:23 [INFO] [/127.0.0.1:57287] <-> InitialHandler has connected
20:01:23 [INFO] [/127.0.0.1:57294] <-> InitialHandler has connected
20:01:24 [INFO] [/127.0.0.1:57301] <-> InitialHandler has connected
20:03:28 [INFO] [/127.0.0.1:57324] <-> InitialHandler has connected
20:03:28 [INFO] [/127.0.0.1:57332] <-> InitialHandler has connected
20:03:28 [INFO] [/127.0.0.1:57339] <-> InitialHandler has connected
20:03:28 [INFO] [/127.0.0.1:57346] <-> InitialHandler has connected
20:03:29 [INFO] [/127.0.0.1:57353] <-> InitialHandler has connected
20:03:29 [INFO] [/127.0.0.1:57360] <-> InitialHandler has connected
20:03:30 [INFO] [/127.0.0.1:57367] <-> InitialHandler has connected
20:03:32 [INFO] [/127.0.0.1:57374] <-> InitialHandler has connected

**Comment by xxyy** [comment]
This has already been requested and rejected with notion of log filters,
but I still want this.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included. For free!

**Comment by Janmm14** [comment]
@xxyy @Fishy246 I suggest using either custom forks or @md-5 @Thinkofdeath add a config option.

**Comment by Fishy246** [comment]
@xxyy @Janmm14 If i forked Bungeecord what section would i go to to get rid of this feature

**Comment by Fireflies** [comment]
@Fishy246 [here](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L275) is the exact line you want to remove :smile:

**Comment by Fishy246** [comment]
Thank you @Fireflies you just saved me whole a lot of time 😊

**Comment by md-5** [comment]
#1484
