### ISSUE TITLE
Reduce bungee security manager messages

### ISSUE THREAD

**Issue by FurmigaHumana** [SpigotMC/BungeeCord#1461]
What im sugesting is simple: Instead of showing the full stacktrace everytime a plugin performs a restricted action, reduce it to just a warning, or with a way for us to customize it.

But is this security manager really necessary? I get it that most developers are tutorial-followers but not all of them, a few of them actually knows what their are doing, all plugins running on my bungeecord server are made by me and I have full comprehension of my code and what it is doing.

Some APIs have its own scheduler, which are usually developed to do a specific kind of task so they have great performance, but we have to avoid using it because of this bullshit notification and maybe future blocking.

The reload system will mostly never be implemented, we all know it will never be smooth, a simple configuration file reload is already messy. So no need to worry about threads staying alive after a reload or stuff like that

From my point of view this is pretty useless, just annoy and do nothing it says it does ( at least not yet, but its been there for a while and still nothing )

Without considering that we can't even set the java policy to actually prevent harm to the server on shared machines.

**Comment by yawkat** [comment]
First of all, you should not rely on java security managers to secure your shared host. 

Second, you can either use my classloader patch or simply create the threads in an async task to circumvent this issue. 

Third, if you really really need to you can still disable the security manager using a custom fork, agents or reflection.

**Comment by FurmigaHumana** [comment]
It's not for security and I do not own a shared host, its just a kind of cheap access control :hand: 

But anyway... as you said yourself, there is countless ways to bypass this manager, it does not provide "security" of any kind, just problems.

I'm currently patching this everytime I update the proxy.
