### ISSUE TITLE
Random Bungee crashes just started two days ago.

### ISSUE THREAD

**Issue by akoldfart** [SpigotMC/BungeeCord#1462]
Can someone look error log what is causing random Bungee Crash. These just started after running Bungee many months without problems. No changes in configuration. Just random shutdowns... 

http://pastebin.com/gcyz6NX3

**Comment by md-5** [comment]
Java bug

**Comment by akoldfart** [comment]
So, just a Java Bug. Is there anything I can do to fix this?

**Comment by NickG365** [comment]
You could try upgrading to Java 7u80 or Java 8.
