### ISSUE TITLE
Double player

### ISSUE THREAD

**Issue by PhanaticD** [SpigotMC/BungeeCord#1465]
A player reported he could not get on a server on my network. This is the disconnect message: http://pastebin.com/SkQ14StA

According to /list from essentials he was still on that server though, even though /find from bungee reported him as being elsewhere. I tried kicking the ghost player but it did not seem to help

Nocheat also verifies this issue [NoCheatPlus] DataMan inconsistencies: missing online players (1) | changed player instances (1)

I cannot find anything in the actual spigot server logs to see what would cause it

**Comment by TheModKing** [comment]
I think I found the issue a player named Deathbeats666 told me that she used a duplicating player glitch

**Comment by TheModKing** [comment]
I can connect again :D

**Comment by PhanaticD** [comment]
this is related to https://github.com/SpigotMC/BungeeCord/issues/1441

**Comment by Techcable** [comment]
@TheModKing 
Is your client modified at all?
