### ISSUE TITLE
Server connected to bungeecord crashes "packet-encoder"

### ISSUE THREAD

**Issue by gameplayerhd** [SpigotMC/BungeeCord#1467]
Tried using BungeeCord build 1044 and 1059

BungeeCord error: http://pastebin.com/PJRJxybu
Lobby Crash Server Dump: http://pastebin.com/su9VgAcR

Fallback server crashed too. Default and fallback server crashes using 700% CPU

Any ideas?

**Comment by Janmm14** [comment]
The packet-encoder bungee crash is already known and in other issues. Is your bungee running on the same machine as your backend servers? Maybe that's why they crash.

**Comment by md-5** [comment]
#1489
