### ISSUE TITLE
can not set the connection throttled

### ISSUE THREAD

**Issue by donbubu** [SpigotMC/BungeeCord#1470]
I set the connection throttled to 10000 ms in the bungee settings, but i can rejoin without have to wait for. I test it with 20000 but nothing happens. Rejoin with no wait. Have i need mor to do as set connection_throttle: 10000 ?

**Comment by Janmm14** [comment]
The throttle is currently disabled as it caused some problems. I don't know ehich problems, maybe searchung through commit messages helps.
