### ISSUE TITLE
BungeeCord - Ip Forwarding

### ISSUE THREAD

**Issue by J0ker98** [SpigotMC/BungeeCord#1472]
I have an issue with the setup of my BungeeCord intallation. I have setted bungeecord to true in my server's spigot.yml but when I try to connect, for example, to the factions server using the direct ip it tells me that I need to enable the IP forwarding in my bungeecord configuration. The problem is that I already have it enabled. All works good when I connect to bungee without the direct ip and then switch server using the /server command... Where is the problem?

Here my BungeeCord config.yml:
http://pastebin.com/bn6TWT6v

Here my Spigot spigot.yml:
http://pastebin.com/zj709MR2

My BungeeCord version is: git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"d1e1ce4":1060 by md_5
My Spigot version is: git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)

How can I fix my issue?

**Comment by thinkofdeath** [comment]
Directly connecting to the backend servers is not supported and insecure, they should be firewalled

**Comment by J0ker98** [comment]
How I'm supposed to do that?

**Comment by Janmm14** [comment]
Directly connecting to the backend servers of bungeecord is not supported.

As anyone ca detup your backend server as a server for their own bungee, its possivle they can join with spoofed uuid and wrong name, so its insecure to be able to join your backend servers not theough bungeecord

**Comment by J0ker98** [comment]
What I'm trying to do is make players join with an ip like factions.minecraftsmp.org so they get directly on the factions server, I'm not trying to make players join without bungee.

**Comment by kamcio96** [comment]
use forced host

**Comment by J0ker98** [comment]
I've already setted it up but it says "if you wish to use ip forwarding enable it in your bungeecord config"... Is possible that my subdomain is not setted up correctly? I've setted it up so, for example, factions.minecraftsmp.org is pointed to minecraftsmp.org:23350 (the port where the factions server is hosted)

**Comment by kamcio96** [comment]
All DNS records should be A and pointed to BungeeCord

**Comment by J0ker98** [comment]
So if my bungeecord is on port 25565 I point all my subdomain to minecraftsmp.org:25565 and then bungee do the other stuff?

**Comment by kamcio96** [comment]
yes :D you just set it in config.yml

**Comment by J0ker98** [comment]
Thanks;D
