### ISSUE TITLE
Minecraft Server, I can join but friends cant

### ISSUE THREAD

**Issue by XxTheEnderGodxX** [SpigotMC/BungeeCord#1473]
This is my new issue i have. I actually need help again on the Bungee Cord. Yesterday i turned on my server for others to join, but as i turned it on later i noticed no one came on so i asked my friends why they didnt join. One of them said it was because it said "Cant Resolve Host Name" and they typed in the ip exactly as it was supposed to be. I do have a custom ip btw. Anyway my other friend said that their screen said existing connection was forcibly closed by the remote host. Im not completely sure how to fix this because i also updated my Java for my computer. I really need some help to get the server up and running again.
P.s. My server ran perfectly before this happend.
My console and my Config will be down below.

**Comment by XxTheEnderGodxX** [comment]
C:\Users\XxTheEnderGodxX\Desktop\Minecraft Server\Proxy>java -Xmx1024M -jar Bung
eeCord.jar -o true
17:25:55 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
17:25:55 [INFO] Using standard Java compressor. To enable zero copy compression,
run on 64 bit Linux
17:25:55 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"9cf57ca":1068
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
17:25:55 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"9cf5
7ca":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"9cf57ca":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"9c
f57ca":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
17:25:55 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
17:25:55 [WARNING] Forced host server pvp is not defined
17:25:55 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"9cf
57ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNA
PSHOT:"9cf57ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"9
cf57ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
17:25:55 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
17:25:55 [INFO] Listening on /192.168.1.13:25565
17:26:00 [INFO] [/192.168.1.13:53589] <-> InitialHandler has connected
17:26:00 [INFO] [/192.168.1.13:53585] <-> InitialHandler has connected

**Comment by XxTheEnderGodxX** [comment]
--------------------------------------------------------
My Console is above and next is my Config
--------------------------------------------------------

**Comment by XxTheEnderGodxX** [comment]
https://cloud.githubusercontent.com/assets/12076356/7693313/7cc3e382-fd84-11e4-9d88-c10945d9e739.jpg

**Comment by XxTheEnderGodxX** [comment]
Oh also my ingame name is XxTheEnderGodxX

**Comment by XxTheEnderGodxX** [comment]
Omg ok well Nevermind!! I found out that it was the custom ip that i messed up on
My server is back up and i fixed it :D

**Comment by Yive** [comment]
I recommend you remove that picture a few comments ago since it shows your backend IP.
