### ISSUE TITLE
Forge 1408 and Bungeecord

### ISSUE THREAD

**Issue by devryb** [SpigotMC/BungeeCord#1476]
I setup a test server with just forge 1408 and same with the client.
I downloaded the latest bungeecord and tried to connect to my test server.

The client gets this message:
http://puu.sh/hX7Zk/56f0bdc797.png

Client log:
http://pastebin.com/Hub6jA6r

Server log:
http://pastebin.com/xpCkrebh

Bungeecord log:
http://pastebin.com/3RJzbDPH

Doing these exact same tests with 1403 doesn't have this issue

https://github.com/MinecraftForge/MinecraftForge/issues/1891

**Comment by dualspiral** [comment]
There was a check on the FML version that (tried) to stop old FML client working. As Lex correctly noted, we try to stop old clients from connecting - but I bet with FML being merged into Forge, FML is no longer reported as a separate mod.

Should be simple for me to fix this. I'll look into it now.

**Comment by dualspiral** [comment]
@devryb While you're waiting for this to get pulled - https://dl.dropboxusercontent.com/u/28705212/BungeeCord.jar works.

**Comment by devryb** [comment]
Awesome thanks!

**Comment by md-5** [comment]
#1477
