### ISSUE TITLE
BungeeCord does not properly handle private/default (package) Listener classes

### ISSUE THREAD

**Issue by Brian-Graham** [SpigotMC/BungeeCord#1478]
BungeeCord does not use Class#setAccessible for when registering a private listener class (in cases where you don't want them to be seen).

I can't seem to locate exactly where the problem is, probably in EventBus or PluginManager, but if the inherited listener class is default (package) or private then it prevent event locating, as I outlined here: http://www.spigotmc.org/threads/bungeecord-cant-pull-events-from-an-abstract-listener.67885/

**Comment by md-5** [comment]
Intended.

We would check this at register time, but Java provides no API to do so.

**Comment by Nubebuster** [comment]
What does this mean and how do I get around this?

**Comment by Outfluencer** [comment]
> What does this mean and how do I get around this?

By making the function public

**Comment by Nubebuster** [comment]
> > What does this mean and how do I get around this?
> 
> By making the function public

Not helpful.

Turns put the problem had nothing to do with the custom event. In bungeecord you cannot have an anonymous Listener. The listener was the problem.
