### ISSUE TITLE
Which does not operate controls

### ISSUE THREAD

**Issue by Dylan3250** [SpigotMC/BungeeCord#1480]
Hello,

The basic commands such as / or greload / IP work correctly when I arrive on my server. However all other basic commands (/ server, / send, ...) do not work and tell me they do not exist.

I tried to start the game since my user or directly from the console BungeeCord, it changes nothing.

Here is my setup: http://pastebin.com/rXdnKBsW

Thanks
___________________________________________________________
Bonjour,

Les commandes de bases telles que /greload ou /ip fonctionnent correctement lorsque j'arrive sur mon serveur principal. En revanche toutes les autres commandes de bases (/server, /send, ...) ne fonctionnent pas et m'indiquent qu'elles n'existent pas.

J'ai essayé de les lancer depuis mon utilisateur en jeu ou directement depuis la console du BungeeCord, ça ne change rien.

Voici ma configuration: http://pastebin.com/rXdnKBsW

Merci d'avance...

**Comment by agusztin** [comment]
Error in syntax, try this config
http://pastebin.com/eg8vGiaR

**Comment by Dylan3250** [comment]
There aren't change... :/ But I have a error: http://pastebin.com/WptGuZkH

**Comment by agusztin** [comment]
Your config.yml works well in my bungee cord server
Maybe is a plugin

**Comment by nikosgram13** [comment]
Your plugins & your OS?

**Comment by minecrafter** [comment]
Check your `modules.yml`

**Comment by Dylan3250** [comment]
Not plugins saw that when I disable it does not change ...
I haven't modules.yml: /
_________________
Ce ne sont pas les plugins vu que quand je les désactive ça ne change rien...
Je n'ai pas de modules.yml :/

**Comment by agusztin** [comment]
Re install bungee cord
Use latest version

**Comment by Dylan3250** [comment]
It's good, thanks ;) !
