### ISSUE TITLE
Players can't Connect to the bungee server 

### ISSUE THREAD

**Issue by jppabs115** [SpigotMC/BungeeCord#1482]
I've setted up a BungeeCord server but for some reason other players can't connect to the server only me and my brother so meaning it doesn't work for people that is not connected to my internet also pople can connect to the Hub server which is linked to the BungeeCord when they /server its says unknown command :p but it works for us because we are connected to the Bungee server and they are just connected to a normal Bukkit server

also here is a link to my BungeeCord Config 
http://pastebin.com/gkjbRSw8

**Comment by agusztin** [comment]
What is the error?
try join with the yourIP:25568

**Comment by jppabs115** [comment]
yea i did that i can connect the prob is others cant....

**Comment by agusztin** [comment]
You connect with localhost:25568 or your public ip?
Maybe is a firewall issue

**Comment by jppabs115** [comment]
yea i can connect with localhost:25568 i port forwarded 25568 and since we have two internet my brother connect to the other one and he cant join but ehrn he connected to where im connected it worked my brother used my external ip

**Comment by jppabs115** [comment]
can anyone still help me?

**Comment by Janmm14** [comment]
Maybe u get more help at spigotmc.org forum. if u are in the same local network your brother has to use your local network ip.on windows openn cmd and type in ipconfig then there should be a line with a ip like 192.168 often. let your brother use that ip. else let your brother try out all the ip listed there

**Comment by jppabs115** [comment]
thats not the solution i was looking for is Players cant connect to the bungeecord server but my lecal Ip address works for me and my brother just not other differnet IP addresses

**Comment by jppabs115** [comment]
Update: I've been opening port in my firewall from the inbound and outbound rules i added the 25568 port and still doesn't works pls can anyone still help me?

**Comment by Janmm14** [comment]
Well this issue is not about bungeecord itself. You just configured your router/firewall/anything else wrong. You need to enable forwarding for that port also in your router, how its named depends on the company created the router.

**Comment by jppabs115** [comment]
I port forwarded the ports from 25565 to 25568 when i open a port checker tool the 25565 to 25567 was opened but 25568 was closed, the lobby,prison and factions server of mine was ok people can connect except the Bungee Server maybe i should test if i put the bungee in 25565 will it still work?

**Comment by Janmm14** [comment]
just try it out. you also just need to open the port bungee is running on
