### ISSUE TITLE
Can connect to vanilla/bungee, cannot connect to Cauldron.

### ISSUE THREAD

**Issue by Zilacon** [SpigotMC/BungeeCord#1483]
I am trying to setup a 1.7.10 bungee modpack hub. I have seen many network do this before me so i know its possible.

I am using MineTick for the vanilla server, it has bungee support and am able to run it perfectly fine connecting to it and running bungee.

Now i am trying to connect KCauldron Build 69 1.7.10 modpack servers such as RR3 + New Mainline and Agrarian Skies 2 to the hub and connect to them.

When i attempt to do /server ags2, nothing happens for 30 seconds, then it shows on the agrarian skies server "Zilacon timed out" i have changed every config option possible even pumped the timeout time to 10000 on cauldron as its set on bungee which didnt change anything, still stuck at 30 seconds.

This happens on multiple modpacks, to multiple players. The bungee/vanilla server works perfectly fine when simply connecting to the vanilla part its just trying to get to the cauldron part thats bugging out.

I tried using builds 1068, 1049, and 985. 1068 and 1049 showed the server as a "non compatible FML server" while 985 shows it as "Vanilla" so i think that ones working correctly.

Any help on this would be great!
Thank you.

**Comment by Zilacon** [comment]
Just tried using spigot, unlike MineTick the server is completely unjoinable now.
http://i.imgur.com/YhD8SLy.png

Used Spigot 1.7.10 B1657 from Yives mirror.
No errors on bungee, however when joining server it says:
````
Internal Exception: java.IOException: An established connection was aborted by the software in your host machine.
&
Internal server error.
````

MineTick did not have any of these errors, any idea whats going on? I would have thought spigot would be more compatible then MineTick with Bungeecord.

**Comment by devryb** [comment]
Hey, theres a limitation in Spigot that causes that too many channels registered error.
I have previously fixed this in my own fork here:

https://github.com/devryb/Spigot/commit/179bc8dae03a5fe7ee5b872ef2145d7aabc74c0d

**Comment by md-5** [comment]
Not bungee issue

**Comment by Zilacon** [comment]
@md-5 But yet a bungee version given to me by YIVE fixes all of my connection issues?
Yup totally not a bungee issue, love how you just kick everyone out the door without even investigating.

**Comment by md-5** [comment]
>@md-5 But yet a bungee version given to me by YIVE fixes all of my connection issues?

You stated above, as did @devryb that it is a SPIGOT issue. Which makes my statement "not a bungee issue" completely correct.

**Comment by Zilacon** [comment]
@md-5 My main issue and the issue i later described were 2 completely different issues.

I said that connecting to cauldron servers with bungee would make everyone time out and disconnect them. This was the primary issue.

I also said i was using MineTick for my vanilla HUB server which worked flawlessly.

I then said for testing purposes i tested it on Spigot and Paperspigot which gave a connection issue when trying to join the server. Also which was fixed due to YIVE giving me a recompiled version of spigot that worked the same as MineTick but this issue was completely separate from Bungee.

Build 985 of Bungee shows the V for Vanilla on the HUB server while any build after 985 shows X for Incompatible FML Server. But on both 985 and any other builds connections timed out and did not connect to any KCauldron OR Cauldron server.

After posting this issue on yives website forums he replied to me with a fixed version of Bungee which is also listed on his Cauldron download page saying "Bungee does not work with Cauldron heres the fix (Download)" And his version did INDEED fix all of my connection issues for me and all of the players helping me test it.

However his version still shows the VANILLA hub server as a X and Non Compatible FML server unlike Build 985. If someone YIVES version could be fixed to show the correct type of server it would be the perfect running bungee version for any modded network.
