### ISSUE TITLE
BungeeCord not starting up

### ISSUE THREAD

**Issue by AuzziPuppy** [SpigotMC/BungeeCord#1486]
Hey I am using the latest (successful) build of Bungee and my server will NOT start up no matter what I do or try. The only plugins I am using is Enjin... Any ideas? Here is config:

http://pastebin.com/nNPRFvzt

**Comment by kamcio96** [comment]
wrong config, go to forum ;)
it isn't bungee issue

**Comment by AuzziPuppy** [comment]
^ I updated the config and its still giving me the error

**Comment by kamcio96** [comment]
where is it?
