### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by mcwnuq** [SpigotMC/BungeeCord#1487]
http://pastebin.com/raw.php?i=GU5huzs6
#1068
java -server -Xmx24G -XX:MaxDirectMemorySize=2g -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -jar BungeeCord.jar

**Comment by yawkat** [comment]
version?

**Comment by kamcio96** [comment]
latest

**Comment by md-5** [comment]
latest is not a version. What does the version command say.

**Comment by md-5** [comment]
Also you won't get support with those weird GC options

**Comment by Janmm14** [comment]
24 gb is too mich. that leads to too hige gc pauses causing crashes. MAXIMUM ram per 500 players should be 1gb. Also just delete the -XX parameters. only use those if you get issues.
