### ISSUE TITLE
Bungeecord starts without errors but then...

### ISSUE THREAD

**Issue by NotLazy** [SpigotMC/BungeeCord#1488]
Bungeecord appears to start without errors, but once it gets to the listening on 0.0.0.0:25565(i cant change this other then the port or else bungee fails to start) it starts taking a shit load of RAM and my processor starts taking a hit. i've tried starting bungee without any other programs and the same happens, its come to the extreme point once where i was unable to stop the bungeecord cmd.exe process and my computer blue screened. Side note(might have something todo with it): doing mass editing to the config makes bungee un-startable. i can edit some ports, the bungee admins, and admin group permissions and default group permissions, and i can edit the default server ip limitedly. I've had to reset my config multiple times, i've even tried a fresh install of bungee. the only plugin i use is AnimMOTD which outputs one error on startup saying it failed to check for an update. Might i add that if i go into minecraft and try to ping the IP it pings forever(doesnt even time out) and upon trying to connect just gets you stuck in a "Connecting to server" screen. In the console log below you'll notice there is no stop to it because typing "end" into console does nothing. it just stays silent and actually increases the amount of resources it uses.

Console is as follows(with minor censoring at the start for privacy reasons):
C:\Users\-----\Desktop\-----\Bungee>title Bungee

C:\Users\-----\Desktop\-----\Bungee>java -Xmx512M -jar BungeeCord.jar
19:39:53 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
stalled.
19:39:53 [INFO] Using standard Java compressor. To enable zero copy compression,
 run on 64 bit Linux
19:39:53 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT
:"9cf57ca":1068
19:39:58 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
lert.jar, provider=JenkinsModuleSource())
19:39:58 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
nd.jar, provider=JenkinsModuleSource())
19:39:58 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
st.jar, provider=JenkinsModuleSource())
19:39:58 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
nd.jar, provider=JenkinsModuleSource())
19:39:58 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
server.jar, provider=JenkinsModuleSource())
19:39:58 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
reconnect_yaml.jar, provider=JenkinsModuleSource())
19:39:59 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
SHOT:"9cf57ca":1068 by SpigotMC
19:39:59 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
19:39:59 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"9c
f57ca":1068 by SpigotMC
19:39:59 [INFO] Loaded plugin AnimMOTD version 1.3 by lite20
19:39:59 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"9cf5
7ca":1068 by SpigotMC
19:39:59 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
19:39:59 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"9cf57c
a":1068 by SpigotMC
19:40:00 [WARNING] Forced host server pvp is not defined
19:40:00 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNA
PSHOT:"9cf57ca":1068 by SpigotMC
19:40:00 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
19:40:00 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"9
cf57ca":1068 by SpigotMC
19:40:04 [INFO] [AnimMOTD] Could not check for new version. This version might b
e outdated...
19:40:04 [INFO] Enabled plugin AnimMOTD version 1.3 by lite20
19:40:04 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"9cf
57ca":1068 by SpigotMC
19:40:04 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
19:40:04 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"9cf57
ca":1068 by SpigotMC
19:40:16 [INFO] Listening on /0.0.0.0:25565

**Comment by Janmm14** [comment]
1) try out without any plugin, if then there is not sich a performance problem, report to the author and close this.

2) if the problem persists without any plugin, download this: https://visualvm.java.net/ and send some screens of the different tabs you have after opening the bungee process on the left.

INFO: you can't change the ip to whatever as your pc needs to be able to get the requests sent to the ip (0.0.0.0 is listening to any ip the pc has access to)

**Comment by NotLazy** [comment]
i cant change it to localhost or 127.0.0.1 which are both localhosting ip's along with 0.0.0.0 i know i cant change it to something like 165.224.845.99. ill try that visualvm. but i also know the plugin isnt the problem because it was working fine before with this plugin. but to please you i will try.

Thanks for the reply.

**Comment by NotLazy** [comment]
Fixed! it appears it is a bug with the animMOTD caused by live update. thanks though
