### ISSUE TITLE
 Could not connect to default or fallback server

### ISSUE THREAD

**Issue by CoolBanana27** [SpigotMC/BungeeCord#1492]
When I try to join my server or anyone does it will say Could not connect to default or fallback server.  I have watched many youtube vids and followed all the directions.  I don't know what to do can someone help?

**Comment by CoolBanana27** [comment]
PLEASE HELP!

**Comment by kamcio96** [comment]
config?

**Comment by Puddanator** [comment]
This just means that the server your trying to connect to is most likely down.

**Comment by kukubaczek** [comment]
Your lobby/fallback server is on? Give config.yml

**Comment by Phineas-0510** [comment]
@CoolBanana27 What's your config.yml?
