### ISSUE TITLE
Bungee Cord Native Library Issue on Centos

### ISSUE THREAD

**Issue by ergology** [SpigotMC/BungeeCord#1496]
03:34:18 [INFO] Could not load native library: /tmp/bungeecord-native-cipher8216482943626086177.so: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /tmp/bungeecord-native-cipher8216482943626086177.so)
03:34:19 [INFO] Could not load native library: /tmp/bungeecord-native-cipher7282728797066690550.so: /usr/lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /tmp/bungeecord-native-cipher7282728797066690550.so)
03:34:19 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
03:34:19 [INFO] Using native code compressor
03:34:19 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"918d722":1070
03:34:19 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
03:34:19 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
03:34:19 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
03:34:19 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
03:34:19 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
03:34:19 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
03:34:19 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [WARNING] Forced host server pvp is not defined
03:34:19 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"918d722":1070 by SpigotMC
03:34:19 [INFO] Listening on /0.0.0.0:25565

**Comment by yawkat** [comment]
`Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.`

**Comment by minecrafter** [comment]
If you're willing to invest some work, [you can use native cipher on CentOS](https://minimum.io/recompiling-bungeecord-native-libraries-for-use-on-centosrhe/).
