### ISSUE TITLE
Empty Packet protocol error

### ISSUE THREAD

**Issue by UnioDex** [SpigotMC/BungeeCord#1503]
http://i.imgur.com/MIs9kEg.png

some users receive this error and kicking.

**Comment by Janmm14** [comment]
see #1474

**Comment by md-5** [comment]
Empty packets are not allowed, maybe a mod?

**Comment by UnioDex** [comment]
My plugins:
http://i.imgur.com/BY2kab9.png

I dont have any mods.

**Comment by Janmm14** [comment]
@md-5 1.7 clients are sending empty packets as someone verified. Maybe he has a 1.7 / 1.8 network.
I suggest just ignoring packets which are empty and go on.

**Comment by UnioDex** [comment]
Yes i am using 1.7, 1.8 network.

**Comment by Janmm14** [comment]
Use bungeecord build 1065, check for that got added in build 1066
