### ISSUE TITLE
[Forge] Getting kicked from BungeeCord when going to a Mystcraft world.

### ISSUE THREAD

**Issue by AnodyneEntity** [SpigotMC/BungeeCord#1507]
It's as the title as, I'm wondering if there is anything that can be done about this. I've tried looking for a few hours for a solution, unfortunately I found none. As it stands, when I transfer to a Mystcraft age while using BungeeCord, I get this CME error

http://pastebin.com/xbiHRvZW

 on login and I'm unable to reconnect unless I manually edit my dimension location. Wondering if you know whats going on @dualspiral

**Comment by dualspiral** [comment]
I think it's a mod issue - nothing to do with Bungee itself. I think Galacticraft had the same problem - they did solve it eventually (there is a closed issue in their issue logs somewhere). I also noticed that cpw added something to FML 1.7 a long while ago to sync dimensions (server side), but if you are using Cauldron, you won't have this fix (it was after the whole DMCA thing) and as a result, everything fails. Most mods used custom packets to try to solve this, but they are not supported by Bungee, particularly during the login phases.

To be honest, I don't think this is a Bungee issue - you should raise this with the mod author, it's a problem that has been solved before.

(Referenced commit: https://github.com/MinecraftForge/FML/commit/dfebcafd49550b8c3f90c6c028ef0d7f3a13e607)
