### ISSUE TITLE
Server Icon doesn't work

### ISSUE THREAD

**Issue by Nograe** [SpigotMC/BungeeCord#1510]
Hello,
I have a problem with my server icon. ( http://i.imgur.com/Qo3dsPk.png )
The image is named server-icon.png, it's located in the root folder of bungee, and it's 64x64 pixels.

Thank you for you help.

**Comment by Janmm14** [comment]
What is your issue? Error? Or just not displayed?

**Comment by Nograe** [comment]
No, the image is just not displayed...
And when I send a message in the server, I have that error: http://pastebin.com/N4YAbg92

**Comment by ThePhineas** [comment]
You can't use too complex images because of BungeeCord's encoding, and that looks a tiny too complex for it's liking.

**Comment by Nograe** [comment]
The image is 64x64 pixels...

**Comment by ThePhineas** [comment]
Yes, but that doesn't matter to Bungee, your picture has too high of a resolution/too many colours.

**Comment by Nograe** [comment]
I've try already try many icons...
Hypixel and others servers that have Bungee can use icons, how is it possible?

**Comment by ThePhineas** [comment]
What version of Bungee do you use?

**Comment by Nograe** [comment]
I use the latest stable build, the #1071.

**Comment by md-5** [comment]
All icons that work with vanilla will work. Maybe yours doesn't work with vanilla?
