### ISSUE TITLE
[Modded] Fluids: value already present

### ISSUE THREAD

**Issue by Katelyn-SN** [SpigotMC/BungeeCord#1524]
I've tested this multiple times and it only happens when Bungeecord is between the server and the client.

```
http://paste.atlauncher.com/view/630aeacf
```

**Comment by Katelyn-SN** [comment]
@dualspiral This is something you will want to take a look at.

**Comment by dualspiral** [comment]
Why would I _want_ to take a look at it? I'm happy to be asked, but please don't tell me I want to look at it.

We're missing a lot of information here. Versions? Mods? Are any of them core mods? Can you isolate the mod? What's the setup?

My feeling is that it might be a FML thing, but before reporting it as such, I'd rather someone made sure it isn't Bungee itself.

**Comment by Katelyn-SN** [comment]
I tested this against FTB Infinity with the latest 1448 forge based KCauldron (for bungee support) and a bungee with all the necessary pull requests added from you to make it work with the latest pack version. This issue is not present without bungeecord between the client and the server.

**Comment by dualspiral** [comment]
It was a FML problem - https://github.com/MinecraftForge/MinecraftForge/issues/1973

Please check with the latest version of Forge.

**Comment by Katelyn-SN** [comment]
This is solved! :)
