### ISSUE TITLE
Bungeecord randomly kicking users and using 300% cpu

### ISSUE THREAD

**Issue by FilthyPorty** [SpigotMC/BungeeCord#1529]
10:10:28 [SEVERE] [Portanna] <-> DownstreamBridge <-> [Tamriel] - encountered exception

http://pastebin.com/F4m74D49

The server, from time to time, kicks 5 or 6 players randomly giving that error in console and giving in chat the message "The server you were previously on went down... ".

Bungeecord bukkit.yml http://gyazo.com/16dc750f6e9143f3fda03524f125d47c
Bungeecord config.yml listeners: http://gyazo.com/a9ea3c2cf4a9deb7e0ea0e8e785876bb
Using Bungeecord latest build and Spigot 1.8.3 latest build

After 5/6 hours online, bungeecord starts acting strange, no errors in console, but starts to take more and more cpu, until there's no cpu left. The server has 2 CPUs 4 cores each (xeon) and 32 gb ram. Previously I gave Bungeecord no limits about RAM, but still the same. The problem is just the cpu usage, ram seems to be unaffected.

Please help fix this, because is very annoying. I'm not going to put multiple bungeecord because it's pointless, We have 4 servers in which just 1 server has 70 users and the others just from 10 to 20.

The player kicking and the cpu overload are not connected, they happen randomly without notice

**Comment by Techcable** [comment]
Run "jstack" when the large cpu increases happen.
Run it like 7 times with a few seconds in between, then pastebin the output of each one.

**Comment by kamcio96** [comment]
Do you have latest version? EmptyByteBuf shouldn't be in MinecraftDecoder

**Comment by FilthyPorty** [comment]
@kamcio96 I'm using the latest build downloaded from Spigot. 

@Techcable http://pastebin.com/JsyZaDPH This is one, I'm posting the other ones in another comment below

**Comment by kamcio96** [comment]
Do you have epoll enabled?

**Comment by FilthyPorty** [comment]
How do I check if it is enabled?

**Comment by Janmm14** [comment]
@FilthyPorty you see that after startup. Try to set the maximum ram to 2 or 4 gb

**Comment by FilthyPorty** [comment]
@Janmm14 You mean after the Bungeecord startup
@Techcable Here are 7 jstack of bungeecord using 250% cpu :
http://pastebin.com/xEEwz6E9
http://pastebin.com/P2NgtQKq
http://pastebin.com/hnVm00gq
http://pastebin.com/9THvMTte
http://pastebin.com/kwtyatWF
http://pastebin.com/YmyKe7Yw

**Comment by Techcable** [comment]
Try without Adfly4Bungee.
It seams to be constantly parsing regexes.

**Comment by FilthyPorty** [comment]
When users are kicked in lobby this appears in the server's console:
peppapig lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
I'll try to disable Adfly4Bungee and I'll tell if something changes. But the kicking problem is something else I think.

**Comment by Techcable** [comment]
Well the 300% cpu and random kicking are probably related.
It could possibly be that Adfly4Bungee is starving the netty io threads.

**Comment by FilthyPorty** [comment]
I don't think so, because the kicking problem started today, while the 300% cpu started like one month ago.

**Comment by FilthyPorty** [comment]
Sorry i closed for mistake. lol misclicked

**Comment by FilthyPorty** [comment]
Apparently it kicks the player to the lobby every 4/5 minutes or whenever they write the same word twice. I checked ChatGuard, but there are no punishments set for flooding. Maybe this could help somehow.

**Comment by kamcio96** [comment]
Where did you download bungee?

**Comment by FilthyPorty** [comment]
http://ci.md-5.net/job/BungeeCord/

**Comment by kamcio96** [comment]
So, i dont know

**Comment by FilthyPorty** [comment]
@kamcio96 I'm using #1​07​1 build.
Now bungeecord.jar is using over 370% cpu
jstack here -> http://hastebin.com/udojehetij.avrasm

**Comment by Techcable** [comment]
@FilthyPorty 
Have you tried removing adfly 4 bungee?

**Comment by FilthyPorty** [comment]
I'm restarting now with adfly4bungee disabled. I'll write if something changes. I coud not restart before because there were 70 people on the server.

**Comment by FilthyPorty** [comment]
When restarting with Adfly4Bungee disabled, no one is able to write in chat. Trying to fix this, after that I tell you if the cpu load problem is solved or not.

**Comment by nerdtron123** [comment]
whats your plugins

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
