### ISSUE TITLE
BungeeCord aborting start.sh & crashing?

### ISSUE THREAD

**Issue by ThePhineas** [SpigotMC/BungeeCord#1530]
A couple of times today, my BungeeCord has randomly crashed.
I have recently added the plugin called HubMagic (yesterday), not sure if thats the issue.

Here are the crash messages: 
<img width="1424" alt="screen shot 2015-07-08 at 18 47 28" src="https://cloud.githubusercontent.com/assets/6209808/8578080/87c1c608-25a4-11e5-880b-aa44718c2dc8.png">
<img width="1268" alt="screen shot 2015-07-08 at 07 56 15" src="https://cloud.githubusercontent.com/assets/6209808/8578084/8cd5b78a-25a4-11e5-98c2-491de8c4121d.png">

RAM: 512MB to BungeeCord
Bungee Version:  This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"faf9034":1015 by md_5
Plugins: 
<img width="1175" alt="screen shot 2015-07-08 at 19 09 48" src="https://cloud.githubusercontent.com/assets/6209808/8578142/ed9b6600-25a4-11e5-8be8-53eb4cf551ac.png">
Crash report: http://pastebin.com/Fph7RnJV

Thank you for all your help!

**Comment by minecrafter** [comment]
I am the author of HubMagic. HubMagic shouldn't be causing your server to crash with SIGSEGV.

**Comment by ThePhineas** [comment]
@minecrafter Hmm, have any idea why it's crashing then?

**Comment by md-5** [comment]
Java bug :\

Really wish we could do something to help @normanmaurer work around it
