### ISSUE TITLE
Netty 4.1 update breaks compressors

### ISSUE THREAD

**Issue by ninja-** [SpigotMC/BungeeCord#1531]
I am opening this bug just to ask a question to @md-5 @thinkofdeath if any of them have any clue why updating netty version in bungee causes compression to break? It's not rare to see a netty commit with "fix for something memory leak" so it would be cool if we could keep up with it.

**Comment by 9190281** [comment]
Also having this issue.

**Comment by minecrafter** [comment]
My educated guess is that the native compression is the issue

**Comment by md-5** [comment]
Not a Bungee bug as we don't use this Netty version and it isn't released as stable.
