### ISSUE TITLE
/send <server> <server>

### ISSUE THREAD

**Issue by PhanaticD** [SpigotMC/BungeeCord#1537]
This is a feature request, can we get /send to be able to do server to server so that the command can be done from the console instead of having to log on and do /send current <destination>

**Comment by marcoslater** [comment]
I second this, it would be quite useful in various situations.

**Comment by kamcio96** [comment]
but it could be done by plugin, write it ;)

**Comment by PhanaticD** [comment]
nah its just a slight expansion on something already there
