### ISSUE TITLE
Cant setup BungeeCord

### ISSUE THREAD

**Issue by richardtda1** [SpigotMC/BungeeCord#1539]
So i just buyed 2 servers (1hub) (1Factions) and later probably another server to come.

The problem is i just cant setup bungeecord, i followed a tutorial https://www.youtube.com/watch?v=yjUt8CfkiYE but at the part where he opens the console to put his information from the my sql database it just goes wrong. I will post it the config and console here.

groups:
  richardtda1:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: -1
stats: ebfc033b-a2e2-4720-9ed8-79c298429c08
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- max_players: 100
  fallback_server: hub
  host: 0.0.0.0:25565
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  default_server: hub
  forced_hosts:
    pvp.md-5.net: pvp
  tab_size: 60
  force_default_server: true
  motd: '&1Another Bungee server'
  query_enabled: false
  query_port: 25577
timeout: 30000
connection_throttle: 4000
servers:
  hub:
    address: 5.200.23.179:26122
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  factions:
    address: 5.200.23.176:25769
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
ip_forward: false
online_mode: true

---------------------------------------------------------------------------------
15.07 19:42:51 [Server] INFO Command not found
15.07 19:42:14 [Server] INFO Command not found
15.07 19:41:37 [Server] INFO Command not found
15.07 19:41:05 [Server] INFO Command not found
15.07 19:41:05 [Server] INFO Command not found
15.07 19:41:05 [Multicraft] Auto-saving world...
15.07 19:40:59 [Server] INFO Command not found
15.07 19:40:22 [Server] INFO Command not found
15.07 19:39:44 [Server] INFO Command not found
15.07 19:39:07 [Server] INFO Command not found
15.07 19:38:29 [Server] INFO Command not found
15.07 19:37:52 [Server] INFO Command not found
15.07 19:37:15 [Server] INFO Command not found
15.07 19:36:37 [Server] INFO Command not found
15.07 19:36:00 [Server] INFO Command not found
15.07 19:35:22 [Server] INFO Command not found
15.07 19:34:45 [Server] INFO Command not found
15.07 19:34:08 [Server] INFO Command not found
15.07 19:33:30 [Server] INFO Command not found
15.07 19:32:53 [Server] INFO Command not found
15.07 19:32:15 [Server] INFO Command not found
15.07 19:31:38 [Server] INFO Command not found
15.07 19:31:00 [Server] Startup Listening on /0.0.0.0:25565
15.07 19:31:00 [Multicraft] Skipped 26 lines due to rate limit (30/s)
15.07 19:31:00 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"81d1c46":1075 by SpigotMC
15.07 19:31:00 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"81d1c46":1075 by SpigotMC
15.07 19:31:00 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"81d1c46":1075 by SpigotMC
15.07 19:31:00 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"81d1c46":1075 by SpigotMC
15.07 19:31:00 [Server] INFO Loaded plugin BungeeSuite version 3.0 by luke199
15.07 19:31:00 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"81d1c46":1075 by SpigotMC
15.07 19:31:00 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
15.07 19:31:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
15.07 19:31:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
15.07 19:31:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
15.07 19:31:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
15.07 19:31:00 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
15.07 19:30:59 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"81d1c46":1075
15.07 19:30:59 [Server] INFO Using native code compressor
15.07 19:30:59 [Server] INFO Using OpenSSL based native cipher.
15.07 19:30:58 [Multicraft] Loaded config for "[custom] custom.jar"
15.07 19:30:58 [Multicraft] Starting server!
15.07 19:30:58 [Multicraft] Loading server properties
-----------------------------------------------------------------------------
Please help as soon as possible!

**Comment by yawkat** [comment]
This bug tracker is for bungee bugs only, not setup help.

**Comment by richardtda1** [comment]
So where should i post this

**Comment by jflory7** [comment]
@richardtda1 Please use the forums for troubleshooting help. https://www.spigotmc.org/forums/bungeecord-help.70/
