### ISSUE TITLE
Port Forwarding help with Bungee cord?

### ISSUE THREAD

**Issue by Oliy1492** [SpigotMC/BungeeCord#1542]
I have all the bungee working, I can connect on the PC I am hosting it on but when I am on my other PC I can't, I know I have to port forward but I don't know what to port forward and what I have tried did not work.

Here is my config: http://pastebin.com/uaBDSH89

Help, please?

**Comment by yawkat** [comment]
This is not a forum, this is a bug tracker.

**Comment by Janmm14** [comment]
Please post your issue on https://spigotmc.org
