### ISSUE TITLE
Incorrect JavaDoc in PlayerHandshakeEvent

### ISSUE THREAD

**Issue by FearThe1337** [SpigotMC/BungeeCord#1546]
Javadoc of [PlayerHandshakeEvent](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/event/PlayerHandshakeEvent.java#L10-13) states that:

Event called to represent a player first making their presence and username known.

As far as I can tell however this was removed due to a more modern protocol? in this [commit](https://github.com/SpigotMC/BungeeCord/commit/4257b81d8c188d4ccfc11879a8e6f316a68cb700)

As far as I can tell the HandShake event/packet is now nothing more then a handshake with no username or uuid information.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
