### ISSUE TITLE
Bungeecord - No colors on chatting

### ISSUE THREAD

**Issue by roopekoo** [SpigotMC/BungeeCord#1547]
I tested color chatting on my spigot server without Bungeecord connection. The results were positive, colors on chatting.
I connected to Bungeecord and tested color chatting. The results were negative. No colors at all.
There isn't any error messages at all. Color messages appear in default white color
I used these messages:
&6Hi! &5This is test&r &l#1
&6Hi! &5This is test&r &l#2

![2015-07-23_15 44 12](https://cloud.githubusercontent.com/assets/6078487/8861714/a78bb5ec-3194-11e5-8778-fa23c8d91120.png)
![2015-07-23_15 48 42](https://cloud.githubusercontent.com/assets/6078487/8861719/abe8b298-3194-11e5-8e78-a86593c9b2f8.png)

Plugins that i'm using
I'm using Bungeecord version: BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"6343416":1076
CraftBukkit version git-Spigot-74e8786-a3cb1bc (MC: 1.8.7) (Implementing API version 1.8.7-R0.1-SNAPSHOT)
The problem lies in Bungeecord.

**Comment by Janmm14** [comment]
Which plugins do you use?

**Comment by roopekoo** [comment]
@Janmm14 
I use these Bungeecord plugins:
AlwaysOnline, BungeeChatPlus-0.6.1-SNAPSHOT, BungeeTabListPlus-2.0.5 and bungeeyaml-1.1

**Comment by Janmm14** [comment]
Try without BungeeChatPlus please

**Comment by roopekoo** [comment]
Still not working!
