### ISSUE TITLE
BungeeCord randomly crashing.

### ISSUE THREAD

**Issue by PLAnonymousPL** [SpigotMC/BungeeCord#1548]
Hello,

I have a problem with BungeeCord. Yesterday I started my server (+/- 200 players).
In first 2 hours everything is good, but later BungeeCord was randomly crashing (every 20-30 minutes) and CPU use is + 700%. :(

Here is server log: http://pastebin.com/DAWKJSKk

Anyone can help me?
Thanks guys,

**Comment by greatman** [comment]
Hmm, the error tells it's OutOfMemory. Not sure if it's related to https://github.com/SpigotMC/BungeeCord/pull/1522

**Comment by weaondara** [comment]
well this seems not to be a bungeeperms issue as there's no bungeeperms related code is the stack trace
check the Xmx param and look for solutions in the bungeecord issue tracker

if you get a stack trace with net.alpenblock.bungeeperms... please post it here
thx
