### ISSUE TITLE
Color codes not working at times.

### ISSUE THREAD

**Issue by InstanceOfDev** [SpigotMC/BungeeCord#1550]
This is the send message method: http://gyazo.com/e729ab81593c95776c1b8be8ad7e986d

This is what happened in game: http://gyazo.com/fc877cdbcb5dc149477badae25aab743 See that some of it is white?

**Comment by md-5** [comment]
Use the component API for accurate colours.

**Comment by InstanceOfDev** [comment]
I was using new TextComponent(ChatColor.translateAlternateColorCodes etc.) is that fine to use?

**Comment by thinkofdeath** [comment]
no, use `TextComponent.fromLegacyText` for that case

**Comment by InstanceOfDev** [comment]
Ah thank you very much.
