### ISSUE TITLE
Crashing my friend's server

### ISSUE THREAD

**Issue by Xayanix** [SpigotMC/BungeeCord#1553]
They are using TOR, just blocked this right now.

But is it issue - http://pastebin.com/mbZSfG1U

**Comment by InstanceOfDev** [comment]
Can you elaborate a bit more?

**Comment by Xayanix** [comment]
I have no idea how he do this, i think he is sending packets to friend's bungeecord.
When he do it, then he have 800% CPU on bungee.

**Comment by Xayanix** [comment]
He is using 1076 bungeecord

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
