### ISSUE TITLE
Crashing my server! CPU 700%

### ISSUE THREAD

**Issue by bartek10256** [SpigotMC/BungeeCord#1554]
Hello!

I have a problem with BungeeCord. Yesterday I started my server (+/- 400 players).
In first 5 hours everything is good, but later BungeeCord was randomly crashing (every 20-30 probably 1 h and 20 minutes) and CPU use is + 700%. :( My server and bungeecord have one machine. And kick my player Timed Out! I have 0 error with log!
Plis help me my friend!

**Comment by yawkat** [comment]
Are you on latest bungee?

**Comment by bartek10256** [comment]
@yawkat 
Yes!

**Comment by Mikgreg** [comment]
Bungee CPU usage often spikes when it runs out of RAM, how much are you allocating to it?

**Comment by Xayanix** [comment]
http://pastebin.com/xg6H47s4
I have same.

**Comment by Mikgreg** [comment]
Read the last line; 
Exception: java.lang.OutOfMemoryError 
You need to allocate more RAM, and if you already have a lot allocated you need to investigate for leaks.

**Comment by Xayanix** [comment]
Man, its crasher.
Someone uses bungee's bug to crash others server.

**Comment by ninja-** [comment]
I have found the bug that the crasher used. I'll try to commit something soon.

**Comment by McLive** [comment]
I have the same problem.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
