### ISSUE TITLE
the Cauldron server ,can't use the BungeeCord

### ISSUE THREAD

**Issue by baq982** [SpigotMC/BungeeCord#1559]
my cauldron server can't use the bungecord, bungecord's version 1075 , cauldron's version 1.7.10,1.1388.1.0

player can connect the cauldron server by bungecord , if he left the server ,and join again , player's client will be quite automatically ,and player can't join the server again before deleting the player's playdates 

if I try to connect the cauldron server without the bungecord , there is no problem.

can you tell me what's the problem????

here is the crash-report
![qq 20150811210756](https://cloud.githubusercontent.com/assets/13748433/9198202/12a48bba-406d-11e5-9df9-707f16e24389.png)

**Comment by baq982** [comment]
who can help me

**Comment by Janmm14** [comment]
You do not get the error if you do not use bungee? Is there a error in the bungee log/console?
