### ISSUE TITLE
Connection spam to my bungee then crash

### ISSUE THREAD

**Issue by Xayanix** [SpigotMC/BungeeCord#1560]
Hi, im using #1076 bungee with java 7 on debian dedicated machine.
This traffic http://pastebin.com/TRFqkg9U caused my bungee to use 400% CPU, i have connection throttling on port 25565 with iptables but it didnt help at all.

Why my bungee get crashed?

**Comment by PhanaticD** [comment]
is there anything in bungee log

**Comment by Xayanix** [comment]
No

**Comment by Janmm14** [comment]
No unusual joins?
Nothing with that ip?

Well its still possible to crash bungee with malicious packets(whoch cause high load), it could also be a dos attac.

**Comment by Xayanix** [comment]
No unusual joins, i saw that was 58 active connections from one IP to 25565 port so i decided to set max connection to 5 to this port.

**Comment by ninja-** [comment]
I have found the bug that the crasher used and confirmed later that the person has tried to use the bug again, after I patched it. I'll try to commit something soon.
