### ISSUE TITLE
If You Wish to use IP Fowarding, Enable it in Your Config

### ISSUE THREAD

**Issue by Cyprez** [SpigotMC/BungeeCord#1565]
Hello,

 I am currently trying to BungeeCord with my friends server (he'll be the creative server, mine will be the hub, and factions), but that is not going so well. Also, I'm not sure if this is a BungeeCord bug, or something I'm not doing correctly.

 Here are my console logs:
http://pastebin.com/3JcX49Xm

 BungeeCord config:
http://pastebin.com/mLxYjHTZ

 Spigot config:
http://pastebin.com/PLWmqcnd

 I appreciate any help.
 Thanks.

By the way, I am using BungeeCord #1078 
http://prntscr.com/85od3f
Also, both servers are running the same version of BungeeCord, and the same version of Spigot, same config files, etc.

**Comment by Janmm14** [comment]
@Cyprez Is this still an issue? Otherwise please close it.

Remember to join only onto the bungeecord ip and not the spigot server's ip.
