### ISSUE TITLE
players timing out or dropping like flies

### ISSUE THREAD

**Issue by Disorbs** [SpigotMC/BungeeCord#1566]
well after i switched to a bungee network players have been getting dropped after we reach 200+ online

idk exactly what it is but i see some of these in the bungee logs

disconnected with: §fReadTimeoutException : null

or just "Timed out"

and another one about peer reset but i think that's when they Close MC out [X] button

all bukkits have -1 for throttle and bungee set to true

bungee version - https://i.gyazo.com/2282a273cf2c76ba9acde1f5909703cb.png

**Comment by RicoswLive** [comment]
I have the same problem

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
