### ISSUE TITLE
Unknown z_stream return code : -3

### ISSUE THREAD

**Issue by Gregin** [SpigotMC/BungeeCord#1567]
So here is the thing, when players join through bungeecord they lag a ton for 5 seconds and they can't join any other servers. 

disconnected with: DecoderException : net.md_5.bungee.jni.NativeCodeException: Unknown z_stream return code : -5 @ io.netty.handler.codec.ByteToMessageDecoder:278

Unknown z_stream return code : -3
19.08 20:21:58 [Server] SEVERE -> UpstreamBridge - encountered exception
19.08 20:19:36 [Server] INFO disconnected with: [Proxy] Lost connection to server.

Caused by: net.md_5.bungee.jni.NativeCodeException: Unknown z_stream return code : -3

**Comment by Janmm14** [comment]
ry running with this startup option as a workaround:  -Dnet.md_5.bungee.native.disable=true

**Comment by ninja-** [comment]
any progress on this? @md-5 @thinkofdeath any of you looked why the native zlib is so buggy?

**Comment by ninja-** [comment]
let me guess...it's because there's no flush() before the compression handler is removed when switching servers?

**Comment by Janmm14** [comment]
@ninja- Just change what you mean and try it out or let Gregin try out.

**Comment by ewized** [comment]
with 4e94c27 connections are giving this http://pastebin.com/8cMZYzaw and preventing them from connecting. With default '256' compression setting.

**Comment by thinkofdeath** [comment]
@ewized What client version?

**Comment by ewized** [comment]
@thinkofdeath The client is 1.8, After further testing if you set the compression level to < 240 the error is constant every time someone logs in, if it was set higher the exception goes away.

**Comment by thinkofdeath** [comment]
Sounds like a netty optimization, not using native buffers for small packets

**Comment by Janmm14** [comment]
@ewized Thought the exception occurs too on default ```256``` compression?

**Comment by ninja-** [comment]
for me the current 'master' is fine as long as I disable the "-1" compression in server.properties (I am the only one with it...?)

**Comment by ewized** [comment]
@Janmm14 It did but its rare, though what @ninja- said that fixes the problems I had.

**Comment by Gregin** [comment]
For anyone still having this problem, try resting your spigot/bukkit/bungee.yml to the defaults. It fixed the problems for me.

I guess I edited something I shouldn't of, or the .yml was not up to date with the current version being run. Hope this helped someone.
