### ISSUE TITLE
"Error occurred while contacting login servers, are they down?"

### ISSUE THREAD

**Issue by HardcoreSwag** [SpigotMC/BungeeCord#1569]
I'm getting this message every time i try to connect to my server.
I have uploaded it in my dedicated server now and suddenly it doesn't work. In local all the servers works great.
The Minecraft Servers are up, why i'm getting this problem?
md5, don't close this issue until the problem is solved, ;)

**Comment by thinkofdeath** [comment]
The issue is with your server not bungeecord, talk with your host.
