### ISSUE TITLE
People can't join my BungeeCord server.

### ISSUE THREAD

**Issue by aotrand** [SpigotMC/BungeeCord#1570]
![c__windows_system32_cmd exe 8_20_2015 5_20_16 pm](https://cloud.githubusercontent.com/assets/13895323/9398780/e66ba8a4-475f-11e5-8645-6271bb931095.png)

**Comment by aotrand** [comment]
I don't understand why nobody can join.

**Comment by kamcio96** [comment]
you have to forward port on your router

**Comment by aotrand** [comment]
I did but none of my friends could join...

**Comment by Janmm14** [comment]
Try joining with your mobile over your mobile data with minechat. Also the log looks like they just pinged your server (put into minecraft server list and got the motd)
