### ISSUE TITLE
Any chance to fix epoll?

### ISSUE THREAD

**Issue by ninja-** [SpigotMC/BungeeCord#1571]
Epoll has been broken for a few years, any chance we could get back to epoll with a fix?

tracking netty bug at
https://github.com/netty/netty/issues/4127

**Comment by md-5** [comment]
It hasn't even been around for a few years, and it's not our bug.

**Comment by ninja-** [comment]
I know. Are you interested to track the progress while I am trying to find the cause?

**Comment by loganspeck** [comment]
@ninja- 
That's unnecessary work for him.

**Comment by ninja-** [comment]
@md-5 found a fix :) it's mentioned in the linked bug, you can have a look. and decide if you want to bring epoll back to live.

**Comment by ninja-** [comment]
@md-5 

https://github.com/ninja-/netty/commit/5795c866c6d2462eff175306c039e9a5e163e279 - a confirmed fix for netty 4.0 :) up to you if you want to bring epoll back to live

**Comment by minecrafter** [comment]
:+1:

**Comment by ninja-** [comment]
@minecrafter depends. it's not a good one for doing a full unit-test (a test that will create 1000 connections and close them all expecting 0 connections? maybe). It's too small for doing a real test.

Also, if you want to get back to epoll you would be faster with throwing IP_TOS out of bungee.

**Comment by minecrafter** [comment]
@ninja- good point.
