### ISSUE TITLE
Bungee Crash (netty?)

### ISSUE THREAD

**Issue by xion87** [SpigotMC/BungeeCord#1572]
Using:
Ubuntu 14, java 8, BC 1078

Bungee server keeping to crash today for like 30 times, i think sometimes is abusing with it, Aikar told me that can be a netty-related
Crash log: http://hastebin.com/omeriveqit.hs

**Comment by xion87** [comment]
Using: 
Ubuntu 14, java 8

Bungee server keeping to crash today for like 30 times, i think sometimes is abusing with it, Aikar told me that can be a netty-related
Crash log: http://hastebin.com/omeriveqit.hs

**Comment by ninja-** [comment]
you have run out of memory (trust me I know what what I am saying)

**Comment by xion87** [comment]
well, why it happening? i am using these plugins:
- bungeeauth
- bungeesuite
- bungeepeerms
- bungeechatfilter
- SkinsRestorer
- Ultimate friends
- Movemenow

**Comment by Janmm14** [comment]
If you'd like to know about memory usage, run ```jmap``` and post reuslts here. See: https://docs.oracle.com/javase/7/docs/technotes/tools/share/jmap.html

**Comment by md-5** [comment]
Java bug
