### ISSUE TITLE
bungee not even trying connection with forge server

### ISSUE THREAD

**Issue by popcorn9499** [SpigotMC/BungeeCord#1577]
when i try to log into my minecraft forge server all i get is a few things on bungees side and nothing appear on my forge server.
this is bungees log http://puu.sh/k0IQz/eacc59749a.png

Forge servers log http://puu.sh/k0IRd/50ddc4329f.png

Clients log http://paste.ee/p/Re1bx
Now i understand that you guys were working to fix this. i also understand that since my forge server has no logs of my connection i am not helping much. but i will also say that if i run cauldron as the server it works. I really dont know whos side needs to do a fix.

bungee git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"bd07be8":1079 by md_5
forge version 10.13.3.1403
mc 1.7.10

hope this helps you guys fix it

**Comment by i9hdkill** [comment]
Try placing a 1.7.10/1.8 protocol hack server as your lobby server. Then switch from this server to your modded server. it should work. (Only tested with cauldron, not sure if its works with Forge standalone)

**Comment by popcorn9499** [comment]
it doesn't work with standalone forge but cauldron does work. and 1.7.10 protocol hack doesnt work and a modified bungee is required to make all this work. but going from lobby to my server crashed my forge client on the spot. a kcauldron is the only cauldron build that i found for the new forge versions. hoping this can be eventually fixed

**Comment by i9hdkill** [comment]
You can use a vanilla BungeeCord and a normal Protocol Hack Build to make it work.
Place the protocolhack spigot as the fallback and lobby server and add as many cauldron or spigot servers as you want:)
