### ISSUE TITLE
BungeeCord Error

### ISSUE THREAD

**Issue by Nograe** [SpigotMC/BungeeCord#1579]
Hello, when I send a message as a player in the lobby server of bungee, I'm kicked and I have this error in the bungee console : http://pastebin.com/03uUtN8M

Thank you for your help.

**Comment by Janmm14** [comment]
Bungeecord version, client version, backend server version?

**Comment by Nograe** [comment]
I have the last stable version of Bungeecord, the 1083. My server is in 1.8 and what's backend please?

**Comment by Janmm14** [comment]
I meant the version of the server "behind" bungee you're trying to connect to, in your case the lobby. (Update to latest if you're not on latest version should be best)

But tbh I don't know what could cause that exception.

Also please include which 1.8 version you're using.

**Comment by Nograe** [comment]
Thank you for trying to help me!
I solved the problem yesterday after 2hours of research..
To help others player that have the same problem : You have to update BungeeCord, and put that in the "run.bat" of your backend server: java -Xss192k -Xmx2G -jar spigot.jar
