### ISSUE TITLE
Unpredictable invisible players

### ISSUE THREAD

**Issue by JokHornsby** [SpigotMC/BungeeCord#1580]
I am creating a Mini Game that utilises dynamic instances.

Players can queue to join the minigame, and a few ticks after the instance is set up, they are ported over to the new server (via Bungee).

However, completely unpredictably, some players appear completely invisible to others and vice versa.
The only solution so far is to have a millisecond wait time of over 250 (ms) between player joins.

However, this means that 100 players take 25 seconds to join the game... So it's not really a viable solution.

**Comment by ninja-** [comment]
This is a spigot related problem

**Comment by JokHornsby** [comment]
So it's totally unrelated to bungee? Players who join the server manually (through their minecraft server list I mean) never seem to be invisible. If you are correct, and are sure that it is a spigot issue, do you happen to know any reasons or solutions related to the problem?

**Comment by ninja-** [comment]
What spigot are you on?

**Comment by JokHornsby** [comment]
Latest (1.8.8), on both the lobby and the instance. I've also tried older versions of spigot (1.8.1, 1.8.4, 1.8.6, 1.8.7) and older versions of bungee too; both with no luck.

**Comment by ninja-** [comment]
Try adding protocolsupport and get everyone to join from 1.7. Might be tablist related

**Comment by JokHornsby** [comment]
Thanks for the suggestion, I'll get back to you on that.

**Comment by Paulomart** [comment]
We had this issue too, a possible workaround for that is to make all players invisible for the joining player, then make them visible after a few ticks.

**Comment by JokHornsby** [comment]
I previously tried the whole invisible then visible fix before, but without the delay. It seems a delay of around 5 ticks fixes this invisibility issue (with around 7 players joining at the same time). Thanks for the help guys, although this problem still needs to be fixed (in the SpigotAPI?). It seems the issue could be with players joining within the same tick or something similar since the issue occours seemingly randomly.

**Comment by Paulomart** [comment]
I think its a syncing issue with the client, maybe spigot sends the right packets, but the client is dropping them because a race condition or something.

**Comment by Janmm14** [comment]
Or maybe the bungee is dropping them as things may not be set up correctly yet after the server switch.

**Comment by Paulomart** [comment]
@Janmm14 I think is reproducible without bungeecord too, but its very rare.

**Comment by Janmm14** [comment]
One could try out using https://www.spigotmc.org/resources/api-bungeepacketlistenerapi.6155/ verbosing all packets and also using a modfied client doing the same.

**Comment by Paulomart** [comment]
Just saying: https://twitter.com/SeargeDP/status/648836545286422528

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
