### ISSUE TITLE
UnsupportedOperationException on connect

### ISSUE THREAD

**Issue by wuuei** [SpigotMC/BungeeCord#1582]
Hello,

recently we began experiencing instant disconnects when joining a Spigot server through Bungeecord, other servers on the same machine worked fine.
As my markdown skills are horrible I have created a pastebin with the error log, I hope it's ok.
http://pastebin.com/hAsHmeTi

The error only happens on builds after # 1082, which updated the netty version.
Could that be the problem?

If you need any further information please let me know.
[My spigotmc.org thread](https://www.spigotmc.org/threads/instant-disconnect-when-joining-server.91731/), in case I forgot to include something in this issue.

**Comment by kamcio96** [comment]
system?

**Comment by wuuei** [comment]
Oh, sorry

Linux server1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64 GNU/Linux

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by kamcio96** [comment]
Now run bungee with -Dnet.md_5.bungee.native.disable

**Comment by wuuei** [comment]
It didn't help :/

Just to be sure, is there a way to tell if it does indeed run with that option?
Is this command correct?
java -Xmx1024M -Dnet.md_5.bungee.native.disable -jar Bungeecord.jar

**Comment by macguy8** [comment]
@wuuei I believe you need to use -Dnet.md_5.bungee.native.disable=true

There's no message printed if it worked, if it didn't you'll see 'Using native code compressor' in your startup log.

**Comment by wuuei** [comment]
You're right, adding "=true" removed the message.
However, while it did remove the native compressor info in the console, the problem still persists.

**Comment by ninja-** [comment]
Yes, Think introduced a regression with that commit. The fix is to remove in.readbytes which uses heap buffers and read to a new direct buffer manually

**Comment by wuuei** [comment]
So, I might have been a little bit fast with blaming Bungee.
Turns out that somehow on 1 of 3 spigot server the "network-compression-threshold" setting changed from "256" to "400". After setting it back to the default Bungee worked again flawlessly.

But it shouldn't matter, right? According to the minecraftwiki the value shouldn't be lower than 64 or higher than 1500, 400 should be fine.

**Comment by md-5** [comment]
@wuuei thanks, that's the info I needed. The bug has been fixed.

**Comment by wuuei** [comment]
Awesome, thank you very much.
