### ISSUE TITLE
Horses kick to fallback server

### ISSUE THREAD

**Issue by karatemaccie** [SpigotMC/BungeeCord#1584]
Riding tamed horses or giving them saddles resolves in disconnecting players to the fallback server. It also gives the following error in the console:

[WARNING] [NAME] <-> DownstreamBridge <-> [WORLDNAME] - bad packet ID, are mods in use!? Did not read all bytes from packet class org.spawl.bungeepackets.packet.server.OutOpenWindow 45 Protocol GAME Direction net.md_5.bungee.protocol.Protocol$DirectionData@338ac1a7

**Comment by kamcio96** [comment]
Plugin bug

**Comment by karatemaccie** [comment]
Yeah I see it now, didn't recognize the package at first, so I just thought I should report it here... Sorry... :/
