### ISSUE TITLE
Double connections

### ISSUE THREAD

**Issue by PhanaticD** [SpigotMC/BungeeCord#1585]
I have been noticing this a lot in my bungee log: http://pastebin.com/kqLtf8Mz

I was able to re-produce it by spam clicking on my server on the multiplayer server list in my client. I got the same exact error message in console, and no essentials plugin commands worked when I logged in and I did not appear to have a skin, it was like I was only partially logged in. Perhaps logins are being accepted twice in a row?

**Comment by prplz** [comment]
I believe this may be a bug in the vanilla client, where it can kind of connect twice.

**Comment by Paulomart** [comment]
I think it could be fixed by throttleing the connections, it's currently disabled in bungee

**Comment by ninja-** [comment]
client bug. harmless

**Comment by PhanaticD** [comment]
Well it is harmful actually because it makes the player invisible to other players, which is really bad in a pvp server as they can damage other players without being seen at all. I had to write a hacky workaround that kicks players if they join at the same time as a disconnect to fix it

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
