### ISSUE TITLE
Invalid session after restarting BungeeCord - requires clients to restart completely.

### ISSUE THREAD

**Issue by mibby** [SpigotMC/BungeeCord#1589]
BungeeCord 1087

After running updates and restarting BungeeCord, some users experience invalid sessions when trying to reconnect through BungeeCord. Is there a reason why BungeeCord loses authorization and requires the client to completely restart?

**Comment by thinkofdeath** [comment]
Invalid session is a client error message sent by the session server directly to the client. Bungee doesn't get a say in that message

**Comment by mibby** [comment]
Is there any reason why the client loses session authorization when restarting BungeeCord though? It seems to happen just about every time, only when restarting BungeeCord.

**Comment by md-5** [comment]
Probably a case of correlation != causation
