### ISSUE TITLE
Bungee Network not even Working

### ISSUE THREAD

**Issue by Zilacon** [SpigotMC/BungeeCord#1590]
I have successfully setup a 1.7 network. Works great no problems.
I have multiple forced host sub domains which correctly link to the servers i have configured on that bungee server.

However when i try to do the same thing with 1.6.4 Bungee + Spigot i get nothing.
Connecting to the hub is impossible through direct connection via localhost:port and forced host through hub1.apocgaming.org.

I have everything setup exactly like i did on the 1.7 bungee network. Any help on this would be great.

And i dont know if this has any relevance but both bungeecord servers are on the same network but on separate dedicated servers with separate local IP's. The ports for both servers are also different 1.6.4 binds to 7800 while 1.7.10 binds to 7801.

**Comment by md-5** [comment]
1.6.4 is not supported, so even if it is a bug it won't get fixed.
