### ISSUE TITLE
Cauldron connections still not fixed?

### ISSUE THREAD

**Issue by Zilacon** [SpigotMC/BungeeCord#1591]
So im using the bungee fix from tcpr.ca which works for my modded network "kinda". I am having multiple players getting timed out and others saying "Enable IP Forwarding in your Config" when it is enabled.

So i tried updating to build 1087 and now no one can connect to any cauldron server just like before i got the bungeefix jar from tcpr.ca.

Could this please be looked into and fixed? This is all for 1.7.10.

**Comment by MatthewM** [comment]
Bungee dropped support for 1.7.10 entirely in recent commits. I doubt this will be fixed.

**Comment by md-5** [comment]
@MatthewM only in the 1.9 branch.

That being said, Forge/Cauldron is a pretty big mess to try and support.

**Comment by MatthewM** [comment]
@md-5 is the Jenkins server on 1.9's branch?

**Comment by md-5** [comment]
Nope. Master / Jenkins still have support for 1.7

**Comment by MatthewM** [comment]
Weird.. .I'm pretty sure I saw a build that dropped it.. I pulled my Cauldron from the network and spun it out as a result.

**Comment by Zilacon** [comment]
Ya the jenkins has support for 1.7 we could login to the hub but we could not login to any cauldron server. Isnt it possible to take whatever lets people connect from the build im using and slap it into the latest version?

I know nothing of java so dont quote me on that, im just trying to find a resolution to my players problems.

**Comment by MatthewM** [comment]
@Zilacon do you know what they are using for the fix? If so someone could submit a PR for it. Be it them or someone else.

**Comment by Zilacon** [comment]
You would have to contact @Yive about that. Hes the one that made the bungeefix jar.

**Comment by Zilacon** [comment]
https://twitter.com/ItsYive is how i contact him.

**Comment by MatthewM** [comment]
@Zilacon nice thing about github is you can [compare repos](https://github.com/SpigotMC/BungeeCord/compare/master...Yive:master).

**Comment by Yive** [comment]
@MatthewM Wrong branch, the build on my site is the forge branch on the repo.

**Comment by MatthewM** [comment]
@Yive maybe that is something that could and should be fixed then? The beauty of OSS and GitHub as well is peer coding. I don't think @md-5 has enough time to go through everything and feels Cauldron is a major concern as it's 1.7.10 and we're going to be on 1.9 soon and that means dropping of 1.7.x support.

Any idea if there will be a Cauldron for 1.8 or 1.9 or should we just wait for Sponge and then get that working with Bungee?
