### ISSUE TITLE
Build 1087, Players not removed from glist online count after disconnect

### ISSUE THREAD

**Issue by c0wg0d** [SpigotMC/BungeeCord#1593]
When I type /glist it will only list a few players online whereas the total online players count is much higher.  It seems like when players connect it never removes them from the "online" list after disconnecting from the server.  Is anyone else seeing this issue?

**Comment by PhanaticD** [comment]
mine is fine, try without any plugins?

**Comment by c0wg0d** [comment]
This appears to be an issue with IdentityOverride, but that plugin has not been updated in a very long time and it's never been an issue until build 1087.  I'm guessing it's an issue with UUID support added to BungeeCord.  Can this be fixed?  It's causing yet another plugin to have issues now also, BungeeTabListPlus is showing players as online that have logged out long ago.  Very frustrating.

**Comment by Janmm14** [comment]
Seems like that plugin is somehow cancelling the PlayerDisconnectedEvent (or how its named here)

**Comment by intangir** [comment]
this can be closed apparently
