### ISSUE TITLE
[Solved] BungeeCord Cant Connect to my server

### ISSUE THREAD

**Issue by theviruss** [SpigotMC/BungeeCord#1594]
Hi I've been having some problems with bungeecord I've tried everything but i couldn't fix it if someone can fix it please tell me
Error: Server is online mode!

**Comment by Jckf** [comment]
Sett online-mode=false in server.properties. Gee.

**Comment by theviruss** [comment]
i did

**Comment by Janmm14** [comment]
Do you have paid minecraft? If not you need to set online-mode to false in bungee's config.yml

However you should have a Auth plugin supporting bungeecord in that case.

**Comment by theviruss** [comment]
you are talking about paid minecraft and cracked minecraft -_- i want someone that can help me

**Comment by Jckf** [comment]
If Bungee kicks you and says the server is in online mode, then it is. Make sure the Spigot server's IP address is correct in the Bungeecord config, and that you have restarted Spigot after updating server.properties.

**Comment by theviruss** [comment]
no still with the same message the server is online mode!

**Comment by theviruss** [comment]
nvm i just solved it it was a problem with the starting script :D
