### ISSUE TITLE
Help, BungeeCord Startup Error

### ISSUE THREAD

**Issue by SpencerHiltbrand** [SpigotMC/BungeeCord#1595]
Noooo. My BungeeCoord won't startup! Please help, error in startup, and config file is listed below.

Error: http://pastebin.com/KRTL0GKr
Config: http://pastebin.com/P6RRKyRE

**Comment by Phoenix616** [comment]
```
forced_hosts: [] 
```
on line 24 probably is the reason for this issue (it's an empty array in yaml {} could be the right syntax there but it's yaml so who knows for sure)
