### ISSUE TITLE
Strange Exception

### ISSUE THREAD

**Issue by MatteCarra** [SpigotMC/BungeeCord#1597]
BungeeCord sometimes makes this strange exception: http://pastebin.com/MYYVR2H5

**Comment by Janmm14** [comment]
Plugins? Bungee version? Are you able to test different versions to get the version where this error started?

**Comment by ninja-** [comment]
it was mentioned before. someone send a chat message while his server was null. no one cared to add a check there that returns if the server is actually null.

**Comment by MatteCarra** [comment]
@Janmm14 I don't know the reason. I think they chat too early.
I sometimes see this exception.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
