### ISSUE TITLE
BungeeCord #1087 with KCauldron-1.7.10-1448.133

### ISSUE THREAD

**Issue by minecraft7net** [SpigotMC/BungeeCord#1600]
Hi,

i have problem with connecting bungeecord #1087 with KCauldron-1.7.10-1448.133

BungeeCord log:
http://pastebin.com/rsjCfULW
KCaludron log :
http://pastebin.com/rsbEiSuF

i have tested with oterh kcauldron version with the same errors (never version to v152) - they sourcre website : https://gitlab.prok.pw/Prototik/KCauldron

thereis any chance to try to add support for that ? please i have currently connected to my bungeecord 30 normal 1.7-1.8 servers with two modded on cauldron-1.7.10-1.1272.06.215-server.jar and everything works fine (MoCreatures and Pixelmon 3.4) - but new - Tekkit Legends needs minimum requires mod versions [Forge@[10.13.4.1448,)] to be available and its now only available by KCauldron-1.7.10-1448.133.

i can make this issue for KCauldron too.

i think there will be more issues like this becouse Tekkit released new official mod pack Tekkit Legens and BlightFall.

if you need more logs and tests let me know - i'll do.

**Comment by dualspiral** [comment]
Looks like one of the mods uses a negative ID, and md-5 has said he won't support that.

**Comment by irgusite** [comment]
Is there a way to find the mod who does that? I use hermitcraft 2 and have the same problem.

**Comment by Janmm14** [comment]
I do not know whether protocollib is running on your platform, but if it does, you can simply look up what data is sent in the packets, like /packet server play -256-0 true or so

**Comment by irgusite** [comment]
It's not possible to show negative packets with protocollib :(
