### ISSUE TITLE
tab list misbehaving when reconnecting

### ISSUE THREAD

**Issue by CodeCrafter47** [SpigotMC/BungeeCord#1601]
When joining a server with an account that is already playing on that server you don't see your self on the tab list. Also you are removed from the tab list of all other players on the server.

Steps to reproduce:
* You need a simple BungeeCord setup: BungeeCord and a single spigot server behind it, online_mode = true
* Join BungeeCord with your Minecraft account
* Start a second instance of Minecraft and join the BungeeCord server again with the same account.
* The Minecraft client that joined BungeeCord first is kicked, The second one joins the server but doesn't see itself on the tab list.

I used BungeeCord build 1087.

BungeeCord log http://pastebin.com/4Q6eNpbV
Spigot log: http://pastebin.com/LKAD0rNi

**Comment by ninja-** [comment]
Wasnt that behaviour disabled on master because bugs...?

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
