### ISSUE TITLE
can't connect to server default

### ISSUE THREAD

**Issue by SkymaxPlay** [SpigotMC/BungeeCord#1602]
Hello,
I created bungee and when I connect to bungee I see this error:
"Could not connect to default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException"
This is configuration bungee: http://pastebin.com/7hbNxYgd
This is configuration spigot: http://pastebin.com/XyaC81M7
Please help me.

**Comment by minecrafter** [comment]
Check if your server IP is correct and your server is online.

**Comment by SkymaxPlay** [comment]
My Server is online

**Comment by kamcio96** [comment]
Poczytaj: https://www.spigotmc.org/wiki/bungeecord-installation/
I od tego jest forum a nie issue ;)

**Comment by SkymaxPlay** [comment]
Ta jasne, poczytaj sobie. Robiłem 10 min przed tym bungee inne bungee i działa a te zrobiłem dokładnie tak jak poprzednie i nie działa. Może wytłumaczysz?

**Comment by ninja-** [comment]
your backend ip is wrong or there is a firewall in place...simple as that

**Comment by SkymaxPlay** [comment]
IP is correct, this bungee is in hosting and I use bungee engine from hosting's offer

**Comment by ninja-** [comment]
then you should reach it from bungee using hosting's internal ip, not external

**Comment by SkymaxPlay** [comment]
how to set spigot's access?

**Comment by kamcio96** [comment]
server.properties daj, hosting czy vps/dedyk?

**Comment by SkymaxPlay** [comment]
Server.properties: http://pastebin.com/j7N7Bfhz
Bungee - hosting pierwszy
Domyślny - hosting drugi

**Comment by kamcio96** [comment]
możliwe ze 2 hostingi się nie widzą, z PC działa Ci bungee?
