### ISSUE TITLE
Race condition with DownstreamBridge and UpstreamBridge

### ISSUE THREAD

**Issue by Mystiflow** [SpigotMC/BungeeCord#1604]
By force closing the Minecraft client you can cause an IOException which appears to be harmless in #579.

The overriden behaviour of ```UpstreamBridge#exception(Throwable)``` when an exception occurs calls ```UserConnection#disconnect()```, as does ```DownstreamBridge#disconnect(ChannelWrapper)```. This causes a race because there is half a second delay for the channel closes in the ```UserConnection#disconnect()``` method, therefore the method can occasionally be called twice.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
