### ISSUE TITLE
Requesting Permission & A Few Questions.

### ISSUE THREAD

**Issue by RandomAltThingy** [SpigotMC/BungeeCord#1607]
I would like to port this (With a similar name, or the same) to PocketMine-MP. I do not mind if you want to host the repo on the Spigot github organisation or not, but this would be a great MCPE feature.

---

**Questions:**
• Is BungeeCord a plugin, or does it wrap around Spigot directly? Like forge.

--- 

**Disclaimer:**
If I am authorized to do this port, all credit to SpigotMC for the name and original code, and credit to me for coding this port of course. 
SpigotMC get access to the whole plugin to make edits or fixes, but this requires hosting repo on the [Spigot Github](https://github.com/SpigotMC). I am fine with this.

**Comment by Cammeritz** [comment]
BungeeCord isn't a plugin.
It's a CMS for multiple spigot servers.
e.g. HiveMC.com or Mineplex.com
You can connect multiple spigot/bungee servers that are running as "virts" and are controlled/connected by the "host" the bungee server. 

Scheme: https://wiki.nitrado.net/de/images/0/0d/Bungee.png
"Spieler" means "Player" in german.

**Comment by RandomAltThingy** [comment]
Alright thanks.

But how come Bungee comes as its own server and not any other dependent jars such as craftbukkit or spigot? So its basically a server software in itself? If so, where is the actual spigot code such as networking etc.

**Comment by RandomAltThingy** [comment]
Oh, used the protocal.

**Comment by xxyy** [comment]
BungeeCord is a completely separate proxy server with its own
implementation of the Minecraft protocol.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by Cammeritz** [comment]
xxyy is right. It's a proxy managing the bukkit servers.
Bungee is forwarding the players information to the bukkit/spigot server :)

**Comment by RandomAltThingy** [comment]
@md_5

**Comment by RandomAltThingy** [comment]
How come we can use Spigot API features then?

**Comment by Cammeritz** [comment]
https://www.spigotmc.org/wiki/bungeecord/

**Comment by Cammeritz** [comment]
And if you want to develop BungeePlugins: https://www.spigotmc.org/wiki/bungeecord-plugin-development/

**Comment by Janmm14** [comment]
> How come we can use Spigot API features then?
BungeeCord sends additional data in one of the earliest packets at connection to the spigot server. It gives the spigot server the skin data, uuid and real ip of the player. For spigot plugins 
basic information about a player can be retrieved through the BungeeCord plugin messaging channel. The plugin messaging channel is already included in the desktop minecraft protocol.

BungeeCord does basically the following thing:
1. Player joins the bungeecord.
2. BungeeCord sends the default (or last server of the player) a "fake player login"
3. BungeeCord starts to just forwarding packets except some about entities to be able to despan them on server change or the ones bungeecord has events for and the chat packet for bungee commands for example. Just look up the source at Upstream / DownstreamBridge (I think it was there...)
4. At server change bungeecord sends the client a world change, while sending "fake logout" to the server he was on and "fake login" to the server he wants to join.
5. Go to number 3.

**Comment by RandomAltThingy** [comment]
So is that why it can connect so fast to a server? How does it query the target server and show kick messages in chat? I need to know this then I can create my software.

**Comment by RandomAltThingy** [comment]
Sorry to spam, but how does it compile with multiple folders like this? And I get that you send fake players packets to spigot server but that doesn't explain how you can access the API. Why not just add as submodule?

**Comment by Cammeritz** [comment]
If you want to start developing Bungee plugins take a look at here:
https://www.spigotmc.org/wiki/bungeecord-plugin-development/ (General Information)
http://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/index.html (BungeeCord API Javadoc)
http://ci.md-5.net/job/BungeeCord/ws/chat/target/apidocs/index.html (BungeeCord Chat API Javadoc)
https://github.com/SpigotMC/BungeeCord/ (Github page of BungeeCord)
https://github.com/SpigotMC/BungeeCord/tree/master/api (Github page of the BungeeCord API)
https://hub.spigotmc.org/ (General SpigotMC/Bungee Developmer Hub)
http://simba.spi.gt/iris/ (IRC for Spigot/Bungee Developers)
https://www.spigotmc.org/forums/bungeecord-plugin-development.23/ (SpigotMC.org Bungee Plugin Development Thread)

Another interesting thing is netty.io. 
Netty is an asynchronous event-driven network application framework
for rapid development of maintainable high performance protocol servers & clients.
If you really need to work with netty.io (u probably won't) and change/influence/order the protocols the way you want without using the Bungee API take a look at here:
http://netty.io/ (Main page)
http://netty.io/4.1/api/index.html (Netty 4.1 Javadoc)
http://netty.io/5.0/api/index.html (Netty 5.0 Javadoc)
http://netty.io/wiki/user-guide-for-4.x.html (Userguide/Tutorial to work with Netty 4.x)
http://netty.io/wiki/user-guide-for-5.x.html (Userguide/Tutorial to work with Netty 5.x)

I hope that this has helped you :)

**Comment by RandomAltThingy** [comment]
It did, some of it. However please read the title. I want to **PORT** it not **DEVELOP** for it ;)

**Comment by md-5** [comment]
Basically BungeeCord connects to two servers, and then pretends that it in itself is a server and the other two servers are different worlds. You're gonna need to implement the MCPE protocol (wiki.vg) at the very least to accomplish this. Certainly won't be easy.

**Comment by RandomAltThingy** [comment]
@md-5 I have people to help with protocal, I can do the rest. But my original question: can I use the name?

**Comment by RandomAltThingy** [comment]
If this was hosted on spigot then I wouldn't mind if you publish it as your own (As long as it is working)

**Comment by md-5** [comment]
No you shouldn't use the name BungeeCord, since your software is not BungeeCord.

**Comment by RandomAltThingy** [comment]
@md-5 It isint, but it could be.

Sorry for this spam but how come entities and block breaking and stuff work since there is no files for them?

Hang on; I've looked in pom.xml and seen bukkit dependency.

**Comment by Janmm14** [comment]
> Sorry to spam, but how does it compile with multiple folders like this?
Multi-Module maven project
>And I get that you send fake players packets to spigot server but that doesn't explain how you can access the API. Why not just add as submodule?
I do not understand in which way you can access the api.

**Comment by RandomAltThingy** [comment]
Access the spigot api features and simple stuff like blocks, player class, etc.

**Comment by RandomAltThingy** [comment]
I could use PocketBungee :)

**Comment by Cammeritz** [comment]
You could :)

**Comment by Cammeritz** [comment]
Remember that you can't user bukkit/spigot librarys for MC-Pocket ^^

**Comment by RandomAltThingy** [comment]
Why would I use libraries? I roll vanilla B)

**Comment by RandomAltThingy** [comment]
https://github.com/RandomAltThingy/PocketBungee

**Comment by Janmm14** [comment]
On bungeecord we do not have access to blocks, the bukkit player class and many other stuff from bukkit.

You need to look at the API / the code to see what is accessible at bungeecord: http://ci.md-5.net/job/bungeecord/ws/api/target/apidocs/index.html

**Comment by Cammeritz** [comment]
If you want to "port" Bungee to your "PocketBungee" then you aren't allowed to use Bungees' source code.
And you first have to know the way that Minecraft-PE is handling it's protocols. I guess it's not netty.io ^^

**Comment by RandomAltThingy** [comment]
Well how come we have horse and mobs in bungeecord if we don't have the classes and stuff?

**Comment by RandomAltThingy** [comment]
I KNOW. I don't wanna copy code I can do it myself.

**Comment by Cammeritz** [comment]
As i said before Bungee is forwarding the packets/protocols (funcion of a proxy server) to the servers that are behind the proxy. So Bungee isn't accessing the mob packets, it's only forwarding them.

**Comment by RandomAltThingy** [comment]
I know how to handle the MCPE protocal. And for RakNet packets, there is JRakLib library.

**Comment by RandomAltThingy** [comment]
By @jython234

**Comment by RandomAltThingy** [comment]
The server behind the proxy? But if all your servers are bungeecord what server is there behind the proxy?

**Comment by md-5** [comment]
Bungee is a proxy, it simply relays and alters what the servers say.

**Comment by RandomAltThingy** [comment]
But it would be possible for me to make this as a complete server software, wouldn't it? With the proxy included inside.

**Comment by RandomAltThingy** [comment]
I mean when doing the port.

**Comment by Cammeritz** [comment]
"The server behind the proxy? But if all your servers are bungeecord what server is there behind the proxy?"
BungeeCord is the proxy and Spigot/Bukkit are the servers behind the proxy.

**Comment by RandomAltThingy** [comment]
I guessed that. Thanks for confirmation. But there is no imports, spigot or bukkit jar files anywhere and no code to download the jars that I've found; so how does it do it

**Comment by Cammeritz** [comment]
Because spigot does not nead to read the packets in that way that you can work with them (except proxy relevant and chat relevant packets).

**Comment by RandomAltThingy** [comment]
So how are commands executed? (Last question, seriously). We have the Command class but there is no code to execute it.

**Comment by Cammeritz** [comment]
Command/Chat packets are handled by BungeeCord and Spigot/Bukkit.
If Bungee notices that a Chat/Command messages start with a prefix the BungeeCommand is starting with (e.g. "end", "glist") then it will look throught it's CommandHandler and find the correct CommandExecutor where the command handling is being coded.

**Comment by RandomAltThingy** [comment]
Thanks.

@md-5 Feel free to lock, if you want.

**Comment by Janmm14** [comment]
Obviously the Command class in the API does not include how its executed. I think Commands need to be registered in the plugin manager and then the implementation in the peoxy module (look in the connection package) calls the command.

**Comment by RandomAltThingy** [comment]
Where is the load balancing code located at?

**Comment by Janmm14** [comment]
@RandomAltThingy 
> Where is the load balancing code located at?

BungeeCord itself does not have any kind of load balancing. If you mean network io threads, that is done by netty.
