### ISSUE TITLE
You are already connected to this Server

### ISSUE THREAD

**Issue by Cammeritz** [SpigotMC/BungeeCord#1608]
Hello md_5,

i know that this problem has been reported a few times, but i couldn't find way to solve the problem, yet!

The Bungee is running good for like 3 or 4 ours and then stops working. If someone leaves or tries to join the Bungee stops noticing that.

e.g. I type /glist and "DarkFlash_HD" is still connected altough he left the Server 10 mins before.
Here you can see that he is still connected:
https://i.gyazo.com/1c294268aa58755c60247398ff7e5a13.png

If i restart the Server it's working again but that is probably because Bungee "kicks/disconnects" all players.

Also when i try to /kick the player(using the ProxiedPlayer#disconnect()) function the player i try to kick still is shown at /glist .
That's kinda weird but idk why that happens.
We have 1GB/s Up/Download. We have set our soft/hard-limits to 50,000.

This is how we start our Bungee: (./bungeestart.sh)
http://hastebin.com/hamebiwoki.bash
And this is the start.sh being executed by bungeestart.sh:
http://hastebin.com/fexobugicu.bash

We are running Java 8 
-> "java version" = 1.8.0_60
-> "Runtime Environment" = build 1.8.0_60-b27
-> "Server VM" = build 25.60-b23, mixed mode

All Spigot/Bungee relevant processes are executed via root user

I hope you can help ous out :)

Thank you :*

**Comment by Cammeritz** [comment]
PS: We are using the newest Bungee build!

**Comment by sha-2** [comment]
Is it possible to provide a server log?

**Comment by Cammeritz** [comment]
Here you go: thronemc.com/proxy.log

And the "java.io.IOException: Too many open files" Error has already been fixed :)

**Comment by Cammeritz** [comment]
Go to the bottom and scroll up to 15-17

**Comment by kamcio96** [comment]
Are you using animated motd plugin?

**Comment by Cammeritz** [comment]
No, we don't, we use a static motd set in zhe bungee config

**Comment by sha-2** [comment]
Maybe the same problem here #1441

**Comment by Cammeritz** [comment]
It hapens also without any plugins installed

**Comment by kamcio96** [comment]
Is player on server? check it in /bukkit:list

**Comment by Cammeritz** [comment]
Nope, it say's the player is offline, just bungee says the player is online

**Comment by kamcio96** [comment]
Did you try using epoll?

**Comment by Cammeritz** [comment]
I never used it and don't know what it does exactly

**Comment by kamcio96** [comment]
in start script add -Dbungee.epoll=true before -jar

**Comment by Cammeritz** [comment]
And what will this do?

**Comment by Cammeritz** [comment]
You are talking about this: https://en.wikipedia.org/wiki/Epoll Correct?

**Comment by Janmm14** [comment]
@Cammeritz Yes.

**Comment by Cammeritz** [comment]
"where the number of watched file descriptors is large (unlike the older system calls, which operate in O(n) time, epoll operates in O(1) time[2])"

Sounds good.

**Comment by Cammeritz** [comment]
I'll try that on the next restart and tell you here :) Thank you for your help altough it might not work ^^

**Comment by kamcio96** [comment]
Probably it is netty bug or race condition and thing about it.

**Comment by Cammeritz** [comment]
Yeah probably. I'll try to change Bungees' protocol handling as i need it since i am a netty dev for almost 1 year now.

**Comment by Cammeritz** [comment]
@md-5 Since your active right now, please have a look at this topic <3

**Comment by Xayanix** [comment]
#1441 
Plugin fix: https://dl.dropboxusercontent.com/u/64069713/FuckOff.jar

**Comment by kamcio96** [comment]
That is the most stupid plugin.
Bungee remove that connection anyway: https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L57
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L629

Btw, getDecalaredField and get() methods should be in onEnable
:smile: 
I think there is some netty bugs.

**Comment by Xayanix** [comment]
Ważne, że działa.

**Comment by kamcio96** [comment]
Jak ma działać skoro Bungee robi to samo co ten plugin?

Już lepiej zrobić cmd która ręcznie usuwa z tych dwóch map.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
