### ISSUE TITLE
Selector loop error

### ISSUE THREAD

**Issue by maxlehot1234** [SpigotMC/BungeeCord#1610]
Hi everyone, I use Bungeecoord #1087 and Spigot 1.8.7 and I try with Spigot 1.8.8, I alway see this error in the chat when I try to join the lobby server (all was setup correctly, because its works great with Spigot 1.8.3):

11.10 04:19:12 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_60]
11.10 04:19:12 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [OpenMod-Prov2.jar:git-Spigot-f94fe8f-d27e6d0]
11.10 04:19:12 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [OpenMod-Prov2.jar:git-Spigot-f94fe8f-d27e6d0]
11.10 04:19:12 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:311) ~[OpenMod-Prov2.jar:git-Spigot-f94fe8f-d27e6d0]
11.10 04:19:12 [Server] INFO at io.netty.channel.epoll.Native.eventFdRead(Native Method) ~[OpenMod-Prov2.jar:git-Spigot-f94fe8f-d27e6d0]
11.10 04:19:12 [Server] INFO java.lang.RuntimeException: Error calling eventfd_read(...)
11.10 04:19:12 [Server] WARN Unexpected exception in the selector loop.

If I use Spigot 1.8.3, all works good without problems....

Anyone know how I can make latest Spigot version works with bungeecoord?

I have Java8 if you need to know.

Thanks in advanced

**Comment by Janmm14** [comment]
Error only in chat? Or also in console? If yes, which console (bungee or spigot)?

**Comment by minecrafter** [comment]
Not a BungeeCord issue.
