### ISSUE TITLE
You are already connected to this server

### ISSUE THREAD

**Issue by TrainsPlayMinecraft** [SpigotMC/BungeeCord#1611]
I keep getting kicked with:
11.10 08:53:29 [Server] INFO -> UpstreamBridge has disconnected
11.10 08:53:29 [Multicraft] disconnected with: You ran command Message of the Day
11.10 08:53:29 [Connect] User disconnected with: You, IP  
11.10 08:53:29 [Server] INFO disconnected with: You are already connected to this server!
11.10 08:53:29 [Server] INFO disconnected with: You are already connected to this server!
11.10 08:53:26 [Server] INFO -> UpstreamBridge has disconnected
11.10 08:53:25 [Multicraft] disconnected with: You ran command Message of the Day
11.10 08:53:25 [Connect] User disconnected with: You, IP  
11.10 08:53:25 [Server] INFO disconnected with: You are already connected to this server!
11.10 08:53:25 [Server] INFO disconnected with: You are already connected to this server!

Help would be much appreciated

**Comment by Cammeritz** [comment]
Same problem for me: https://github.com/SpigotMC/BungeeCord/issues/1608 
Not solved yet
