### ISSUE TITLE
BungeeCord error

### ISSUE THREAD

**Issue by didjee2** [SpigotMC/BungeeCord#1613]
_____________________________________________________________________________
17.10 13:23:44 [Server] INFO disconnected with: CorruptedFrameException : Empty Packet! @ net.md_5.bungee.protocol.Varint21FrameDecoder:34
17.10 13:23:44 [Server] INFO at java.lang.Thread.run(Thread.java:745)
17.10 13:23:44 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
17.10 13:23:44 [Server] INFO at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
17.10 13:23:44 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
17.10 13:23:44 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
17.10 13:23:44 [Server] INFO at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
17.10 13:23:44 [Server] INFO at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
17.10 13:23:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
17.10 13:23:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
17.10 13:23:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
17.10 13:23:44 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
17.10 13:23:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
17.10 13:23:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
17.10 13:23:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:230)
17.10 13:23:44 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:327)
17.10 13:23:44 [Server] INFO at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:34)
17.10 13:23:44 [Server] INFO io.netty.handler.codec.CorruptedFrameException: Empty Packet!
_____________________________________________________________________________

That is the error that we get all the time. Our server laggs out, from 1000 people to 500 people & big ping drops.
I don't know if it's a plugin that creates this error or BungeeCord itself.
(We will also go to redis soon).
The plugins: BungeeYAML, MultiLobby, BungeeUtilisals (Custom), ServerListPlus & Skinsrestorer

**Comment by Janmm14** [comment]
See https://github.com/SpigotMC/BungeeCord/issues/1599

**Comment by Xayanix** [comment]
Looks like someone is crashing your server.
Throotle new connections to bungee's port to ex. 3 per second from one ip.
