### ISSUE TITLE
Bungee v59208aa won't fully startup

### ISSUE THREAD

**Issue by TheTrollz** [SpigotMC/BungeeCord#1621]
29.10 01:44:40 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"59208aa":1080 by SpigotMC
29.10 01:44:40 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"59208aa":1080 by SpigotMC
29.10 01:44:40 [Server] INFO Loaded plugin ServerChecker version 1.1 by AgentLV
29.10 01:44:40 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"59208aa":1080 by SpigotMC
29.10 01:44:40 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
29.10 01:44:40 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
29.10 01:44:40 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
29.10 01:44:40 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
29.10 01:44:40 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
29.10 01:44:40 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
29.10 01:44:40 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"59208aa":1080
29.10 01:44:40 [Server] INFO Using native code compressor
29.10 01:44:40 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
29.10 01:44:40 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher122467879255325890.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
29.10 01:44:40 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher93887759908555686.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
29.10 01:44:30 [Server] INFO *** Server will start in 10 seconds ***
29.10 01:44:30 [Server] INFO *** You will get NO support regarding this build ***
29.10 01:44:30 [Server] INFO *** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
29.10 01:44:30 [Server] INFO *** Warning, this build is outdated ***

After the top line, nothing is logged/nothing occurs.

**Comment by Phoenix616** [comment]
I suggest you first try to download the most recent build as indicated in the log.

**Comment by TheTrollz** [comment]
I've tried it, same output as before.

**Comment by Janmm14** [comment]
Did you checked config.yml file that everything is correct? Pleasse post it here too.
