### ISSUE TITLE
Server Stops Loading And Is Stuck

### ISSUE THREAD

**Issue by lightning21games** [SpigotMC/BungeeCord#1624]
IT IS STUCK UP HERE
|
|
\/
30.10 17:18:18 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"013320f":1088 by SpigotMC
30.10 17:18:18 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"013320f":1088 by SpigotMC
30.10 17:18:18 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"013320f":1088 by SpigotMC
30.10 17:18:18 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"013320f":1088 by SpigotMC
30.10 17:18:18 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
30.10 17:18:18 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
30.10 17:18:18 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
30.10 17:18:18 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
30.10 17:18:18 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
30.10 17:18:18 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
30.10 17:18:17 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"013320f":1088
30.10 17:18:17 [Server] INFO Using native code compressor
30.10 17:18:17 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
30.10 17:18:17 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher3955447124781952054.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
30.10 17:18:17 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher8076095592252833330.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
30.10 17:18:16 [Multicraft] Loaded config for "Mod: BungeeCord"
30.10 17:18:16 [Multicraft] Starting server!
30.10 17:18:16 [Multicraft] Loading server properties
30.10 17:18:16 [Multicraft] Received start command
30.10 16:59:21 [Multicraft] Loading server properties

**Comment by RoboMWM** [comment]
In the future, it is suggested that you post logs from the log file itself, not from Multicraft.

**Comment by lightning21games** [comment]
That does not fix my problem

**Comment by Janmm14** [comment]
Would be nice if you give us a thread dump once its stuck.

**Comment by Janmm14** [comment]
Also you did not understand anything what @RoboMWM said, @lightning21games

You should go onto your server by ftp and show us parts out of the generated log file.

**Comment by lightning21games** [comment]
I am so sorry but it stopped generating logs
