### ISSUE TITLE
BungeeCord Kicks all players globally when sessionserver.mojang.com is offline

### ISSUE THREAD

**Issue by surgetheurge** [SpigotMC/BungeeCord#1625]
I don't know why but bungeecord just gives the entire server a boot whenever sessionserver.mojang.com is offline. I'm using latest bungeecord. here is a server log https://gist.githubusercontent.com/anonymous/782df2695ff8513e28db/raw/1014a35723e2755ec186aa5137cce078b1b39ada/gistfile1.txt
here are my java plugins 
http://upx.nz/oGOVB9
Please help!

**Comment by Janmm14** [comment]
I think it can only be SquadLink

**Comment by surgetheurge** [comment]
I removed BackToLobby, BungeeYAML, movemenow-0.2, and quietcord-1.0. Now it fully functions even with sessionserver.mojang.com is down. One of the four plugins uses sessionserver.mojang.com.

**Comment by Janmm14** [comment]
Well none of these plugins should do that

**Comment by Janmm14** [comment]
Maybe its not related.

**Comment by xxyy** [comment]
QuietCord surely doesn't. It doesn't interact with players or network at
all.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by surgetheurge** [comment]
No it's defiantly related. The moment I started the server with those 4 plugins excluded, the server booted up, even with sessionserver.mojang.com still being down.

**Comment by surgetheurge** [comment]
wtf, it's happening now and i have no plugins on my bungeecord!

**Comment by md-5** [comment]
Pretty sure Mojang isn't going down, your server is.

**Comment by Janmm14** [comment]
Could be a kind of (d)DoS attack

**Comment by surgetheurge** [comment]
apparently intreppid didn't configure my ddos protection to a "minecraft ip" so it would terminate connections.
