### ISSUE TITLE
messages.properties variables

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpigotMC/BungeeCord#1626]
I've been trying to modify this message:
connect_kick=\u00a7cKicked whilst connecting to {0}: {1}
But i don't know where the variable {1} points to, so i can't modify it. I've already modified the outdated-client and outdated-server messages in all my servers (lobby and the main server) using the spigot.yml option, but it still shows the default message.

**Comment by sha-2** [comment]
https://github.com/SpigotMC/BungeeCord/blob/013320fd9ec7e088a61634c28a3a39c5baab302d/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L279

{0} will be replaced by the servers name in your BungeeCord config and {1} will be replaced by the kick message.

**Comment by LuxusDarkangel** [comment]
Yep, i already know that as i stated on my first post. Anyway i'll close this, it's a problem with KCauldron ignoring that part of the cfg.
