### ISSUE TITLE
Don't connect player to a server when disconnected in PostLoginEvent listener

### ISSUE THREAD

**Issue by marcbal** [SpigotMC/BungeeCord#1630]
Is it possible to avoid player to connect to the default server when it is supposed to be kick on login ?

In my plugin :
```java
@EventHandler(priority=EventPriority.NORMAL)
public void onPostLogin(PostLoginEvent event) {
	event.getPlayer().disconnect("you are banned");
}
```

then when I login to my server, I see the spawn of the default server, and then I am kicked from server with message "you are banned".

In my server, I'm using a cheat : my plugin manage itself the content of the server list. So I can put in the  bungee's `config.yml` a fake server (with a name like `ttttttt`) and then define `default_server` and `fallback_server` as `ttttttt`.

But everybody does not use a plugin that manipulate the server list, and it's annoying to see a player login and then logout in the default server.

**Comment by Black-Hole** [comment]
You have to check for banned players in the ServerConnectEvent, too.

**Comment by marcbal** [comment]
I use a database to store the ban/whitelist status of a player. So it may be a performance problem if I request for player data twice and every time the player connect to a new server.

**Comment by marcbal** [comment]
It's right that i can use `ServerConnectEvent#getPlayer().getServer() == null` condition to check if the player has just logged in to the proxy.

But this is for semantic reason : I want to kick the player when he join the proxy, not when he try to connect to the server.

**Comment by Black-Hole** [comment]
Simple use a synchronized (or better concurrent) HashSet for players to kick in ServerConnectEvent.

Also the LoginEvent might be useful. You don't have a ProxiedPlayer object there, but you could use event.getConnection().getUniqueId()

**Comment by marcbal** [comment]
Yep, a cancelled LoginEvent call the disconnect(message) method and finish the login process :
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L458

Thanks for your answer.
