### ISSUE TITLE
Players disappearing

### ISSUE THREAD

**Issue by xGalDev** [SpigotMC/BungeeCord#1634]
If players get sent to the same server or join the same server at the same time sometimes itll random players from tab and show them as the alex skin or sometimes they are on the server but you cant see them in tab and you cant see them at all

**Comment by PhanaticD** [comment]
pretty sure this is a client bug

**Comment by Janmm14** [comment]
There are several issues with chunk packets recieving the client too late and causing invisible players. Read about it on twitter. Fixed in snapshots. But try out solution above or do a double /vanish

**Comment by xGalDev** [comment]
@Janmm14 i just downgraded to an older spigot for now :p

**Comment by xGalDev** [comment]
This is still happening....

**Comment by Janmm14** [comment]
Well one could write a plugin for proper packet order or wait for minecraft and spigot 1.9

**Comment by Paulomart** [comment]
I notice this problem on my network too, I got started with [this](https://github.com/Mystalion/right-packet-order) but I dont even get to reproduce the issue :/

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
