### ISSUE TITLE
BungeeCord down

### ISSUE THREAD

**Issue by przemek3697** [SpigotMC/BungeeCord#1637]
BungeeCord stoped responding when he got exception on connecting to mojang session server.
After that all players on BungeeCord are disconnected (ReadTimeoutException)

http://pastebin.com/9mmn2FSV

**Comment by Black-Hole** [comment]
Your server is having routing problems. So it can't reach Mojang servers and connections to some users are dropped.

**Comment by przemek3697** [comment]
That happens when i got bot attack, maybe I reach limit to connect to mojang servers but this is on second plan. Still have trouble with "lagged" BungeeCord. it didn't respond.

**Comment by Black-Hole** [comment]
It's not special to the mojang servers. The BungeeCord server is still reponsive. Packets form/to some or all external networks are dropped. It's a network issue.

Maybe your server hoster is dropping all packets to your server or the DDoS filtering is faulty. Anyway, local connections to your BungeeCord servers are still working, like connections to your local spigot servers.

Ask your server hoster for assistance, they should be able to explain in detail what happened and what you can do about it. If not, then it might be advisable to change to a hoster with a decent DDoS protection.

**Comment by przemek3697** [comment]
Thanks for trying help me but, your way is bad. When my bungee console is frozen, and is not responsible after that error, its must be a BungeeCord problem there is no other way.

p.s. My hoster is OVH with **Game** AntiDdos Protection

**Comment by kamcio96** [comment]
Polish:
Czy zawsze występuje błąd z połączeniem do mojangu?

**Comment by przemek3697** [comment]
@Xayanix Nicki botów były randomowe (non-premium)

@kamcio96 Nie. Wydaje mi się że dzieje się to wtedy jak przekroczymy limit zapytań do serwera Mojang lub jak ich serwer padnie

**Comment by kamcio96** [comment]
@przemek3697 wiem od czego jest ten błąd, ale czy obie te rzeczy występują razem?

**Comment by przemek3697** [comment]
Ciężko jest mi stwierdzić ponieważ nie widziałem tego na oczy.
Motyw jest taki 
* Atak botów (pomijam expolit)
  * Prawdopodobnie przekraczamy limit połączeń do mojangu
* Wchodzi jakiś gracz
  * I tu właśnie występuje błąd połączenia do mojangu
* Bungee zaczyna ostro lagować
  * Wywala znaczną część graczy
* Często właśnie jest albo crash (hs_pid_err) albo kompletny brak odpowiedzi

**Comment by kamcio96** [comment]
pokaz tego hr_pid_err (tylko wrzuc na http://hastebin.com/)
jak chcesz wiecej pomocy to napisz na skype: kamkamkam11
