### ISSUE TITLE
Error dispatching event PluginMessageEvent

### ISSUE THREAD

**Issue by Simonsator** [SpigotMC/BungeeCord#1640]
Hello,
My Bungeecord plugin sometimes throw the error:
14:54:26 [GRAVE] nov 19, 2015 2:54:26 PM net.md_5.bungee.event.EventBus post
AVVERTENZA: Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@1948721c, receiver=nik0072), cancelled=false, tag=PartyAndFriends, data=[0, 33, 118, 101, 114, 115, 116, 101, 99, 107, 116, 101, 115, 112, 105, 101, 108, 101, 114, 98, 101, 107, 111, 109, 109, 101, 110, 124, 110, 105, 107, 48, 48, 55, 50]) to listener partyAndFriends.main.listener.SpigotMessage@7c4fc2bf
java.lang.NullPointerException

That's all I don't get any information about in which line it did happen, but I think (I am not sure) the error is net.md_5.bungee.event.EventBus post and not in my plugin.

**Comment by kamcio96** [comment]
Nooo, its definitely bug in your plugin

**Comment by 00pflaume** [comment]
What can generate the bug in my plugin?.
@EventHandler
	public void onPluginMessage(PluginMessageEvent ev) {
		if (!ev.getTag().equals("PartyAndFriends")) {
			return;
		}
		if (!(ev.getSender() instanceof Server)) {
			return;
		}
		Server server = (Server) ev.getSender();
		ByteArrayInputStream stream = new ByteArrayInputStream(ev.getData());
		DataInputStream in = new DataInputStream(stream);
		try {
			wasIstZuTun(in.readUTF(), server);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

**Comment by 00pflaume** [comment]
The bug also don't happens allways it only happens sometimes (for me the bug never happend only for a user).

**Comment by Black-Hole** [comment]
Use a try-catch with NullPointerException to print out the stacktrace to help debugging your plugin.

**Comment by kamcio96** [comment]
Could you paste wasIstZuTun method?

**Comment by 00pflaume** [comment]
I changed both methods (I surrounded them with a try catch and added pre he does anything a sysout("test")). Still same error nothing changed, so it seems like he is never executing the method onPluginMessage(PluginMessageEvent: pEvent). Also he does not print out my sysout.

**Comment by kamcio96** [comment]
did you register your listener?

**Comment by 00pflaume** [comment]
Of cause. Only two servers (as far as I know), who uses my plugin, have the error, but these two servers are getting spammed (this servers have 200 players normally on it) with the error, but anyway all functions seem to work right (with the exception of the error in the console)

**Comment by kamcio96** [comment]
Could you paste full event code?

**Comment by 00pflaume** [comment]
private void wasIstZuTun(String erhalten, Server server) {
		try {
			StringTokenizer st = new StringTokenizer(erhalten, "|");
			String mitZuArbeiten = st.nextToken();
			String spielerNameSender = st.nextToken();
			if (mitZuArbeiten.equals("verstecktespielerbekommen")) {
				String freundeZuUebergeben = "/";
				int playerID = -1;
				playerID = Main.main.verbindung.getIDByPlayerName(spielerNameSender);
				int EinstellungHidePlayers = 0;
				EinstellungHidePlayers = Main.main.verbindung.getEinstellungHidePlayers(playerID);
				if (EinstellungHidePlayers == 1 | EinstellungHidePlayers == 2) {
					int[] freunde = null;
					freunde = Main.main.verbindung.getFreundeArray(playerID);
					int durchlaufOnline = 0;
					ArrayList<String> onlineSpieler = new ArrayList<String>();
					for (int spielerID : freunde) {
						String spielerName = Main.main.verbindung.getNameDesSpielers(spielerID);
						ProxiedPlayer pl = BungeeCord.getInstance().getPlayer(spielerName);
						if (pl != null) {
							onlineSpieler.add(durchlaufOnline, spielerName);
						}
					}
					if (onlineSpieler.size() > 0) {
						freundeZuUebergeben = onlineSpieler.get(0);
						int durchlaufUebertragen = 1;
						while (onlineSpieler.size() > durchlaufUebertragen) {
							freundeZuUebergeben = freundeZuUebergeben + "$" + onlineSpieler.get(durchlaufUebertragen);
							durchlaufUebertragen++;
						}
					}
				}
				sendMessage(
						"hidePlayers|" + spielerNameSender + "|" + EinstellungHidePlayers + "|" + freundeZuUebergeben,
						BungeeCord.getInstance().getPlayer(spielerNameSender).getServer().getInfo());
				return;
			}
			if (mitZuArbeiten.equals("Hauptinventar")) {
				String freunde = "";
				freunde = Main.main.verbindung
						.freundeAusgeben(Main.main.verbindung.getIDByPlayerName(spielerNameSender));
				StringTokenizer stn = new StringTokenizer(freunde, "|");
				int durchlauf = 0;
				int durchlaufOnline = 0;
				int durchlaufOffline = 0;
				ArrayList<String> onlineSpieler = new ArrayList<String>();
				ArrayList<String> offlineSpieler = new ArrayList<String>();
				int soVieleDrin = stn.countTokens();
				while (soVieleDrin > durchlauf) {
					int spielerID = Integer.parseInt(stn.nextToken());
					String spielerName = Main.main.verbindung.getNameDesSpielers(spielerID);
					ProxiedPlayer pl = BungeeCord.getInstance().getPlayer(spielerName);
					if (pl != null) {
						String name = pl.getDisplayName();
						if (name.length() > 24) {
							name = pl.getName();
						}
						onlineSpieler.add(durchlaufOnline, name + "%" + pl.getServer().getInfo().getName());
						durchlaufOnline++;
					} else {
						offlineSpieler.add(durchlaufOffline, spielerName);
						durchlaufOffline++;
					}
					durchlauf++;
				}
				String zuUebergebeneSpieler = "";
				if (onlineSpieler.size() != 0) {
					zuUebergebeneSpieler = onlineSpieler.get(0);
					int durchlaufOnlineUebertragen = 1;
					while (onlineSpieler.size() > durchlaufOnlineUebertragen) {
						zuUebergebeneSpieler = zuUebergebeneSpieler + "$"
								+ onlineSpieler.get(durchlaufOnlineUebertragen);
						durchlaufOnlineUebertragen++;
					}
				}
				zuUebergebeneSpieler = zuUebergebeneSpieler + ",";
				if (offlineSpieler.size() != 0) {
					zuUebergebeneSpieler = zuUebergebeneSpieler + offlineSpieler.get(0);
					int durchlaufOfflineUebertragen = 1;
					while (offlineSpieler.size() > durchlaufOfflineUebertragen) {
						zuUebergebeneSpieler = zuUebergebeneSpieler + "$"
								+ offlineSpieler.get(durchlaufOfflineUebertragen);
						durchlaufOfflineUebertragen++;
					}
				}
				String uebergeben = "Hauptinventar|" + spielerNameSender + "|" + zuUebergebeneSpieler;
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				sendMessage(uebergeben, proxiedSpieler.getServer().getInfo());
				return;
			}
			if (mitZuArbeiten.equals("setEinstellungVersteckte")) {
				Main.main.verbindung.setEinstellungVersteckte(spielerNameSender, Integer.parseInt(st.nextToken()));
				return;
			}
			if (mitZuArbeiten.equals("schieckeFreundschaftsAnfrage")) {
				String freundschaftsAnfrageEmpfaenger = st.nextToken();
				if (Main.main.verbindung.istBefreundetMit(BungeeCord.getInstance().getPlayer(spielerNameSender),
						BungeeCord.getInstance().getPlayer(freundschaftsAnfrageEmpfaenger)) == false) {
					String[] args = new String[2];
					args[0] = "add";
					args[1] = freundschaftsAnfrageEmpfaenger;
					add.hinzufuegen(BungeeCord.getInstance().getPlayer(spielerNameSender), args);
				}
				return;
			}
			if (mitZuArbeiten.equals("Accept")) {
				String[] args = new String[2];
				args[0] = spielerNameSender;
				args[1] = st.nextToken();
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				accept.akzeptieren(proxiedSpieler, args);
				return;
			}
			if (mitZuArbeiten.equals("Decline")) {
				String[] args = new String[2];
				args[0] = "settings";
				args[1] = st.nextToken();
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				deny.ablehnen(proxiedSpieler, args);
				return;
			}

			if (mitZuArbeiten.equals("einstellungen")) {
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				int[] abgefragteEinstellung = Main.main.verbindung.einstellungenAbfragen(proxiedSpieler);
				sendMessage(
						"einstellungen|" + spielerNameSender + "|" + abgefragteEinstellung[0] + "|"
								+ abgefragteEinstellung[1] + "|" + abgefragteEinstellung[2] + "|"
								+ abgefragteEinstellung[3] + "|" + abgefragteEinstellung[4],
						proxiedSpieler.getServer().getInfo());
				return;
			}
			if (mitZuArbeiten.equals("freundschaftsanfragen")) {
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				String anfragen = Main.main.verbindung
						.getAnfragen(Main.main.verbindung.getIDByPlayerName(spielerNameSender));
				int durchlauf = 1;
				StringTokenizer stn = new StringTokenizer(anfragen, "|");
				int soVieleDrin = stn.countTokens();
				String spielerListe = "";
				if (soVieleDrin > 0) {
					spielerListe = Main.main.verbindung.getNameDesSpielers(Integer.parseInt(stn.nextToken()));
					while (soVieleDrin > durchlauf) {
						int spielerID = Integer.parseInt(stn.nextToken());
						String spielerName = Main.main.verbindung.getNameDesSpielers(spielerID);
						spielerListe = spielerListe + "$" + spielerName;
						durchlauf++;
					}
				}
				sendMessage("freundschaftsanfragen|" + spielerNameSender + "|" + spielerListe,
						proxiedSpieler.getServer().getInfo());
				return;
			}
			if (mitZuArbeiten.equals("EinstellungenAendern")) {
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				String[] args = new String[2];
				args[0] = "settings";
				args[1] = st.nextToken();
				einstellungen.settings(proxiedSpieler, args);
				return;
			}
			if (mitZuArbeiten.equals("partyEinladen")) {
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				String[] args = new String[2];
				args[0] = "invite";
				args[1] = st.nextToken();
				Main.main.KommandoParty.execute(proxiedSpieler, args);
				return;
			}
			if (mitZuArbeiten.equals("loesche")) {
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				String[] args = new String[2];
				args[0] = "settings";
				args[1] = st.nextToken();
				remove.entfernen(proxiedSpieler, args);
				return;
			}
			if (mitZuArbeiten.equals("springeZu")) {
				ProxiedPlayer proxiedSpieler = BungeeCord.getInstance().getPlayer(spielerNameSender);
				String[] args = new String[2];
				args[0] = "jump";
				args[1] = st.nextToken();
				jump.springen(proxiedSpieler, args);
				return;
			}
		} catch (NullPointerException e) {
			e.printStackTrace();
		}
	}

**Comment by kamcio96** [comment]
Omg, a lot of code. I cannot find bug there, but exception stack trace should point you where it is.

**Comment by Black-Hole** [comment]
Too bad the BungeeCord EventBus does not print a stack trace there. :(
The code looks OK.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
