### ISSUE TITLE
PacketPlayInWindowClick anty crash bungee side

### ISSUE THREAD

**Issue by kukubaczek** [SpigotMC/BungeeCord#1644]
Can you fix PacketPlayInWindowClick crasher on bungee? I want use 1.7 & 1.8 PaperSpigot, but this is deprecated. Please block this at bungee :C

**Comment by minecrafter** [comment]
Very unlikely that Bungee is going to fix 1.7/1.8-related issues.

**Comment by md-5** [comment]
Bungee isn't a firewall..
