### ISSUE TITLE
Add a restart command to proxy

### ISSUE THREAD

**Issue by Legoman99573** [SpigotMC/BungeeCord#1646]
Hi md_5.

I feel like there should be a /grestart command to restart a bungeecord Server without using /end all the time. This will act like spigots restart command. May need to add restart.yml folder to allow the command to know what batch file, or other file to use.

**Comment by Chnkr** [comment]
:-1: Not needed, you can use wrappers and bash/batch scripts to preform the tasks needed.

**Comment by zahlex** [comment]
:-1:  I'd also recommend to use some script magic for that.

For example use a simple loop to restart your BungeeCord when typing `/end`.
`while true; do java -jar BungeeCord.jar; done`

**Comment by Legoman99573** [comment]
Ok then. Just a suggestion. Idk why it would be bad if there is a /greload command

**Comment by zahlex** [comment]
Not much, but there are simply much more important things.

**Comment by ravkr** [comment]
much better would be ability to make server stop listening for incoming connections so we can start another bungee instance and when last player of 1st Bungee leaves the game it just shutdowns
I know we already have some plugins that can do that but native bungee solution would be the best ^_^

**Comment by Janmm14** [comment]
Then write it yourself and pr it :)

**Comment by md-5** [comment]
` while true; do java -jar BungeeCord.jar; done`

This is recommended.

Having an app restart itself really doesn't play nicely with most things - plus it requires manual configuration anyway
