### ISSUE TITLE
/server [server name] not functioning

### ISSUE THREAD

**Issue by CariPruna** [SpigotMC/BungeeCord#1647]
I have 4 servers in total. The Server running the plugin, the server running the actual hub so that players join, and two game-servers. I set everything up and the servers all turned on correctly, and I was able to join the server. I tried to join my OTHER servers but it failed to function, and it reacts like the command is non-existing. I am using a Spigot build for the hub (#1655; the one that allows 1.8 clients to join.) I am using the latest Bungee-Cord jar for the server that runs the plugin (#1076) and my two game servers are KCauldron 1.7.10
What Do I do?

**Comment by Janmm14** [comment]
Please check whether the corresponding module is in the modules directory. If not, download the module manually from here (normally if bungee is not modified it does that automatically): http://ci.md-5.net/job/bungeecord/

**Comment by CariPruna** [comment]
What do you mean that I have to check whether the corresponding module is in the modules directory?? and what module are you talking about? and where do i put it in??

**Comment by Janmm14** [comment]
BungeeCord has several modules:
- cmd_alert.jar
- cmd_find.jar
- cmd_list.jar
- cmd_send.jar
- cmd_server.jar
- reconnect_yaml.jar

All these can be downloadedon the linked page.

Normally these are downloaded automatically, but if that fails you need to downoad the modulesyou want and put them into a directory called ```modules```.

**Comment by CariPruna** [comment]
Ah I see. All downloaded. Now I am having issues with IPWhitelist... Well
thanks for helping me with the Bungee Error. If you can help with the
IPWhitelist error too, feel free to do so? :)

Link:
https://www.spigotmc.org/threads/ipwhitelist-technical-difficulties.105008/

**Comment by darthandrew1** [comment]
This can be closed.

**Comment by Janmm14** [comment]
@CariPruna use OnlyProxyJoin, IPWhitelist dies bot work with ip forwarding.
