### ISSUE TITLE
Proxy Kick

### ISSUE THREAD

**Issue by c0wg0d** [SpigotMC/BungeeCord#1648]
This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1091 by md_5

My players are constantly being kicked from our hub/lobby world (and other worlds too, occasionally) and I have yet to figure out why.  Sometimes you can stay connected for 30 minutes before getting kicked, sometimes it will kick players every few seconds.  I am constantly seeing these errors in the Spigot server logs when they get kicked from the server they are in:

<player> lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

What would be causing this?  What other info do you need?

**Comment by Janmm14** [comment]
Can you reproduce it yourself? What version of spigot? Which client version?

**Comment by c0wg0d** [comment]
I have been trying to reproduce it reliably for hours without success.  It seems like it happens a lot more often when there are many people in our lobby, but I was in the lobby alone last night and it was still happening.

Client version is vanilla minecraft 1.8.8.
Spigot version is latest 1.8.8-R01 snapshot as of two nights ago.

**Comment by firefligher** [comment]
If you could show us a bit more of your Spigot log it would be really helpful. Maybe it is a bug in Spigot that is causing this issue. (Minecraft server will kick player if there is a packet decoding error or something like that) Another important information is the kick message that the players see after they have been kicked from the server.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
