### ISSUE TITLE
BungeeCord Modification Idea: Offline-Online Server Connections.

### ISSUE THREAD

**Issue by M91** [SpigotMC/BungeeCord#165]
http://www.spigotmc.org/threads/bungeecord-modification-idea-offline-online-server-connections.815/

Hello everybody, I am here not just to ask for a plugin addition, but to actually show how it could be made possible. As you all know, the most recent update of the BungeeCord plugin now allows cracked clients to connect to a BungeeCord proxy as long as it is enabled in the config. The problem, or more or less setback is that it is currently set up where you either have the node in the config toggled to online, or offline; no meeting ground, just either cracked, or premium.

I am requesting an addition be made to the plugin. When a BungeeCord config is set to offline, the editor of the config then has the option to add servers that would be in Online mode, even though the proxy would be in offline mode. While all servers have to be set to offline in the server config so the proxy can hook up to them, the part of the BungeeCord config in where you list what servers hook up to the proxy be changed to allow online and offline mode servers. Here is an example:

servers:
  lobby:
    address: 10.1.10.11:25565
  offline_servers:
    pvp:
      address: 10.1.10.11:25566
    survival:
      address: 10.1.10.11:25567
  online_servers:
    pvp:
      address: 10.1.10.10:25565
    survival:
      address: 10.1.10.10:25566

The servers are broken up to online and offline mode servers. The offline_servers would have no change to the way BungeeCord currently hooks up servers to the proxy, but the online_servers would. When a server is added to the online_servers list, the server is set up to where when a player tries to connect to the server via command, stargate, etc, the players client is run through the minecraft.net database checking to see if the player is or is not using a correct
username/password. I would believe that you would be able to use your current online mode setup with your BungeeCord proxy sever, and just take it and hook it up with the online_servers, but do not quote me on that.

You may be asking what would be the practical use to this? Well... BungeeCord servers could then be set up with some servers catering to cracked clients while others on the proxy will cater to premium clients. Premium clients could be protected with some type of authentication plugin, but that would be up to the server owners discretion.

I know that the true goal of BungeeCord is to get all players of Minecraft on a single server where they would be able to connect to hundreds of different servers all in 1 place, and with the addition of offline mode clients in the mix, allowing cracked and premium clients to all be in same place and able to go to whichever server they are allowed to, it just is taking one step closer to the true dream of BungeeCord and players everywhere. Please take this idea into heavy considerations; it would be amazing to see this implemented.

If the post is not making the idea clear, you can contact me through my skype: jphyman.

Thank you for your time,
Taxiboss22 & M91

**Comment by FuturisticCake** [comment]
Plugins are able to authenticate players, I'm reasonably sure. :) Interesting plugin idea.

**Comment by Janmm14** [comment]
Plugins (both public (free) and private) already exist to create online-and-offline-mode-together servers. Bungee also provides the neccessary API for that already. @FuturisticCake

**Comment by xxyy** [comment]
> md-5 closed this issue over 3 years ago
