### ISSUE TITLE
e.getConnection().getVirtualHost().getHostName(); - error

### ISSUE THREAD

**Issue by Xayanix** [SpigotMC/BungeeCord#1653]
Hi, method:
e.getConnection().getVirtualHost().getHostName();

Sometimes returns invalid domain, like that:
e59bcfdfoDEEqBCqtpApBqDqoFtrB>>AEsDq?sA@rACGB?GA?BBFE>EEC>?CF
or 
e59bcfdfoDEEqBCqtpApBqDqoFtrB>>AEsDq?sA@rACGB?GA?BBFE>EEC>?CF

Player need to restart client, it is bungee issue?

**Comment by Paulomart** [comment]
Is the player connecting over ipv6 or something?

**Comment by Xayanix** [comment]
No, he uses IPv4.
I told him to restart his game, when he did that domain was correct after.

**Comment by Xayanix** [comment]
It was caused by custom launcher.
