### ISSUE TITLE
Tablist

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1654]
Hey, can you guys fix tablist loading? On server change you sometimes see couple players from server, on which you were before changing. I'm using FunnyGuilds for tablist. https://github.com/Wruczek/FunnyGuilds-Reloaded

**Comment by c0wg0d** [comment]
Having the same issue with BungeeTabListPlus, but they told me it was an issue with IdentityOverride (another plugin for BungeeCord) and not BungeeCord itself.  I don't know who to believe.

**Comment by CzlowiekKuktas** [comment]
I don't use IdentityOverride plugin.

**Comment by c0wg0d** [comment]
Okay, here is my bug report, which seems similiar/the same issue as you: https://github.com/SpigotMC/BungeeCord/issues/1593

**Comment by Xayanix** [comment]
I confirm issue

**Comment by Janmm14** [comment]
Why post the issue here?

**Comment by CzlowiekKuktas** [comment]
Maybe it's an bungeecord problem?

**Comment by Xayanix** [comment]
It is Bungee problem, it happens even on servers which does not have FunnyGuilds

**Comment by c0wg0d** [comment]
After a quick grep in my logs, my server is proxy kicking players about 10,000 times per day on average.  For some players, they are getting kicked every few seconds.  This is maddening.  Can a developer please at least acknowledge that this is an issue or tell us what steps we can try to resolve the issue?

**Comment by Janmm14** [comment]
@c0wg0d Which plugins are you currently using on bungee and are kicks bound to certain servers or not?

**Comment by c0wg0d** [comment]
It's across all servers, but seems to happen more often on the hub server than anywhere else.  I'm guessing that's because that server has a lot more joins/disconnects than any other server.

Plugins are IdentityOverride, BungeeTabListPlus, Yamlr, MoveMeNow, and MineverseChat.

**Comment by ryantheleach** [comment]
>After a quick grep in my logs, my server is proxy kicking players about 10,000 times per day on average. For some players, they are getting kicked every few seconds. This is maddening. Can a developer please at least acknowledge that this is an issue or tell us what steps we can try to resolve the issue?

Does not seem to relate to the original issue at all.

**Comment by c0wg0d** [comment]
You're right, I commented on the wrong bug.  Feel free to delete my last two comments, and this one.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
