### ISSUE TITLE
Bot Attack = Freeze

### ISSUE THREAD

**Issue by MaRoTheTroLLeR** [SpigotMC/BungeeCord#1655]
Bungeecord is easily freezing because of bot attacks.

Tested with plugins and without plugins.

**Comment by Janmm14** [comment]
You mean join bots?
ram / cpu usage?
cpu type?

Additionally you could try out my changes to BungeeCord:
Change list: https://github.com/minotopiame/BungeeCordPatcher/tree/master/patches
Download: https://ci.janmm14.de/job/public~server~BungeeCordPatcher/

**Comment by MaRoTheTroLLeR** [comment]
the CPU is Intel Xeon E3 1245v2. I dont know if the cou/ram usage is big, because im on terminal and i dont know much linux, but it keeps freezing, I tried with adding moe ram, but it didnt solve the problem.

PS = Im running the latest bungeecord.

**Comment by MaRoTheTroLLeR** [comment]
I think Bungeecord accepts the players one by one. and that causes the freeze, since the bots are thousants.

**Comment by minecrafter** [comment]
The time taken to accept one player is insignificant (unless you're unlucky and got a stop-the-world GC).

BungeeCord scales based on CPU cores available to it, so something like a E5-2620v2 would have a better chance of acceptably handling bot attacks.

**Comment by MaRoTheTroLLeR** [comment]
It shouldnt be like this...

**Comment by Janmm14** [comment]
My custom bungee should significantly lower impact of bot attacks, as joins are limited per ip to the ```connection_throttle``` setting in your ```config.yml```, which got deactivated when bungee updated to 1.8 .

use these commands to see memory and cpu usage:
```sudo apt-get install htop -y```
```htop```

At the top are cpu, memory and such, below you have all running threads on your machine.
Remove the ```sudo ``` out of the first command if you are logged in as root.

**Comment by MaRoTheTroLLeR** [comment]
I added the connection throttle for now until they make a new one.

            if ( BungeeCord.getInstance().getConnectionThrottle().throttle( ( (InetSocketAddress) ch.remoteAddress() ).getAddress() ) )
            {
                // TODO: Better throttle - we can't throttle this way if we want to maintain 1.7 compat!
                 ch.close();
                 return;
            }

**Comment by Janmm14** [comment]
@MaRoTheTroLLeR
That will count motd pings of minecraft server list as a connection try and will apply the throttle then you wanna connect then.

**Comment by MaRoTheTroLLeR** [comment]
I dont rly care about minecraft server list. Also minecraft server list pings the servers per some time.
But i dont really care about minecraft server list. I wanna prevent crashes, so i hope it ll be good.

PS: I didnt really understand this "and will apply the throttle then you wanna connect then."

**Comment by MaRoTheTroLLeR** [comment]
Its freezing again. I cant see my cpu usage since i cant install htop. apt-get is unknown command.

**Comment by MaRoTheTroLLeR** [comment]
Hi, I just realized that BungeePerms was causing the problem. I've removed it.

Thanks for the help :)

**Comment by Janmm14** [comment]
@MaRoTheTroLLeR use ```aptitude``` or ```yum```. You could have googled yourself how to install htop for your linux distribution.

Basically your implementation requires a delay of the ```connection_throttle``` setting between any server list ping and/or join attempt. My solution to that is using another attempt.
