### ISSUE TITLE
Get player from PacketLoginInStart

### ISSUE THREAD

**Issue by SkymaxPlay** [SpigotMC/BungeeCord#1656]
Hello,
I have a problem, How to send packet to player when I received PacketLoginInStart?
PacketLoginInStart sending to server only GameProfile. Can I use GameProfile to create EntityPlayer,next create PlayerConnection and send packet using PlayerConnection?
How to do it ProtocolLib?

**Comment by kamcio96** [comment]
PreLoginEvent:
event.getConnection().unsafe().sendPacket(new EncryptionRequest(...));

To bungee, nie masz tu klas takich jak EntityPlayer albo PlayerConnection. ProtocolLib to też nie tutaj.
To osobna aplikacja, nie dodatek do bukkita.

**Comment by SkymaxPlay** [comment]
mi chodzi o bukkit'a

**Comment by SkymaxPlay** [comment]
LOL no BungeeCord xD I was wrong page.

**Comment by kamcio96** [comment]
hahahhahahahhahahahahahhahahahahah
leze i nie mogę wstać xD

dzięki ziomek, poprawiłes mi dziś humor :P

**Comment by SkymaxPlay** [comment]
proszę bardzo xD

**Comment by kamcio96** [comment]
@SkymaxPlay Jak masz chwile czasu napisz do mnie na [fanpage](https://www.facebook.com/kamcio96/)
