### ISSUE TITLE
Writing commands to BungeeCord Process OutputStream does not appear to execute them.

### ISSUE THREAD

**Issue by slipswhitley** [SpigotMC/BungeeCord#1661]
Here is the code I am using to read / write to a BungeeCord process. Only issue is it appears that writing commands to the output stream does not appear to work. 

http://pastebin.com/JvsetSUq

I believe my code is working correctly for the following reasons but I am open to light criticism if it is a fault at my end:
- I have checked that that the code that writes to the output stream is being reached with the correct command
- This code works flawlessly using the Spigot server jar.

Maybe BungeeCord uses a command execution system I don't know about? 
Thanks

**Comment by slipswhitley** [comment]
Fixed! Added "-Djline.terminal=jline.UnsupportedTerminal" to launch arguments

**Comment by ThePhineas** [comment]
@slipswhitley Close the issue.
