### ISSUE TITLE
Can't connect to network. Console has NO errors

### ISSUE THREAD

**Issue by Xanderpitz** [SpigotMC/BungeeCord#1662]
Clone of this thread: https://www.spigotmc.org/threads/cant-connect-to-network-no-error.106366/

I've search tirelessly on Google for any information regarding this specific issue, but either it's an issue that no one has ever encountered before or the keywords are just too common and get mixed in with other topics (more likely imo).

Here are logs from both my bungee and lobby servers on boot-up:
Lobby: http://pastebin.com/bmgCC1bE
Bungee: http://pastebin.com/djRXFSU1

It appears that they're both booting completely fine. I've tried connecting to my web IP (mc.xpcraft.com) as well as the numerical IP (xxx.xx.xx.xxx:25565 [both with and without port]). Neither have worked.

**Comment by chdxD1** [comment]
Your BungeeCord ("Startup Listening on /0.0.0.0:25577" in http://pastebin.com/djRXFSU1) is listening on 25577 not 25565.

**Comment by Xanderpitz** [comment]
That's the UDP port. Minecraft runs on the TCP port. My network dev had me run a few commands in PuTTy and we found that neither UDP and TCP port 25565 were open, so that's the issue.

We opened those up and it works perfectly so it should be good!
