### ISSUE TITLE
Groups not working for certain username.

### ISSUE THREAD

**Issue by OmgItsMax** [SpigotMC/BungeeCord#1666]
I am having some troubles with the groups defined in the bungee config.yml.

Part of config:
```
groups:
05:
- admin
Null101:
- admin
```

It seems that the two character username is not registered and can not perform any commands defined under the group "admin"s permissions. The user Null101 has all admin commands, that's why I believe its not allowing a two character name. If anyone could help me solve this or tell me what the problem is, I thank you in advance.

**Comment by Black-Hole** [comment]
For group names with only number characters use single quotation marks, like '05'. YAML would parse them as number, if not quoted (to "5" here).
