### ISSUE TITLE
Bungee Vanish kick

### ISSUE THREAD

**Issue by AlexNova1555** [SpigotMC/BungeeCord#1668]
i found but that if u using a invisible potion so after the effect if off u got kicked and a error 
the error: http://pastebin.com/DqgwA3aK

i using spigot
CraftBukkit version git-Spigot-db6de12-1 8fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
and bungee cord version is Build #1093

**Comment by Black-Hole** [comment]
It's a plugin issue. Bungeecord isn't adding teams by itself. :)

**Comment by AlexNova1555** [comment]
ohh ok gone to try to remove plugin plugin and check if it still doing that ^_^

**Comment by AlexNova1555** [comment]
ok i found the plugin is was custom nametagedit that someone made XD
tnx for the quick respawned
