### ISSUE TITLE
Kicked whilst connecting (error)

### ISSUE THREAD

**Issue by LuminousViper** [SpigotMC/BungeeCord#1669]
I currently run a bungee cord server and when i tried to connect to the server i got this response:

Exception Connecting:CorruptedFrameException : Empty Packet! @ net.md_5.bungee.protocol.Varint21FrameDecoder:34

Thank you for your help :)

**Comment by ravkr** [comment]
what is your bungee version and minecraft version? is it modded?

**Comment by LuminousViper** [comment]
Build #1093 and minecraft version 1.8.8

If it helps i am trying to make it so i can connect using 1.7.10 as well as 1.8.8 

TY for quick reply

**Comment by LuminousViper** [comment]
Build #1093 and minecraft version 1.8.8

If it helps i am trying to make it so i can connect using 1.7.10 as well as 1.8.8 

TY for quick reply

**Comment by Done84** [comment]
I also have a few players complaining about this error.
27.12 21:28:07 [Server] INFO This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1091 by md_5

**Comment by Janmm14** [comment]
This error usually came up with 1.7 client versions.

**Comment by Done84** [comment]
@Janmm14 Yeah since i posted i noticed that. I would be nice to have a "Version error" instead because this confuses new players.

**Comment by Janmm14** [comment]
@Done84 BungeeCord still supports 1.7, but md_5 or thinkofdeath either could not reproduce this or don't want to accept to ignore this instead of throwing an error leading to disconnect.
