### ISSUE TITLE
Incorrect online status

### ISSUE THREAD

**Issue by Xayanix** [SpigotMC/BungeeCord#1670]
Hi, why when someone is joinbotting my BungeeCord (it causes very low load, no performance issue) i have then incorrect online count? For example i had 100 players online, someone was botting for 10 minutes and then stop and i have 250 players until restart and it looks like i had fake players :(

**Comment by Janmm14** [comment]
Seems this is some kind of disconnection bug, possibly related to a plugin. Show us your bungee plugins please. Does /glist show the fake players?

**Comment by Xayanix** [comment]
I don't use plugins, yes /glist show fake players.
It takes even 3-4 hours to disconnect all fake players.

Maybe main reason its my timeout setting in config.yml?
I set it to 0, should it be more?

**Comment by Janmm14** [comment]
The timeout setting may not be 0, just remove it from the config to get the default value.

**Comment by Xayanix** [comment]
What it exactly does?
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Ten
e-mail został wysłany z komputera wolnego od wirusów chronionego przez
Avast.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2015-12-23 1:55 GMT+01:00 Janmm14 <notifications@github.com>:

**Comment by Janmm14** [comment]
If nothing was sent for the given milliseconds it closes the connection. 0 is equal to disabling the check.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
