### ISSUE TITLE
When Mojang Session Servers come back online, bungeecord still tells the client they're off

### ISSUE THREAD

**Issue by schentuu** [SpigotMC/BungeeCord#1671]
I really hate to re open closed issues, but this issue isn't fixed yet.
It seems like the real cause for problem has not been found so far.

When i search the web i find lots of people complaining about this bug.
But md-5 said "it is no bug" and tickets get closed without a solution.

So i assume the former reports did not showed clearly enough, that there actually is a problem.

See issue #1230 
(closed without solution)

See also https://www.spigotmc.org/threads/error-occurred-while-contacting-login-servers-are-they-down.24055/
(topic closed without solution)

See also https://www.spigotmc.org/threads/solved-error-occurred-while-contacting-login-server-are-they-down.25699/
(topic "resolved" the solution "restart bungeecord manually" is just a bad workarround)

The error occurs when the mojang session servers are at their limit.
The problem is that even after the session servers are back on normal operation bungeecord the reply of bungecord causes connecting clients to show the message "Error occurred while contacting login servers, are they down?"

While in this state, when a user is connecting, the bungeecord log says:

13:36:12 [SEVERE] Error authenticating schentuu with minecraft.net
io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/50.19.241.171:443
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:213)
	at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:123)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:745)

The problem with that is:
This behaviour goes on until the bungeecord is restarted.
Waiting (even for days!) won't help.
And please don't tell me that the mojang servers were offline for days, while i was able to connect to all 10 other gameservers i tested.

Without restarting bungeecord users will still receive the message "Error occurred while contacting login servers, are they down?" while the mojang servers are NOT down.

The problem is not caused by the host.
Normaly it operates flawlessly. But every now and then (when mojang servers are to busy) it fails and does not recover after mojang servers are back to normal operation.

If you need further info, please let me know.
But please don't close the issue again without further investigation.

**Comment by NickG365** [comment]
What build/version of BungeeCord are you running?  Did you grab a copy of the DNS records for sessionserver.mojang.com while affected by the issue?  If so, please provide it.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
