### ISSUE TITLE
./glist isnt working?

### ISSUE THREAD

**Issue by Zayneh** [SpigotMC/BungeeCord#1672]
./glist isnt working??,

i installed the new update to fix this issue. and it still isnt working but my bungeecoord is working perfectly fine.

**Comment by Janmm14** [comment]
Check your modules directory. Are you using the official version from http://ci.md-5.net/job/bungeecord ?
If not you need to download the modules manually to the modules directory (create if not there).

If you got the modules and it still does not work, look into your log file for any errors and show them.

**Comment by SysVoid** [comment]
Is it a no permissions error?

**Comment by Janmm14** [comment]
Requesting close.

**Comment by Janmm14** [comment]
Requesting close or answer from @Zayneh
