### ISSUE TITLE
Bug: [WARNING] Forced host server pvp is not defined

### ISSUE THREAD

**Issue by Gongerino** [SpigotMC/BungeeCord#1673]
10:40:45 [INFO] Using OpenSSL based native cipher.
10:40:45 [INFO] Using native code compressor
10:40:45 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1093
10:40:45 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
10:40:45 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
10:40:45 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
10:40:45 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
10:40:45 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
10:40:45 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
10:40:45 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"b6e26e0":1093 by SpigotMC
10:40:45 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"b6e26e
10:40:45 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAP
10:40:45 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"b6
10:40:45 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"b6e26e
10:40:45 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"b6e26e
10:40:45 [WARNING] Forced host server pvp is not defined
10:40:45 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"b6e
10:40:45 [INFO] Enabled plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"b6e26
10:40:45 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.8-SNA
10:40:45 [INFO] Enabled plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"b
10:40:45 [INFO] Enabled plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"b6e26
10:40:45 [INFO] Enabled plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"b6e26
10:40:45 [INFO] Listening on ......

Nothing else comes up after that.. Please help
Thank you!

**Comment by LaxWasHere** [comment]
Forced host server pvp is not defined.

**Comment by Gongerino** [comment]
Yes, so what do I do?

**Comment by RoboMWM** [comment]
So, did you try looking in your config? Or searching already-solved issues: https://github.com/SpigotMC/BungeeCord/issues/1667

**Comment by ravkr** [comment]
you have to put `forced_hosts: []` in your config or define server with name **pvp**

**Comment by schwie** [comment]
ravkr's line didn't work, but this works on macOS High Sierra:

forced_hosts: {}
