### ISSUE TITLE
Bungeecord not showing online players.

### ISSUE THREAD

**Issue by kingpyro** [SpigotMC/BungeeCord#1674]
I recently have change a value in my config.yml that needs to stay this way. The value being Force_Default_Server to True. With this being set to true, BungeeCord only displays the players logged onto the default server. Not all of them in other servers.

I have tested this in a test environment and have concluded with that enabled it does not display the proper player count. In this case, it only shows the amount of players in the hub and not the total amount of players. Having the force_default_server to false it shows all of the servers combined players.

Config.yml: http://pastebin.com/QiDZvjXC
BungeeCord version: Version 1093

**Comment by willies952002** [comment]
this is why you're only seeing information from the default server:

    ping_passthrough: true

This basically tells Bungee to pass the ping to the default server, which then responds with what you are seeing. So basically, you can either disable ping_passthrough (set it to false), or install a plugin into Bungee that will display the right player count.

**Comment by kingpyro** [comment]
Thank you very much, this resolved the issue. I thought that only brought back the stability of the connection.
