### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by kukubaczek** [SpigotMC/BungeeCord#1676]
Logs: http://pastebin.com/SzwG439T
After this players was kicked from server. I have OVH Anty-DDoS Game. In MRTG: 
![zrzut ekranu 2015-12-23 17 42 33](https://cloud.githubusercontent.com/assets/6909820/11980643/ba046f18-a99c-11e5-919b-78a13b3c3eab.png)

**Comment by Janmm14** [comment]
No issue on bungeecord's end, but definitely your image does not help anywhere.
Possible things:
- plugins are doing something in the network threads that lasts too long
- spambot attack?

**Comment by kukubaczek** [comment]
My plugins:
 - /helpop etc commands,
 - country checker GeoIP.dat (to block bots),
 - ServerListPlus - Motd manager.

Any bot attack.

W dniu czwartek, 24 grudnia 2015 Janmm14 <notifications@github.com>
napisał(a):

**Comment by Janmm14** [comment]
Possibly the county checker, please link it so I can look whether it could be the issue.

**Comment by kukubaczek** [comment]
I removed this yesterday. I wilk send you this tomorrow

W dniu sobota, 26 grudnia 2015 Janmm14 <notifications@github.com>
napisał(a):

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
