### ISSUE TITLE
[Kicked] You have logged in from another location 

### ISSUE THREAD

**Issue by LuminousViper** [SpigotMC/BungeeCord#1679]
I am using bungee cord and on my Hub i use the command '/server game' it connects to the correct server (bungee cord is setup correctly) but displays a kick message "you have logged in from another location"

**Comment by LuminousViper** [comment]
also i can connect to the server directly using :25567 w/ no issues but trying to connect threw bungee brings them

**Comment by Janmm14** [comment]
Does that always happen and is it related to that server switch? Is your bungee in online or offine mode? Can you look whether the backend server kicked you or the proxy? (Look logs)

Also make sure to edit firewalls or install OnlyProxyJoin ( https://www.spigotmc.org/resources/onlyproxyjoin.28/ ) to circumvent any player can log in to your backend server directly (and getting your permissions).

If you have [bungeecord in offline mode] or [in online mode AND you don't mid about the uuid from cracked -> premium change] do this (steps above are required!):
Set ```bungeecord: true``` in ```spigot.yml``` and set ```ip_forwarding: true``` in ```config.yml``` of bungeecord to allow the backend spigot server to get correct ip of the player and also to get the correct uuid.

Likely no issue with bungeecord but another user logging in as you.

**Comment by LuminousViper** [comment]
It only happens on the server switch and my bungee is on offline mode.
It says "LuminousViper lost connection: Internal Exception: java.io.IOException: Connection reset by peer"


Also i have done what you have said with the only proxy join. Firstly i placed the plugin in the 'games server' And in teh bungeecord CONFIG i made ip_forwarding true and true in spigot.yml in the games directory. But now when i try and join the games server it says "If you wish to use IP forwarding, please enable it in your BungeeCord config as well' and before you think im stupid it is enabled in bungee cord  config.yml


Thanks for quick reply :)

**Comment by LuminousViper** [comment]
Update: Now when i disconnect it says im still on the server and i cant join untill i restart:
You are already connected to this server

**Comment by LuminousViper** [comment]
Additionally it will occasionally say "You have to join threw the proxy"

**Comment by Janmm14** [comment]
For latest issue, you need to make sure usig the bungeecord ip and port.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
