### ISSUE TITLE
Re-enable Epoll by default

### ISSUE THREAD

**Issue by minecrafter** [SpigotMC/BungeeCord#1681]
Since the issue preventing us from using Epoll is fixed in Netty 4.0.31, and the Minecraft 1.8 server uses Epoll without issues, I think it's time we re-enable Epoll in BungeeCord by default.

**Comment by ninja-** [comment]
Yup, I fixed it personally some time ago :P aren't you fine with using -Dbungee.epoll?

**Comment by minecrafter** [comment]
This is about re-enabling it by default. I should have clarified as such.

**Comment by Harry5573** [comment]
+1

**Comment by Fireflies** [comment]
:+1:

**Comment by minecrafter** [comment]
It's re-enabled in 1182aff.
