### ISSUE TITLE
I got this error every 2~ seconds and it's probably crashing Bungee.

### ISSUE THREAD

**Issue by JuliCarles** [SpigotMC/BungeeCord#1682]
I got this issue and it's probably crashing our BungeeCord everyday.
http://pastebin.com/VsWseMKb 
BungeeCord 1.8 (ONLY) Versions.

**Comment by minecrafter** [comment]
That's a plugin issue. Ask the author.

**Comment by JuliCarles** [comment]
Here should be the place to ask him! @md-5

**Comment by Black-Hole** [comment]
The issue is known since May 2015, maybe look for another plugin?
https://www.spigotmc.org/threads/playerthrottlebungee.32711/page-2

**Comment by JuliCarles** [comment]
Oh, there was a lot before we updated PlayerThrottleBungee we are probably using the first version.
We will update and see if this problem continues, thanks @Black-Hole
