### ISSUE TITLE
Bungeecord Offline status

### ISSUE THREAD

**Issue by noammiz007** [SpigotMC/BungeeCord#1683]
can someone answer plz on my question?

my bungeecord server is working and all, but is show me offline status and i CAN connect to the server.
why this heappen?

**Comment by scholzi100** [comment]
May check out https://www.spigotmc.org/threads/1-7-2-1-8-bungeecord.392/ this site.

**Comment by scholzi100** [comment]
What do you mean exactly with "Offline status"?

**Comment by Janmm14** [comment]
@noammiz007 Issue solved? If yes, please close, else provide further information pleasr.
