### ISSUE TITLE
Proxy Lost Connection / Lag / Disconnects

### ISSUE THREAD

**Issue by roaspeci** [SpigotMC/BungeeCord#1684]
Hello everybody
i hope you can help me to figure out why my bungee server on the same root as the backends is very laggy and has bad connections while everything else is very fine.

For Details please see this Forum post:
https://www.spigotmc.org/threads/proxy-lost-connection-to-server.112299/

Thank you very much

**Comment by MrFrostmaul** [comment]
I am having the same issue as you and it only randomly started a few days ago.

**Comment by roaspeci** [comment]
Do you also can setup the proxy on another machine than the backends? 
Over the second proxy or directly on a backend it works fine and very good

**Comment by MrFrostmaul** [comment]
So your solution is to have the proxy on a different physical machine and it works better?

**Comment by roaspeci** [comment]
... yes it is very confusing!
After setting up bungee on a different (old) host all works fine - Backends are still on the new host (and the standalone one is still in best performance)

But this is no solution to me because the other old host is already cancelled! :(

.. Yesterday i forwarded the port on the "new" Server with the new domain name to the "old" Server with the old domain name (but working proxy) .. but the issues are the same: stays at "pinging" and very bad connection

So i think the Problem must be more on the host side but only belongs to Bungee (backends and standalone spigot are still very good) .. any ideas what is different between bungee and spigot? Any dependencies?? 


@MrFrostmaul is your proxy working on oracle java 1.8 build 66 (may be autoupdated)?
Because on my old server runs build 60 and on my new one build 66!

NEW Server:
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

OLD Server:
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

**Comment by MrFrostmaul** [comment]
Yeah, this is a weird issue with Bungee and from searching on the internet alot of people have had the same issue, but with no full solution.
My proxy was on build 50 of java 8, but updated to the latest just incase while trying to figure it out. I will try moving my proxy to another VPS i have and see if that fixes for me.

Thanks,

**Comment by roaspeci** [comment]
Can anybody help here? 
Problem is still there..

**Comment by MrFrostmaul** [comment]
Same for me, I have even bought another VPS for the proxy and all was working for 2 days then just started again today and been having every 5 - 15 mins normally.

**Comment by MrFrostmaul** [comment]
Roaspeci, may I ask how is your server host?

**Comment by roaspeci** [comment]
For sure .. may new host is 1blu! The old  one is server4you!

**Comment by Janmm14** [comment]
Try updating bungee to latest version.

**Comment by roaspeci** [comment]
Yesterday was a new version released. Actually iam waiting until this problem will come back again and then update my proxy. After that i will post again

**Comment by roaspeci** [comment]
In the evening the problem comes back again and i installed the latest release of bungeecord (1096).
But iam very sorry: nothing changed, problem is still the same! On the new VPS of 1blu it stays at "pinging" and/or i get kicked after a short while.

maybe it is based on shared VPS ressources like RAM and/or CPU? And dont happens to bigger networks with physical machines?

**Comment by MrFrostmaul** [comment]
I've updated my proxy (latest - pm last night) and so far everything seems to be working bueatifully once again :) - Will do more testing and see if it occurs again.

**Comment by MrFrostmaul** [comment]
Issue seems to be resolved for me by updating to the latest version (one that came out 2 days ago at 10pm)
