### ISSUE TITLE
BungeeCord keep crashing

### ISSUE THREAD

**Issue by MatteCarra** [SpigotMC/BungeeCord#1685]
Hello, i'm getting an exit code 134 with bungeecord. 

Version:This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1093 by md_5 

(I downloaded today, after an older version started crashing with code 134 this morning)

http://pastebin.com/Hu1yxAs2

**Comment by Janmm14** [comment]
Java issue. Update java or report bug to java as mentioned in the log.
Maybe the content of /home/minecraft/bungee/hs_err_pid21143.log shows further information.
