### ISSUE TITLE
Cannot connect, ServerConnector connecting to 2 servers.

### ISSUE THREAD

**Issue by bhsgoclub** [SpigotMC/BungeeCord#1688]
22:31:53 [INFO] [Lord_Popo] <-> ServerConnector [crowns] has connected
22:31:53 [INFO] [Lord_Popo] <-> ServerConnector [lobby] has connected
22:31:53 [INFO] [Lord_Popo] <-> ServerConnector [crowns] has disconnected
22:31:53 [INFO] [Lord_Popo] <-> ServerConnector [lobby] has disconnected

Not quite sure how to fix this.

**Comment by kamcio96** [comment]
Plugins?

**Comment by Janmm14** [comment]
Are the spigot servers on and is bungeecord configured correctly?
Most likely no issue with bungeecord.
