### ISSUE TITLE
CPU spikes

### ISSUE THREAD

**Issue by JhoniSilva** [SpigotMC/BungeeCord#1689]
Hey, I`m having some lag spikes in my bungeecord. I use 2 instances with Redisbungee to handle ~1k players. I've bought another machine but the problem persists.
Here is the snapshot: http://www.mediafire.com/download/6m5ase5jn950r91/BungeeCord1091-2016-01-06.zip
Can someone help-me?

**Comment by przemek3697** [comment]
Is this a 5 seconds lag everytime for a random player?

**Comment by JhoniSilva** [comment]
No, that lag affect all online players and show the Bungee instance offline while is lagging

**Comment by ThePhineas** [comment]
List of Bungee plugins & start script please.

**Comment by JhoniSilva** [comment]
Yamler, SkinRestorer, ServerInfo, RedisBungee, BungeePluginManager and AdvancedBungeeAnnouncer. 
I dont use any java flag in my start script. Simple as "java -jar -Xms2000M -Xmx3000M Bungeecord.jar"
That problem occours even without any plugins(I've tried), and without the -Xmx and -Xms.
O run the latest Bungeecord build.

**Comment by kamcio96** [comment]
use visualvm

**Comment by JhoniSilva** [comment]
Here is the snapshots with VisualVM
https://mega.nz/#!SoISiTyb!HB7nf4vlqhxts8qN11hMAJrdy2ZKQh7_EiXz5M1aFyo
The first one, show one of my 2 instances, when it is running without any problems or lags.
The second one, show the same instance when the lag spikes starts
The third one, show my other instance, with so many lag spikes. At this point, bungee starts to time out most of my players.
OBS: In every lag spike, the CPU usage increases to the max(using 100% of all cores/threads). Before lag spikes starts, the both instances together uses about 10 - 20% of CPU.
I've bought another machine (MC32 from OVH, game - i7 4790k) but the problem persists.

**Comment by md-5** [comment]
These snapshots are insufficient, you need to use YourKit please.

**Comment by JhoniSilva** [comment]
@md-5 Thanks for your attention. I love you
After so many tries, I updated java from 7 to 8(Oracle), and the Bungee instances are running for 2 days without any problems. 
If the problem returns, I will run YourKit before tell you. Thanks

**Comment by Janmm14** [comment]
@JhoniSilva Reminder this issue is still open. Consider closing it if all runs fine.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
