### ISSUE TITLE
BungeeCord - Can't connect to a server

### ISSUE THREAD

**Issue by Atmazphere** [SpigotMC/BungeeCord#1690]
Hello,
Recently (Today) I cannot connect to my "OPFactions" server but I can connect to any other server. Anyone else can connect to the OP Factions server even my alt can! I'm not banned or anything, it's just not letting me. Yesterday, it allowed me to connect fine and nothing happened like this. My other Owner, didn't change a single thing as he was away. Just today, it doesn't want to function with me.

There's no error in any consoles or anything, it just wont let me connect to that specific server... I tried regenerating the configuration and still nothing.

Running version: This server is running BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"b6e26e0":1093 by md_5
Here's the error: http://prntscr.com/9ne7aw

I know I spammed it, I was just showing an example.
Here's the plugin list for my OP Factions server  (From my alt): http://prntscr.com/9ne8p2

**Comment by i9hdkill** [comment]
when all other players can connect without any issues, you are banned 100%.
Are these players connecting through bungee?

**Comment by GooDGrounD** [comment]
Well i had a problem with a plugin called combat tag plus and the result was same as here. If a player disconnects when in combat mode an npc is spawned and player cant connect anymore.
