### ISSUE TITLE
BoneCP SecurityException

### ISSUE THREAD

**Issue by ItsHarry** [SpigotMC/BungeeCord#1691]
I'm trying to use BoneCP as MySQL connection pool, but BungeeCord keeps throwing SecurityExceptions.

What can I do about this? I thought about using Reflection to disable the in my case useless SecurityManager since I'm only using plugins written by myself anyway, but that seems to be blocked as well.

**Comment by minecrafter** [comment]
Initialize the pool in an async task and block until it's ready (try `FutureTask`).

Also, you should really be using HikariCP. The BoneCP author himself deprecated it and recommends HikariCP to replace it.

**Comment by ItsHarry** [comment]
Block the main thread or the async thread?

And I'll look into HikariCP later, I'm going to stick to the easier option for now since I'm already familiar with this. Thanks

**Comment by minecrafter** [comment]
Block the main thread.

**Comment by ItsHarry** [comment]
Okay I'll try that, thanks

**Comment by ItsHarry** [comment]
What if BoneCP needs to allocate a new thread after the plugin has already started though? Won't there still be warning messages?

**Comment by PunKeel** [comment]
Not if they're started from an async thread

**Comment by ItsHarry** [comment]
Oh okay, so the SecurityManager only checks if a new Thread is created on the main thread?

**Comment by Fireflies** [comment]
Sorry for the bump - a friend of mine recently encountered this so figured I'd post an explanation as to why this happens.

You can see [here](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeSecurityManager.java#L30) that only BungeeCord and java packages are permitted to start threads. If you start a thread by using the Bungee scheduler you get around that restriction.

**Comment by ItsHarry** [comment]
Yes, I figured that was the case. I've since made the switch to HikariCP, which allows you to set a custom ThreadGroup to be used
