### ISSUE TITLE
Bungeecord not turning on

### ISSUE THREAD

**Issue by UltraSwft** [SpigotMC/BungeeCord#1692]
Hello, on my network its not letting me turn on bungeecord its something to do with the config I think. 
here is the error my config will be under it.

Error: http://pastebin.com/22Su0ze3

Config: http://pastebin.com/javBqtDk

**Comment by Black-Hole** [comment]
As the message suggests, please update to the latest BungeeCord version. It should be fixed by this commit:
https://github.com/SpigotMC/BungeeCord/commit/b6e26e0c090e200a186a681a8de116caa04b3c4a

**Comment by UltraSwft** [comment]
Black-Hole it didnt work, i still does not work. same error

**Comment by UltraSwft** [comment]
The new Error: http://pastebin.com/03s0ntMF

**Comment by kamcio96** [comment]
your system probably doesn't support openssl
