### ISSUE TITLE
Unlimited REGISTER plugin message cache

### ISSUE THREAD

**Issue by ytripehard** [SpigotMC/BungeeCord#1695]
There is no limit for registering PluginMessage packets in memory.
This bug can be used to crash servers by sending a lot of packets as they are not cleared.
Also, changing server with some packets uploaded gives a big spike on one network thread.

**Comment by Xayanix** [comment]
Confirmed.
http://scr.hu/0duk/hximm

**Comment by OtekPlay** [comment]
+1

**Comment by ytripehard** [comment]
-1 for YtHard
