### ISSUE TITLE
Losing connection when trying to join forge server

### ISSUE THREAD

**Issue by Zangoran** [SpigotMC/BungeeCord#1697]
This happens when I try to connect to localhost which is passing me through bungeecord to the forge server and then it throws this error (below). But i can connect to the forge server manually and it works perfectly fine. I am trying to create a Sky Factory 2.4 server.
So the forge version is the one that is in the most updated version of Sky Factory, I don't know what version forge is, sorry. Below is all the errors and config files for you to figure out what is wrong.

Thanks for your time!

Error in client: http://pastebin.com/AR5DQmC0

Error in console of forge server:  http://pastebin.com/RqFW2HsZ

BungeeCord config.yml: http://pastebin.com/KAZn7f00

Forge server server.properties: http://pastebin.com/bHS9as6y

EDIT: Bump

**Comment by Zangoran** [comment]
Bump

**Comment by Janmm14** [comment]
```DecoderException: java.lang.ArrayIndexOutOfBounds Excepotion: -26 @ io.netty.handler.codec.MessageToMessageDecoder:99 ```
This indicates the mod is using negative packet ids, which will stay unsupported in bungeecord as of the last note I've seen (its a while ago).

**Comment by Zangoran** [comment]
I am using the sky factory mod pack. Do you know what mod that it could be?

**Comment by Zangoran** [comment]
@Janmm14 I found out that it is CoFH Core that is causing the issue. Do you know of a fix that allows BungeeCord the accept negative packet ids? If so could you please supply me with the answer? Thanks for you time!

**Comment by Janmm14** [comment]
Sorry, but no.

**Comment by Zangoran** [comment]
@Janmm14 Its ok I found an answer in a previous ticket with a modified bungeecord.jar file. Marking as closed.
