### ISSUE TITLE
Error when trying to connect to a server through Bungeecord

### ISSUE THREAD

**Issue by jdlx277** [SpigotMC/BungeeCord#1698]
Having the error: Could not connect to server, please try again later: io.netty.channel.ConnectTimeoutException, when trying to connect to one of my servers through the bungeecord hub. 

As far as I know, everything in the Bungee Config.yml has been setup properly, as well as the way that the prison server has been setup. I have also contacted my hosting provider to see if there was any type of firewall blocking the connection. I'm running my servers on multicraft, and the one server which will NOT connect is not on the same panel as the bungee server. As well there are completely no errors in either the bungee console, or the server console.

Any help is greatly appreciated because I have been attempting to fix this error for quite some time now. Thank you

Bungee Config.yml: http://pastebin.com/gNKffPVz
Prison server-properties.yml: http://pastebin.com/8wQeBhnN

![help](https://cloud.githubusercontent.com/assets/8679201/12219473/16af0646-b713-11e5-9927-e567dfea4b06.gif)

**Comment by MrFrostmaul** [comment]
We are getting the same issues as you, but also with our Proxy having a hissy fit and just kicking everyone off the network.

**Comment by deathharmony** [comment]
Same issue here, but only for new Servers i added in config.

**Comment by ThePhineas** [comment]
Is your host blocking connections from your proxy, since everything is on different machines? Maybe contact them?

**Comment by Janmm14** [comment]
Do you have set ```connection-throttle``` in ```bukkit.yml``` to ``` -1```?

Maybe get a timings report via console (console no ```/``` for commands) of the prison server while trying to join:

1. ```/timings reset``` (or ```/timings on``` if reset gives error)
2. Try to join.
3. ```/timings paste``` and show us the link.

This shows whether plugins cause the timeout due to long login / join listeners (async or not has no effect here)

**Comment by jdlx277** [comment]
We merged out bungeecord server to a different host and the same problem is occurring after a new Config.yml. As well we lost our Hub server, so our Fallback is now set as this server. My one question is whether or not the connection throttle needs to match in both servers. I'm not very experienced with the entirety of bungeecord so I greatly appreciate any help. As well all of the /timings commands did nothing when put into my console on both servers.

**Comment by Janmm14** [comment]
The connection throttle setting in bungeecord is currently unused while the connection throttle in craftbukkit/spigot servers should be at -1 in the bukkit.yml, otherwise issues can occurr. (Check out minotopiame/BungeeCordPatcher for enabled connection throttle in bungeecord)

**Comment by jdlx277** [comment]
Janmm14, I reset the bungee Config one more time and redid everything and after setting both servers connection throttle to -1 everything has started to work normally again! Thanks for everyone's replies and help. :)
