### ISSUE TITLE
Latest build #1096 causing a ClassCastException error on boot

### ISSUE THREAD

**Issue by accoladearts** [SpigotMC/BungeeCord#1700]
Latest build #1096 causing a ClassCastException error on boot:

    01:16:51 [INFO] Using OpenSSL based native cipher.
    01:16:51 [INFO] Using native code compressor
    01:16:51 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"aa214c0":1095
    01:16:51 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
    01:16:51 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
    01:16:51 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
    01:16:51 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
    01:16:51 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
    01:16:51 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
    01:16:51 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"aa214c0":1095 by SpigotMC
    01:16:51 [INFO] Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"aa214c0":1095 by SpigotMC
    01:16:51 [INFO] Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"aa214c0":1095 by SpigotMC
    01:16:51 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"aa214c0":1095 by SpigotMC
    01:16:51 [INFO] Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"aa214c0":1095 by SpigotMC
    01:16:51 [INFO] Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"aa214c0":1095 by SpigotMC
    01:16:51 [SEVERE] Exception in thread "main" 
    01:16:51 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
    01:16:51 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:174)
    01:16:51 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:92)
    01:16:51 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:248)
    01:16:51 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    01:16:51 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by md-5** [comment]
Your config is wrong
