### ISSUE TITLE
Stumped on Bungee Bug

### ISSUE THREAD

**Issue by Muzixs** [SpigotMC/BungeeCord#1703]
The proxy works, but randomly cuts/halts/crashs, something. I cant make head or tails of this report. Could I get some insight to the issue. Is it related to the node the server is hosted on? The server it self or a configuration issue?

Its the latest version of Bungee from: http://ci.md-5.net/job/BungeeCord/
CentOS 7
Java 8
4GB RAM (100 players at most on peak hours)

[hs_err_pid28828.txt](https://github.com/SpigotMC/BungeeCord/files/89243/hs_err_pid28828.txt)

**Comment by kamcio96** [comment]
Try disable epoll

**Comment by Muzixs** [comment]
This proxy server is being hosted on CentOS 6 x64 minimal build. This node is identical to other nodes that actively run Bungee without issue. I would like to assume that the epoll setting has nothing to do with the issue im getting, but I can see its mentioned in the report. So would you be able to explain its realtion to the issue before I proced with making changes?

**Comment by ninja-** [comment]
You are running out of memory. Trust me on this

**Comment by Muzixs** [comment]
I presummed 512MB for 500 players to start was the benchmark for running Bungee. This server has 4GB, with only 100 players joining at the most on peak hours. This information came from the Bungee wiki, did I misunderstand something?

**Comment by ninja-** [comment]
You didn't misunderstand anything but now as you have more experience you should increase it.

**Comment by Muzixs** [comment]
"but now as you have more experience you should increase it." Could you clarify that? You state to increase it, are you referring to the RAM? If so, why? The number of players this server gets doesn't add up to the amount it should be assigned. Wouldn't adding more actually intact the performance?

**Comment by ninja-** [comment]
your problem is out of memory error so increasing it is the only you can and should do

**Comment by Muzixs** [comment]
I'll do that. Could you point me to where you deduced this in the report so I can familiarize myself with what the error looks like?

**Comment by Janmm14** [comment]
@Muzixs
close
> [eden space 350208K, 90% used]
filled
>  object space 2097152K, 99% used

Also maybe update your java.

**Comment by i9hdkill** [comment]
are you sure it's the latest from the jenkins and you allocated 4gigs?

>jvm_args: -Xmx3072M -Xms3072M -XX:MaxPermSize=256m -Djline.terminal=jline.UnsupportedTerminal 
java_command: /home/minecraft/multicraft/servers/server16868/jar/custom256.jar nogui
java_class_path (initial): /home/minecraft/multicraft/servers/server16868/jar/custom256.jar

We are running a bungee with 180-300 players with
>-XX:+UseG1GC -XX:G1HeapRegionSize=4m -Dio.netty.recycler.maxCapacity.default=20000
just fine. Even with heavy plugins like bungeetablistplus
It's not a bungee bug, there must be a "broken/leaking" plugin that causes this.

I advice you to open a thread in BungeeCord help forum to get some help. This is not the right place for it.

**Comment by md-5** [comment]
Netty / Java bug
