### ISSUE TITLE
Help, Exception Connecting

### ISSUE THREAD

**Issue by austinator222** [SpigotMC/BungeeCord#1710]
This is the error I get when it says logging in:
Exception Connecting:RuntimeException : Server is online mode! @ 
net.md_5.bungee.ServerConnector:261

Please if you know the fix please tell me! My server is online mode and I have 0.0.0.0:25565 as the host just because for now I want to connect locally.

**Comment by kamcio96** [comment]
"My server is online mode"
it should be offline mode

Read wiki before reporting
