### ISSUE TITLE
Bungeecord not loading

### ISSUE THREAD

**Issue by Kremis** [SpigotMC/BungeeCord#1713]
Bungeecord is starting, but not fully loading. I have no idea what is wrong.
config - http://pastebin.com/aQKQFBR9
console when starting up - http://pastebin.com/kic7D2dg

**Comment by Black-Hole** [comment]
This doesn't look right:
 address: 0.0.0.0:25565

**Comment by Kremis** [comment]
You were right, that was the wrong ip. I fixed it, and bungee still won't load though :(

**Comment by Janmm14** [comment]
Please check out log files from bungee itself. I don't trust Multicraft.
