### ISSUE TITLE
Plugin.getPlugin(Class<? extends Plugin>)

### ISSUE THREAD

**Issue by TheMysterious** [SpigotMC/BungeeCord#1715]
Bungee has no feature to get a plugin instance by Class, that I know of, like JavaPlugin has.
Would be appreciated.
There is only a PluginManager.getPlugin(String). But my plugin name is not final.

**Comment by Janmm14** [comment]
Pass your plugin to your other classes in their constructor or create a static getInstance() method yourself (thats not recommended as its against oop)

**Comment by TheMysterious** [comment]
yeah but why is there no such method?

**Comment by minecrafter** [comment]
You can use:

```java
for (Plugin plugin : ProxyServer.getInstance().getPluginManager().getPlugins()) {
    if (plugin instanceof MyPlugin) {
        // my logic here
    }
}
```

However, this is inherently bad logic, especially as plugins shouldn't be declaring static methods like that.

Look at the Bukkit API as an example of bad design.

**Comment by Scrayos** [comment]
A singleton-approach always worked well for me. You can access the main-class from everywhere without any relevant disadvantages.

**Comment by Janmm14** [comment]
Requesting close.
