### ISSUE TITLE
ComponentBuilder's Retention seem to have inconsistencies

### ISSUE THREAD

**Issue by Scrayos** [SpigotMC/BungeeCord#1716]
Hey,

I recently worked a lot with the ComponentBuilders and there seems to be an error in the generation of the JSON-String (as far as I can judge it)

![c8d4035f1625aaffde9cab314b549e94](https://cloud.githubusercontent.com/assets/2124642/12552171/52b2a85a-c370-11e5-9371-6c7d1d2a0288.png)

This is the result of the following code: 

```java
.event(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder("Spielerinfo\n").color(ChatColor.DARK_GREEN).bold(true)
    .append("Namen: ", ComponentBuilder.FormatRetention.NONE).bold(false).color(ChatColor.DARK_GREEN)
    .append(StringUtils.join(n_recipient, ", ") + "\n", ComponentBuilder.FormatRetention.NONE).color(ChatColor.GRAY)
    .append("Rang: ", ComponentBuilder.FormatRetention.NONE).color(ChatColor.DARK_GREEN)
    .append(u_recipient.getGroup().getFormattedName(), ComponentBuilder.FormatRetention.NONE).color(ChatColor.GRAY)
    .create()))
```

As you can see I use FormatRetention.NONE which should prevent ANY previous formatting from getting preserved. Because it didn't worked at all (Everything was bold) I forced it to be slim by calling .bold(false) in the second line. And as you can see in the screenshot it works for the second line but every appended element after this is bold again. It's as if the new Standard has become "bold".

Haven't tested this for underline and striketrough but I'm convinced that this would also apply to them. This issue may also be valid for spigot.

**Comment by Janmm14** [comment]
I think your issue here is the getFormattedName method which likely outputs code with the old color system.

**Comment by Scrayos** [comment]
Nope, it doesn't. The FormattedName is indeed just a correctly capitalized version of the .getGroup().name() method which I didn't used because it's an enum-constant e.g: ADMINISTRATOR which isn't nice for displaying it to users :)

**Comment by Paulomart** [comment]
Simple to prove: write ja unit test for it

**Comment by Janmm14** [comment]
The thing is that the first bold=true seems to set the default boldness for any further append calls.

**Comment by kamcio96** [comment]
All is correct, https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/ComponentBuilder.java#L240 
You don't retain text data, but minecraft know who is parent and use parent's format.
You can see it with that method: https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/chat/ComponentSerializer.java#L45

**Comment by Scrayos** [comment]
So instead of not retaining it I've to force .bold(false) on every appendix since the appendixes are the "extra"-Part of the new JSON-Chat-Format and they inherit the boldness from the parent?

We need that reset(true)-method for sure.

**Comment by kamcio96** [comment]
or FormatRetention.RESET :)

**Comment by Janmm14** [comment]
One could make the text in the constructor ```""``` without any formatting and use append for everything so format doesn't get inherited.

**Comment by Scrayos** [comment]
I think FormatRetention.RESET symantically doesn't make too much sense. Maybe the described behaviour should be the default for FormatRetention.NONE since that's what you would expect of it?

**Comment by Scrayos** [comment]
Btw: As a workaround @Janmm14 's solution works brilliantly.
