### ISSUE TITLE
Players get kicked interacting with player skulls

### ISSUE THREAD

**Issue by EnderSandman** [SpigotMC/BungeeCord#1719]
Players get kicked from servers sometimes when they open an inventory with a player's skull in it.  Players always get kicked when they click on or try to place a player skull in their inventory. I don't know the exact build this started in but when I reverted back to build #1105, the problem stopped.  It happens on a test server I created to test this problem that only had the latest paper spigot jar and the latest version of EssentialsX. If I remove this server from the bungee network, the problem goes away. Let me know if you need more info or if there is anything you want me to try/test and I would be happy to help.

**Comment by Janmm14** [comment]
Possible duplicate of #1717
Please compare your error with the error in that ticket.
