### ISSUE TITLE
Respawn packet

### ISSUE THREAD

**Issue by Th3Tr0LLeR** [SpigotMC/BungeeCord#1721]
Hi.

Sending a respawn packet (net.md_5.bungee.protocol.packet.Respawn) will result chunk loading glitches. Client has to hit F3 + A to fix that.

I noticed that when i was trying to send client packet to the player, so i can refresh his GameProfile (In bungee LoginResult).

Anyone knows something about that ?

**Comment by md-5** [comment]
Sending packets is not part of the API and not supported. You need to deal with such issues yourself.

**Comment by Janmm14** [comment]
You might need to create a fake death for the respawn packet.

**Comment by Th3Tr0LLeR** [comment]
@Janmm14 How could that be done ? I'm really new with Bungeecord packets.

I also need to send packet like PacketPlayOutNamedEntitySpawn.

**Comment by Janmm14** [comment]
Well if you want to do everything on bungeecord side and not spigot, I can't help that much. But its basically setting the players health to ```0``` and then respawn him. might help, don't know exactly.
