### ISSUE TITLE
Plugin messaging channel causing lag

### ISSUE THREAD

**Issue by Th3Tr0LLeR** [SpigotMC/BungeeCord#1725]
Hello. Today i started using the plugin messaging channel and i noticed that it causes lag.
I am using it to execute a method from a bukkit plugin and after the method is finished, th server freezes for 1-2 soemtimes for 5 seconds. I don't rly know if bungeecord is causing that, but i'm reporting it as a issue.

I will add my method, so you can know if this is caused by me. If you know please tell me how to fix it.

    public void sendUpdateRequest(final UserConnection p, final boolean removeSkin) {
    	ByteArrayOutputStream b = new ByteArrayOutputStream();
    	DataOutputStream out = new DataOutputStream(b);
		try {
			out.writeUTF("ForwardToPlayer");
			out.writeUTF(p.getName());
			out.writeUTF("UpdateChannel");
            if (removeSkin==true){
            out.writeBoolean(true);
            }else{
            out.writeBoolean(false);
            }
    	out.write(b.toByteArray()); 
		} catch (IOException e) {
			e.printStackTrace();
		}
    	p.getServer().sendData("UpdateChannel", b.toByteArray());
			}

**Comment by lukas81298** [comment]
Try to execute it asynchronously

**Comment by Th3Tr0LLeR** [comment]
I tried. The result was the same

P.S. i tried with the runAsync method. Any other way ?

**Comment by md-5** [comment]
You're saying the above code causes Bungee to freeze?

**Comment by Th3Tr0LLeR** [comment]
@md-5  Yes.

If i call the method without sending the data to the server it's OK, but when i send the data Bungeecord freezes for 1-2 seconds. Even if im using runAsync and new Thread() (which isnt allowed).

**Comment by md-5** [comment]
Method literally just sends it like any other packet :\

**Comment by Th3Tr0LLeR** [comment]
Yes. I know. I even tried to send the packet directly, but it was the same. How do i see which method causes the lag ? Bungeecord doesn't rly have timings.

**Comment by przemek3697** [comment]
I suggested it in #1636
Our network has similar problems but I think this somewhere else. But maybe this is some of points

**Comment by Black-Hole** [comment]
The line "out.write(b.toByteArray());" might write some GB in a loop. :)

**Comment by Th3Tr0LLeR** [comment]
@Black-Hole Depends how much players are online, but i will change that now.

**Comment by Th3Tr0LLeR** [comment]
Should i bump now ?

**Comment by kamcio96** [comment]
remove out.write(b.toByteArray());

**Comment by Th3Tr0LLeR** [comment]
Then it will never send the data..


2016-02-01 19:48 GMT+02:00 kamcio96 <notifications@github.com>:

**Comment by Janmm14** [comment]
Its doubled written if you do not remove that line.

**Comment by Th3Tr0LLeR** [comment]
I don't know if you will help if it's about SkinsRestorer, but now it looks like this and still freezes for a sec.

Request sender
    public void sendUpdateRequest(final UserConnection p, final boolean removeSkin) {
    	final ByteArrayOutputStream b = new ByteArrayOutputStream();
    	final DataOutputStream out = new DataOutputStream(b);
		SkinsRestorer.getInstance().getProxy().getScheduler().runAsync(SkinsRestorer.getInstance(), new Runnable(){

			@Override
			public void run() {
    	try {
			out.writeUTF( p.getName() );
            if (removeSkin==true){
            out.writeBoolean(true);
            }else{
            out.writeBoolean(false);
            }
         
         p.getServer().sendData("SkinUpdate", b.toByteArray());
		} catch (IOException e) {
			e.printStackTrace();
		}}});
			}

Request receiver
   @Override
   public void onPluginMessageReceived(String channel, final Player player, final byte[] message) {
     if (!channel.equals("SkinUpdate")) {
       return;
     }
		    	 ByteArrayDataInput in = ByteStreams.newDataInput( message );
		    	 String target = in.readUTF();
		    	 boolean removeSkin = in.readBoolean();
		    	 if (Bukkit.getPlayer(target)==null){
		    		 return;
		    	 }
		    	 if (removeSkin==true){
		    		 removeSkin(Bukkit.getPlayer(target));
		    		 return;
		    	 }
		     updateSkin(Bukkit.getPlayer(target));
		     System.out.println(target);
   }

**Comment by md-5** [comment]
Are you sure this isn't the server freezing, not bungee.

**Comment by Th3Tr0LLeR** [comment]
@md-5 it seems to be the server, but isn't that a problem too ? The TPS isn't changed even if i made it non Async.

**Comment by NickG365** [comment]
What are your removeSkin and updateSkin methods doing?  Is there anything in there that could be slowing things down?

**Comment by Th3Tr0LLeR** [comment]
They're just sending packets. Asynchronously. The packets are for removing
gameprofile, adding it back, respawning. Some other packets for position
and held item slot. They are also reloading player's chunks.

2016-02-07 19:54 GMT+02:00 Nick <notifications@github.com>:

**Comment by Th3Tr0LLeR** [comment]
Refreshing too many chunks at once caused the lag.
Sorry. Closing!

**Comment by Janmm14** [comment]
@Th3Tr0LLeR
Icreated the plugin Customskins (can be found on spigotmc.org) and I do not have to refresh chunks. One user forked my project and provided the simple fix of sending a ```WrapperPlayServerRespawn``` packet followed by teleporting the player to his old location and setting isFlying and isFlyingAllowed again after that.
You can find my code at https://bitbucket.org/Janmm14/custom-skins/src/ce84c2ab552464e8144d46e03a3900541bd8b9cd/bukkit/src/main/java/de/janmm14/customskins/bukkit/wrapperimpl/ProtocolLibSkinHandler.java?at=master&fileviewer=file-view-default#ProtocolLibSkinHandler.java-275

**Comment by Th3Tr0LLeR** [comment]
Thank you, but i don't want to use ProtocolLib.

**Comment by Janmm14** [comment]
@Th3Tr0LLeR Its just about the packet you need to send, you can send it also with NMS or your own packet library or whatever. Just that you do not need to resend chunks on skin update.

**Comment by Th3Tr0LLeR** [comment]
@Janmm14  If i don't do it, it starts glitching. Try it yourself with, and without.
