### ISSUE TITLE
Names like "1002" (full number names) do not work in Bungee.

### ISSUE THREAD

**Issue by ApleetServers** [SpigotMC/BungeeCord#1726]
My IGN is "1002", full number names apparently don't work. I found it fixes when I change it to a letter name, leading me to use a alt, Please fix this.

https://gyazo.com/4c94327077f9f8d1631aeaa70ca4ada6
https://gyazo.com/4232f8f5e39e1d4068295c54cd6f23fb

**Comment by 0x277F** [comment]
What do you mean by "don't work"? Could you take some screenshots showing it (as it would be hard for anyone without a name like that to test)?

**Comment by ApleetServers** [comment]
I have updated it with pictures now.

**Comment by minecrafter** [comment]
Try adding quotes around your username.

**Comment by ApleetServers** [comment]
Thank you minecrafter!
