### ISSUE TITLE
Nullpointerexception - ServerConnectEvent

### ISSUE THREAD

**Issue by voodootje0** [SpigotMC/BungeeCord#1730]
Hey,

I got this nullpointerexception http://pastebin.com/raw/TaR0Emrv

My code is:
![image](https://cloud.githubusercontent.com/assets/6852308/12703549/295d6a78-c846-11e5-89b0-f6a05743ed05.png)

Is this a mistake in bungeecord or I code it wrong?

Kind regards,
voodootje0

**Comment by minecrafter** [comment]
`ServerConnectEvent` gets posted before the server connection is even established.

**Comment by voodootje0** [comment]
Oh, what is than the best event to use?

**Comment by voodootje0** [comment]
This is very strange, for example when I go from server1 to server2 it works.
But when I the server (from server list) to server1 it doesn't work.

**Comment by Black-Hole** [comment]
Have a look at ServerConnectedEvent and ServerSwitchEvent

**Comment by voodootje0** [comment]
@Black-Hole Thank you very much, ServerSwitchEvent works and ServerConnectedEvent has the same as ServerConnectEvent.
