### ISSUE TITLE
InitialHandler - encountered exception

### ISSUE THREAD

**Issue by IpNoZeWaRx** [SpigotMC/BungeeCord#1731]
Hey, Bungee doesn't want log me :c 
Can you help me ? 
Log: 
http://pastebin.com/432XwPET

Config:
http://pastebin.com/qytFsQ1Z

Thanks

**Comment by minecrafter** [comment]
Looks like your Java install is a bit messed up. Try reinstalling it.

**Comment by IpNoZeWaRx** [comment]
Why ? Java Or Bungee ? It's the last version of java

**Comment by Phineas** [comment]
Re-install Java. Just because you have the latest version and everything doesn't mean something didn't mess up on your previous installation.

**Comment by IpNoZeWaRx** [comment]
I test it, wait a minute :)

**Comment by IpNoZeWaRx** [comment]
I've reintalle him, but i've the same error..

**Comment by IpNoZeWaRx** [comment]
If I put On Offline mode I can connect on the server, but on Online mode I can't, Why ?

**Comment by minecrafter** [comment]
Please add in the unlimited strength cryptography files from Oracle:

Java 8: http://www.oracle.com/technetwork/java/javase/downloads/jce8-download-2133166.html
Java 7: http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

**Comment by IpNoZeWaRx** [comment]
I've se same error :c

**Comment by Janmm14** [comment]
@IpNoZeWaRx If you have the same error, try the same solution provided and do not just post here you have that error.

**Comment by IpNoZeWaRx** [comment]
I've Try the solution, but he doesn't work.

**Comment by kamcio96** [comment]
Can you run server with online mode?

**Comment by IpNoZeWaRx** [comment]
Yes, but I can't connect with Proxy bungee, And If I put that on offline mode I can connect

**Comment by kamcio96** [comment]
You told it few times, we know...

It looks like Java bug, I don't know what exactly.
Try run ```java -version``` and run bungee with full java path, be sure it is latest version

**Comment by IpNoZeWaRx** [comment]
It's the last version

**Comment by IpNoZeWaRx** [comment]
bungee with full java path ? I don't understead..

**Comment by kamcio96** [comment]
Eg: ```"C:/Program Files/Java/jre_version/bin/java.exe" -Xmx2G BungeeCord.jar```

**Comment by IpNoZeWaRx** [comment]
I've this: ```
C:\Users\clement\Documents\Serveurs\BungeeCord>"C:\Program Files (x86)\Java\jre1
.8.0_71\bin\java.exe" -Xmx512M BungeeCord.jar
Error: Could not find or load main class BungeeCord.jar
```

**Comment by kamcio96** [comment]
```"C:/Program Files/Java/jre_version/bin/java.exe" -Xmx2G -jar BungeeCord.jar```
 my bad
