### ISSUE TITLE
Certain items causing crashes

### ISSUE THREAD

**Issue by SP33DCRAFT** [SpigotMC/BungeeCord#1742]
Hi, on my network, no matter what server you are on, when I click on playerheads aswell as items from a bukkit plugin called slimefun (which may or may not be relevant), it crashes my game. This error also effects other players. An error appears in the bungeecord console (not in the bukkit server's), and I do not know what it means

Error from console (My username is SP33DWAY):

09.02 21:37:46 [Multicraft] Skipped 12 lines due to rate limit (30/s)
09.02 21:37:45 [Server] INFO at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:11)
09.02 21:37:45 [Server] INFO at net.md_5.bungee.compress.PacketDecompressor.decode(PacketDecompressor.java:42)
09.02 21:37:45 [Server] INFO at net.md_5.bungee.jni.zlib.NativeZlib.process(NativeZlib.java:43)
09.02 21:37:45 [Server] INFO at io.netty.buffer.SlicedByteBuf.memoryAddress(SlicedByteBuf.java:112)
09.02 21:37:45 [Server] INFO at io.netty.buffer.PooledHeapByteBuf.memoryAddress(PooledHeapByteBuf.java:262)
09.02 21:37:45 [Server] INFO Caused by: java.lang.UnsupportedOperationException
09.02 21:37:45 [Server] INFO at java.lang.Thread.run(Unknown Source)
09.02 21:37:45 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
09.02 21:37:45 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:255)
09.02 21:37:45 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:339)
09.02 21:37:45 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:823)
09.02 21:37:45 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
09.02 21:37:45 [Server] INFO at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
09.02 21:37:45 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
09.02 21:37:45 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:263)
09.02 21:37:45 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:276)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:304)
09.02 21:37:45 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:318)
09.02 21:37:45 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:99)
09.02 21:37:45 [Server] INFO io.netty.handler.codec.DecoderException: java.lang.UnsupportedOperationException
09.02 21:37:45 [Server] SP33DWAY -> UpstreamBridge - encountered exception

One of my bukkit server's plugins list:
![2016-02-10](https://cloud.githubusercontent.com/assets/17050887/12953825/fc080cd8-d013-11e5-918e-773575d29dbd.png)

Another server's plugin list:
![2016-02-10 1](https://cloud.githubusercontent.com/assets/17050887/12953893/44403106-d014-11e5-9561-01e6d39394be.png)

BungeeCord server's plugin list:
![2016-02-10 2](https://cloud.githubusercontent.com/assets/17050887/12953887/3cd6805a-d014-11e5-9e87-0c95a7312080.png)

Thanks for any help!

**Comment by thinkofdeath** [comment]
Update bungee

**Comment by Janmm14** [comment]
Also posting logs from multicraft with console log message rate limits is highly NOT effective and you should never search in rate limited multicraft log for issues.
