### ISSUE TITLE
VPN Or Proxy Error!

### ISSUE THREAD

**Issue by ConnorPlaysYT** [SpigotMC/BungeeCord#1745]
Hello, I have just set up my bungee cord config.yml to what I need for my 3 server (not including bungee server) and when every I use the new bungee cord ip to connect me to my hub I am not able to join it says that I'm using a VPN or Proxy when I'm not and so join any of my servers. Reply if you need me to send you other information like the ip's or anything to help find the solution.

**Comment by hibo98** [comment]
If you use Spigot servers then set them offline mode and in spigot.yml `bungeecord = true` and also modify ip to 127.0.0.1 on the Minecraft servers.
https://www.spigotmc.org/wiki/bungeecord-installation/#post-installation

I think this can be closed.

**Comment by Janmm14** [comment]
You need to do these things:

* Bungee's config.yml: ```ip_forwarding: true```
* Spigot's spigot.yml: ```bungeecord: true```
* If you run bungee and spigot servers on the same machine, set in server.properties: ```server-ip=127.0.0.1```
* If you run bungee on another machine, either use the plugin https://www.spigotmc.org/resources/onlyproxyjoin.28/ or set up iptables to restrict access to your spigot server's ports.

**Comment by md-5** [comment]
Bungee has no such VPN detection, you probably installed a plugin
