### ISSUE TITLE
Bungeecord corrupted Jarfile

### ISSUE THREAD

**Issue by Sprungente** [SpigotMC/BungeeCord#1747]
Only what i have done is a javaupdate so 1.8_73. 
Since the update are done, all spigotserver from me works fine only the bungeecord
error: Invalid or corrupted jarfile

I try to start Bungeecord on my pc and my dedicated rootserver but nothing works. 
of course i have redownload the newest Bungeecordfile

anybody here, they can help me?

**Comment by Janmm14** [comment]
Latest ```BungeeCord.jar``` (build 1116) from http://ci.md-5.net/job/bungeecord/ works fine for me. You maybe should redownload again.
