### ISSUE TITLE
BungeeCord Help Please.

### ISSUE THREAD

**Issue by Wazupbutrcup** [SpigotMC/BungeeCord#1748]
Hello, can someone help me/tell me what i did wrong?
BungeeCord Config:
http://pastebin.com/hMM5b7mq
Server Console:
http://pastebin.com/nTaML0LB

And another question should people beable to connect throught bungee ip or the hub ip?.
Like which ip would you use to login with?

Everytime i do try to join the server i get; Server:could not connect to default or fallback server, please try again later: java.net.ConnectException
Server -> Upstreambridge has disconnected

**Comment by willies952002** [comment]
> And another question should people beable to connect throught bungee ip or the hub ip?.

Since you are using BungeeCord, your players should only connect via the Bungee port. If they are able to connect to a server directly it's a security issue.

Also, are your servers in online or offline mode?

**Comment by Janmm14** [comment]
Please do not give multicraft logs for errors, take some minutes to go to the proxy.log files and get a sanme log without a log rate limit.

This might not be apply to you directly, but I want to state that it sometimes hides errors.

Please note that any craftbukkit/spiogt servers which shoul operate behind bungeecord are required to be in offline mode. More information: https://www.spigotmc.org/wiki/bungeecord-installation/ and https://www.spigotmc.org/wiki/firewall-guide/

**Comment by Wazupbutrcup** [comment]
Bungee Logs
http://pastebin.com/J12VB6xS

**Comment by md-5** [comment]
This is for bugs not support.
