### ISSUE TITLE
Already connected.

### ISSUE THREAD

**Issue by frostlord22** [SpigotMC/BungeeCord#1749]
I've been having this issue with bungeecord #1​11​6, it seems to happen more frequently in this version as before, however i've been experiencing this issue for about a year now.

I'm unable to execute any command, i'm able to interact with things, see people chat and message me and chunks don't seem to load further out.

23:05:39 [INFO] [lichcraft22] <-> InitialHandler has connected
23:05:40 [INFO] [/192.99.21.109:33402] <-> InitialHandler has connected
23:05:40 [INFO] [/192.99.21.109:33404] <-> InitialHandler has connected
23:05:40 [INFO] [/192.99.21.109:33406] <-> InitialHandler has connected
23:05:40 [INFO] [lichcraft22] <-> ServerConnector [hub9] has connected
23:05:41 [INFO] [/151.230.248.160:53470] <-> InitialHandler has connected
23:05:41 [INFO] [/192.99.21.109:33429] <-> InitialHandler has connected
23:05:41 [INFO] [/192.99.21.109:33431] <-> InitialHandler has connected
23:05:42 [INFO] [lichcraft22] <-> InitialHandler has connected
23:05:42 [INFO] [/192.99.21.109:33436] <-> InitialHandler has connected
23:05:42 [INFO] [/192.99.21.109:33438] <-> InitialHandler has connected
23:05:42 [INFO] [lichcraft22] disconnected with: §cYou are already connected to this server!
23:05:42 [INFO] [lichcraft22] disconnected with: §cYou are already connected to this server!
23:05:42 [INFO] [lichcraft22] <-> ServerConnector [hub9] has connected
23:05:42 [INFO] [lichcraft22] disconnected with: §f[Proxy] Lost connection to server.
23:05:42 [INFO] [lichcraft22] <-> DownstreamBridge <-> [hub9] has disconnected
23:05:43 [INFO] [lichcraft22] -> UpstreamBridge has disconnected

**Comment by Janmm14** [comment]
Then do the described issues occurr exactly? After you've sawn the already connected log messages?

Also referring to https://github.com/WaterfallMC/Waterfall/issues/26
It says there that theconnection_throttle prevents the described issues and it happns because bungeecord has it disabled by default.

**Comment by frostlord22** [comment]
bungeecord is set at connection_throttle: 3000
the server it's connecting to is configured at  connection-throttle: -1

**Comment by md-5** [comment]
Post your config, you likely have Bungee connecting to itself

**Comment by frostlord22** [comment]
http://pastebin.com/VUa8cfuv

**Comment by Black-Hole** [comment]
You should use some YAML parser like https://yaml-online-parser.appspot.com/
If you paste your config there it will show you some errors. Have a look at your server section.

**Comment by frostlord22** [comment]
it doesn't spit out any yaml errors.
I've edited it a bit to now display these ip's.

**Comment by md-5** [comment]
You deleted the IPs which is what we were after.

Anyway you have Bungee connecting to itself. Fix your IPs or ask the forums for support.

**Comment by frostlord22** [comment]
http://pastebin.com/uCE9P2dw

All the ips are differences from the bungeecord ips, it's not just this instance,  it's multiple bungeecord instances.

**Comment by me4502** [comment]
I can confirm that it is not connecting to itself.
