### ISSUE TITLE
SEVERE Feb 17, 2016 12:06:01 PM io.netty.channel.DefaultChannelPipeline$TailContext exceptionCaught

### ISSUE THREAD

**Issue by maxlehot1234** [SpigotMC/BungeeCord#1751]
Hi everyone, I have this problem with BUngeecoord 1116 build.
http://pastebin.com/RcrxLukz

It simply spam my console each 10-15 minutes without reason or I don't know why...

Anyone have a fix for this?

I have skinrestorer, bungeetablistplus, java8, debian7

Thank you ;)

**Comment by minecrafter** [comment]
Invalid session data, can be safely ignored
