### ISSUE TITLE
Netty is not using direct IO buffers

### ISSUE THREAD

**Issue by maxlehot1234** [SpigotMC/BungeeCord#1752]
Hi everyone, sorry for double issue but they are not the same...

I use latest bungeecoord devbuild and I see this in the console:
Netty is not using direct IO buffers

No error, nothing more than this, but NOONE can connect to my servers....

Anyone can check this and give me a solution?

I have Java 8, debian7

Thankyou

**Comment by minecrafter** [comment]
This isn't a bug. You're experiencing a different issue that is likely a misconfiguration on your side.

Ask for help on the Spigot forums: https://www.spigotmc.org/forums/bungeecord-help.70/

**Comment by maxlehot1234** [comment]
I already put a threads on bungeecoord help, but what can cause this if I setup it all things great
