### ISSUE TITLE
BungeeCord p.connect(ServerInfo server) error.

### ISSUE THREAD

**Issue by didjee2** [SpigotMC/BungeeCord#1754]
This error is only since the last BungeeCord version, it worked perfectly before.
(Btw, there is a NullPointerException check for the ServerInfo & the player is still being sent).

Error: http://pastebin.com/ZiSqLE9P

Note: Nothing was changed into HubBalancer (private/custom plugin), it only came with updating BungeeCord. (We were 10 versions behind). We are now using **Build #1118 (18-feb-2016 17:07:45)**

**Comment by Paulomart** [comment]
First guess: server is not in your config

**Comment by Black-Hole** [comment]
Anyway, it's a plugin issue. The exception is happening in your plugin. So you should add more null checks for all other possible values.

**Comment by didjee2** [comment]
Well, just to say, having it with other plugins too. Even with BungeeCord's buildin /send

**Comment by didjee2** [comment]
Sorry, accidentally closed it

**Comment by didjee2** [comment]
And another thing, it came with the latest version. Nothing wrong when I downgrade again.

**Comment by didjee2** [comment]
Well, it has been fixed. I still don't know why it only came with Build 1110 and higher, no errors or problems below.
But I added a catch for this, the error spam is gone :+1:
