### ISSUE TITLE
Same ports how shall i do?

### ISSUE THREAD

**Issue by GammerGemplay** [SpigotMC/BungeeCord#1759]
I know i use 2 same ports but is there some body there would send a example of how i should do?
(Im buying my server from OwnageHosting)

My previous post..

When i use Bungeecord, and i want it to have the default server, to the server i also use for host bungeecord! But when i try to join i getting kicked and it says: You are already connected to that server?? what shall i do?﻿

https://gyazo.com/6998e0618fce665f4d0b7504309d14f6

and the issue

https://gyazo.com/ae1ba37d2a1eaf355a366b6291f707ca

**Comment by XxCoolGamesxX** [comment]
Stop make issue posts.

**Comment by Thinkofname** [comment]
Please stop opening issues, this tracker is for bugs. Ask on the forums for support https://www.spigotmc.org/forums/bungeecord-help.70/
