### ISSUE TITLE
I cant connect to other servers

### ISSUE THREAD

**Issue by GammerGemplay** [SpigotMC/BungeeCord#1760]
If im trying to use /server Prison
It says that the server is online mode, but it has to be, if ells everybody loose ther money and so?
what to do?

https://gyazo.com/187013d75ef07e1c9c449f08252295a9

**Comment by Black-Hole** [comment]
Please use the forum.

**Comment by willies952002** [comment]
There are 2 steps you need to take:
**If you're server is not on the same machine as the bungeecord proxy, skip 2**

1. Set your server into offline mode in server.properties -> `online-mode=false`
2. Set your server ip in server.properties -> `server-ip=127.0.0.1`
3. Enable bungeecord support in spigot.yml -> `bungeecord: true`

[Source](https://www.spigotmc.org/wiki/bungeecord-installation/#post-installation)
