### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1761]
Hi, on the newest version I have "Too many open files" error.

**Comment by kamcio96** [comment]
Do you have animated motd plugin?

**Comment by CzlowiekKuktas** [comment]
No, yesterday I installed BungeeMOTD, but it still was happening. I installed previous version today (#1118) and it's good so far.

**Comment by kamcio96** [comment]
Don't use plugin for animated motd. Other plugins?

**Comment by CzlowiekKuktas** [comment]
BungeePremiumAuthenticator and BungeeMSG.

**Comment by kamcio96** [comment]
I don't know both, try test without

**Comment by CzlowiekKuktas** [comment]
Not possible, but it didn't happen before.

**Comment by jflory7** [comment]
@CzlowiekKuktas Where is your BungeeCord instance being hosted from? This sounds more like a Linux server misconfiguration than BungeeCord.

http://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by CzlowiekKuktas** [comment]
OVH.

**Comment by jflory7** [comment]
@CzlowiekKuktas Okay, this is probably something you will need to do on your own from the command line. Check out the link I posted above and that should resolve this issue for you.

**Comment by CzlowiekKuktas** [comment]
It is still happening.
