### ISSUE TITLE
Another server bungee cord in my minigame

### ISSUE THREAD

**Issue by Nya017** [SpigotMC/BungeeCord#1763]
I do not want people to enter directly to a server.
And another person can create another bungeecoord and add the IP of my minigame and enter without password.
A few days ago someone destroyed me my progress, but only in that minigame.
That person entered without entering the lobby

My server is offline mode.
Bungeecord: ip_forward: true
Spigot: Bungee: true

Any help?
Thanks!

**Comment by Nya017** [comment]
I speak spanish, because the text have errors. excuse me.

**Comment by minecrafter** [comment]
https://www.spigotmc.org/wiki/firewall-guide/
