### ISSUE TITLE
Already connected ( address issue #1734)

### ISSUE THREAD

**Issue by JHXSMatthew** [SpigotMC/BungeeCord#1764]
Hi,

I am still having the same issue as #1734 
It was closed by @md-5 but It appears on my network while I am using build 1119.

Here are some words from player who get this :

A: " I was walking and then I was suddenly in the void and then disconnected from the server, then I cannot join server for 2 days and it always says (You are already connected)  "

B: "I was using sword combating with other players, suddenly the world become still and all creatures stop moving, then disconnect "

Please let me know if you guys need any information related to this issue, find command indicates the player is still online but actually he is not connected to the server.

Cheers.

**Comment by i9hdkill** [comment]
Still an issue?
