### ISSUE TITLE
A Fatal Error has been detected by the JRE

### ISSUE THREAD

**Issue by SolarShrieking** [SpigotMC/BungeeCord#1771]
http://paste.md-5.net/gunifevoju.apache

Has been happening every few days over the past couple of months. Would be nice to know what is causing this / how to prevent it.

I have multiple of these logs, if you need more just say the word. They're nearly identical to this one, however.

**Comment by Black-Hole** [comment]
Maybe related to OutOfMemoryError while GC: http://paste.md-5.net/gunifevoju.apache#L301

So, please try with more heap space.

**Comment by SolarShrieking** [comment]
I already have a gig dedicated to the bungeecord, we don't even get 250 daily players.

**Comment by LucaDev** [comment]
maybe a memory leak in a bungeecord plugin? or in bungee itself?

**Comment by Janmm14** [comment]
To get information about what is going on, I suggest to look for some tools to get a memory snapshot.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
