### ISSUE TITLE
[1.9] BungeeCord - Spigot Gamemode 3 not working

### ISSUE THREAD

**Issue by sebastianbinder** [SpigotMC/BungeeCord#1772]
Seems like there is an issue with BungeeCord and Spigot 1.9 in Gamemode 3:
https://hub.spigotmc.org/jira/browse/SPIGOT-1629

Running BungeeCord build 1125 as well as latest Spigot (built it a couple of minutes ago).

**Comment by axcode** [comment]
Same problem for me  (build 1125).
With bungeecord can't pass trought block and without i can.

**Comment by md-5** [comment]
Sorry didn't see this ticket:
https://github.com/SpigotMC/BungeeCord/commit/46e7f2dfc9821ce65b6d81c4b2c5c9f89e2ab5ae

**Comment by md-5** [comment]
Related: https://hub.spigotmc.org/jira/browse/SPIGOT-1629
