### ISSUE TITLE
BungeeCord out of memory

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1777]
Hi, I'm getting out of memory error on my BungeeCord. My startup line for now:
java -Xmx16G -server -Xincgc -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=4 -XX:+AggressiveOpts -jar BungeeCord.jar

Plugins:
BungeePremiumAuthenticator
BungeeMOTD
BungeeMSG

**Comment by Janmm14** [comment]
Insufficient information. Please give us max player count and a memory dump of the java process when memory is quite a bit filled. How long was your server running?

(Also your startup flags are not good. First you say it should use ConcMarkSweepGC and then you say the same about ParNewGC.)

**Comment by CzlowiekKuktas** [comment]
Maybe 250 players online, how to make a memory dump? It was running for maybe 16 hours.

What about my startup line?

**Comment by Janmm14** [comment]
You enable two different GC engines while only one can be active at one time. Also for such laege heaps the new GC engine G1 might be the way to go.

I've heard of jmap being a tool for memory snapshots, you might want to search further on this topic.

**Comment by CzlowiekKuktas** [comment]
So how should I change the startup line?

**Comment by Master-chan** [comment]
You really don't need 16G for 250 players.
Try changing your startup line to
"java -Xmx1G -server -jar BungeeCord.jar"

**Comment by CzlowiekKuktas** [comment]
It is still happening.

**Comment by Master-chan** [comment]
How much time passes from startup before error?

**Comment by CzlowiekKuktas** [comment]
Maybe 10 hours.

**Comment by Master-chan** [comment]
Probably this is one of your plugins issue.

**Comment by CzlowiekKuktas** [comment]
How to check it and what could do this error?

**Comment by Master-chan** [comment]
Open config.yml and find online_mode option.

**Comment by CzlowiekKuktas** [comment]
And what?

**Comment by Master-chan** [comment]
And post it here.

**Comment by CzlowiekKuktas** [comment]
It's false, I am checking if they are premium in the plugin.

**Comment by games647** [comment]
Maybe one of your plugins is causing a memory leak. You could try VisualVM or Java Mission Control to analyze your heap memory.

**Comment by Master-chan** [comment]
It's my personal opinion but you should avoid running bungeecord with online_mode false.
Contact developer of BungeePremiumAuthenticator plugin - its probably causing a memory leak.

**Comment by CzlowiekKuktas** [comment]
@games647 How to use VisualVM or Java Mission Control?

**Comment by games647** [comment]
@CzlowiekKuktas 

1. Create a Heap dump - 
[Create dump of a running application](https://stackoverflow.com/questions/407612/how-to-get-a-thread-and-heap-dump-of-a-java-process-on-windows-thats-not-runnin)
Dump when the server crashes with [OutOfMemory](https://stackoverflow.com/questions/10944082/can-sun-jdk-generate-core-heap-dump-files-when-jvm-crashes)
2. Open VisualVm on your local computer 
    You can download it from [here ](http://visualvm.java.net/download.html) or it's in your jdk folder
3. Click on File -> Load -> Select the heap dump

**Comment by CzlowiekKuktas** [comment]
How to "dump when the server crashes"? I have to add these options to the startup line?

**Comment by games647** [comment]
yes

**Comment by CzlowiekKuktas** [comment]
I will do it next time when the server crash. Size of dump file is around 1GB, how to fix this?

**Comment by Janmm14** [comment]
Size of dump file is that big normally. You can however compress it well to my knowledge (zip or similar)

**Comment by CzlowiekKuktas** [comment]
I had "Too many open files" error before. I think I have these dumps, what now?

**Comment by CzlowiekKuktas** [comment]
@games647 ?

**Comment by games647** [comment]
@CzlowiekKuktas Continue at step 2

**Comment by CzlowiekKuktas** [comment]
There were char[] and byte[] in the first and second line.

**Comment by games647** [comment]
A bit more would be useful. Maybe post a pic of the classes tab.

**Comment by CzlowiekKuktas** [comment]
@games647 https://scr.hu/wW4qJj

**Comment by games647** [comment]
It's looks normal for me at this state. The server is not consuming much memory at the time of the dump right?

**Comment by CzlowiekKuktas** [comment]
I was doing it when the server was throwing errors.

**Comment by CzlowiekKuktas** [comment]
@games647 How about it? https://scr.hu/Yy9M6J

**Comment by CzlowiekKuktas** [comment]
? @games647 @Janmm14

**Comment by Cryptite** [comment]
@Janmm14 @md-5 @Thinkofname 

I am getting these as well and this is after increasing my XMX from what used to be 256M (when in 1.8) to 1G with less average users, in fact (less than 20)

Running Xms:512M and Xmx1G and no other flags other than ones required to attach a profiler.

**The following are two separate Memory Snapshots taken with YourKit: https://www.dropbox.com/s/3lcxkhhfvd7qgb5/Snapshots.zip?dl=0**

**Comment by Janmm14** [comment]
@Cryptite may I ask first if you are using a bungee build >= 1137?

@CzlowiekKuktas Your leak is possibly fixed by 1137.

**Comment by Cryptite** [comment]
@Janmm14 this is bungeecord 1142.

I got a heapdump on a crash finally, here it is: https://www.dropbox.com/s/in3ae02y9fx0qxi/heapdump.zip?dl=0

**Comment by BlackBeltPanda** [comment]
I'm also having this issue lately, this is the info I've gathered on my end so far:
https://www.spigotmc.org/threads/outofmemoryerror-direct-buffer-memory.138663/

**Comment by CzlowiekKuktas** [comment]
Calm your tita, there was a memory leak. :)

**Comment by CzlowiekKuktas** [comment]
Tits*
