### ISSUE TITLE
Json error

### ISSUE THREAD

**Issue by TheWinuXs** [SpigotMC/BungeeCord#1779]
Hi, I have an error Json with BungeeCord 1.9 look that http://prntscr.com/ab88lo  . Have you changed a Json syntax with BC 1.9 ? Thanks ;)

**Comment by Thinkofname** [comment]
Update bungeecord

**Comment by TheWinuXs** [comment]
I have the latest version guy !

**Comment by Janmm14** [comment]
@Thinkofname he said he uses latest version
@TheWinuXs please post the output of the /bungee command
