### ISSUE TITLE
TabCompleteEvent

### ISSUE THREAD

**Issue by us09alex** [SpigotMC/BungeeCord#1783]
Hey,

I found this line
[https://github.com/SpigotMC/BungeeCord/blob/848cad2a5962e0db363d8993ea8c79ff3e279d53/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L131](https://github.com/SpigotMC/BungeeCord/blob/848cad2a5962e0db363d8993ea8c79ff3e279d53/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L131)
in the tabcomplete part of the UpstreamBridge. Is ist possible to remove it, because every time a player use the tabcomplete he see a no permission message.

Best Regards
Alex

**Comment by Mystiflow** [comment]
The method checks for this so has no effect.

https://github.com/SpigotMC/BungeeCord/blob/ba448b5670946d4a744009320cdc9b758ad368cb/api/src/main/java/net/md_5/bungee/api/plugin/PluginManager.java#L150

**Comment by us09alex** [comment]
Thanks
