### ISSUE TITLE
BungeeCordPE

### ISSUE THREAD

**Issue by Ragnok123** [SpigotMC/BungeeCord#1785]
Hello. It is possible to make BungeeCord for MCPE?

**Comment by minecrafter** [comment]
MCPE works very differently from the PC version of Minecraft, which 
BungeeCord targets. You'd want to create an entirely new codebase instead.

**Comment by Janmm14** [comment]
You might want to check out these guys creating a mcpe server in java: https://github.com/GoMint

**Comment by TheDiamondYT1** [comment]
@Janmm13 Not really... You should check out the project that the team I'm in is working on - its a proxy for mcpe and PC.

https://GitHub.com/DragonetMC/DragonProxy.
