### ISSUE TITLE
Error: IndexOutOfBoundExeption

### ISSUE THREAD

**Issue by Vinetos** [SpigotMC/BungeeCord#1791]
Error: http://pastebin.com/0xUF2HMA 

All the logs (Very very big ~3k lines ): http://hastebin.com/sewarogane.avrasm

**Comment by Vinetos** [comment]
http://puu.sh/nDIN1/b3dd16992c.jpg

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
