### ISSUE TITLE
BungeeCord stops responding

### ISSUE THREAD

**Issue by XNoki200010** [SpigotMC/BungeeCord#1793]
Hey,

sometimes my BungeeCord CPU wents up to 780% (maximal 800%).
Also the memory gets full.

I think there is a way to overload the BungeeCord, but there are no errors, it just stops responding.

**Comment by Janmm14** [comment]
Insufficient information.

**Comment by XNoki200010** [comment]
D oyou see increaed network usage, or got a bot attack?
-> I don't know :/ i will look next time

Is the CPU just busy after memory is (nearly) full? ^
yes

How many players do you host? Which CPU? How much memory?
per Proxy ~120 players

**Comment by Janmm14** [comment]
If the cpu is only high if memory is nearly full, the memory garbage collection usually takes the cpu power to free up memory. Youeither have a memory leak in a plugin or not enough memory for 120 players assigned.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
