### ISSUE TITLE
BungeeCord under DDoS attack

### ISSUE THREAD

**Issue by CzlowiekKuktas** [SpigotMC/BungeeCord#1795]
Why BungeeCord is ruining the server's motd while being attacked? It mess the whole motd and doesn't show the number online player.

**Comment by Janmm14** [comment]
Well you say there is a dDoS hitting your bungee. What do you see exactly?

**Comment by CzlowiekKuktas** [comment]
I see what I said + where should be number of players it shows BungeeCord version.

**Comment by Janmm14** [comment]
You did not said what you see instead of the player count.

**Comment by CzlowiekKuktas** [comment]
For example it ignore motd plugins and doesn't show 2nd line.

**Comment by Black-Hole** [comment]
I sounds more like a filter problem. Like the DDoS protection from your hoster is filtering server list pings. For instance OVH does this.
