### ISSUE TITLE
Add option to disable "InitialHandler has connected" in log file

### ISSUE THREAD

**Issue by sebastianbinder** [SpigotMC/BungeeCord#1797]
Would it be possible to add a config option for disabling the spammy "InitialHandler has connected" in log file?

**Comment by xxyy** [comment]
#1459 #1484 #1394 
Anyways, there are [p](https://github.com/xxyy/quietcord)lugins out there that remove it.

**Comment by Janmm14** [comment]
Alterantively you could use FlexPipe which allows disabling the InitialHandler connected messages for pings, as the plugin also removes the initialhandler messages for joins.

**Comment by xxyy** [comment]
@Janmm14 Actually, it doesn't by default. You can still configure it to do so though. This isn't the place for discussion about plugins anyways.

**Comment by md-5** [comment]
ba0739798a0b6f184eca4def52750e8633623487
