### ISSUE TITLE
Online mode error.....

### ISSUE THREAD

**Issue by PvpMiky** [SpigotMC/BungeeCord#1798]
Hey,

Well i have a premium minecraft account

my bungeecord online-mode is true
and my bukkit online-mode is true to

This means for premium players / cracked

i want premium i have both set to true

but when i try to join i get an error:
Exception Connection:RunTimeException : Server is in online mode! @net.md_5.bungeeserverconnector:256 

when i set it to false it works properly

but i want a premium minecraft server not cracked

can anyone tell me how to fix ?

**Comment by PvpMiky** [comment]
when i set the bukkit hub server to false 
and bungeecord to true it works

is this okay?

SORRY FOR THIS NOOB QUESTION FIRST TIME I'AM RUNNING BUNGEE I ALWAYS HAD BUKKIT.,.

**Comment by CodeCrafter47** [comment]
That is okay.

You should enable ip_forwarding to avoid issues. https://www.spigotmc.org/wiki/bungeecord-installation/#post-installation

**Comment by PvpMiky** [comment]
Ohw thanks alot, 1 more question

Is my server now premium ? 
with bungee online-mode: true 
And bukkit online-mode: false 

Sorry for this noob question again, i understand evrything except this XDDD

**Comment by kamcio96** [comment]
All servers have to have online-mode=false
