### ISSUE TITLE
Merge patches from FlexPipe repo

### ISSUE THREAD

**Issue by new-sashok724** [SpigotMC/BungeeCord#1799]
I think it would be great idea to merge some patches from https://github.com/minotopiame/FlexPipe

**Comment by kamcio96** [comment]
Most of them are waiting in PR

**Comment by Janmm14** [comment]
Yeah. While at it, one can also look at the patches of https://github.com/WaterfallMC/Waterfall

The problem is that no issues occurr with these PRs and also nothing is written to them by the authors.

**Comment by md-5** [comment]
Patches need to be PRd individually.
