### ISSUE TITLE
Servers Change to "Online" Mode After Random Amount of Time

### ISSUE THREAD

**Issue by vintagedon** [SpigotMC/BungeeCord#1801]
So I am trying to track down an issue with BungeeCord eventually timing out on my lobbies and not letting people login, and even stripping everything down to bare metal of just spigot/BC, it's still happening.

 Am running the latest build of Spigot (today's build) and the latest build of BungeeCord (build 1135) with the latest build of BungeeRedis. If I remove BungeeRedis and go down to a single lobby, I still have the problem. If I remove ALL my BungeeCord plugins and ALL my Spigot plugins, I still have the problem.

There are several physical boxes, all on the same switch, and each box has a lobby and a BC instance. They are behind a hardware firewall (with the switch behind the firewall so that the switch is handing all server-to-server traffic), only allow untrust access to the BC ports (all 25565) all on the same zone, so nothing can reach the individual instances of Spigot. None of the servers have UFW or iptables running, since the hardware firewall is handling that (and I've verified it numerous times).

Everything starts out fine, but anywhere from 30 minutes to 3-4 hours later, I'll start getting these:

```
08:11:38 [SEVERE] [PLAYER_NAME] <-> ServerConnector [Lobby1] - encountered exception
java.lang.RuntimeException: Server is online mode!
08:28:06 [INFO] [/XX.XX.XX.XX:45671] <-> InitialHandler has connected
08:28:10 [WARNING] [Ping Handler] -> Lobby1 - read timed out
```

Note that the first line is from the server that BC and Lobby1 reside on together.  The 2nd and 3rd lines happen on the rest of the BC servers.  The 2nd and 3rd line do not begin until AFTER the first line has happened.

Now, before someone begins about checking your config for online mode, refer back to the statement that everything works fine for 30 minutes to 3-4 hours. They *are* in offline mode, and then it appears BungeeCord hits an error at some point, decides that the server is now in online mode, and then everything just collapses like dominos.

Of course, the ports vary each time, but the IP is always the IP of the BungeeCord instance.

Unfortunately, I don't have much in the way of logs to submit, other than that.  I have some network graphs, but they don't show anything important.  No network errors, bad packets, transmit or receive errors, or anything like that.  I've been monitoring the network closely and there's none of that.

As Always,
Don

**Comment by Janmm14** [comment]
Are your spigot servers still in offline-mode?
The exception is only thrown if the bungee gets an EncryptionRequest by a server (indicating the server is online mode).

**Comment by vintagedon** [comment]
As far as I can tell.  If I try to connect to them directly (I'm whitelisted through the firewall), they tell me to enable IP forwarding ... which indicates they're still listening for BungeeCord ... I have IP forwarding set to true in the config).

There's no other errors in the Console on the BungeeCord server or the Spigot server (like it saying it's changed to online mode), and during this time, I don't restart the Spigot servers or the BungeeCord servers.

Is there any specific way to see if they've flipped to online mode from offline?  Is this an issue where they suddenly switch?

As Always,
Don

**Comment by Janmm14** [comment]
Normally servers never switch on online-mode anywhere.

**Comment by vintagedon** [comment]
That's what I assumed, and why I'm trying to figure out why suddenly BungeeCord thinks they're suddenly in online mode.

You stated "The exception is only thrown if the bungee gets an EncryptionRequest by a server (indicating the server is online mode)."  Is there any situation that you know of that could simulate this?  I'm just groping here, but I really don't have anything to go off of to try to troubleshoot it.  It looks like, unfortunately, that I'm going to have to roll back to 1.8.8 because of this, and am trying to avoid all that work.

Do you have any troubleshooting that I could possibly do beyond the logs?

As Always,
Don

**Comment by Janmm14** [comment]
If you restart your bungee only, does it work again? Or do you have to restart your spigot server to make it work again?

**Comment by vintagedon** [comment]
Good question; I hadn't thought of that in my frustration.  This morning, I was forced to restart the Spigot instance on the lobby to get logged in.

When doing so, what I see is:

=====
11:26:47 [INFO] [CrainBramp] <-> InitialHandler has connected
=====

At that point, Minecraft hangs at "Downloading Terrain", and everything just sits there until it times out.  So BC doesn't immediately reject me as no fallback servers being online.

However, if I do get logged in, if I bounce around from server to server, as I leave a particular server, I can't return to it.  THEN it tells me the server is offline.  So if I move to all 16 lobbies and then disconnect, NOW I can't reconnect at all, and get the standard "no server / fallback server available"

As a side note, I spent most of last night (a number of hours) trying every Spigot 1.9 build that I could dig up (I keep all my Spigot builds from BuildTools) and it always happened.  And for testing purposes, I always use no plugins on BC or Spigot so there's no extraneous issues to deal with.

**Comment by Janmm14** [comment]
So a bungee restart fixes the issues?

Which bungeecord version do you have? Do you know an older version without this issue?

**Comment by vintagedon** [comment]
Looks like you misunderstood me ... I said that a Spigot restart fixed it this morning.  To be honest, I can't remember if it was the same prior to this.  Currently, if you'll look back at the first post, I'm running the most current BC (1135) and a fresh build of Spigot as of yesterday.  But the problem started after I switched to 1.9, and has persisted through all of the various builds of Spigot I've done.

I've tried several of the BC versions; at least the last couple, and then rolled back last night to the first version where you guys supported 1.9.

**Comment by Janmm14** [comment]
So this looks like a spigot issue.

What about the connection throttle in bukkit.yml? Is it set to -1? Try out without ip-forwarding, then you can also try out the direct join (try cracked and premium direct join). Can you try using craftbukkit? Does it fix the issue?

Are you doing this on localhost or not?

**Comment by vintagedon** [comment]
Will try all the suggestions.  Have to do some errands, but I'll reply back this evening.

Also, am not doing this localhost because I've got 16 servers, each with a bungeecord instance, and they need to be able to see the lobbies from server to server.  So everything's on the same IP, but different ports.  There's a hardware firewall blocking untrust-->trust for those ports (only 25565 is allowed, which are the BC servers), but server-to-server communications are handled directly by the switch.  I've run traces on the firewall, and it's not picking up any server-to-server communication, so it can't be interfering since it never sees those packets.  As an additional note, ip tables/ufw is not running on any of the servers, and I've verified that.

Don

**Comment by i9hdkill** [comment]
Can you verify that these lobbies are not crashing and restarting in online-mode: true after you quit? add  -o false to your startup script.
Are you sure that you didn't use any bungge/spigot plugins?
I don't think that this is a issue in spigot, but an odd configuration mistake. Can you post your spigot startup script, server.properties and your bungeecord config?

**Comment by vintagedon** [comment]
My apologies for not getting back to you.  My son caught strep and passed it to me, and I've been trashed since I posted this, and am still pretty rough.

So I've reviewed the Spigot logs, and the servers aren't crashing and restarting at all, so that knocks out the possibility of them restarting in online mode.

As for plugins, of course, I was using some, but to make sure the problem was still manifesting, I shut everything down, renamed plugins to plugins-old on both Bungee and Spigot and restarted.  Although it looked like it had fixed it, when I left it overnight, I came back and couldn't login, same error.  Double checked, and the lobby had NOT restarted.  Just the familiar error from Bungee saying Lobby1 had disconnected.  When I traced that time stamp back to the Lobby, nothing was going on at that time ... no errors, no anything.  As far as I could tell, the lobby was just sitting there.

There's no startup script, per se.  Am using PufferPanel (not using Docker containers, btw), so it starts the jar itself with:

```
su -s /bin/bash -l pp-lobby1_tu3ud -c cd ./public && java -Xms1024M -Xmx1024M -server -jar server.jar
su -s /bin/bash -l pp-bungee_q2h9b -c cd ./public && java -Xms1024M -Xmx1024M -server -jar BungeeCord.jar
```

If you're wondering about hardware, it's 16 x 1u E3-1270v3s, each with 32GB of RAM, 2 x 960GB SSDs in RAID1, running vmWare ESXi6.0 Enterprise Plus w/4 x GB NICs each in a vmWare Distributed switch.  All behind a Juniper EX4200-48T which is behind a Juniper SRX550 firewall with 2x10GB uplinks so that the switch, not the firewall, is handling all inter-server traffic.  I've made sure the distributed switches have no traffic rules, and monitoring everything via SFlow, there are no error packets, packets per second are low, etc.  Plus, it's happening on the same server, not just across the switch.

My configs are attached; I believe I have sanitized  them.

[vintagedon-configs.zip](https://github.com/SpigotMC/BungeeCord/files/181648/vintagedon-configs.zip)

As Always
Vint

**Comment by i9hdkill** [comment]
This does not solve the problem, but
`default_server: Lobby1
    fallback_server: Lobby1`
are not needed anymore, so you can remove the default and fallback server config value.
connection throttle in your bukkit.yml should be set to -1
The rest looks good so far. You network hardware should not matter, as the error is between your bungeecord and spigot server.
When I got it right, there is running 1 bungee and 1 spigot on the same ip/machine.
