### ISSUE TITLE
BungeeCord server not completly starting up! 

### ISSUE THREAD

**Issue by MrSwagSausage** [SpigotMC/BungeeCord#1802]
Everytime I start up the BungeeCord server it says it's starting up but it's still offline. It's not like loading up... I can't join the server too.
My CONSOLE when I am trying to startup the server:
http://pastebin.com/XrptbX9v
My config.yml file:
http://pastebin.com/TWs7xiQF

If anyone has a idea of what the problem would be please post it in the comments.
*NOTE* If I try using Spigot on the same server everything works so it's not a hosting problem.

**Comment by minecrafter** [comment]
Looks like you're using Multicrap on a shared host, that's already a no-no.

The issue is in your configuration. (Try putting it into https://yaml-online-parser.appspot.com/)

**Comment by MrSwagSausage** [comment]
What do I need to do on https://yaml-online-parser.appspot.com/? It's not so self explanatory...

> Looks like you're using Multicrap on a shared host, that's already a no-no.

The issue is in your configuration. (Try putting it into https://yaml-online-parser.appspot.com/)

**Comment by Janmm14** [comment]
Please use proxy.log.* files for actual output.

Bungee has problems to unpack the native libraries, you can try running with -Dnet.md_5.bungee.native.disable=true parameter (before -jar argument)

**Comment by MrSwagSausage** [comment]
where do I put the proxy.log.*? Were do I right in  Dnet.md_5.bungee.native.disable=true parameter?

> Please use proxy.log.* files for actual output.

Bungee has problems to unpack the native libraries, you can try running with -Dnet.md_5.bungee.native.disable=true parameter (before -jar argument)

**Comment by Janmm14** [comment]
proxy.log.* files are in the folder of your bungeecord jar.

-Dnet.md_5.bungee.native.disable=true is a startup parameter. I do not know Multicraft, you need to fnd the settings yourself.

**Comment by MrSwagSausage** [comment]
> proxy.log.* files are in the folder of your bungeecord jar.
> Dnet.md_5.bungee.native.disable=true is a startup parameter. I do not know Multicraft, you need to 
> fnd the settings yourself.
I can only find proxy:log.0 and proxy:log.o.lck
And  -Dnet.md_5.bungee.native.disable=true needs to be enabled cause its disabled by default in MultiCraft and idk how to enable it so...
