### ISSUE TITLE
Server-icon & BungeeCord !

### ISSUE THREAD

**Issue by DjTrolleur** [SpigotMC/BungeeCord#1805]
Hey,
Excuse me for my bad english (i speak french).
I have a little problem with my bungeecord server. When i put the server-icon.png in a simple spigot or bukkit server, the icon work. But, when i put it on BungeeCord folder, the logo does not working... Can you help me please ? :(

Thanks!

**Comment by md-5** [comment]
Maybe start by sharing the problematic logo?

**Comment by DjTrolleur** [comment]
This is the logo : 
`<a href='http://postimage.org/' target='_blank'><img src='http://s24.postimg.org/xo8wwi1kx/server_icon.png' border='0' alt="server icon" /></a>`

**Comment by md-5** [comment]
Works fine.
![d7qxxjf](https://cloud.githubusercontent.com/assets/1007849/14041005/265a8ba8-f2c1-11e5-997f-3e25374aaba6.png)

**Comment by Janmm14** [comment]
Best is you place the logo in the folder while BungeeCord is off.
