### ISSUE TITLE
Bungee java freezes and goes 100% CPU

### ISSUE THREAD

**Issue by zenandreas** [SpigotMC/BungeeCord#1806]
Hello,

I've been experiencing a real annoying issue for the past weeks and haven't figured it why. By bungee server freezes and i have to kill it manually because it overloads my CPU. This happens even if there aren't any players online so its not a capacity issue. Also, the machine we are hosting on is more than capable of handling 1000 players. Using the latest version of bungeecord.

If i may ask, could it possibly be related to buildtools or anything like that? I'm preety sure it shouldnt be related with the spigot version we are running because the spigot servers are acting just fine and they don't even crash. After killing the bungee task and restart it all works just fine.

Please do tell me what other information you need from us. Thank you

These are the installed plugins: http://prntscr.com/ajyjq3

**Comment by kamcio96** [comment]
Use VisualVM ;)

**Comment by Janmm14** [comment]
If there are no players online and there is no unusual activity in the logs you can be pretty sure one of your plugins has some issues.

**Comment by Tomographix** [comment]
I've had issues with this as of last week. I allocated 5GB of RAM to the Bungee and it seemed to go away.

**Comment by zenandreas** [comment]
Yes, i've allocated more RAM and it all seems fine, for the moment
