### ISSUE TITLE
OutOfMemoryError crashing BungeeCord

### ISSUE THREAD

**Issue by Cryptite** [SpigotMC/BungeeCord#1807]
In 1.8 I was able to run BungeeCord with 256M and never run into this problem. Now I'm running with 512M and no bigger playerbase (talking under 30 players) and an getting this 2-3 times a day.

http://pastebin.com/7zFSTK7b

**Comment by Janmm14** [comment]
You need to provide a memory snapshot. Use YourKit, JVisualVM, maybe java flags like heapdumponoutofmemoryerror or jmap (command line). Please use google for getting a memory snapshot of java on your platform. Is the increase in memory slowly constantly or suddenly and rapid? Does it start immediately or after a (random) delay after starting?

**Comment by md-5** [comment]
Likely above
