### ISSUE TITLE
MOTD in server ping broke after commit 7926230

### ISSUE THREAD

**Issue by Spirit55555** [SpigotMC/BungeeCord#1810]
79262306820cc874d1830210b71729884efaa918 broke the MOTD in the server ping:

Before that commit, BungeeCord would send the MOTD in the following format:
`§fHello §4World`

If I remember correctly, this is also the format that Spigot/Craftbukkit uses.

Vanilla Minecraft sends it in this format:
`{"text":"§fHello §4World"}`

After the commit, BungeeCord sends it in this format:
`{"text":"Hello ","color":"white"},{"text":"World","color":"dark_red"}`

This breaks all sort of status tools and pages. BungeeCord should not send a full text component.

**Comment by md-5** [comment]
I disagree though, it's Mojangs position that section signs are not supported. "Vanilla" only sends it like that because it has no real way to configure colours.

**Comment by Spirit55555** [comment]
Section signs might not be supported, but they still work.

The purpose of the commit was to fix #1765. If BungeeCord was changed to send it like vanilla, the bug would still be fixed, right?

**Comment by Thinkofname** [comment]
Honestly those sites need to update because the old style is being phase out everywhere now

**Comment by Janmm14** [comment]
https://github.com/minotopiame/FlexPipe/blob/master/patches/0027-Restore-1.8-like-ping-motd-description-output-for-co.patch
