### ISSUE TITLE
Bungeecord error with build #1138

### ISSUE THREAD

**Issue by Sckaletz** [SpigotMC/BungeeCord#1811]
Players are getting kicked randomly with this error in the Bungeecord:

http://pastebin.com/q153wuvF

Spigot version: git-Spigot-e4d4710-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

**Comment by Janmm14** [comment]
@Sckaletz Issue still exists with newest bungee?

**Comment by Sckaletz** [comment]
Yes it's still the same problem with Bungeecord #1142

**Comment by wow4201** [comment]
Hmm happens quite a bit, like 180 times in 5 hours with a few hundred players going through.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
