### ISSUE TITLE
Exception Netty Handler

### ISSUE THREAD

**Issue by zenandreas** [SpigotMC/BungeeCord#1812]
Hi there,

This is a new error, not sure what is caused by, i don't understand the error. http://prntscr.com/alw8o5

This happens when i type /aac ( advanced anti cheat ) on one of the connected spigot severs ( i also get disconnected )

**Comment by Sckaletz** [comment]
This is the same error I'm experiencing but with me it has nothing to do with AAC.

https://github.com/SpigotMC/BungeeCord/issues/1811

**Comment by zenandreas** [comment]
I have checked and i didn't even had AAC enabled. Makes it even weirder. Also getting strange Broken pipe disconnects

**Comment by i9hdkill** [comment]
This might be an outdated Bungeeplugin. Did you check all of them for updates?
