### ISSUE TITLE
Substantial Delay on Server Login

### ISSUE THREAD

**Issue by Tomographix** [SpigotMC/BungeeCord#1813]
Hi,
For the past week or so now players have had issues logging into servers.
When you login the client gets suck on 'Loading Terrain' for 30+ seconds.
The servers that players are logging into are performing with with average 20 TPS.
Without Bungee, the logging in is instant.
Substantially older versions of bungee from the 8/3 work fine as well.
Thanks

**Comment by i9hdkill** [comment]
How many servers did you add to your prioritylist?

**Comment by Tomographix** [comment]
2 servers are currently in the priorities.

priorities:
- hub
- skyblock

**Comment by Janmm14** [comment]
Is the hub up while this error appears?

**Comment by Tomographix** [comment]
yes it is :)

**Comment by i9hdkill** [comment]
On what versions are your spigot priority list servers running, which Bungeeplugins are installed and what kickmessages are defined? Are these spigot and BungeeCord servers on the same machine?
Does this even happen when you just use one hub server, for example just "hub"?

**Comment by Tomographix** [comment]
All servers are running 1.9.2.
ServerListPlus is the only bungee plugin installed.
Yes they are on the same box.
Not as much logging into the hub, but still slow. The hub does not keep any players online. It just automatically forces players to choose a server.

**Comment by i9hdkill** [comment]
1.9.2 with protocolsupport installed or just plain spigot 1.9.2?
Can you give me an ip adress/domain to test?

**Comment by Tomographix** [comment]
Just plain spigot installed. Nothing fancy. mc.fruitservers.net

**Comment by i9hdkill** [comment]
Might be just a slow connection between your server and the mojang authentification servers. I am from germany and it took 5 seconds to actually connect to your hub. This is pretty good. Your 30 seconds doanloading terain was maybe just bad luck or you had a bad connection to your server at that moment.

**Comment by Tomographix** [comment]
Try joining the survival server if you have a sec please.

**Comment by i9hdkill** [comment]
Does not work at all for me.(Took 3 minutes) Can you post your bungeecord config.yml, your bukkit.yml, spigot.yml and server.properties? And probabvl the bungee/spigot log when a player or me is trying to join?
