### ISSUE TITLE
DecoderException on player login attempt (1.9.2)

### ISSUE THREAD

**Issue by kidsfarmCoding** [SpigotMC/BungeeCord#1814]
Using build: git:BungeeCord-Bootstrap:1.9-SNAPSHOT:7179dd4:1141
On attempting to join with Vanilla Minecraft 1.9.2, I get this error:

![image](https://cloud.githubusercontent.com/assets/17813411/14180129/a251b672-f759-11e5-92ae-cd8a62aed17f.png)

I've tried removing all modules, and I have no plugins installed.

**Comment by SamboyCoding** [comment]
Oh dear... I posted this with the incorrect account. This is the account i meant to post with.

**Comment by Thinkofname** [comment]
Assuming an unmodified vanilla server that shouldn't be possible. It is normal vanilla right?

**Comment by SamboyCoding** [comment]
Yes

**Comment by SamboyCoding** [comment]
Just updated spigot

**Comment by SamboyCoding** [comment]
Oh wait... does spigot count as vanilla?

**Comment by SamboyCoding** [comment]
I just tested... and none of the other servers in my list (that I know use Bungee) such as Mineplex work fine.

**Comment by Thinkofname** [comment]
Not but its fine anyway. Going to try something

**Comment by SamboyCoding** [comment]
Ok.

**Comment by SamboyCoding** [comment]
Client-side, in the logs, I just get a "connecting to [IP], 25565" message, and then nothing. It kicks me with the text: "Disconnected"

**Comment by SamboyCoding** [comment]
Shall i test that?

**Comment by SamboyCoding** [comment]
Ok it's fixed. Thanks!
