### ISSUE TITLE
Help Me.

### ISSUE THREAD

**Issue by mikael11d** [SpigotMC/BungeeCord#1816]
I don't know what im doing wrong..

Problem: http://pastebin.com/avnZRJfT
Config: http://pastebin.com/KNaDgkBN

~Mikael11d

**Comment by Zartec** [comment]
This should be a charset problem.

Try to remove the wired `ø` character from servers name or try to save the config file UTF-8 encoded.

The char is in `FactionsGrønn` and `FactionsRød`.

**Comment by mikael11d** [comment]
Thank you for your help! You're a real life saver! Have a nice day!

**Comment by Janmm14** [comment]
@mikael11d Please close this issue then.
