### ISSUE TITLE
Memory Eater

### ISSUE THREAD

**Issue by Johandrex** [SpigotMC/BungeeCord#1818]
So Bungeecord is supposed to need like 50 MB per 100 players or something. But when there's 200-300 players on my network bungeecord is using 4-6 GB Ram. Then it crashes on 300-400 players. Down below you can find screenshots of bungeecords memory, where I've spammed the /memory command. Also, note that my bungeecord server restarts every day.
Bungeecord version: git:BungeeCord-Boostrap:1.9-SNAPSHOT:b6b015f:1142

Plugins: https://fnpaste.com/Gzoy
https://gyazo.com/4e20a0fd9c0870346d834800e8577e3a
https://gyazo.com/a1e57122ae316bad113e30b3b1214489

**Comment by kamcio96** [comment]
99.99999999999999999999999999999999999% chance it is plugin bug

**Comment by ScruffyRules** [comment]
Kamcio would be right, Also it's about 512MB per 500 players (Plugins not counted in)

**Comment by Johandrex** [comment]
Alright, how do I find out which plugin that's causing the lag?

**Comment by ScruffyRules** [comment]
Trial and error.

**Comment by Johandrex** [comment]
Could you guys check why I'm unable to use the samplet? https://www.youtube.com/watch?v=w4jqH4x1Rzg

**Comment by Zartec** [comment]
You must start te server with the jmx service.

It should be described here:
http://docs.oracle.com/javase/7/docs/technotes/guides/management/agent.html

**Comment by Cryptite** [comment]
I will again point to snapshots I have taken that might help pinpoint the (I think Netty) problem: https://github.com/SpigotMC/BungeeCord/issues/1777#issuecomment-204739693

Followed by the actual OOM heap dump I get on crash: https://www.dropbox.com/s/in3ae02y9fx0qxi/heapdump.zip?dl=0

Note I have **no** plugins.

**Comment by Johandrex** [comment]
I am starting the jmx service though with this script
screen -d -m -S SG java -server -Xmx8G -Xms1G -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:MaxGCPauseMillis=30 -XX:+UseBiasedLocking -XX:+OptimizeStringConcat -XX:+UseFastAccessorMethods -XX:+AggressiveOpts -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=8766 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.ssl=false -jar spigot.jar

**Comment by Johandrex** [comment]
The issue were that I logged in as monitorRole instead of controlRole when connecting remotely. Facepalm. Will try to find out what plugin that's causing Bungeecord to eat so much memory now.

**Comment by Johandrex** [comment]
Managed to fix the issues. Could anyone take a look at the thread dump to see what's causing the lag spikes on Bungeecord? : https://fnpaste.com/zrvV

**Comment by Johandrex** [comment]
Could anyone take a look at the pictures/logs & see what's causing the memory leak? I also have a heapdump on 2 GB if required.

Thread Dump: https://fnpaste.com/zrvV
https://i.gyazo.com/720b4183024df45174a31be97185d4b4.png
https://i.gyazo.com/fa75b50d376e92d3308314ac56a8e4c8.png
https://i.gyazo.com/133964bd16a27003c203b7c4abeb1be7.png
https://i.gyazo.com/a19a5a0a0c3103ca588d321b046d56da.png
https://i.gyazo.com/c662ab2f62c94741a6f744375721486b.png

**Comment by md-5** [comment]
You have allocated 8gb of ram, so Bungee will attempt to use all 8gb of ram.
You haven't provided any information about your supposed crashes. In any case the recommendation is 0.5mb per player (minimum of 512mb), and you should follow that.

Threads dumps are useless for looking at memory issues.

**Comment by Johandrex** [comment]
Removed the max & minimum usage but it's still using a 2-3 GB at startup. How am I supposed to find the memory issues?

**Comment by md-5** [comment]
You're meant to set -Xmx to 512M and then follow the instructions I provided

**Comment by Cryptite** [comment]
@md-5 What about the crash heap dump and memory profile snapshots that I provided?

**Comment by Johandrex** [comment]
Unable to set it to set it to "-Xmx512M" as the proxy stops at once.
Here's a compressed heap dump: https://www.dropbox.com/s/9jowz8wpzg6ru95/heapdump-1459869201398.rar?dl=0

**Comment by Johandrex** [comment]
@md-5

**Comment by Johandrex** [comment]
I sent the dump

**Comment by md-5** [comment]
Featherboard is leaking (not removing) teams, you also appear to have some other Bungee side plugin issue which is impossible to tell without allocation recording. Please provide a clean Bungee snapshot.

**Comment by Johandrex** [comment]
How do I provide a clean bungee snapshot?

**Comment by Janmm14** [comment]
Restart bungee and take a snapshot after ~1 hour maybe and disconnect all players while taking the snapshot.

**Comment by Cryptite** [comment]
I have no plugins and got this, but seem to be continually ignored: https://github.com/SpigotMC/BungeeCord/issues/1818#issuecomment-205275617

There's a snapshot of an OOM with a no-plugins bungeecord.
