### ISSUE TITLE
Cant add more than 4 servers

### ISSUE THREAD

**Issue by andrewfer000** [SpigotMC/BungeeCord#1819]
I tried to add a 5th server and it would just cause errors.

**Comment by ghacproductions** [comment]
Maybe you should post these errors?

**Comment by andrewfer000** [comment]
-XX:MaxPermSize=512M -jar BungeeCord.jar -o true
19:52:34 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
19:52:34 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
19:52:34 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.9-SNAPSHOT:b6b015f:1142
19:52:35 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
19:52:35 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
19:52:35 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
19:52:35 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
19:52:35 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
19:52:35 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
19:52:35 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.9-SNAPSHOT:b6b015f:1142 by SpigotMC
19:52:35 [INFO] Loaded plugin cmd_find version git:cmd_find:1.9-SNAPSHOT:b6b015f:1142 by SpigotMC
19:52:35 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.9-SNAPSHOT:b6b015f:1142 by SpigotMC
19:52:35 [INFO] Loaded plugin EnjinMinecraftPlugin version 2.7.0-bungee by www.Enjin.com
19:52:35 [INFO] Loaded plugin cmd_server version git:cmd_server:1.9-SNAPSHOT:b6b015f:1142 by SpigotMC
19:52:35 [INFO] Loaded plugin cmd_send version git:cmd_send:1.9-SNAPSHOT:b6b015f:1142 by SpigotMC
19:52:35 [INFO] Loaded plugin cmd_list version git:cmd_list:1.9-SNAPSHOT:b6b015f:1142 by SpigotMC
19:52:35 [SEVERE] Exception in thread "main"
19:52:35 [SEVERE] java.lang.IllegalArgumentException: port out of range:255572
19:52:35 [SEVERE]     at java.net.InetSocketAddress.checkPort(Unknown Source)
19:52:35 [SEVERE]     at java.net.InetSocketAddress.<init>(Unknown Source)
19:52:35 [SEVERE]     at net.md_5.bungee.Util.getAddr(Util.java:34)
19:52:35 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:205)
19:52:35 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:92)
19:52:35 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
19:52:35 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:52:35 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Zartec** [comment]
One of your servers in the config use a port higher the maximum port.
`255572` should be `25572` or something else.

**Comment by andrewfer000** [comment]
omg!! how did I never catch that! thanks so much

**Comment by Zartec** [comment]
Np and please close the issue

**Comment by andrewfer000** [comment]
ok bye

**Comment by Janmm14** [comment]
@md-5 bad server advertisment in comment above
