### ISSUE TITLE
problems getting players gamemode on bungeecord

### ISSUE THREAD

**Issue by Fchen48** [SpigotMC/BungeeCord#1822]
Hi,
we have some problems when a player gets gamemode spectator, he will be invisible and can't fly through blocks, he also has no access to the spectator menu. After hours of troubleshooting, we found that our own tablist plugin will create this issue, the problem is that the tablist should set the correct gamemode, but it doesn't.
I will give you an example:
Player enter /gamemode 3
Server will change the players gamemode correctly to gm 3
BungeeCord tablist still gets gamemode 0 (using method: ((UserConnection) ProxiedPlayer).getGamemode())
Player gets invisible and fly, but can't passthrough blocks.

We tested it on our test environment and everything works fine, so after another 2-3 hour of troubleshooting, we found that if we set on BungeeCord config.yml ip-forward: true and on spigot.yml bungeecord: true the bungee receive the incorrect gamemode, in our case we received every time gm 0. If I change in spigot.yml to bungeecord: false, the server will receive the bungee IP instead of the players IP (which I know, because of reasons) and now it's possible to get the correct gamemode, problem with the following configuration is that we get another (wrong) UUID from the players, so it's no solution to change it to false.

**Comment by md-5** [comment]
The only currently supported tab list is the inbuilt SERVER one. There are an absolute tonne of issues with custom tab lists now that players are actually tied to within their tab list. If you want to debug this further you should probably look at line 34 of TabList - but note that your code is using non API methods so is not actually supported.
