### ISSUE TITLE
Add isOnline() to ProxiedPlayer

### ISSUE THREAD

**Issue by KingFaris10** [SpigotMC/BungeeCord#1823]
I think it would be good to add isOnline() or isConnected() to the ProxiedPlayer class. It's a lot neater and more simple than getting the player by UUID and checking if it's not null, for example:

```
final ProxiedPlayer player = event.getPlayer();
this.getProxy().getScheduler().schedule(this, () -> {
    if (getProxy().getPlayer(player.getUniqueId()) != null) {

    }
}, 1L, TimeUnit.SECONDS);
```

**Comment by Janmm14** [comment]
The ```Connection``` class has a method ```isConnected()```, as ```ProxiedPlayer extends Connection```, its available there too.
https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/connection/ProxiedPlayer.java#L17
https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/connection/Connection.java#L54-L60

**Comment by KingFaris10** [comment]
Oh, I had a few months ago build of BungeeCord, thanks for that.
