### ISSUE TITLE
getChar() method in ChatColor class

### ISSUE THREAD

**Issue by KingFaris10** [SpigotMC/BungeeCord#1824]
In the Bukkit API, ChatColor contains 'getChar' which returns the character code for that specific ChatColor. It would be useful if BungeeCord also had this.

**Comment by md-5** [comment]
Use case?

**Comment by KingFaris10** [comment]
I want to save a coloured string to config with nice looking text, e.g. Saving: ChatColor.RED + "Hi"
As &cHi

**Comment by minecrafter** [comment]
You can use ChatColor.<color>.toString().charAt(1) as a workaround

**Comment by KingFaris10** [comment]
Yeah I like the idea but in general a getChar method would still make the API more open.

**Comment by md-5** [comment]
@KingFaris10 your use case is compelling, but I'd be a bit hesitant about adding it (at least in non-deprecated form), because from our perspective it is a magic value, and all chat should be json formatted these days. Any reason you aren't using JSON chat?

**Comment by Janmm14** [comment]
@md-5 Json chat in configurations is not user-friendly as they need to use an online tool or know how json chat is built.

**Comment by md-5** [comment]
@KingFaris10 just remember, in both Bungee and Bukkit you should just be using the translate alt codes method which does this for you.

**Comment by Janmm14** [comment]
@md-5 Nah, he wants the opposite: ```§``` to ```&```

**Comment by KingFaris10** [comment]
@md-5 As stated, user friendly reasons for not using component builders, etc. and also stated by @Janmm14, I would like to go from the reverse of translateAlt.

**Comment by KingFaris10** [comment]
If this really won't be added, I will just use @minecrafter workaround.
