### ISSUE TITLE
Bungeecord 1123 - Incorrect Player Counts and 1145

### ISSUE THREAD

**Issue by mcraftpete** [SpigotMC/BungeeCord#1828]
Hi,
My ping is reading incorrectly , if I type glist in console and add up the players on each server they add up to more then the total shown ..

![ping](https://cloud.githubusercontent.com/assets/5656426/14532567/615815d4-0259-11e6-8646-24260773a46c.jpg)

This count is also shown incorrectly on server list when refreshing , is this fixed in later version ?

**Comment by mcraftpete** [comment]
Updating to another bungeecord + changing from swiftmotd fixes the issue , not sure which one causes it though.

**Comment by mcraftpete** [comment]
I take that back , I am updated to 1145 and using serverlistplus , with or without that it still reads incorrect player number total.
![playercount](https://cloud.githubusercontent.com/assets/5656426/14561325/66622bf0-030d-11e6-81d5-102ed7255d89.jpg)

**Comment by Janmm14** [comment]
Do you have some players which can't connect because it says they are already online?

Please check whether the /list of each server and the /glist command show the same amount of players.

If there are differences, please check bungee console for errors in conjunction with the players which are not shown in one or the other list command.

**Comment by mcraftpete** [comment]
Hi,
No those players are definitely online , I actually went to each server while having multiple windows and phone open checking player counts as I moved around to confirm the actual servers were correct with what glist was showing , I used tab and list , and also /msg and tabbed through players to be sure all were online too , I did this with each server confirming numbers given on the glist was correct at the time of checking so go to each server /glist and confirm it read correctly in case it was 1 server not reading well or something. It is definitely the total player count that is incorrect , I also use featherboard and its bungeecount also shows the correct figure what glist adding all servers up does.

**Comment by Janmm14** [comment]
It looks like each server has its list of who is online (which seems to be correct), but it does not count into the global list, which is maintained at another place. The total count of glist is coming from the list which seems to fail having all currently online players in it.

**Comment by mcraftpete** [comment]
Yes exactly that , the total count is incorrect , and this is the same figure shown on front page of client where all servers are listed , that figure is same as glist total beign wrong , but as said featherboard does have correct figure , i can see this as i log into server as i show total players online,  it matches the pllayers added up on all the servers , and as stated all servers have correct numbers on them so that total needs a fix i believe unless something is causing it to read wrong.

**Comment by Janmm14** [comment]
I know what you just wrote, I just wanted to point out the internal issue in bungeecord, so for example md-5 can take a look at it.

**Comment by Wazez** [comment]
any updates on this issue. also experiencing the same problem. titlemanager/featherboard display correct total player counts but bungeecord /glist does not.

**Comment by md-5** [comment]
The code is very robust and I see no issue with it, nor has this issue been reproduced in the absence of plugins.

If the code was actually at issue, then various BungeeCord functions would be obviously broken as for example getPlayer(Player) would return null for an online player.
