### ISSUE TITLE
BungeeCord Could not connect to default or fallback server, please try again later: java.net.ConnectException

### ISSUE THREAD

**Issue by StijnSimons** [SpigotMC/BungeeCord#1829]
Log:
20:19:59 [INFO] Listening on /HAD.TO.VANISH.IP:25565
20:20:14 [INFO] Netty is not using direct IO buffers.
20:20:14 [INFO] [/HAD.TO.VANISH.IP:53837] <-> InitialHandler has connected
20:20:15 [INFO] [Derp_Stijn] <-> InitialHandler has connected
20:20:18 [INFO] [Derp_Stijn] disconnected with: Could not connect to default or fallback server, please try again later: java.net.ConnectException
20:20:19 [INFO] [Derp_Stijn] -> UpstreamBridge has disconnected
20:21:25 [INFO] [/VANISHED:52707] <-> InitialHandler has connected
20:21:30 [INFO] [/VANISHED:52712] <-> InitialHandler has connected

**Comment by Janmm14** [comment]
This means that bungeecord is not able to reach the vanilla/bukkit/spigot/whatever minecraft server which bungee is configured to send players to who newly connect.

Please doublecheck he config and if applicable the firewall. This is likely no issue in bungeecord.

**Comment by ThemInspectors** [comment]
Fallback and default servers were removed in BC 1.9 Use priorities

**Comment by MoseRattoe** [comment]
it says( Cloud Not Connect To Target Server. You Moved To fallback Server

**Comment by KRD66778** [comment]
Same problem Here bruh

**Comment by Janmm14** [comment]
> Same problem Here bruh ![Screenshot 2022-05-17 12 45 40 PM](https://user-images.githubusercontent.com/67106394/168879693-457e0ed4-b436-4f5a-85e6-30b3b511dcac.png)

@lfierro743 
ARE YOU UNABLE TO READ THEW PREVIOUS ANSWERS?????
