### ISSUE TITLE
?Run Code Check Getting this

### ISSUE THREAD

**Issue by alwaysontop617** [SpigotMC/BungeeCord#1832]
dodiaraculus:~/introcs $ ./bin BungeeCord.jar
Running findbugs on BungeeCord.jar:
M D EQ_UNUSUAL Eq: io.netty.handler.codec.http.multipart.DiskFileUpload.equals(Object) is unusual  At DiskFileUpload.java:[lines 77-81]
M B EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS Eq: io.netty.handler.codec.http.multipart.DiskFileUpload.equals(Object) checks for operand being a Attribute   At DiskFileUpload.java:[line 77]
M B EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS Eq: gnu.trove.decorator.TIntSetDecorator.equals(Object) checks for operand being a gnu.trove.set.TIntSet   At TIntSetDecorator.java:[line 108]
M B EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS Eq: gnu.trove.decorator.TByteSetDecorator.equals(Object) checks for operand being a gnu.trove.set.TByteSet   At TByteSetDecorator.java:[line 108]
M B EQ_CHECK_FOR_OPERAND_NOT_COMPATIBLE_WITH_THIS Eq: gnu.trove.decorator.TShortSetDecorator.equals(Object) checks for operand being a gnu.trove.set.TShortSet   At TShortSetDecorator.java:[line 108]

**Comment by minecrafter** [comment]
These are issues in GNU Trove and Netty. Findbugs is not the end-all to catching actual issues - in fact, BungeeCord doesn't use _any_ of these classes (as far as I know).

**Comment by alwaysontop617** [comment]
Ok I sent you an organization invitiation
:)

**Comment by minecrafter** [comment]
I'm not interested.

**Comment by alwaysontop617** [comment]
Ok Then, So do you know why I am getting these issues.

**Comment by Paulomart** [comment]
Because Bungeecord includes this libs. Use the scource code of bungee instead.
