### ISSUE TITLE
Colors in message

### ISSUE THREAD

**Issue by Vinetos** [SpigotMC/BungeeCord#1834]
Hi !
When I execute this code:
`p.sendMessage(new TextComponent("§cNous n'avons trouvé aucun serveur lobby disponible actuellement."));`

The message sent hasn't its color: http://prntscr.com/au3vrf

I'm using the latest build

**Comment by Thinkofname** [comment]
Don't mix the old system with the new one. https://www.spigotmc.org/wiki/the-chat-component-api/#common-pitfalls
