### ISSUE TITLE
TextComponent ClickEvent OPEN_FILE - no example, environment variables

### ISSUE THREAD

**Issue by JOO200** [SpigotMC/BungeeCord#1836]
I try to use a TextComponent with a ClickEvent OPEN_FILE to open the minecraft folder with a command.
I don't find any examples for the OPEN_FILE event, maybe you can add some.
Maybe you can add the support for environment variables ( look at https://en.wikipedia.org/wiki/Environment_variable for more)

**Comment by md-5** [comment]
Environment gariables would be a client side thing.
