### ISSUE TITLE
Kicked while connecting to lobby, you are already logged on

### ISSUE THREAD

**Issue by ReaperAngels** [SpigotMC/BungeeCord#1838]
Hi, this is just a big nuisance for me. New server, still doing final touches, 1.9.2 Me and my co-op can connect fine to the lobby, the ping is low, everything works. When I do /server towny it works like a charm. However, the bane of my life is factions. I do /server factions I go there, it shows "Downloading Terrain", and then again "Downloading Terrain". Back to lobby. Then at times I do /server factions and it just works. I have checked all the configs, even swapped the port for factions, seemed to work better for a moment and then went back to kicking me back to lobby. The weird thing is you are actually at factions for a brief moment, even the logs show that you are there.

Stuff I've noticed.
When I do stay in factions, I get a message "Kicked while connecting to lobby, you are already logged on". But I'm in factions. I need to set up the warps and portals, and this is really frustrating.

Bungeecord is running on outside ip:25565, lobby on localhost:25565, towny on localhost:25566 and factions on localhost:25568, was on 25567.   No clues in the logs, according to the logs /server factions worked fine. Any thoughts would be greatly appreciated.

**Comment by Janmm14** [comment]
You might want to try putting your lobby on another port.

**Comment by ReaperAngels** [comment]
Thanks for the reply, but as the bungee cord is running on the outside IP, say 192.1.1.1 and the lobby on 127.0.0.1, how would that conflict? Also, the lobby server runs fine. Actually all the servers run fine with a constant tps of 20. Connecting to the factions server is the problem. I tested it again, it fails 8/10 times. Running latest bungee cord and spigot.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        From: Janmm14Sent: Thursday 21 April 2016 01:17To: SpigotMC/BungeeCordReply To: SpigotMC/BungeeCordCc: ReaperAngels; AuthorSubject: Re: [SpigotMC/BungeeCord] Kicked while connecting to lobby, you are already logged on (#1838)You might want to try putting your lobby on another port.

—You are receiving this because you authored the thread.Reply to this email directly or view it on GitHub

**Comment by ReaperAngels** [comment]
Right, moved the ports on all the servers. Factions still connects and disconnects, with you ending up back in the lobby (Hub).

From the bungee log.
This is a fail, connect and disconnect.

01:25:15 [INFO] [Grimreaper] <-> ServerConnector [factions] has connected
01:25:15 [INFO] [Grimreaper] <-> DownstreamBridge <-> [lobby] has disconnected
01:25:15 [INFO] [Grimreaper] <-> ServerConnector [lobby] has connected
01:25:16 [INFO] [Grimreaper] <-> DownstreamBridge <-> [factions] has disconnected

This is success
01:25:43 [INFO] [Grimreaper] <-> ServerConnector [factions] has connected
01:25:43 [INFO] [Grimreaper] <-> DownstreamBridge <-> [lobby] has disconnected
01:25:43 [INFO] [Grimreaper] <-> ServerConnector [lobby] has connected
01:25:43 [INFO] [Grimreaper] <-> ServerConnector [lobby] has disconnected

Now according to this, my understanding, is the connection starts to factions, lobby disconnects, then reconnects to lobby, and finally disconnects again. 

Should it not be a simple connect factions, disconnect lobby?

**Comment by Janmm14** [comment]
Can you take a look at the factions log for both cases please too.

**Comment by ReaperAngels** [comment]
Problem is sorted.  I copied towny, that does work, configs over to factions and changed the level-name and port. Restarted everything and it works.
