### ISSUE TITLE
BungeeCord Version #1148 seems to be broken

### ISSUE THREAD

**Issue by TheOli95xz** [SpigotMC/BungeeCord#1841]
I have updated to the latest build(#1148) of BungeeCord today and I can not get it to run properly. It simply crashes with an Java exception. (See log file: http://pastebin.com/RrdaHK9e).

After a rollback to version #1147 it works just fine. Java version was untouched during the upgrade procedure.

**Comment by Thinkofname** [comment]
I'm guessing you have `throttle` set to `-1` in your config, change it back to the default of `4000`

**Comment by TheOli95xz** [comment]
Yes, you were right. It fixed my issue. Thank you for your quick response, have a nice day!

-TheOli95xz

**Comment by Janmm14** [comment]
We maybe should take care of negative throttle values by not applying the throttle. On the other hand this might be a security benefit for the servers who have their throttle at -1 currently by forcing them to rethink about it. A bungee normally should never have the need of a disabled throttle.
