### ISSUE TITLE
If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

### ISSUE THREAD

**Issue by G0d0fWar** [SpigotMC/BungeeCord#1842]
I keep getting this error and I have no idea how to fix it. Thanks for anybody who attempts to assist me. 

BungeeCord Proxy Config: http://pastebin.com/jC9452SQ
Hub Spigot Server Config: http://pastebin.com/GvE6LcKd
Hub Server.properties: http://pastebin.com/McAnpUET

Again, thank you for anyone who assists. I am using Spigot 1.9.2

**Comment by md-5** [comment]
Please use the forums for support.
