### ISSUE TITLE
NullPointerException: Nodes must be provided.

### ISSUE THREAD

**Issue by XNoki200010** [SpigotMC/BungeeCord#1844]
Sometimes when my Bungee stops I am getting this error:
http://pastebin.com/A0Z5UwNX

After that nothig will work until i kill the bungee and restart.

**Comment by Janmm14** [comment]
Are you using plugin(s) on your bungeecord?

**Comment by Phineas** [comment]
Please give us your locations.yml :)

**Comment by XNoki200010** [comment]
My locations.yml are deleted every night after the bungee stops and befor it starts again.

With an oder BungeeCord version everything was okay.

**Comment by i9hdkill** [comment]
Please open a new ticket if this issue still persists in the latest version.
