### ISSUE TITLE
Hover Event is misplaced when a part of the component is in bold

### ISSUE THREAD

**Issue by TheTonyk** [SpigotMC/BungeeCord#1845]
When a part of my Chat Component is in bold, if i add an hover event of another part of the component, the hover event will be misplaced like if the all text was not in bold.

(Sorry for my bad english)

**Comment by Janmm14** [comment]
Can you provide example code and a screenshot od the message you get?

Best thing would be if you also provide the fenerated json code which you can recieve through System.out.println(ComponentSerializer.toString(...));

**Comment by i9hdkill** [comment]
Did it work for you by now? 
Otherwise just create a thread here:
https://www.spigotmc.org/forums/bungeecord-plugin-development.23/
