### ISSUE TITLE
ServerKickEvent Not fired for roughly 50% of players disconnecting from crashed or stopped server.

### ISSUE THREAD

**Issue by andrewchi12345** [SpigotMC/BungeeCord#1846]
This event will only fire for around 50% of the players, making creating fallback servers impossible.

**Comment by Janmm14** [comment]
Can you combine your findings of the ServerKickEvent being called with the logs of disconnects?

**Comment by andrewchi12345** [comment]
'
	@EventHandler
	public void onServerKick(ServerKickEvent event) {
		System.out.println("ServerKickEvent fired for " + event.getPlayer() + " who was kicked from "+ event.getPlayer().getServer().getInfo().getName());
        }
'

**Comment by andrewchi12345** [comment]
20:27:04 [INFO] ServerKickEvent fired for PeachyChips who was kicked from LOMC-1
20:27:04 [INFO] [PeachyChips] disconnected with: Server closed
20:27:04 [INFO] [PeachyChips] <-> DownstreamBridge <-> [LOMC-1] has disconnected
20:27:04 [WARNING] [CrypticError] <-> DownstreamBridge <-> [LOMC-1] - IOException: syscall:read(...)() failed: Connection reset by peer
20:27:04 [WARNING] [Tritone] <-> DownstreamBridge <-> [LOMC-1] - IOException: syscall:read(...)() failed: Connection reset by peer
20:27:04 [INFO] [Tritone] <-> DownstreamBridge <-> [LOMC-1] has disconnected
20:27:04 [INFO] [CrypticError] <-> DownstreamBridge <-> [LOMC-1] has disconnected
20:27:04 [INFO] [CrypticError] disconnected with: Could not connect to default or fallback server, please try again later: java.net.ConnectException
20:27:04 [INFO] [Tritone] disconnected with: Could not connect to default or fallback server, please try again later: java.net.ConnectException
20:27:04 [INFO] [SixthElement] disconnected with: [Proxy] Lost connection to server.
20:27:04 [INFO] [SixthElement] <-> DownstreamBridge <-> [LOMC-1] has disconnected
20:27:04 [INFO] [PeachyChips] -> UpstreamBridge has disconnected
20:27:05 [INFO] [Tritone] -> UpstreamBridge has disconnected
20:27:05 [INFO] [CrypticError] -> UpstreamBridge has disconnected
20:27:05 [INFO] [SixthElement] -> UpstreamBridge has disconnected

There were 4 accounts on the server. Using /stop, one was caught by the Kick Event, two were NOT caught by the kick event, but bungee tried to send them to the fall back server, and one just flat out disconnected.

**Comment by andrewchi12345** [comment]
`20:31:18 [INFO] ServerKickEvent fired for SixthElement who was kicked from BuildServer`
`20:31:18 [INFO] [SixthElement] disconnected with: Server closed`
`20:31:18 [INFO] [SixthElement] <-> DownstreamBridge <-> [BuildServer] has disconnected`
`20:31:18 [INFO] ServerKickEvent fired for CrypticError who was kicked from BuildServer`
`20:31:18 [INFO] [CrypticError] disconnected with: Server closed`
`20:31:18 [INFO] [CrypticError] <-> DownstreamBridge <-> [BuildServer] has disconnected`
`20:31:18 [INFO] [SixthElement] -> UpstreamBridge has disconnected`
`20:31:18 [INFO] [CrypticError] -> UpstreamBridge has disconnected`
`20:31:19 [INFO] [Tritone] disconnected with: [Proxy] Lost connection to server.`
`20:31:19 [INFO] [PeachyChips] disconnected with: [Proxy] Lost connection to server.`
`20:31:19 [INFO] [PeachyChips] <-> DownstreamBridge <-> [BuildServer] has disconnected`
`20:31:19 [INFO] [Tritone] <-> DownstreamBridge <-> [BuildServer] has disconnected`
`20:31:19 [INFO] [PeachyChips] -> UpstreamBridge has disconnected`
`20:31:19 [INFO] [Tritone] -> UpstreamBridge has disconnected`

**This log is from a /stop command**
Again, there were 4 accounts on the server, two were caught by the Kick event, and two flat out disconnected, other tests had similar situations where they were sent to the fallback server, but not caught by the kick event (Problematic if there is a load balancer.)

**Comment by nathan818fr** [comment]
This behavior seems to be normal.

As indicated in your logs, some players are kicked but others simply lose the connection without being kick (blame the Minecraft server that does not wait for all the kick of packets are sent to shutdown).

And when a player loses connection without being kicked, the ServerDisconnectEvent event is called, not the ServerKickEvent (I will do some tests to confirm that, but that's what the analysis of the source shown me).

**Comment by andrewchi12345** [comment]
Yes, a temporary work around is to just kick all players on disable of a plugin, but that does not factor in problems such as crashes...
