### ISSUE TITLE
A question about bungeecord-proxy maven repo

### ISSUE THREAD

**Issue by Nicofisi** [SpigotMC/BungeeCord#1847]
Hello, I need to access latest `net.md_5.bungee.BungeeCord`, which is 1.9-SNAPSHOT afaik.
I have found two links,
https://oss.sonatype.org/content/repositories/snapshots/net/md-5/bungeecord-proxy/ and 
https://oss.sonatype.org/content/groups/public/net/md-5/bungeecord-proxy/
However, on both, latest version is 1.4.7-SNAPSHOT. I understand it might not be the best place to ask it, but is there any server where I can get the 1.9 from?

**Comment by Paulomart** [comment]
bungeecord-proxy is no longer released in the repos. Use bungeecord-api.

**Comment by ghacproductions** [comment]
The api is version 1.9. Use the forums the next time please.

**Comment by Nicofisi** [comment]
@ghacproductions got it
@Paulomart, but it doesn't contain `net.md_5.bungee.BungeeCord`
Maven throws error on line BungeeCord.getInstance().getPluginManager().getPlugin("LargeSk");

**Comment by ghacproductions** [comment]
Try ProxyServer instead of BungeeCord.

**Comment by Nicofisi** [comment]
@ghacproductions Thank you! (I promise I will use the forums next time :) )
