### ISSUE TITLE
Starting Bungee under ProcessBuilder freezes Parent Console.

### ISSUE THREAD

**Issue by andrewchi12345** [SpigotMC/BungeeCord#1852]
Running bungeecord with
`new ProcessBuilder("java","-jar", "-Xms"+server.getRam(), "-Xmx"+server.getRam(), "bungee.jar").start();`
Will freeze a scanner reading System.in.
Both the scanner and bungee are executed under separate threads. This does not happen with Spigot instances.

Output that is printed is live, but using BufferedReader to read the input stream produces weird lines. For every "real line", there is a separate empty line outputted. http://hastebin.com/homuhixoce.coffee

**Comment by md-5** [comment]
` -Djline.terminal=jline.UnsupportedTerminal`

**Comment by andrewchi12345** [comment]
Alright, appreciate your time and help 👍 
Have a nice day!
