### ISSUE TITLE
Bad Packet ID crashes Bungee?!

### ISSUE THREAD

**Issue by Phineas** [SpigotMC/BungeeCord#1855]
Sometimes I get these IPs pinging my server with bad packet ids:
`03:47:52 [WARNING] [/54.81.83.21:51642] <-> InitialHandler - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.StatusRequest 0 Protocol STATUS Direction net.md_5.bungee.protocol.Protocol$DirectionData@8b9b332` 
Then after a few of these pings, my Bungee seems to slowly crash, it doesn't say anything, but it just gets  REALLY slow to the point where you can hardly join and it takes ages to ping

**Comment by i9hdkill** [comment]
Did you solve your isse? Any BungeePlugins installed?

**Comment by Xayanix** [comment]
Did u solve it? I got same and im trying to investigate it ;)
