### ISSUE TITLE
"Ping" query not working after update

### ISSUE THREAD

**Issue by FHRNet** [SpigotMC/BungeeCord#1862]
Hi,
So I updated Bungeecord yesterday to latest release to support 1.9.4 and it broke the "Ping" query.
I see those error messages in my Bungee log:
`16:04:43 [WARNING] [/MyLoggingServerIP:50333] <-> InitialHandler - bad packet ID, are mods in use!? Unsupported protocol`

Response is empty.
The "old" UDP query works fine, and this worked fine on previous builds, so I assume this has something to do with the protocol change?

This is annoying because several server lists list my server as "Offline".

**Comment by md-5** [comment]
What logging protocol are you using? Ping clearly works fine here (see: client list)

**Comment by Janmm14** [comment]
What is the connection between the issue with server list pinging and your mentioning of udp and query?

**Comment by FHRNet** [comment]
Some examples of what's not working would be probably be great, so:
I'm using the Ping query to display information on my website and generate graphs of online players.
I've been using xPaw's PHP class to do that, hosted here http://api.fhrnet.eu/mc/play.ytgamers.eu/25565/newinfo?method=json and my problem is, it just returns zero information and that error message in my Bungee log pops up. It worked fine before the update, and works fine if I type in other IP (such as eu.mineplex.com).

**Comment by AshourAziz** [comment]
Experiencing this too
