### ISSUE TITLE
Bad packet ID spamming

### ISSUE THREAD

**Issue by MineTheCube** [SpigotMC/BungeeCord#1865]
Hi,

This is quite weird.. It seems that someone spam my server with malicious requests, it has started few hours ago and he still continue now.
Here are the log: http://pastebin.com/raw/ZNMceFb1 (all request are made from the same IP)

I don't know if it is related, but my bungee crashed (all players were disconnected) twice while he was spamming, it has almost never happened before.
Also it may be the same issue as #1855.

EDIT: I use the latest version (1152) of BungeeCord.

**Comment by i9hdkill** [comment]
"Crashing" Do you mean crashing by running out of memory?
For now block the IP via IpTables.
Might be a serverlist pinger?

**Comment by Janmm14** [comment]
Disable query if you don't need it.

**Comment by MineTheCube** [comment]
After looking at the logs, the crash kicked almost all my players, but I don't think every one were kicked.
Well, take a look at the logs when it happened: http://pastebin.com/raw/bKcsV8KR

I can't access to IP tables as I'm on a shared host. Also query seems to re-enable itself each time I start my bungee, I think it's forced by my host for any reason..

**Comment by Janmm14** [comment]
@MineTheCube Maybe your host uses it to display some data of your bungee in his web interface.

**Comment by SoldatulBanana** [comment]
Basically they send you a null packet and bungee can't recognize that packet then your serverlog will get full and it will slowly crash

**Comment by MineTheCube** [comment]
It is indeed a server (maybe my host) that query my bungee every 3 seconds. But I updated to Bungee 1156, and now queries are done without errors.
