### ISSUE TITLE
CPU overload

### ISSUE THREAD

**Issue by FreeWall** [SpigotMC/BungeeCord#1869]
Since 1.9.2 bungeecord support was released, my bungeecord server is getting **100% CPU usage** several times during the day. No DDoS attack or bots is detected, no error in log is appeared.

In htop (linux debian) there is like 8-10 instances of bungeecord using 100% CPU, so 600% overall.
Server cannot be stoped regularly from bungeecord console, because it's not responding. I have to kill the process with SIGKILL flag.

Screen: http://www.michalvanek.net/s/20160515181729.png

Using latest bungeecord build 1155.
Server has around 40 players online, bungeecord instance has allocated 1GB of RAM.

HW specification:
```
Intel Xeon E3-1230 (4 cores, 8 threads)
RAM 32GB
HDD 1TB
```

Bungeecord plugins:
`BungeeTabListPlus, SkinsRestorer, CommandControl, ServerListPlus`

Graph of system load during the overload (10:25 to 10:35):
http://www.michalvanek.net/s/20160515103817.png

Graph of system load in a day, there is several peaks (overloads):
http://www.michalvanek.net/s/20160515103901.png

**Comment by minecrafter** [comment]
To more accurately gauge the cause, you should use a Java profiler like VisualVM or YourKit (free trial).

**Comment by FreeWall** [comment]
Please repair this, it's really frustrating.

**Comment by Janmm14** [comment]
@FreeWall Please provide the information you were asked for.

**Comment by FreeWall** [comment]
@Janmm14 I don't want any information, i just reported a bug.

**Comment by minecrafter** [comment]
We're asking for a CPU profile from YourKit or VisualVM.

**Comment by FreeWall** [comment]
Sorry, I was trying to, but it's a problem. I'm not so skilled in linux but if I'll find out how to run it, I will provide the information.

**Comment by Brokkonaut** [comment]
This usually happens when a server has a very large scoreboard. some broken plugins create those large scoreboards.. Have a look at the servers world/data/scoreboard.dat. If that file is very large (more than about 100kb) it is probably the cause. You can delete it while the server is shut down (it will reset all scoreboards), but you should also try to find the plugin that causes those large scoreboards

**Comment by FreeWall** [comment]
@Brokkonaut Wow, you are right. My scoreboards file was almost 2MB large and it has over 120k teams. After a while I discovered it's happening because of Citizens plugin, I disabled "player-scoreboard-teams" in Citizens config.yml and it's fixed now.
Really thank you for your help, you saved my server!

**Comment by iKaneki-Ken** [comment]
Issue fixed, @md-5, this issue can be closed now.
