### ISSUE TITLE
Specify Version for Network?

### ISSUE THREAD

**Issue by Phreag** [SpigotMC/BungeeCord#1871]
Could it be possible to add an option to set which version should be supported by the bungee?
Because we are runnging on 1.9.4 but in server lists and in Clients it shows 1.8.x, 1.9.x.

Its really annoying for players if the server shows the wrong version.

So could it be possible to add an config option to choose which version should be displayed as supported and which not?

**Comment by Brokkonaut** [comment]
Plugins can do that.

**Comment by i9hdkill** [comment]
This does pretty much the same job:
1250088f98fc59d28736932fac88586594329ec2
