### ISSUE TITLE
IP Forwarding issue Bungeecord

### ISSUE THREAD

**Issue by LogieOneCanobie** [SpigotMC/BungeeCord#1872]
Hi there! I've tried to set up my Minecraft server with Bungeecord today, and I successfully did, but only for myself (I had some IP issues where other people couldn't connect.) I think I fixed the IP issues, but now whenever I try to log onto my server, it won't connect and it says: 'If you wish to use IP forwarding please enable it in your Bungeecord config as well.' In the Bungeecord config, IP forwarding is set to 'true,' and in both of my world's spigot files, Bungeecord is set to 'true.' I've been trying to find a solution to this problem for 2 hours now, and this is my last result. 

World Spigot.yml:

config-version: 8
settings:
  debug: false
  timeout-time: 60
  restart-on-crash: true
  restart-script: ./start.sh
  bungeecord: true
  late-bind: false
  filter-creative-items: true
  moved-wrongly-threshold: 0.0625
  save-user-cache-on-stop-only: false
  player-shuffle: 0
  sample-count: 12
  user-cache-size: 1000
  int-cache-limit: 1024
  netty-threads: 4
  attribute:
    maxHealth:
      max: 2048.0
    movementSpeed:
      max: 2048.0
    attackDamage:
      max: 2048.0
  moved-too-quickly-multiplier: 10.0
stats:
  disable-saving: false
  forced-stats: {}
messages:
  restart: Server is restarting
  whitelist: You are not whitelisted on this server!
  unknown-command: Unknown command. Type "/help" for help.
  server-full: The server is full!
  outdated-client: Outdated client! Please use {0}
  outdated-server: Outdated server! I'm still on {0}
commands:
  silent-commandblock-console: false
  tab-complete: 0
  log: true
  spam-exclusions:
  - /skill
  replace-commands:
  - setblock
  - summon
  - testforblock
  - tellraw
world-settings:
  default:
    verbose: true
    hanging-tick-frequency: 100
    wither-spawn-sound-radius: 0
    merge-radius:
      item: 2.5
      exp: 3.0
    item-despawn-rate: 6000
    view-distance: 10
    enable-zombie-pigmen-portal-spawns: true
    arrow-despawn-rate: 1200
    zombie-aggressive-towards-villager: true
    ticks-per:
      hopper-transfer: 8
      hopper-check: 8
    hopper-amount: 1
    seed-village: 10387312
    seed-feature: 14357617
    dragon-death-sound-radius: 0
    max-entity-collisions: 8
    entity-tracking-range:
      players: 48
      animals: 48
      monsters: 48
      misc: 32
      other: 64
    max-tick-time:
      tile: 50
      entity: 50
    save-structure-info: true
    max-tnt-per-tick: 100
    hunger:
      walk-exhaustion: 0.2
      sprint-exhaustion: 0.8
      combat-exhaustion: 0.3
      regen-exhaustion: 3.0
    random-light-updates: false
    mob-spawn-range: 4
    nerf-spawner-mobs: false
    growth:
      cactus-modifier: 100
      cane-modifier: 100
      melon-modifier: 100
      mushroom-modifier: 100
      pumpkin-modifier: 100
      sapling-modifier: 100
      wheat-modifier: 100
      netherwart-modifier: 100
    entity-activation-range:
      animals: 32
      monsters: 32
      misc: 16

Bungeecord config.yml:

ip_forward: true
network_compression_threshold: 256
stats: 3c48107b-e155-47d3-a2b4-f784a31d2b8d
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  Logan_miner:
  - admin
servers:
  kitPvP1:
    motd: '&1Just another BungeeCord - KitPvP 1'
    address: 127.0.0.1:25566
    restricted: false
  kitPvP2:
    motd: '&1Just another BungeeCord - KitPvP 2'
    address: 127.0.0.1:25567
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - kitPvP1
  - kitPvP1
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
    kitPvP1.md-5.net: kitPvP1
    kitPvP2.md-5.net: kitPvP2
  max_players: 100
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
player_limit: 100
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000

It would be very helpful of someone could look over this code (as I am still a huge noob to all of this,) and point out any errors I have made. Thanks so much!

**Comment by md-5** [comment]
Please use the forums for support
