### ISSUE TITLE
GC overhead limit exceeded

### ISSUE THREAD

**Issue by Blamo27** [SpigotMC/BungeeCord#1875]
Bungeecord disconnect all players : (crash)
java.lang.OutOfMemoryError: GC overhead limit exceeded

Startup: java -Xms512M -Xmx512M -jar BungeeCord.jar

Processor usage : 600% (bungeecord)

**Comment by Brokkonaut** [comment]
Have you tried to increase the memory limit (Xmx)? Looks like it just ran out of memory..

**Comment by Blamo27** [comment]
So when the server is out of memory, the CPU usage is increasing

**Comment by Brokkonaut** [comment]
Yes, because the GC desperately tries to free some memory... Until it gives up and throws the OOM

**Comment by Blamo27** [comment]
Okey I'll try thanks !
