### ISSUE TITLE
Using BungeeCord as a local proxy to connect minecraft 1.9.4 to 1.8.x servers.

### ISSUE THREAD

**Issue by beppe9000** [SpigotMC/BungeeCord#1876]
Can we do that? Is it even possible?

**Comment by kamcio96** [comment]
No

**Comment by Janmm14** [comment]
BungeeCord does not support online-mode servers behind itself and also it does not change the packets, it can just handle packets of different versions where neccessary for itself. People can put either ViaVersion on an 1.8 Spigot Server or ProtocolSupport on an 1.8 / 1.9 spigot server to supports older minecraft versions.
