### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by FunnyCraft** [SpigotMC/BungeeCord#1879]
http://pastebin.com/NiD6NhqS

**Comment by Envici** [comment]
Can you provide more information about the problem than just screaming WARNING. When did this occur? What were you doing when this occurred? What plugins are you running etc.

**Comment by FunnyCraft** [comment]
SkinRestorer oll

**Comment by Janmm14** [comment]
This error is about the query function. If you don't need it, turn it off. Else likely someone sent an illegal packet.
