### ISSUE TITLE
If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

### ISSUE THREAD

**Issue by SPACEMONKEYDev** [SpigotMC/BungeeCord#1880]
When i try to join my server it says [18:50:54 INFO]: /127.0.0.1:49485 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!
wich i have change it and it still won't work plz help

**Comment by SPACEMONKEYDev** [comment]
plz help me

**Comment by kamcio96** [comment]
just read error...

**Comment by Janmm14** [comment]
Issues are for real issues. This is a notice that contains exactly what you have to do. If you don't know about that, please consult the wiki on spigotmc.org

**Comment by kamcio96** [comment]
@Janmm14 btw https://github.com/SpigotMC/BungeeCord/issues?utf8=%E2%9C%93&q=is%3Aissue+forward+forwarding :joy: :joy: :joy:
