### ISSUE TITLE
DecoderException - [Proxy] Lost connection to server

### ISSUE THREAD

**Issue by DragonbornCommunity** [SpigotMC/BungeeCord#1883]
Error: http://pastebin.com/sC0rEZ6K
Plugins on bungeecord:
Latest RedisBungee, Latest BungeeAuthMeBridge, Latest SkinsRestorer

Bungee version #1158 downloaded from the official jenkins.

Only happens with certain players.
Deleting all player data from the fallback server (essentials, world .dat files...) did not do any difference.
Using no plugins on the fallback server did not do any difference.

When he tries to connect with 1.9 it just throws the proxy connection lost error, while on 1.8 it throws the error in the pastebin.

When he joins the server he gets instantly kicked and all the players in the server are kicked for the same exact reason.

Tested and reproduced on different computers with the same account and the same result shows up, so it is indeed a server-related problem and not client-side.

**Comment by i9hdkill** [comment]
Even deleting the whole world on your hub server didn't do the trick? Try emoving skins restorer.

**Comment by DragonbornCommunity** [comment]
Removing SkinsRestorer did not change anything.

**Comment by kamcio96** [comment]
Try [Waterfall](http://github.com/WaterfallMC/Waterfall/)

**Comment by md-5** [comment]
Please remove all plugins from both server and bungee. This looks almost certainly plugin induced.

**Comment by DragonbornCommunity** [comment]
Removed all plugins from bungee, nothing changed. Now trying to remove the plugins from the server.

**Comment by i9hdkill** [comment]
Did you manage to fix it?

**Comment by DragonbornCommunity** [comment]
Updated Bungeecord and this still happens: http://pastebin.com/g7XKb2F2

**Comment by i9hdkill** [comment]
Even after removing all spigot plugins?

**Comment by DragonbornCommunity** [comment]
Now removed all the plugins and started testing.

**Comment by i9hdkill** [comment]
It's definitely an outdated or bad written spigot plugin.

**Comment by DragonbornCommunity** [comment]
I noticed a message in the console of the spigot fallback server:
 [21:02:42] [Netty Epoll Server IO #2/ERROR]: java.lang.NullPointerException

**Comment by DragonbornCommunity** [comment]
With no plugins on the spigot server, this error comes up in the console of the spigo fallback server: [01:32:28 INFO]: rtetin lost connection: Internal Exception: java.io.IOException: Error while write(...): Broken pipe
