### ISSUE TITLE
java.net.connectexeption

### ISSUE THREAD

**Issue by servialcraft** [SpigotMC/BungeeCord#1886]
my console won't let me see whats going on but i have 2 servers: server001,server002
and i can't connect to server002
can anybody help me 
this is my config:

ip_forward: true
network_compression_threshold: 256
stats: f41fdcfa-37a4-4834-9661-9b1f2223fd14
groups:
  Ultra_Simon:
  - admin
servers:
  server001:
    motd: ''
    address: localhost:25566
    restricted: false
  server002:
    motd: ''
    address: localhost:25567
    restricted: false
timeout: 30000
player_limit: 2000
listeners:
- query_port: 25577
  motd: '&cServial&dCraft  &a-----  &bJoin &eNow!'
  priorities:
  - server001
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 2000
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000

**Comment by md-5** [comment]
Please use the forums for support.
