### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by EMC3** [SpigotMC/BungeeCord#1888]
Hello,

I got this Issue for about 2 months, but never worried as my BungeeCoord survived without crashing for about 2 Days and I have a scheduled restart every 24h. But since the 1.10 update bungeecord crashes about 2-3 times a day with an OutOfMemory Error. Bungeecoord has 1.5Gb.

Some screenshots:
http://upload-pictures.de/bild.php/97682,l1B18WI.png
http://upload-pictures.de/bild.php/97683,l258PW6.png
http://upload-pictures.de/bild.php/97684,l3HKAN3.png

**Comment by i9hdkill** [comment]
Any plugins installed? Looks like a plugin issue. How many players are connected at this time?

**Comment by EMC3** [comment]
Plugins:
https://www.spigotmc.org/resources/bungeetablistplus.313/
https://www.spigotmc.org/resources/skinsrestorer.2124/
and a self made, that only changes the motd (not animated) and handles some plugin messages

Players Connected: 26, because of a recent crash. Before 1.10 update it hold about 100 players with the same amount of ram, but the same leaks were present.

**Comment by i9hdkill** [comment]
remove all of them and test again.

**Comment by andrewkm** [comment]
EMC3 I am experiencing the same issue and highly suspect BungeeTabListPlus to be the culprit.

**Comment by andrewkm** [comment]
@EMC3 update for you after removing the TabListPlus plugin?
