### ISSUE TITLE
send command doesn't work with changed names

### ISSUE THREAD

**Issue by intangir** [SpigotMC/BungeeCord#1889]
this worked before, on all of 1.8 and i think even before it (since name changes were allowed whenever that was)

but now when i try to send a person using their currently set name it doesn't work, it will only send them via their actual mojang account name

i have a mod which changes their name on log in.
it sets the name field on the connection, it sets the name field on the login request object, and it sets their player display name

previously this worked perfectly fine, i could send using their new name but now it doesn't

auto completion still completes their new name though which is weird, all of the log events also show their new name, everything seems to work fine with the new name but send, and it worked before so i don't know why it doesn't now

since the 1.9 versions

**Comment by intangir** [comment]
overriding names with this: https://www.spigotmc.org/resources/identityoverride.3877/

**Comment by intangir** [comment]
it also effects how the "ConnectOther" plugin message is handled (this also worked fine before with changed names)

**Comment by intangir** [comment]
i also just tested the getName of all of the players in .getPlayers(), and it is the changed name, it looks like the ConnectOther checks that SAME sub, not sure why it can't find players

**Comment by kamcio96** [comment]
Hmmm, what? How did you change player's name?

**Comment by Janmm14** [comment]
Is the plugin using the bungeecord api onlx or is it handling with internals of bungeecord? In the first case this might get fixed, in the other case you have to fix the plugin somehow.

**Comment by md-5** [comment]
You are using a plugin which bypasses the BungeeCord API (and breaks Bungee).
