### ISSUE TITLE
offline players linger on proxied players list after they've logged

### ISSUE THREAD

**Issue by intangir** [SpigotMC/BungeeCord#1890]
for some reason since 1.9 players remain 'online' even after they have logged. permanently

they show up in the plugin.getProxy().getPlayers() even after LoggedOut events have been processed for them, they are definiately not on

they end up being listed in mods like bungeetablistplus, and my realmtracker

it seems to happen pretty frequently like 40-50% of the time, not 100% though

**Comment by intangir** [comment]
it just occured to me that this bug might be related to the #1889 bug. maybe it can't find their names to remove them because they are overridden

**Comment by Janmm14** [comment]
Bungee plugins?
