### ISSUE TITLE
Problems with server icon

### ISSUE THREAD

**Issue by SaF3rC** [SpigotMC/BungeeCord#1891]
Hello, I am SaF3rC.Hi, I am creating a bungee server that works well but when I put the server icon in bungee folder and I reboot the server it does not start! Please, I need help! Sorry for my English :(

**Comment by MiniDigger** [comment]
>  it does not start!
can you paste some logs? we can't help you without that.

**Comment by kamcio96** [comment]
```server-icon.png``` ?

**Comment by md-5** [comment]
This is not for support, please use the forums for support.
