### ISSUE TITLE
Permission alert

### ISSUE THREAD

**Issue by MrDienns** [SpigotMC/BungeeCord#1894]
Hi, not sure if this is the right place for a request;

Is it possible to add a function that alerts to people (on all or a list of servers) with a speficic permission? Like the Broadcast("message", "some.permission"); method in Spigot?

If this is the wrong place for a request, sorry

Thanks in advance

**Comment by md-5** [comment]
Really you should just use a for loop, such a method is hardly useful from an API perspective.

**Comment by Dienns** [comment]
Already thought about that, so I guess I'll go on with that idea. Thanks
