### ISSUE TITLE
Clients Crash whilst join different servers

### ISSUE THREAD

**Issue by CR3DITorD3BIT** [SpigotMC/BungeeCord#1898]
So clients are able to connect the "Hub" perfectly fine, but when they try to join any other server, they get this client crash:
http://pastebin.com/UpDTbHxh

My bungeecord is running with Cauldron 1.7.10 and the mods in use are from Tekkit Legends. Im unsure on what is exactly causing the crash, I will most certainly grateful if anyone is able to give me some information to fix this!

**Comment by MylesIsCool** [comment]
BungeeCord does not support 1.7.10.

Please take this issue out with the fork or what you're using.
