### ISSUE TITLE
Bungeecord #1167 Commands not working console.

### ISSUE THREAD

**Issue by rsnorboy95** [SpigotMC/BungeeCord#1902]
Im using bungeecord #1167 the cpu usage is constant 50% and i cant do any commands in console + console says:
Command queue limit reached (1000), not sending: glist

**Comment by Paulomart** [comment]
Not a bungee bug. It's your host.

**Comment by rsnorboy95** [comment]
hmm how? I tried using bungeecord for 1.8 and it doesnt happen then?

**Comment by i9hdkill** [comment]
Not a Bungee bug. No response, no way to reproduce it provided.
