### ISSUE TITLE
BungeeCord hogging VM?

### ISSUE THREAD

**Issue by L4BORG** [SpigotMC/BungeeCord#1903]
PID 5621 = BungeeCord

startup: java -Xmx8G -Xms8G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:MaxGCPauseMillis=100 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=60 -XX:InitiatingHeapOccupancyPercent=30 -XX:TargetSurvivorRatio=90 -Dio.netty.recycler.maxCapacity.default=20000 -jar BungeeCord.jar

The issue: http://pastebin.com/7q77ZHDx

This started happening a few weeks back... and it last happened with:

04:34:13 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:1250088:1167 by md_5

I'm not sure how's that even possible or what is causing this... but the numbers are crazy (14 GB)

Plugins: ServerListPlus, SkinsRestorer, NuVotifier

I remember back then when we could run BungeeCord for months without restart, now it would get killed every 1,2 or 3 weeks tops... and we were using exact the same plugins...

**Comment by md-5** [comment]
Crazy java options are not supported.
