### ISSUE TITLE
BungeeCord Build #1167 error when starting 

### ISSUE THREAD

**Issue by SignusFalcon** [SpigotMC/BungeeCord#1904]
`[m[2K00:50:28 [SEVERE] Exception in thread "main" 
[m[2K00:50:28 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
[m[2K00:50:28 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:237)
[m[2K00:50:28 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:78)
[m[2K00:50:28 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:259)
[m[2K00:50:28 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
[m[2K00:50:28 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)` 

Starting the server after changing the motd to: InfernalAtaxia || OPFactions, Skywars and more

**Comment by md-5** [comment]
Your config is invalid
