### ISSUE TITLE
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder"

### ISSUE THREAD

**Issue by TheWhiteLow** [SpigotMC/BungeeCord#1907]
Hey

I have the bungeecord projekt von this github site and I can not the bungeecord projekt with maven compilen. This is the fail message

[INFO] --- scriptus:0.3.1:describe (default) @ bungeecord-parent ---
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

**Comment by md-5** [comment]
This isn't an issue with BungeeCord, nor is it a fail.

**Comment by TheWhiteLow** [comment]
What than?

**Comment by Janmm14** [comment]
After running is there a BungeeCord.jar in the bootstrap/target folder?

**Comment by TheWhiteLow** [comment]
@Janmm14 
yes, but the format in the console from the bungeecord.jar shows this :

^J^[[m^[[2K^M22:46:35 [INFORMATION] Loaded plugin Yamler version 2.4.0-SNAPSHOTb-16 by geNAZt^J^[[m^[[2K^M22:46:35 [INFORMATION] Loaded plugin BungeeCloud version 1.0 by null^J^[[m^[[2K^M22:46:35 [INFORMATIO
l version git:reconnect_yaml:1.9-SNAPSHOT:ec48077:1156 by SpigotMC^J^[[m^[[2K^M22:46:35 [INFORMATION] Loaded plugin cmd_list version git:cmd_list:1.9-SNAPSHOT:ec48077:1156 by SpigotMC^J^[[m^[[2K^M22:46:35 [W
is not defined^J^[[m^[[2K^M22:46:35 [INFORMATION] Enabled plugin Yamler version 2.4.0-SNAPSHOTb-16 by geNAZt^J^

the format is crashing
