### ISSUE TITLE
Bug log

### ISSUE THREAD

**Issue by x9nico** [SpigotMC/BungeeCord#1908]
Hello, My log is like that now : 
11.07 13:52:40 [Server] INFO ^[[2K^M13:51:36 [INFO] Using OpenSSL based native cipher.^J^[[m^[[2K^M13:51:36 [INFO] Using native code compressor^J^[[m^[[2K^M13:51:36 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:eca9957:1168^J^[[m^[[2K^M13:51:36 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop^J^[[m^[[2K^M13:51:36 [INFO] Epoll is working, utilising it!^J^[[m^[[2K^M13:51:37 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M13:51:37 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M13:51:37 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M13:51:37 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M13:51:37 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M13:51:37 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())^J^[[m^[[2K^M13:51:37 [INFO] Attempting to update plugin from ModuleVersion(build=1152, git=a12ac37) to ModuleVersion(build=1168, git=eca9957)^J^[[m^[[2K^M13:51:37 [INFO] Attempting to Jenkins download module cmd_alert v1168^J^[[m^[[2K^M13:51:37 [INFO] Download complete^J^[[m^[[2K^M13:51:37 [INFO] Attempting to update plugin from ModuleVersion(build=1152, git=a12ac37) to ModuleVersion(build=1168, git=eca9957)^J^[[m^[[2K^M13:51:37 [INFO] Attempting to Jenkins download module cmd_find v1168^J^[[m^[[2K^M13:51:38 [INFO] Download complete^J^[[m^[[2K^M13:51:38 [INFO] Attempting to update plugin from ModuleVersion(build=1152, git=a12ac37) to ModuleVersion(build=1168, git=eca9957)^J^[[m^[[2K^M13:51:38 [INFO] Attempting to Jenkins download module cmd_list v1168^J^[[m^[[2K^M13:51:38 [INFO] Download complete^J^[[m^[[2K^M13:51:38 [INFO] Attempting to update plugin from ModuleVersion(build=1152, git=a12ac37) to ModuleVersion(build=1168, git=eca9957)^J^[[m^[[2K^M13:51:38 [INFO] Attempting to Jenkins download module cmd_send v1168^J^[[m^[[2K^M13:51:38 [INFO] Download complete^J^[[m^[[2K^M13:51:38 [INFO] Attempting to update plugin from ModuleVersion(build=1152, git=a12ac37) to ModuleVersion(build=1168, git=eca9957)^J^[[m^[[2K^M13:51:38 [INFO] Attempting to Jenkins download module cmd_server v1168^J^[[m^[[2K^M13:51:38 [INFO] Download complete^J^[[m^[[2K^M13:51:38 [INFO] Attempting to update plugin from ModuleVersion(build=1152, git=a12ac37) to ModuleVersion(build=1168, git=eca9957)^J^[[m^[[2K^M13:51:38 [INFO] Attempting to Jenkins download module reconnect_yaml v1168^J^[[m^[[2K^M13:51:38 [INFO] Download complete^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin LegendBungee version 1.0 by x9nico^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin LegendGamesBroadcasts version 1.0 by x9nico^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin LegendMotd version 1.0.0 by Th0MaX^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin BungeeJSON version 0.1 by tuxed^J^[[m^[[2K^M13:51:38 [INFO] LegendServersStatues > Dmarage en cours...^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin LegendServersStatues version 1.0 by JumperBoost^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin BungeeParty version 2.0 by OverGames^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin BungeeHub version 1.1 by Inkzzz^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin BuycraftX version 0.1.2-SNAPSHOT by Buycraft^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin AntiNuke version 1.0 by x9nico^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:38 [INFO] Loaded plugin BungeeServerManager version 1.0.15-SNAPSHOT by Teg^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin LegendBungee version 1.0 by x9nico^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin LegendGamesBroadcasts version 1.0 by x9nico^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin LegendMotd version 1.0.0 by Th0MaX^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin BungeeJSON version 0.1 by tuxed^J^[[m^[[2K^M13:51:39 [INFO] LegendServersStatues > Le Plugin vient de s'allumer avec Succ !^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin LegendServersStatues version 1.0 by JumperBoost^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin BungeeParty version 2.0 by OverGames^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin BungeeHub version 1.1 by Inkzzz^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:39 [INFO] [BuycraftX] Looks like this is a fresh setup. Get started by using 'buycraft secret <key>' in the console.^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin BuycraftX version 0.1.2-SNAPSHOT by Buycraft^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin AntiNuke version 1.0 by x9nico^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:eca9957:1168 by SpigotMC^J^[[m^[[2K^M13:51:39 [INFO] Enabled plugin BungeeServerManager version 1.0.15-SNAPSHOT by Teg^J^[[m>^[[2K^M13:51:39 [INFO] Listening on /0.0.0.0:25565^J^[[m>save-all
11.07 13:52:40 [Server] INFO ^[[2K^M13:52:40 [INFO] ^[[0;31;1mCommand not found^J^[[m>end
11.07 13:52:42 [Server] INFO ^[[2K^M13:52:40 [INFO] Closing listener [id: 0x777d8ac1, /0.0.0.0:25565]^J^[[m>^[[2K^M13:52:40 [INFO] Closing pending connections^J^[[m>^[[2K^M13:52:40 [INFO] Disconnecting 0 connections^J^[[m>^[[2K^M13:52:40 [INFO] Closing IO threads^J^[[m>^[[2K^M13:52:42 [INFO] Disabling plugins^J^[[m>^[[2K^M13:52:42 [INFO] LegendServersStatues > Le Plugin vient de d'eindre avec Succ !^J^[[m>^[[2K^M13:52:42 [INFO] Thank you and goodbye^J^[[m>

Why is like that ?

**Comment by md-5** [comment]
> 11.07 13:52:40 [Server] INFO ^[[2K^M13:52:40 [INFO] ^[[0;31;1mCommand not found^J^[[m>end

You or your server panel typed end into the console...

**Comment by x9nico** [comment]
I already enter that and nothing as changed

**Comment by Janmm14** [comment]
> I already enter that and nothing as changed
You should NOT enter the `end` command, as it stops your server. And `save-al`l is no bungeecord command.
