### ISSUE TITLE
Broken console

### ISSUE THREAD

**Issue by DiaLight** [SpigotMC/BungeeCord#1909]
[This commit](https://github.com/SpigotMC/BungeeCord/commit/eca99576a0bf41a07684fc653405b9e9d2a09111) brakes windows console.
newlines replaces by "^J^[[m^[[2K^M".

**Comment by DiaLight** [comment]
Example:
^[[2K^M22:32:13 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.^J^[[m^[[2K^M22:32:13 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux^J^[[m^[[2K^M22:32:13 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:eca9957:1168

**Comment by DiaLight** [comment]
On previous commit everything is fine.

**Comment by i9hdkill** [comment]
Confirmed, console output is broken since last commit on windows.
http://prntscr.com/bs6j55
