### ISSUE TITLE
Add support for Dynamic IPs

### ISSUE THREAD

**Issue by TiTo-418** [SpigotMC/BungeeCord#1910]
Example:
I add a server with the ip "example.com"
It redirects to 1.2.3.4 (my server is hosted there so I can connect)
Later on, example.com redirects to 5.6.7.8 so I'm not able to connect anymore.

**Comment by md-5** [comment]
IPs are resolved via the Java resolver and may dependent on cache's there or at a DNS server.
There is no change at the BungeeCord level that could fix this. You should look  at your TTLs.

**Comment by TiTo-418** [comment]
@md-5 So the ip is resolved constanty and "updated" on BungeeCord?
