### ISSUE TITLE
Bungee Yaml

### ISSUE THREAD

**Issue by ReaperAngels** [SpigotMC/BungeeCord#1911]
I have these errors on startup. And then a few hours later players can no longer connect.

19:47:38 [INFO] Could not load native library: /tmp/bungeecord-native-cipher1329309710847732483.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
19:47:38 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
19:47:38 [INFO] Using native code compressor
19:47:38 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:97eef62:1159
19:47:38 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
19:47:38 [INFO] Epoll is working, utilising it!
19:47:38 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
19:47:38 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
19:47:38 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
19:47:38 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
19:47:38 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
19:47:38 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
19:47:38 [INFO] Loaded plugin EnjinMinecraftPlugin version 3.0.1-bungee by www.Enjin.com
19:47:38 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:38 [INFO] Loaded plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:38 [INFO] Loaded plugin SkinsRestorer version 12.4.2 by Blackfire62,Th3Tr0LLeR
19:47:38 [INFO] Loaded plugin BungeeChat version 1.2.b1 by shawn_ian
19:47:38 [INFO] Loaded plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:38 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:38 [INFO] Loaded plugin NuVotifier version 2.3.2.2 by blakeman8192, Kramer, tuxed
19:47:38 [INFO] Loaded plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:38 [INFO] Loaded plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:38 [INFO] Loaded plugin BungeeTabListPlus version 2.5.2 by CodeCrafter47
19:47:40 [INFO] Enabled plugin EnjinMinecraftPlugin version 3.0.1-bungee by www.Enjin.com
19:47:40 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:40 [INFO] Enabled plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:97eef62:1159 by SpigotMC
19:47:40 [SEVERE] java.lang.ClassNotFoundException: org.bukkit.configuration.file.YamlConfiguration
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
19:47:40 [SEVERE] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
19:47:40 [SEVERE] 	at java.lang.Class.forName0(Native Method)
19:47:40 [SEVERE] 	at java.lang.Class.forName(Class.java:264)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.reload(YamlConfig.java:142)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.<init>(YamlConfig.java:25)
19:47:40 [SEVERE] 	at skinsrestorer.shared.storage.Locale.<clinit>(Locale.java:11)
19:47:40 [SEVERE] 	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:41)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:47:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:47:40 [SEVERE] java.lang.ClassNotFoundException: org.bukkit.configuration.file.YamlConfiguration
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
19:47:40 [SEVERE] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
19:47:40 [SEVERE] 	at java.lang.Class.forName0(Native Method)
19:47:40 [SEVERE] 	at java.lang.Class.forName(Class.java:264)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.reload(YamlConfig.java:142)
19:47:40 [SEVERE] 	at skinsrestorer.shared.storage.Locale.load(Locale.java:42)
19:47:40 [SEVERE] 	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:41)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:47:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:47:40 [SEVERE] java.lang.NullPointerException
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.get(YamlConfig.java:55)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.get(YamlConfig.java:63)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.getString(YamlConfig.java:79)
19:47:40 [SEVERE] 	at skinsrestorer.shared.storage.Locale.load(Locale.java:49)
19:47:40 [SEVERE] 	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:41)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:47:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:47:40 [SEVERE] java.lang.NullPointerException
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.set(YamlConfig.java:45)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.get(YamlConfig.java:64)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.getString(YamlConfig.java:79)
19:47:40 [SEVERE] 	at skinsrestorer.shared.storage.Locale.load(Locale.java:49)
19:47:40 [SEVERE] 	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:41)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:47:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:47:40 [SEVERE] java.lang.NullPointerException
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.get(YamlConfig.java:55)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.get(YamlConfig.java:66)
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.getString(YamlConfig.java:79)
19:47:40 [SEVERE] 	at skinsrestorer.shared.storage.Locale.load(Locale.java:49)
19:47:40 [SEVERE] 	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:41)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:47:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
19:47:40 [SEVERE] java.lang.NullPointerException
19:47:40 [SEVERE] 	at skinsrestorer.shared.utils.YamlConfig.getString(YamlConfig.java:79)
19:47:40 [SEVERE] 	at skinsrestorer.shared.storage.Locale.load(Locale.java:49)
19:47:40 [SEVERE] 	at skinsrestorer.bungee.SkinsRestorer.onEnable(SkinsRestorer.java:41)
19:47:40 [SEVERE] 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:227)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
19:47:40 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
19:47:40 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

This is what happens

19:42:28 [INFO] [Grimm] <-> ServerConnector [Lobby] has connected
19:42:29 [INFO] [/165.255.23.197:59699] <-> InitialHandler has connected
19:42:45 [INFO] [/37.187.63.146:39915] <-> InitialHandler has connected
19:42:46 [WARNING] [Grimm] -> UpstreamBridge - read timed out
19:42:46 [INFO] [Grimm] disconnected with: §fReadTimeoutException : null
19:42:46 [INFO] null

**Comment by Janmm14** [comment]
The errors are that a plugin (skinsrestorer) tries to use a bukkit class on a bungee server.
I expect that the following issues are caused by the first issue. Also that the user can't connect is likely a plugin issue.

**Comment by ReaperAngels** [comment]
The thing is that skinsrestorer is a bungee plugin. Now I also see that the same plugin is used on Spigot too. So if I'm understanding this correctly, you're saying it's picking up on the spigot part and throwing the exception?

**Comment by Janmm14** [comment]
yes
