### ISSUE TITLE
Make BungeeCord create Thread for each Player

### ISSUE THREAD

**Issue by xXAlex10Xx** [SpigotMC/BungeeCord#1915]
Hey,
i'v got some Problem with plugins that block BungeeCord main-thread when too much players want to join.
How about making a thread for each player and handle the events sync to that thread, so other players aren't affected by lags, one player causes.

Or would my idea cause other problems with BungeeCord.
If i would be deep enough in the MC-protocol, i would try it myself, but i'm not.

Best Regards
Alex

**Comment by MylesIsCool** [comment]
Fix your plugin and use non blocking actions then.

**Comment by xxyy** [comment]
Hi, BungeeCord does not have a main thread.

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by xXAlex10Xx** [comment]
I almost did, but some actions cannot be done async, when handling join events.
So far this was my idea how to fix this problem easily.

**Comment by xxyy** [comment]
Can't you use intents?

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by xXAlex10Xx** [comment]
@xxyy Sorry, i dont use GitHub that often. Did not know about that function...

**Comment by xxyy** [comment]
It's not a feature of GitHub, but of the BungeeCord event dispatcher:
https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/event/AsyncEvent.java#L50

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.

**Comment by xXAlex10Xx** [comment]
@xxyy Oh well, thank you. Recoded anything possible to this.
