### ISSUE TITLE
Question about ReconnectHandler

### ISSUE THREAD

**Issue by ItsHarry** [SpigotMC/BungeeCord#1916]
Tried asking this in #md_5 IRC but got no response. Is ReconnectHandler.getServer() asynchronous?

In other words, will issues arise if a custom ReconnectHandler.getServer() takes a long time to complete?

**Comment by md-5** [comment]
Nothing in Bungee is async by default

**Comment by ItsHarry** [comment]
Okay thank you. So that means that if a MySQL query in ReconnectHandler.getServer() were to take a long time, it would cause issues. What can I do to prevent this besides setting a query timeout?

**Comment by ItsHarry** [comment]
Shouldn't ReconnectHandler be changed to be asynchronous if slow queries can have an impact on Bungee performance?

**Comment by kamcio96** [comment]
There should be async event, where plugin can set server or kick player if server is unavailable :smile:
