### ISSUE TITLE
PreLoginEvent UUID

### ISSUE THREAD

**Issue by Dienns** [SpigotMC/BungeeCord#1918]
Hi,

I'm not entirely sure if this is a bug or not, but I feel like it should be changed;

In the PreLoginEvent, there's a method for receiving a player UUID from the event. However, this UUID is always null and therefore can't be used. Is it possible to either send the UUID in the PreLoginEvent, or get rid of the GetUniqueID on this event?

Thank you

**Comment by kamcio96** [comment]
PreLoginEvent is called before connecting to mojang's server, so it's impossible to get right UUID, use LoginEvent :wink:

**Comment by Janmm14** [comment]
The `PreLoginEvent` does not contain a direct method to recieve an uuid. It just exposes the `PendingConnection`. And I think we do not need to create an `EarlyPendingConnection` interface (or similar name) to remove that one method.

Instead such information might fit into the javadocs of `PendingConnection`.

**Comment by ItsHarry** [comment]
It is in the docs for PreLoginEvent

https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/event/PreLoginEvent.java#L14

**Comment by kamcio96** [comment]
Similar issue is with ProxyPingEvent, some devs want check username in that event.
