### ISSUE TITLE
Pixelmon fights "waiting" bug (Only when connected via BC)

### ISSUE THREAD

**Issue by MarkL4YG** [SpigotMC/BungeeCord#1919]
This may seem unrelated to BungeeCord but since this only happens on our servers when the client is connected via BungeeCord, I'll post this anyway:

When fighting another Pokémon the fight freezes during "wating..." phase.
The fight then has to be aborted using "/endbattle".

This problem is already known to the Pixelmon community for some time which provides one with many possible solutions but none of these fixed the problem for our server.
I then tried out different things ending up resolving the problem with: Not using BungeeCord.

Since, as you all know, BungeeCord is somehow a must-have for Minecraft servers we can not use this work-around. I now would like to ask someone familiar with BungeeCord internals to take a look into this.

---

Some information about the setup:

BungeeCord version: **git:BungeeCord-Bootstrap:1.9-SNAPSHOT:ec48077:1157**  
Forge version: **11.15.1.1902-1.8.9**  
Pixelmon version: **4.2.7**  

Sadly I can not provide any further information about the problem since there're no errors or warnings displayed by bungee/the server or the client.

**Comment by Janmm14** [comment]
Is there any action needed by the player that makes the fight go on? Or does it usually wait a certain amount of time and then goes on?

**Comment by MarkL4YG** [comment]
@Janmm14 No, the fight will not continue. You have to use /endbattle or suicide and reconnect.

**Comment by i9hdkill** [comment]
Does this still happen with Pixelmon 4.3/5.0 and latest BungeeCord?

**Comment by MarkL4YG** [comment]
Will test tomorrow

**Comment by MarkL4YG** [comment]
Sorry for the delay.
The bug doesn't seem to be fixed.
I tested with BungeeCord #1189 and Pixelmon 4.3 Beta 7.

**Comment by i9hdkill** [comment]
We run Pixelmon 5.0 B12 since a week with 50 player+ and are not experiencing this problem.
Guess it's network related. Please open a help thread either in the pixelmon forums or sponge forums if you are using sponge.

**Comment by MarkL4YG** [comment]
We'll test with Pixelmon 5.0 maybe it's fixed for us too.

**Comment by Cristichi** [comment]
The bug is still going on

**Comment by Malachiel87** [comment]
still present on current version

**Comment by Janmm14** [comment]
For mods it might be better to try out the bungee fork "Waterfall" and enable its option "disable entity rewrite" or how its called. This increases general mod compatibility and might fix this issue as well.
When you use the Bungeecord fork Waterfall, please be aware that you do not get support on this issue tracker / from spigotmc anymore and you have to use Waterfall's issue tracker.

**Comment by Marcos666** [comment]
I'm playing alone. Without people, and i can't leave the battle, the thing is, sometimes i can write /endbattle, and sometimes, i just can open the chat, but not writing. I need to close the game? ._.
