### ISSUE TITLE
Bungeecord Error cannot start

### ISSUE THREAD

**Issue by LethalSh0tt** [SpigotMC/BungeeCord#1921]
Description
I could never start my bungeecord unless I take my config, copy it, then delete the config, then start bungeecord, then end it, then paste it, and then start it. If I end it I would have to repeat this step, here is the error I get when starting it.
09:29:43 [SEVERE] Exception in thread "main"
09:29:43 [SEVERE] org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
09:29:43 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
09:29:43 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
09:29:43 [SEVERE] at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
09:29:43 [SEVERE] at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
09:29:43 [SEVERE] at net.md_5.bungee.conf.Configuration.load(Configuration.java:65)
09:29:43 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
09:29:43 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:111)
09:29:43 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
09:29:43 [SEVERE] Caused by: java.nio.charset.MalformedInputException: Input length = 1
09:29:43 [SEVERE] at java.nio.charset.CoderResult.throwException(Unknown Source)
09:29:43 [SEVERE] at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
09:29:43 [SEVERE] at sun.nio.cs.StreamDecoder.read(Unknown Source)
09:29:43 [SEVERE] at java.io.InputStreamReader.read(Unknown Source)
09:29:43 [SEVERE] at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123)
09:29:43 [SEVERE] at java.io.Reader.read(Unknown Source)
09:29:43 [SEVERE] at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184)
09:29:43 [SEVERE] ... 7 more
My bungeecord is up to date and it works perfectly. Its just annoying for this to happen.
NOTE: Here is the bungeecord version

This server is running MCrafterz version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:d99f813:80 by md_5 Protocol support for 1.7.x by Zartec, ghac and I9hdkill9

**Comment by md-5** [comment]
Invalid config. Make sure it is saved in UTF-8

**Comment by LethalSh0tt** [comment]
I always save it in UTF-8 but it manages to always go to ANSI
