### ISSUE TITLE
InetAddress.getByName() extremely slow

### ISSUE THREAD

**Issue by ItsHarry** [SpigotMC/BungeeCord#1922]
[`InetAddress.getByName( uri.getHost() );`](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/http/HttpClient.java#L65) takes 4.9 seconds to complete on average on my machine according to Java profiling. It seems abnormally long, I tried asking on Stackoverflow but have not figured out the cause yet.

In any case, shouldn't this method be called asynchronously in BungeeCord? Forgive me if it is already asynchronous, I am not familiar with how Netty works. If it isn't however, wouldn't it cause the Netty thread to be blocked impacting gameplay performance?

**Comment by Janmm14** [comment]
It should mainly block due to dns lookups, which shouldn't often take more than 1s normally.
It shouldn't block always as java has a dns cache.
Also the httpclient is not used on many different hosts. Maybe the first join might take more time.

**Comment by ItsHarry** [comment]
Yes, but on my machine it takes 4.9 seconds.

Most people have Java DNS cache disabled as it causes issues when Mojang session servers changes IP (it happens quite often)

The host is only cached by Bungee for 1 minute, which means every minute there could be another lag spike, if it is indeed not asynchronous.

**Comment by Janmm14** [comment]
Then don't disable the cache and hope mojang stays up.

Maybe change the dns server to a faster one.

**Comment by ItsHarry** [comment]
"hoping Mojang stays up" is the dumbest thing you can do... Java DNS cache is set to cache forever by default. If the Mojang servers ever change IP, which they do frequently, you are forced to manually restart Bungee.

**Comment by md-5** [comment]
This is a misconfiguration on your end.
Normal call time for this method is in the order of 1ms:

```
╰─$ time host sessionserver.mojang.com
sessionserver.mojang.com has address 54.192.133.172
host sessionserver.mojang.com  0.01s user 0.00s system 24% cpu 0.049 total
```

**Comment by ItsHarry** [comment]
Still trying to figure out what is causing it, but thanks for clarifying
