### ISSUE TITLE
BungeeCord crash bots

### ISSUE THREAD

**Issue by SyqlexxPI** [SpigotMC/BungeeCord#1930]
http://hastebin.com/sunewavehe.avrasm

**Comment by md-5** [comment]
Version?

**Comment by SyqlexxPI** [comment]
> This server is running BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:a605c1a:1175

**Comment by Black-Hole** [comment]
This PR will prevent the log spam:
https://github.com/SpigotMC/BungeeCord/pull/1515
