### ISSUE TITLE
ClassNotFoundException YamlConfiguration - b#1176

### ISSUE THREAD

**Issue by jeremy100** [SpigotMC/BungeeCord#1931]
16:06:47 [INFORMACIÓN] [/127.0.0.1:52798] <-> InitialHandler has connected
16:06:47 [GRAVE] java.lang.ClassNotFoundException: org.bukkit.configuration.file.YamlConfiguration
16:06:47 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
16:06:47 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
16:06:47 [GRAVE] 	at java.lang.ClassLoader.loadClass(Unknown Source)
16:06:47 [GRAVE] 	at java.lang.Class.forName0(Native Method)
16:06:47 [GRAVE] 	at java.lang.Class.forName(Unknown Source)
16:06:47 [GRAVE] 	at skinsrestorer.shared.utils.YamlConfig.reload(YamlConfig.java:146)
16:06:47 [GRAVE] 	at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:48)
16:06:47 [GRAVE] 	at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:191)
16:06:47 [GRAVE] 	at skinsrestorer.bungee.listeners.LoginListener.onLogin(LoginListener.java:23)
16:06:47 [GRAVE] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
16:06:47 [GRAVE] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
16:06:47 [GRAVE] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
16:06:47 [GRAVE] 	at java.lang.reflect.Method.invoke(Unknown Source)
16:06:47 [GRAVE] 	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
16:06:47 [GRAVE] 	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
16:06:47 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
16:06:47 [GRAVE] 	at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:525)
16:06:47 [GRAVE] 	at net.md_5.bungee.connection.InitialHandler.access$600(InitialHandler.java:62)
16:06:47 [GRAVE] 	at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:371)
16:06:47 [GRAVE] 	at net.md_5.bungee.connection.InitialHandler$4.done(InitialHandler.java:352)
16:06:47 [GRAVE] 	at net.md_5.bungee.api.event.AsyncEvent.postCall(AsyncEvent.java:38)
16:06:47 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:378)
16:06:47 [GRAVE] 	at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:378)
16:06:47 [GRAVE] 	at net.md_5.bungee.protocol.packet.LoginRequest.handle(LoginRequest.java:39)
16:06:47 [GRAVE] 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
16:06:47 [GRAVE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
16:06:47 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
16:06:47 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
16:06:47 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:219)
16:06:47 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:616)
16:06:47 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:457)
16:06:47 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:417)
16:06:47 [GRAVE] 	at net.md_5.bungee.protocol.LegacyDecoder.decode(LegacyDecoder.java:37)
16:06:47 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
16:06:47 [GRAVE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
16:06:47 [GRAVE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
16:06:47 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
16:06:47 [GRAVE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
16:06:47 [GRAVE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
16:06:47 [GRAVE] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
16:06:47 [GRAVE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
16:06:47 [GRAVE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
16:06:47 [GRAVE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
16:06:47 [GRAVE] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
16:06:47 [GRAVE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
16:06:47 [GRAVE] 	at java.lang.Thread.run(Unknown Source)
16:06:49 [GRAVE] java.lang.ClassNotFoundException: org.bukkit.configuration.file.YamlConfiguration
16:06:49 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
16:06:49 [GRAVE] 	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
16:06:49 [GRAVE] 	at java.lang.ClassLoader.loadClass(Unknown Source)
16:06:49 [GRAVE] 	at java.lang.Class.forName0(Native Method)
16:06:49 [GRAVE] 	at java.lang.Class.forName(Unknown Source)
16:06:49 [GRAVE] 	at skinsrestorer.shared.utils.YamlConfig.reload(YamlConfig.java:146)
16:06:49 [GRAVE] 	at skinsrestorer.shared.storage.SkinStorage.removePlayerSkin(SkinStorage.java:48)
16:06:49 [GRAVE] 	at skinsrestorer.shared.storage.SkinStorage.getPlayerSkin(SkinStorage.java:191)
16:06:49 [GRAVE] 	at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:213)
16:06:49 [GRAVE] 	at skinsrestorer.bungee.SkinApplier$1.run(SkinApplier.java:23)
16:06:49 [GRAVE] 	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
16:06:49 [GRAVE] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
16:06:49 [GRAVE] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
16:06:49 [GRAVE] 	at java.lang.Thread.run(Unknown Source)
16:06:49 [INFORMACIÓN] [Terachnos] <-> ServerConnector [Conector] has connected

**Comment by Janmm14** [comment]
Error from SkinsRestorer, not from BungeeCord.
The plugin tries to use Bukkit's configuration api on BungeeCord. Report to the author or update your version.

**Comment by i9hdkill** [comment]
As mentioned above, not BungeeCord's fault.
