### ISSUE TITLE
Commit "Don't handle upstream packets if no server connected" breaks forge ip forwarding

### ISSUE THREAD

**Issue by i9hdkill** [SpigotMC/BungeeCord#1932]
This commit:
https://github.com/SpigotMC/BungeeCord/commit/3a0b0aa116310add15ef0b2d77be8b76a1564adf
breaks ip forwarding on sponge (forge) servers.

How to reproduce it.
Setup BungeeCord + Spongepls (plugin that enables general ip forwarding support for sponge)
https://forums.spongepowered.org/t/spongepls-bungeecord-forge-support/9891
set ip forwarding to true.

Setup a clean spongeForge 1.10.2 server with BungeeCord and ipforwarding enabled.
Place the spongeforge server as a prioritylist server.

Try to connect with a forge 1.10.2 client. 
You will get a timeout.

Before that commit, you can connect just fine.

**Comment by md-5** [comment]
That plugin hacks into BungeeCord and bypasses the API.
Reopen this ticket if there is an issue with an untampered BungeeCord.

**Comment by MJRLegends** [comment]
@md-5 it happens without having Spongepls see https://github.com/HexagonMC/BungeeCord/issues/67#issuecomment-239148510

**Comment by Time6628** [comment]
This occurs with just vanilla forge and bungeecord as well.

**Comment by md-5** [comment]
Update
