### ISSUE TITLE
Bungee Config API Error

### ISSUE THREAD

**Issue by JokHornsby** [SpigotMC/BungeeCord#1934]
When getting keys from a configuration section using the bungee API, if the keys are integers the call throws an error:

```
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
    at some.call.to.getkeys(SomeClass.java:1)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169)
    at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

The stack trace doesn't seem to go back any further.

An example configuration file would be:
```
someKey:
    1: 1
    2: 2
    3: 3
    4: 4
```

An example getKeys call:

```
Configuration someKeySection = config.getSection("someKey");
for(String key : someKeySection.getKeys())
{
    System.out.println(key);
}
```

I believe that even though the underlying HashMap in the Configuration class is has a String key some unsafe code is parsing and putting the keys as an Integer instead of String, and when you try to get the key (or use it in a get lookup) as a string, it does not work as intended (searches return nothing and keySet throws an error).

It seems this code is in the ConfigurationProvider (in this case, YamlConfiguration) in the load method, as I see an unsafe cast between an object and a map, with no enforcement of types.

Thanks in advance.

**Comment by Janmm14** [comment]
As a workaround for numeric keys put `"` or `'` around them, like `"1": 1`, as far as I know, this is equal in bukkit's implementation.

**Comment by JokHornsby** [comment]
Oh wow I don't know how I didn't think of this. Thanks for the workaround. 

Obviously this is still a bug that could do with fixing though.
