### ISSUE TITLE
Error with a packet.

### ISSUE THREAD

**Issue by RichTheLord** [SpigotMC/BungeeCord#1935]
In my plugin (of spigot) I've added a listener with protocollib, so when I call the packet in game it needs to fill the player inventory (craft section) and then the server kicks the player and shows this error in bungeecord:

Packet: PacketPlayInClientCommand

If this is my fault help me how to fix it please.

[ -- >ERROR <-- ](http://hastebin.com/cifujopase.avrasm)

**Comment by md-5** [comment]
This is not a Bungee bug unless proven otherwise.

**Comment by Janmm14** [comment]
@RichTheLord 
A note to Multicraft users: Please go to the real log files as Multicraft likes skipping some lines of a stack trace (thats how the error is called).

**Comment by RichTheLord** [comment]
But, so why when I use some versions it works (if I use the latest it doesn't work).

If I use this one: [LINK](https://www.dropbox.com/s/a004rwm5lzwm3dj/Bungee.jar?dl=0) it works.

**Comment by TheDiamondYT1** [comment]
@RichTheLord Why did you make text saying `LINK` for the link, instead of turning the text [this one]() into a link?

**Comment by RichTheLord** [comment]
That's not important ¬¬
