### ISSUE TITLE
Make a Configuration#contains method

### ISSUE THREAD

**Issue by KingFaris10** [SpigotMC/BungeeCord#1936]
Unless I'm missing something, I'm confused as to why the 'Configuration' class does not contain a 'contains(String key)' method. I'd rather not use Configuration#getKeys().contains(String key) as every time getKeys() is used, it makes a copy of the array, whereas a contains() method would directly fetch from the Map. Also, you're not able to do getKeys().contains("Path.Key"), i.e. It doesn't support dots.

**Comment by MylesIsCool** [comment]
You could just use Configuration#get(String path, T def)

eg. Configuration.get("key",null) == null

Would work fine

**Comment by md-5** [comment]
Thats because dots are the path separator.

**Comment by KingFaris10** [comment]
I also thought about that option, but again, it's a bit too much just to see if a Configuration contains a path.

**Comment by KingFaris10** [comment]
@md-5 Right, so getKeys() wouldn't work hence I think contains() would be a nice feature. Makes it also easier for Bukkit plugin developers who want to do BungeeCord plugin development too.

**Comment by md-5** [comment]
Not opposed to adding a method, but in all probability it would just return get(path,null) !=null

**Comment by KingFaris10** [comment]
Even if it does that, I think it makes the API look better and makes it easier for Bukkit plugin developers with little BungeeCord experience,, and doesn't cause any damage (a few bytes/kilobytes more in file size).

**Comment by xxyy** [comment]
After all, a well-named method makes the intention clearer, making the code
easier to read.

if(config.contains(path)) is definitely easier to read and cleaner than
if(config.get(path, null) != null).

-- Above message was sent from my mobile phone. There may and will be all
kinds of errors included.
