### ISSUE TITLE
Error when we have 2 BungeeCord servers

### ISSUE THREAD

**Issue by Yoann166** [SpigotMC/BungeeCord#1939]
Hello,

I have 2 BungeeCord servers (BungeeCord 1 and BungeeCord 2, server 1 connects to server 2).

![ss 2016-08-19 at 10 54 58](https://cloud.githubusercontent.com/assets/1645101/17823347/5367c610-665c-11e6-8b2d-88efa8ed7ae5.png)

When I use BungeeCord >= 1171 versions, I'm kicked with this error: "IndexOutOfBoundsException: readerIndex(1) + length(66) exceeds writerIndex(64): UnpooledHeapByteBuf(ridx: 1, widx: 64, cap: 64) @ io.netty.buffer.AbstractBytesBuf:1179" when I want to connect on BungeeCord server 2 (BungeeCord server 1 => BungeeCord server 2). There is this error on BungeeCord server 1: http://pastebin.com/VHX1HjfJ

No problem with <= 1170 versions.

Can you fix this please?

Thanks.

**Comment by Janmm14** [comment]
Simply don't point 1 bungee to another, its useless.

**Comment by md-5** [comment]
This is not a supported configuration - never has been, never will be.
That being said I did test this and cannot reproduce.

**Comment by md-5** [comment]
I've fixed the bug, but I've also prevented Bungee from connecting to itself (there is no reason why you should do this - can you please explain why you are?).

**Comment by Yoann166** [comment]
We need this feature because we have 2 dedicated servers with 2 different staff (one BungeeCord server for one staff).

@md-5, thank you for your help. But, there is again a issue. Indeed, now with version 1181 (http://ci.md-5.net/job/BungeeCord/1181/), I'm kick with this error:

![ss 2016-08-21 at 01 03 09](https://cloud.githubusercontent.com/assets/1645101/17834340/cfe32c68-673b-11e6-82f1-9bd2cbc6fea7.png)

And, into console, there is this error: http://pastebin.com/LdG77Agh

Can you fix this please?

**Comment by md-5** [comment]
No, this was done on purpose.

It makes no sense to connect Bungee to itself. You just introduce lag, reliability issues, command issues, configuration complexity etc. Reconfigure your Bungee so that both Bungees point to the servers, not eachother.

**Comment by Yoann166** [comment]
Unfortunately we can not do otherwise now. However, I will take your advice and change the functioning (configuration, and remove BungeeCord-BungeeCord connetion) in the future.

Meanwhile, can you take a little of your time to fix this bug?
So, can you add the possibility to allow BungeeCord-BungeeCord connection please? This is important for me for not stuck with an older version (1170).

**Comment by Yoann166** [comment]
Unfortunately we can not do otherwise now. However, I will take your advice and change the functioning (configuration, and remove BungeeCord-BungeeCord connetion) in the future.

@md-5 Meanwhile, can you take a little of your time to fix this bug?
So, can you add the possibility to allow BungeeCord-BungeeCord connection please (even if it's deprecated)? It's important for me to don't be stuck with an older version (1170).

**Comment by Lothean** [comment]
Hello
I do not usually make requests to mods authors because they are already working hard and i'm quit quiet usually, but I really want this to be back again because it is very useful to my whole mini-games setup.
Is there any way to bring it back ?

**Comment by caoli5288** [comment]
Please unblock this. It's not necessary to prevent it. It is useful at some point.

**Comment by caoli5288** [comment]
@Yoann166 This is a fork fixed it. ()[https://github.com/caoli5288/waterfall]

**Comment by md-5** [comment]
https://git.io/v6d9G
