### ISSUE TITLE
Unable to join forge server with modded client

### ISSUE THREAD

**Issue by Tencao** [SpigotMC/BungeeCord#1941]
So, I created a clean bungee server, and a clean sponge server (with bungee connection and ipforward enabled for both), however, I bungee refuses to properly connect me to the server.

Minecraft version - 1.10.2
Sponge version - 1.10.2-2052-5.0.0-BETA-1678
Forge version - 1.10.2-12.18.1.2052
Bungee version - Build 1181

With IP Forwarding on for both -

> 09:54:25 [INFO] [/_IPRemoved_] <-> InitialHandler has connected
> 09:54:26 [INFO] [Tencao] <-> ServerConnector [Hub] has connected
> 09:54:26 [INFO] [Tencao] <-> ServerConnector [Hub] has disconnected
> 09:54:56 [WARNING] [Tencao] -> UpstreamBridge - read timed out
> 09:54:56 [INFO] [Tencao] disconnected with: ReadTimeoutException : null
> 09:54:56 [INFO] [Tencao] -> UpstreamBridge has disconnected

With IP Forwarding off for both - 

> 09:58:57 [INFO] [/_IPRemoved_] <-> InitialHandler has connected
> 09:58:58 [INFO] [Tencao] <-> ServerConnector [Hub] has connected
> 09:58:58 [FINE] [START Server -> Bungee][SENDING: ServerHello]
> 09:58:58 [FINE] [HELLO Client <- Bungee][RECEIVED: ServerHello]
> 09:58:58 [INFO] Netty is not using direct IO buffers.
> 09:58:58 [SEVERE] [Tencao] -> UpstreamBridge - encountered exception
> java.lang.NullPointerException
> 	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:93)
> 	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:85)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:572)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:513)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:427)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:399)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
> 	at java.lang.Thread.run(Unknown Source)
> 09:58:58 [INFO] [Tencao] disconnected with: §fNullPointerException : null @ net.md_5.bungee.connection.UpstreamBridge:93
> 09:58:58 [INFO] [Tencao] -> UpstreamBridge has disconnected
> 09:59:28 [INFO] [Tencao] <-> ServerConnector [Hub] has disconnected

Edit - Just for confirmation, the config for the server isn't wrong, as when IP forwarding is off, it does show on the server console that it attempted to connect

> [09:59:28] [Netty Server IO #4/WARN] [io.netty.channel.DefaultChannelPipeline]:
> An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
> io.netty.handler.timeout.ReadTimeoutException
> [09:59:28] [Server thread/INFO]: Tencao lost connection: Disconnected
> [09:59:28] [Server thread/INFO]: Tencao left the game

**Comment by kashike** [comment]
https://github.com/SpigotMC/BungeeCord/pull/1678

**Comment by Tencao** [comment]
Would that cause issues with no ip-forwarding though, as I disabled it on both sponge and forge, hence the two errors above.

**Comment by md-5** [comment]
No.

There are however plugins that enable IP forwarding with Sponge.
I don't however have any sponge or forge instances to test.
