### ISSUE TITLE
Unable to make Bungee-Bungee connection

### ISSUE THREAD

**Issue by Lothean** [SpigotMC/BungeeCord#1943]
Hi,
Since lasts updates, i'm not able to do Bungee-Bungee connections, which was very useful for me and my Mini-Games setup.
My configurations stayed the sames, and it comes with a nice error, saying that the proxy cannot connect to itself...
Can you please fix that if possible ?

**Comment by electronicboy** [comment]
Connecting bungeecord to itself is just bad practice, If you wanna maintain this horrible behavior, I'd suggest sticking to an older build.

**Comment by Black-Hole** [comment]
Have a look at the discussion in #1939

**Comment by Lothean** [comment]
Just looked, and there is no answer to my issue.

**Comment by Lothean** [comment]
Ok, problem solved.

**Comment by Lothean** [comment]
Well, I steel need Bungee to Bungee connection and I think that the md-5's idea of blocking theses is completely silly. If not resolved, I think I will solve that on my own.

**Comment by electronicboy** [comment]
The decision to block these types of connections is noted on the linked issue as causing problems, and as noted; in general, it is just a completely bad idea, and I really doubt that the decision made to block these types of connections will be reverted, it's completely unsupported and in general just a bad idea.

If you wanna do this, maintain your own fork that re-enable 'support' for this.

**Comment by Lothean** [comment]
I actually just done this.

**Comment by Lothean** [comment]
Et personnellement on s'en branle de ces problèmes, on fait ce qu'on veux pd.

**Comment by Lothean** [comment]
kouchikari
