### ISSUE TITLE
[possible enhancement] disconnect event schedule

### ISSUE THREAD

**Issue by franciscopaniskaseker** [SpigotMC/BungeeCord#1944]
About ./proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java code, do we still have wait 500ms to send disconnect packet?

I am concerned about this 

(1) Will run new thread only to disconnect (performance)
(2) Allow client to send unexpected packets after disconnection (security)
(3) bungee taking care about client side (which seems wrong) consuming resources (seems more wrong)

**Comment by Janmm14** [comment]
> (3) bungee taking care about client side (which seems wrong) consuming resources (seems more wrong)
No, bungee takes care of displaying the kick message correctly because the client has some issues. Else it would just display: Disconnected.

**Comment by franciscopaniskaseker** [comment]
Agree with you about what bungee take care, but the question is we still need that with recent clients?

**Comment by kamcio96** [comment]
#1874

**Comment by md-5** [comment]
Unless demonstrated otherwise it's still a client issue. 1) isn't applicable as it doesn't make a new thread, 2) hardly seems an issue, 3) yes - if thats whats required to handle the client properly then it should be done.
