### ISSUE TITLE
CPU usage peaking during Garbage Collector cycle

### ISSUE THREAD

**Issue by prajniak** [SpigotMC/BungeeCord#1946]
Good afternoon,

I am system administrator on network with pixelmon 3.5.2 and we are running into issues, which seems to indicate memory leak. The CPU goes above 200% on "top" while Garbage Collector tries to release RAM but when it does it, it is a usually very small amount. This problem occurred since upgrading from 1.6 to 1.7. 

Adding more RAM for Bungee just delays the problem. I have tried to removing plugins from BungeeCord if they are they are the cause of memory leak. 

We are running 2 bungees with redisbungee and using HexagonMc bungee. Currently we have 800 players and one bungee handles 400 players approx.  I have ran JProfiler on Bungee to further determine cause. I also tried to use different GC like G1 or CMS but it did not helped at peak. 
Attaching pictures from JProfiler under post with default GC. 

The plugins we are using - MultiLobby, RedisBungee, BetterServerJoin, BungeeKick, ProxyPipe-BungeeCord, UltimateFriends, BungeeRTK. Currently we restart both bungees 24 hours.

I already tried to contact Hexagonmc developer and he advised posting issue here cause of issue occurring also on original BungeeCord.   If you could provide some advice or any help, I would be very grateful.

Have a nice day.

Best regards
Patrik Rajniak

http://i.imgur.com/p51dJFS.png
http://i.imgur.com/vLA99S0.png
http://i.imgur.com/Ta12hTI.png

**Comment by kamcio96** [comment]
This is normal action. Java GC need CPU. Can you paste your JVM flags?

**Comment by prajniak** [comment]
I understand that GC needs CPU but the peaks increase in intensity. It gets to spike lags which can last on server for 5-8 seconds and happen on every GC cycle. During peak time when bungee runs for 20 hours, the spike lags occur every 25 seconds and the game becomes unplayable. This did not happen on 1.6

Here are JVM flags 

java -Xms20480M -Xmx20480M -Djline.terminal=jline.UnsupportedTerminal -XX:MaxGCPauseMillis=200 -XX:MaxPermSize=256m -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -jar BungeeCord.jar

**Comment by kamcio96** [comment]
I suggest use: 
```java -Xmx2048M -Xms256M -Djline.terminal=jline.UnsupportedTerminal -XX:MaxPermSize=256m -XX:+AggressiveOpts -XX:+UseFastAccessorMethods -jar BungeeCord.jar```

GC will run often but less

**Comment by prajniak** [comment]
I tried to lower size but the RAM got eaten that much faster. Also tried to remove some flag I have read that recommended allocation is 1 GB but allocating 20 GB helps to delay the problem until next restart. 

I tried many versions of JVM flags, these works best for me right now. I have also tried to check on every GC cycle and there were cases when GC would run 13 times during 1 one second because it could not release memory. The problem is that bungee currently can "eat" 30 GB and GC can release less than 5%. I also tried use flag on CMS which made GC release memory regularly not when only needed.

**Comment by i9hdkill** [comment]
Allocating that much ram WILL lag your server. Try less and remove all plugins. It's fine to run bungee without any xms or xmx flag.

**Comment by prajniak** [comment]
Alright, I will try to do it. Do you recommend setting some specific GC or some specific flags? I will try to use flags kamcio96 suggested if nothing.

**Comment by minecrafter** [comment]
@prajniak You should typically need no more than 4GB at worst.
