### ISSUE TITLE
Deadlock?

### ISSUE THREAD

**Issue by ItsHarry** [SpigotMC/BungeeCord#1948]
Happened twice now, here is thread dump:
http://paste.md-5.net/bapiviqowu.avrasm

Running BungeeCord build 1184.

Program completely froze and did not accept new connections until I force killed it after an hour.

**Comment by yawkat** [comment]
Looks more like a lot of concurrent calls to .execute to me, since one thread is actually in putVal. You appear to have yourkit attached, what does it say in its deadlock detection?

**Comment by ItsHarry** [comment]
I did not check it unfortunately

**Comment by md-5** [comment]
Please update

**Comment by ItsHarry** [comment]
Will do, will report back if it happens again
