### ISSUE TITLE
Can't get it to work :(

### ISSUE THREAD

**Issue by jollesnaas** [SpigotMC/BungeeCord#1949]
I get this error:

> 15:47:55 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based nati
> ve cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl in
> stalled.
> 15:47:55 [INFO] Using standard Java compressor. To enable zero copy compression,
>  run on 64 bit Linux
> 15:47:55 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHO
> T:0581e49:1189
> 15:47:56 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_a
> lert.jar, provider=JenkinsModuleSource())
> 15:47:56 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_fi
> nd.jar, provider=JenkinsModuleSource())
> 15:47:56 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_li
> st.jar, provider=JenkinsModuleSource())
> 15:47:56 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_se
> nd.jar, provider=JenkinsModuleSource())
> 15:47:56 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_
> server.jar, provider=JenkinsModuleSource())
> 15:47:56 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\
> reconnect_yaml.jar, provider=JenkinsModuleSource())
> 15:47:56 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.10-SNA
> PSHOT:0581e49:1189 by SpigotMC
> 15:47:56 [INFO] Loaded plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:0581e4
> 9:1189 by SpigotMC
> 15:47:56 [INFO] Loaded plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:05
> 81e49:1189 by SpigotMC
> 15:47:56 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:0581
> e49:1189 by SpigotMC
> 15:47:56 [INFO] Loaded plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:0581e4
> 9:1189 by SpigotMC
> 15:47:56 [INFO] Loaded plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:0581e4
> 9:1189 by SpigotMC
> 15:47:56 [SEVERE] Exception in thread "main"
> 15:47:56 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast
> to java.util.Map
> 15:47:56 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.j
> ava:195)
> 15:47:56 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.j
> ava:92)
> 15:47:56 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:259)
> 15:47:56 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLaunc
> her.java:55)
> 15:47:56 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

This is my config:

> ip_forward: false
> network_compression_threshold: 256
> stats: 9dae2843-d227-405e-9e69-d2cb9754c602
> permissions:
>   default:
>   - bungeecord.command.server
>   - bungeecord.command.list
>   admin:
>   - bungeecord.command.alert
>   - bungeecord.command.end
>   - bungeecord.command.ip
>   - bungeecord.command.reload
> groups:
>   md_5:
>   - admin
> servers: 
> lobby 
> motd '&1IkIsJolle Minecraft Server' 
> address localhost:50001 
> restricted false 
> sw
> motd '&1IkIsJolle Skywars Server'
> address ***.***.92.167:40858 
> restricted false
> timeout: 30000
> listeners:
> - query_port: 25577
>   motd: '&1IkIsJolle MC Server'
>   priorities:
>   - lobby
>   bind_local_address: true
>   tab_list: GLOBAL_PING
>   query_enabled: false
>   host: 0.0.0.0:25565
>   forced_hosts:
>     pvp.md-5.net: pvp
>   max_players: 1
>   tab_size: 60
>   ping_passthrough: false
>   force_default_server: true
> player_limit: -1
> online_mode: false
> log_commands: false
> disabled_commands:
> - disabledcommandhere
> connection_throttle: 4000

What to do?

**Comment by electronicboy** [comment]
Delete your config file and try again WITHOUT breaking the formatting of the file.

**Comment by jollesnaas** [comment]
@electr

**Comment by jollesnaas** [comment]
I didn't want that


But It does work now

**Comment by i9hdkill** [comment]
Yes, see electronicboy's comment:)

**Comment by electronicboy** [comment]
If it's working, no, you're fine.
If it's not working, the error is stating that you've screwed up the config file.
Yaml is highly sensitive in regards to how it's formatted.

**Comment by jollesnaas** [comment]
Thanks! I messed something up! Now its working!
