### ISSUE TITLE
Lag/Freeze

### ISSUE THREAD

**Issue by LTDJ** [SpigotMC/BungeeCord#1951]
I have 300-400 players online and my bungeecord many lags at end of the day... I use your BungeeCord.

**Comment by MiniDigger** [comment]
we can't help you if you don't provide any information. 
are you using any bungee plugins that could cause it?
how do you notice the lag? are you sure it's bungee lagging and not the underlying spigot/bukkit servers?
most likely your machine that is running bungee is just not capable of running 400 players.

**Comment by md-5** [comment]
No version, no startup script, no server specifications, no console log.
