### ISSUE TITLE
Bungeecord Server 

### ISSUE THREAD

**Issue by KucRyans** [SpigotMC/BungeeCord#1952]
Whilst trying to connect to a server I would either get a 
"You are already connected to this server" message or be redirected
to another server.

**Comment by Trickster489** [comment]
This is a normal Bungee issue. Try disconnecting and reconnecting again, if that doesn't work relaunch Minecraft.

**Comment by i9hdkill** [comment]
If your issue still persists, look for help in our BungeeCord forums.
https://www.spigotmc.org/forums/bungeecord-help.70/
