### ISSUE TITLE
Ip forwarding not enabled

### ISSUE THREAD

**Issue by ChetwyndKid** [SpigotMC/BungeeCord#1953]
Im confused with this, Im running a Pixelmon server running Pixelmon 3.5.1.

For most players they can connect normally, But with a few players they get the error that IP forwarding is not enabled and should be enabled in the config, Which it is.

Is there a fix for this?

**Comment by i9hdkill** [comment]
Block the cauldron server port to prevent them from joining the cauldron server directly. (Very high security risk)
They only should join through your proxy ip.

**Comment by ChetwyndKid** [comment]
Sorry, Im new at this how would I do that?

**Comment by i9hdkill** [comment]
It's all in the wiki I posted earlier. That's the direct link:
https://www.spigotmc.org/wiki/firewall-guide/
