### ISSUE TITLE
Native compress slower then Java compress

### ISSUE THREAD

**Issue by caoli5288** [SpigotMC/BungeeCord#1964]
```Bash
Running net.md_5.bungee.NativeZlibTest
Testing: net.md_5.bungee.jni.zlib.NativeZlib@3c09711b
Took: 468ms
Testing: net.md_5.bungee.jni.zlib.JavaZlib@5cc7c2a6
Took: 458ms
```
Is it necessary use of native compressor?

**Comment by caoli5288** [comment]
A `perf` report here. It use lot of kernel-space time.
![20161005140258](https://cloud.githubusercontent.com/assets/3120587/19102709/f4d4a082-8b04-11e6-8cfc-d4dfa212698b.png)

**Comment by md-5** [comment]
You can use it if you want to; otherwise use the java property to disable native code. It is a thin wrapper around OpenSSL only.
