### ISSUE TITLE
Fallback error

### ISSUE THREAD

**Issue by Zortex04** [SpigotMC/BungeeCord#1965]
Hey Everyone so recently i made a bungeecord server but now everyime i join it gives me this error

Could not connect to default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

Ive tried removing the fallback server but it keeps going back agian? please help

**Comment by md-5** [comment]
The servers you have configured are not reachable.

**Comment by Zortex04** [comment]
Another thing, every time i delete the fallback server it comes back

**Comment by Janmm14** [comment]
Stop the server. Edit the config. Enable the config. Or use /greload
