### ISSUE TITLE
Cannot connect to my bungeecord server!!

### ISSUE THREAD

**Issue by SamsoomYT** [SpigotMC/BungeeCord#1966]
I cannot login to my bungeecord server!! This is the cmd log:

18:49:02 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
18:49:02 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
18:49:02 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:0581e49:1190
18:49:02 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
18:49:02 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
18:49:02 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
18:49:02 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
18:49:02 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
18:49:02 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
18:49:02 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Loaded plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Loaded plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Loaded plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Loaded plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [WARNING] Forced host server pvp is not defined
18:49:02 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Enabled plugin cmd_find version git:cmd_find:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Enabled plugin cmd_server version git:cmd_server:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Enabled plugin cmd_send version git:cmd_send:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Enabled plugin cmd_list version git:cmd_list:1.10-SNAPSHOT:0581e49:1190 by SpigotMC
18:49:02 [INFO] Listening on /0.0.0.0:25565
18:50:09 [INFO] [/192.168.1.1:51095] <-> InitialHandler has connected
18:50:10 [INFO] [/127.0.0.1:51099] <-> InitialHandler has connected
18:50:12 [INFO] [/192.168.1.1:51102] <-> InitialHandler has connected
18:50:14 [INFO] [losamaw] <-> ServerConnector [lobby] has connected
18:50:14 [INFO] [losamaw] <-> ServerConnector [lobby] has disconnected
18:50:34 [INFO] [losamaw] -> UpstreamBridge has disconnected
18:56:44 [INFO] [/192.168.1.1:51244] <-> InitialHandler has connected
18:56:45 [INFO] [/127.0.0.1:51248] <-> InitialHandler has connected
18:56:47 [INFO] [/192.168.1.1:51251] <-> InitialHandler has connected
18:56:49 [INFO] [losamaw] <-> ServerConnector [lobby] has connected
18:56:49 [INFO] [losamaw] <-> ServerConnector [lobby] has disconnected
18:57:09 [INFO] [losamaw] -> UpstreamBridge has disconnected

This is my Bungeecord Config:

https://gyazo.com/d7883b3973343da4738fd356bafac5de

**Comment by SamsoomYT** [comment]
PLS HELPPPPP

**Comment by kamcio96** [comment]
Server log? pls use pastebin or git markdown

**Comment by SamsoomYT** [comment]
Which one? Bungeecord Server or lobby server?

**Comment by Janmm14** [comment]
lobby server

**Comment by veemorrison** [comment]
I'm not sure if the issue tracker is the right place for reports, this isn't a bug. You'd probably get more advice on the official forum.

**Comment by i9hdkill** [comment]
See post above
