### ISSUE TITLE
Error on Startup

### ISSUE THREAD

**Issue by ChimpGamer** [SpigotMC/BungeeCord#1973]
13:55:24 [SEVERE] Exception in thread "main"
13:55:24 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
13:55:24 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:237)
13:55:24 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:78)
13:55:24 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:259)
13:55:24 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
13:55:24 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by i9hdkill** [comment]
You broke your config.
Delete it and restart BungeeCord to regenerate it.
Don't use Tabs and stay to the yml formatting.
