### ISSUE TITLE
Send Command World Arguement

### ISSUE THREAD

**Issue by GershonR** [SpigotMC/BungeeCord#1984]
Is it possible to add another optional argument in the send command, to send a user/all to a specific world in the given server?

**Comment by MylesIsCool** [comment]
This would require modification of the server instances connected to BungeeCord.

Therefore probably never gonna happen, you could always make your own plugin to do it using Plugin Messaging. :)

**Comment by GershonR** [comment]
I see, I looked at the PluginMessanging docs on the Spigot site and saw you can use it to connect a player to a server, but how will I know when the player is full loaded into to the server to then warp them to the specific world?

**Comment by md-5** [comment]
Bungee is designed to work with Vanilla, so we cannot implement this.
