### ISSUE TITLE
error when joining

### ISSUE THREAD

**Issue by Noodles0809** [SpigotMC/BungeeCord#1985]
I get this error when joining 

I just updated to the newest bungeecord

 DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Title 69 Protocol GAME Direction net.md_5.bungee.protocol.Protocol$DirectionData@7b272e @ io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by i9hdkill** [comment]
Related:
https://github.com/MylesIsCool/ViaVersion/issues/529

**Comment by MiniDigger** [comment]
do you use viaversion by any chance? since that has problems with 1.11 and titles

**Comment by Noodles0809** [comment]
I do use viaversion

**Comment by MiniDigger** [comment]
wait till myles gets home then and can take a look at it, doubt that it is actually a bungee problem (unless you can reproduce it without via of course)

**Comment by Noodles0809** [comment]
ok thanks

**Comment by Matsv** [comment]
The bungee title plugin you use is not updated to 1.11 yet. You could fix this for now by removing ViaVersion from your spigot servers and only use it as bungee plugin

**Comment by cindyker** [comment]
I just checked this on a Vanilla server (no plugins) that is updated to work with Bungee. Its the Title packet when an ActionBar message (new option with 1.11) is sent.

**Comment by MylesIsCool** [comment]
#1987 fixes this.
