### ISSUE TITLE
Clients disconnected when sent titles in 1.11

### ISSUE THREAD

**Issue by zedwick** [SpigotMC/BungeeCord#1986]
1.11 clients connected to 1.11 (vanillacord) servers will be disconnected with an error when sent titles using /title

```
bad packet ID, are mods in use!? Did not read all bytes from packet class n
et.md_5.bungee.protocol.packet.Title 69 Protocol GAME Direction net.md_5.bungee.protocol.Protocol$DirectionData@34972d3a
```

This is not an issue when using changes made to Title.java here: protocol/src/main/java/net/md_5/bungee/protocol/packet/Title.java

**Comment by MylesIsCool** [comment]
#1987 fixes this
