### ISSUE TITLE
Bungee outdated...?

### ISSUE THREAD

**Issue by Killertom63** [SpigotMC/BungeeCord#1989]
I updated my bungee and it keeps saying outdated. Do I need to update spigot too?

**Comment by electronicboy** [comment]
Yes. However, there is no 1.11 release yet.

**Comment by Killertom63** [comment]
Oh so the coding for bungee is out for when spigot 1.11 is ready?

**Comment by electronicboy** [comment]
Yup

**Comment by Killertom63** [comment]
Thanks
