### ISSUE TITLE
Configuration#getString: null check returning true despite value not existing.

### ISSUE THREAD

**Issue by PotatoTheEllie** [SpigotMC/BungeeCord#1995]
Hey so I am making a plugin and referencing a configuration file and doing a null check on a value, as I would usually. 

```
                if(configuration.getString("val") != null) 
                    this.val = configuration.getString("val");
               else this.val = "null";
```
That is the code I am doing. In the instance of my example, in the configuration file "val" does not exist. Despite this, the code is still returning true to say it does.

To clarify, the path doesn't even exist. That value is only put there when called upon appropriately, so a null check to this "val" should be false surely.

I asked a friend and she said she had also had this problem and fixed it but couldn't recall how to, however I am posting it on here anyway since it could be regarded as a bug.

My server version & API build is is BungeeCord-Bootstrap:1.10-SNAPSHOT:75b7fda:1193

EDIT: Just tried with Configuration#get and it worked fine, so it looks like it's just Configuration#getString

~El

**Comment by Janmm14** [comment]
getAteing wprks like the bukkit's xondiguration getString - it returns an empty one if none was found.

Also there is a contains method, maybe use that.

**Comment by PickNChew** [comment]
getString actually returns null if it does not exist in Bukkit.

**Comment by md-5** [comment]
getString("val",null) or else replace != null with !.isEmpty
