### ISSUE TITLE
Not working in 1.11!

### ISSUE THREAD

**Issue by GabrielAugustoTI** [SpigotMC/BungeeCord#1996]
Not working in 1.11 with ping_passthrough: true

Sends "Timed out"

**Comment by Janmm14** [comment]
Please choose a better title

**Comment by md-5** [comment]
Cannot reproduce

**Comment by GabrielAugustoTI** [comment]
Can reproduce!

Please fix!

**Comment by Janmm14** [comment]
@GabrielAugustoTI
1. Please update to latest BungeeCord.
2. Give us more information.
* * BungeeCord version
* * Spigot version
* * Client versions not working
* * Client versions where its working

**Comment by GabrielAugustoTI** [comment]
Fixed yet! Is not bungee bug, ViaVersion bug..
