### ISSUE TITLE
BungeeCord crash (OutOfMemory)

### ISSUE THREAD

**Issue by Sprax2013** [SpigotMC/BungeeCord#1999]
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "BungeeCord Logger Thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Netty IO Thread #7"

I'm using BungeeCord with 2GB RAM.

I also tried without plugins but BungeeCord is crashing.

**Comment by i9hdkill** [comment]
This isn't a detailed bug report.
We need more information. Like bungee logs, used stsartup params etc.

**Comment by Sprax2013** [comment]
The Error: `Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "BungeeCord Logger Thread"

Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "Netty IO Thread #7"`

Start cmd: `java  -Xmx2G -jar BungeeCord.jar` (using "screen")

Plugins: All the default BungeeCord-Modules, BungeePexBridge, BungeePing, PunishManager, ServerListPlus

I'm using the latest BungeeCord and latest Plugins.

Is it possible to analyse a Java prozess? (Which Plugin, Thread is filling the Memory)

**Comment by i9hdkill** [comment]
Look for help here:
https://www.spigotmc.org/forums/bungeecord-help.70/

Github is for actual bugs only
