### ISSUE TITLE
High lag when connecting to a cuberite server through bungeecord

### ISSUE THREAD

**Issue by yangm97** [SpigotMC/BungeeCord#2001]
Client version:   1.9.4
Server OS:        Linux (debian jessie)
Cuberite Commit id:        ded59e9519c429c511866609d0e5e909f8e10aad
BungeeCord: latest release from jenkins

Everything, from chat, commands (both cuberite commands and bungeecord commands like /server) to interacting with the world or its entities lags baddly and the client eventually times out. Mojang authentication is disabled on both, cuberite and bungeecord. Enabling or disabling the bungeecord support in the cuberite settings didn't change the results.

### Steps to reproduce the behavior
Connect to a cuberite server using a bungeecord proxy server (tested with their latest release, the issue persists).

**Comment by md-5** [comment]
What makes you think this is a BungeeCord bug? We won't investigate why software other than Vanilla doesn't work properly as we assume that they follow a Vanilla compatible protocol.
If Cuberite lags but Vanilla doesn't then Cuberite is probably not completely compatible with Vanilla.
If they think it is a BungeeCord bug then they should please give us technical details.

**Comment by yangm97** [comment]
I think if the issue was (only) on the cuberite side, bungeecord commands like /server shouldn't lag.

**Comment by Janmm14** [comment]
> If they think it is a BungeeCord bug then they should please give us technical details.

**Comment by madmaxoft** [comment]
[rant]
Me thinks this is a BungeeCord bug, because Cuberite works perfectly well with a Minecraft Client. So following your logic, there can't be a bug in Cuberite.

Glad to see the community here is really supporting.
[/rant]

I'll have a look at this (from Cuberite side) and will report any findings in the linked Cuberite issue, feel free to visit for more info.
