### ISSUE TITLE
Chat message too long ==> Connection lost

### ISSUE THREAD

**Issue by lafaipopo** [SpigotMC/BungeeCord#2002]
Bungee version:  1205
Log: http://pastebin.com/PGsmQLVB

When a player writes a message of more than 100 characters,
He is ejected from the server ==> Connection lost
I tried without any Bungee plugin, the result is the same.
All my servers use the latest version of spigot. (1.11)

**Comment by MiniDigger** [comment]
are you sure that you are running 1205?
your log does indicate you are not running 1205.
this error has been fixed in 1204

**Comment by lafaipopo** [comment]
Why, but why !! ??
I was sure to have downloaded the 1205 ...

But you were right, thank you and sorry for the inconvenience.
