### ISSUE TITLE
Need help, security issues.

### ISSUE THREAD

**Issue by VenixNetwork** [SpigotMC/BungeeCord#2003]
Hi,

I know that you offer to enable IP forwarding which means you cannot join any of the servers connected to the bungee cord directly (Prevents users logging in with cracked accounts), However our network recently got breached, they did not gain access to anything in our system, however they managed to bypass the IP forwarding rule. I heard you can use iptables in linux to only allow access to the servers through localhost? However been playing around with that and can't seem to get it working

**Comment by i9hdkill** [comment]
> I know that you offer to enable IP forwarding which means you cannot join any of the servers connected to the bungee cord directly
That's NOT the use of ip forwarding! Ip-foward only shows the spigot servers the players real ip.

**Comment by VenixNetwork** [comment]
So can you help me then, as bungee cord requires the servers to be in offline mode, how do u stop someone logging in with a cracked account (What happened to us)

**Comment by VenixNetwork** [comment]
However if i block all ports, then it doesn't matter if someone connects via the bungee as they can't access the hub server for example?...

**Comment by i9hdkill** [comment]
Read the beginner tutorial I linked above, it's well explained there.
