### ISSUE TITLE
Kicks player on Item pickup

### ISSUE THREAD

**Issue by KingLinuxMC** [SpigotMC/BungeeCord#2005]
Every time I pickup a item it kicks all online players.
If you could help me figure it out that will be awesome.

**Comment by md-5** [comment]
Cannot reproduce.
No version provided.
No server info provided.

Please reproduce on the latest version with the latest CraftBukkit, Spigot or Vanilla build.

**Comment by KingLinuxMC** [comment]
I added some info.

**Comment by KingLinuxMC** [comment]
I am running the latest version of Spigot and Bungeecord. It does not happen on.. my Non Bungeecord server for testing. It also does not happen in a regular world.

**Comment by KingLinuxMC** [comment]
I also have no Plugins on the Bungeecord or the hub server.

**Comment by i9hdkill** [comment]
Still no versions/logs provided. This bug is fixed since some days.

**Comment by KingLinuxMC** [comment]
I re-downloaded Bungeecord and reset everything on Bungeecord it is now fixed. Thx.
