### ISSUE TITLE
Maven build problem

### ISSUE THREAD

**Issue by FlamestoN** [SpigotMC/BungeeCord#2007]
Hello, when i try build from source, i got maven error:
`Failed to execute goal on project bungeecord-bootstrap: Could not resolve dependencies for project net.md-5:bungeecord-bootstrap:jar:1.11-SNAPSHOT: Failure to find net.md-5:bungeecord-proxy:jar:1.11-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced`

**Comment by Janmm14** [comment]
did you `mvn clean install` inside the bootstrap module? do it in the parent directory instead

**Comment by FlamestoN** [comment]
Oh, i'm stupid.
Yes, i did it in bootstap module.
Thank you
