### ISSUE TITLE
Disconnect message & more

### ISSUE THREAD

**Issue by mads03dk** [SpigotMC/BungeeCord#2009]
Hi. It would be awesome if `Disconnect-message`  was added to `messages.properties` so people can set a custom message instead of just getting _Disconnected_ and also which items are getting logged, like `[/IP:50046] <-> InitialHandler has connected` and `[PLAYER] <-> DownstreamBridge <-> [SERVER] has disconnected ` as a boolean

**Comment by md-5** [comment]
There is no user facing message "Disconnected". Please illustrate exactly which user facing message you need translated.

**Comment by mads03dk** [comment]
When i send `end` to bungee, players get _Disconnected_. In spigot its _Server closed_ or a custom message

**Comment by md-5** [comment]
/end takes the disconnect message as an argument
