### ISSUE TITLE
Need help with understanding Bungee stack strace, and how to fix it.

### ISSUE THREAD

**Issue by GoadingGoat** [SpigotMC/BungeeCord#2010]
I'm attempting to write a plugin which redirects players to a specified. but console is throwing this...
![bungeeerror](https://cloud.githubusercontent.com/assets/11308755/20690227/2b3503d4-b62e-11e6-8724-dc4a6f638c5d.PNG)

It doesn't stop the code from functioning, but would rather not have the error message. The code that handles the server connect event is below.

![serverconnectevent](https://cloud.githubusercontent.com/assets/11308755/20690433/784ff740-b62f-11e6-867b-abdf82617aff.PNG)

EDIT: bungeecord build is 1206.

**Comment by md-5** [comment]
At some point you are cancelling ServerConnectEvent without disconnecting the player when the player is not connected to any server.

**Comment by GoadingGoat** [comment]
Ok, is there anyway to not have the error show in console?
found this #2008 

The code does cancel the serverconnect event. but it schedules a new task to either disconnect the player, or connect them to appropriate server. The new task is so that i can ping the server they are going to be connected to, to make sure it is running.

**Comment by md-5** [comment]
I don't think what you are doing is a sane way of achieving something. BungeeCord already checks if the server is up as part of the connecting process

**Comment by GoadingGoat** [comment]
It does, but when the server is down, you cannot send a custom disconnect message to the player, at least as far as i can tell anyway.

**Comment by Janmm14** [comment]
>It does, but when the server is down, you cannot send a custom disconnect message to the player, at least as far as i can tell anyway.

You can change that disconnect message in `messages.properties` (either edit in the jar directly or extract it into the jar's folder and edit it there).

**Comment by GoadingGoat** [comment]
That wouldn't achieve what i want. I want to say why they were disconnected, rather than just set the default disconnect message.

**Comment by md-5** [comment]
There is only one reason they can be disconnected "server is down" - message should be edited accordingly.

**Comment by md-5** [comment]
The problem is the way your plugin behaves you leave players in an inconsistent state - they are not connected to any server, nor will they be.
If all you are wanting is a custom disconnect message then that is what messages.properties is for, or if this is insufficient you can outline what you want.

**Comment by Janmm14** [comment]
Actually your code does not contain any message that would not be possible to set up with current bungeecord. Optional arguments to the disconnect message like the exception class and message could easily be added if not already present.

**Comment by GoadingGoat** [comment]
The user is only temporarily left without a server to connect to, for a very short period of time. As soon as the state of the server they are going to be sent to is established, they are either sent to it or disconnected.

**Comment by md-5** [comment]
Bungee has no way of knowing you are only temporarily doing that

**Comment by Janmm14** [comment]
@GoadingGoat Like you do currently, there is no additional possible message for you to send which bungee doesn't have.

**Comment by GoadingGoat** [comment]
I don't see how adding messages to messages.properties would help me. I have two conditions for the message i want to send. 

A) - The player has not accepted the servers rules.
given A, then B) - The server they are going to be redirected to is offline.

hence i would like to disconnect them with an appropriate error message .

**Comment by md-5** [comment]
So you only disconnect them if they haven't accepted the rules and the server is offline? This makes very little sense. 

My original assertion still stands - you're leaving Bungee in a state of limbo and it has no idea of knowing why.
Maybe you could ping servers periodically to see if they're online, or better yet, just let bungee handle it like it already does.

**Comment by GoadingGoat** [comment]
That's only one of the reasons for disconnecting them, but it is the one that is causing issues...

**Comment by md-5** [comment]
The issue is that you're not disconnecting them.

**Comment by GoadingGoat** [comment]
I honestly don't see why leaving them in limbo for half a second should be an issue...

I love your work md-5, but this is going no where... will probably to easier to find a way of hiding the error from console, as it's not a fatal error.

**Comment by md-5** [comment]
If you have a solution that still allows the API to be robust in the face of misbehaving plugins I'm happy to hear it.

**Comment by GoadingGoat** [comment]
The only thing that currently springs to mind is a boolean flag that can be set to override the check at each ServerConnectEvent. It wouldn't make the api any more robust though... would just mean the plugin dev had to specifically remove the check.
