### ISSUE TITLE
BungeeCord vs SkinsRestorer

### ISSUE THREAD

**Issue by BabelSolea** [SpigotMC/BungeeCord#2011]
Minecraft 1.11
Sponge Vanilla 1.11 # 170 BETA (https://www.spongepowered.org/downloads/spongevanilla/bleeding/1.11)
BungeeCord # 1206 (http://ci.md-5.net/job/BungeeCord/1206/)
SkinsRestorer 12.9.4 (https://www.spigotmc.org/resources/skinsrestorer.2124/updates)

Other plugins on Bungee:
BungeeAuth-1.4 (https://www.spigotmc.org/resources/bungeeauth.493/updates)

showed reason to disconnect after tried loggin to server:

Exception Connecting:NativeIoException : syscall:read(...)() failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

usually just connection timeout.

with out SkinsRestorer that work fine
with - cant loggin.

help pls))) fix that :3
with <3 for your job

**Comment by md-5** [comment]
We can't fix plugins - remove SkinRestorer and contact the author

**Comment by BabelSolea** [comment]
okay) i sended that for all developer sides
