### ISSUE TITLE
Bungeecord - Error

### ISSUE THREAD

**Issue by RabsCodes** [SpigotMC/BungeeCord#2014]
Hello,

I have recently found an error that is caused by java.lang.IndexOutOfBoundsException.

Here is the full log:

http://hastebin.com/nusebekihe.vbs

**Comment by electronicboy** [comment]
make sure you're running the latest version of bungeecord. Likely this is an old version of bungeecord, or your issue is actually caused by something else running on your server/bungee

**Comment by RabsCodes** [comment]
Hello,
Yes its the latest build. It's the latest stable one.

I'm not sure what else could be causing this.

**Comment by md-5** [comment]
>30.11 16:59:31 [Server] INFO at net.md_5.bungee.protocol.packet.PlayerListItem.read(PlayerListItem.java:34)

A plugin you are running on BungeeCord or your server.
Possibly skins/tabs/version compatbility.

If this occurs without plugins let us know

**Comment by RabsCodes** [comment]
What sort of 'plugin' could it be?

**Comment by md-5** [comment]
Please read my message

**Comment by RabsCodes** [comment]
I deleted all the plugins on the server to source out the issue. Only a few that were important i didn't and now that I have reset the server some-what, the issue has been resolved.
