### ISSUE TITLE
Trying to connect to bungee results in console crash

### ISSUE THREAD

**Issue by necrogami** [SpigotMC/BungeeCord#2015]
```Inconsistency detected by ld.so: dl-lookup.c: 128: check_match: Assertion `version->filename == NULL || ! _dl_name_match_p (version->filename, map)' failed!```

So i just setup bungeecord and this is the error message i'm seeing when i try to connect to bungeecord 1210 with a 1.10.2 client with a 1.10.2 vanilla server in the background.

**Comment by md-5** [comment]
https://github.com/netty/netty-tcnative/issues/111

Alpine linux? Some basic OS info would help....
Looks like you need -Dbungee.epoll=false

**Comment by necrogami** [comment]
Yes, this is alpine linux, running inside a docker container.

https://gist.github.com/necrogami/2f17e64d165d87567d1483016da45f40

Here's the startup and crash when i tried connecting to the server.

**Comment by md-5** [comment]
Update to 1211 and add -Dbungee.native=false

Alpine isn't really a supported platform for a heap of Spigot plugins also, seriously consider using a Debian container.

**Comment by kamcio96** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L218

**Comment by Janmm14** [comment]
bungee.native: https://github.com/SpigotMC/BungeeCord/blob/master/native/src/main/java/net/md_5/bungee/jni/NativeCode.java#L83

**Comment by Janmm14** [comment]
Maybe also add -Dbungee.epoll=false

**Comment by necrogami** [comment]
Except -Dbungee.epoll=false didn't work.

**Comment by Janmm14** [comment]
@necrogami Does it work with the other flag also present?

**Comment by necrogami** [comment]
@Janmm14 Yes, it did launch and work with the other flag.

**Comment by MarkehMe** [comment]
I still have this issue with `-Dbungee.epoll=false -Dbungee.netty -Dnative.disable=true`

Guess I'm switching to EL for now though, too much lack of support for alpine 😢
