### ISSUE TITLE
QUESTION: Bungeecord and incompatible Minecraftversions

### ISSUE THREAD

**Issue by Sprungente** [SpigotMC/BungeeCord#2016]
My minecraftserver's run on 1.11. 
When I want to Join with for example 1.8 the bungeecord show's in the serverlist as would I use the correct version.

How can I change, that Bungeecord say his version in the Serverlist when the User use a wrong version?

Hope you can unterstand this and the question isn't embarrassing

**Comment by kamcio96** [comment]
You have server priorities. Set it with version priority (from 1.11 to 1.8)

**Comment by Sprungente** [comment]
I don't understand how i set version priorities. Could you give me an example or something that can help me to understand?

**Comment by kamcio96** [comment]
in config.yml
```
priorities:
- lobby1.11
- lobby1.10
- lobby1.9
- lobby1.8
```
And you have to define yours servers 

Or you can you setup one lobby with ProtocolSupport 😁

**Comment by Sprungente** [comment]
I don't have a lobby 😆 

now bungee will not starting. What have I doing wrong?

03:41:26 [SCHWERWIEGEND] Exception in thread "main" 
03:41:26 [SCHWERWIEGEND] java.lang.IllegalArgumentException: Server citybuild1.11 (priority 0) is not defined
03:41:26 [SCHWERWIEGEND] 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
03:41:26 [SCHWERWIEGEND] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:121)
03:41:26 [SCHWERWIEGEND] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
03:41:26 [SCHWERWIEGEND] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
03:41:26 [SCHWERWIEGEND] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Sprungente** [comment]
i think I expressed badly 😢 

I want that Bungeecord says to People, that he has to use 1.11 and not the spigotserver. 

my people are irritaded because in serverlist looks the server like on 1.11. 

For example a spigotserver: When the minecraftversion isn't the same and not compatible, then it's displayed as "Server out of date".  that is my goal

**Comment by i9hdkill** [comment]
Create a thread here:
https://www.spigotmc.org/forums/bungeecord-help.70/

This issue tracker should be used to report bugs only.
