### ISSUE TITLE
bungee 1.10.2 java 8

### ISSUE THREAD

**Issue by bobbyspelt** [SpigotMC/BungeeCord#2017]
where can i download bungee java 8?

**Comment by electronicboy** [comment]
Pretty much all versions of bungee will work on java 8. if you're having issues, your issue is most likely elsewhere than the version of java that bungee is compiled against.

**Comment by i9hdkill** [comment]
See answer above.

**Comment by bobbyspelt** [comment]
yes but i cant find a bungee 1.10.2 version of it

**Comment by electronicboy** [comment]
latest bungeecord supports 1.8-1.11
