### ISSUE TITLE
Bungee Cord "Kicked While Connecting To Lobby:You Are Already Connected To This Server"

### ISSUE THREAD

**Issue by ROKRNatPlayzYT** [SpigotMC/BungeeCord#2019]
Here is my bungee config, http://pastebin.com/vrQZQ3aG

I have gotten rid of the ip part so you can't see it.

Please HELP!!

**Comment by electronicboy** [comment]
That error is not a bungeecord error, but one on your spigot servers. The issue tracker is for bugs, not for help with setup issues, especially issues that are not to do with bungeecord. Please use the forums/IRC for help with Spigot.

**Comment by i9hdkill** [comment]
See answer above
