### ISSUE TITLE
Decoder Exception

### ISSUE THREAD

**Issue by JosephTheEngineer** [SpigotMC/BungeeCord#2021]
**Hello, players connecting through Bungee Cord get this error:**
`bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Kick 0 Protocol LOGIN Direction net.md_5.bungee.protocol.Protocol$DirectionData@154d4be
06:54:44 [INFO] [JosephTheEngi] disconnected with: §fException Connecting:DecoderException : net.md_5.bungee.protocol.BadPacketException: Did not read all bytes from packet class net.md_5.bungee.protocol.packet.Kick 0 Protocol LOGIN Direction net.md_5.bungee.protocol.Protocol$DirectionData@154d4be @ io.netty.handler.codec.MessageToMessageDecoder:98`

We are able to login if we rejoin like 20 times.
### Client Errors:
![image](https://cloud.githubusercontent.com/assets/17937582/21083269/6e587812-c038-11e6-9b73-80309a93cbff.png)
![image](https://cloud.githubusercontent.com/assets/17937582/21083605/8f4013da-c03f-11e6-900d-e833d5fc3c9d.png)
![image](https://cloud.githubusercontent.com/assets/17937582/21083608/a3308302-c03f-11e6-85e0-00530de61b20.png)
![image](https://cloud.githubusercontent.com/assets/17937582/21083610/b1d1a666-c03f-11e6-9435-cc500b7d4f98.png)

[Bungee Cord Log](http://pastebin.com/aCXz0kng)
[Bungee Cord Config](http://pastebin.com/ugQEQ1Cy)
[Spigot Log](http://pastebin.com/MA5ZDa1N)

I have already tried without bungee plugins and spigot plugins.
Thanks! :D

**Comment by electronicboy** [comment]
This looks more like a misconfiguration of the machine that your servers are running on as opposed to an issue with Bungeecord, particularly in regards to the SSL components.

**Comment by JosephTheEngineer** [comment]
@electronicboy So... Is there anyway to fix it?
Would a windows reset work? (or I could switch to linux)
Thanks :D

**Comment by Janmm14** [comment]
Try reinstalling your jre maybe.

**Comment by JosephTheEngineer** [comment]
@Janmm14 Yea ok I'll try that.
Thanks for the help! :D

**Comment by JosephTheEngineer** [comment]
@Janmm14 Reinstalling Java did not work still getting errors. D: Going to look to resetting windows or switching to Linux.

**Comment by Phineas** [comment]
Are you home-hosting this/what host do you use? And why are you getting random pings from internal network/subnet

**Comment by JosephTheEngineer** [comment]
@electronicboy SOLUTION : Switched to Linux (Ubuntu) and bungee cord works fine without errors. :D 
@Phineas This is home hosted on an old HP machine running Windows Vista (Now on Ubuntu ^). I don't know why i'm getting random pings from 10.0.0.138 (never noticed it). It runs Bungeecord, spligot servers (1.11), forge servers and a wamp webserver. I also have a no-ip, ip redirect to lesion.ddns.net.

**Comment by electronicboy** [comment]
10.0.0.138 is an IP address on the same private network as your machine, which likely means that somebody is probably running something on their machine on the same network your server is on
