### ISSUE TITLE
BungeeCord Server Error

### ISSUE THREAD

**Issue by tankpillow** [SpigotMC/BungeeCord#2022]
Hi, I am trying to set up a BungeeCord Server, but when I run the BungeeCord start.command file I get this Error Message:

20:47:19 [SEVERE] Exception in thread "main" 
20:47:19 [SEVERE] java.lang.IllegalArgumentException: Server lobby (priority 0) is not defined
20:47:19 [SEVERE]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
20:47:19 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:121)
20:47:19 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
20:47:19 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
20:47:19 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Here Is My BungeeCord Config:

ip_forward: true
network_compression_threshold: 256
stats: 1962c42a-7932-4652-a6b1-a76c4a58d2d3
groups:
  tankpillow:
  - admin
servers:
  hub:
    motd: '&4The Redstone Isles'
    address: localhost:25566
    restricted: false
timeout: 30000
player_limit: 20
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 20
  tab_size: 60
  ping_passthrough: false
  force_default_server: true
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: -1

Here is my Hub Server server.properties:

#Minecraft server properties
#Sun Dec 11 20:44:34 EST 2016
query.port=25566
generator-settings=
force-gamemode=false
allow-nether=true
gamemode=0
broadcast-console-to-ops=true
enable-query=true
player-idle-timeout=0
difficulty=1
spawn-monsters=true
op-permission-level=4
announce-player-achievements=true
pvp=true
snooper-enabled=true
level-type=DEFAULT
hardcore=false
enable-command-block=false
max-players=20
network-compression-threshold=256
resource-pack-sha1=
max-world-size=29999984
server-port=25566
debug=false
server-ip=
spawn-npcs=true
allow-flight=false
level-name=world
view-distance=10
resource-pack=
spawn-animals=true
white-list=false
generate-structures=true
online-mode=false
max-build-height=256
level-seed=
prevent-proxy-connections=false
motd=A Minecraft Server
enable-rcon=false

Is there anything that I'm doing wrong?

**Comment by electronicboy** [comment]
from the looks of that, your configuration file for bungeecord is completely malformed. Delete the config and start again.

**Comment by tankpillow** [comment]
Ok let me try that. And what do you mean by malformed. Do you mean that it didn't generate correctly?

**Comment by electronicboy** [comment]
I mean that you edited the configuration file and totally messed it up

**Comment by tankpillow** [comment]
Ok how should the configure look like
Sorry I'm new at BungeeCord

**Comment by tankpillow** [comment]
Ok so I should change the lobby in the priority list to hub

**Comment by electronicboy** [comment]
yes, if that is what your server is called in the servers list

**Comment by tankpillow** [comment]
Ok let me change that to hub

**Comment by tankpillow** [comment]
I'm still getting the same error

**Comment by electronicboy** [comment]
The paste above is hard to tell, but looks like you've mis-formatted it. yaml is format sensitive, so you need to make sure that you use spaces before lines properly. correct the formatting, if you can't do that, move your config file to another place and start bungee to create a brand new config file, and then reconfigure it, being weary that you don't break the formatting of anything in the file.

**Comment by tankpillow** [comment]
Ok

**Comment by tankpillow** [comment]
Are there any errors in my server.properties

**Comment by Janmm14** [comment]
This topic belongs to the spigotmc bungeecord help forum, and not i to the bugtracker btw.

Also if you include yaml or other code in here, please use three ` followed by a newline before the code and three ` in a newline after the end of the code.

**Comment by i9hdkill** [comment]
^
