### ISSUE TITLE
Connection lose during Bot Attacks

### ISSUE THREAD

**Issue by Twonox** [SpigotMC/BungeeCord#2024]
When so many bots try to join my server, successful or not, all server's connection in my bungeecord network lose their connection, so the players have a ping of 600-1000ms.
Even if I shutdown the lobby server of my network, it changes nothing, other servers are affected.

I have many bot protections, the bots can't join, but it's sufficient that the bots try to join the server to cause this..

**Comment by md-5** [comment]
Unless you can demonstrate a specific weakness in Bungeecord that can be addressed, a malicious attack or ddos is hot a bug.

**Comment by Dimatert9** [comment]
Hi. You can try map captcha based on Waterfall(BungeeCord fork).
Video: https://youtu.be/9I6X3LMKf6g
Captcha download link: https://mega.nz/#!bZJBkJrA!EEgYPbmEtFPQUbz9CvscSGNNTAKlW04eGJc0DYOeiqI
Modules for WaterFall: https://ci.destroystokyo.com/job/Waterfall/
Captcha sources:  https://github.com/Dimatert9/Waterfall-rus/tree/original

**Comment by Twonox** [comment]
@Dimatert9 The bots can't join my server, I d'ont need that but thanks :)
@md-5 I founded the problem after some test... the cause is one bad config of BungeePerms.

**Comment by Dimatert9** [comment]
@Twonox Captcha load the server in 3-4 times less than the antibot plugin.
