### ISSUE TITLE
Player switching server after "disconnect"

### ISSUE THREAD

**Issue by XLordalX** [SpigotMC/BungeeCord#2025]
As can be seen in this hastebin: http://hastebin.com/iwuxokawek.css, the player "Sieva" switches servers 
("[Sieva] <-> ServerConnector [factions] has connected") after the apparent "disconnect" ("[Sieva] -> UpstreamBridge has disconnected"). This causes several issues on our backend, such as players being removed from ram too early. Is there any way to fix this?

Config: http://hastebin.com/julixigele.php.
Build: 1205.

**Comment by md-5** [comment]
Please provide reproduction steps without plugins.
