### ISSUE TITLE
Error when server online for long periods of time and no players online

### ISSUE THREAD

**Issue by Ronan77** [SpigotMC/BungeeCord#2027]
When ever my server doesn't have players on for a while, the server has an error when someone tries to join under the Bungee. Any ideas why this happens? I just get a huge error and all i can think about is the mysql plugins just failing maybe? But the only mysql plugin i have is AdvancedBans and it doesn't have errors when servers have been online for a long while, please look into this error log :)
I haven't been able to find the source of "[\*] An error occurred." message anywhere, i even have a custom messages.properties file, but it's not in there, and I know I made "[\*]" custom but no plugins have that error message in any config or file, any help?

Error Log: http://hastebin.com/ipinaquxed.lua
Image: http://i.imgur.com/M93U4SK.png
Messages.Properties: http://hastebin.com/hegobakake.tex

**Comment by electronicboy** [comment]
`10:02:10 [SEVERE]     at lu.r3flexi0n.bungeeonlinetime.utils.MySQL.querySync(MySQL.java:100)`
This issue tracker is for bugs with bungeecord, not for general help due to issues caused by other plugins.

**Comment by i9hdkill** [comment]
Not a problem with BungeeCord itself, see post above.
