### ISSUE TITLE
[HELP ME] ReadTimeoutExpection : null

### ISSUE THREAD

**Issue by Tonyzoo1234** [SpigotMC/BungeeCord#2029]
Every single time I try to join my server I always get this one error! :(
My log file
       \/
http://pastebin.com/CTaUxera

I don't understand this at all! Please, walk me through this.

**Comment by i9hdkill** [comment]
This is a bugtracker and not the place for getting configuration help.

Create a thread here:
https://www.spigotmc.org/forums/bungeecord-help.70/

or simply read the BungeeCord wiki:
https://www.spigotmc.org/wiki/bungeecord/
