### ISSUE TITLE
BungeeCord shows online players that are actually offline

### ISSUE THREAD

**Issue by Relaking** [SpigotMC/BungeeCord#2031]
Bump: https://github.com/SpigotMC/BungeeCord/issues/1734

Sometimes if a player times out on a server the BungeeCord doesnt seem to proberly disconnect the player, which results in a ghost-player that is shown online when checking the BungeeCord, but offline when listing the players on the local server.
The only way to disconnect those players is by completely restarting the BungeeCord-Server.
Happened multiple times with BungeeCord #1216

**Comment by md-5** [comment]
Please provide steps to reproduce without plugins.

**Comment by Relaking** [comment]
Look at https://github.com/SpigotMC/BungeeCord/issues/1734
There are no good ways to reproduce, as it happens randomly.
Sometimes it doesn't occur for over a week, and on other days it happens multiple times, with multiple BungeeCord-Restarts in between (Today it happened multiple times, and every time 2-5 players got "stuck" in the BungeeCord. After every time we restarted the BungeeCoord, and sometimes it only took a few minutes until it happened again, and sometimes it took a few hours).
The player gets disconnected from the server, most often with a timeout-message
`[01:09:09] [Server thread/INFO]: Revanlp lost connection: Timed out`
but the bungeecord doesn't show anything about that at all.
Trying to kick the player doesn't help either.
If you need any more information, logs or whatever, I'll gladely provide them, but right now I can't find anything at all.

**Comment by Phineas** [comment]
Do you have RedisBungee installed?

**Comment by Relaking** [comment]
No, do you think that RedisBungee could fix the problem?

**Comment by Janmm14** [comment]
@Relaking no iit does not fix any problem bout could've been the problems source

**Comment by Relaking** [comment]
@Janmm14 Ah, well in that case it's definetely not the source, as we don't use it :/
