### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by wanted156** [SpigotMC/BungeeCord#2032]
Hello,

When any player tries to connect to my "CSGO" server he instantly gets disconnected with the following error:

http://prnt.sc/do500a
http://prnt.sc/do502o
Any fix?

Regards

**Comment by md-5** [comment]
Teproduce without plugins; make sure your servers are updated

**Comment by wanted156** [comment]
Reproduced without plugins. The "CSGO" server requires a modpack to join and the user get's the notification to download. If they choose yes or no, doesn't matter, they get kicked with the above mentioned error.

**Comment by md-5** [comment]
Some mods may not be supported by bungee

**Comment by wanted156** [comment]
Updated ProtocolLib on the server and that solved the issue. Hopes it helps in any future cases. /closed

**Comment by md-5** [comment]
>Reproduced without plugins. 

If it occured without plugins how did updating ProtocolLib help?

**Comment by Janmm14** [comment]
@md_5 I think he meant without plugins on bungeecord.
