### ISSUE TITLE
Unable to launch with forced_hosts set to []

### ISSUE THREAD

**Issue by ThyImortalGamer** [SpigotMC/BungeeCord#2033]
As the title says, it won't properly launch when forced_hosts is is set to []

On top of that when it is set to basically anything else I am unable to connect to the default server. Note: I am attempting to use this with YAMS, so that may be the cause of the second problem

Config: pastebin.com/d81uSFLC

Error: pastebin.com/3jgheCg

**Comment by prplz** [comment]
It's not a list it's a map, so you must set it to {}

**Comment by ThyImortalGamer** [comment]
Thanks, fixed all the problems I was having.
