### ISSUE TITLE
motd gets split in two lines -> Server startup reacts badly, and cannot start the server

### ISSUE THREAD

**Issue by MithrandirCraft** [SpigotMC/BungeeCord#2035]
`servers:
  factions:
    motd: '&9M&bi&9t&bh&9r&ba&9n&bd&9i&br&9C&br&9a&bf&9t &bNetwork &6[1.11] &ewww.mithrandircraft.es &4Factions/PvP &b(Custom PVP:1.8 y 1.9) &aSurvival/PvE'
    address: 5.135.92.52:25565
    restricted: false`

Hi, I don't know if this is an issue with my host, or with Spigot, but with the previously set motd, the server cannot restart (Through an auto restarting service provided by my host), because the motd splits itself into the following line. Like this:

motd: '&9M&bi&9t&bh&9r&ba&9n&bd&9i&br&9C&br&9a&bf&9t &bNetwork &6[1.11] &ewww.mithrandircraft.es 
&4Factions/PvP &b(Custom PVP:1.8 y 1.9) &aSurvival/PvE'

This motd splitting occurs when the bungee starts. I think it may be my host reacting badly to it. But I still wanted to make you guys know in case this is something which could be fixed on your side.

**Comment by md-5** [comment]
That motd works fine for me - you will have to contact your host.
