### ISSUE TITLE
DownstreamBridge <-> [Server] - read timed out

### ISSUE THREAD

**Issue by krfcm** [SpigotMC/BungeeCord#2036]
Hi,
I currently having some issues with BungeeCord, randomly kicked all player for "Time out" and starts using 100% CPU. 
I use last wersion of BungeeCord
Config bunge: http://pastebin.com/HRiX3jrQ
Log http://pastebin.com/BRBJZDVD.
I set connection throttle on spigot serwer to -1

**Comment by md-5** [comment]
Please reproduce without plugins; Provide a stack dump with jstack when lagging
