### ISSUE TITLE
Bungee Warning

### ISSUE THREAD

**Issue by Lammendam** [SpigotMC/BungeeCord#2037]
16:05:52 [WARNING] Event ServerConnectedEvent(player=Lammendam, server=net.md_5.bungee.ServerConnection@4c6e0a7f) took 352,116,993ns to process!
16:05:52 [WARNING] Event ServerSwitchEvent(player=Lammendam) took 494,020,722ns to process!

Please tell me someone what it means. And may this to occur crush bungeecord server?

**Comment by Paulomart** [comment]
Its a plugin that takes a long time to process an Event.

**Comment by Lammendam** [comment]
Okay, thanx for answer :)
