### ISSUE TITLE
BungeeCord Not working

### ISSUE THREAD

**Issue by Devontae1** [SpigotMC/BungeeCord#2038]
Everytime I set my online mode flase the server shows up with these commands

06:08:44 [SEVERE] Exception in thread "main" 
06:08:44 [SEVERE] java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
06:08:44 [SEVERE] at net.md_5.bungee.conf.YamlConfig.getBoolean(YamlConfig.java:188)
06:08:44 [SEVERE] at net.md_5.bungee.conf.Configuration.load(Configuration.java:81)
06:08:44 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
06:08:44 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
06:08:44 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

I'm gonna provide the config I'm not gonna have the ips filled in if that's ok

  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  Devontae_:
  - admin
servers:
  hub:
    address: 
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  Factions:
    address: 
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  Skyblock:
    address: 
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
timeout: 30000
listeners:
- max_players: 4000
  priorities:
  - hub
  host: 
  tab_size: 60
  force_default_server: true
  bind_local_address: true
  ping_passthrough: false
  tab_list: GLOBAL_PING
  motd: '&1Another Bungee server'
  query_enabled: false
  query_port: 25577
  forced_hosts:
    pvp.md-5.net: pvp
player_limit: 1000
online_mode: flase
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: -1

If someone could tell me how to fix this isn't easy for me.

**Comment by MiniDigger** [comment]
>online_mode: flase
typo ;)

**Comment by Devontae1** [comment]
OMG I Feel SOO STUPID....

**Comment by Devontae1** [comment]
Thank you

**Comment by MiniDigger** [comment]
next time, please don't create an issue here. 
use the irc or the forum if you need help. the issue section is used to track actual bugs. 
Also, as this is solved now, please close it.
