### ISSUE TITLE
Server online, but not ping- or joinable

### ISSUE THREAD

**Issue by xXAlex10Xx** [SpigotMC/BungeeCord#2042]
Hello, 
my server is online, and works fine for some hours.
But after a random amount of time (not sure if its after a specified amount of pings / joins / hours), the server isn't responding to NEW players anymore. Anyone who is on the server, doesn't even recognize there would be a problem. Everything is fine for them, but when they disconnect, they can't ping or connect to the server.

Edit: InitialHandler doesn't show up in console anymore ([IP] <-> InitialHandler has connected)

Any ideas?

**Comment by md-5** [comment]
Please reproduce without plugins; use the forums for support
