### ISSUE TITLE
Problem with Players_Limit

### ISSUE THREAD

**Issue by Outravez** [SpigotMC/BungeeCord#2045]
I have problem with bungeecord i can't limit players on bungee.

I need it fast, please :)

Problem:

I have server 200 slots, you and me will join the server (with us server will be full). So server is full and we are going to play 1vs1 (on other server by /server server2) during we are playing, two other guys can join Lobby and when we will finish we are not able to back on Lobby,

How to fix it? Can i setup maximum players on bungee? 

I think that i can but it's not working. i was trying with:
player_limit: 2 and with   max_players: 2 
 when i joined with 2 on Lobby i can't join with other (it's good) but when i will join with one of 2 i'm able to connect with other he wasn't on server before but he was able to join even when 2 was connected to bungee.
and when i was trying back to lobby, i can't because lobby was full

Better describe...

Player A and B are on Lobby, player C can't join (it's good)
Player A joined server1, Player C now can join lobby
But Player A can't back to lobby..

Please help me i just need to have limit on connection to bungee.

If u can, please send me pre-made config or step by step how i should do it.

Best Regards and A lot of Thanks,
Outraves

PS. I'm on version 1.9

**Comment by i9hdkill** [comment]
Hi,
please reproduce that with orginal BungeeCord. We didn't changed stuff regarding this.

Usually setting max_players should do the trick.

**Comment by md-5** [comment]
The player_limit on BungeeCord refers to the maximum amount of players that can join via the proxy.
