### ISSUE TITLE
Bungeecord issue Exception in thread "main"

### ISSUE THREAD

**Issue by yanchu0612** [SpigotMC/BungeeCord#2046]
i cant start my bungeecord!! help!

10:33:03 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
10:33:03 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
10:33:03 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:81de9d5:1221
10:33:04 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
10:33:04 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
10:33:04 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
10:33:04 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
10:33:04 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
10:33:04 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
10:33:04 [INFO] Attempting to update plugin from null to ModuleVersion(build=1221, git=81de9d5)
10:33:04 [INFO] Attempting to Jenkins download module cmd_alert v1221
10:33:04 [INFO] Download complete
10:33:04 [INFO] Attempting to update plugin from null to ModuleVersion(build=1221, git=81de9d5)
10:33:04 [INFO] Attempting to Jenkins download module cmd_find v1221
10:33:05 [INFO] Download complete
10:33:05 [INFO] Attempting to update plugin from null to ModuleVersion(build=1221, git=81de9d5)
10:33:05 [INFO] Attempting to Jenkins download module cmd_list v1221
10:33:05 [INFO] Download complete
10:33:05 [INFO] Attempting to update plugin from null to ModuleVersion(build=1221, git=81de9d5)
10:33:05 [INFO] Attempting to Jenkins download module cmd_send v1221
10:33:05 [INFO] Download complete
10:33:05 [INFO] Attempting to update plugin from null to ModuleVersion(build=1221, git=81de9d5)
10:33:05 [INFO] Attempting to Jenkins download module cmd_server v1221
10:33:05 [INFO] Download complete
10:33:05 [INFO] Attempting to update plugin from null to ModuleVersion(build=1221, git=81de9d5)
10:33:05 [INFO] Attempting to Jenkins download module reconnect_yaml v1221
10:33:06 [INFO] Download complete
10:33:06 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:33:06 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:33:06 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:33:06 [INFO] Loaded plugin BuycraftX version 10.1.4 by Buycraft
10:33:06 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:33:06 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:33:06 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:81de9d5:1221 by SpigotMC
10:33:06 [ALLVARLIG] Exception in thread "main"
10:33:06 [ALLVARLIG] org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
10:33:06 [ALLVARLIG]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
10:33:06 [ALLVARLIG]     at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
10:33:06 [ALLVARLIG]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
10:33:06 [ALLVARLIG]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
10:33:06 [ALLVARLIG]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:64)
10:33:06 [ALLVARLIG]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
10:33:06 [ALLVARLIG]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
10:33:06 [ALLVARLIG]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:33:06 [ALLVARLIG] Caused by: java.nio.charset.MalformedInputException: Input length = 1
10:33:06 [ALLVARLIG]     at java.nio.charset.CoderResult.throwException(Unknown Source)
10:33:06 [ALLVARLIG]     at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
10:33:06 [ALLVARLIG]     at sun.nio.cs.StreamDecoder.read(Unknown Source)
10:33:06 [ALLVARLIG]     at java.io.InputStreamReader.read(Unknown Source)
10:33:06 [ALLVARLIG]     at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123)
10:33:06 [ALLVARLIG]     at java.io.Reader.read(Unknown Source)
10:33:06 [ALLVARLIG]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184)
10:33:06 [ALLVARLIG]     ... 7 more 

_______________________________________________________________________________________________________________

ip_forward: true
network_compression_threshold: 256
stats: 57102b43-cc68-4fb9-9d6e-20c9331a5051
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
groups:
  md_5:
  - admin
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25566
    restricted: false
  survival:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25567
    restricted: false
  MiniGames:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25568
    restricted: false
timeout: -1
listeners:
- query_port: 25577
  motd: '&6Vällkomen till XeonCraft!'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 100
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000

**Comment by Janmm14** [comment]
Your configuration is malformed. Unable to detect it if you just copy-paste it without applying propper markdown formatting. This issue also does not belong here at all, but into the spigotmc.org forums.
