### ISSUE TITLE
Add a way to access a players ClientSettings

### ISSUE THREAD

**Issue by Foorack** [SpigotMC/BungeeCord#2047]
Currently, we have to use bungeecord-proxy and cast the ProxiedPlayer to a UserConnection to get the settings. I know there is getLocale but would be really helpful if we could access the others as well. Thanks :+1:

https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/packet/ClientSettings.java

https://github.com/SpigotMC/BungeeCord/blob/81de9d5a63a143c3267968d7fa5ec13db622d268/proxy/src/main/java/net/md_5/bungee/UserConnection.java#L124

**Comment by Phineas** [comment]
You could create a pull request.

**Comment by Foorack** [comment]
Closing this as it has now been implemented, see pull request #2057 and commit https://github.com/SpigotMC/BungeeCord/commit/dbf20957a9cd7c93ee6e08d3f255f49df2066d97
