### ISSUE TITLE
PluginManager#dispatchCommand not executing variable (Sounds stupid)

### ISSUE THREAD

**Issue by PotatoTheEllie** [SpigotMC/BungeeCord#2049]
Hey so I know this may sound really silly, but for some reason when I try to execute a string gathered from an inputstream (from a Spigot server). It won't execute. 

This is the code:

`        @EventHandler
        public void onEvent(PluginMessageEvent e){

            if(e.getTag().trim().equals("commander")){

                ByteArrayDataInput in = ByteStreams.newDataInput(e.getData());

                String cmd = in.readUTF();
                if(cmd.split(":")[0].equals("command")) { // passes ^^

                    String command = in.readUTF(); // prints fine

                    listening = true;
                    ProxyServer.getInstance().getPluginManager().dispatchCommand(ProxyServer.getInstance().getConsole(), "alert test"); //Works
                    //execute(command); - Attempted fix which is just the method below else where
                    ProxyServer.getInstance().getPluginManager().dispatchCommand(ProxyServer.getInstance().getConsole(), command); // Doesn't work
                    listening = false; // ignore this
                    System.out.println(stream.getMessage()); // and this

                    //and this vvvvvvvvvvvvvvvvvvv
                    if(stream.getMessage() != null) {
                        ByteArrayDataOutput out = ByteStreams.newDataOutput();
                        out.writeUTF(cmd);
                        out.writeUTF(stream.getMessage());

                        ProxyServer.getInstance().getServers().forEach((s, serverInfo) -> serverInfo.sendData("commander", out.toByteArray()));
                    }
                }
            }
        }`

The first execute works, but then the second one doesn't. Regardless of whether the first command works or not the second one isn't. Which is quite odd. As for the rest of the plugin it's about 3 other lines as it's solely for a response to be sent back (and executed).

If you need any more information I can give it.

Thanks.

--Whole class: http://pastebin.com/rk9VnQd9

**Comment by md-5** [comment]
If "alert test" works, then there is probably an issue in the way you are sending your stuff, or command is not identically equal to "alert test".
(check command.equals("alert test"))
It is unlikely there is a BungeeCord bug here, so you should use the forums for help
