### ISSUE TITLE
1.11.2 server not working on bungee.

### ISSUE THREAD

**Issue by Zilacon** [SpigotMC/BungeeCord#2051]
So i brought this to hexagons attention here: https://github.com/HexagonMC/BungeeCord/issues/123
To which they asked me to test to see if this is also an issue with official bungee, and it was. So told me to post a issue here. I used the latest version on the Jenkins.

Basically using the forced host or the subdomain with a srv record pointing to the bungeecord IP does not work with the 1.11.2 server (which is the default server/hub). When i go onto a 1.11.2 client it shows no connection or anything. But going onto 1.11 it shows everything just fine. As shown on the pictures on the hexagon issue.

Pinging to the IP:PORT of the 1.11.2 server on the 1.11.2 client works. But not through anything through bungee.

**Comment by md-5** [comment]
Cannot reproduce on latest BungeeCord version without plugins.

BungeeTabPlus is NOT a supported plugin because it causes issues exactly like this.

**Comment by md-5** [comment]
Heck I can't even reproduce it on your own server with 1.11.2
![p6ohyx7](https://cloud.githubusercontent.com/assets/1007849/22497829/4da08dec-e8a8-11e6-8ada-6bf2924fafc3.png)

**Comment by Zilacon** [comment]
Actually you helped, im trying to update BungeeTabListPlus, and its having config errors with the update. So that basically proves you were right about it being the problem. Hopefully fixing the config on 2.7.0 amkes it work with it on.

Thanks for helping.
