### ISSUE TITLE
How can i get that current player which listener connected to?

### ISSUE THREAD

**Issue by Redfoxbox** [SpigotMC/BungeeCord#2052]
I would like create a bungee cord plugin that have a "lobby" command, and if a players wrote in they will be redirect(transport) to a default server witch depends the player current listener. When you have declarate many listener in bungee cord you need to known current player what listener connected to.
Somebody can help me about that problem?

**Comment by md-5** [comment]
ProxiedPlayer.getPendingConnection().getListener()

Please use the forums for questions, this is for bug reports only

**Comment by Redfoxbox** [comment]
Sorry about that, next time i will.
