### ISSUE TITLE
random : WARNING Event ChatEvent

### ISSUE THREAD

**Issue by thunderlight411** [SpigotMC/BungeeCord#2054]
Hello all,

i have started just a new Bungeecord Server and all working fine except 1 small thing
sometimes i receive some error messages in my console about chat messages that take to long to process

04.02 23:23:04 [Server] WARNING Event ChatEvent(super=TargetedEvent(sender=playername, receiver=net.md_5.bungee.ServerConnection@17509905), cancelled=false, message=niemand) took 495,357,699ns to process!

Its not just one server its a random event 

everything is working correctly only some times the chat messages are getting true slowly,

Plugins in BungeeCord
AdvancedBan
BUngeeEssentials
BungeeTabListPlus-2.7.0
Movemenew
ServerSwitcher

i hope someone can tell me what this problem creates and how to resolve it.

**Comment by Paulomart** [comment]
A plugin is causing it.

**Comment by Janmm14** [comment]
Plugin issue. Please use the forums for support.

**Comment by thunderlight411** [comment]
Oke, thnx for the feed back,
