### ISSUE TITLE
BungeeCord Error (io.netty.channel.ConnectTimeoutException)

### ISSUE THREAD

**Issue by MineD85** [SpigotMC/BungeeCord#2056]
Hello!
Forgive me for my English :D I am from Asia
I am trying to solve this issue, but I can't fix it with my knowledge this time >_>.
At first, I am creating a Minecraft server with 4 servers in it (lobby (1gb ram), bungee cord (1gb ram), fac (2gb ram), and sky block (2gb ram too)), it works well until I want to change the version (lobby 1.8-1.11, sky block 1.9-1.11). i changed all the server to that version (i already inserted ViaVersion plugin). The Faction and the Skyblock works well, but i cant logging in to the lobby server :(. it says : Could not connect to a default server or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
What should i do :( i host all the 4 server in the same host (ServerOmat)
here is the config files :

config.yml :
http://pastebin.com/7seDMQqz

pls help me :(

**Comment by md-5** [comment]
Not a bug, your other server is not reachable. Use the forums for support.
