### ISSUE TITLE
Changing server while flying with elytra makes you stuck in "flying mode"

### ISSUE THREAD

**Issue by checkium** [SpigotMC/BungeeCord#2059]
If you are flying with an elytra and you switch servers, you stay client-side in the floor, if you jump it slowly glides you to the floor, and the unique way to stop it is taking fall damage.

**Comment by md-5** [comment]
Cannot reproduce in build 1226.

Glided with elytra, used command to switch mid air, was placed on ground in other server just fine.

**Comment by Foorack** [comment]
Tested this today. I was able to reproduce. Bug still exist. Latest bungee (1234) and spigot (1.11.2) on both servers.

Player report: "fly with an elytra in creative or survival, warp to lobby, and don't touch any keys. The you will be stuck in elytra flight mode, free to fly around"

**Comment by Janmm14** [comment]
I assume your spawn points are not on the ground?

**Comment by Foorack** [comment]
@Janmm14 No, the server I help has the spawn point about 5-6 blocks above ground.
