### ISSUE TITLE
BungeeCord goes quiet

### ISSUE THREAD

**Issue by voigtman** [SpigotMC/BungeeCord#2060]
i have an issue with bungee suddenly going "quiet." There are no errors, perse, but all of a sudden all incomming pings from vote sites and the ability to ping and login with the game client cease. When I open the console screen to watch - buycraft is still pinging within the console but something with bungee itself seems to have shut down, locked up, or is hanging. If I type /end it gets to "closing IO threads" and thats it. I have to exit the screen, quit the screen and start a new one to reboot the proxy.

Using a dedicated host
Centos
Java 8
BungeeCord build 1226

**Comment by Phineas** [comment]
What plugins do you use & what start script?

**Comment by voigtman** [comment]
This is the same issue as #2061 

Last night I disabled VanillaPod 1.3 and the proxy has been running continuously since, so there may be a link... When updating to 1.11.2 I did notice this plugin broke all bungee MOTD plugins, annoying but not the biggest issue by far...

**Plugins**
- Alt Tracker
- AlwaysOnline
- Bungee Chat Filter
- Bungee Essentials
- Bungee Mail
- Bungee Perms
- Bungee Tab List
- Bungee YAML
- BuycraftX
- Command Control
- Execute Everywhere
- Maintenance Mode
- Move Me Now
- My Ping
- nuVotifier
- ProxySuite
- SchematicaPlugin
- Slash Server
- Super Anti Ad
- Ultimate Friends
- Vanilla Pod (disabled)
- Yamler Bungee

**Start Script:**
`#!/bin/sh
while true
do
   java -Xmx3G -jar BungeeCord-v1226b.jar
   sleep 5
done
`
