### ISSUE TITLE
Bungee freezes and will not turn off

### ISSUE THREAD

**Issue by govnojon** [SpigotMC/BungeeCord#2061]
The server runs for some time, and then suddenly stops responding! It appeared quite a long time ... I've got is the latest build. What can be wrong? Please correct
One more thing: it does not turn off the /end. there is a message "closing listeners" and all Bungee does not turn off

**Comment by Phineas** [comment]
Can we have the full log?

**Comment by govnojon** [comment]
He's already lost. But it does not have absolutely nothing, no errors.

**Comment by md-5** [comment]
Thread stack dump required.
