### ISSUE TITLE
Bungee randomly kicks players & stops responding, but it is alive

### ISSUE THREAD

**Issue by SwiftAdviser** [SpigotMC/BungeeCord#2062]
On my server I have a magic issue. :(
It doesn't print any errors or messages, doesn't save any files in the bungee dir! Bungeecord in random period of time kicks all players and doesn't send any responses to players, monitoring sites.
But it sends JMX stats and responses to console commands!

it is response of the command `/glist` after bungee have kicked all players:
https://pp.vk.me/c836322/v836322828/22508/2e_lUCt1r_k.jpg
But they are already had been kicked!

Also when I trying to disable bungee instance and writing `/end` process doesn't finish!

Oracle Java 8, Debian Jessie
Bungee and all services have been updated tonight! :(
#etopizdec

**Comment by SwiftAdviser** [comment]
List of bungee plugins:
![image](https://cloud.githubusercontent.com/assets/5148967/22835103/42ccd62c-efc0-11e6-88a9-97179ebd487a.png)

**Comment by Phineas** [comment]
Do you get any errors or know the kick message that players get?

**Comment by md-5** [comment]
Thread stack dump required.

**Comment by SwiftAdviser** [comment]
no errors, players just got "Disconnected".

**Comment by SwiftAdviser** [comment]
Why did you close the issue? I can add thread stack dump when it will be again, but I can't reproduce it, so we need some time to get this problem on production ._.

**Comment by SwiftAdviser** [comment]
Also this values I have in my zabbix monitoring, if it will help you.
![image](https://cloud.githubusercontent.com/assets/5148967/22850529/5fb6dd52-f013-11e6-8f3d-3606374e0626.png)

**Comment by Janmm14** [comment]
@SwiftAdviser he can also reopen issues

**Comment by md-5** [comment]
No read this,
https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr016.html

You also need to not be using plugins

**Comment by SwiftAdviser** [comment]
Thanks, I already have read this.

As I understood, I should make thread stack dump after all players have been kicked? But I can't reproduce this bug without plugins and with players, because it is my production server.

And if I will make it without plugins, on my local machine, I will never get this bug (or I must wait much more time).

It is contradictory things. Or it is needed for you, just to see all alive threads on the bungee?

**Comment by md-5** [comment]
All of the above.
If I can't reliably reproduce a bug or understand why it happens then its very hard to fix.

**Comment by SwiftAdviser** [comment]
YUP! I did it!

http://pastebin.com/Xy8WyUs5

Here is your data by "jstack -l JAVA_PID"

**Comment by SwiftAdviser** [comment]
Bungee had been stoped when 300 players was on it :(

**Comment by SwiftAdviser** [comment]
And I can make conclusion that all your netty threads had been locked. And after moment when the threads had locked by mysql queries that try to load users data, bungee stop responding.

And solution for this is write asynchronous mysql threads. Am I right?

**Comment by i9hdkill** [comment]
You can get support here:
https://www.spigotmc.org/forums/#bungeecord.33
Create a thread over there.
This is the issuetracker for BungeeCord not our support area for plugin problems.

**Comment by md-5** [comment]
ua.govnojon.libsbungee.modules.user.User.getSettings(User.java:141)

Bug in that plugin

**Comment by SwiftAdviser** [comment]
Thank you very much!
