### ISSUE TITLE
Random Disconnection

### ISSUE THREAD

**Issue by johnsoncui02** [SpigotMC/BungeeCord#2063]
I'm unsure of how to read this bug report and in need of guidance of what I did wrong here. The following is a bug report of what happened in the console.

Server Version: 1.8.8
Bungeecord Version: most current as of 2/11/2017
19:00:46 [INFO] [Chewfungus] <-> InitialHandler has connected
19:00:47 [INFO] [Chewfungus] <-> ServerConnector [skyblock] has connected
19:00:53 [INFO] [KirbyLegs] -> UpstreamBridge has disconnected
19:00:54 [INFO] [KirbyLegs] disconnected with: §f[Proxy] Lost connection to server.
19:00:54 [INFO] [KirbyLegs] <-> DownstreamBridge <-> [skyblock] has disconnected
19:00:55 [INFO] [/47.199.40.153:50588] <-> InitialHandler has connected
19:00:56 [INFO] [/47.199.40.153:50590] <-> InitialHandler has connected
19:00:56 [INFO] [/47.199.40.153:50591] <-> InitialHandler has connected
19:01:40 [INFO] [/47.199.40.153:50667] <-> InitialHandler has connected
19:01:40 [INFO] [KirbyLegs] <-> ServerConnector [skyblock] has connected
19:01:47 [INFO] [/47.199.40.153:50694] <-> InitialHandler has connected
19:01:48 [INFO] [/47.199.40.153:50693] <-> InitialHandler has connected
19:03:14 [INFO] Using OpenSSL based native cipher.
19:03:14 [INFO] Using native code compressor
19:03:14 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:6104354:1217
19:03:14 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
19:03:14 [INFO] Epoll is working, utilising it!
19:03:14 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
19:03:14 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
19:03:14 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
19:03:14 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
19:03:14 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
19:03:14 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
19:03:14 [INFO] Loaded plugin AlwaysOnline version 6.1 by Johnnywoof
19:03:14 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Loaded plugin BungeeShout version 1.0 by nhadobas
19:03:14 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] [AlwaysOnline] Loading configuration...
19:03:14 [WARNING] Forced host server hub is not defined
19:03:14 [INFO] [AlwaysOnline] Successfully loaded previous state variables!
19:03:14 [INFO] [AlwaysOnline] Loading file database...
19:03:14 [INFO] [AlwaysOnline] Database is ready to go!
19:03:14 [INFO] [AlwaysOnline] Mojang help page check: false
19:03:14 [INFO] [AlwaysOnline] Xpaw check: false
19:03:14 [INFO] [AlwaysOnline] Head Session server check: true
19:03:14 [INFO] [AlwaysOnline] Total check methods active: 1
19:03:14 [INFO] Enabled plugin AlwaysOnline version 6.1 by Johnnywoof
19:03:14 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] BungeeShout is enabling!
19:03:14 [INFO] Enabled plugin BungeeShout version 1.0 by nhadobas
19:03:14 [INFO] Enabled plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:6104354:1217 by SpigotMC
19:03:14 [INFO] Enabled plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:6104354:1217 by SpigotMC

**Comment by md-5** [comment]
Probably an issue with your plugins or network connection

**Comment by johnsoncui02** [comment]
appreicate the response. it happens to be the plugin connection having
issues. i end up removing it. Thanks :)
