### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Nerms** [SpigotMC/BungeeCord#2065]
12.02 20:01:17 [Server] INFO *** Warning, this build is outdated *** 12.02 20:01:17 [Server] INFO *** Please download a new build from http://ci.md-5.net/job/BungeeCord *** 12.02 20:01:17 [Server] INFO *** You will get NO support regarding this build *** 12.02 20:01:17 [Server] INFO *** Server will start in 10 seconds *** 12.02 20:01:28 [Server] INFO Using OpenSSL based native cipher. 12.02 20:01:28 [Server] INFO Using native code compressor 12.02 20:01:28 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"3973c51":1055 12.02 20:01:28 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource()) 12.02 20:01:28 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource()) 12.02 20:01:28 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource()) 12.02 20:01:28 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource()) 12.02 20:01:28 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource()) 12.02 20:01:28 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource()) 12.02 20:01:28 [Server] INFO Attempting to update plugin from ModuleVersion(build=101, git=488fb55) to ModuleVersion(build=1055, git=3973c51) 12.02 20:01:28 [Server] INFO Attempting to Jenkins download module cmd_alert v1055 12.02 20:01:39 [Server] INFO Download complete 12.02 20:01:39 [Server] INFO Attempting to update plugin from ModuleVersion(build=101, git=488fb55) to ModuleVersion(build=1055, git=3973c51) 12.02 20:01:39 [Server] INFO Attempting to Jenkins download module cmd_find v1055 12.02 20:01:52 [Server] INFO Download complete 12.02 20:01:52 [Server] INFO Attempting to update plugin from ModuleVersion(build=101, git=488fb55) to ModuleVersion(build=1055, git=3973c51) 12.02 20:01:52 [Server] INFO Attempting to Jenkins download module cmd_list v1055 12.02 20:01:52 [Server] INFO Download complete 12.02 20:01:52 [Server] INFO Attempting to update plugin from ModuleVersion(build=101, git=488fb55) to ModuleVersion(build=1055, git=3973c51) 12.02 20:01:52 [Server] INFO Attempting to Jenkins download module cmd_send v1055 12.02 20:01:53 [Server] INFO Download complete 12.02 20:01:53 [Server] INFO Attempting to update plugin from ModuleVersion(build=101, git=488fb55) to ModuleVersion(build=1055, git=3973c51) 12.02 20:01:53 [Server] INFO Attempting to Jenkins download module cmd_server v1055 12.02 20:02:09 [Server] INFO Failed to download: SocketTimeoutException : Read timed out @ java.net.SocketInputStream:-2 12.02 20:02:09 [Server] INFO Attempting to update plugin from ModuleVersion(build=101, git=488fb55) to ModuleVersion(build=1055, git=3973c51) 12.02 20:02:09 [Server] INFO Attempting to Jenkins download module reconnect_yaml v1055 12.02 20:02:11 [Server] INFO Download complete 12.02 20:02:11 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"3973c51":1055 by SpigotMC 12.02 20:02:11 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"3973c51":1055 by SpigotMC 12.02 20:02:11 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:488fb55:101 by WaterfallMC 12.02 20:02:11 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"3973c51":1055 by SpigotMC 12.02 20:02:11 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"3973c51":1055 by SpigotMC 12.02 20:02:11 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"3973c51":1055 by SpigotMC 12.02 20:02:11 [Server] SEVERE Exception in thread "main" 12.02 20:02:11 [Server] SEVERE java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map 12.02 20:02:11 [Server] SEVERE at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:209) 12.02 20:02:11 [Server] SEVERE at net.md_5.bungee.conf.Configuration.load(Configuration.java:73) 12.02 20:02:11 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:242) 12.02 20:02:11 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54) 12.02 20:02:11 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Somebody pleae help!

**Comment by Nerms** [comment]
Here's a Pastebin

http://pastebin.com/snDzJVX5

**Comment by Nerms** [comment]
It just says Loaded Modules but never loads..?

**Comment by md-5** [comment]
12.02 20:01:17 [Server] INFO *** Warning, this build is outdated *** 12.02 20:01:17 [Server] INFO *** Please download a new build from http://ci.md-5.net/job/BungeeCord 


Additionally your config is wrong.
Ask the forums for support.

**Comment by Nerms** [comment]
Are there any builds that support 1.7?

**Comment by i9hdkill** [comment]
Yes, but they don't support 1.9 or higher.
If you need any further help, jump on spigot IRC or ask in forums.
