### ISSUE TITLE
Copyright notice in README.md

### ISSUE THREAD

**Issue by ghost** [SpigotMC/BungeeCord#2067]
It still says 2016.

**Comment by RabsCodes** [comment]
A lot of companies haven't updated their copyright stuff for their sites and licenses etc. for years. I don't think it matters it says 2016, it's not that important.

**Comment by Phineas** [comment]
#2068

**Comment by Janmm14** [comment]
I guess next time a real change is happening to the code base, the years will be updated in a separate commit pushed together with the "real" change commit. This is to reduce unneccessary updates.

**Comment by md-5** [comment]
Was changed at some point
