### ISSUE TITLE
i get a very strange error

### ISSUE THREAD

**Issue by hooft99** [SpigotMC/BungeeCord#2072]
![k](https://cloud.githubusercontent.com/assets/24228593/23079071/8ddcee5a-f54b-11e6-8e5c-9ec3d90b4f9a.png)
For some reason everyone gets the same IP on my server, and that is my local pc name, and after the / my local IP, how do i fix this?

my config:
![k2](https://cloud.githubusercontent.com/assets/24228593/23079177/00e3592a-f54c-11e6-8db5-d1cc1293a792.png)
I hope you can help me out, because i have found no solutions on the internet!

hooft99

**Comment by Black-Hole** [comment]
Enable the bungeecord setting in the spigot.yml file of your servers.

**Comment by hooft99** [comment]
this solved my problem, much thanks to you :)
