### ISSUE TITLE
Bungeecord Cant connect to a default or fallback server please try again later io.netty.channel.ConnectTimeoutException

### ISSUE THREAD

**Issue by FiSH-Goldfish** [SpigotMC/BungeeCord#2073]
http://pastebin.com/YEVpB1DB i need the bungeecord server asap because its about to be released to friends and they want to see it

**Comment by md-5** [comment]
Your server is down or firewalled. Please use the forums for support.
<~md_5> .mcping 76.30.63.65:25566
<CafeBabe> (md_5) Request timed out

**Comment by FiSH-Goldfish** [comment]
My server is hosted on minecraft-hosting.pro

**Comment by FiSH-Goldfish** [comment]
and i turned it off so i can record
