### ISSUE TITLE
[1.12] Removing 1.8 Support ?

### ISSUE THREAD

**Issue by x9nico** [SpigotMC/BungeeCord#2074]
Hi, the 1.12's BungeeCord have not longer 1.8 support or he has always 1.8 support ?

**Comment by kamcio96** [comment]
BungeeCord supports 1.8. Why you want remove it?
What about list in config with allowed versions?

**Comment by i9hdkill** [comment]
You missunderstood him. He is asking if BungeeCord will drop support for 1.8 when 1.12 comes out. Like BungeeCord dropped support for 1.7 when 1.9 came out.

**Comment by md-5** [comment]
Don't know 1.12 isn't out

**Comment by Janmm14** [comment]
For me the current system looks pretty conclusive in essy support of new versions. I guess support won't be removed soon.
