### ISSUE TITLE
Change listening port by plugins

### ISSUE THREAD

**Issue by HAlexTM** [SpigotMC/BungeeCord#2077]
TL;DR Is there a way to change the proxy port by using a plugin?

Complete version:
I need to be able to change the default port to 25565 without touching the configuration file, is there a way by doing so within the onEnable method of a plugin?

**Comment by Phineas** [comment]
Not currently, as the netty listener starts before the plugin registry

**Comment by HAlexTM** [comment]
Is there a way to restart it?

**Comment by Phineas** [comment]
Well sure, you could just have a plugin that changes the config variables then stops bungee & have an auto-restart script on the bungee

**Comment by 1bytee** [comment]
You could actually just stop all listeners ([BungeeCord.getInstance().stopListeners()](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L344)), change the port (you need to change [this](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/config/ListenerInfo.java#L21) field, I'm sure you're gonna figure out how) and then just start the listeners ([BungeeCord.getInstance().startListeners()](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L294))

You can simply get the BungeeCord configuration and change the InetSocketAddress of the first entry in the list!

**Comment by HAlexTM** [comment]
Awesome @1bytee, thanks for figuring this out

**Comment by kamcio96** [comment]
@HAlexTM you can also use `iptables` to forward port 😉

**Comment by HAlexTM** [comment]
@kamcio96 that's not the case but thanks for the suggestion!

**Comment by Moehritz** [comment]
@HAlexTM this is entirely possible by replaceing the ConfigurationAdapter in onLoad()

`ProxyServer.getInstance().setConfigurationAdapter(bungeeConfig);`

If you want to you can delegate all method invocations to the original one, and only change the return value of `getListeners()`

**Comment by HAlexTM** [comment]
Thank you @Moehritz if I'll need it in the future I'll use this within my plugin, but right now I'm using an external way to solve this problem (templates)
I've closed this issue because I consider it resolved.
