### ISSUE TITLE
Bungeecord problem, Could not bind to host/WARNING Forced host server pvp is not defined

### ISSUE THREAD

**Issue by NKEND** [SpigotMC/BungeeCord#2081]
27.02 14:42:27 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher8466745719240153633.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
27.02 14:42:27 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
27.02 14:42:27 [Server] INFO Using native code compressor
27.02 14:42:27 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:b728aea:1216
27.02 14:42:27 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
27.02 14:42:27 [Server] INFO Epoll is working, utilising it!
27.02 14:42:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
27.02 14:42:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
27.02 14:42:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
27.02 14:42:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
27.02 14:42:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
27.02 14:42:27 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
27.02 14:42:27 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] WARNING Forced host server pvp is not defined
27.02 14:42:27 [Server] INFO Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Enabled plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:27 [Server] INFO Enabled plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:b728aea:1216 by SpigotMC
27.02 14:42:28 [Server] WARNING Could not bind to host /.............
27.02 14:42:28 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: bind() failed: Cannot assign requested address
27.02 14:42:28 [Server] INFO at io.netty.channel.unix.Errors.newIOException(Errors.java:117)
27.02 14:42:28 [Server] INFO at io.netty.channel.unix.Socket.bind(Socket.java:234)
27.02 14:42:28 [Server] INFO at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:91)
27.02 14:42:28 [Server] INFO at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
27.02 14:42:28 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
27.02 14:42:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:512)
27.02 14:42:28 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:497)
27.02 14:42:28 [Server] INFO at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
27.02 14:42:28 [Server] INFO at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
27.02 14:42:28 [Server] INFO at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:363)
27.02 14:42:28 [Server] INFO at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
27.02 14:42:28 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
27.02 14:42:28 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
27.02 14:42:28 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
27.02 14:42:28 [Server] INFO at java.lang.Thread.run(Unknown Source)

**Comment by md-5** [comment]
Your config has a listener IP defined which is not present on your server. Kep listener IPs as 0.0.0.0 unless you know what you are doing
