### ISSUE TITLE
Somewhat problem when compiling plugin using Bungee's API.

### ISSUE THREAD

**Issue by SimSonic** [SpigotMC/BungeeCord#2082]
Hello. I'm trying to compile my plugin (one jar contains code both for Bukkit and Bungee) and it depends on BungeeCord-API:

```xml
<repository>
	<id>nexus-oss-snapshots-repo</id>
	<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
</repository>

...

<dependency>
	<groupId>net.md-5</groupId>
	<artifactId>bungeecord-api</artifactId>
	<version>1.11-SNAPSHOT</version>
	<scope>provided</scope>
</dependency>
```

So mvn process is going to die: http://pastebin.com/3NS4vjzv

I believe that something that causes this is on your side.
When I change "version" tag to the 1.10-SNAPSHOT, 1.9-SNAPSHOT and older, all works and plugins builds.
There are lines noting about internal linking of 1.10 jars in the log (lines 9, 10).

**Comment by md-5** [comment]
Could not transfer metadata net.md-5:bungeecord-api:1.11-SNAPSHOT/maven-metadata.xml from/to methuselah-repo (https://maven.methuselah.ru/): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target


You have configured your own maven repo in a way that is incompatible, its on your end

**Comment by Black-Hole** [comment]
Certificates for "Let's encrypt" are included in Java 8 with Update 101 and higher.

**Comment by SimSonic** [comment]
This is not a case.
I've updated jdk so there is no more https warnings, but maven errors are still here.

Hovewer, CI builds are OK.
Probably it can be something in my local IDE.

Thanks.
