### ISSUE TITLE
IP Forwarding Error - All servers on one machine

### ISSUE THREAD

**Issue by B-Knight49** [SpigotMC/BungeeCord#2083]
So, I've got Bungee and all of my servers on 1 machine with 16GB of RAM. 

I've set everything up, I believe, correctly but I get an error when joining saying "If you wish to use IP Forwarding, please enable it in your BungeeCord config as well!"

Is there some other way to setup BungeeCord when running off of one machine? I'm assuming it's different to using multiple. I'd appreciate any help/even a step-by-step guide on settings up Bungee when it's on a single server. 

Spigot: spigot-1.8-R0.1-SNAPSHOT-latest

BungeeCord: 1.8-SNAPSHOT:"e1951c5":1050

Config:

`groups:
  BKnight_:
  - admin
disabled_commands:
- disabledcommandhere
player_limit: -1
stats: bd8a66a6-0000-4b26-a4f2-129da452d202
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  forced_hosts:
    pvp.md-5.net: hub
  ping_passthrough: false
  default_server: hub
  bind_local_address: false
  fallback_server: hub
  host: 172.31.xx.xxx:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
timeout: 30000
connection_throttle: -1
servers:
  hub:
    motd: '&1Just another BungeeCord - Forced Host'
    address: mc.thexxxxxxx.com:25566  (This domain has been associated with the IP: 52.56.xxx.xxx)
    restricted: false
ip_forward: true
online_mode: true
`

**Comment by kamcio96** [comment]
Probably you're connecting to server without Bungee. Do you have login log in Bungee console?

On one machine it's better to use localhost in server.properties and server's section in config.yml

**Comment by 1bytee** [comment]
1. Make sure you set [bungeecord](https://www.spigotmc.org/wiki/spigot-configuration/) to true in your spigot.yml 
2. You can update to the latest version of BungeeCord since it supports 1.8 - 1.11 (maybe there was an update that already fixed this problem)

(and you should update your Spigot to 1.8.8 imo)

**Comment by B-Knight49** [comment]
@kamcio96 I heard this elsewhere and tried it out but I wasn't sure how to join. I've tried it again now, and what IP do I enter/do clients enter to join the server?

@1bytee Bungeecord is set to true and I've updated my BungeeCord. Thanks for the suggestion. I might actually update my spigot too. Cheers for the suggestions!

**Comment by kamcio96** [comment]
Clients have to use 172... ip. Are you using docker?

**Comment by B-Knight49** [comment]
@kamcio96 The 172 IP is private. I can't use the public IP as it says "Cannot bind to address".

**Comment by kamcio96** [comment]
Do you have discord? My account: kamcio96#8278

**Comment by B-Knight49** [comment]
I have teamspeak, can you come on there instead? I'm currently talking with another Owner about the server on here:

ts.themultiserver.com

**Comment by 1bytee** [comment]
Localhost should be fine if you're running BungeeCord and Spigot on the same machine... Maybe try to set the bungeecord host to 0.0.0.0 and the address of the hub server to localhost or 127.0.0.1

that might solve your problem

**Comment by B-Knight49** [comment]
@1bytee Nope, now it can't even connect to the server when I enter all 3 addresses.

**Comment by kamcio96** [comment]
Nvm
Your private IP is eg 172.31.1.2. Set it as Bungee host, or set 0.0.0.0 there. 
Clients have to connect with public IP which is redirected to private.

1. Now servers, if it's same machine set it to localhost (in server.properties and in bungee's config.yml)

2. If it's not same machine. Set public IP in bungee's config and private IP in server.properties

**Comment by 1bytee** [comment]
Yea make sure you also set the spigot ip to localhost too... forgot about that

**Comment by i9hdkill** [comment]
You may find an answer in our BungeeCord wiki or join our forums for support.

**Comment by B-Knight49** [comment]
@kamcio96 @1bytee I've done all of the things you guys have suggested and it still isn't working.

I've set the 'host: 0.0.0.0:25565' I've set the 'server-properties, server-ip: localhost' and I've set the '- hub, address: localhost' and it's not connecting to the server and nothing is appearing in the Bungee log indicating that someone has connected. I'm also getting no errors but the server just isn't connecting when using the public IP address of the server.

**Comment by kamcio96** [comment]
any login logs on bungee?

**Comment by B-Knight49** [comment]
@kamcio96 14:53:59 [INFO] [BKnight_] <-> ServerConnector [hub] has connected
14:53:59 [INFO] [BKnight_] disconnected with: Kicked whilst connecting to hub: You have to join through the proxy.
14:53:59 [INFO] [BKnight_] <-> ServerConnector [hub] has disconnected
14:53:59 [INFO] [BKnight_] -> UpstreamBridge has disconnected

**Comment by drakeliemmore** [comment]
hey could u guys help me, im also having this issue

[00:38:30 INFO]: /1xx.1xx.1xx.2xx:53596 lost connection: If you wish to use IP forwarding, please enable it in your BungeeCord config as well!

I turned the settings on spigot.yml, bungeecord: true

Here is my config.yml from Bungeecord folder:

groups:
  BankOfGenius:
  - admin
ip_forward: true
forge_support: false
network_compression_threshold: 256
stats: 8ec823ac-2680-4bb5-8459-f413f6a3fa34
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
servers:
  lobby:
    motd: '&4Welcome to RaidClass!'
    address: localhost:5900
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  default_server: lobby
  fallback_server: lobby
  priorities:
  - lobby
  bind_local_address: false
  host: 1xx.1xx.1xx.xxx:25565
  max_players: 50
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
player_limit: -1
disabled_commands:
- disabledcommandhere
log_commands: false
connection_throttle: -1

Please help :D
