### ISSUE TITLE
Runtime Exception Error!

### ISSUE THREAD

**Issue by MisfitNetwork** [SpigotMC/BungeeCord#2084]
Exception Connecting:Runtime Exception : Server is online mode! @ net.md_5.bungee.ServerConnector:270

Here is my config(Ip's are 'blockedip' blocked usernames are 'blockedusername'):
http://pastebin.com/UkGbfKjp

I don't currently have any spigot servers connected. I'm just trying to connect to the Bungee Server itself. If your able to help please do! Thanks

**Comment by kamcio96** [comment]
You can't connect Bungee to itself. It's ridiculously. It isn't issue. 

For support and testing pls use forum.
