### ISSUE TITLE
PROBLEM WHIT BUNGEE CORD SEVERE Exception in thread "main"

### ISSUE THREAD

**Issue by Encients** [SpigotMC/BungeeCord#2085]
I have problem whit SEVERE Exception in thread "main"
CONSOLE LOG
04.03 12:57:46 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
04.03 12:57:46 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:"28496e0":1036
04.03 12:57:46 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
04.03 12:57:46 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
04.03 12:57:46 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
04.03 12:57:46 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
04.03 12:57:46 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
04.03 12:57:46 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
04.03 12:57:46 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
04.03 12:57:46 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
04.03 12:57:46 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
04.03 12:57:46 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
04.03 12:57:46 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
04.03 12:57:46 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.8-SNAPSHOT:"28496e0":1036 by SpigotMC
04.03 12:57:46 [Server] SEVERE Exception in thread "main" 

THIS IS MY CONFIG

groups:
  TheKipha:
  - admin
disabled_commands:
- find
player_limit: -1
stats: 640a134f-9ebd-41e1-9633-d05ed75b4b6d
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
listeners:
- fallback_server: lobby
  max_players: 400
  host: 192.99.2.42:25565
  tab_size: 60
  force_default_server: true
  tab_list: GLOBAL_PING
  motd: '&9Splash &fNetwork - &41.6.2'
  default_server: lobby
  forced_hosts: []
timeout: 30000
connection_throttle: 4000
servers:
  lobby:
    address: 127.0.0.1:21620
    restricted: false
    motd: '&9Splash &fNetwork - &41.6.2'
  survival:
    address: 127.0.0.1:21621
    restricted: false
    motd: '&9Splash &fSurvival - &41.6.2'
  Svtres:
    address: 127.0.0.1:21622
    restricted: false
    motd: '&9Splash &fCreative - &41.6.2'
  Svcuatro:
    address: 127.0.0.1:21623
    restricted: false
    motd: '&9Splash&fPvP - &41.6.2'
online_mode: false

**Comment by Janmm14** [comment]
for general help with bungeecord please go to https://www.spigotmc.org/forums/bungeecord-help.70/
