### ISSUE TITLE
Server lags when a player joins it

### ISSUE THREAD

**Issue by ArciParci** [SpigotMC/BungeeCord#2087]
We are using bungeecord on external vps, and the rest of the servers, including the auth one are on a dedicated
server lags for 3-5 seconds when some players are joinning the server

this is the error that appears in the console when the lag occures
21:41:23 [WARNING] Event LoginEvent(cancelled=false, cancelReasonComponents=null, connection=[AliJunioru] <-> InitialHandler) took 4,684,531,686ns to process!
21:41:23 [WARNING] Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[AliJunioru] <-> InitialHandler) took 4,685,639,926ns to process!

the thing is that we didn't add or remove any plugins when we switched bungeecord on the vps
PS: the problem didn't existed when all the servers were on the dedicated

the servers are organised this way:
dedicated server 1: auth, survival, factions skyblock etc
dedicated server 2( external vps): lobby(hub) with bungee

**Comment by kamcio96** [comment]
Bungee plugins?

**Comment by ArciParci** [comment]
BungeeAuthMeBridge
BungeePerms
BungeeReport
BungeeWeb
LiteAnnouncer

**Comment by md-5** [comment]
Plugin issue
