### ISSUE TITLE
Bungeecord Not Opening PLZ HELP ASAP

### ISSUE THREAD

**Issue by SquishyBread** [SpigotMC/BungeeCord#2088]
So I have started a Bungeecord server with the ip: 104.149.238.215:25565
I have contacted support and said they cant do it for me I tried tutorials but non of them worked/helped! I am going to put a copy of everything here! Please reply ASAP!

CONSOLE : 
10.03 03:55:16 [Multicraft] Loading server properties
10.03 03:55:16 [Multicraft] Starting server!
10.03 03:55:16 [Multicraft] Loaded config for "Default Minecraft Server"
10.03 03:55:16 [Multicraft] Updating eula.txt file
10.03 03:55:16 [Server] INFO Using OpenSSL based native cipher.
10.03 03:55:16 [Server] INFO Using native code compressor
10.03 03:55:16 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:cb60d08:1227
10.03 03:55:17 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
10.03 03:55:17 [Server] INFO Epoll is working, utilising it!
10.03 03:55:17 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
10.03 03:55:17 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
10.03 03:55:17 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
10.03 03:55:17 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
10.03 03:55:17 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
10.03 03:55:17 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
10.03 03:55:17 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:cb60d08:1227 by SpigotMC
10.03 03:55:17 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:cb60d08:1227 by SpigotMC
10.03 03:55:17 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:cb60d08:1227 by SpigotMC
10.03 03:55:17 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:cb60d08:1227 by SpigotMC

Config.yml
groups:
  md_5:
  - admin
ip_forward: false
network_compression_threshold: 256
stats: b10fc409-069e-4feb-9341-38f97bbd1e92
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 	104.149.238.215:25565
    restricted: false
timeout: 30000
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  priorities:
  - lobby
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25577
  forced_hosts:
    pvp.md-5.net: pvp
  max_players: 1
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
player_limit: -1
disabled_commands:
- disabledcommandhere
log_commands: false
connection_throttle: 4000

Server.proterties <however its spelled

server-ip=104.149.238.215
server-port=25565
max-players=50
level-name=world
pvp=true
motd=
allow-nether=false
op-permission-level=1
player-idle-timeout=
gamemode=1
spawn-animals=false
generator-settings=
texture-pack=
hellworld=false
level-type=DEFAULT
generate-structures=false
difficulty=1
view-distance=
hardcore=true
allow-flight=true
online-mode=true
spawn-monsters=false
force-gamemode=true
spawn-npcs=true
white-list=false
announce-player-achievements=false
max-build-height=
level-seed=

Please help me the best thing you can do is sending them again with the fixed configurations! 
Thank You

~CraftiteMania, Owner

**Comment by kamcio96** [comment]
Pls use forum for support and pastebin for logs and config files.
