### ISSUE TITLE
Erro pls guide fix this :|

### ISSUE THREAD

**Issue by FlexVN** [SpigotMC/BungeeCord#2089]
01:29:39 [INFO] [/103.9.159.245:59039] <-> InitialHandler has connected
01:29:39 [INFO] [/103.9.159.245:59040] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59041] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59042] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59043] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59044] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59045] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59046] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59047] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59048] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59049] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59050] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59051] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59052] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59053] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59054] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59055] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59056] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59057] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59058] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59059] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59060] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59062] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59063] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59064] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59065] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59066] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59067] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59068] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59069] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59070] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59071] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59072] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59073] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59074] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59075] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59076] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59077] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59078] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59079] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59080] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59081] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59082] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59083] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59084] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59085] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59086] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59087] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59088] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59089] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59090] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59091] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59092] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59093] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59094] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59095] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59096] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59097] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59098] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59099] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59100] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59101] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59102] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59103] <-> InitialHandler has connected
01:29:40 [INFO] [HieuZKG] <-> ServerConnector [Skywars] has connected
01:29:40 [INFO] [/103.9.159.245:59105] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59106] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59107] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59108] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59109] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59110] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59111] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59112] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59113] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59114] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59115] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59116] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59117] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59118] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59119] <-> InitialHandler has connected
01:29:40 [INFO] [/103.9.159.245:59120] <-> InitialHandler has connected
103.9.159.245 is my IP address server address
103.9.159.245 is this IP address it bugs on cmd

**Comment by md-5** [comment]
Would seem like you've set bungee to connect to itself.
Please use the forums at spigotmc.org for aupport and be sure to share your config.
