### ISSUE TITLE
My Servers Keep Change Online Mode To True 

### ISSUE THREAD

**Issue by FiSH-Goldfish** [SpigotMC/BungeeCord#2090]
Hello ! I have a problem with my server. My servers always changes the online mode in server.properties true when I set it to false.Can u help me plz. 

Thanks,
    FiSH_Goldfish

**Comment by FiSH-Goldfish** [comment]
I also forgot to tell u the server ip is MiniMCReborn.evils.in or 76.30.63.65

**Comment by md-5** [comment]
This is probably an issue with the configuration of your host panel.
Try changing the settings there or contact your host
