### ISSUE TITLE
Spigot uuid differs from bungeecord uuid

### ISSUE THREAD

**Issue by toonsevrin** [SpigotMC/BungeeCord#2091]
We are running a bungeecord network behind a loadbalancing layer, due to this loadbalancing layer, the ips are lost and we can't enable bungeecord: true in the spigot config. Is there a way to retain the player uuids without having to enable the ip retention protocol?

Reprod: Put bungeecord: false in spigot configuration and ipforward: false in bungee, then compare uuids

**Comment by toonsevrin** [comment]
We were able to enable the ip forwarding, even with our proxy after some tweaks. So this is no longer an issue, though it may remain interesting to decouple the uuid protocol from the ip forwarding protocol.

**Comment by md-5** [comment]
This is because the server is offline mode so will have different uuids to online mode bungee.
We cannot fix this, its not in our control

**Comment by toonsevrin** [comment]
Apparently it is because with IP forwarding it works.

**Comment by md-5** [comment]
Because IP forwarding is an extension we built to overcome exactly this issue.
IP retention and UUID retention are the same protocol built by bungee for bungee and it makes no sense to decouple them

**Comment by toonsevrin** [comment]
Yeh it works now so I have no issue with this.

Anyway, we needed some kind of IP load balancer as our bungee instances are very short lived. An IP balancer that never needs updating is very attractive compared with the bungeecord instances that constantly get swapped with plugin/bungeecord updates, mainly because of DNS downtime. There's a performance cost but the predictability of Kubernetes services outweighs it.
