### ISSUE TITLE
You have to join through the proxy error message

### ISSUE THREAD

**Issue by Ne0nDelta** [SpigotMC/BungeeCord#2093]
I try to connect to my bungeecord server and it says You have to join through the proxy and i dont have any plugins.

**Comment by kamcio96** [comment]
You have to setup correctly IPWhitelist plugin. For support use forum

**Comment by Ne0nDelta** [comment]
but this is a public server
i want alot of people to join

**Comment by Ne0nDelta** [comment]
this has never happened to me before

**Comment by md-5** [comment]
Read the instructions re the plugin you installed.

**Comment by Ne0nDelta** [comment]
what? i am confused

**Comment by Janmm14** [comment]
No bungeecord issue.
For support use the spigotmc.org forum.
