### ISSUE TITLE
Not able to use the "restricted" option in the config

### ISSUE THREAD

**Issue by gtavbeastaya** [SpigotMC/BungeeCord#2094]
Was trying to set up a little system using the `restricted: true` in the configuation, however it doesn't appear to be working, as it lets me join the server that I'm trying to restrict even though I do not have permissions.

`ip_forward: true
network_compression_threshold: 512
stats: bd84e92c-52e3-4754-9ff4-7b8d870dd293
groups:
  2F4U:
  - queue
servers:
  queue:
    motd: fsdfsdf
    address: 127.0.0.1:54321
    restricted: false
  main:
    motd: fsdfsdf
    address: 127.0.0.1:12346
    restricted: true
timeout: 30000
player_limit: -1
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  priorities:
  - queue
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25566
  forced_hosts:
    4b4t.us: main
  max_players: 2000
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
permissions:
  queue:
  - bungeecord.command.server
  - bungeecord.command.list
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: true
log_commands: false
disabled_commands:
- server
connection_throttle: 4000`

there's my config.

any ideas?

**Comment by md-5** [comment]
Restricted only applies to the inbuilt /server command.

**Comment by Baterka** [comment]
Wait really?
