### ISSUE TITLE
Bungeecord won't start up after switching from v1225 to v1119

### ISSUE THREAD

**Issue by goscoobye** [SpigotMC/BungeeCord#2095]
Hi, I have a pretty big problem. I have been using version1225 of bungee for the past week as I need bungee for my server. Unfortunately, it doesn't support any MC version under 1.8...
I downloaded version1119 as it said it has support for versions under 1.8! I downloaded, used FileZilla to throw it into my server jar and set the bungee server to default and typed in the files name (I renamed it from bungeecord.jar to bungeecord1.7.10.jar)
I started up my server with the hope of it working but it was unfortunately offline. I gave it five minutes thinking it just needed some time but nothing happened. 
My server console was only putting out this message
`18.03 13:46:54 [Server] INFO *** Warning, this build is outdated ***
18.03 13:46:54 [Server] INFO *** Please download a new build from http://ci.md-5.net/job/BungeeCord ***
18.03 13:46:54 [Server] INFO *** You will get NO support regarding this build ***
18.03 13:46:54 [Server] INFO *** Server will start in 10 seconds ***
18.03 13:47:04 [Server] INFO Could not load native library: /tmp/bungeecord-native-cipher1465899580797730947.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
18.03 13:47:04 [Server] INFO Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
18.03 13:47:04 [Server] INFO Using native code compressor
18.03 13:47:04 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.8-SNAPSHOT:7d2c2ab:1119
18.03 13:47:05 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
18.03 13:47:05 [Server] INFO Epoll is working, utilising it!
18.03 13:47:05 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
18.03 13:47:05 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
18.03 13:47:05 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
18.03 13:47:05 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
18.03 13:47:05 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
18.03 13:47:05 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
18.03 13:47:05 [Server] INFO Attempting to update plugin from ModuleVersion(build=1225, git=950d504) to ModuleVersion(build=1119, git=7d2c2ab)
18.03 13:47:05 [Server] INFO Attempting to Jenkins download module cmd_alert v1119
18.03 13:47:05 [Server] INFO Download complete
18.03 13:57:04 [Multicraft] Auto-saving world...`

I don't know what to do and am at a loss right now. Even after I tried to switch it back to version1225 I would get pretty much the same error message. Any help at all is good and I am releasing my server soon so I need to get this problem fixed pronto. Thanks!

**Comment by md-5** [comment]
If you're the guy on twitter, this log is incomplete and you corrupted your config.yml

**Comment by goscoobye** [comment]
Yep I realized what I did wrong.
