### ISSUE TITLE
[Proxy] Lost Connection to Server

### ISSUE THREAD

**Issue by Vlad2000MC** [SpigotMC/BungeeCord#2096]
Hello ! When i connect to my bungee server and enter to Survival, for example, after 5 or 10 minutes kick all players, or only 1/2, with reason "[Proxy] Los Connection to Server".
I have last version of BungeeCorde and modules.
What can i do ?

Logs:
10:56:03 [INFO] Could not load native library: /tmp/bungeecord-native-cipher3487020866511233713.so: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
10:56:03 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
10:56:03 [INFO] Using native code compressor
10:56:03 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:01f4448:1226
10:56:03 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
10:56:03 [INFO] Epoll is working, utilising it!
10:56:03 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
10:56:03 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
10:56:03 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
10:56:03 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
10:56:03 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
10:56:03 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
10:56:03 [INFO] Attempting to update plugin from ModuleVersion(build=1228, git=53cc324) to ModuleVersion(build=1226, git=01f4448)
10:56:03 [INFO] Attempting to Jenkins download module cmd_alert v1226
10:56:05 [INFO] Download complete
10:56:05 [INFO] Attempting to update plugin from ModuleVersion(build=1228, git=53cc324) to ModuleVersion(build=1226, git=01f4448)
10:56:05 [INFO] Attempting to Jenkins download module cmd_find v1226
10:56:05 [INFO] Download complete
10:56:05 [INFO] Attempting to update plugin from ModuleVersion(build=1228, git=53cc324) to ModuleVersion(build=1226, git=01f4448)
10:56:05 [INFO] Attempting to Jenkins download module cmd_list v1226
10:56:05 [INFO] Download complete
10:56:05 [INFO] Attempting to update plugin from ModuleVersion(build=1228, git=53cc324) to ModuleVersion(build=1226, git=01f4448)
10:56:05 [INFO] Attempting to Jenkins download module cmd_send v1226
10:56:06 [INFO] Download complete
10:56:06 [INFO] Attempting to update plugin from ModuleVersion(build=1228, git=53cc324) to ModuleVersion(build=1226, git=01f4448)
10:56:06 [INFO] Attempting to Jenkins download module cmd_server v1226
10:56:07 [INFO] Download complete
10:56:07 [INFO] Attempting to update plugin from ModuleVersion(build=1228, git=53cc324) to ModuleVersion(build=1226, git=01f4448)
10:56:07 [INFO] Attempting to Jenkins download module reconnect_yaml v1226
10:56:07 [INFO] Download complete
10:56:07 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Loaded plugin SkinsRestorer version 12.9.7 by Blackfire62, Th3Tr0LLeR
10:56:07 [INFO] Loaded plugin BungeeAuthMeBridge version 1.6.2 by CryLegend
10:56:07 [INFO] Loaded plugin BungeeAdvancedMotd version b1.2 by w67clement
10:56:07 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [WARNING] Forced host server pvp is not defined
10:56:07 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Enabled plugin SkinsRestorer version 12.9.7 by Blackfire62, Th3Tr0LLeR
10:56:07 [INFO] Enabled plugin BungeeAuthMeBridge version 1.6.2 by CryLegend
10:56:07 [INFO] ?7[?6Bungee?3Advanced?2Motd?7]?r ?aStarting load configuration...
10:56:07 [INFO] ?7[?6Bungee?3Advanced?2Motd?7]?r ?aConfiguration was loaded successfully!...
10:56:07 [INFO] Enabled plugin BungeeAdvancedMotd version b1.2 by w67clement
10:56:07 [INFO] Enabled plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [INFO] Enabled plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:01f4448:1226 by SpigotMC
10:56:07 [SEVERE] Mar 17, 2017 10:56:07 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: e6:bf:d8:8c:f8:2e:cf:cb

10:56:07 [INFO] Listening on /89.34.25.187:25565
10:56:07 [INFO] Started query on /89.34.25.187:25565
10:56:07 [INFO] 
10:56:07 [INFO] ?a +===============+
10:56:07 [INFO] ?a | SkinsRestorer |
10:56:07 [INFO] ?a +===============+
10:56:07 [INFO] 
10:56:07 [INFO] ?a STABLE BUILD
10:56:07 [INFO] 
10:56:07 [INFO] ?b Current version: ?a12.9.7
10:56:07 [INFO] ?a The latest version!
10:56:07 [INFO] 
11:05:12 [INFO] [/213.239.204.169:40606] <-> InitialHandler has connected
11:15:12 [INFO] [/213.239.204.169:39652] <-> InitialHandler has connected
11:45:11 [INFO] [/213.239.204.169:36009] <-> InitialHandler has connected
11:55:15 [INFO] [/213.239.204.169:37396] <-> InitialHandler has connected
12:05:12 [INFO] [/213.239.204.169:38799] <-> InitialHandler has connected
12:15:15 [INFO] [/213.239.204.169:42688] <-> InitialHandler has connected
12:25:12 [INFO] [/213.239.204.169:47091] <-> InitialHandler has connected
12:32:22 [INFO] [/81.181.81.190:52174] <-> InitialHandler has connected
12:35:17 [INFO] [/213.239.204.169:49979] <-> InitialHandler has connected
12:55:14 [INFO] [/213.239.204.169:54799] <-> InitialHandler has connected
13:01:50 [INFO] [/109.99.98.231:1420] <-> InitialHandler has connected
13:02:23 [INFO] [/109.99.98.231:1466] <-> InitialHandler has connected
13:05:13 [INFO] [/213.239.204.169:60681] <-> InitialHandler has connected
13:05:49 [INFO] [/86.127.117.22:60865] <-> InitialHandler has connected
13:05:50 [INFO] [/86.127.117.22:60870] <-> InitialHandler has connected
13:15:18 [INFO] [/213.239.204.169:40563] <-> InitialHandler has connected
13:17:05 [INFO] [/188.241.133.12:50902] <-> InitialHandler has connected
13:17:18 [INFO] [/86.127.117.22:61032] <-> InitialHandler has connected
13:17:19 [INFO] [/86.127.117.22:61037] <-> InitialHandler has connected
13:18:28 [INFO] [/86.127.117.22:61192] <-> InitialHandler has connected
13:18:29 [INFO] [/86.127.117.22:61197] <-> InitialHandler has connected
13:20:10 [INFO] [/86.127.117.22:61239] <-> InitialHandler has connected
13:20:11 [INFO] [/86.127.117.22:61244] <-> InitialHandler has connected
13:22:09 [WARNING] [/81.181.81.190:52174] <-> InitialHandler - NativeIoException: syscall:read(...)() failed: Connection reset by peer
13:23:13 [INFO] [/81.181.81.190:56647] <-> InitialHandler has connected
13:24:31 [INFO] [/86.127.117.22:61300] <-> InitialHandler has connected
13:24:33 [INFO] [/86.127.117.22:61305] <-> InitialHandler has connected
13:31:37 [INFO] [/188.241.133.12:50963] <-> InitialHandler has connected
13:35:15 [INFO] [/213.239.204.169:53692] <-> InitialHandler has connected
13:45:20 [INFO] [/213.239.204.169:60966] <-> InitialHandler has connected
13:48:32 [INFO] [/81.181.81.190:57828] <-> InitialHandler has connected
14:20:03 [WARNING] [/81.181.81.190:56647] <-> InitialHandler - NativeIoException: syscall:read(...)() failed: Connection reset by peer
14:20:03 [WARNING] [/81.181.81.190:57828] <-> InitialHandler - NativeIoException: syscall:read(...)() failed: Connection reset by peer
14:28:33 [INFO] [/79.115.6.237:54478] <-> InitialHandler has connected
14:32:27 [INFO] [/79.115.6.237:54696] <-> InitialHandler has connected
14:32:29 [INFO] [/79.115.6.237:54712] <-> InitialHandler has connected
14:35:18 [INFO] [/213.239.204.169:37162] <-> InitialHandler has connected
14:36:04 [INFO] [/79.115.6.237:54959] <-> InitialHandler has connected
14:38:34 [INFO] [/78.96.225.32:9893] <-> InitialHandler has connected
15:05:14 [INFO] [/213.239.204.169:60716] <-> InitialHandler has connected
15:15:19 [INFO] [/213.239.204.169:37546] <-> InitialHandler has connected
15:15:31 [INFO] [/89.123.98.84:64451] <-> InitialHandler has connected
15:15:38 [INFO] [/89.123.98.84:64455] <-> InitialHandler has connected
15:26:46 [INFO] [/92.80.243.122:14466] <-> InitialHandler has connected
15:27:40 [INFO] [/92.80.243.122:14625] <-> InitialHandler has connected
15:32:10 [INFO] [/92.80.243.122:14972] <-> InitialHandler has connected
15:35:13 [INFO] [/213.239.204.169:36665] <-> InitialHandler has connected
15:45:15 [INFO] [/92.80.243.122:16054] <-> InitialHandler has connected
15:45:15 [INFO] [/213.239.204.169:44812] <-> InitialHandler has connected
15:48:33 [INFO] [/92.80.243.122:16331] <-> InitialHandler has connected
15:53:59 [INFO] [/92.80.243.122:16761] <-> InitialHandler has connected
15:55:16 [INFO] [/213.239.204.169:54834] <-> InitialHandler has connected
16:05:19 [INFO] [/213.239.204.169:36432] <-> InitialHandler has connected
16:15:19 [INFO] [/213.239.204.169:46179] <-> InitialHandler has connected
16:26:13 [INFO] [/89.34.214.246:49260] <-> InitialHandler has connected
16:26:14 [INFO] [/89.34.214.246:49273] <-> InitialHandler has connected
16:26:15 [INFO] [/89.34.214.246:49284] <-> InitialHandler has connected
16:26:15 [INFO] [/89.34.214.246:49297] <-> InitialHandler has connected
16:26:16 [INFO] [/89.34.214.246:49309] <-> InitialHandler has connected
16:26:16 [INFO] [/89.34.214.246:49321] <-> InitialHandler has connected
16:26:17 [INFO] [/89.34.214.246:49333] <-> InitialHandler has connected
16:26:17 [INFO] [/89.34.214.246:49345] <-> InitialHandler has connected
16:35:15 [INFO] [/213.239.204.169:41517] <-> InitialHandler has connected
16:45:18 [INFO] [/213.239.204.169:49570] <-> InitialHandler has connected
16:55:36 [INFO] [/213.239.204.169:34207] <-> InitialHandler has connected
17:05:19 [INFO] [/213.239.204.169:43702] <-> InitialHandler has connected
17:06:59 [INFO] [/78.96.225.32:3222] <-> InitialHandler has connected
17:09:57 [INFO] [/78.96.225.32:16408] <-> InitialHandler has connected
17:19:22 [INFO] [/78.96.225.32:17319] <-> InitialHandler has connected
17:19:59 [INFO] [/78.96.225.32:16404] <-> InitialHandler has connected
17:22:08 [INFO] [/78.96.225.32:15181] <-> InitialHandler has connected
17:24:38 [INFO] [/78.96.225.32:16956] <-> InitialHandler has connected
17:25:34 [INFO] [/213.239.204.169:46494] <-> InitialHandler has connected
17:27:27 [INFO] [/78.96.225.32:10085] <-> InitialHandler has connected
17:28:49 [INFO] [/78.96.225.32:6766] <-> InitialHandler has connected
17:32:13 [INFO] [/92.80.243.122:22318] <-> InitialHandler has connected
17:32:59 [INFO] [/92.80.243.122:22473] <-> InitialHandler has connected
17:33:44 [INFO] [/92.80.243.122:22601] <-> InitialHandler has connected
17:35:32 [INFO] [/213.239.204.169:58376] <-> InitialHandler has connected
17:40:18 [INFO] [/109.98.122.28:55509] <-> InitialHandler has connected
17:40:18 [INFO] [/109.98.122.28:55510] <-> InitialHandler has connected
17:40:19 [WARNING] Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[BlackSky] <-> InitialHandler) took 355,043,590ns to process!
17:40:22 [INFO] [BlackSky] <-> ServerConnector [lobby] has connected
17:42:38 [INFO] [BlackSky] <-> ServerConnector [apocalipsa] has connected
17:42:39 [WARNING] Event ServerSwitchEvent(player=BlackSky) took 980,009,963ns to process!
17:42:39 [INFO] [BlackSky] <-> DownstreamBridge <-> [lobby] has disconnected
17:45:16 [INFO] [/213.239.204.169:44182] <-> InitialHandler has connected
17:48:36 [INFO] [/109.96.125.253:49809] <-> InitialHandler has connected
17:48:48 [INFO] [/109.96.125.253:49813] <-> InitialHandler has connected
17:51:00 [WARNING] [/109.96.125.253:49809] <-> InitialHandler - NativeIoException: syscall:read(...)() failed: Connection reset by peer
17:51:00 [WARNING] [/109.96.125.253:49813] <-> InitialHandler - NativeIoException: syscall:read(...)() failed: Connection reset by peer
17:53:25 [INFO] [/5.14.125.201:51186] <-> InitialHandler has connected
17:53:26 [INFO] [/5.14.125.201:51191] <-> InitialHandler has connected
17:55:07 [INFO] [/5.14.125.201:51224] <-> InitialHandler has connected
17:55:07 [INFO] [ToxicProdX] <-> ServerConnector [lobby] has connected
17:55:34 [INFO] [/213.239.204.169:34580] <-> InitialHandler has connected
17:55:38 [INFO] [ToxicProdX] disconnected with: ?f?aFragCs ?8? ?fTimpul de login a expirat, ai primit kick, incearca din nou!
17:55:38 [INFO] [ToxicProdX] <-> DownstreamBridge <-> [lobby] has disconnected
17:55:38 [INFO] [ToxicProdX] -> UpstreamBridge has disconnected
17:58:04 [INFO] [/78.96.225.32:8087] <-> InitialHandler has connected
17:58:41 [INFO] [/78.96.225.32:8140] <-> InitialHandler has connected
18:04:26 [INFO] [/95.76.1.242:63234] <-> InitialHandler has connected
18:05:32 [INFO] [/213.239.204.169:52524] <-> InitialHandler has connected
18:09:43 [INFO] [/81.181.81.190:60584] <-> InitialHandler has connected
18:09:56 [WARNING] [/81.181.81.190:60584] <-> InitialHandler - NativeIoException: syscall:read(...)() failed: Connection reset by peer
18:10:44 [INFO] [/81.181.81.190:60846] <-> InitialHandler has connected
18:12:20 [INFO] [/79.118.243.119:58943] <-> InitialHandler has connected
18:12:21 [INFO] [/79.118.243.119:25235] <-> InitialHandler has connected
18:12:41 [INFO] [/79.118.243.119:25237] <-> InitialHandler has connected
18:12:41 [INFO] [Andrei] <-> ServerConnector [lobby] has connected
18:12:52 [INFO] [Andrei] <-> ServerConnector [apocalipsa] has connected
18:12:52 [INFO] [Andrei] <-> DownstreamBridge <-> [lobby] has disconnected
18:13:52 [INFO] [BlackSky] disconnected with: ?f[Proxy] Lost connection to server.
18:13:52 [INFO] [BlackSky] <-> DownstreamBridge <-> [apocalipsa] has disconnected
18:13:52 [INFO] [Andrei] disconnected with: ?f[Proxy] Lost connection to server.
18:13:52 [INFO] [Andrei] <-> DownstreamBridge <-> [apocalipsa] has disconnected
18:13:52 [INFO] [BlackSky] -> UpstreamBridge has disconnected
18:13:52 [INFO] [Andrei] -> UpstreamBridge has disconnected

**Comment by md-5** [comment]
SkinsRestorer is not a supported plugin and you also have issues sith events taking too long.
Please reproduce wih no plugins on bugee or server.

**Comment by Vlad2000MC** [comment]
Doesn't not work.. Is the same error.
