### ISSUE TITLE
Proxy Erro

### ISSUE THREAD

**Issue by Vlad2000MC** [SpigotMC/BungeeCord#2097]
Hello ! When i connect to my bungee server and go to Survival, kick me and all players with message: '[Proxy] Lost Connection to Server'. 
I have latest version of BungeeCorde and modules.
What can i do to fix this issue ?

Logs:
08:35:52 [INFO] [BlackSky] disconnected with: ?f[Proxy] Lost connection to server.
08:35:52 [INFO] [BlackSky] <-> DownstreamBridge <-> [survival] has disconnected
08:35:52 [INFO] [BlackSky] -> UpstreamBridge has disconnected
08:36:08 [INFO] [/109.98.122.28:63426] <-> InitialHandler has connected
08:36:23 [INFO] [/109.98.122.28:63467] <-> InitialHandler has connected
08:36:23 [INFO] [BlackSky] <-> ServerConnector [lobby] has connected
08:52:01 [INFO] [BlackSky] disconnected with: ?f[Proxy] Lost connection to server.
08:52:01 [INFO] [BlackSky] <-> DownstreamBridge <-> [survival] has disconnected
08:52:01 [INFO] [BlackSky] -> UpstreamBridge has disconnect

**Comment by md-5** [comment]
Check the survival console for errors.
Make sure you aren't using any plugins.
Check if you can join the server directly.

**Comment by Vlad2000MC** [comment]
Survival doesn't have errors.
And i can't join directly to survival because spigot.ymg have 'bungeecorde: true'
