### ISSUE TITLE
Chat and Commands

### ISSUE THREAD

**Issue by Vlad2000MC** [SpigotMC/BungeeCord#2099]
Hello !
When i connect to bungee server and type in chat, in lobby, '/server' or '/featherboard reload', doesn't work, and chat too. I write but nothing is happen.
On Survival is too, when i type 'Hello', for example, doens't not work, and in Proxy Log spam errors and i don't know how can i fix that:

WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: a4:60:2a:56:78:19:1d:4b

[WARNING] Forced host server pvp is not defined

[SEVERE] Exception in thread "main" 
[SEVERE] java.io.IOException: Input/output error
[SEVERE] 	at java.io.FileInputStream.read0(Native Method)

BungeeCord version: https://ci.md-5.net/job/BungeeCord/1228/
BugeePlugins: 
        - BungeeAuthMeBridge-1.6.2
        - BungeeMotd-1.2
        - SkinsRestorer-v12.9.7.
What can i do ?

**Comment by kamcio96** [comment]
Try without plugins

**Comment by Vlad2000MC** [comment]
Is the same..

**Comment by md-5** [comment]
Complete log required
