### ISSUE TITLE
Crash with packet spam?

### ISSUE THREAD

**Issue by Dimatert9** [SpigotMC/BungeeCord#2102]
https://www.hastebin.com/mijebehegi.lua

**Comment by JampireX** [comment]
One more error
https://www.hastebin.com/wixogipuze.lua

We had about 100pps of these bad packets, eventually it resulted in Too many open files and proxy crashed

**Comment by Black-Hole** [comment]
You should block the ip of the offender in your network firewall.

**Comment by Dimatert9** [comment]
There is not one IP. Maybe attacker use proxy.

**Comment by md-5** [comment]
100pps alone is definitely not enough to crash Bungee, there are definitely other factors at play here.
Without a reproducible test I can only say that you are probably being DDoSd with lots lingering connections, which is not something that Bungee can fix
