### ISSUE TITLE
Client crashes when server overwrites middle mouse click.

### ISSUE THREAD

**Issue by JoJoDeveloping** [SpigotMC/BungeeCord#2104]
Hello,
I have a plugin which overwrites the creative middle mouse click option in certain cases. It works fine when not used with bungeecoord.
Now I wanted to migrate that server to bungeecoord and when the server overwrites the click, I get this error on the client side (vanilla client 1.8.9, latest bungeecoord from jenkins): [http://imgur.com/a/fYdPE](http://imgur.com/a/fYdPE).
There are no stack traces or exceptions being reported in the bungeecoord, server and client (launcher) log.

**Comment by md-5** [comment]
No reproduction code included.
