### ISSUE TITLE
No players can join bungeecord

### ISSUE THREAD

**Issue by ICEconchy** [SpigotMC/BungeeCord#2106]
Here is the error from the console:

12:53:04 [SEVERE] Apr 03, 2017 12:53:04 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@18fea4b5 java.lang.NullPointerException: info at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:226) at net.md_5.bungee.UserConnection.connect(UserConnection.java:246) at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:519) at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418) at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312) at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) at java.lang.Thread.run(Thread.java:745)

**Comment by Black-Hole** [comment]
It seems you're using an invalid config file. Please use a paste service to upload your BungeeCord config file.

**Comment by md-5** [comment]
Also not using up to date version
