### ISSUE TITLE
IP Forwarding.....?

### ISSUE THREAD

**Issue by ItzOnlyAnimalYT** [SpigotMC/BungeeCord#2108]
Hello md_5 and whomever else may be reading, I'm using BungeeCord build #1228 and spigot 1.8.8-R0.1-SNAPSHOT. Anyway, When Connecting via the hub server, I get the notorious "If you wish to use IP forwarding, please enable it in your BungeeCord config as well!"
I put the config in a pastebin so you can check the formatting and everything else
BungeeCord Config: https://pastebin.com/JvNGbsZd
Spigot.yml file: https://pastebin.com/6ieYpiAH
*note that the spigot.yml is the exact same for every server i'm running.
I'm sure a lot of other people STILL face this issue, so maybe this will help them as well!

**Comment by i9hdkill** [comment]
Connect via your bungee:
yourip:25578
Never connect to your servers directly.
Read the BungeeCord wiki to learn how to protect your spigot servers.
Not a bug, if you need further support, visit the wiki or the forums.

**Comment by ItzOnlyAnimalYT** [comment]
OH. MY. GOD. i need to use github more. Thank you SOOOO much!
