### ISSUE TITLE
WARN java.net.ConnectException: Connection timed out - spigot server help

### ISSUE THREAD

**Issue by NKEND** [SpigotMC/BungeeCord#2114]
Hey 
Since today im i getting the message: readtimeoutexception null.
when im in my server for 5 minutes.
know someone how to fix this error?

18.04 15:53:49 [Server] WARN java.net.ConnectException: Connection timed out
18.04 15:53:49 [Server] WARN at java.net.PlainSocketImpl.socketConnect(Native Method)
18.04 15:53:49 [Server] WARN at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
18.04 15:53:49 [Server] WARN at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
18.04 15:53:49 [Server] WARN at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
18.04 15:53:49 [Server] WARN at java.net.SocksSocketImpl.connect(Unknown Source)
18.04 15:53:49 [Server] WARN at java.net.Socket.connect(Unknown Source)
18.04 15:53:49 [Server] WARN at java.net.Socket.connect(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.NetworkClient.doConnect(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.http.HttpClient.openServer(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.http.HttpClient.openServer(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.http.HttpClient.<init>(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.http.HttpClient.New(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.http.HttpClient.New(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.connect(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
18.04 15:53:49 [Server] WARN at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
18.04 15:53:49 [Server] WARN at java.net.HttpURLConnection.getResponseCode(Unknown Source)
18.04 15:53:49 [Server] WARN at net.mindoverflow.hubthat.UpdateChecker.linksValid(UpdateChecker.java:37)
18.04 15:53:49 [Server] WARN at net.mindoverflow.hubthat.UpdatesTimer.run(UpdatesTimer.java:26)
18.04 15:53:49 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71)
18.04 15:53:49 [Server] WARN at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
18.04 15:53:49 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:730)
18.04 15:53:49 [Server] WARN at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
18.04 15:53:49 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:675)
18.04 15:53:49 [Server] WARN at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:574)
18.04 15:53:49 [Server] WARN at java.lang.Thread.run(Unknown Source)

**Comment by caoli5288** [comment]
Seems NOT a bungeecord bug.
