### ISSUE TITLE
Chain TextComponent 

### ISSUE THREAD

**Issue by SimplyBallistic** [SpigotMC/BungeeCord#2115]
It would be awesome if you could make the methods in TextComponent return itself so we can chain in methods such as `sendMessage(BaseComponent)`

e.g
```
player.sendMessage(new TextComponent("Hello World!").setColor(ChatColor.GREEN).setItalic(true));
//ahhh, so neat
```
Thanks!

**Comment by md-5** [comment]
Chaining at this point would break plugins compiled against previous versions.

**Comment by Janmm14** [comment]
usong bytecode transformations to achievw compatibility is probably out-of-scope

**Comment by SimplyBallistic** [comment]
It wouldn't really cause any issues, the return type wouldn't change much since it returns nothing in the first place right?

**Comment by Janmm14** [comment]
It's not bytecode compatible, aka all plugins using the old function would have to be recompiled against newest bungeecord-api.

**Comment by SimplyBallistic** [comment]
Ohh ok, makes sense. I'll close this issue. If anyone is interested, you can do something similar to this...

https://github.com/SimplyBallistic/JoinVerify/blob/master/src/main/java/me/SimplyBallistic/util/TextComponent.java

**Comment by md-5** [comment]
@SimplyBallistic we have an inbuilt way to chain:
https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/ComponentBuilder.java

Forgot about it initially.
