### ISSUE TITLE
Netty Issue

### ISSUE THREAD

**Issue by Fluxty** [SpigotMC/BungeeCord#2116]
Running latest Bungeecord (1229)

On the Spigot end we see:
https://hasteb.in/acasenoqog.pas

Nobody can connect to the server when this happens, and so far it only happens right in the middle of a reboot, which we have multiple servers on automatic reboot schedules.. and it hits all of them.

And in Bungeecord:
https://hasteb.in/sawexoqivu.avrasm

**Comment by i9hdkill** [comment]
Featherboard or a NameTag Plugin is causig this issue. Not a bungee bug
`Team MVdWAN5780 already exists in this scoreboard`

**Comment by Fluxty** [comment]
We have no Featherboard or animated names Bungee side? How can we receive the error from on our Spigot servers before those plugins are enabled?  I'll ask MVdW, but I thought it looked like an MVdW plugin is trying to create the scoreboard object and Bungee is throwing and exception
