### ISSUE TITLE
Kick no reason

### ISSUE THREAD

**Issue by Raphy123** [SpigotMC/BungeeCord#2117]
Hi,

Since one day, one of my staff is kicked many times. 
This error in BungeeCord : 
https://pastebin.com/BRMmH27Z

How resolve that ?

Thanks !

Regards

**Comment by Raphy123** [comment]
"14:30:19 [INFOS] [Zawakuro] disconnected with: DecoderException : java.lang.RuntimeException: VarInt too big @ io.netty.handler.codec.MessageToMessageDecoder:98"

**Comment by md-5** [comment]
We discussed this on IRC, it appears that your staff member may be using a modded client or something causing him to send corrupt data.
Please have him reinstall Minecraft from minecraft.net
