### ISSUE TITLE
forced_hosts for bungee wont work

### ISSUE THREAD

**Issue by owendemars** [SpigotMC/BungeeCord#2118]
ive made a bungee server and i put my public address in and in minecraft it will never connect help
i have port fowarded all ports that ive seen in my properties and config files
![git](https://cloud.githubusercontent.com/assets/27905528/25309443/5fdd691c-279b-11e7-8d7c-2771726b1a83.PNG)

**Comment by md-5** [comment]
Your server is not up or reachable at that address currently.
Forced_hosts is used only to configure the default server, not the IP the server listens on.
Please use the forums for support.
