### ISSUE TITLE
Just a question about permission nodes

### ISSUE THREAD

**Issue by EmanYm** [SpigotMC/BungeeCord#2119]
Just so I don't muddle this up, do I add the [permission](https://www.spigotmc.org/wiki/bungeecord-commands/) nodes to the [config](https://www.spigotmc.org/wiki/bungeecord-configuration-guide/), or can I add them to permissionsex?
Or does it even make a difference if I was to add them in both places?

**Comment by xxyy** [comment]
BungeeCord (natively) has no way of knowing what permissions you have configured on your Spigot backend server (aka, PermissionsEx), so, for BungeeCord commands, you'll have to either set them in the config or via a permissions plugin for BungeeCord. Questions like these might be more appropriate in the [Forums](https://www.spigotmc.org/forums/#bungeecord.33) though.

**Comment by EmanYm** [comment]
I never even considered checking the spigot forums...I guess that only makes sense with Bungeecord being a spigot creation.
I got the answer I was expecting, though.  Thank you for clarifying for me, xxyy.
