### ISSUE TITLE
Forced Host not working?

### ISSUE THREAD

**Issue by PeterXonwiiXx** [SpigotMC/BungeeCord#2124]
http://prntscr.com/f2vqaa
Seems like with that its not working, been trying A LOT so dont know what the problem is.`

**Comment by md-5** [comment]
Forced hosts don't work with ports I believe

**Comment by Janmm14** [comment]
Additionally you would need to put your address (if bungee would suppport it) into quotes `"myaddrress:port": myserver`

**Comment by PeterXonwiiXx** [comment]
@md-5 Jup, somebody from Spigot helped me out using skype screenshare,
I had to make a A record pointing to my servers ip and then create a CNAME on top of it.
SRV's (port) doesnt work.
But i got it solved so this thread can be closed, thanks anyway for the help! <3
