### ISSUE TITLE
when i chatting /server Server1

### ISSUE THREAD

**Issue by Volendam** [SpigotMC/BungeeCord#2126]
than i see this " The specified server does not exist

this is config.yml
ip_forward: false
network_compression_threshold: 256
stats: dc3887f4-4ad3-4d77-b1b3-1e7de05de7cc
permissions:
default:

bungeecord.command.server
bungeecord.command.list
admin:
bungeecord.command.alert
bungeecord.command.end
bungeecord.command.ip
bungeecord.command.reload
groups:
Volendam:
admin
servers:
lobby:
motd: HSN BungeeCord Server
address: localhost:25566
restricted: false
timeout: 30000
Server1:
motd: Bable BungeeCord Server
address: localhost:25567
restricted: false
prevent_proxy_connections: false
online_mode: true
player_limit: -1
log_commands: false
listeners:
query_port: 25565
motd: Minecraft BungeeCord Server
priorities:
lobby
bind_local_address: true
tab_list: GLOBAL_PING
query_enabled: false
host: 0.0.0.0:25565
forced_hosts:
pvp.md-5.net: pvp
max_players: 40
tab_size: 60
ping_passthrough: false
force_default_server: true
disabled_commands:
disabledcommandhere
connection_throttle: 4000

Lobby port 25566
Babel port 25567

**Comment by md-5** [comment]
Please use the forums for support
