### ISSUE TITLE
They sent me here! Bungee Server not starting up! Need help ASAP!

### ISSUE THREAD

**Issue by EpicHalo77** [SpigotMC/BungeeCord#2131]
16:24:22 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
16:24:22 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
16:24:22 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:53cc324:1229
16:24:22 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
16:24:22 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
16:24:22 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
16:24:22 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
16:24:22 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
16:24:22 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
16:24:22 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
16:24:22 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
16:24:22 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
16:24:22 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
16:24:22 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
16:24:22 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:53cc324:1229 by SpigotMC
16:24:22 [SEVERE] Exception in thread "main"
16:24:22 [SEVERE] mapping values are not allowed here
 in 'reader', line 2, column 11:
    ip_forward: true
              ^

16:24:22 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:249)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:253)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:124)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:120)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
16:24:22 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
16:24:22 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
16:24:22 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:64)
16:24:22 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
16:24:22 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
16:24:22 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Paulomart** [comment]
Your config is invalid, try deleting it.

**Comment by EpicHalo77** [comment]
I did that Paulomart now what?

**Comment by kamcio96** [comment]
Now use wiki or forums for help. It's issue tracker.
