### ISSUE TITLE
Players can change Server between Internal IP External IP

### ISSUE THREAD

**Issue by HuskyTW** [SpigotMC/BungeeCord#2132]
My problem is a little bit like #918. While it happens rather in different capitalized name, but in ```InternalIP``` and ```ExternalIP```.
Is there any way to fix that?

# For Further info
## >>The situation of our server
I have two spigot servers connect with bungeecord.
In our server, players cannot using command.
For switching servers through command block placing at spawn(with plugin CommandSync).
And can only switch item through Ender chest(with plugin PlayerSQL).

>>It means players can only switch server at spawn point where the command block is.
>>And can only switch item when get back to spawn, then get to another server.

I gave ```Internal IP``` to a few people whose connections bad.(from other country)
## >>Problem
While when those who knew ```Internal IP``` now found that they can switch server through ```External IP```.

### For ex: 
A player join the server and
1. Left the game with ```Enternal IP``` at **ServerA X1 Y1 Z1**.
2. Left the game with ```Internal IP``` at **ServerB X2 Y2 Z2**.

The player would
1. Join the game with ```Enternal IP``` at **SeverA X1 Y1 Z1**.
2. Join the game with ```Internal IP``` at **ServerB X2 Y2 Z2**

>>Means an IP for a server

If the player want to switch items between server.
No need to get back to spawn point but switching between ```External IP``` & ```Internal IP```.
Is there any way to fix it

**Comment by HuskyTW** [comment]
While in location.yml
I found it save username out of order.
Such as:

'Notch;```Internal IP:25565```': ServerA, 'Notch;```Enternal IP:25565```': ServerB, 'Dinner_Bone;```Internal IP:25565```': ServerA, 'Lisa;```Internal IP:25565```': ServerA

**Comment by md-5** [comment]
This is by design. The locations.yml reconnect handler stores by virtual hosts.
If you don't like this behaviour a plugin can replace it.

**Comment by Combustible** [comment]
For anyone looking to do exactly as md-5 suggests above - take a look at https://github.com/SpigotMC/BungeeCord/tree/master/module/reconnect-yaml 

You can modify this code to implement your own ReconnectHandler which doesn't save/use virtual hosts.
