### ISSUE TITLE
Issue Can't bind to address

### ISSUE THREAD

**Issue by ImpactOres** [SpigotMC/BungeeCord#2136]
There is nothing running on 25565 except BitTorrent. I stopped it and this still happened.

09:30:38 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
09:30:38 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
09:30:38 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:5bc189f:1232
09:30:39 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
09:30:39 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
09:30:39 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
09:30:39 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
09:30:39 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
09:30:39 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
09:30:39 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Loaded plugin QuietCord version 1.0-git-00f2196 by Literallie
09:30:39 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Loaded plugin RandomHub version 1.1.6-SNAPSHOT by null
09:30:39 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [WARNING] Forced host server pvp is not defined
09:30:39 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Enabled plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Enabled plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] [QuietCord] This logger is now filtered by InitialHandlerFilter{filterPings=true, filterJoins=false}
09:30:39 [INFO] Enabled plugin QuietCord version 1.0-git-00f2196 by Literallie
09:30:39 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] [RandomHub] Listing your servers into the plugin...
09:30:39 [INFO] [RandomHub] [Updater] Searching for updates.
09:30:39 [INFO] [RandomHub] A total of 2 servers have been added to the plugin
09:30:39 [INFO] [RandomHub] Starting the ping task, the interval is 1000
09:30:39 [INFO] Enabled plugin RandomHub version 1.1.6-SNAPSHOT by null
09:30:39 [INFO] Enabled plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [INFO] Enabled plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:5bc189f:1232 by SpigotMC
09:30:39 [WARNING] Could not bind to host /0.0.0.0:25565
java.net.BindException: Address already in use: bind
    at sun.nio.ch.Net.bind0(Native Method)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.Net.bind(Unknown Source)
    at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
    at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:128)
    at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:554)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1258)
    at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
    at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
    at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:980)
    at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:250)
    at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:365)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
    at java.lang.Thread.run(Unknown Source)
09:30:40 [INFO] [RandomHub] [Updater] Found new version: 1.1.7! (Your version is 1.1.6-SNAPSHOT)
09:30:40 [INFO] [RandomHub] [Updater] Download here: http://www.spigotmc.org/resources/639

**Comment by ghacproductions** [comment]
Another process is already listening on port 25565 (maybe a spigot server?).

**Comment by i9hdkill** [comment]
As we said yesterday, this is not the place to get support.
Please ask here:
https://www.spigotmc.org/forums/bungeecord-help.70/

**Comment by Black-Hole** [comment]
If it tell you that the port is already in use then it is. You could call it a "fact".
09:30:39 [WARNING] Could not bind to host /0.0.0.0:25565
java.net.BindException: Address already in use: bind
