### ISSUE TITLE
Giving me this error when i try to power on my server.

### ISSUE THREAD

**Issue by iMagic142Official** [SpigotMC/BungeeCord#2138]
10:19:38 [INFO] Using OpenSSL based native cipher.
10:19:38 [INFO] Using native code compressor
10:19:38 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.11-SNAPSHOT:950d504:1225
10:19:38 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
10:19:38 [INFO] Epoll is working, utilising it!
10:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
10:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
10:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
10:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
10:19:38 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
10:19:38 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
10:19:38 [INFO] Loaded plugin BungeeMSG version 2.2.0 by O_o_Fadi_o_O
10:19:38 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.11-SNAPSHOT:950d504:1225 by SpigotMC
10:19:38 [INFO] Loaded plugin ServerListPlus version 3.4.7 by Minecrell <https://github.com/Minecrell>
10:19:38 [INFO] Loaded plugin BungeeAuthMeBridge version 1.6.2 by CryLegend
10:19:38 [INFO] Loaded plugin cmd_find version git:cmd_find:1.11-SNAPSHOT:950d504:1225 by SpigotMC
10:19:38 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.11-SNAPSHOT:950d504:1225 by SpigotMC
10:19:38 [INFO] Loaded plugin cmd_send version git:cmd_send:1.11-SNAPSHOT:950d504:1225 by SpigotMC
10:19:38 [INFO] Loaded plugin cmd_server version git:cmd_server:1.11-SNAPSHOT:950d504:1225 by SpigotMC
10:19:38 [INFO] Loaded plugin SlashServer version 3 by Bloodsplat
10:19:38 [INFO] Loaded plugin SkinsRestorer version 12.9.5 by Blackfire62, Th3Tr0LLeR
10:19:38 [INFO] Loaded plugin cmd_list version git:cmd_list:1.11-SNAPSHOT:950d504:1225 by SpigotMC
10:19:38 [SEVERE] Exception in thread "main" 
10:19:38 [SEVERE] java.lang.NullPointerException
10:19:38 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.get(YamlConfig.java:109)
10:19:38 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:202)
10:19:38 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:92)
10:19:38 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:264)
10:19:38 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
10:19:38 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by md-5** [comment]
Your config is likely invalid. Please use the forums for support.
