### ISSUE TITLE
Sending users to lobby

### ISSUE THREAD

**Issue by Bitconion** [SpigotMC/BungeeCord#2140]
BungeeCord sends users to lobby, there is no error or warning message. 

BungeeCord has no plugins installed.

The only message is : "03:46:06 [INFO] [WinterTreat] <-> DownstreamBridge <-> [blch1] has disconnected"

It does not happen at a specific time or to specific users, this happens to every single user (even ops) in every single connected server, but not at the same time. (it happens even in a server with no plugins installed)

Bungee log: https://pastebin.com/vi9jF35v

Bungee Config: https://pastebin.com/BQ0UxYww

**Comment by EmanYm** [comment]
You could have just posted a response or added more information to [your other ticket](https://github.com/SpigotMC/BungeeCord/issues/2139)

**Comment by Bitconion** [comment]
it was closed

**Comment by md-5** [comment]
You can still reply to closed tickets, it just means that given the current info I don't consider them to be a bug.
In this case your BungeeCord is losing connection to your servers.
This could be a bad plugin on your servers, a time out, or bad networking between bungee and your servers.
You should connect your servers over localhost if possible without plugins.

**Comment by Bitconion** [comment]
It stills happening even in a server with no plugins, 5 out of 6 servers are on localhost.

I have had the same problem on two different networks on different host & ussing different plugins.
