### ISSUE TITLE
bungeecord 

### ISSUE THREAD

**Issue by marcosp20** [SpigotMC/BungeeCord#2141]
I can not connect my server appears could not connect to a default or fallback server io.netty.channel.abstractchannel$Annotatedconnecte

**Comment by EmanYm** [comment]
Whoever helps you will be asking for a log and plugin/mod versions to help pinpoint and fix the issue you're having.

**Comment by i9hdkill** [comment]
Hi,
this is the BungeCord bugtracker. Unless you find a bug, look for help in the forums here:
https://www.spigotmc.org/forums/bungeecord-help.70/

But it looks like, that the wiki could help you aswell:
https://www.spigotmc.org/wiki/bungeecord/
