### ISSUE TITLE
wrong packet ids?

### ISSUE THREAD

**Issue by Dimatert9** [SpigotMC/BungeeCord#2142]
https://github.com/SpigotMC/BungeeCord/commit/09ee2b1644ab3698aba67c91808ef8cb758ebb17#diff-f5da6738ad3c03e59c357db9fd022745R64

in pre4(http://wiki.vg/index.php?title=Pre-release_protocol&oldid=10804) it was changed to 0x20 and in pre5 it dont changed.

also https://github.com/SpigotMC/BungeeCord/commit/09ee2b1644ab3698aba67c91808ef8cb758ebb17#diff-f5da6738ad3c03e59c357db9fd022745R70
https://github.com/SpigotMC/BungeeCord/commit/09ee2b1644ab3698aba67c91808ef8cb758ebb17#diff-f5da6738ad3c03e59c357db9fd022745R76
https://github.com/SpigotMC/BungeeCord/commit/09ee2b1644ab3698aba67c91808ef8cb758ebb17#diff-f5da6738ad3c03e59c357db9fd022745R87
https://github.com/SpigotMC/BungeeCord/commit/09ee2b1644ab3698aba67c91808ef8cb758ebb17#diff-f5da6738ad3c03e59c357db9fd022745R93

and some others.

**Comment by Dimatert9** [comment]
looks like a wiki.vg have wrong documentation

**Comment by Black-Hole** [comment]
The documentation at wiki.vg is not wrong. It just documents the changes since the last release version, not between snapshots. So in 1.12-pre5 some packet ids changed, mostly to the same ID used in 1.11.2.

**Comment by Dimatert9** [comment]
oh. thanks
