### ISSUE TITLE
Failed to enable CommandsDispatcher

### ISSUE THREAD

**Issue by smmmadden** [SpigotMC/BungeeCord#2146]
I'm using the 1235 build of BungeeCord and Spigot 1.12 pre5 build today and when I start Bungee, I get the below warning and while in game, when I try to /server myWorld to one of my worlds (1.12 pre5), it tells me I'm already in that world (when I'm not).  I am also using the SlashServer 3.0 to allow for commands to be called directly (so /MyWorld2 as opposed to /server MyWorld2.  SlashServer says I'm already in the same world, but using /server MyWorld2 directly, I'm taken to another world, but it isn't MyWorld2.  So it seems that the command dispatcher is having troubles identifying/communicating with the right server.  Note if this helps, all my other worlds except MyWorld2 are 1.11.2 latest build.  This was working before upgrading to 1235 build.

Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
11:47:18 [INFO] Using standard Java JCE cipher. To enable the OpenSSL based native cipher, please make sure you are using 64 bit Ubuntu or Debian with libssl installed.
11:47:18 [INFO] Using standard Java compressor. To enable zero copy compression, run on 64 bit Linux
11:47:18 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:4db5352:1235
11:47:18 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
11:47:18 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
11:47:18 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
11:47:18 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
11:47:18 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
11:47:18 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
11:47:18 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Loaded plugin BungeeWhiteList version 1.0 by xGabryMC
11:47:18 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Loaded plugin CommandSync version 2.3 by YoFuzzy3
11:47:18 [INFO] Loaded plugin SlashServer version 3 by Bloodsplat
11:47:18 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
**11:47:18 [WARNING] Socket4MC (required by CommandsDispatcher) is unavailable
11:47:18 [WARNING] Failed to enable CommandsDispatcher**
11:47:18 [WARNING] Forced host server pvp is not defined
11:47:18 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Enabled plugin BungeeWhiteList version 1.0 by xGabryMC
11:47:18 [INFO] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] [CommandSync] Configuration file loaded.
11:47:18 [INFO] [CommandSync] Opened server on localhost:9190.
11:47:18 [INFO] [CommandSync] All data loaded.
11:47:18 [INFO] Enabled plugin CommandSync version 2.3 by YoFuzzy3
11:47:18 [INFO] Enabled plugin SlashServer version 3 by Bloodsplat
11:47:18 [INFO] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:18 [INFO] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:4db5352:1235 by SpigotMC
11:47:19 [INFO] Listening on /192.168.0.151:25577
11:47:26 [INFO] [CommandSync] Received new connection from 127.0.0.1:52730.
11:47:26 [INFO] [CommandSync] Connection from 127.0.0.1:52730 under name creative has been authorised.
11:47:26 [INFO] [CommandSync] Received new connection from 127.0.0.1:52731.
11:47:26 [INFO] [CommandSync] Connection from 127.0.0.1:52731 under name thehub has been authorised.
11:47:26 [INFO] [CommandSync] Received new connection from 127.0.0.1:52732.
11:47:26 [INFO] [CommandSync] Connection from 127.0.0.1:52732 under name future has been authorised.
11:47:26 [INFO] [CommandSync] Received new connection from 127.0.0.1:52733.
11:47:26 [INFO] [CommandSync] Connection from 127.0.0.1:52733 under name survival has been authorised.
11:47:27 [INFO] [CommandSync] Received new connection from 127.0.0.1:52734.
11:47:27 [INFO] [CommandSync] Connection from 127.0.0.1:52734 under name educator has been authorised.
11:47:27 [INFO] [CommandSync] Received new connection from 127.0.0.1:52735.
11:47:27 [INFO] [CommandSync] Connection from 127.0.0.1:52735 under name hogwarts has been authorised.
11:47:27 [INFO] [CommandSync] Received new connection from 127.0.0.1:52736.
11:47:27 [INFO] [CommandSync] Connection from 127.0.0.1:52736 under name tester has been authorised.
>

**Comment by Black-Hole** [comment]
That is a plugin issue. The plugin CommandsDispatcher is missing some other plugin named Socket4MC.
Please read the documentation for the plugin or ask the plugin author.

**Comment by smmmadden** [comment]
Thanks Black-Hole, found the plugin and going through the setup.
