### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by x9nico** [SpigotMC/BungeeCord#2147]
Hi, when I  start BungeeCord (latest version) it is do that:
18:13:15 [SEVERE] Exception in thread "main" 
18:13:15 [SEVERE] org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
18:13:15 [SEVERE] 	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:200)
18:13:15 [SEVERE] 	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:60)
18:13:15 [SEVERE] 	at org.yaml.snakeyaml.Yaml.load(Yaml.java:412)
18:13:15 [SEVERE] 	at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
18:13:15 [SEVERE] 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:65)
18:13:15 [SEVERE] 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
18:13:15 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
18:13:15 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
18:13:15 [SEVERE] Caused by: java.nio.charset.MalformedInputException: Input length = 1
18:13:15 [SEVERE] 	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
18:13:15 [SEVERE] 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
18:13:15 [SEVERE] 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
18:13:15 [SEVERE] 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
18:13:15 [SEVERE] 	at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:123)
18:13:15 [SEVERE] 	at java.io.Reader.read(Reader.java:140)
18:13:15 [SEVERE] 	at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:184)
18:13:15 [SEVERE] 	... 7 more

**Comment by Black-Hole** [comment]
Your config.yml file is invalid. Please use the forums for support.
