### ISSUE TITLE
BungeeCord not diconnecting players correctly, casing high cpu

### ISSUE THREAD

**Issue by MrMinecraft15** [SpigotMC/BungeeCord#2148]
Hello everyone.

As not already quite often mentioned, BungeeCord does NOT disconnect players ALWAYS correctly, and yes, this is causing a VERY HIGH cpu usage.

I already mentioned this at spigot: https://www.spigotmc.org/threads/extreme-high-cpu-usage.242232/

Please read the port above, if this doesn't mean anything to you. I woun't repeat myself and many others.

I would please everyone, who is involved in this project to take this issue serious - this is driving me crazy!
Ok, calm down.

I took a look at the functions, which are available to me and found something out:
ProxyServer.getInstance().getOnlineCount() is displaying a wrong amount of players (too much)
A for loop though all servers, which counts all players together, displays also too much players.
The player is still availalbe as a object (serverInfo.getPlayers() return all the player objects) - some even with the same name!
p.getServer() is available and returns the server object (but not everything?!?!) - warning, this is funny:
The proxiedPlayer.getServer().getAddress(), getInfo(), isConnected() is working, returning the address, serverinfo and the onlinestatus (it is not correct, but ok) BUT if you call proxiedPlayer.getServer().disconnect("KICKMESSAGE") it is casing a NullPointerException: https://pastebin.com/ja2gpfrz

But you are able to call proxiedPlayer.disconnect("KICKMESSAGE") - if you are doing this, the player is no longer counted at ProxyServer.getInstance().getOnlineCount()!!!

So, this bug does exist in fact and is not solved though any update yet!

It is possible to work around this, but only half. (For get getOnlineCount() method, but not for the "Server" objects).

So, please fix this - not as fast as possible - but it is a bug, which should definitely not exist!
It not that good, if a player wants to tonnect, but is unable to connect, cause the server is unable to remove the player from the memory... :/

Good luck!

AND if you need any other information, PLEASE tell me! I'll reply as fast as possible!

**Comment by MrMinecraft15** [comment]
Maybe it is an idea to check your modules, like the reconnect_yaml.jar if one of these modules is causing this issue?

**Comment by MrMinecraft15** [comment]
Oh, i forgot to mention, that this also happened without plugins.

**Comment by nathan818fr** [comment]
I find it strange that this bug is not met by big Minecraft networks. Personally I have a server that sometimes exceeds 10k connected players (so with several BungeeCord proxies) and we have never encountered any problems.

~~Whenever people complain about this kind of problems, they have personal plugins, I would direct my searches to them first.
What do your plugins do? Do they add servers at runtime? Do you have the right concurrent programming skills and understand that BungeeCord works mostly on the Netty event loop (which implies many consideration especially with the collections)?~~
(Written before `i forgot to mention, that this also happened without plugins`)

It is strange indeed, what version of BungeeCord? The latest build?
Can you take java memory and thread dump of your BungeeCord process when the problem occurs? (`jmap -dump:format=b,file=memorydump.bin <pid>` and `jstack <pid> >> threaddump.txt`)

**Comment by MrMinecraft15** [comment]
This might be true, but there is no way to find this out, cuz there is no tutorial or any conventions...

Its the latest build. sure.

**Comment by MrMinecraft15** [comment]
We only had one plugin enabled (for the motd, and basic functions). And it can't be the truth, that so many have this problem, just running one plugin...

**Comment by ninja-** [comment]
The stack trace you pasted is harmless and happens when someone types a command and is not connected to any backend server. I have no idea what could cause players to leak though.

**Comment by ninja-** [comment]
actually can you paste the full stacktrace and not a cut...might be interesting

**Comment by MrMinecraft15** [comment]
This waas the only thing what happened, when i called p.getServer().disconnect("");

**Comment by ninja-** [comment]
that's not a full stacktrace

**Comment by MrMinecraft15** [comment]
So, WHAT should I "considerate especially"?

**Comment by md-5** [comment]
Cannot reproduce:
`07:42:31 [INFO] [/127.0.0.1:58138] <-> InitialHandler has connected
>
07:42:32 [INFO] [md_5] <-> ServerConnector [lobby] has connected
>
07:42:35 [INFO] [md_5] disconnected with: [Proxy] Lost connection to server.
>
07:42:35 [INFO] [md_5] <-> DownstreamBridge <-> [lobby] has disconnected
>
07:42:35 [INFO] [md_5] -> UpstreamBridge has disconnected
>glist
glist
>
07:42:37 [INFO] [lobby] (0): 
>
07:42:37 [INFO] [other] (0): 
>
07:42:37 [INFO] Total players online: 0
`

Code: `getServer().disconnect( "Test");`

Please provide the MINIMAL test case required to reproduce this issue with no other plugins. Just calling getServer().disconnect cleans everything up fine.
