### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by FuwaYura** [SpigotMC/BungeeCord#2153]
How can I make BungeeCord connect servers over IPv6 connection?
I mean I want to create backyard connection in IPv6.

I've tried many formatting of addresses, but everything failed.
(example:  [xx:yyy:zzzz]:25566,  domain like hogehoge.mc:25566 )

plz help. ;o
(sorry for my poor Engilsh

**Comment by FuwaYura** [comment]
I don't think so.
I can connect Spigot server by IPv6 connection.
That problem might have fixed. 

>proxy/src/main/java/net/md_5/bungee/BungeeCord.java
>Showing the top match Last indexed on 26 Apr
>248	        System.setProperty( "java.net.preferIPv4Stack", "true" ); // Minecraft does not support IPv6

**Comment by Black-Hole** [comment]
The Minecraft server supports IPv6. Since 1.9 the Minecraft client supports IPv6, too. So that setting in BungeeCord could be changed.

**Comment by md-5** [comment]
That setting does not disable ipv6 support, all it does is prefer it in the case you have a domain pointing to A and AAAA records.

**Comment by md-5** [comment]
Cannot reproduce, BungeeCord works fine with:
[ipv6addr]:port


IPv6 was added in 1182affa09f2161d301d00e347b6ee1c77e71100 and you can see the unit tests for parsing it there.

**Comment by Gigadoc2** [comment]
Thanks!

For anyone reading this in the future, see 76dc32ee3259c9d52ce71467c926c055693f5e92.
