### ISSUE TITLE
[SEVERE] Exception in thread "main"

### ISSUE THREAD

**Issue by AndrewFirePvP7** [SpigotMC/BungeeCord#2158]
https://gyazo.com/9e31cfc290ecd98c4176702659ec97c6

Minecraft related issue: How do I fix this error so I can run my Minecraft server on BungeeCord?

**Comment by i9hdkill** [comment]
You messed up your bungeecord config.yml somehow.

Read more about configuring BungeeCord here:
https://www.spigotmc.org/wiki/bungeecord/

Keep in mind that this is the issue tracker for BungeeCord bugs and not a support area.
Head to the forums if you can't find the solution in BungeeCord wiki.
