### ISSUE TITLE
Exception: Connecting:NativeIOException

### ISSUE THREAD

**Issue by DaniFoldi** [SpigotMC/BungeeCord#2162]
Exception: Connecting:NativeIOException : syscall:read(..) failed: connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

This is the error I keep getting when using BungeeCord's newest build; happens with or without plugins, 1.11.2 and 1.12 installed. How can I fix this?

**Comment by md-5** [comment]
This is an issue with your networking or server closing the connection
