### ISSUE TITLE
BungeeCord player crash

### ISSUE THREAD

**Issue by LittleCakeMan** [SpigotMC/BungeeCord#2163]
Hi,
If I hit a player 4 times I get kicked from the server. I get kicked with the "fallback_kick" message.
(This does not happen when the attacker is OP on the server.)

Error: https://pastebin.com/fWu8TiKE
(I run the latest build of BungeeCord.)

**Comment by Janmm14** [comment]
Client version? Server version? Bungeecord plugins? Spigot/Bukkit plugins?

**Comment by LittleCakeMan** [comment]
Client version: 1.11.2 & 1.12
Server version: CraftBukkit version git-Spigot-3fb9445-6e3cec8 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)
BungeeCord plugins: none (I deleted them)
Spigot plugins: https://ibb.co/hxOp2k

**Comment by md-5** [comment]
Need to reproduce without spigot plugins, you have lots of protocol modifying plugins

**Comment by LittleCakeMan** [comment]
Thank you, just found the plugin:
https://www.spigotmc.org/resources/pncp-a-nocheatplus-addition-1-7-10-1-11-support-1000-downloads.37941/
