### ISSUE TITLE
BungeeCord using single core too much

### ISSUE THREAD

**Issue by TrexSo** [SpigotMC/BungeeCord#2164]
Hey Im using bungeecord version,

https://image.prntscr.com/image/hjBAuIF8R62RKQEX9F2EVQ.png

But its using single core too much,
https://image.prntscr.com/image/JmFJi9PzTXa6WzWDi7gdVg.png

Specs;
RAM 8GB
CPU E3-1230 v3 @ 3.30GHz
OS: Debian 3.2.82-1 x86_64
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

Its dedicated server, not VDS.

**Comment by md-5** [comment]
Bungeecord uses all cores evenly, plugins may not.
In addition red cpu is kernel time which means it is probably related to your server os itself, ie not balancing irqs properly.
