### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by EmanYm** [SpigotMC/BungeeCord#2165]
Is [this](https://hastebin.com/ebodeveyoq.swift) caused by BungeeCord or SpongePls?

15:32:06 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:eab710b:1242
15:32:06 [INFO] Loaded plugin SpongePls version 1.1-SNAPSHOT-b#35 by Cory Redmond

Edit
Going back through the jenkins builds, it seems that the most recent Minecraft 1.10.2 build might be [1199](https://ci.md-5.net/job/BungeeCord/1199/).  1200 adds support for 1.11.

Unless I am mistaken, and Bungeecord version doesn't matter, only the plugins built against it do.  In this case it would be SpongePls that's at fault.

**Comment by md-5** [comment]
Thats a plugin issue

**Comment by EmanYm** [comment]
I assumed as much.  I had already posted to that github before posting here.  Figured I should cover all bases.
