### ISSUE TITLE
Factions Won't Work

### ISSUE THREAD

**Issue by MysticParadox** [SpigotMC/BungeeCord#2167]
Installed BungeeCord and now whenever players login to my Factions server, it registers them as a new player and not with their old player files.

**Comment by MysticParadox** [comment]
Will pay for someone to fix this tonight

**Comment by i9hdkill** [comment]
Hi,
please read the wiki.
It provides all info you need:
https://www.spigotmc.org/wiki/bungeecord/
(small hint: ip forwarding)

Keep in mind that this is not the place to get support. It's for bugs only.
