### ISSUE TITLE
bungeecord not working

### ISSUE THREAD

**Issue by Bluejeanx** [SpigotMC/BungeeCord#2170]
So i cant get my bungee cord to work someone please help me

Console Error - https://pastebin.com/FHarxAwn

**Comment by EmanYm** [comment]
Looks like it might be a config issue.

**Comment by i9hdkill** [comment]
You messed up your config. Have a look here:
https://www.spigotmc.org/wiki/bungeecord-configuration-guide/

**Comment by Bluejeanx** [comment]
ok thanks for helping
