### ISSUE TITLE
Can't add more servers

### ISSUE THREAD

**Issue by IKqa** [SpigotMC/BungeeCord#2171]
I'm working on a project with my team. We've found out that after adding around 80 servers to the server list, some of them will just disappear at the next BungeeCord start. 

Is there a limit in the servers that you can add or is an issue?

**Comment by Janmm14** [comment]
bungeecord has no code which checks amount of servers

**Comment by IKqa** [comment]
Oh ok thanks. So we don't get what goes wrong here.

If we put this list of servers:
https://pastebin.com/SAKwrs0v

at the next restart it becomes:
https://pastebin.com/ZbDnSRR4

noticing how some entries like: 
`melina:
    motd: ''
    address: 10.0.1.55:25685
    restricted: false`
or
`TheLastTest:
    motd: ''
    address: 10.0.1.55:25612
    restricted: false`

just vanish after the restart.
is it something to do with the servers' name?

**Comment by md-5** [comment]
Looks closely at your server list, you have many duplicate names, eg
servkjdkd is listed three times.
Duplicate servers will be removed
