### ISSUE TITLE
Bad Packet ID - Crash Bungee

### ISSUE THREAD

**Issue by Niketion** [SpigotMC/BungeeCord#2172]
`05:52:34 [AVVERTENZA] [/54.226.83.22:58429] <-> InitialHandler - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.StatusRequest 0 Protocol STATUS Direction TO_SERVER `
Why bungee spam this "error"?

**Comment by md-5** [comment]
Means the player sent invalid data to bungee
