### ISSUE TITLE
Bungeecord bug. Lag and crash

### ISSUE THREAD

**Issue by xTheFox** [SpigotMC/BungeeCord#2173]
Hi, i have a problem with bungeecord. 
A player can crash bungeecord. I don't know how but in 1 minute bungeecord said 
[AVVERTENZA] [/54.226.83.22:58429] <-> InitialHandler - bad packet ID, are mods in use!? Did not read all bytes from packet class net.md_5.bungee.protocol.packet.StatusRequest 0 Protocol STATUS Direction TO_SERVER 

Then after a few of these pings, my Bungee seems to slowly crash, it doesn't say anything, but it just gets REALLY slow to the point where you can hardly join and it takes ages to ping.
 Like this:
[AVVERTENZA] Event ProxyPingEvent(connection=[/93.34.118.89:30068] <-> InitialHandler, response=ServerPing(version=ServerPing.Protocol(name=HexaCord 1.7.x, 1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, protocol=47), players=ServerPing.Players(max=1, online=15, sample=null), description=§f§9Heros§fPvP §7(§a4.0v§7) §7(§aONLINE§7)            §7Noi contro tutti!           §7[§e§lPRACTICE 1.7!§7] [§f§lDETTO, FATTO!§7], modinfo=ServerPing.ModInfo(type=FML, modList=[]))) took 6.136.524.915ns to process!

Here is the video: https://www.youtube.com/watch?v=cZ8ZT_Aii20

**Comment by md-5** [comment]
Not using bungeecord
