### ISSUE TITLE
LuckPerms-Bungee loads, but doesn't work

### ISSUE THREAD

**Issue by xbette** [SpigotMC/BungeeCord#2175]
When i start my Bungeecord up 
Version bungeecord-bootstrap:1.12-snapshot:73a81ff:1243
then it loads LuckPerms-Bungee But when i use the /lpb commands ingame then it just says "[LP] Running Luckperms v3.2.20."

I got told from the Luckperms team that i should make a report here at bungeecord.

**Comment by TheMolkaPL** [comment]
This is the plugin issue.

**Comment by xbette** [comment]
Okay, thanks... 
I'll get to them again then!
