### ISSUE TITLE
Multicraft - BungeeCord #1244 Startup Issue

### ISSUE THREAD

**Issue by RedEyedRocker** [SpigotMC/BungeeCord#2177]
So I've just updated my BungeeCord #1242 to #1244 on Multicraft and it always stucks when starting up. Here is the console log. I need help quick because I'm running a 24/7 dedicated server and downtime is really bad.

https://pastebin.com/CzYyJZBq

**Comment by Janmm14** [comment]
The log does not contain any useful information. Additionally forum might be more approiate for this kind of support. Ah and it might be a good idea to test before you attempt updating your main server if 24/7 uptime is crucial.

**Comment by RedEyedRocker** [comment]
Thanks for the advice. I had pasted the console log instead of the actual detailed log but It's already fixed though, it was due to some conflicted ports.

**Comment by Janmm14** [comment]
In that case you should close this issue.
