### ISSUE TITLE
ActuallyAdditions buttons bug

### ISSUE THREAD

**Issue by mkrtes** [SpigotMC/BungeeCord#2178]
There is one strange problem, that I don't know where to write. When I use bungeecord for sponge-server there was a problem with mod ActuallyAdditions. Interface buttons don't work. I run server only with sponge - it works well. Once connect with bungee - buttons not working. Something similar was discussed here: https://github.com/SpongePowered/SpongeForge/issues/1394 I don't know what to do and who to contact...

**Comment by i9hdkill** [comment]
Very unlikely caused by BungeeCord as it has been reproduced without BungeeCord, as you can see in the ticket you linked. Some other(including us) are using this mod behind BungeeCord without any issues.
Could you tell us if a newer mod/forge/sponge version fixed the issue?
