### ISSUE TITLE
Make TabCompleteEvent and TabCompleteResponseEvent sender-specific

### ISSUE THREAD

**Issue by VTCAKAVSMoACE** [SpigotMC/BungeeCord#2180]
Right now, both of these events only have references to Connections. If two players are connected from the same IP, we cannot determine which of the players sent or is being sent the tab complete. Making these events have references to CommandSenders instead would be preferable.

**Comment by Black-Hole** [comment]
So just test if the Connection is an instance of ProxiedPlayer and cast then.

**Comment by VTCAKAVSMoACE** [comment]
🤦‍♀️
