### ISSUE TITLE
elytra bug

### ISSUE THREAD

**Issue by PhanaticD** [SpigotMC/BungeeCord#2182]
when you switch servers while flying with an elytra, you are still stuck flying on the new server

**Comment by md-5** [comment]
Cannot reproduce

**Comment by PhanaticD** [comment]
make sure you are in survival mode, only happens then

**Comment by md-5** [comment]
Mhm, I am in survival.

Make sure you are using spigot 1.12 and the latest version of bungeecord with no additional plugins when reproducing.
