### ISSUE TITLE
Latest build not responding to pings and connections?

### ISSUE THREAD

**Issue by jasoryeh** [SpigotMC/BungeeCord#2183]
I installed the latest Bungeecord build, and I've tried it on two servers, and none of them respond to Minecraft's pings or connections. Older version I had laying around worked.

**Comment by jasoryeh** [comment]
I also know it is not my error, because the other servers work on the other ports. And I've tried using another port.

**Comment by i9hdkill** [comment]
Hi,
please provide the proxy log, your server specs , OS and OS version.

**Comment by jasoryeh** [comment]
Nevermind, it seems that bungeecord likes to set its default port to 25577. Thanks though.
