### ISSUE TITLE
BUNGEECORD BUG

### ISSUE THREAD

**Issue by Xxyion** [SpigotMC/BungeeCord#2184]
Hello!When I trying to connect to my bungee network ,i get this error in console: 11:10:23 [SEVERE] Error authenticating Xxyion with minecraft.net,
Here's the console log:https://pastebin.com/UD2T0wXZ,
SORRY FOR MY BAD ENGLISH;D

**Comment by kamcio96** [comment]
os, java version?

**Comment by Paulomart** [comment]
Either you use a really old java version or you sewed up your java keystore.

**Comment by Xxyion** [comment]
windows 10 ,java 8

**Comment by Xxyion** [comment]
how could I solved this?

**Comment by ninja-** [comment]
uninstall and reinstall java

**Comment by EmanYm** [comment]
It looks like it might be a server trust issue. (ssl certificates)
I was just about to type what ninja did.  Remove bungee and re-download it from spigot.

**Comment by ninja-** [comment]
no, not bungee, java

**Comment by Black-Hole** [comment]
Since it's on Windows I think an antivirus program is hijacking the SSL connection. So you should ask the producer of your security solution for help configuring it to be compatible with Java.

**Comment by Xxyion** [comment]
I reinstalled java, bungeecord and I stopped all security programs, I still get this error

**Comment by Paulomart** [comment]
I would sugest installing bungeecord on a unix like os.

**Comment by Janmm14** [comment]
I guess this is more likely something to discuss in spigotmc forums.
Could also be that your pc is missing some root certificates or the certificates are corrupted. I guess.
