### ISSUE TITLE
No ü/ö/ä

### ISSUE THREAD

**Issue by MinecraftTim123** [SpigotMC/BungeeCord#2189]
Hey there, in bungeecord plugins I can't use with UTF ä/ö//ü. It will show two ??. I am using the newest version of bungeecord (it not works on LiteAnnouncer and BungeeChat). If I write a ü, it will be shown up, but as a announce/greeting message: Only two ?? and not ü/ö/ä

Please help!

Greetings
Tim

**Comment by md-5** [comment]
BungeeCord supports UTF-8, we can't comment on individual plugins

**Comment by MinecraftTim123** [comment]
But before everything works fine and now 3/3 plugins (from separate author's) doesn't work.

**Comment by md-5** [comment]
You can see in the attached screenshot that Bungee handles these fine:
![ndz3ofr](https://user-images.githubusercontent.com/1007849/28152860-f42cc9f2-67e5-11e7-96ef-eeab89cae119.png)

**Comment by MinecraftTim123** [comment]
It works..

Do you have an idea why this is not working (ü/ä/ö)?

**Comment by MinecraftTim123** [comment]
An all 3 plugins

**Comment by md-5** [comment]
I can't comment on how other plugins are coded - I don't know.

**Comment by MinecraftTim123** [comment]
Okay, but thanks for answering so fast! :)
