### ISSUE TITLE
Error BossBar

### ISSUE THREAD

**Issue by maxw2000** [SpigotMC/BungeeCord#2190]
I have some problems if a player goes to a server with a bossbar and if he connect back he will kicked and send a error in the console

pastebin: https://pastebin.com/VBUaDg0Q

(sorry for my bad english i am from holland)

**Comment by Janmm14** [comment]
Issue is likely that the server sends the bossbar information too early.

**Comment by Black-Hole** [comment]
The BossBar packet was added in 1.9, so it isn't supported in 1.8
