### ISSUE TITLE
Bungeecord: Failed to Bind Host

### ISSUE THREAD

**Issue by CorruptedCodes** [SpigotMC/BungeeCord#2191]
Hello. I have recently connected two of my servers to Bungeecord and I have recieved this error within the console on startup.

Console Error: https://pastebin.com/N6DAgc8s

I think it has to do with the way I setup the config.yml. Do you know what it could be?

**Comment by Janmm14** [comment]
The server bungeecord runs on does not have `144.217.73.209` as public IP. Either it needs to be set up if you payed for it as additional IP address with a command (which I don't know atm) or you need to change the config again, maybe resetting the ip address in that field to `0.0.0.0:41994` which mean bungeecord binds to all ips your machine has at the port `41994`
