### ISSUE TITLE
Bungeecord: Server is Online mode! 

### ISSUE THREAD

**Issue by CorruptedCodes** [SpigotMC/BungeeCord#2192]
Hello. Sorry for the Issue spam, but I did what you said, and it worked fine, until I tried connecting to the server itself, which gives me this error: "Exception Connecting:RuntimeException : Server is online mode! @net.md_5.bungee.ServerConnector:270". I've already set the connected servers' Online Setting to False, so I don't know what else to do unless I have to set the Bungee Server to False, which I doubt is the case.

**Comment by Janmm14** [comment]
"Such issues belong into the spigotmc forums."

**Comment by md-5** [comment]
The servers need to be false, they are not (or bungee is not connecting to the right server, or you are overwriting offline mode with -o true)

**Comment by CorruptedCodes** [comment]
They are false, but for some reason it still has the same error.

**Comment by md-5** [comment]
I believe the error more than you. Use the forums for support, there is no bug.
Maybe you are even connecting bungee to itself by mistake
