### ISSUE TITLE
Request for further security options or assistance

### ISSUE THREAD

**Issue by SpiritAmet** [SpigotMC/BungeeCord#2193]
Hello again.  I am hoping that i might be able to get some further help/support for security more so than before.

Last time I requested some assistance, I was curtly pointed at: https://www.spigotmc.org/wiki/firewall-guide/

To which I had already explained I had followed to the best of my ability.

This time I am using OnlyProxyJoin.

I have ensured all of my plugins are legit and up to date, with the exception of a voting plugin being 1 update behind.

I have ensured that the setup was done correctly for BungeeCord as it was done professionally by the MCProHosting team.  I have been once again directed to come here for further support or help.

Please note, I am indeed on a shared server, so a firewall is not optional at this juncture.

![plugin list 1](https://user-images.githubusercontent.com/30029036/28297555-79e90f0c-6b23-11e7-80a4-dcb99786b1d3.JPG)
![plugin list 2](https://user-images.githubusercontent.com/30029036/28297556-7c7e6942-6b23-11e7-9486-9b3fde223cfa.JPG)

Please keep in mind thats the plugin list for the server thats being attacked (NOT the hub or the bungee server)

Please note, that the client that the griefer used before has now been updated as is found here: 
1.11.2 and 1.12 Forge pre-release!
https://skillclient.com/download.html

I have again had bungeecord professionally installed and they have assured me that all of the settings are correct and up to date, they later checked with my OnlyProxyJoin plugin and confirmed that it was set up correctly.

I am not blaming anyone, nor do i have the desire to fight or argue, I am simply here asking for any further ways to protect myself from an idiot griefer who seems to have nothing better to do but target those of us using BungeeCord.

I should further add, that he is able to mimic my account without needing the credentials. I am aware that some say thats impossible, but I assure anyone willing to offer help here, that it is completely possible and is done many times to many different people.

**Comment by SpiritAmet** [comment]
Please keep in mind thats the plugin list for the server thats being attacked (NOT the hub or the bungee server)

**Comment by md-5** [comment]
This is a bug tracker, not support forum.
spigotmc.org is a support forum.
