### ISSUE TITLE
Bungee Cord Proxy server not going online

### ISSUE THREAD

**Issue by MasterMyokan** [SpigotMC/BungeeCord#2195]
Console error's
[m[2K00:19:59 [SEVERE] Exception in thread "main" 
[m[2K00:19:59 [SEVERE] while parsing a block mapping
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:569)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
[m[2K00:19:59 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:436)
[m[2K00:19:59 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
[m[2K00:19:59 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:65)
[m[2K00:19:59 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
[m[2K00:19:59 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
[m[2K00:19:59 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
My config looks like this:
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 158.69.127.178:40112
    restricted: false
 factions:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 167.114.208.4:40260
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - hub
  bind_local_address: true
  host: 144.217.73.213:41231
  max_players: 1
  tab_size: 60
  force_default_server: true
ip_forward: true
network_compression_threshold: 256
groups:
  md_5:
  - admin
connection_throttle: -1
stats: 93cda96d-704d-4ecb-87eb-071c385e6905
prevent_proxy_connections: false

**Comment by md-5** [comment]
Invalid config, use forums for support
