### ISSUE TITLE
Making the PermissionCheckEvent cancellable

### ISSUE THREAD

**Issue by NurMarvin** [SpigotMC/BungeeCord#2196]
Make the PermissionsCheckEvent cancellable to allow customizable permission messages even for external plugins.

E.g. plugin X makes a permissions check that is not connected to a command, plugin Y (our plugin) catches the permissions check with the PermissionCheckEvent and cancels it to send a custom message

**Comment by Janmm14** [comment]
The better option I see here is modifying the other plugin. Cancelling a PermissionCheckEvent also needs to get implemented in all the other plugins.

In my opinion this might better fit into each plugin's API with a custom event.

**Comment by NurMarvin** [comment]
> The better option I see here is modifying the other plugin.
The problem is that many plugins don't allow you to modify the code.

**Comment by md-5** [comment]
The PermissionCheckEvent has no message, so this makes no sense to me

**Comment by NurMarvin** [comment]
Didn't really think that through to be honest :/ It was just an idea but after reading your comments I noticed that it isn't really possible to cancel it. Going to close the issue now
