### ISSUE TITLE
BungeeCord server query bug on some server port

### ISSUE THREAD

**Issue by danielsawan** [SpigotMC/BungeeCord#2197]
Hi there. I think i found a strange bug with bungee while trying to use query to get some server information.

When i set specific server port to bungee (33000 and more) then i don't manage to query the server using default server port or query port. I tested that using my own query script and other query script (https://dinnerbone.com/minecraft/tools/status/) to be sure this is not coming from my own script.

Exemple of working config :
------------------------------
host: 0.0.0.0:32000
query_port: 33123
bind_local_address: true
query_enabled: true

Exemple of bug config :
------------------------------
host: 0.0.0.0:33000
query_port: 33123
bind_local_address: true
query_enabled: true

I read the doc to see if there is some port range requierement but i found nothing.
Any help would be apreciated.

**Comment by ghacproductions** [comment]
I'm not a 100% sure if this problem is directly related to this bug but there was a similiar (the same?) problem on dinnerbones serverping, see here: https://github.com/Dinnerbone/mcstatus/commit/fff9b053894a916dff5db726aa91b24a48d02430 . Maybe it's the same issue here.

**Comment by danielsawan** [comment]
Oh this is exactly that ! When i use port until 32767 this work then at 32768 and after i have the bug.
I am actually using this java lib : https://github.com/rmmccann/Minecraft-Status-Query

**Comment by ghacproductions** [comment]
The commit was written in 2015, but it was merged only some months ago (see https://github.com/Dinnerbone/mcstatus/commit/ac92ee33881518548d45a3387feb7aacff514189), maybe the version running on the website is outdated?

**Comment by danielsawan** [comment]
Yeah maybe. Do you know any updated JAVA library to query / ping a Minecraft server ?
Minecraft is made in java and there is more php / other API then JAVA :(

**Comment by danielsawan** [comment]
Ok guys this is definitly not a bungee bug but librairies bug. For a strange reason some librairies work for Minecraft and not for Bungee.

**Comment by Black-Hole** [comment]
Might be helpful: https://en.wikipedia.org/wiki/Ephemeral_port
