### ISSUE TITLE
bungeecord.command.list   shows players who are vanished.

### ISSUE THREAD

**Issue by dniym** [SpigotMC/BungeeCord#2199]
would it be possible to hide players who are vanished or invisible from listing on bungeecord.command.list?
it does not have to be on all servers but perhaps they could be removed from the list if the player invoking the command can not see the player on the list if they're on the same server.

**Comment by md-5** [comment]
How would bungee know they are vanished?
Vanish is implemented by plugins.

**Comment by dniym** [comment]
if(!player1.canSee(player2))
    //dont show in player1's list

**Comment by Black-Hole** [comment]
That Player.canSee() is a Bukkit feature. It's not know to BungeeCord. Maybe some plugin is offering an alternative list command based on the entries in the player list.

**Comment by dniym** [comment]
Ah, I suppose that does pose a problem.  I suppose I could intercept glist and override it with a custom version that does this.

**Comment by md-5** [comment]
You can't do that from bungeecord lol

**Comment by phenomax** [comment]
@dniym One way to achieve your wanted result would be replacing the /list command with an own solution, which cares about vanished players. You have to tell bungeecord (e.g. via plugin messages) that the player x is vanished and shall not be listed.

**Comment by md-5** [comment]
Closing this as wontfix, outside of bungee scope
