### ISSUE TITLE
YAMLException issue

### ISSUE THREAD

**Issue by ImAleexMC** [SpigotMC/BungeeCord#2201]
Hello, I have an issue

I start the .bat BungeeCord and the config say this https://gyazo.com/26cb79beb10c1473aaf865c5cf2ed66c

Here are my plugins https://gyazo.com/5436e47b0701485fea41e1a96fb7adcc

And here my config: ip_forward: false
custom_server_name: BungeeCord
log_commands: false
listeners:
- query_port: 25565
  motd: '&6&lMagistral&c&lNetwork &8 | &d&lSERVIDOR &b 1.7.x / 1.8.x | &e&l+ NUEVO!
    &3&l¡UHC!'
  tab_list: SERVER
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 300
  tab_size: 60
  force_default_server: false
always_handle_packets: false
online_mode: false
connection_throttle: 4000
groups:
  md_5:
  - admin
  ImAleex:
  - admin
player_limit: -1
prevent_proxy_connections: false
permissions:
  default:
  - skinsrestorer.playercmds
  - bungeepinger.viewownping
  - report.use
  - BungeeBan.Broadcast.Mute
  - BungeeBan.Broadcast.Unmute
  - BungeeBan.Broadcast.Unban
  - BungeeBan.Broadcast.Ban
  admin:
  - BungeeBan.Broadcast.Mute
  - BungeeBan.Broadcast.Unmute
  - BungeeBan.Broadcast.Unban
  - BungeeBan.Broadcast.Ban
  - bungeecord.command.server
  - bungeecord.command.list
  - bungeepinger.viewothersping
  - bungeepinger.hideothersping
  - report.see
  - BungeeBan.Ban
  - BungeeBan.Tempban
  - BungeeBan.Unban
  - BungeeBan.Mute
  - BungeeBan.Tempmute
  - BungeeBan.Unmute
  - BungeeBan.Check
  - BungeeBan.Kick
stats: 4ca58dd4-c7c5-49fc-b141-0a261d21c0b1
disabled_commands:
- disabledcommandhere
timeout: 30000
servers:
  lobby:
    motd: '&6&lMagistral&c&lNetwork &8 | &d&lSERVIDOR &b 1.7.x / 1.8.x | &e&l+ NUEVO!
      &3&l¡UHC!'
    address: 0.0.0.0:25566
    restricted: false
  uhc:
    motd: '&6&lMagistral&c&lNetwork &8 | &d&lSERVIDOR &b 1.7.x / 1.8.x | &e&l+ NUEVO!
      &3&l¡UHC!'
    address: 0.0.0.0:25567
    restricted: false
network_compression_threshold: 256

PLEASE HELPME

**Comment by i9hdkill** [comment]
This no support area. It‘s for bugs only. Visit spigotmc forums to get support - or - like it has been suggested before, use a yaml checker to fix your config.

**Comment by Janmm14** [comment]
(You are still not using bungeecord.)
