### ISSUE TITLE
Bungee Crash 

### ISSUE THREAD

**Issue by JamieSinn** [SpigotMC/BungeeCord#2205]
Server log:
https://gist.githubusercontent.com/andrewkm/51bdc5cbab7889ab20103264efcbdfac/raw/5cb44b083facf40625ef20e1d26d5ed03b289359/gistfile1.txt

Crash Log:
https://gist.githubusercontent.com/andrewkm/4f3014e149436bc727f71c289e6391a4/raw/a5b97a080bdb0df4eb0b6069f0541cd98eacd5f5/gistfile1.txt

FYI - Running latest Java 1.8.0_141-b15

**Comment by md-5** [comment]
If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#

**Comment by Paulomart** [comment]
It seems that you run in Windows I would recommend running Bungee on Linux.
