### ISSUE TITLE
Players cannot connect

### ISSUE THREAD

**Issue by itslukemango** [SpigotMC/BungeeCord#2206]
17:14:39 [INFO] [nonamelikethis] <-> ServerConnector [Lobby] has connected
17:14:41 [INFO] [nonamelikethis] -> UpstreamBridge has disconnected

Keeps getting disconnected

**Comment by kamcio96** [comment]
Try without plugins

**Comment by i9hdkill** [comment]
This isn't a support area. If you really think that this is a bug (Which pretty sure isn't the case), add more info to this ticket.
Otherwise please head to the forums post your issue there.
