### ISSUE TITLE
pls help me Bungeecord lag, timeout

### ISSUE THREAD

**Issue by FlexVN** [SpigotMC/BungeeCord#2207]
Each time it lag it will show 4-5 lines 
java.io.IOException: An established connection was aborted by the software in your host machine.
example

> 08:25:19 [WARNING] [/************:57114] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57118] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57109] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57106] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57141] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57143] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57148] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57150] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57152] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57120] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57153] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine
08:25:19 [WARNING] [/************:57115] <-> InitialHandler - IOException: An established connection was aborted by the software in your host machine

**Comment by md-5** [comment]
This is a bug tracker not support.
