### ISSUE TITLE
Are there any plans to support Java 9 yet?

### ISSUE THREAD

**Issue by scholzi100** [SpigotMC/BungeeCord#2209]
Well, as you might already have read Java 9 will be released 21st September of this year.
The JDK team already finished the collection of all features on 26 May last year. 
I already testet around with JDK 9, and there a some problem with Jigsaw belonging to Netty,  Lombok and generally modularisation.  

### So I wanted to know if there are plans to support Java 9?
(maybe after Netty and Lombok upgraded, at some later point in time)

**Comment by Paulomart** [comment]
Im pretty sure bungeecord will always support latest java versions.

**Comment by md-5** [comment]
BungeeCord runs fine on Java 9.
If you are experiencing a particular issue, open a bug report.

**Comment by caoli5288** [comment]
It must be no issue with lombok it's a compile scope lib NOT runtime's.
