### ISSUE TITLE
Bungeecord save logs lag?

### ISSUE THREAD

**Issue by FlexVN** [SpigotMC/BungeeCord#2211]
I have tried testing more than 10 times and every time logs are updated it will lag both the console and the server
My config bungeecord:
https://www.hastebin.com/zoqaqigapu.go
My bukkit.yml for all server:
https://www.hastebin.com/obowisecuk.coffeescript
My spigot.yml for all server:
https://www.hastebin.com/oyucucequh.swift
My server.properties:
https://www.hastebin.com/yigaselazo.ini
:( please help me

**Comment by Janmm14** [comment]
This is for actual bugs. Go to the spigotmc forums for support.

**Comment by FlexVN** [comment]
https://www.spigotmc.org/threads/bungeecord-save-logs-lag.263663/
here :(

**Comment by md-5** [comment]
BungeeCords logs are entirely asynchronous.
Do you have any evidence that printing a message causes lag?

**Comment by FlexVN** [comment]
I use notepad ++ to open proxy logs and monitor
When it lags it will appear a logs line and after the lag it appears several lines again

**Comment by FlexVN** [comment]
This is an error
My bungeecord used 5 months now normally suddenly 4-5 days it appears problematic

**Comment by caoli5288** [comment]
I'm very sure bungeecord's log file backend works async. It's no possible lags server.
