### ISSUE TITLE
Player count issue

### ISSUE THREAD

**Issue by Icalave** [SpigotMC/BungeeCord#2212]
Player count only showing our Hub numbers for some reason on the multiplayer server list

https://pastebin.com/7kKxfdXW

**Comment by md-5** [comment]
Reproduce without plugins, works fine here:

>glist
08:19:13 [INFO] [lobby] (0): 
08:19:13 [INFO] Total players online: 0


version 1256

**Comment by Icalave** [comment]
See its doing that glist fine and getting the correct total players on the console what isn't working is it showing the correct amount of players in the multiplayer server list shows 0/100 or 2/100 if there are players in the hub, but when players are in my survival server and lets say 7 of them are in survival the server list still shows 0/100 cause no one is in hub
The only update i did was to the recent release of bungeecord

**Comment by Icalave** [comment]
If you look at this section of the console it is actually doing this part correctly

09.08 03:22:06 [Server] INFO CONSOLE executed command: /glist
09.08 03:22:06 [Server] INFO (0):
09.08 03:22:06 [Server] INFO (5): Camo578, ebartlow, lukiepie, Mxlppxl, TheIQFactor
09.08 03:22:06 [Server] INFO (1): Alex_Vampira
09.08 03:22:06 [Server] INFO (0):
09.08 03:22:06 [Server] INFO Total players online: 6
