### ISSUE TITLE
connection throttle

### ISSUE THREAD

**Issue by Scorpionvssub** [SpigotMC/BungeeCord#2218]
10.08 12:21:51 [Server] WARNING [ImaBear] -> UpstreamBridge - read timed out 
10.08 12:21:51 [Server] [Informatie] [ImaBear] disconnected with: ReadTimeoutException : null 
10.08 12:21:51 [Server] [Informatie] [ImaBear] -> UpstreamBridge has disconnected 

This person along side others keep getting this.
It takes them 390 tries before they can log in and seems if they keep moving its fine.
Soon as they stop moving wait 1-5 seconds  "Disconnected" shows up in their face.

I've updated everything all spigot servers have -1 and bungee was connection throttle 4000 and even tried 10k just to see what happens

This only happens in the bungee not the single servers that arent connected to bungee

**Comment by md-5** [comment]
This is nothing to do with connection throttle, and increasing connection throttle will actually prevent more connections.
Read timed out suggests an issue with your server configuration, please reproduce without plugins and use the forums - spigotmc.org for support

**Comment by Scorpionvssub** [comment]
even without plugins it does this.
