### ISSUE TITLE
Bungeecord stops working immediatly

### ISSUE THREAD

**Issue by JeffyGaming** [SpigotMC/BungeeCord#2219]
**Here is the console when I start it up...**

11.08 08:49:36 [Server] SEVERE Exception in thread "main" 
11.08 08:49:36 [Server] SEVERE while scanning for the next token
11.08 08:49:36 [Server] INFO found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
11.08 08:49:36 [Server] INFO in 'reader', line 46, column 1:
11.08 08:49:36 [Server] INFO lobby:
11.08 08:49:36 [Server] INFO ^
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:420)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingValue.produce(ParserImpl.java:585)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:133)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
11.08 08:49:36 [Server] SEVERE at org.yaml.snakeyaml.Yaml.load(Yaml.java:436)
11.08 08:49:36 [Server] SEVERE at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
11.08 08:49:36 [Server] SEVERE at net.md_5.bungee.conf.Configuration.load(Configuration.java:65)
11.08 08:49:36 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
11.08 08:49:36 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
11.08 08:49:36 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**And here is the config...**

groups:
  md_5:
  - admin
ip_forward: true
network_compression_threshold: 256
stats: d08ac203-36db-45a2-9351-1f30a20781ef
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
online_mode: false
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 198.27.89.248:25591
    restricted: false
timeout: 30000
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    crafty-city.mcph.co: lobby
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 198.27.89.248:25591
  max_players: 40
  tab_size: 60
  force_default_server: true
prevent_proxy_connections: false
player_limit: -1
disabled_commands:
- disabledcommandhere
log_commands: false
connection_throttle: 4000
servers:
	lobby:
		motd: 'Lobby'
		address: 162.244.165.141:31308
		restricted: false
	skyblock:
		motd: 'Skyblock'
		address: 198.27.89.248:25607
		restricted: true

**What am I doing wrong? What is causing this? And how do I fix it? Please respond.**

**Comment by md-5** [comment]
11.08 08:49:36 [Server] INFO found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)


Read.

**Comment by JeffyGaming** [comment]
So how do I get rid of that?

**Comment by md-5** [comment]
Stop using tabs in your config.
http://yaml-online-parser.appspot.com/

**Comment by JeffyGaming** [comment]
I know what I am supposed to do but **how** exactly do I do it?

**Comment by Janmm14** [comment]
Ask on the spigotmc forums, not here. This is no place for support.
