### ISSUE TITLE
How do I get rid of this?

### ISSUE THREAD

**Issue by JeffyGaming** [SpigotMC/BungeeCord#2220]
11.08 08:49:36 [Server] INFO found character '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)

**Explain to me how I am supposed to stop that?**

**Comment by Janmm14** [comment]
First, this is the wrong place to ask. Use the spigotmc forums for that.
Second, .yml files should never contain any tab characters, but spaces instead.
