### ISSUE TITLE
How do I fix this severe error in my server console that is stopping me from starting up the BungeeCord server?

### ISSUE THREAD

**Issue by elastic-owner** [SpigotMC/BungeeCord#2221]
#11.08 09:41:42 [Server] SEVERE Exception in thread "main" 
11.08 09:41:42 [Server] SEVERE java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
11.08 09:41:42 [Server] SEVERE at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:200)
11.08 09:41:42 [Server] SEVERE at net.md_5.bungee.conf.Configuration.load(Configuration.java:94)
11.08 09:41:42 [Server] SEVERE at  #net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
11.08 09:41:42 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
11.08 09:41:42 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Janmm14** [comment]
You have an error in your configuration. Ask onthe spigotmc forums for support.
