### ISSUE TITLE
Got Rid of Tab. Now what do I do?

### ISSUE THREAD

**Issue by JeffyGaming** [SpigotMC/BungeeCord#2222]
It's still not working. Here is the console: https://pastebin.com/StgHAidt

And here is the config once more: https://pastebin.com/ZZphFdvt

What's the issue?

**Comment by i9hdkill** [comment]
Why don‘t you use the old ticket? As md_5 said, this isn‘t a support area, it‘s for bugs only and this is clearly not a bug. Please visit spigotmc BungeeCord forums to get support.

**Comment by JeffyGaming** [comment]
That's the issue. There's literally nobody helping us here or the forums. Why can't they just tell us what to do so we can shut the fuck up about it...
