### ISSUE TITLE
Memory leak 

### ISSUE THREAD

**Issue by MedicOP** [SpigotMC/BungeeCord#2223]
Ever since upgrading from the 1.12 build to the 1.12.1 build of BungeeCord, I've been experiencing a memory leak that is causing BungeeCord to crash after a few days. I don't know which build introduced the problem, it may have been one of the builds before it.

Memory snapshot shows 4 million objects of io.netty.channel.ChannelOutboundBuffer$Entry. There were around 250 players online when the snapshot was taken.

![screenshot_1](https://user-images.githubusercontent.com/18251099/29319489-83aa9b06-81d4-11e7-9def-6c32d4aeaa4b.png)

Object explorer on one of the ChannelOutboundBuffer#Entry shows this:
![screenshot_2](https://user-images.githubusercontent.com/18251099/29319973-1fc859c8-81d6-11e7-8fb8-164adb763e5e.png)

I can upload the snapshot if needed

**Comment by Janmm14** [comment]
@MedicOP Plugins?

**Comment by MedicOP** [comment]
AdvancedBungeeAnnouncer, RedisBungee, and 11 custom ones

**Comment by Janmm14** [comment]
(I guess you are sure those don't have any memory leaks. Maybe do a quick search in that snapshot for those plugins to be 1000% sure)

**Comment by MedicOP** [comment]
Yes, I have checked but no classes that use my package prefix retain more than a couple of MBs. The issue also only started happening recently after I updated to 1.12.1 build of Bungee, and the plugins have not been changed during that time.

**Comment by md-5** [comment]
Please provide a compressed heap dump with a small heap size containing no plugins.

Also try various builds to see where the issue was introduced, we need a specific build. There have been only 8 versions, so you shouldn't need to test more than 4 to find the problem.

**Comment by MedicOP** [comment]
The older builds don't support 1.12.1, and the plugins are necessary for the server (moderation, player count, what not)

Can you say which one of the changes is the most likely to be the cause of the memory leak?

Would "Replace OpenSSL native cipher" or "Use statically linked zlib" or "Use property to skip deploy" or "Update Animal Sniffer" even have a possibility to cause a leak?

If it's most likely the Netty updates causing the issue, I could try compiling a build with older Netty version

**Comment by MedicOP** [comment]
Hmm.. What does it mean when 'top' says it's using 14 GBs of memory while YourKit says only 2.1GB?

![-lkn3wpes3q4g30cmt5zww](https://user-images.githubusercontent.com/18251099/29345158-1f2c0480-823d-11e7-8dde-313eaa97cbf6.png)
![screenshot_1](https://user-images.githubusercontent.com/18251099/29345159-1f337490-823d-11e7-8591-ea9dd343bd4f.png)

**Comment by MedicOP** [comment]
Apparently this mean it's an off-heap memory leak. Could it be the change to the native cipher then?

**Comment by Janmm14** [comment]
I would try with an older netty version in that case.

**Comment by MedicOP** [comment]
Tried with 1.12 build and just cherry picking the 1.12.1 commit, but still happening. Running out of ideas here
