### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by ProDash1998** [SpigotMC/BungeeCord#2224]
22:06:28 [INFO] [BungeePerms] Adding default groups to ProDash
22:06:28 [INFO] [ProDash|/127.0.0.1:59846] <-> ServerConnector [hub1] has connected
22:06:29 [SEVERE] java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
22:06:29 [SEVERE] 	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:54)
22:06:29 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
22:06:29 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
22:06:29 [SEVERE] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
22:06:29 [SEVERE] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
22:06:29 [SEVERE] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
22:06:29 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
22:06:29 [SEVERE] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
22:06:29 [SEVERE] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
22:06:29 [SEVERE] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
22:06:29 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
22:06:29 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
22:06:29 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
22:06:29 [SEVERE] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
22:06:29 [SEVERE] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
22:06:29 [SEVERE] 	at java.lang.Thread.run(Unknown Source)

and A player can using command end

**Comment by Black-Hole** [comment]
Every player with the permission "bungeecord.command.end" can use the /end command.

You should use the forums for help configuring your server. Your chances for receiving help there are much higher if you provide a lot of details about your server setup, like plugins and BungeeCord version.

**Comment by md-5** [comment]
No version provided

**Comment by ProDash1998** [comment]
all version (add suport in 1.12.x version BungeeCord-1233+)

**Comment by md-5** [comment]
Impossible, the error you have pasted does not exist in build 1259.

**Comment by ProDash1998** [comment]
sorry my bad
I've mistaken file names
