### ISSUE TITLE
Send chat action by plugins to BungeeCord

### ISSUE THREAD

**Issue by metroyanno** [SpigotMC/BungeeCord#2226]
Writing here because SpigotMC/Spigot repo blocked. Please, make sending by plugins (in Spigot) chat actions first to BungeeCord to process by them plugins

**Comment by Black-Hole** [comment]
If you're looking for the Spigot issue tracker:
https://hub.spigotmc.org/jira/secure/Dashboard.jspa

It looks like you are trying to filter chat messages sent by Spigot plugins on a BungeeCord server? That would already be possible. But the preferred way would be to talk to the plugin author to add an option to disable those messages.

For help creating a chat filter plugin please use the forums.
