### ISSUE TITLE
CorruptedFrameException

### ISSUE THREAD

**Issue by MinelandTeam** [SpigotMC/BungeeCord#2230]
I use bungeecord build #1​25​3.
This errors is written all the time.
"io.netty.handler.codec.CorruptedFrameException: length wider than 21-bit"
And "io.netty.handler.codec.DecoderException: java.lang.RuntimeException: VarInt too big"
![buneeerror](https://user-images.githubusercontent.com/30803993/29579619-02179140-877c-11e7-8726-aa10f4c28b5c.jpg)
![screenshot_3](https://user-images.githubusercontent.com/30803993/29579617-01fdce2c-877c-11e7-91ba-630970024bbb.jpg)
![screenshot_4](https://user-images.githubusercontent.com/30803993/29579618-0201ae66-877c-11e7-9731-1203cbeee094.jpg)

**Comment by Janmm14** [comment]
This report is missing crucial information.
Bungee plugins?
Spigot plugins?
Used minecraft version?
Used modded client?

**Comment by MinelandTeam** [comment]
Minecraft version 1.8-1.12
I can not know if the players use the modified client.
One thing I can say is that when I came in, from the usual client version 1.8 - 1.12 - there were no errors. I think they are bots.
In addition, the error occurs during the Initial Handler, so I do not think that Spigot plug-ins are important. Since the error occurs even when all Spigot servers are turned off.
Concerning bungeePlugins - I'm using a self-contained plugin. But, I can say that the error does not come from him. Because it does not modify the BungeeCord code.
There are no errors on the local server. And there is a errors, started today. During two days of work and tonight, everything was fine, but in the afternoon, there were errors (BungeeCord did not restart). Someone started sending strange packets, as seen in the screenshots. I can say that errors occur, mostly with duplicate IP addresses. I think someone purposely sends out the wrong packages.
In the screenshots, you can pay attention to the fact that the errors come from those ips that send strange packets. I want to say that despite the presence of errors, players do not have problems with the connection and they do not give out errors.
![wows](https://user-images.githubusercontent.com/30803993/29587016-46fab2ce-8795-11e7-9316-82b142063884.jpg)
![screenshot_6](https://user-images.githubusercontent.com/30803993/29587023-4b0d2310-8795-11e7-9fd8-f3ec447322d9.jpg)
![ips](https://user-images.githubusercontent.com/30803993/29587028-4d7727b8-8795-11e7-93d4-ba43c15ea54c.jpg)
![ipss](https://user-images.githubusercontent.com/30803993/29587033-4fb34e8a-8795-11e7-9d35-d3b2a8a04f99.jpg)

**Comment by Janmm14** [comment]
So what you experience is either a player who always tries to reconnect with his heavily modified client, or some automated system sending whatever requests to your server.

This does not look like it could ever be a valid minecraft client and as long you do not have any players telling you that they can't connect or get disconnected randomly you will probably have to live with such a spammy console.

**Comment by Fejm** [comment]
31.185.104.19 = Anonymous Proxy

Seems like bot attack or some cheat. 

Block with iptables or just ignore.

**Comment by MinelandTeam** [comment]
Thanks for the answer.
