### ISSUE TITLE
"Connection lost" message.

### ISSUE THREAD

**Issue by KevSlashNull** [SpigotMC/BungeeCord#2231]
Compared to build 1259 (fd67502):
If players connect to BungeeCord in the 1260 build (bd5a7e5) and get kicked in the `PreLoginEvent` they will be disconnected with `Connection lost` instead of the specified [cancelReasonComponents](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/event/PreLoginEvent.java#L72).

Kev ^-^

**Comment by md-5** [comment]
![h5ps8ztrhg](https://user-images.githubusercontent.com/1007849/29735678-0c433db2-8a3e-11e7-981d-34674ed411d3.png)

cannot reproduce
