### ISSUE TITLE
Issue with sending titles?

### ISSUE THREAD

**Issue by FlyingPikachu** [SpigotMC/BungeeCord#2232]
Hello, I am the current author of the [Quests](https://www.spigotmc.org/resources/quests.3711/) plugin.

One of my users reports players getting kicked whenever a title is received on his BungeeCord server. I have never used BungeeCord and am unable to assist him further. This is the error @Legendaryx receives:

> [06:33:08] [Server thread/INFO]: Title command successfully executed
[06:33:08] [Server thread/INFO]: Title command successfully executed
[06:33:08] [Server thread/INFO]: LeGenDaryX lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

and

> Internal Exception: io.netty.handler.codec.DecoderException: java.lang.ArrayIndexOutOfBoundsException: 63

This is not the first time I've heard of this problem, but he's the first to provide an error. You can see how
the Quests plugin sends titles [here](https://github.com/FlyingPikachu/Quests/blob/3b394dfad7813ac1925f089ae3b3a82db86a08e0/src/main/java/me/blackvein/quests/Quest.java#L351), but he claims that _any_ plugin utilizing titles produces similar errors.

Source: https://github.com/FlyingPikachu/Quests/issues/106

**Comment by i9hdkill** [comment]
We are using Quests + titles on 1.12.1 BungeeCord + Spigot 1.12.1 without any issues. 
User should update to latest bungee and spigot and check his setup.
If he is still getting this issue, he should try again without any bungee/spigot plugins (Just Quests and maybe Vault).
We will reopen this ticket if the issue persists.
