### ISSUE TITLE
Command /server +TAB - Disconnect

### ISSUE THREAD

**Issue by Eclixal** [SpigotMC/BungeeCord#2233]
Hello,

I have just done the last update of BungeeCord, but when I make the command /server and pressing Tab, my client logs off leaving this error in the console. I try by reinstalling the Bungeecord but still the same problem on this module, the others work! 

https://hastebin.com/dadazapusu.lua 
Eclixal,

**Comment by Black-Hole** [comment]
What is your output of "java -version"?

**Comment by md-5** [comment]
Cannot reproduce

**Comment by md-5** [comment]
04:39:02 [INFO] This server is running BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:bd5a7e5:1260 by md_5

**Comment by Eclixal** [comment]
Java version: Java(TM) SE Runtime Environment (build 1.8.0_144-b01)

I have retry with http://ci.md-5.net/job/BungeeCord/lastSuccessfulBuild/artifact/bootstrap/target/BungeeCord.jar but have the same error :/

**Comment by ApocalypsjeNL** [comment]
Try removing your modules folder

**Comment by Eclixal** [comment]
I just tried but still the same thing: /

**Comment by Black-Hole** [comment]
Could you please try without any plugins?

**Comment by Eclixal** [comment]
Still sorry, I did not test to remove the plugins, it is one of my plugins that is not compatible, thank you for your help.
