### ISSUE TITLE
error enable plugin 

### ISSUE THREAD

**Issue by GiwrgosMasterGR** [SpigotMC/BungeeCord#2234]
Hello i have this problem with a lot of plugins. Like /hub /lobby and bungeeportals. i try to install.. and i have problem with jdk (one error) i have jdk 8 and says want jdk 7 (sorry for bad english)
One screenshot from the error code here http://prntscr.com/gemzuh

topic in spigot:
https://www.spigotmc.org/threads/errors-with-plugins.269500/#post-2639352
im using last version bungeecord.

**Comment by md-5** [comment]
You cant load bukkit plugins on bungee

**Comment by GiwrgosMasterGR** [comment]
http://prntscr.com/gf5pam
from here all works>?

**Comment by Janmm14** [comment]
@GiwrgosMasterGR The plugin requires a bungeecord to exist somewhere, but it has to be put on each subserver (spigot server) that should have such portals.
