### ISSUE TITLE
Custom event declared in a plugin can't be listened from outside

### ISSUE THREAD

**Issue by ramaroberto** [SpigotMC/BungeeCord#2239]
Hey there,

I was working in fixing a plugin that adds a custom event (https://www.spigotmc.org/wiki/event-api/) when a packet arrives. From the domain of the same plugin it works well and I can listen to the event, but it doesn't work when I try to listen within the domain of another plugin.

I tracked down the problem to the use of different ClassLoaders during the loading of the plugins in the PluginManager module. Since it uses different class loaders, the PacketEvent class gets two different references (one from the plugin where it's defined, and one from the external plugin), making the "byListenerAndPriority" and "byEventBaked" maps (which are using event classes as keys) inside the EventBus module (which is the core component of the event dispatcher) to differentiate between them.

This is an intended behavior? I realize that not having this can maybe give some security issues / compatability problems between plugins, but just asking to be sure this is path that shouldn't be followed.

This is what I got when printing out "byListenerAndPriority" as an entrySet. We can see that "PacketEvent" key is repeated two times.

>[class net.md_5.bungee.api.event.ServerConnectedEvent={0={org.spawl.bungeepackets.BungeePackets@6ae5aa72=[Ljava.lang.reflect.Method;@8f4ea7c, ar.com.gamerarg.gmaclientvalidator.GMAClientValidator@131774fe=[Ljava.lang.reflect.Method;@77847718}},
>class org.spawl.bungeepackets.event.PacketEvent={0={org.spawl.bungeepackets.PacketListener@515aebb0=[Ljava.lang.reflect.Method;@6c64cb25}},
>class org.spawl.bungeepackets.event.PacketEvent={0={ar.com.gamerarg.gmaclientvalidator.PacketListener@c8c12ac=[Ljava.lang.reflect.Method;@6adbc9d}}]`

When printing out the PluginClassLoader of the two class references we can see that they are actually different, making the maps to differentiate them:

>net.md_5.bungee.api.plugin.PluginClassloader@2aece37d
>net.md_5.bungee.api.plugin.PluginClassloader@7920ba90

Thanks in advance!

**Comment by md-5** [comment]
You are probably including the event in both plugins, only one plugin should have the event.
See https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/PluginClassloader.java#L38

If this is still an issue, provide a minimal reproduction.
