### ISSUE TITLE
cross-world bleeding

### ISSUE THREAD

**Issue by smmmadden** [SpigotMC/BungeeCord#2240]
No better way to describe what I'm seeing that I know of.  I'm on the latest [BungeeCord build 1261, Spigot Servers 1.12.1](https://pastebin.com/Xes9b8Td) built today on Windows 10 Pro x64, Java 1.8.0_141x64 and when I travel from world to world, I'm getting images bleeding through from the "last world" into the next world.  For example, the image below is from the world named "tester".
![image](https://user-images.githubusercontent.com/10309346/30000059-ce1fcda8-902c-11e7-8bbd-923a9da99d28.png)
The problem is that the houses and the dome shown above, do not exist in "tester".  They exist in the world I came from "future".    What's odd is, if I fly towards the houses/dome or whatever cross-world bleeding image I see, it slowly disappears and paints what should be there.
![image](https://user-images.githubusercontent.com/10309346/30000078-5f969d02-902d-11e7-84ae-474a21cf4cc9.png)
Here is one repainting as I get closer.
![image](https://user-images.githubusercontent.com/10309346/30000091-ab158270-902d-11e7-8f0d-c38f9ade3f27.png)
Not sure when this started (build), but it's more pronounced now going world to world.  Other than the warnings in the logs I've already reported to the plugin owners, [startup looks pretty good](https://pastebin.com/mazjCdCL).  It's just the screen painting from using /server (/tester, /future, etc.) to jump between worlds that's messed the rendering isn't happening fast enough (or completely).  Any ideas?  Thanks, Steve

**Comment by md-5** [comment]
It looks like you are using a modded client.
Please reproduce on a clean map with clean server / client.

**Comment by smmmadden** [comment]
Sorry, but it has nothing to do with what what resource pack I'm using on the client.  Even with no resource packs (just the default), the issue is still there.
![image](https://user-images.githubusercontent.com/10309346/30002662-1225ffb8-907d-11e7-829a-530250223403.png)

**Comment by Janmm14** [comment]
@smmmadden
He did not spoke about resource packs, but about the client itself. Are you using an official unmodified client by mojang?

**Comment by smmmadden** [comment]
Yes - I always and only used licensed products. I don't use any hacked clients, software of any kind or hardware of any kind or any pirated software.  Not my first post here reporting issues.
I host my own servers, keep them all up-to-date with the latest released versions, including Java, the client, servers and plugins.  :-)

**Comment by smmmadden** [comment]
plugins used on BungeeCord
![image](https://user-images.githubusercontent.com/10309346/30002864-88fc7e92-9081-11e7-9980-f5dd7a7c55c6.png)

**Comment by smmmadden** [comment]
plugins used on bungeecord
![image](https://user-images.githubusercontent.com/10309346/30002867-9a28999e-9081-11e7-8893-974f9327a3f9.png)

**Comment by Black-Hole** [comment]
Please try without FastConnect.

**Comment by Janmm14** [comment]
After looking at fastconnect, it seems that it is the plugin which can cause such issues.

**Comment by smmmadden** [comment]
spot on! Thanks guys for the support and quick RCA.  Removing FastConnect from BC plugins did the trick.  

Any suggestions I can relay to the plugin owner for addressing this?

**Comment by Janmm14** [comment]
Possible solution is to teleport the player once to a place far away and back to force unloading chunks.
Other possible solution is to set the view distance equal for all your servers, then chunks in view distance should replace themself with a little delay.

**Comment by smmmadden** [comment]
sounds like a plan, I'll give it a shot today and see if that will help.  Thanks again!

**Comment by smmmadden** [comment]
I've reset all my worlds so they have the same timings and chuck views so at least it is consistent. Not seeing any bleeding any more.
