### ISSUE TITLE
Calling PlayerKickEvent when a server stops unexpected

### ISSUE THREAD

**Issue by xXAlex10Xx** [SpigotMC/BungeeCord#2243]
Hey,

i tried to figure out which event is called, when a server stops unexpected and the user gets reconnected.
It seems to me that just the ServerDisconnectEvent and the ServerConnectEvent are called, but in my opinion it would be useful to call the ServerKickEvent with some reason, due to the fact, that the player would have been kicked, if it wasn't Bungeecord.

In my case it is the following problem:
If I am on a lobby, which stops unexpected (killed, crashed, whatever) my lobbydistributor tries to reconnect me to that lobby, cause the plugin does not know the lobby crashed. With the ServerKickEvent this issue could be fixed simple.

Thanks for reading :)

**Comment by kjl13** [comment]
Great Idea, would love to see this implemented.

**Comment by md-5** [comment]
No, that makes no sense. ServerDisconnectEvent is the event you are looking for. ServerKickEvent is for when the player is kicked with a reason, ServerDisconnectEvent is for when the player is disconnected for any reason (ie lobby crashed)

**Comment by xXAlex10Xx** [comment]
Okey, can u add a DisconnectReason to the event? Cause the event is also fired, when a user changes server on purpose.
