### ISSUE TITLE
Bungee on MacOS

### ISSUE THREAD

**Issue by StarstrikeGaming** [SpigotMC/BungeeCord#2247]
I get this error:

16:36:46 [INFO] Using standard Java JCE cipher.
16:36:46 [INFO] Using standard Java compressor.
16:36:46 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ef326db:1263
16:36:46 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
16:36:46 [WARNING] Epoll is not working, falling back to NIO: ExceptionInInitializerError : null @ io.netty.channel.epoll.Epoll:33
16:36:46 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
16:36:46 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
16:36:46 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
16:36:46 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
16:36:46 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
16:36:46 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
16:36:46 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
16:36:46 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
16:36:46 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
16:36:46 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
16:36:46 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
16:36:46 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
16:36:46 [SEVERE] Exception in thread "main" 
16:36:46 [SEVERE] java.lang.IllegalArgumentException: Server lobby (priority 0) is not defined
16:36:46 [SEVERE]     at com.google.common.base.Preconditions.checkArgument(Preconditions.java:359)
16:36:46 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:123)
16:36:46 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
16:36:46 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
16:36:46 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

How to fix? I'm on a Mac.

**Comment by md-5** [comment]
Your config is invalid
