### ISSUE TITLE
"Already connected to server" when connecting 1.11.2 -> 1.12.1

### ISSUE THREAD

**Issue by Kopo942** [SpigotMC/BungeeCord#2250]
```
Game versions:
Client: 1.11.2
Lobby: Spigot 1.11.2
Survival: Spigot 1.12.1
```

I discovered a little problem with BungeeCord (or Spigot..? dunno.). When trying to connect from Lobby to "Survival" using a 1.11.2 client, Bungee throws an error in the chat saying I am already connected to that server while I'm obviously not. If I execute the same command a second time (/server Survival), Bungee tells me (like it should on the 1st time) I need MC 1.12.1 to connect to that server. Another weird thing is that if I have a 3rd server AND the "priorities" list configured, and try to connect to the Survival server, the first time it again says I'm already connected, but on the second time, it throws me to the third server, which shouldn't happen (atleast in my opinion).

Configs: https://pastebin.com/zB7Fh1Du

**Comment by kjl13** [comment]
It looks like in your situation, this is being caused because your Survival server is 1.12.1 and your Client Version is 1.12.2 unless you are running a plugin like ViaBackwords this will not be possible. Id recommends you check it out or update the version of your survival server.

**Comment by md-5** [comment]
Bungee only supports 1:1 version connections, as above this must be the product of a plugin
