### ISSUE TITLE
Dangerous Exception

### ISSUE THREAD

**Issue by MinelandTeam** [SpigotMC/BungeeCord#2251]
Thrown exeption:
io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 2))
Exception CODE: https://pastebin.com/FpST7SH2

I'm even sure. Most likely, these are bots.
The server is often attacked. And I think, this time, this is also an attack.
I use bungeecord build #1​25​3.
The server on this assembly has been running for a long time. Restarts, every day at 6:00. The plugins have not changed, the bungee code has not changed. Before that, the server worked for a couple of weeks without problems. But today this exception happened. During the release of this exception, BungeeCord ceases to accept new players and stops throwing players between servers. Unfortunately, it is impossible to analyze the error in detail, since all the logs have been completely rewritten in a couple of minutes. At the time of the error, even the connection is lost, to the JMX.
I think a huge number of bots are doing something strange at the Initial Handler stage - forcing BungeeCord to throw such an exception.
![start](https://user-images.githubusercontent.com/30803993/30298678-f4db8cd2-9754-11e7-822c-e60d815a4297.jpg)
![end](https://user-images.githubusercontent.com/30803993/30298680-f50c7d06-9754-11e7-8a91-570b5409e9e7.jpg)
![logs](https://user-images.githubusercontent.com/30803993/30298679-f4f93174-9754-11e7-9b0a-8df00910c9f4.jpg)

**Comment by Dimatert9** [comment]
#2246

**Comment by MinelandTeam** [comment]
Есть идеи как с этим бороться? Сегодня тоже, атаковали, но в меньшем кол-ве. Я видел у тебя фикс, в банджикорде BotFilter. Я взял код из MinecraftDecoder, и вшил в бангу. Увы, не помогло =(

**Comment by Dimatert9** [comment]
Это не пофиксить на уровне банджи. Это грубо говоря обычный ддос на уровне приложения. (TCP Half Open connection). А эта ошибка тупо для прикрытия была, чтобы не в ту сторону копали. 
Метод называется Junk(x-junk - модификация которая ошибку вызывает для прикрытия). Как фиксить хз.

**Comment by Fejm** [comment]
English please :disappointed:

**Comment by JampireX** [comment]
attack fixed by adding SO_LINGER param to netty bootstraper. but it generate memory leak while longer attack.

**Comment by md-5** [comment]
If SO_LINGER fixes it, that indicates it is not a Bungee problem

**Comment by JampireX** [comment]
yes, but this problem CAN be fixed in bungee.

just drop any connection with no wait if error ocurred by decoder / framer

**Comment by md-5** [comment]
That's what happens already https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java#L162

**Comment by JampireX** [comment]
attack uses half-opened connections - sending handshake, but not accepting any answer from bungee. By default close() trying to send remaining data, but in this way bungee will not receive a confirmation and will wait for the timeout. SO_LINGER can close connection without any waiting not trying to send remaining data.

**Comment by md-5** [comment]
There's no way to change the behaviour of close without SO_LINGER

**Comment by JampireX** [comment]
but what prevents us from applying SO_LINGER ?
i see only one problem - kick packets, but i see you wait 250ms before close, this may be enough
https://github.com/SpigotMC/BungeeCord/blob/db266a8484d0ebebc5e40ca0803a91fa60427248/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L107

**Comment by md-5** [comment]
>it generate memory leak while longer attack.

**Comment by JampireX** [comment]
I'm working on this and trying to figure out the reason

**Comment by Janmm14** [comment]
Maybe this is a job for ddos protection?

**Comment by Dimatert9** [comment]
can you give link to good antiddos?
Hetzner antiddos, OVH Game AntiDdos doesnt help.

**Comment by Janmm14** [comment]
that was just a rough idea that ddos protections maybe have some heuristic against this kind of connection holding

**Comment by caoli5288** [comment]
I think SO_LINGER will lead performance degradation.

**Comment by evka89** [comment]
I know how to detect and fillter all of this attacks.

**Comment by evka89** [comment]
В принципе я уже поставил защиту от этой атаки, фильтрация в 12 поверок + провека на ботов игры. Layer7 протокол. Кому интересно можете написать в [лc в ВК](https://vk.com/nextera)
