### ISSUE TITLE
Bungee COrd dont run

### ISSUE THREAD

**Issue by PetereoCraft** [SpigotMC/BungeeCord#2252]
This is the complete code:

12:15:41 [INFO] Using standard Java JCE cipher.
12:15:41 [INFO] Using standard Java compressor.
12:15:41 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ef326db:1263
12:15:41 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
12:15:41 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
12:15:41 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
12:15:41 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
12:15:41 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
12:15:41 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
12:15:41 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
12:15:41 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
12:15:41 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
12:15:41 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
12:15:41 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
12:15:41 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
12:15:41 [SEVERE] Exception in thread "main"
12:15:41 [SEVERE] mapping values are not allowed here
 in 'reader', line 22, column 12:
          facti:
               ^

12:15:41 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:871)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:360)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:226)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:557)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:224)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:246)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:237)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:225)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:122)
12:15:41 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:505)
12:15:42 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:436)
12:15:42 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:63)
12:15:42 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:65)
12:15:42 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
12:15:42 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
12:15:42 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
...

**Comment by i9hdkill** [comment]
Your config.yml is broken. Regenerate it and make sure you don't do formatting mistakes.

**Comment by PetereoCraft** [comment]
How

P.C.

Em 13/09/2017 12:19, "John" <notifications@github.com> escreveu:

**Comment by Janmm14** [comment]
Use spigotmc.org forums for further support.
