### ISSUE TITLE
BungeeCord not starting

### ISSUE THREAD

**Issue by xZayos** [SpigotMC/BungeeCord#2253]
[2K
18:17:35 [INFO] Using mbed TLS based native cipher.
[m[2K
18:17:35 [INFO] Using zlib based native compressor.
[m[2K
18:17:35 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ef326db:1263
[m[2K
18:17:36 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
[m[2K
18:17:36 [INFO] Epoll is working, utilising it!
[m[2K
18:17:36 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[m[2K
18:17:36 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[m[2K
18:17:36 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[m[2K
18:17:36 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[m[2K
18:17:36 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[m[2K
18:17:36 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[m[2K
18:17:36 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
[m[2K
18:17:36 [INFO] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
[m[2K
18:17:36 [INFO] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
[m[2K
18:17:36 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
[m[2K
18:17:36 [INFO] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
[m[2K
18:17:36 [INFO] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:ef326db:1263 by SpigotMC
[m[2K
18:17:36 [SEVERE] Exception in thread "main" 
[m[2K
18:17:36 [SEVERE] java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
[m[2K
18:17:36 [SEVERE] at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:237)
[m[2K
18:17:36 [SEVERE] at net.md_5.bungee.conf.Configuration.load(Configuration.java:79)
[m[2K
18:17:36 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:265)
[m[2K
18:17:36 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
[m[2K
18:17:36 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[m

**Comment by md-5** [comment]
Fix your config or use spigotmc.org for support please
