### ISSUE TITLE
ComponentBuilder not working correctly

### ISSUE THREAD

**Issue by VooxoPlay** [SpigotMC/BungeeCord#2255]
When the Componentbuilder gets another Componentbuilder to use it for example a prefix that i need everytime that happens:

in older builds: Prefix | You got muted!
now: Prefix | You Prefix | got Prefix | muted! Prefix | 

I only updated my bungee server so it is not my code because it was working before

**Comment by md-5** [comment]
Please post code or at least versions.

cc @Mystiflow

**Comment by VooxoPlay** [comment]
`ComponentBuilder prefix = new ComponentBuilder(" System").color(ChatColor.GOLD).append(" ❘ ").color(ChatColor.DARK_GRAY);
player.sendMessage(new ComponentBuilder(prefix).append("Hello").color(ChatColor.GREEN).create()`

I must test all versions to find the good one because I dont have saved the old version in that all was fine

**Comment by Black-Hole** [comment]
ComponentBuilder was changed with this commit: https://github.com/SpigotMC/BungeeCord/commit/fd675022c0dd2d8597c2f32a89d81545d99cfa9d

So you could try a version before that.

**Comment by VooxoPlay** [comment]
I use waterfall and there it changed in #137 so I use #136
