### ISSUE TITLE
Last Stable Build {issue]

### ISSUE THREAD

**Issue by KiritoKun90** [SpigotMC/BungeeCord#2257]
I tried to update my BungeeCord with the last stable build, but when I run the server I get this error in the console now, and I can't join my server:

`06:59:34 [SEVERE] Sep 16, 2017 6:59:34 AM io.netty.util.internal.MacAddressUtil defaultMachineId
WARNING: Failed to find a usable hardware address from the network interfaces; using random bytes: 03:7d:bc:0c:de:a9:fd:23`

I read it was a common bug with older versions and that it wasn't a big issue, but actually I can't join my server so I dunno what to do. I've also tried by deleting all my BungeeCord server and reinstall it again from the beginning with the command wget... but nothing changed.

What's that?

**Comment by md-5** [comment]
I doubt this is causing you to not be able to join the server, but you can try adding -Dbungee.epoll=false just in case.
Either way it's not a Bungee bug. You can try netty/netty if the above does not fix it

**Comment by KiritoKun90** [comment]
Should I add this: Dbungee.epoll=false into the .config file?
And what you mean I can try netty/netty?

**Comment by md-5** [comment]
I have no idea what a .config file is, and I mean https://github.com/netty/netty/issues with far more information about your setup.
