### ISSUE TITLE
VarInt too big (Build #1265)

### ISSUE THREAD

**Issue by JustDJplease** [SpigotMC/BungeeCord#2258]
**Affects:** 1.12.2 clients on bungeecord build 1265.
**Decription:** When using the latest spigot build at this moment, build #1265 (18-sep-2017 10:23:14), players will be kicked seconds after connecting on a 1.12.2 client. The disconnect message will simply say 'Disconnected'. However, the bungeecord console will broadcast the following:

_Hastebin link for the error: https://hastebin.com/ixuzivizeq.vbs_
_Full error:_

`[Server] SEVERE -> UpstreamBridge - encountered exception
[Server] INFO java.lang.RuntimeException: VarInt too big
[Server] INFO at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:114)
[Server] INFO at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98)
[Server] INFO at net.md_5.bungee.entitymap.EntityMap.rewriteVarInt(EntityMap.java:100)
[Server] INFO at net.md_5.bungee.entitymap.EntityMap.rewrite(EntityMap.java:219)
[Server] INFO at net.md_5.bungee.entitymap.EntityMap.rewriteServerbound(EntityMap.java:76)
[Server] INFO at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteServerbound(EntityMap_1_12_1.java:161)
[Server] INFO at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:111)
[Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
[Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
[Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
[Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
[Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[Server] INFO at java.lang.Thread.run(Thread.java:745)
[Server] INFO disconnected with: RuntimeException : VarInt too big @ net.md_5.bungee.protocol.DefinedPacket:114
[Server] INFO -> UpstreamBridge has disconnected`

**Comment by gameplayerhd** [comment]
Same

**Comment by sebastianbinder** [comment]
I can second this

**Comment by myr1001** [comment]
same thing

**Comment by MylesIsCool** [comment]
This is down to a typo in EntityMap:

https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap_1_12_1.java#L46

It should be 0x0A instead of 0x0B.

**Comment by ninja-** [comment]
@MylesIsCool is it a typo regarding 1.12.1 also or we should make a new entitymap class for 1.12.2 with this change?

**Comment by MylesIsCool** [comment]
@ninja- Typo in regards to 1.12.1, there are no id changes in 1.12.2 :)
