### ISSUE TITLE
Server stuck on reconnect_yaml.jar loading

### ISSUE THREAD

**Issue by Kwright02** [SpigotMC/BungeeCord#2260]
the server gets stuck on reconnect_yaml.jar loading.
Pastes this error:
23.09 02:22:57 [Server] SEVERE com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure
23.09 02:22:57 [Server] INFO The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
23.09 02:22:57 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
23.09 02:22:57 [Server] SEVERE at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
23.09 02:22:57 [Server] SEVERE at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
23.09 02:22:57 [Server] SEVERE at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.SQLError.createCommunicationsException(SQLError.java:989)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.MysqlIO.<init>(MysqlIO.java:341)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2196)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2229)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2024)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
23.09 02:22:57 [Server] SEVERE at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)

**Comment by md-5** [comment]
That's not from Bungee, bungee does not have a Mysql connection.
You have some plugin with a mysql connection

**Comment by Kwright02** [comment]
It's still getting stuck on reconnect_yaml.jar even with no added plugins

**Comment by Janmm14** [comment]
full log?
try to delete the modules folder so bungee will redownload the modules

**Comment by Kwright02** [comment]
I don’t havw the log rn, but iv alr day tried that several times
