### ISSUE TITLE
KeepAlive issue. Again.

### ISSUE THREAD

**Issue by Dimatert9** [SpigotMC/BungeeCord#2261]
#2259
Sorry for making new issue.
I am use my BungeeCord fork **with latest changes**. I 100% sure that it cant make this.  Also i use PaperSpigot(git-Paper-1210 (MC: 1.12.2)) with lastest dev build of ProtocolSupport to allow versions before 1.12.2. 
I am 100% sure that it caused by BungeeCord/Original spigot and does not caused by plugins.
In PlayerConnection on 1.12.1 we have this code:

```    public void a(final PacketPlayInKeepAlive packetplayinkeepalive) {
        if (packetplayinkeepalive.a() == this.f) {
            final int i = (int)(this.d() - this.g);
            this.player.ping = (this.player.ping * 3 + i) / 4;
        }
    }
```

but in 1.12.2 we have

```
    public void a(PacketPlayInKeepAlive packetplayinkeepalive) {
        PlayerConnectionUtils.ensureMainThread(packetplayinkeepalive, this, this.player.x()); // CraftBukkit
        if (this.g && packetplayinkeepalive.a() == this.h) {
            int i = (int) (this.d() - this.f);

            this.player.ping = (this.player.ping * 3 + i) / 4;
            this.g = false;
        } else if (!this.player.getName().equals(this.minecraftServer.Q())) {
            this.disconnect(new ChatMessage("disconnect.timeout", new Object[0]));
        }

    }
```

I think this is our problem. And i think that it can be fixed in BungeeCord or in Spigot.

**Comment by NachtRaben** [comment]
In case you missed what he said in the last issue, unless you can recreate this issue with regular spigot as PaperSpigot isn't supported and not BungeeCords problem.

**Comment by Dimatert9** [comment]
This code from original spigot. I am not only one who get this error. Others have a original spigot.

**Comment by Dimatert9** [comment]
I really cant understand why you can not fix it right away and do not wait until about 10 people write about it.

**Comment by md-5** [comment]
I cannot reproduce the issue. Even if it was an issue the chances of it actually happening given frequencie on spigots are small

**Comment by Dimatert9** [comment]
How to reproduce: get big ping (like 150-200 ms)
Join to server. Server will send keep alive packet. Change server before client will answer to this packet.
....
profit

**Comment by md-5** [comment]
Nope, the  code now accounts for that.

**Comment by Dimatert9** [comment]
But with latest changes i continue get this error.

**Comment by md-5** [comment]
You are also not using a proper test setup

**Comment by Dimatert9** [comment]
1) BungeeCord server without plugins.
2) Server with authme and session enable. 
3) Other server with spigot 1.12.2

Join to server. Register. Leave, Join again and wait until authme will teleport you to other server. 
This issue will randomly appears.

**Comment by md-5** [comment]
Again, you can see the code will not allow the client to send the old keep alive to the server https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L117

**Comment by Dimatert9** [comment]
maybe you dont need send old keep alive? You skip it.

**Comment by md-5** [comment]
No, then the server will kick you for not sending the keep alive

**Comment by Dimatert9** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L129

does this packet  will became from new server, or from old server?

**Comment by md-5** [comment]
Fine, try it

**Comment by Dimatert9** [comment]
Thanks. I will check it at night. I dont want to restart bungeecord with 220 players online.
