### ISSUE TITLE
TimedOut

### ISSUE THREAD

**Issue by MinelandTeam** [SpigotMC/BungeeCord#2263]
![start](https://user-images.githubusercontent.com/30803993/30779208-fab099fc-a0f2-11e7-98ee-b9d1494c5703.jpg)
Sometimes players kick, when moving between servers. It appeared, exclusively after the transition to 1.12.2, servers and BungeeCord.

In sterile conditions, the error is difficult to repeat.
On a local server, I could repeat it, only when the test server loads about 100 bots. And with a specific way to reconnect to the server: https://pastebin.com/tzkDxWnE

As a result, we got the connection bedWars -> auth -> bedWars

In this strange way, you can make this error appear.
In actual conditions, on the server, it can randomly appear, with a simple transition to another server.

**Comment by MinelandTeam** [comment]
This is really a problem, in just an hour. More than 200 kicks were obtained with this cause.

**Comment by md-5** [comment]
No version of bungee or servers provided
