### ISSUE TITLE
 I have a problem and esque on my server there is an error and it closes, unfortunately I do not know what to do Help me please

### ISSUE THREAD

**Issue by Skormian** [SpigotMC/BungeeCord#2264]
16:04:41 [WARNING] Plugin performed restricted action, please inform them to use proper API methods: Illegal thread group accessjava.security.AccessControlException: Plugin violation: Illegal thread group accessat net.md_5.bungee.BungeeSecurityManager.checkRestricted(BungeeSecurityManager.java:39)at net.md_5.bungee.BungeeSecurityManager.checkAccess(BungeeSecurityManager.java:62)at java.lang.ThreadGroup.checkAccess(ThreadGroup.java:315)at java.lang.Thread.init(Thread.java:394)at java.lang.Thread.init(Thread.java:349)at java.lang.Thread.(Thread.java:678)at java.util.concurrent.Executors$DefaultThreadFactory.newThread(Executors.java:613)at java.util.concurrent.ThreadPoolExecutor$Worker.(ThreadPoolExecutor.java:619)at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:932)at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1378)at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:19)at skinsrestorer.bungee.SkinApplier.applySkin(SkinApplier.java:69)at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:140)at skinsrestorer.bungee.SkinApplier$1.run(SkinApplier.java:24)at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)at java.util.concurrent.FutureTask.run(FutureTask.java:266)at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)at java.lang.Thread.run(Thread.java:748)

**Comment by i9hdkill** [comment]
Update/Remove Skinsrestorer.
Not a bug, if you need help, visit the spigotmc forums.
