### ISSUE TITLE
Netty Issues - relogin then keep disconnect

### ISSUE THREAD

**Issue by samueleycw** [SpigotMC/BungeeCord#2265]
As the pastbin show that sometime the player will connect to both server at the same time, is it a normal?

such as:
01:29:34 [INFO] [Toyoten] <-> ServerConnector [Lobby] has connected
01:29:47 [INFO] [Toyoten] <-> ServerConnector [Ser1] has connected

17:38:13 [INFO] [NiNaiMiO] <-> ServerConnector [Lobby] has connected
17:39:46 [INFO] [NiNaiMiO] <-> ServerConnector [Ser1] has connected

https://pastebin.com/cRJb2aac

BungeeCord server VPS's OS is reinstalled. No issue for VPS confirmed.
Backend server's OS is reinstalled too. No issue confirmed.

Bungeecord Build #.1271

**Comment by md-5** [comment]
Yes, this is normal

21:31:26 [INFO] [NiNaiMiO] <-> ServerConnector [Lobby] has connected
21:32:33 [INFO] [NiNaiMiO] <-> ServerConnector [Ser1] has connected
21:32:35 [INFO] [NiNaiMiO] <-> DownstreamBridge <-> [Lobby] has disconnected
21:33:04 [INFO] [NiNaiMiO] <-> DownstreamBridge <-> [Ser1] has disconnected

You can see bungee connects them to both servers, drops the first when they switch.
The last line is then them disconnecting from that server.
