### ISSUE TITLE
4.1.16.Final released with bug fix 

### ISSUE THREAD

**Issue by samueleycw** [SpigotMC/BungeeCord#2266]
it should fixed the 'rollback' issue and improve  Netty stability .

#netty http://4.1.16.Final  and http://4.0.52.Final  released today with bugfixes and performance improvements http://netty.io/news/2017/09/25/4-0-52-Final-4-1-16-Final.html …
9:19 PM - 25 Sep 2017 

Rerefer: http://netty.io/news/2017/09/25/4-0-52-Final-4-1-16-Final.html

https://github.com/netty/netty/issues/7219

**Comment by Janmm14** [comment]
i don't see how netty 7219 is related

**Comment by md-5** [comment]
It’s not clear what you’re hoping to have fixed by updating netty.
I review all the netty changelogs and  there’s nothing there that really impacts bungee
