### ISSUE TITLE
I need help now please

### ISSUE THREAD

**Issue by Skormian** [SpigotMC/BungeeCord#2267]
Well a long time ago, more than 1 week ago I have this problem very, very annoying.
Which? You ask yourself.
What happens is that every number of players in my Network stops the bridge. I need help is very urgent I can not find the exact code because it happens, when it occurs
Disconnected.
Ram: 2gb
Error: UpstreamBridge has Disconnected
Sorry for my bad english. I speak spanish 😃 
Ip: UltraKing.mcserv.pro

**Comment by NachtRaben** [comment]
This sounds more like your internet cutting out more than anything.

**Comment by Skormian** [comment]
No, since what stops is the Bungee server and no other server stops and always happens and I'm already bothering a lot of that mistake or whatever
