### ISSUE TITLE
Exception Connecting:NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1

### ISSUE THREAD

**Issue by MachoPiggies** [SpigotMC/BungeeCord#2269]
I get the error in the title when I try to join my bungeecord network. I have restarted all the servers many times but nothing works. This is my console output.

`03.10 19:10:00 [Multicraft] Received start command
03.10 19:10:00 [Multicraft] Loading server properties
03.10 19:10:00 [Multicraft] Starting server!
03.10 19:10:00 [Multicraft] Loaded config for "BungeeCord 1.12.1 Build #1251"
03.10 19:10:00 [Multicraft] Updating eula.txt file
03.10 19:10:00 [Server] INFO Updating BungeeCord Config.

03.10 19:10:10 [Server] INFO Using mbed TLS based native cipher.
03.10 19:10:10 [Server] INFO Using zlib based native compressor.
03.10 19:10:10 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:017f3a2:1251
03.10 19:10:11 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
03.10 19:10:11 [Server] INFO Epoll is working, utilising it!
03.10 19:10:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
03.10 19:10:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
03.10 19:10:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
03.10 19:10:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
03.10 19:10:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
03.10 19:10:11 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
03.10 19:10:11 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] WARNING Forced host server pvp is not defined
03.10 19:10:11 [Server] INFO Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] INFO Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:017f3a2:1251 by SpigotMC
03.10 19:10:11 [Server] Startup Listening on /178.32.247.192:25565
03.10 19:10:57 [Server] INFO (0): 
03.10 19:10:57 [Server] INFO (0): 
03.10 19:10:57 [Server] INFO (0): 
03.10 19:11:28 [Server] INFO disconnected with: Exception Connecting:NativeIoException : syscall:read(..) failed: Connection reset by peer @ io.netty.channel.unix.FileDescriptor:-1
03.10 19:11:28 [Server] INFO -> UpstreamBridge has disconnected`

**Comment by md-5** [comment]
Not a bungee issue, the server you’re connecting to (or client) is closing the connection

**Comment by MachoPiggies** [comment]
I'm now getting this, all my servers are fine.
Error sending command: Authentication failed (auth: Empty response)
