### ISSUE TITLE
Second line is white

### ISSUE THREAD

**Issue by LielAmarScoRpyoN** [SpigotMC/BungeeCord#2272]
Hey, I made a /msg command, but if the message is very long and it goes to another line, the second line will be WHITE.

Code:
p.sendMessage(new TextComponent(ChatColor.RED + sender.getName() + ChatColor.GRAY + " > " + ChatColor.GREEN + "me" + ChatColor.GRAY + ": " + msgBuilder.toString()));

Example: https://i.imgur.com/3h9Oetr.png?1

**Comment by kamcio96** [comment]
Wiki: https://www.spigotmc.org/wiki/the-chat-component-api/#common-pitfalls
