### ISSUE TITLE
Unexpected kick w/ Scoreboard Teams

### ISSUE THREAD

**Issue by Rhonim** [SpigotMC/BungeeCord#2273]
Currently whenever I attempt to connect to a server for the first time on our network I get kicked with the error below in console.

I've tried and ensured the following:

- Team is checked for before being registered, thus only registered once
- Attempted to delete the scoreboard.dat on server involved
- Renamed the Team to something unique that no other server has on the network

Error:
https://pastebin.com/7tUKq5K1

In-Game display once kicked:
http://prntscr.com/gvc5ik

**Comment by md-5** [comment]
Cannot reproduce.
What is creating the team TestPref and what versions are you running

**Comment by Rhonim** [comment]
Running BungeeCord version 1.12-SNAPSHOT:8d49424:1273, the 1.8.8 spigot servers are creating the teams. Using the following code:

```
Team team = scoreboard.getTeam(this.teamName);
        if (team == null) {
            team = scoreboard.registerNewTeam(this.teamName);
            team.setPrefix(this.getCompletePrefix(true));
            team.setCanSeeFriendlyInvisibles(false);
        } else if (!team.getPrefix().equals(this.getCompletePrefix(true)) || team.canSeeFriendlyInvisibles()) {
            team.setPrefix(this.getCompletePrefix(true));
            team.setCanSeeFriendlyInvisibles(false);
        }

```

**Comment by Rhonim** [comment]
Also, may be worth mentioning we do run ViaVersion, however I am able to reproduce it after removing ViaVersion

**Comment by ninja-** [comment]
@Rhonim are you 100% sure that it reproduces without ViaVersion? also can we see the plugin list and spigot version?

**Comment by Rhonim** [comment]
Yes, it does happen when ViaVersion is removed still. 
Spigot it just the default 1.8.8
Plugin List:
http://prntscr.com/gvo7zq

**Comment by Rhonim** [comment]
Seems to only be happening when I'm teleporting the player using the PlayerJoinEvent.

**Comment by ninja-** [comment]
weird, but don't teleport the player to another world inside PlayerJoinEvent.
That's a bad idea.

**Comment by Rhonim** [comment]
Mind expanding upon why? For curiosity's sake. And I'm assuming a runTaskLater would be fine then?

**Comment by Mystiflow** [comment]
Perhaps [PlayerSpawnLocationEvent](https://hub.spigotmc.org/javadocs/spigot/org/spigotmc/event/player/PlayerSpawnLocationEvent.html) could be something of interest for you.

**Comment by ninja-** [comment]
@Rhonim basically calling .teleport there breaks the order in which initial packets should be delivered; can result in ghost players for example

**Comment by Rhonim** [comment]
@ninja- Awesome, thank you for explaining that.

**Comment by Rhonim** [comment]
That said, upon changing things I'm still running into the issue. I'll be looking into it more when I can.

**Comment by md-5** [comment]
We can’t patch 1.8 bugs if its server side, 1.12.2 is the only aupported spigot version

**Comment by Rhonim** [comment]
Not sure I'd consider it server side when the issue isn't happening without bungee. Regardless, for now I've delayed when the scoreboard will show for players as a hacky fix.
