### ISSUE TITLE
Bungeecord Issue: Getting kicked (disconnected) when i type a very long bungeecord command

### ISSUE THREAD

**Issue by Luddiluddien** [SpigotMC/BungeeCord#2274]
Im writing: sync player Hazlow whitelist message set &8&l[&5&lIGNITE&b&lMC&8&l]&bThe server is in its development phase.&bNo join access! Please try again later. In a command block and i get disconnected. Why is this and how to fix.

**Comment by md-5** [comment]
Disconnected with what message?
What versions?
