### ISSUE TITLE
Bungeecord server not starting...

### ISSUE THREAD

**Issue by Sn0wSquad** [SpigotMC/BungeeCord#2275]
Hello! Today when I was editing a server name for one of my bungeecord servers, I got this message on the bungeecord startup. 
https://pastebin.com/iV2NNvyw
If you can help that would be great.
Thanks 👍 
-Sno

**Comment by ApocalypsjeNL** [comment]
Maybe also send your config.yml?

**Comment by Janmm14** [comment]
The issue tracker is no place for config support. Use the appriate subforum on spigotmc.org.
