### ISSUE TITLE
"Server is online mode!" But I am online.

### ISSUE THREAD

**Issue by Tokelauan** [SpigotMC/BungeeCord#2277]
Full error (when trying to connect to the server):
Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:277

- ip forward in bungee's config.yml is set to true.
- online mode in bungee's config.yml is set to true.
- spigot.yml's bungeecord setting is set to true.
- server.propterties' online-mode is set to false.
- My client is not in offline mode. Perhaps an OptiFine issue..?

I'm only attempting to run one server with bungee. The server appears to be working perfectly fine when looking in the console, the only problem: I can't connect. I've followed all there is on the tutorial pages on the spigot website, done as much searching as I could for this issue, yet I still haven't found what I'm looking for. This is my last resort.

**Comment by Black-Hole** [comment]
For help configuring your server please use the Spigot forums.

**Comment by Tokelauan** [comment]
Moved to the Spigot forums.
