### ISSUE TITLE
BungeeCord "If You Wish to Use IP Forwarding..." Error

### ISSUE THREAD

**Issue by ItsNotMineshafter** [SpigotMC/BungeeCord#2278]
I've basically tried everything, enabled BungeeCord in my spigot.yml and ip_forward to true in the BungeeCord thing.

My BungeeCord Config: https://pastebin.com/d1Af00E4
spigot.yml for my main server: https://pastebin.com/Z1u8upFr
spigot.yml for my bungeecord separate server: https://pastebin.com/QyjHdVV0

**Comment by kjl13** [comment]
In your bungeecord config, your host is 0.0.0.0:25577, be sure that is the correct IP that you want the proxy to be hosted on. I would recommend that the host's port is 25565 so when connecting to your network you don't have to use a port.

**Comment by md-5** [comment]
Use the forums for support
