### ISSUE TITLE
I had this Problem and generated: WARNING: A task raised an exception.

### ISSUE THREAD

**Issue by RedBowNetwork** [SpigotMC/BungeeCord#2292]
SEVERE Nov 14, 2017 4:23:56 PM io.netty.util.concurrent.SingleThreadEventExecutor runAllTasks
14.11 16:23:56 [Server] INFO WARNING: A task raised an exception.
14.11 16:23:56 [Server] INFO java.util.NoSuchElementException: compress
14.11 16:23:56 [Server] INFO at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:966)
14.11 16:23:56 [Server] INFO at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:305)
14.11 16:23:56 [Server] INFO at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:88)
14.11 16:23:56 [Server] INFO at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:629)
14.11 16:23:56 [Server] INFO at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:494)
14.11 16:23:56 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:358)
14.11 16:23:56 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:259)
14.11 16:23:56 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112)
14.11 16:23:56 [Server] INFO at java.lang.Thread.run(Thread.java:748)

I don't know what is this but i can't entry to my network

Any idea what is causing this or why this is happening?

My BungeeCord version git:BungeeCord-Bootstrap:1.10-SNAPSHOT:1250088:1167 by md_5

**Comment by md-5** [comment]
Your bungeecord is > 50 versions outdated
