### ISSUE TITLE
No main manifest attribute.

### ISSUE THREAD

**Issue by HarleyCC** [SpigotMC/BungeeCord#2293]
I was doing a YT video tutorial and when i was creating a Lobby folder (server) it says 'No main manifest attribute' i followed all steps and i dunno what happened.

The video go to 7:15 mins: https://www.youtube.com/watch?v=LhLkDSgkE68

Your support is highly appreciated.

**Comment by md-5** [comment]
You haven't said what you've done or provided any tangible information such as logs or commands entered.
Furthermore this is a bug tracker, use the forums for support.
