### ISSUE TITLE
java.lang.IllegalArgumentException: Unknown meta type

### ISSUE THREAD

**Issue by Yorkforce** [SpigotMC/BungeeCord#2294]
We just started having this occur on one of our modpack servers, it's a brand new world and only seems to occur in a certain area of the world. (eg: we were moving from default world spawn to 0,0 coordinates.

Were at a complete loss tbh
Error from bungeecord log:
https://pastebin.com/JcnpHdUk

**Comment by md-5** [comment]
http://wiki.vg/Entity_metadata

There is no metadata with type 14 in vanilla.
Without knowing what the mod is and what data it is adding there is nothing we can do.
Even if we did, really the mod should be using plugin messages to handle custom data rather than changing the vanilla protocol.

**Comment by Yorkforce** [comment]
Yeah you're not kidding with the lack of messages, the actual forge log is this:

[04:27:02] [Netty Epoll Server IO #2/DEBUG] [FML]: Muted NetworkDispatcher exception
io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer
	at io.netty.channel.unix.FileDescriptor.readAddress(..)(Unknown Source) ~[FileDescriptor.class:?]

We also got a Unknown meta type 16 error too.

Do you know if this is a mob?

**Comment by md-5** [comment]
No, you need to find the issue - we can only investigate issues that occur with vanilla, craftbukkit, or spigot

**Comment by MrCrayfish** [comment]
I know that this was closed a while ago but I recently ran into the issue. The problem lies with adding custom DataSerializers for Entities. I now have reverted to using plain primitives instead of a custom serializer. I disagree though that we are changing Vanilla's protocol because these are my own custom entities with values that I need synced to the client.

**Comment by md-5** [comment]
>disagree though that we are changing Vanilla's protocol 

>custom DataSerializers

How is that NOT changing the protocol?

**Comment by MrCrayfish** [comment]
Okay, I take that back :/
