### ISSUE TITLE
Allow sending plugin messages to empty servers [Feature]

### ISSUE THREAD

**Issue by hurrgurl** [SpigotMC/BungeeCord#2298]
it would be nice if it was possible to send plugin messages from/to bungee and servers that have 0 players connected

**Comment by md-5** [comment]
Plugin messages have to be sent via players, you should use a message queue if you require this feature.

**Comment by hurrgurl** [comment]
Would it be difficult to add a feature where an empty server can receive a message without a queue? I have a problem and a solution that would work much better if this was possible.

**Comment by ApocalypsjeNL** [comment]
Use sockets

**Comment by md-5** [comment]
No, that would be horribly inefficient - bungee would have to create a dummy connection to the server each time a message needed to be sent (and would not be able to get a response unless a dummy player was always connected).

A messagequeue such as redis is the proper solution to this problem and can be done in half a dozen lines of code.

**Comment by hurrgurl** [comment]
Thank you so much md5, redis sounds way better, just what I needed!
