### ISSUE TITLE
Server Thermos

### ISSUE THREAD

**Issue by ElPanchoYT** [SpigotMC/BungeeCord#2302]
When I try to connect with a compass to my Thermos or KCauldron server it works a few minutes but then the error of Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel $ AnnotatedConnectException
Could you give me a solution or what should I do?

**Comment by i9hdkill** [comment]
1.7 is not supported.

**Comment by ElPanchoYT** [comment]
Yes, but there are servers that do allow that union because I do not fight if they use the same as me.

**Comment by Lmmb74** [comment]
@ElPanchoYT Use Travertine or HexaCord forks

**Comment by ElPanchoYT** [comment]
Good I'm looking for a programmer to create a bungeecord that I give my server mods and that is compatible 1.7.10 to 1.9

I'm using Travertine or HexaCord but it bugs me in bungeecord when I try to connect with a compass to my Thermos or KCauldron server it works a few minutes but then the error of Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel $ AnnotatedConnectException Could you give me a solution or what should I do? And in the console of my mods server I get this error "Migrated 3 channels to the new selector"




________________________________
De: Lautaro Mancini <notifications@github.com>
Enviado: jueves, 21 de diciembre de 2017 09:35 a. m.
Para: SpigotMC/BungeeCord
CC: ElPanchoYT; Mention
Asunto: Re: [SpigotMC/BungeeCord] Server Thermos (#2302)


@ElPanchoYT<https://github.com/elpanchoyt> Use Travertine or HexaCord forks

**Comment by i9hdkill** [comment]
This cannot be discussed here. This is the issuetracker for the latest BungeeCord build only. Use the spigotmc hiring a dev forum if you need a dev.
