### ISSUE TITLE
Doesnt add all servers

### ISSUE THREAD

**Issue by Hundeklemmen** [SpigotMC/BungeeCord#2306]
So I'm trying to add and remove servers dynamically and it only add some of its and I have tried and tried to debug and I says it adds the server but when I then look it says it not exist :/
Main class: https://hastebin.com/mamopufejo.java

**Comment by md-5** [comment]
If you are attempting to report a bug with an API method you need to produce a minimal example that we can test with which shows the issue (i.e. remove everything except the addServer calls).
