### ISSUE TITLE
io.netty.handler.codec.DecoderException: Error decoding packet id

### ISSUE THREAD

**Issue by jonny42g** [SpigotMC/BungeeCord#2307]
Hello i have a bungeecord network, when i am in the hub/lobby server and try to goto my sponge server i get this error

20.12 14:21:05 [Server] INFO io.netty.handler.codec.DecoderException: Error decoding packet id 18 with contents +-------------------------------------------------+
20.12 14:21:05 [Server] INFO | 0 1 2 3 4 5 6 7 8 9 a b c d e f |
20.12 14:21:05 [Server] INFO +--------+-------------------------------------------------+----------------+
20.12 14:21:05 [Server] INFO |00000000| 18 08 52 45 47 49 53 54 45 52 46 4d 4c 7c 48 53 |..REGISTERFML|HS|
20.12 14:21:05 [Server] INFO |00000010| 00 46 4d 4c 00 46 4d 4c 7c 4d 50 00 46 4d 4c 00 |.FML.FML|MP.FML.|
20.12 14:21:05 [Server] INFO |00000020| 46 4f 52 47 45 00 53 70 6f 6e 67 65 |FORGE.Sponge |
20.12 14:21:05 [Server] INFO +--------+-------------------------------------------------+----------------+
20.12 14:21:05 [Server] INFO at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68)
20.12 14:21:05 [Server] INFO at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
20.12 14:21:05 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
20.12 14:21:05 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
20.12 14:21:05 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
20.12 14:21:05 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
20.12 14:21:05 [Server] INFO at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
20.12 14:21:05 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
20.12 14:21:05 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
20.12 14:21:05 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
20.12 14:21:05 [Server] INFO at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:967)
20.12 14:21:05 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:386)
20.12 14:21:05 [Server] INFO at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:302)
20.12 14:21:05 [Server] INFO at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:877)
20.12 14:21:05 [Server] INFO at java.lang.Thread.run(Thread.java:745)

**Comment by Janmm14** [comment]
You do not use bungeecord.
