### ISSUE TITLE
ServerSwitchEvent: Include methods to get fcrom and to server

### ISSUE THREAD

**Issue by AaronMcHale** [SpigotMC/BungeeCord#2309]
In the ServerSwitchEvent it would be useful to have methods to get the Server Objects for the server the player is leave and the server the player is joining, for example getFromServer() and getToServer().

The documentation is also unclear as to when the ServerSwitchEvent is raised if ProxiedPlayer.getServer() returns the "From" or "To" Server, my assumption is it is the "From" Server but it would be nice to have this documented somewhere to avoid any confusion.

**Comment by Janmm14** [comment]
@AaronMcHale The ServerSwitchEvent is called after the switching was done and the new server can be seen by proxiedPlayer.getServer()

The api documentation clearly states that: https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/event/ServerSwitchEvent.java#L10

**Comment by AaronMcHale** [comment]
@Janmm14 thanks I somehow missed that comment at the top of the ServerSwitchEvent class.  I think it would still be easier to have the "From" and "To" methods, if only just the "From" method that way it avoids having to hook into multiple methods and track the Player's progress through them.

**Comment by md-5** [comment]
Handled in #2379
