### ISSUE TITLE
Cannot Connect to Hub

### ISSUE THREAD

**Issue by AirCraze** [SpigotMC/BungeeCord#2312]
https://pastebin.com/KR0AHiW6

**Comment by Janmm14** [comment]
Server is trying to send bossbar to a player using an older minecraft version which does not support bossbar packets, but used entities instead

**Comment by AirCraze** [comment]
which plugin may i ask?

**Comment by md-5** [comment]
Who knows, there are > 30,000 plugins
Remove them from your server till you can connect

**Comment by AirCraze** [comment]
i only have 10

**Comment by AirCraze** [comment]
got discord? so i can contact you faster?

**Comment by md-5** [comment]
So, it's one of your ten then.
I'm sure you can figure it out by process of elimination

**Comment by AirCraze** [comment]
in bungeecord/server

**Comment by AirCraze** [comment]
also how do i set perms
without restarting the bungeecord

**Comment by Mystiflow** [comment]
You need to find a plugin to do that for you .
