### ISSUE TITLE
warning Event ServerConnectEvent

### ISSUE THREAD

**Issue by josecuervo2016** [SpigotMC/BungeeCord#2315]
new alert  how fix this?

[WARNING] Event ServerConnectEvent(player=BleedFairness, target=BungeeServerInfo(name=PreLobby, address=localhost/127.0.0.1:25500, restricted=false), cancelled=false) took 258,213,662ns to process!

**Comment by Janmm14** [comment]
plugin issue - your plugins (or some/one of them) need too much time to process the ServerConnectEvent
