### ISSUE TITLE
Bad packet ID and  Packet errors. (He kicks all players from the game.)

### ISSUE THREAD

**Issue by craftrise** [SpigotMC/BungeeCord#2317]
BungeeCord version: #1288 - build (Latest)
Spigot version: 1.8.8

Spigot plugins: Custom + Viaversion (Latest)
Bungeecord plugins: Custom (i'm not using any packet methods)

Explanation:
Sometimes, he throws all the players out of the game. (We have +2500 online)

Errors:

 # 1. NORMAL ERROR - Netty decoder exception (1): 
      HASTEBIN: https://hastebin.com/zodikoqeki.lua | PASTEBIN: https://pastebin.com/Lz81wiWY

 # 2. NORMAL ERROR - Netty decoder exception (2): 
      HASTEBIN: https://hastebin.com/getecememe.lua | PASTEBIN: https://pastebin.com/icHT7PNt

# 3. Error kicking all players in the server (Critical):
      HASTEBIN: https://hastebin.com/izilecepun.hs | PASTEBIN: https://pastebin.com/8X0VncW0

**Comment by Janmm14** [comment]
hastebin seems down for me atm :/

**Comment by craftrise** [comment]
@Janmm14  updated links for pastebin 👍

**Comment by Black-Hole** [comment]
Some plugin is sending invalid PlayerListItem packets. Those are used to build the tab list for the client.

**Comment by craftrise** [comment]
@Black-Hole , i'm not using any packet methods for Bukkit or BungeeCord.

**Comment by md-5** [comment]
But your hacky plugins (via version etc are).
