### ISSUE TITLE
/server <TAB> error

### ISSUE THREAD

**Issue by xtechgamer735** [SpigotMC/BungeeCord#2318]
Hello All!

For some strange reason, when any player types /server and then presses TAB, they get disconnected and a stack trace like so appears:

https://gist.github.com/xtechgamer735/24e937ca7b1997516474a7e7a738b0b6

Don't suppose anyone knows how I could fix it?

**Comment by ninja-** [comment]
Please try emptying the modules/ folder

**Comment by xtechgamer735** [comment]
Thanks for your reply! No luck sadly :(

**Comment by ninja-** [comment]
duplicate of https://github.com/SpigotMC/BungeeCord/issues/2233
looks like issue in one of your plugins - my guess would be that you accidently shaded bungeecord to your plugin jar ?

**Comment by xtechgamer735** [comment]
Thanks, I will give this a try and check though the plugins first. AFAIK we haven't but anything is possible

**Comment by md-5** [comment]
Try removing plugins and add them back slowly.
