### ISSUE TITLE
FishingHook has wrong hooked entity id

### ISSUE THREAD

**Issue by Fejm** [SpigotMC/BungeeCord#2323]
Referring to http://wiki.vg/Entity_metadata#FishingHook hooked entity id has index 6 but EntityMap is rewritting only index 7.

https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap_1_12_1.java#L152

This causes client desync.

**Comment by md-5** [comment]
What about other versions?

**Comment by Fejm** [comment]
1_12_1 was only an example, 1_12, 1_11 and 1_10 are also affected by this issue. Not sure about < 1.10.

**Comment by md-5** [comment]
I've added rewrites for this, but note due to the way that rewrites work, it is completely possible this will create more issues than it solves.

**Comment by Fejm** [comment]
Now it works as intended. Thanks!
