### ISSUE TITLE
Error while moving from server to server

### ISSUE THREAD

**Issue by maxim19116** [SpigotMC/BungeeCord#2324]
Hello, I'm using BungeeCord latest version (1292), and when I move from server to server I get an error, list of servers:

- Login-1
- Hub-1
- Creative

And when I'm with Hub go on Creative this error occurs, I use on every ViaVersion server

How to remove this error, because of it I can not get to the server, in the spigot console there are no errors, without Bungee comes in normally.

https://hastebin.com/loyibokixo.lua

**Comment by md-5** [comment]
What happens if you use an older version (https://ci.md-5.net/job/BungeeCord/1291/)

**Comment by md-5** [comment]
Also ViaVersion is not a supported plugin anyway, so closing unless verified that 1292 is the issue
