### ISSUE TITLE
Commands ignored after some time

### ISSUE THREAD

**Issue by renepreuss** [SpigotMC/BungeeCord#2325]
We have had several versions of BungeeCord for some time now and we have the problem that several commands do not work after some time or sporadically.

If you enter the `/test` command, it does not work. But if you use `/plugin:test` then this command goes. (Doesn't always work)

If you add the commands (from Essentials & Custom Plugins) to the `disabled_commands` configuration section in the `config.yml` file, it works for some reason. Or delete all BungeeCord plugins and download them automaticly again. We have not yet been able to find out any further details.

How can this anomaly be fixed?

Greetings,
René

**Comment by md-5** [comment]
Very skeptical this has anything to do with BungeeCord, certainly not in the default configuration.
You mention plugins, so I would suggest to look on that front first, and reproduce without plugins.
