### ISSUE TITLE
2 Error with las version of bungee cord

### ISSUE THREAD

**Issue by JavituRec** [SpigotMC/BungeeCord#2326]
Hello,

I have 2 bungee cords (1 its premiums and a other is no premium) with redis and redissbungee.

In the premium bungee cord someone staff are kicked of the backend to the hub with this message:

_The server you were previously on went down, you have been connected to a fallback server_

But the backend is online and have users online.

I have found this error:

https://hastebin.com/elubunozum.lua

and other error that has nothing to do with the above:

https://hastebin.com/tuxulerogu.lua

Sincerely.

**Comment by md-5** [comment]
1) is bad plugin on your server, probably something like viaversion
2) is normal

**Comment by JavituRec** [comment]
Its plugin bungee or spigot?

**Comment by md-5** [comment]
Spigot probably
