### ISSUE TITLE
HAProxy Bug

### ISSUE THREAD

**Issue by OwnageTechGeek** [SpigotMC/BungeeCord#2329]
The HAProxy functionality in BungeeCord appears to have a bug.  Whenever it is configured (enabled proxy_protocol in config.yml) and HAProxy is configured with a barebones config (https://pastebin.com/mb3cMsAi).  It has been tested within the same host, between lan, and within virtual networks.  

The bug is reproducable by configuring HAProxy and BungeeCord as stated above.  When connecting through HAProxy, BungeeCord will take approximately 6 seconds to proceed to the log in phase.  It has been tested with the newest BungeeCord, and the latest Spigot (obviously disconnecting) with the same result.  

The relevant BungeeCord log is here:

https://pastebin.com/svnWUvXB

**Comment by OwnageTechGeek** [comment]
The relevant BungeeCord log is here:

https://pastebin.com/svnWUvXB

**Comment by md-5** [comment]
Are you saying with the same config, but without proxy_protocol and  check-send-proxy send-proxy-v2, there is no delay?

Because if so, I think this is not a bug.

**Comment by OwnageTechGeek** [comment]
No, regardless of those settings, it takes to the accuracy to several milliseconds EXACTLY 6 seconds to initiate connection with BungeeCord.

**Comment by md-5** [comment]
This sounds like an issue with your HAProxy configuration.
I know when I set up an haproxy install for someone, the tcp inspect delay had to be changed otherwise this would occur.

**Comment by md-5** [comment]
Cannot reproduce either, using haproxy 1.8.3
```defaults
        retries 3
        mode tcp
        timeout connect 200ms
        timeout client 2000ms
        timeout server 2000ms
 
 
listen minecraft
        bind :25565
        mode tcp
        balance leastconn
        option log-health-checks
        option srvtcpka
        default-server inter 10s fall 1 rise 10
        option tcp-check
        server minecraft1 127.0.0.1:25577 check-send-proxy send-proxy-v2
```
0 delay connecting, not a bungee bug

**Comment by OwnageTechGeek** [comment]
It is now connecting as it appears, but I have a new error....


[00:04:15 ERROR]: [/127.0.0.1:53000] <-> InitialHandler - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!

**Comment by OwnageTechGeek** [comment]
Even with the tcp-inspect error it is still occuring.  Could you please give me a rough idea of the environment you are using?

I'm using:

ubuntu 16.04
bungeecord latest
haproxy 1.8.3

**Comment by md-5** [comment]
Plugins often cause the empty packet error you mentioned.
I was using ubuntu 17.10 with haproxy 1.8.3 compiled from source.

**Comment by OwnageTechGeek** [comment]
I finished testing.  Bug/issue is related to Ubuntu 16.04.  Works fine in 17.10.

**Comment by dahendriik** [comment]
Hey, @md-5 do you also think it is possible to use haproxy for failover? If one Bungee crashes, the players will get pushed to another one?

**Comment by Janmm14** [comment]
@dahendriik you'd need a separate storage for some connection-specific data like last server, handshake info, skin data and a custom plugin that does dive deep into bungee implementation (or custom bungee), but in the end yes, its possible.

**Comment by md-5** [comment]
@dahendriik no, it makes no sense.
