### ISSUE TITLE
Exception connecting:runtimeexception : Server is online mode! @net.md_5.bungee.serverConnector:277

### ISSUE THREAD

**Issue by GenGummy** [SpigotMC/BungeeCord#2331]
When i join my server i get the error Exception connecting:runtimeexception : Server is online mode! @net.md_5.bungee.serverConnector:277. i am only starting lobby and bungee rn. In looby sever.prperties, online mode is false. Please help me.

**Comment by Janmm14** [comment]
Try restart server. Make sure you edited the correct server.properties
