### ISSUE TITLE
Not a report spigotmc website error

### ISSUE THREAD

**Issue by CrazVerse** [SpigotMC/BungeeCord#2332]
I know this is not a report, but I just wanted to ask, I was waiting for about 2 days, to get a email from spigotmc, I cannot upload any resources, because there is no button for it, it's appearing for my friend but not for me, please fix it.My spigotmc account: CrazVerse

**Comment by md-5** [comment]
Alt of banned user.
Contact support@spigotmc.org to appeal your ban
