### ISSUE TITLE
[Question] UUID fowarding protocol?

### ISSUE THREAD

**Issue by bdsomer** [SpigotMC/BungeeCord#2334]
I'm not extremely experienced in Java and don't want to sift through the codebase to find the UUID forwarding protocol that Spigot uses. Where is this protocol documented? If it's not, how does the protocol work?

The purpose of finding the documentation for this protocol is to implement it into a proxy similar to BungeeCord, but written in Node.js.

Thanks in advance!

**Comment by ApocalypsjeNL** [comment]
The Java Edition protocol is documented here http://wiki.vg/Protocol

**Comment by bdsomer** [comment]
@ApocalypsjeNL Yes, you are correct. But is there a way to convince an offline Vanilla server to believe that someone has a UUID that they really don’t?

I think that BungeeCord/Spigot have a small protocol tweak that allows UUIDs to be forwarded so that plugins can utilize real UUIDs, not just offline-mode MD5 hashes.

I may be incorrect.

**Comment by ApocalypsjeNL** [comment]
Oh yes, that's correct. When the proxy has ip forwarding enabled it sents the real ip of the user, and the uuid as shown in this line of code https://github.com/SpigotMC/BungeeCord/blob/8d494242265790df1dc6d92121d1a37b726ac405/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L93

**Comment by Janmm14** [comment]
@ApocalypsjeNL
Yes and other mc servers possibly ignore the stuff after the first \00.
After your line in the file it will also add the skin data at the end, if present.

**Comment by i9hdkill** [comment]
Next time please open a thread in our forums:
https://www.spigotmc.org/forums/#bungeecord.33
We would like to keep the issue section for actual bugs only.
Thank you

**Comment by bdsomer** [comment]
@ApocalypsjeNL @Janmm14 I can't find any documentation for `DefinedPacket#getHost`. Could I get an example of a `newHost` string?

I was thinking something like `"127.0.0.1:25565" + "\00" + "127.0.0.1:25566" + "\00" + "PLAYER_UUID_HERE"`, but I'm sure I'm completely wrong.

As well, I would like to make sure that the [`set_protocol`](https://prismarinejs.github.io/minecraft-data/?v=1.8&d=protocol#toServer_set_protocol) packet's `serverHost` property is where this `newHost` string is going. Am I correct?
