### ISSUE TITLE
Unclear documentation, can you clarify something?

### ISSUE THREAD

**Issue by Dot-Rar** [SpigotMC/BungeeCord#2335]
From looking at the JavaDocs for this line: https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/connection/PendingConnection.java#L67 it is still unclear what it does. One would assume that it is used for checking whether the user has authenticated with the the Mojang servers (e.g. if the server is in offline mode and this value is true, they can skip authentication from plugins like AuthMe). Is this correct?

**Comment by ApocalypsjeNL** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L92 if you look at this code, then it's the online mode which is set in the config. But here it's also possile to change it. (https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L586)
