### ISSUE TITLE
[not bug][info] BungeeCord performance (CPU, RAM etc)

### ISSUE THREAD

**Issue by franciscopaniskaseker** [SpigotMC/BungeeCord#2339]
Hey folks :)

I searched a lot in issues and spigot forums something relevant about these informations, but I have no luck. **I would like to know which are the most resource use points, mainly CPU, when use bungeecord (vanilla without plugins). Maybe centralize best practices.**

I know bungeecord is a proxy server and it manage a lot of packets per second, but it does not explain a lot of CPU usage that I am seeing. 

**Some points that I need to talk:** 
- I am not seeing proportional use of resources when I have 400, 1000 or 10000 connections. So because of that I am trying to understand the mainly points of CPU usage. Hashs? checksum? md5? sha? which libraries? Maybe point some code that we can see cpu usage potential.
- I trying to figure out how improve performance bungeecord with multiple instances (how many players per bungee, how many bungeecord per server etc). If bungeecord is not scalable, how can I improve performance with multiple instances.
- Even with good G1GC parameters, I am not seeing bungeecord free all memory usage when we almost no player. I am producing some graths about memory usage and time and I am seeing, after 3 days, a low efficiency of GC to free memory with no players. Maybe is how G1GC work (if I do not need memory, so I will no work to free), but I do not think so.
- Netty, for default, only test 1% of objects to try to inspect memory leak. Do we have some article about stress test about netty implementation?
- What free java profiller usually people use to analyse bungeecord?
- Do we have some test about usage openjdk or oracle java? openjdk is the standard as we know, but we had here some stress test already done?

For sure I know that is important to use last bungeecord commits, use last netty version and last jvm... and correct use about plugins. But I want to discuss what points is important to spend some time to understand how I can improve performance. **I do no want discuss about plugins and bungeecord forks concerns, only vanilla.** And **I do not want "i think" expressions.** I think will be more productive if we can be more technical.

**Comment by Janmm14** [comment]
Non-proportional cpu usage reasons:
- cpu caches
- hashmaps (the mapping part)

Scalability with multiple instances:
Using a programmable network switch or round-robin dns and run multiple bungeecords simultaneously.
You basically want to sync player counts and your bungee plugins, for example with redis, there is also a plugin called redisbungee (src free on github).

GC:
Profilers often have the option built in to force GC. So use it and then check mem usage w/o players.

I think for free tools about mem/cpu usage people tend to use the shipped jdk tools jvisualvm/jmap/jstack.

Netty leak detection is turned off for performance by default.

**Comment by franciscopaniskaseker** [comment]
About GC choice, I think we have to use G1GC for good tradeoff about free memory and stop-the-world pauses.  With G1GC, I am trying these parameters:

- Defined Xmx to avoid Linux OOM killer execution **(example: -Xmx10G)**
- Defined Xms to decrease work to allocate more memory  **(example -Xms7G)**
- Use G1GC **(-XX:+UseG1GC)**
- For default G1GC create N threads (N is the number of default of cpus online). If we execute 3 or more bungeecord instances in same machine, 24 threads will overload a server with 8 cores. So, depending in your infra, will be nice choose best tradeoff **(example: -XX:ParallelGCThreads=4)**
- Control GC pauses to try best tradeoff **(example: -XX:MaxGCPauseMillis=50)**
- Use string deduplication is always good **(-XX:+UseStringDeduplication)**
- Do 32 bits references in 64bits JVM environment. We can save memory here, but we can not use heaps greater than 32GB) **(-XX:+UseCompressedOops -XX:+UseCompressedClassPointers)**
- Use last JVM version (always seeing all changelogs to update JVM when we will get some improvement of resources or security)

**Oracle JVM changelogs:**
[Oracle Release Notes](http://www.oracle.com/technetwork/java/javase/8u-relnotes-2225394.html)

**OpenJDK changelogs (does not has summary as oracle jvm):**
[OpenJDK Update Releases](http://openjdk.java.net/projects/jdk8u/)

**Comment by franciscopaniskaseker** [comment]
> Netty leak detection is turned off for performance by default.

According [Netty doc](http://netty.io/wiki/reference-counted-objects.html), it will sample 1% of buffers allocations to check memory leaks with no track (equal to: -Dio.netty.leakDetectionLevel=normal)

> Scalability with multiple instances:
> Using a programmable network switch or round-robin dns and run multiple bungeecords simultaneously.

Yes, but my question is about relationship between players, bungeecord instances and server hardware. How many bungeecord per server or how many players per bungee or a mix of that questions. Using one bungee per hardware maybe offer best efficiency for GC? Maybe 3 bungees can scale better cpu usage in exchange for more memory usage and smaller heaps? Maybe smaller heaps can produce more cpu usage because GC jobs?

How we can use math to try to get best performance?

**Comment by Janmm14** [comment]
> According Netty doc, it will sample 1% of buffers allocations to check memory leaks with no track (equal to: -Dio.netty.leakDetectionLevel=normal)
> by @franciscopaniskaseker 

I meant the default bungeecord introduces.

**Comment by md-5** [comment]
The getting started guide says 0.5mb ram per player.
More is bad, because you will trigger large gc pauses
Openjdk and oracle jdk are the same
Most time is spent on io, a bungee with 1000 players is processing a lot of data
I don’t buy into random java flags unless you actually know what you are doing and why

More bungees on the same machine won’t help scalability unless you did something wrong (as you have by using a 10gb heap)

**Comment by franciscopaniskaseker** [comment]
@md-5 can you point where in code we get a lot of cpu usage? like hashmaps and checksum. I would like to see what libraries are envolved. thank you.

**Comment by md-5** [comment]
You would have to find this out yourself.
Most of the CPU usage is generally from io, or even your server kernel itself.

**Comment by franciscopaniskaseker** [comment]
Changed xmx 10GB to xmx 3GB and I am seeing same use of resources (IO and cpu) with less memory. Both cases GC does not use too much CPU.

Buffers launched by netty without GC knowledge will not count in JVM heap, right?
