### ISSUE TITLE
[HelpMe] BungeeCord Players DISCONNECT!! 

### ISSUE THREAD

**Issue by gyamyro** [SpigotMC/BungeeCord#2340]
18:13:23 [INFO] [name2] disconnected with: IOException : An existing connection was forcibly closed by the remote host @ sun.nio.ch.SocketDispatcher:-2
18:14:39 [INFO] [name] disconnected with: IOException : An existing connection was forcibly closed by the remote host @ sun.nio.ch.SocketDispatcher:-2

-------------------------------
Windows 10
Last java

**Comment by Black-Hole** [comment]
Please use the Spigot forums for help configuring your server.

**Comment by Fejm** [comment]
Disable firewall & antyvirus
