### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by juancruzdal** [SpigotMC/BungeeCord#2341]
11:55:09 [INFO] [NUND] <-> ServerConnector [lobby] has connected
11:55:09 [WARNING] [/104.209.35.25:1686] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1685] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1671] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1678] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1676] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1683] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1672] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1668] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1682] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1667] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1684] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1681] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1675] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1679] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1706] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1702] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1699] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1707] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1701] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1697] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1691] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1695] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1693] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1687] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1854] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1704] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1703] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1698] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1700] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1705] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1692] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1694] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1690] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1689] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1688] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:09 [WARNING] [/104.209.35.25:1696] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
11:55:10 [INFO] [NUND] <-> DownstreamBridge <-> [auth] has disconnected
11:55:10 [WARNING] [/104.210.149.68:1129] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1126] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1120] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1823] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1766] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1962] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1117] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2036] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1353] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1738] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1964] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1994] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1768] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1800] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2044] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2013] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1401] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1996] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1365] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1363] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1355] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1371] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2021] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1114] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1998] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1851] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1222] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1132] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1135] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1123] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1113] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1985] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2028] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1984] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1405] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1346] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1779] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1974] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1094] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1811] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1978] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1837] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1925] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1816] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1950] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1362] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1752] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2045] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1848] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1992] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1244] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1106] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1383] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1381] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:2006] <-> InitialHandler - read timed out
11:55:10 [WARNING] [/104.210.149.68:1088] <-> InitialHandler - read timed out

**Comment by TheMolkaPL** [comment]
Do you have any plugins installed?

**Comment by juancruzdal** [comment]
@TheMolkaPL Yes but if i remove all plugins stay the problem, im using ovh host

**Comment by Black-Hole** [comment]
If you don't like those messages consider using a firewall rule to block those hosts.

**Comment by juancruzdal** [comment]
@Black-Hole Ok but im searching other solution

**Comment by md-5** [comment]
Its a host sending garbage to you, maybe trying to dos, or just spam your console
