### ISSUE TITLE
Forced Hosts on LocalHost?

### ISSUE THREAD

**Issue by Tripwire117** [SpigotMC/BungeeCord#2343]
I'm currently working on the start of a multi-server community. Currently I see multiple individuals using server hosting companies to manage their servers. However I am using 1 VPS service. Are there any examples for Forced Hostings to point me in the right direction? I'm using Google Domains and have established SRV & A (lobby) records for the sub servers (Using the same IP but different ports), however I'm confused on how to forward incoming connections via ports. I am aware the current setup is incorrect because it tries to connect directly to the revelation server instead of being validated by bungee/waterfall first.

listeners:
- query_port: 25577
  motd: '&aWelcome &c&l&mvictim&r &a&n%player%&r&a to &5Mekka-Flux!'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    localhost:25568: Revelation
  ping_passthrough: false
  priorities:
  - Lobby
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 160
  tab_size: 60
  force_default_server: false

servers:
  Lobby:
    motd: '&a&lWelcome &l%player% to &5&nMekka-Flux&r&l&a'
    address: localhost:25560
    restricted: false
  Revelation:
    motd: '&a&lWelcome &c&mvictim&r &a&l%player% to &5&nMekka-Flux&r&l&a Revelation!'
    address: localhost:25568
    restricted: false

Any insight would be appreciated.
    ~Trip

**Comment by md-5** [comment]
Please use spigotmc.org for support, this is a bug tracker.
Forced hosts should be using the DNS names that users are connecting via
