### ISSUE TITLE
Check Version before connect

### ISSUE THREAD

**Issue by ItsJulian** [SpigotMC/BungeeCord#2346]
Is there a way thay when a players want try to join bungeecord,

I can get the version and check if it is higher than 1.10 and otherwise cancel / kick the player,

But now the client first ask if the server is compitable with the user version and than it wil handle the events

P.s. sorry for my bad english!

**Comment by ItsJulian** [comment]
p.s. sorry for my bad english!

**Comment by Mystiflow** [comment]
You should be asking this in the forum's at spigotmc.org. At the top of my head I think you need to use event#getPlayer#getPendingConnection#getVersion, use a loginevent and protocol number references here http://wiki.vg/Protocol_version_numbers
