### ISSUE TITLE
Heavy server Load Averages

### ISSUE THREAD

**Issue by Ironic8b498** [SpigotMC/BungeeCord#2347]
was running 1294 Load Averages were 2 or lower,  updated to 1298 and Load Averages would spike to 100+ avg was 60. I have downgraded to 1294 and Load Averages back to normal. Servers are running on a Debian distro dedicated server. Is my issue bad download of the 1298 or just 1298 don't like Linux.

**Comment by md-5** [comment]
Considering the changes between these builds were just formatting the code and adding more documentation: https://github.com/SpigotMC/BungeeCord/compare/aef386178a1025cad4831cb5eeff8926a6f1b36f...master
In the absence of any evidence to the contrary this seems like a red herring.
