### ISSUE TITLE
Unknown module source: travis-ci

### ISSUE THREAD

**Issue by LudnicaKiller** [SpigotMC/BungeeCord#2348]
Bungeecord version: http://prntscr.com/ibco1o

13:08:44 [INFO] Epoll is working, utilising it!
13:08:44 [INFO] Unknown module source: travis-ci://cmd_alert
13:08:44 [INFO] Unknown module source: travis-ci://cmd_find
13:08:44 [INFO] Unknown module source: travis-ci://cmd_list
13:08:44 [INFO] Unknown module source: travis-ci://cmd_send
13:08:44 [INFO] Unknown module source: travis-ci://cmd_server
13:08:44 [INFO] Unknown module source: travis-ci://reconnect_yaml

**Comment by md-5** [comment]
Something has edited modules.yml in a format bungee does not support. Please delete it
