### ISSUE TITLE
[Bungee/FML /MC 1.12.2] Issue with a forge mod

### ISSUE THREAD

**Issue by ilFau** [SpigotMC/BungeeCord#2349]
I'm sorry for my english.

When I attempt to use a block from mod, which interact with other block my client crash.
bungeecord report:

> 02:37:49 [INFORMAZIONI] Using mbed TLS based native cipher.
> 02:37:49 [INFORMAZIONI] Using zlib based native compressor.
> 02:37:49 [INFORMAZIONI] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:dda0638:1288
> 02:37:49 [INFORMAZIONI] Not on Windows, attempting to use enhanced EpollEventLoop
> 02:37:49 [INFORMAZIONI] Epoll is working, utilising it!
> 02:37:49 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
> 02:37:49 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
> 02:37:49 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
> 02:37:49 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
> 02:37:49 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
> 02:37:49 [INFORMAZIONI] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
> 02:37:49 [INFORMAZIONI] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [INFORMAZIONI] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [INFORMAZIONI] Loaded plugin BungeeTabListPlus version 2.8.2 by CodeCrafter47
> 02:37:49 [INFORMAZIONI] Loaded plugin BungeeEssentials version 0.0.9 by Misat11
> 02:37:49 [INFORMAZIONI] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [INFORMAZIONI] Loaded plugin BungeeNews version 1.2.8 by Angeschossen
> 02:37:49 [INFORMAZIONI] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [INFORMAZIONI] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [INFORMAZIONI] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [AVVERTENZA] Forced host server pvp is not defined
> 02:37:49 [INFORMAZIONI] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:49 [INFORMAZIONI] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:50 [INFORMAZIONI] [BungeeTabListPlus] Starting UpdateChecker Task
> 02:37:50 [INFORMAZIONI] [BungeeTabListPlus] Loading default.yml
> 02:37:50 [INFORMAZIONI] Enabled plugin BungeeTabListPlus version 2.8.2 by CodeCrafter47
> 02:37:50 [INFORMAZIONI] [BungeeEssentials] Successfully loaded messages for BungeeEssentials! Language: English
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a********************
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a* BungeeEssentials *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a*    by Misat11    *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a*                  *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a*      V0.0.9      *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a*                  *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a* SNAPSHOT VERSION *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a*                  *
> 02:37:51 [INFORMAZIONI] [BungeeEssentials] §a********************
> 02:37:51 [INFORMAZIONI] Enabled plugin BungeeEssentials version 0.0.9 by Misat11
> 02:37:51 [INFORMAZIONI] [BungeeTabListPlus] Loading default.yml
> 02:37:51 [INFORMAZIONI] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:51 [INFORMAZIONI] §7[§aInfo§7] §8########################
> 02:37:51 [INFORMAZIONI] §7[§aInfo§7] §aBungeeNews enabled!
> 02:37:51 [INFORMAZIONI] §7[§aInfo§7] §8########################
> 02:37:51 [INFORMAZIONI] §7[§aInfo§7] §aAutoStart: §aStartet messages automatically! §eYou can change this in the config file!
> 02:37:51 [INFORMAZIONI] §7[§aInfo§7] §8[§4UPDATER§8] §cDon't check for updates, because you disabled it!
> 02:37:51 [INFORMAZIONI] Enabled plugin BungeeNews version 1.2.8 by Angeschossen
> 02:37:51 [INFORMAZIONI] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:51 [INFORMAZIONI] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:51 [INFORMAZIONI] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:dda0638:1288 by SpigotMC
> 02:37:51 [AVVERTENZA] Could not bind to host /0.0.0.0:25555
> io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Indirizzo già in uso
>         at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
>         at io.netty.channel.unix.Socket.bind(Socket.java:287)
>         at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:688)
>         at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
>         at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
>         at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
>         at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
>         at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
>         at java.lang.Thread.run(Thread.java:748)
> 02:38:56 [INFORMAZIONI] Closing pending connections
> 02:38:56 [INFORMAZIONI] Disconnecting 0 connections
> 02:38:57 [INFORMAZIONI] Saving reconnect locations
> 02:38:57 [INFORMAZIONI] Disabling plugins
> 02:38:57 [INFORMAZIONI] §7[§aInfo§7] §8########################
> 02:38:57 [INFORMAZIONI] §7[§aInfo§7] §aSave all files...
> 02:38:57 [INFORMAZIONI] §7[§aInfo§7] §cBungeeNews disabled!
> 02:38:57 [INFORMAZIONI] §7[§aInfo§7] §8########################
> 02:38:57 [INFORMAZIONI] [BungeeEssentials] §a********************
> 02:38:57 [INFORMAZIONI] [BungeeEssentials] §a* Thanks for using *
> 02:38:57 [INFORMAZIONI] [BungeeEssentials] §a* BungeeEssentials *
> 02:38:57 [INFORMAZIONI] [BungeeEssentials] §a********************
> 02:38:57 [INFORMAZIONI] Closing IO threads
> 02:38:59 [INFORMAZIONI] Thank you and goodbye
> 23:45:05 [INFORMAZIONI] Using mbed TLS based native cipher.
> 23:45:05 [INFORMAZIONI] Using zlib based native compressor.
> 23:45:05 [INFORMAZIONI] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:ca8f31b:1298
> 23:45:05 [INFORMAZIONI] Not on Windows, attempting to use enhanced EpollEventLoop
> 23:45:05 [INFORMAZIONI] Epoll is working, utilising it!
> 23:45:05 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
> 23:45:05 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
> 23:45:05 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
> 23:45:05 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
> 23:45:05 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
> 23:45:05 [INFORMAZIONI] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
> 23:45:05 [INFORMAZIONI] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [INFORMAZIONI] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [INFORMAZIONI] Loaded plugin AuthMeBungee version 2.0.1-SNAPSHOT by AuthMeTeam
> 23:45:05 [INFORMAZIONI] Loaded plugin BungeeTabListPlus version 2.8.2 by CodeCrafter47
> 23:45:05 [INFORMAZIONI] Loaded plugin BungeeEssentials version 0.0.9 by Misat11
> 23:45:05 [INFORMAZIONI] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [INFORMAZIONI] Loaded plugin BungeeNews version 1.2.8 by Angeschossen
> 23:45:05 [INFORMAZIONI] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [INFORMAZIONI] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [INFORMAZIONI] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [AVVERTENZA] Forced host server pvp is not defined
> 23:45:05 [INFORMAZIONI] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:05 [INFORMAZIONI] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:06 [INFORMAZIONI] [AuthMeBungee] Current auth servers:
> 23:45:06 [INFORMAZIONI] [AuthMeBungee] > lobby
> 23:45:06 [INFORMAZIONI] Enabled plugin AuthMeBungee version 2.0.1-SNAPSHOT by AuthMeTeam
> 23:45:06 [INFORMAZIONI] [BungeeTabListPlus] Loading default.yml
> 23:45:06 [INFORMAZIONI] Enabled plugin BungeeTabListPlus version 2.8.2 by CodeCrafter47
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] Successfully loaded messages for BungeeEssentials! Language: English
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a********************
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a* BungeeEssentials *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a*    by Misat11    *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a*                  *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a*      V0.0.9      *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a*                  *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a* SNAPSHOT VERSION *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a*                  *
> 23:45:06 [INFORMAZIONI] [BungeeEssentials] §a********************
> 23:45:06 [INFORMAZIONI] Enabled plugin BungeeEssentials version 0.0.9 by Misat11
> 23:45:06 [INFORMAZIONI] [BungeeTabListPlus] Loading default.yml
> 23:45:06 [INFORMAZIONI] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:06 [INFORMAZIONI] §7[§aInfo§7] §8########################
> 23:45:06 [INFORMAZIONI] §7[§aInfo§7] §aBungeeNews enabled!
> 23:45:06 [INFORMAZIONI] §7[§aInfo§7] §8########################
> 23:45:06 [INFORMAZIONI] §7[§aInfo§7] §aAutoStart: §aStartet messages automatically! §eYou can change this in the config file!
> 23:45:06 [INFORMAZIONI] §7[§aInfo§7] §8[§4UPDATER§8] §cDon't check for updates, because you disabled it!
> 23:45:06 [INFORMAZIONI] Enabled plugin BungeeNews version 1.2.8 by Angeschossen
> 23:45:06 [INFORMAZIONI] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:06 [INFORMAZIONI] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:06 [INFORMAZIONI] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:ca8f31b:1298 by SpigotMC
> 23:45:06 [AVVERTENZA] Could not bind to host /0.0.0.0:25000
> io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Indirizzo già in uso
>         at io.netty.channel.unix.Errors.newIOException(Errors.java:122)
>         at io.netty.channel.unix.Socket.bind(Socket.java:287)
>         at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:688)
>         at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70)
>         at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:558)
>         at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1283)
>         at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501)
>         at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486)
>         at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:989)
>         at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:254)
>         at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:364)
>         at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
>         at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
>         at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:309)
>         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
>         at java.lang.Thread.run(Thread.java:748)
> 

this is a report from server with forge build 2586:

> [18:05:16] [Server thread/INFO]: ilFau[/127.0.0.1:39891] logged in with entity id 12234 at (27692.61220500026, 96.0, 27518.20102013725)
> [18:05:16] [Server thread/INFO]: ilFau joined the game
> [18:05:17] [Server thread/INFO]: ilFau lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connessione interrotta dal corrispondente
> [18:05:17] [Server thread/INFO]: ilFau left the game

it don't produce crash report
the mod used was Astral Sourcery, but i try to connect directly in the server and the block work fine.

did you have suggest for resolve my trouble?

**Comment by Janmm14** [comment]
Some server is already running on port 25000 / 25555

**Comment by ilFau** [comment]
bungecoord port is on 25555, modded minecraft-server's port is 25000,  and the other server are on 25001, 25002, 25003... ecc. 

i've try to contact the mod's author and, he he also thinks that probably not related to forge
> You're using bungeecord for - i presume - a server network and thus modifying the packets as they get sent. Apparently some packet is running into issues being processed.

**Comment by md-5** [comment]
It's nothing to do with mods. You have two servers attempting to use the same port.

**Comment by ilFau** [comment]
don't close please, i'm sorry but i paste the wrong bungeereport this morning.

This is the report when the client is disconnect from server, when it uses the mod's block:

> 16:33:11 [INFORMAZIONI] [ilFau] <-> ServerConnector [lobby] has connected
> 16:33:20 [INFORMAZIONI] [ilFau] <-> ServerConnector [flavourland] has connected
> 16:33:27 [GRAVE] [ilFau] <-> DownstreamBridge <-> [flavourland] - encountered exception
> java.lang.IllegalArgumentException: Unknown meta type 15
>     at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:200)
>     at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:152)
>     at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:102)
>     at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>     at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
>     at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
>     at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
>     at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>     at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>     at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
>     at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
>     at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
>     at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
>     at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
>     at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
>     at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
>     at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
>     at java.lang.Thread.run(Thread.java:748)
> 16:33:27 [INFORMAZIONI] [ilFau] <-> DownstreamBridge <-> [flavourland] has disconnected
> 16:33:27 [INFORMAZIONI] [ilFau] <-> ServerConnector [lobby] has connected
>

**Comment by Black-Hole** [comment]
"java.lang.IllegalArgumentException: Unknown meta type 15"
BungeeCord don't know how to map that entity meta type.

Because of the way entity ids are used in Minecraft, BungeeCord needs to maintain a map of entity ids for each player and maps entity ids that are already used before server switching to new entity ids. Those entity ids are used in various packets. So BungeeCord has to watch those packets closely to not miss a mapping.

**Comment by md-5** [comment]
http://wiki.vg/Entity_metadata#Entity_Metadata_Format

There is no meta type 15 in Vanilla.
You have a mod breaking the protocol in a way Bungee can't understand.
