### ISSUE TITLE
BungeeCord doesn't let me join in the server

### ISSUE THREAD

**Issue by uppa04** [SpigotMC/BungeeCord#2352]
Hello everyone,
I have some problems with my bungeecord server, yesterday i finished to set it up, but for some reason i have a lots of problems every time i try to connect to it says: "You are alredy connected to this server"
Pls, i'm opening a new big server, i need your help!

Server console: https://pastebin.com/YVbcjK15
Config.yml: https://pastebin.com/GrFEw9Yn

I'm hosting 1 server with ShockByte Minecraft Hosting

Thanks

**Comment by TheMolkaPL** [comment]
1. You are trying to install Bukkit plugins on BungeeCord. It doesn't work.
2. Your config.yml is not configured correctly.

Use our forums for help next time. GitHub issues are for bug reports.

**Comment by uppa04** [comment]
Thanks
bye!
