### ISSUE TITLE
On 2 Servers connected (?)

### ISSUE THREAD

**Issue by R4zzer** [SpigotMC/BungeeCord#2360]
Hello, i have a problem since a few minutes.
I created a new server for my network and all works. But now i can't join this server.
We name the servers now "Lobby" and "Zombies".

All other servers in the file are working. 

When i try to join from the Lobby to the Zombies-Server, then BungeeCord says I'm already on this server, but I'm on the lobby server?

BungeeCord - config.yml
https://hastebin.com/logazopepu.erl

Lobby - server.properties
https://hastebin.com/tivokowuvu.ini

Zombies - server.properties
https://hastebin.com/adihusokor.ini

**Comment by Janmm14** [comment]
Any bungee plugins?

**Comment by R4zzer** [comment]
Yes:
AddressLimiter
AdvancedBan
BungeePexBridge
GlobalTablist
LiteAnnouncer
MultiChat
NetworkManager
PartyAndFriends
ServerListPlus
VPNGuardBungee
Yamler

**Comment by R4zzer** [comment]
It is solved, I entered an incorrect IP address in the plugin "OnlyProxy"
