### ISSUE TITLE
Scoreboard. Error after player respawn. Sponge

### ISSUE THREAD

**Issue by Mr-Krab** [SpigotMC/BungeeCord#2366]
I use a static Scoreboard with automatic update of values on the timer. I'm using a server with Sponge API.

After respawn, when the scoreboard is updated, player is thrown from the server, and the following error appears in the BungeeCord console.
https://pastebin.com/kf6UppCz

**Comment by Mystiflow** [comment]
Waterfall is not supported. Report issue at waterfalls issue tracker.

**Comment by Mr-Krab** [comment]
I can put the BungeeCord, the error will be the same. I'll do it now.

**Comment by Mr-Krab** [comment]
See this log https://pastebin.com/zxFYwSiT
WaterFall only inherits the BungeeCord code.  If you have it fixed, then the WaterFall developers will fix it.

**Comment by md-5** [comment]
Your server is creating duplicate objectives without deleting the old ones.
