### ISSUE TITLE
BungeeCord preventing Spigot from receiving LoginSuccess

### ISSUE THREAD

**Issue by Mystiflow** [SpigotMC/BungeeCord#2384]
Is there are particular reason why we are always throwing when the client sends to server the LoginSuccess? https://github.com/SpigotMC/BungeeCord/blob/8d494242265790df1dc6d92121d1a37b726ac405/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L146 

I haven't checked how Spigot handles this yet but I'd believe it's something we shouldn't be cancelling and for future proofing in case the server makes better use of this packet in the future.

**Comment by Mystiflow** [comment]
Is there are particular reason why we are always throwing when the client sends to server the LoginSuccess? https://github.com/SpigotMC/BungeeCord/blob/8d494242265790df1dc6d92121d1a37b726ac405/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L146 I haven't checked how Spigot handles this yet but I'd believe it's something we shouldn't be cancelling and in case the server makes better use of this packet in the future

**Comment by Janmm14** [comment]
I guess because bungee sends its own loginsuccess here:
https://github.com/SpigotMC/BungeeCord/blob/8d494242265790df1dc6d92121d1a37b726ac405/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L503
