### ISSUE TITLE
Help I'm trying to join server

### ISSUE THREAD

**Issue by MaximumPower117** [SpigotMC/BungeeCord#2385]
I'm trying to join a youtubers server and I keep getting a error saying 

Connection Lost
Exception Connecting:RunTimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:227

Please help me

**Comment by MaximumPower117** [comment]
This is on java minecraft 1.12

**Comment by Janmm14** [comment]
The issue tracker is for actual bugs and not for misconfiguration.
