### ISSUE TITLE
I'm the only one who can connect to my server. Anybody else who joins gets the error "io.netty.channel.ConnectTimeoutException: connection timed out: no further information".

### ISSUE THREAD

**Issue by ioixd** [SpigotMC/BungeeCord#2386]
I recently opened up a server for my meme subreddit/discord. The IP is "dededecraft.ddns.net:8080", if you need it. I'm able to connect to the server just find, however when I tried to get one of the server's staff to join, [they replied back with this.](https://media.discordapp.net/attachments/416317949905731594/422197746557124609/image.jpg?width=1048&height=611)

All the solutions I have found online say that this is an error on their part. I know that's not true, because:

* I opened up a LAN world using /publish and when trying to connect I got the same error.

* My server's staff was able to connect to another server just fine.

* I can connect it to it fine through the address.

I've had problems with the server since last night when I opened it up. Today I decided to change the DNS to a different provider, and it seems to be working more reliably. Keep in mind, they can see and connect to the server but when they join they get that error. I should note I'm actually running CraftBukkit 1.12.2, not Spigot, but I'm posting here anyway because all the Bukkit repositories are down due to a DMCA, all three of the sources I've contacted (/r/Minecraft, Bukkit forums, Minecraft Forums) have either ignored my post or straight up removed it, and I understand Spigot is a fork of Bukkit so I might be able to get help here.

In addition, I checked the log today and I saw this repeated about thirty times:

`[18:48:20 WARN]: Selector.select() returned prematurely 512 times in a row; rebuilding Selector io.netty.channel.nio.SelectedSelectionKeySetSelector@199b5d1.`
`[18:48:20 INFO]: Migrated 0 channel(s) to the new Selector.`

with the last message saying "1 channel(s)" instead of zero. I feel like this is related somehow.

**Comment by Janmm14** [comment]
CraftBukkit is maintained by spigot and a repository and issue management exists at hub.spigotmc.org, also the forums at spigotmc.org can help with craftbukkit issues.
Is that log from bungee or craftbukkit?
