### ISSUE TITLE
ColorCode reset doesn't work

### ISSUE THREAD

**Issue by YTKacperSKY** [SpigotMC/BungeeCord#2387]
The reset ColorCode doesn't work (don't resets chat format like bold, italic or magic)

**Comment by Black-Hole** [comment]
Please provide some code to reproduce your issue.

**Comment by YTKacperSKY** [comment]
`cs.sendMessage(TextComponent.fromLegacyText("§a§lTest §r§k» §7this text should be normal"));
cs.sendMessage(new ComponentBuilder("").append(TextComponent.fromLegacyText("§a§lTest §r§k» §7this text should be normal")).create());`

the first one works but the second doesn't work since Build #1302 I use the second for a message dispatch builder

**Comment by md-5** [comment]
@Mystiflow
