### ISSUE TITLE
Server Restart - Already connected to this server

### ISSUE THREAD

**Issue by Loonyy** [SpigotMC/BungeeCord#2390]
Got quite a weird issue.

When I restart a server, it'll stop the server and say I've left in console, however, I'll still appear in-game in sort of "limbo"
https://proxy.spigotmc.org/0745c71256ca0f51bf8653b505bd26996fb081f2?url=https%3A%2F%2Fi.gyazo.com%2Fbf57e19b61b2563edcf5c4bc0df317f0.png
..and I'll still appear on the Tablist for the server for other players. It should instead send me to the fallback server which is the hub, but instead it's just keeping me on the server.

This happens for all of my servers.
Any ideas?

**Comment by Mystiflow** [comment]
Can you reproduce without plugins?

**Comment by Loonyy** [comment]
I’m not in a position to test that at this moment, my server keys are maxed out so can’t create a new server.

**Comment by Loonyy** [comment]
Update -- This also happens when kicking someone from the server.

**Comment by Black-Hole** [comment]
Please provide at least a list of the plugins you're running on BungeeCord.

**Comment by Loonyy** [comment]
Plugins:
- AdvancedBan
- BungeeKick
- BungeePerms
- BungeeTablistPlus
- EMPBungee
- SayNoToMCLeaks
- SlashServer
- ViaVersion
- ViaBackwards
- MoveMeNow

Config:
[code]
ip_forward: true
network_compression_threshold: 256
stats: 4d680820-af20-4f96-aa0c-7461995ca6fa
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  - slashserver.creative
  - slashserver.bending
  - slashserver.skywars
  - slashserver.hub
  - bungeechat.command.msg
  - multichat.chat.msg
  builder:
  - bungeecord.command.server
  - bungeecord.command.creative
  - bungeecord.command.list
  staff:
  - sc.use
  - sc.msg
  - sc.reply
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.server.creative
  owner:
  - bungeecord.command.*
  - bungeecord.command.send
  - bungeecord.command.find
  - bungeetablistplus.*
  - multichat.*
groups:
  Loonyy:
  - admin
  - staff
  - owner
servers:
  hub:
    motd: '&a&lElementum &c- Under Maintenance.'
    address: localhost:25566
    restricted: false
  bending:
    motd: '&a&lElementum &c- Under Maintenance.'
    address: localhost:25567
    restricted: false
  creative:
    motd: '&a&lElementum &c- Under Maintenance.'
    address: localhost:25568
    restricted: false
  skywars:
    motd: '&a&lElementum &c- Under Maintenance.'
    address: localhost:25569
    restricted: true
timeout: 30000
listeners:
- query_port: 25565
  motd: '&a&lElementum &c-Under Maintenance.'
  priorities:
  - hub
  - bending
  - creative
  - skywars
  bind_local_address: true
  tab_list: GLOBAL_PING
  query_enabled: false
  host: 0.0.0.0:25565
  forced_hosts:
    hub.elementum.me: hub
    bending.elementum.me: bending
    creative.elementum.me: creative
    skywars.elementum.me: skywars
  max_players: 200
  tab_size: 60
  ping_passthrough: false
  force_default_server: false
  fallback_Server: hub
player_limit: -1
online_mode: true
log_commands: false
disabled_commands:
- disabledcommandhere
connection_throttle: 4000
[/code]

**Comment by md-5** [comment]
Unsupported plugins in use

**Comment by Loonyy** [comment]
..such as what? which plugin is causing this?

**Comment by md-5** [comment]
I don't know, but we can't support plugins that make unknown modifications to bungeecord - eg viaversion

**Comment by Loonyy** [comment]
All ViaVersion does is allow people to connect on different versions than the server version, but alright

**Comment by Paulomart** [comment]
We also got this problem, we don't now how it's happening but it seems like an issue with the timeout detection. In some cases the player is already timed out, but the events fire 10 seconds or more later.
