### ISSUE TITLE
IDEA - Event "KickEvent"

### ISSUE THREAD

**Issue by Tauchet** [SpigotMC/BungeeCord#2392]
Event is for detect all disconnects by:

> InitialHandler.this.disconnect(InitialHandler.this.bungee.getTranslation("offline_mode_player", new Object[0]));

My system caches in the PreLoginEvent and I do not know if the player is still connected or I cancel the connection, but thanks to that event I could fix it

**Comment by md-5** [comment]
Duplicate #2194 
Therre already is a disconnect event.
I’d probably argue that you’re in the wrong by using the pre event to make any decisions aside from can this player join the server
