### ISSUE TITLE
StackOverflowError during player transfer?

### ISSUE THREAD

**Issue by SocketByte** [SpigotMC/BungeeCord#2393]
My customer is getting pretty confusing error logs. I don't really know what can be the problem.
Error is on this line:
```java
player.connect(ProxyServer.getInstance().getServerInfo("lobby"));
```
That's all. It's in `PostLoginEvent` if it's important.
Lobby server is of course enabled and ready. 

Detailed error logs:  (Too long, needed pastebin)
https://pastebin.com/raw/CEpaQPEx

Any suggestions?

**Comment by md-5** [comment]
Youre calling .connect in ServerConnectEvent
