### ISSUE TITLE
Ping Issue

### ISSUE THREAD

**Issue by CoenDoesGaming** [SpigotMC/BungeeCord#2394]
Hey, sorry to bother you.

But i'm having serveral problems with ping on my bungeecord network, i have mixed server locations 2 from united states and 4 from australia, they seem to break and i end up getting like 500ms when i normally get 20ms on my australian server. Is there any way to fix this?

**Comment by Janmm14** [comment]
This kind of issue is not suited for the issue tracker and belongs to the spigotmc.org forums.

**Comment by md-5** [comment]
There's not enough info here to be considered a bug report.
I'm not even sure what the issue is "seem to break" isn't very specific. It sounds like you're proxying over long distances due to a misconfiguration.
