### ISSUE TITLE
Can't login to Proxy

### ISSUE THREAD

**Issue by R4zzer** [SpigotMC/BungeeCord#2395]
Minecraft only say's: "Logging in.." to me.

Error in Console: ([*For the full log-file click me*](https://hastebin.com/uviripilix.sql))
![31 214 246 148 - putty-000026](https://user-images.githubusercontent.com/29443613/37964215-01bde808-31c1-11e8-8284-ce7529d8d678.jpg)

All Plugins:
AddressLimiter - https://www.spigotmc.org/resources/addresslimiter.42399/
AdvancedBan - https://www.spigotmc.org/resources/advancedban.8695/
EinBot - https://www.spigotmc.org/resources/einbot-teamspeakbot-verify-support-auch-cloudnet.48188/
FriendSystem - https://www.spigotmc.org/resources/friendsystem-gui-mysql-beta.39838/
GlobalTablist - https://www.spigotmc.org/resources/globaltablist.1117/
LiteAnnouncer - https://www.spigotmc.org/resources/liteannouncer-bungeeautomessage.23918/
MultiChat - https://www.spigotmc.org/resources/multichat.26204/
NetworkManager - https://www.spigotmc.org/resources/networkmanager.28456/
ServerListPlus - https://www.spigotmc.org/resources/serverlistplus.241/
VPNGuardBungee - https://www.spigotmc.org/resources/vpnguardbungee.31915/

**Comment by Janmm14** [comment]
Either you did not specified any server in the priority in the bungee config or one of the plugins sets the seerver to connect to to no server ("null")

**Comment by R4zzer** [comment]
But I have nothing changed since days on the plugins and everything worked.
The mistake emerged from nowhere

**Comment by R4zzer** [comment]
I will check all plugins.
