### ISSUE TITLE
TextComponent.fromLegacyText(String message, ChatColor reset) to choose the replacement of ChatColor.RESET to match the environment

### ISSUE THREAD

**Issue by Selebrator** [SpigotMC/BungeeCord#2396]
```net.md_5.bungee.api.chat.TextComponent#fromLegacyText(String)``` makes the text after ChatColor.RESET become white.
But the default/reset color is different from white in some text fields. In books and on signs the color defaults to black and in Lore it's purple.
I suggest adding a new method ```net.md_5.bungee.api.chat.TextComponent#fromLegacyText(String, ChatColor)```  the first argument is the same for both methods. The added argument is the color used for ChatColor.RESET

**Comment by Mystiflow** [comment]
@md-5 How about the solution suggested by @Selebrator ?

**Comment by Janmm14** [comment]
It should be possible to solve this without the given solution.

**Comment by md-5** [comment]
Not sure what you're asking 
The craftbukkit legacy conversion methods can set the reset colour

**Comment by Selebrator** [comment]
I don't know what methods you are talking about, maybe [these](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/util/CraftChatMessage.java)?
Maybe a little bit of context can help. I want to add colored text, selectors and scores too the pages of a book. Currently I parse my input strings into TextComponent, SelectorComponent and ScoreComponent and use ```org.bukkit.inventory.meta.BookMeta.Spigot#setPages(List<BaseComponent[]>)``` because I could not get ```org.bukkit.inventory.meta.BookMeta#setPages(List<String>)``` to work with selectors and scores. I just could not find any way to get this working without rewriting ```net.md_5.bungee.api.chat.TextComponent#fromLegacyText(String)```, but would be very happy to see my mistake.

**Comment by Selebrator** [comment]
Btw I have everything working. It's just that §r becomes white but black is expected.

**Comment by Selebrator** [comment]
By adding
`
input = input.replace("§r", "§0");
`
before doing the parsing I get the desired result.
I still think it's a good idea to add the method though. Sorry if I wasted your time. I don't mind if you close the Ticket if you don't consider my proposal to be useful.

**Comment by Janmm14** [comment]
So its not possible to leave "reset" as reset in the components?
