### ISSUE TITLE
KeepAlive handling is flawed

### ISSUE THREAD

**Issue by Janmm14** [SpigotMC/BungeeCord#2397]
If the ping of a player is greater than 1 second, the [DownStreamBridge](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L107-L112) might have already recieved the next KeepAlive from the server, overriding the sent ping id and causing the [UpstreamBridge](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L117-L129) to cancel legit recieved pings from the client.

The solution is to hold a map of pingid and sent millis instead.

**Comment by md-5** [comment]
Sooo PR?

**Comment by Janmm14** [comment]
I just noticed the issue in the code, will create a PR soon.
