### ISSUE TITLE
IndexOutOfBounds

### ISSUE THREAD

**Issue by JamieSinn** [SpigotMC/BungeeCord#2399]
https://pastebin.com/raw/aucLcHyf

Happened very randomly.

Netty issue? or Bungee?

**Comment by andrewkm** [comment]
Can confirm this continues to happen to us throwing random players off certain servers.

**Comment by md-5** [comment]
You have something on the server sending a completely empty packet (which is not allowed).
I've seen ProtocolSupport do this, so it could be that if you have it installed

**Comment by JamieSinn** [comment]
ProtocolSupport isn't installed, any other known problem plugins?

**Comment by Fejm** [comment]
I got it by playing sound / effect from async thread. Check it out.
