### ISSUE TITLE
ColorCodes don't work

### ISSUE THREAD

**Issue by FrankHeijden** [SpigotMC/BungeeCord#2400]
Currently having this code as Staffchat messaging thing, but very long strings don't get colored right. Only the first row will get colored. Example class:

```
import net.md_5.bungee.api.ChatColor;
import net.md_5.bungee.api.CommandSender;
import net.md_5.bungee.api.chat.ComponentBuilder;
import net.md_5.bungee.api.chat.HoverEvent;
import net.md_5.bungee.api.chat.TextComponent;
import net.md_5.bungee.api.plugin.Command;

public class Test extends Command {

    public Test() {
        super("test", "");
    }

    @Override
    public void execute(CommandSender sender, String[] args) {
        TextComponent msg = new TextComponent(ChatColor.translateAlternateColorCodes('&', "&7tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"));
        msg.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, new ComponentBuilder(ChatColor.translateAlternateColorCodes('&', "&bHello")).create()));
        sender.sendMessage(msg);
    }
}
```

When this command is executed, this will happen in chat:
https://gyazo.com/d5ec215df16b96ef0c60f7ff10e59a13

**Comment by Black-Hole** [comment]
That is a client side rendering bug for legacy color codes. So don't use color codes in compound messages, instead use methods like .color() to set the color.

**Comment by FrankHeijden** [comment]
well ok, but then still an issue with the ComponentBuilder, if I have a string which contains a link it does not work/click when that ComponentBuilder#create() String is being sent in chat.

**Comment by kamcio96** [comment]
@FrankHeijden default `sendMessage(String)` has parser with URL pattern and generates clickable components. ChatAPI is simple API to generate json message with other functions than URL click, but there you have to set everything manually :/

**Comment by Black-Hole** [comment]
With ComponentBuilder you still have to use .event() to make chat messages clickable.
If you're using your code to display user input and don't want to parse URLs for yourself, you might want to have a look at TextComponent.fromLegacyText().

But for further help you should use the community support of the Spigot forums.

**Comment by md-5** [comment]
https://www.spigotmc.org/wiki/the-chat-component-api/#common-pitfalls
