### ISSUE TITLE
Server not starting...

### ISSUE THREAD

**Issue by TheColdEmeraldCODE** [SpigotMC/BungeeCord#2401]
My server wont start and this is what i see:

`07:15:39 [SEVERE] Exception in thread "main"
07:15:39 [SEVERE] java.lang.IllegalArgumentException: Server lobby (priority 0) is not defined
07:15:39 [SEVERE] at com.google.common.base.Preconditions.checkArgument(Preconditions.java:359)
07:15:39 [SEVERE] at net.md_5.bungee.conf.Configuration.load(Configuration.java:123)
07:15:39 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:269)
07:15:39 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
07:15:39 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
`

**Comment by DoNotSpamPls** [comment]
In your config you have defined `lobby` as a server to join first, but the lobby server doesn't exist. Check your config to fix this.

**Comment by TheColdEmeraldCODE** [comment]
How do you disable priorities? Can you?

**Comment by DoNotSpamPls** [comment]
No, you can't. Please read the documentation on how to use BungeeCord [here](https://spigotmc.org/wiki/bungercord)

**Comment by Nolram12345** [comment]
I am using CloudNet tho, so the Lobby server is only created after the Proxy has already started, adn the Lobby server has a dynamic name (Hub-1, Hub-2...)

**Comment by Janmm14** [comment]
In that case, add some dummy server with a cryptic name and unreachable address or some backup spigot you run static, and add it as only priority to the config.

Alternatively you could try to set it to empty like this:
```yaml
  priorities: []
```

**Comment by Nolram12345** [comment]
I have already found a solution, the config was formatted wrong (I accidentally added a space). Thanks anyways !
