### ISSUE TITLE
Bungeecord UUID Issues

### ISSUE THREAD

**Issue by Luysita** [SpigotMC/BungeeCord#2405]
Hello,

I am having issues with my UUIDS from the main server and creative server.
For example, in the whitelist a user's name would appear like this in the main server:

``  {
    "uuid": "1fc14391-958d-31a9-b1d8-26f76a6548d8",
    "name": "Smok3yp"
  },``

And in the creative server it has another UUID:

``  {
    "uuid": "ea39b0af-8e06-426b-86e5-3a92462f282b",
    "name": "Smok3yp"
  },``

Not sure what is causing this, in both server I have Bungeecord: true in spigot.yml, so could someone help me on this?

Thank you.

**Comment by Janmm14** [comment]
Your main server somehow has the offline UUID.

**Comment by Luysita** [comment]
@Janmm14 Yes I know, but how do I change that?

**Comment by Luysita** [comment]
@Black-Hole I did follow those instruction and it's still not working for the main server. For other servers it's working properly.

**Comment by Black-Hole** [comment]
As I said before the issue tracker is not the place to pin down your configuration issue. So please use the Spigot forums and post details about your setup and configuration there.

**Comment by Luysita** [comment]
Quick Links

    Downloads - Latest build is generally stable and recommended!
    Source Code - Use this to browse the code, make pull requests or start hacking on a Bungee plugin.
    Bug Reports - Issues posted on these forums will be ignored, use this tracker instead.

**Comment by Luysita** [comment]
Bungeecord
config: https://pastebin.com/tbyZSH8e

Main server info
server.properties: https://pastebin.com/EaufRZax
spigot.yml: https://pastebin.com/rtBBZyHf

Creative server info
server.properties: https://pastebin.com/9wxAFk37
spigot.yml: https://pastebin.com/HtNmte8T


Not really sure if I'm missing something here.
