### ISSUE TITLE
Getting error when using command /alert etc

### ISSUE THREAD

**Issue by vlaggenstok** [SpigotMC/BungeeCord#2406]
13.04 14:43:19 [Server] INFO at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:389) 13.04 14:43:19 [Server] INFO at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:404) 13.04 14:43:19 [Server] INFO java.lang.LinkageError: net/md_5/bungee/api/ChatMessageType 13.04 14:43:19 [Server] SEVERE -> UpstreamBridge - encountered exception
how to fix

**Comment by md-5** [comment]
Incomplete error.
Please ensure your server is up to date

**Comment by vlaggenstok** [comment]
Still get  the error.
now using BungeeCord-Bootstrap:1.12-SNAPSHOT:cbfdf64:1308

**Comment by vlaggenstok** [comment]
``13.04 15:03:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:03:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) 13.04 15:03:01 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:03:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:03:01 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:03:01 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:141) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.module.cmd.alert.CommandAlert.execute(CommandAlert.java:22) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:399) 13.04 15:03:01 [Server] INFO at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:414) 13.04 15:03:01 [Server] INFO java.lang.LinkageError: net/md_5/bungee/api/ChatMessageType 13.04 15:03:01 [Server] SEVERE -> UpstreamBridge - encountered exception
full error

**Comment by md-5** [comment]
Remove all plugins and modules and let bungee redownload

**Comment by vlaggenstok** [comment]
still get the error.

**Comment by md-5** [comment]
Post your full log

**Comment by vlaggenstok** [comment]
> 13.04 15:10:43 [Multicraft] Skipped 22 lines due to rate limit (30/s) 13.04 15:10:31 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:10:31 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) 13.04 15:10:31 [Server] INFO at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:10:31 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:10:31 [Server] INFO at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) 13.04 15:10:31 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:141) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:116) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:169) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.module.cmd.alert.CommandAlert.execute(CommandAlert.java:22) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:399) 13.04 15:10:31 [Server] INFO at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:414) 13.04 15:10:31 [Server] INFO java.lang.LinkageError: net/md_5/bungee/api/ChatMessageType 13.04 15:10:31 [Server] SEVERE -> UpstreamBridge - encountered exception 13.04 15:10:31 [Server] INFO >K 13.04 15:10:31 [Server] INFO Ramine2001 executed command: /alert

>

**Comment by md-5** [comment]
Your full log from proxy startup...

**Comment by md-5** [comment]
(Works completely fine for me)
```
23:14:49 [INFO] [md_5] <-> ServerConnector [lobby] has connected
23:14:52 [INFO] [Alert] test
```

**Comment by vlaggenstok** [comment]
> 13.04 15:15:16 [Server] Startup Listening on /ip 13.04 15:15:16 [Server] INFO >K 13.04 15:15:16 [Server] INFO Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Enabled plugin LiteBans version 2.2.15 by Ruan 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO v2.2.15 enabled. Startup took 1198 ms. 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Database connection fully initialized (72.1 ms). 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO [Sync] Server UUID: databasestuff 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO [Sync] Server name: litebans 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Connected to [databasestuff] (35.7 ms). 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Connecting to database... 13.04 15:15:16 [Server] INFO K 13.04 15:15:16 [Server] INFO Loading SQL driver: mysql (com.mysql.jdbc.Driver) 13.04 15:15:16 [Server] INFO K 13.04 15:15:15 [Server] INFO Enabled plugin BungeePerms version 3.0-alpha-1 by wea_ondara 13.04 15:15:15 [Server] INFO K 13.04 15:15:15 [Server] INFO Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:15 [Server] INFO K 13.04 15:15:15 [Server] INFO Activating BungeePerms ... 13.04 15:15:15 [Server] INFO K 13.04 15:15:15 [Server] INFO Enabled plugin bungeetestlars. version 1.0 by null 13.04 15:15:15 [Server] INFO K 13.04 15:15:15 [Server] INFO De plugin is verbonden met de database. 13.04 15:15:15 [Server] INFO K 13.04 15:15:15 [Multicraft] Skipped 24 lines due to rate limit (30/s) 13.04 15:15:14 [Server] INFO extracting lang/EN-gb.yml 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Loaded plugin bungeetestlars. version 1.0 by null 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:cbfdf64:1308 by SpigotMC 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Download complete 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Attempting to Jenkins download module reconnect_yaml v1308 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Attempting to update plugin from null to ModuleVersion(build=1308, git=cbfdf64) 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Download complete 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Attempting to Jenkins download module cmd_server v1308 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Attempting to update plugin from null to ModuleVersion(build=1308, git=cbfdf64) 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Download complete 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Attempting to Jenkins download module cmd_send v1308 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Attempting to update plugin from null to ModuleVersion(build=1308, git=cbfdf64) 13.04 15:15:14 [Server] INFO K 13.04 15:15:14 [Server] INFO Download complete 13.04 15:15:14 [Server] INFO K 13.04 15:15:13 [Server] INFO Attempting to Jenkins download module cmd_list v1308 13.04 15:15:13 [Server] INFO K 13.04 15:15:13 [Server] INFO Attempting to update plugin from null to ModuleVersion(build=1308, git=cbfdf64) 13.04 15:15:13 [Server] INFO K 13.04 15:15:13 [Server] INFO Download complete 13.04 15:15:13 [Server] INFO K 13.04 15:15:13 [Server] INFO Attempting to Jenkins download module cmd_find v1308 13.04 15:15:13 [Server] INFO K 13.04 15:15:13 [Server] INFO Attempting to update plugin from null to ModuleVersion(build=1308, git=cbfdf64) 13.04 15:15:13 [Server] INFO K 13.04 15:15:13 [Server] INFO Download complete 13.04 15:15:13 [Server] INFO K 13.04 15:15:12 [Server] INFO Attempting to Jenkins download module cmd_alert v1308 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Attempting to update plugin from null to ModuleVersion(build=1308, git=cbfdf64) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource()) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource()) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource()) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource()) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource()) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource()) 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Epoll is working, utilising it! 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:cbfdf64:1308 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Using standard Java compressor. 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Could not load native library: Expecting an absolute path of the library: tmp/bungeecord-native-compress9063256461136050812.so 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Using standard Java JCE cipher. 13.04 15:15:12 [Server] INFO K 13.04 15:15:12 [Server] INFO Could not load native library: Expecting an absolute path of the library: tmp/bungeecord-native-cipher16644758074927907.so 13.04 15:15:12 [Server] INFO K 13.04 15:15:11 [Server] INFO Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0 13.04 15:15:11 [Multicraft] Updating eula.txt file 13.04 15:15:11 [Multicraft] Loaded config for "[Custom] custom.jar"

**Comment by vlaggenstok** [comment]
i found the problem , probably causes the user connection . in my own plugin i used p.connect onjoin that causes the error , now using setreconnect .
thanks for your support.
it was my fault.
