### ISSUE TITLE
BungeeCord problem

### ISSUE THREAD

**Issue by Miniller** [SpigotMC/BungeeCord#2410]
Hi. I have a problem...
I have BungeeCord and a Lobby server
When a new player registers to my server, AUTHME says that we (Me and the new player) have the same IP address. How??
I think the error is in my Bungee config, because if I rewrite 
address: 192.168.1.66:25566
to address: MY.PUBLIC.IPV4:25566
then the player IP address is MY.PUBLIC.IPV4

My BungeeCord config: https://pastebin.com/fqsptCNy
Sorry for my bad English

**Comment by md-5** [comment]
Use the forums for support.
Read the guide about ip forwarding.
