### ISSUE TITLE
Crash when switching server, SpongeForge Server and FML 0 mods client

### ISSUE THREAD

**Issue by Fungie2134** [SpigotMC/BungeeCord#2413]
This took me a lot of time ! But I finaly got you a no - mod crash report for this issue, let's explain the setup (1.12.2, Java 8 everywhere, local Gigabit network) :

- The proxy is the latest BungeeCord at this date, in offline mode, with SpongePls for only plugin, ip forwarding set to true.

- The backend servers were SpongeForge servers using FML 1.12.2-2655 and the latest Sponge for this version (3064), ip forwarding set to true, offline mode (So the equivalent of a SpongeVanilla server. No plugins were present.

- The client was a 0 mod FML client using the same 2655 version the server was using.

What I did :

1. Connected to the proxy on the server 1
2. Started to /send the player every 10 seconds to the others server, so 1 --> 2 --> 1 etc.

And after a few times (~50 tries), the client crashed while logging in, giving me this crash report :
https://pastebin.com/i9wnsprG (Crash)
https://pastebin.com/WPJmVzdX (Logs)
https://pastebin.com/cuGMMBas (FML logs)
This crash had already been reported to A LOT of mods authors, Sponge, SpongePls, and you, but always using mods. Bungee seems to be the source of that issue. This issue generally happens more often with a large amount of mods like FTB servers. 

I hope this will help fixing this issue ! As it never happens without FML on the client I will also report this to Forge, but they should not be the issue. They do not change the vanilla code here.
Sponge says that it can't be the issue too.

To finish, some others cases :
https://github.com/SpigotMC/BungeeCord/issues/2350
https://github.com/MinecraftForge/MinecraftForge/issues/4764
https://github.com/SpongePowered/SpongeForge/issues/1978

**Comment by md-5** [comment]
I mean Forge is a mod, and clearly a change it makes (or vice-versa) conflicts with BungeeCord.
Given the point of BungeeCord is to do things that the Vanilla client wouldn't normally allow, and that BungeeCord works fine on Vanilla I would suggest Bungee is doing its job properly.

I'm not familiar with Forge, so if someone wants this issue fixed they can look into it.

But repeating: given that BungeeCord works fine with Vanilla and only Forge crashes, then unless BungeeCord is doing some Forge specific code path, I see this as a Forge client bug and not something Bungee can fix.

**Comment by Fungie2134** [comment]
Forge may have fixed it. I will reopen it if necessary.
Thanks !
