### ISSUE TITLE
Kick All Players

### ISSUE THREAD

**Issue by farukkislakci** [SpigotMC/BungeeCord#2414]
17:46:46 [WARNING] [/78.sda39.35:56693] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
17:46:51 [INFO] [/78.a9.35sd:34025] <-> InitialHandler has connected
17:46:52 [INFO] [/18a4.97:42sd848] <-> InitialHandler has connected
17:46:59 [WARNING] [omermarvel] -> UpstreamBridge - read timed out
17:46:59 [INFO] [omermarvel] disconnected with: §fReadTimeoutException : null

PLS HELP ME

**Comment by Janmm14** [comment]
Use spigotmc forums for support. Such errors indicate a problem in the networking area and not inside bungeecord.

**Comment by omermarvel** [comment]
how this kicking all in bungee player and in proxy.log.0

**Comment by Janmm14** [comment]
The log above jsut shows that bungee just recieves that the connection was closed (Connection reset by peer) / that there was no data recieved (ReadTimeoutException).

**Comment by omermarvel** [comment]
why it is caused?

**Comment by Janmm14** [comment]
That is unclear, but its not a bungeecord issue.
