### ISSUE TITLE
possibility to get last server from locations.yml

### ISSUE THREAD

**Issue by vlaggenstok** [SpigotMC/BungeeCord#2415]
Is it possibel to get the last server a player joined from the locations.yml file.

**Comment by Mystiflow** [comment]
```ProxyServer.getInstance().getReconnectHandler().getStoredServer()``` should do the trick.

**Comment by Janmm14** [comment]
post your exception then?

**Comment by Black-Hole** [comment]
So you're calling the method with a null ProxiedPlayer.

For support please use the Spigot forums.
