### ISSUE TITLE
Bungeecord error: Error whilst handling query packet from null

### ISSUE THREAD

**Issue by theralmccoy1234** [SpigotMC/BungeeCord#2417]
I'm getting this error every 3 minutes and then 3 times within 10 seconds in a row
**https://pastebin.com/kkvSrpbJ**

Can anybody tell me how to get rid of it and what causes the error?

**Comment by md-5** [comment]
You are either not running bungee, or running a bungee over a year old.

Please update bungee and open with a new error.

**Comment by Black-Hole** [comment]
Or somebody is sending garbage to your query port. Set `query_enabled: false` in your BungeeCord config if you don't need the query port.

**Comment by theralmccoy1234** [comment]
Well actually it was Bungee-Version  #1310Von meinem Huawei-Mobiltelefon gesendet-------- Originalnachricht --------Betreff: Re: [SpigotMC/BungeeCord] Bungeecord error: Error whilst handling query packet from null (#2417)Von: md-5 An: SpigotMC/BungeeCord Cc: theralmccoy1234 ,Author You are either not running bungee, or running a bungee over a year old.
Please update bungee and open with a new error.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/SpigotMC/BungeeCord","title":"SpigotMC/BungeeCord","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/SpigotMC/BungeeCord"}},"updates":{"snippets":[{"icon":"PERSON","message":"@md-5 in #2417: You are either not running bungee, or running a bungee over a year old.\r\n\r\nPlease update bungee and open with a new error."}],"action":{"name":"View Issue","url":"https://github.com/SpigotMC/BungeeCord/issues/2417#issuecomment-386462111"}}}
