### ISSUE TITLE
[Forge/Sponge] Client crash when Server switching

### ISSUE THREAD

**Issue by TeraNovaLP** [SpigotMC/BungeeCord#2418]
Hello,

I noticed a bug when connecting to other Servers and hover over an item at the same time what causes the client to crash.

Then I searched on Google and found this old Issue: https://github.com/SpigotMC/BungeeCord/issues/1326

I have the same Issue with Sponge Vanilla: 1.12.2-7.1.0 BETA-33.

Is there a chance for a fix?

**Comment by md-5** [comment]
Please see https://github.com/SpigotMC/BungeeCord/issues/2413
