### ISSUE TITLE
[RFC] Drop old versions support since 1.13

### ISSUE THREAD

**Issue by XakepSDK** [SpigotMC/BungeeCord#2419]
The whole thing about multiversion was just to support last version and previous for migration purposes, but sometime this gone wrong and now everyone sits on 1.8(!) that is 4(!) years old!
I think, this is time for resolute actions to stop that circus with old versions.

**Comment by XakepSDK** [comment]
Same thread in protocolsupport: ProtocolSupport/ProtocolSupport#817

**Comment by Janmm14** [comment]
Removing an existing and working system just for the sake of some people wanting to force others to upgrade is useless and I bet it won't happen.
As this is open source, people would just fork this project or use existing forks like waterfall or travertine which won't remove support for older versions, as travertine even support 1.7 by now.

**Comment by md-5** [comment]
I would love to do this, but people will just fork it as they have done for 1.7.

Maybe you could convince them to drop it instead.

**Comment by md-5** [comment]
Ultimately the issue lies with the servers.

We dropped support for Spigot 1.8 years ago, yet servers still come to us complaining about it.

**Comment by Fejm** [comment]
1.8... It's because of new pvp mechanic on 1.9+. Also i found that 1.12 has a lot of client/server bugs, so maybe issue was here.
