### ISSUE TITLE
Bungee Crashes - Packets bots?

### ISSUE THREAD

**Issue by GlobooX** [SpigotMC/BungeeCord#2420]
My bungeecord version: git:BungeeCord-Bootstrap:1.12-SNAPSHOT:b5f17e7:190 by md_5
My server is online mode: true

Hi, all of last 3 days I am having problems with BungeeCord..
Someone just crash my Bungee but i dont know how..

Crashes are randomly, just when someone who do it just want to do it..
BungeeCord log do not show anythink. BungeeCord just stop responding

I disable all my plugins becouse i think it was problem but Bungee crashes still.
Sometimes when i have plugins installed and when not too i i have a lot of "hs_Err_pid" files". Bungee just crash becouse OutOfMemory when "attacker" crash bungee. https://pastebin.com/aUXBhSSG

ALL of the time when crash in the last line of logs is
" [INFO] [/IP HERE] <-> InitialHandler has connected"   but IP is always proxy from countries which my players are not playing on my serever.

Question is.. How someone do this and how to protect my Bungee?

**Comment by pjorun** [comment]
I have this same problem, but i know much more about this issue. md_5 made not good secure code about 2 years ago and he do not check it. Bots are sending packets and this make huge CPU usage and crash. All other fork BC do not secure this.

**Comment by Black-Hole** [comment]
Java is crashing with an internal exception, you should update your Java version, Java 8 Update 74 is more than two years old.

@pjorun If you believe that's a fixable issue that could be "fixed" with a simple fix, please create an issue for it. I believe there is no simple fix for DDoS attacks. Those should be handled by the infrastructure provider. There are providers with a decent DDoS protection.

**Comment by pjorun** [comment]
@Black-Hole yes, this is fixable. I have latest Java version but this is now fixable in this site. First your BC have huge CPU usage 500/700% later ram usage and crash. There is a problem with receiving packets.

**Comment by md-5** [comment]
Your java is eons outdated

>This looks to me like a new error inside the native compression code either in zlib or in bungee's wrapper.

I don't think there is any error aside from invalid data being sent. The crash is likely a java bug and probably already fixed.

**Comment by Encode17** [comment]
I have exactly the same problem as you up from few days. Someone is crashing my bungee by sending packets. It is really java problem? :(

**Comment by Encode17** [comment]
I have exactly the same problem as you up from few days. Someone is crashing my bungee by sending packets. It is really java problem? :(

**Comment by Miracle407** [comment]
I have exactly the same problem as you up from few days. I did not change nothing up from year.
Someone is crashing my bungee. I see nothing more in logs than "InitialHandler has connected" at one of last lines where one of IPs is VPN. It is really java problem and update will help? 
Please help me. I have a lot of players and they are leaving my server due to this kicks :(

**Comment by MiMic10110** [comment]
Same problem. Someone is crashing big networks (including mine) using this method.
@md-5 I have java 8 172 and my bungee is having same issues.

**Comment by md-5** [comment]
Then post your crash report.

**Comment by MiMic10110** [comment]
@md-5  (NULL = NULL SYMBOL):
NULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULLNULL
This is last line in my proxy logs.

**Comment by GlobooX** [comment]
I have the same log sometimes!

**Comment by pjorun** [comment]
I use latest java8, latest bc and latest spigot. This is not Java problem.

**Comment by md-5** [comment]
Bungee does not print nul in logs

**Comment by GlobooX** [comment]
@md-5 
I make packet receiver.  When "attacker" crash my bungee i have ~700% bungee CPU usage and in console i have that packet: https://pastebin.com/4bG9cByD

**Comment by Janmm14** [comment]
maybe a zip bomb?

**Comment by GlobooX** [comment]
@Janmm14  What do You mean?

**Comment by MiMic10110** [comment]
@md-5 here is what is causing it. Good job @GlobooX

**Comment by GlobooX** [comment]
@ghacproductions Can You update HexagonMC?

**Comment by MiMic10110** [comment]
@md-5 Is there any way to disable it in previous version? 
I am using HexagonMC fork (I have some 1.7 "classic mc" servers) but it is 1 version behind :(

**Comment by md-5** [comment]
So you're not even using BungeeCord.

This tracker is for BungeeCord only.

**Comment by GlobooX** [comment]
@md-5 Yes, it was BungeeCord bug, becouse i try use normal BC to test and attacker using the same protocol to crash my server.

**Comment by pjorun** [comment]
@md_5 this bug exist on Bungee / Waterfall and HexagonMC. Today it will be test day. I'll let know about this issue.

**Comment by Xayanix** [comment]
@md-5 you are such a egoistic person, what if i tell you that this bug exist in BungeeCord since 2016?
I suggest you look at packetQueue array at ForgeClientHandler. 

`For all I know you've wasted my time with a bug that doesn't actually even exist in Bungee.`
kek

**Comment by md-5** [comment]
@Xayanix if you know the source of the bug then why not open a PR fixing it?

I spend hours and hours of my time to write this software for free (I spent more than six hours today working on 1.13), it is hardly much for me to ask that you are actually using my software and not a fork before opening a bug report.

**Comment by Xayanix** [comment]
I'm not hating you. I just don't like how you treat people here. Good luck with 1.13 and have a nice day ;)

**Comment by Fejm** [comment]
I recreated bot client based on your logs and found other issues inside bungee.

Should be fixed now.

https://github.com/SpigotMC/BungeeCord/commit/968916c0b83550961e96da858f4be29a81c785b8

**Comment by MiMic10110** [comment]
@Fejm 
Byte Array had maximum value while attack, so it will not help. The problem is when someone will sent 10000+ packets in one moment. Memory will be filled in instantly and a lot CPU will be taken due to java's garbage collector.

This channel between forge and server is broken and should be better programmed. Do not say it is not.
1. You do not have to be on the server to sent this packet (server is accepting this packet without player).
2. You can spam this packet. It should be sent when server will request it, else packet should be rejected.
3. Adding tons of checks will not help. The problem is in development stage. Listener works now like ping listener and this is sad..

**Comment by Fejm** [comment]
@MiMic10110 after these fixes i'm unable to crash bungee with 250 bots and packets spam while without patch it's possible to crash bungee with one bot.

And you are wrong. PluginMessage packet is on PLAY state so you need to full handshake to server. You can't send it without connected player.

Sorry, english is not so good.

**Comment by MiMic10110** [comment]
@Fejm Ok, if it is true, then good job, but really this packet should be sent after server request because it is just single message data.

**Comment by Black-Hole** [comment]
Next time the attacker might use 10000 bots. You can't mitigate that at the application layer. So you have to use a provider that is providing DDoS protection, escapecelly if you're running an offline server.

**Comment by Dimatert9** [comment]
@Black-Hole DDoS protections usually work only with layer 3/4. (Like OVH, Hetzner, Ddos-gurad), layer7 protection cost a lot of money, something like a 200-300$ per ip with 50-100Mbit. 
I think we can mitigate L7 attack, but need a good network speed and a good CPU.

You can check a my fork of bungeecord with built in antibot (captcha and GeoIp).

**Comment by MiMic10110** [comment]
@Black-Hole Just buy server with best anti-ddos protection. Like OVH's GAME servers. This antiddos is activating instantly on attack.

**Comment by Dimatert9** [comment]
@MiMic10110 OVH game antiddos does not protect from L7 attacks

**Comment by Black-Hole** [comment]
I can asure you that OVH is protecting against L7 attacks. There are special filters for Minecraft in place.

**Comment by Dimatert9** [comment]
Filters for minecraft only for UDP(Minecraft Bedrock, Query). For TCP there is no filters.

**Comment by Black-Hole** [comment]
You might have misread their firewall description. There is special firewall hardware for UDP attacks. Mitigating TCP attacks is much easier using filter rules. Look, I'm only a customer of OVH services, so I won't look up the pages where OVH describes their firewall in much detail.
There are DDoS attacks every now and then to the server I'm working for. Sometimes the server CPU will be stressed for up to 2 minutes. But after the DDoS protection kicks in, players can play without any lag or connection loss.
