### ISSUE TITLE
Another BungeeCord bug...

### ISSUE THREAD

**Issue by GlobooX** [SpigotMC/BungeeCord#2422]
@md-5 

14:10:02 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:88bacf1:1312

Another error with YOUR latest BungeeCord. 
Again... someone send packets or something and my BC is crashing..

Błąd wejścia/wyjścia ->Error Inpout/outpout

14:05:01 [SEVERE] Exception in thread "main" 
14:05:01 [SEVERE] java.io.IOException: Błąd wejścia/wyjścia
14:05:01 [SEVERE] 	at java.io.FileInputStream.read0(Native Method)
14:05:01 [SEVERE] 	at java.io.FileInputStream.read(FileInputStream.java:207)
14:05:01 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:169)
14:05:01 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:137)
14:05:01 [SEVERE] 	at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:246)
14:05:01 [SEVERE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:261)
14:05:01 [SEVERE] 	at jline.internal.InputStreamReader.read(InputStreamReader.java:198)
14:05:01 [SEVERE] 	at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2145)
14:05:01 [SEVERE] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2349)
14:05:01 [SEVERE] 	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2269)
14:05:01 [SEVERE] 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:61)
14:05:01 [SEVERE] 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by md-5** [comment]
That’s nothing to do with packets, that’s the input of your console closing, probably from your server panel....

**Comment by Dimatert9** [comment]
@GlobooX  Its like you run a bc not in screen session.
