### ISSUE TITLE
BungeeCord stuck

### ISSUE THREAD

**Issue by lxved** [SpigotMC/BungeeCord#2424]
Hello,

Could you please provide some assistance? I'm booting the BungeeCord server and it's been stuck for around 30 minutes now. I've tried constantly restarting, remove of plugins, updating of the JAR file and much more and it's still stuck.

Here is the log:

https://hastebin.com/orosuviyid.sql

**Comment by lxved** [comment]
Here is a hastebin link to better read the log:

https://hastebin.com/orosuviyid.sql

**Comment by Black-Hole** [comment]
Use the command "end" to stop BungeeCord.

**Comment by lxved** [comment]
I just did and nothing is happening anyways.

**Comment by HAlexTM** [comment]
This is an old issue, if you fixed it please **close the issue**.
If you still have problems, try disabling your plugins and enable one every restart until it's stuck again.
