### ISSUE TITLE
Commands Missing

### ISSUE THREAD

**Issue by dominikremes** [SpigotMC/BungeeCord#2425]
Hello. I have found out that some commands are missing (at least for me) and I can't switch between my servers. And I have tried this with the newest and some other builds and I have no idea why, but it doesn't recognize the /server command for a player but even for the bungee server. I'm sure that the player is connected trought Bungeecord server because the /bungee command works + the bungeecord console recognise the player. The same error is with the player list. Only the spigot one works.

**Comment by Fejm** [comment]
Delete modules.yml and check again

**Comment by dominikremes** [comment]
Still nothing changed. I get this message and the modules.yml regenerates to the same always

![image](https://user-images.githubusercontent.com/18899742/40005133-8787dace-5797-11e8-8a9f-b6a9b24f9393.png)

**Comment by Black-Hole** [comment]
Please use the Spigot forums for help configuring your antivirus program to not interfere with SSL connections opened by Java.

**Comment by dominikremes** [comment]
But I get this error even if I turn my firewalls down

**Comment by Janmm14** [comment]
Antivirus != Firewall

**Comment by Black-Hole** [comment]
Please use the forums for community support, it's not a BungeeCord issue if your SSL connections fails.

**Comment by Janmm14** [comment]
Temporary solution is to download the individual module jar files from https://ci.md-5.net/job/BungeeCord/ and put them into the modules folder.
