### ISSUE TITLE
How to run a bungeeCord command in spigot plugin

### ISSUE THREAD

**Issue by Xireu0** [SpigotMC/BungeeCord#2431]
don't work :(
I have plugin on bans down bungeecord
command is /bungeeban

@EventHandler
public void onJoin(PlayerJoinEvent){
  e.getPlayer().chat("/bungeeban xd hack"));
}

Help me

**Comment by Janmm14** [comment]
Use plugin message channels and a custom bungee plugin.
There are also plugins around providing such functionality.
More help can be given at the spigotmc.org forums, this issue tracker is meant for bugs inside bungeecord.
