### ISSUE TITLE
Bungeecord "You Are Already Connected To This Server" Error When i'm Not Connected To The Server

### ISSUE THREAD

**Issue by TheCoolCat92** [SpigotMC/BungeeCord#2438]

**Comment by TheCoolCat92** [comment]
Video Of Me Trying To Connect To servers: https://www.youtube.com/watch?v=WCR7XUID1S4&

**Comment by TheCoolCat92** [comment]
Help Would Be Really Appriciated :3

**Comment by TheCoolCat92** [comment]
Also I Am Using The Latest Spigot.jar and BungeeCord.jar

**Comment by CCCCarsten** [comment]
I have the same error.

**Comment by Janmm14** [comment]
Do you use bungeecord plugins?

**Comment by TheCoolCat92** [comment]
Nope

**Comment by HAlex** [comment]
1- You should write those issues on the SpigotMC forums
2- As we are already here... Can you post your `config.yml` (using [Pastebin](https://pastebin.com) or similar services)?

**Comment by TheCoolCat92** [comment]
Sure!

Bungeecord config.yml pastebin:
https://pastebin.com/WMCqYLJG

**Comment by HAlex** [comment]
The server address is set to the same value for every server
```
address: localhost:25566
```
You should at least change the port (`25566`) to the one that you've set in the other server.properties files

**Comment by TheCoolCat92** [comment]
Okay i'll try thanks
:D

**Comment by HAlex** [comment]
You're welcome! If you think that it's fixed you can close the issue

**Comment by TheCoolCat92** [comment]
Post Closed.
