### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by heroeminecratti** [SpigotMC/BungeeCord#2441]
So, when I delete everything, and I just open the bungeecord with a start.bat (java -jar bungeecord.jar), and edit the config, it works! When I turn off (with "end" not forced), it gives me this error:

21:06:21 [INFORMAZIONI] Using standard Java JCE cipher.
21:06:21 [INFORMAZIONI] Using standard Java compressor.
21:06:21 [INFORMAZIONI] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:76dc32e:1320
21:06:22 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
21:06:22 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
21:06:22 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
21:06:22 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
21:06:22 [INFORMAZIONI] Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
21:06:22 [INFORMAZIONI] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
21:06:24 [INFORMAZIONI] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:76dc32e:1320 by SpigotMC
21:06:24 [INFORMAZIONI] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:76dc32e:1320 by SpigotMC
21:06:24 [INFORMAZIONI] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:76dc32e:1320 by SpigotMC
21:06:24 [INFORMAZIONI] Loaded plugin BuycraftX version 10.6.2 by Buycraft
21:06:24 [INFORMAZIONI] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:76dc32e:1320 by SpigotMC
21:06:25 [INFORMAZIONI] Loaded plugin Pixelhub version 1.0 by YTKacperSKY
21:06:25 [INFORMAZIONI] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:76dc32e:1320 by SpigotMC
21:06:25 [INFORMAZIONI] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:76dc32e:1320 by SpigotMC
21:06:25 [INFORMAZIONI] Loaded plugin BungeeTabListPlus version 2.8.4 by CodeCrafter47
21:06:25 [GRAVE] Exception in thread "main"
21:06:25 [GRAVE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
21:06:25 [GRAVE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:69)
21:06:25 [GRAVE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:66)
21:06:25 [GRAVE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:268)
21:06:25 [GRAVE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56)
21:06:25 [GRAVE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
21:06:25 [GRAVE] Caused by: org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
21:06:25 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:254)
21:06:25 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58)
21:06:25 [GRAVE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:452)
21:06:25 [GRAVE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:66)
21:06:25 [GRAVE]     ... 4 more
21:06:25 [GRAVE] Caused by: java.nio.charset.MalformedInputException: Input length = 1
21:06:25 [GRAVE]     at java.nio.charset.CoderResult.throwException(Unknown Source)
21:06:25 [GRAVE]     at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
21:06:25 [GRAVE]     at sun.nio.cs.StreamDecoder.read(Unknown Source)
21:06:25 [GRAVE]     at java.io.InputStreamReader.read(Unknown Source)
21:06:25 [GRAVE]     at org.yaml.snakeyaml.reader.UnicodeReader.read(UnicodeReader.java:125)
21:06:25 [GRAVE]     at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:223)
21:06:25 [GRAVE]     ... 7 more

PLS HELP ME!

**Comment by md-5** [comment]
21:06:25 [GRAVE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for heLp
