### ISSUE TITLE
ProxiedPlayer#isConnected

### ISSUE THREAD

**Issue by tomocrafter** [SpigotMC/BungeeCord#2442]
Why I can't use ProxiedPlayer#isConnected (I know that actually Connection Interface) in the Scheduled Task?
It is always true because getPlayer only returns whether the ProxiedPlayer object at the time of acquisition is online or not.

**Comment by md-5** [comment]
What are you trying to ask exactly?
What is the bug?

**Comment by Janmm14** [comment]
isConnected method is there in case you have cached ProxiedPlayer instances somewhere
