### ISSUE TITLE
IllegalArgumentException: Unknown meta type 14 when spawning dinosaur entities from jurassicraft

### ISSUE THREAD

**Issue by Wyn-Price** [SpigotMC/BungeeCord#2443]
Original issue [here](https://github.com/JurassiCraftTeam/JurassiCraft2/issues/317). From talking to the user in private, it seems like spawning any dinosaurs entity causes this issue to be thrown.    This is on 1.12.2. Stacktrace: https://hastebin.com/oyorakedoq.md
Afaik, jurassicraft dosnt do anything too crazy with the dinosaur entities, but if you have any questions about anything then I'll be happy to answer.

**Comment by md-5** [comment]
The mod has modified the Minecraft protocol.
Bungee does not write mod specific code, so this won’t be fixed.
The mide should make use of the existing protocol, or extend it in a supported manner via plugin messages
