### ISSUE TITLE
Chat and commands don't work inside of default server

### ISSUE THREAD

**Issue by Juan010** [SpigotMC/BungeeCord#2444]
I have 4 Servers, all connected through bungeecord and in the same VPS. What happens is that, two of them are game modes, one is a lobby and the other one, a prelobby. As far as I know, the regular Lobby works great as a default forced server, but I decided to make a pre lobby so players could log in there (2FA) and I wouldn't need a bridge or something. This prelobby works great as a server, but when set as default, commands just don't run. Chat doesn't work either. Nothing in server's console, nothing in bungee's console. What should I do?

**Comment by Black-Hole** [comment]
For community support please use the Spigot forums. There you should post more details, like plugin lists and server configurations.
