### ISSUE TITLE
[Feature Req] Split compress rate config to client and server sides

### ISSUE THREAD

**Issue by caoli5288** [SpigotMC/BungeeCord#2445]
Seems the deflate method was the most heavy method when players up to 1000+.
I suggest new config options to ctrl the compress rate and level in bungee to spigot connection. 
THX

**Comment by i9hdkill** [comment]
That could be the case. Could you attach the measurements you did to find out?

**Comment by Janmm14** [comment]
Bungee to Spigot compression threshold can be set up in each spigot server's server.properties file I think.

**Comment by caoli5288** [comment]
@Janmm14 It's only spigot to bungee not bungee to spigot:-(

**Comment by caoli5288** [comment]
@Janmm14 I'm not very sure bungeecord  will not set compress by it self. I'll review it tomorrow

**Comment by caoli5288** [comment]
![201874153516](https://user-images.githubusercontent.com/3120587/42263228-f743feda-7f9f-11e8-9b3a-04d29328fec0.png)
@Janmm14 Shown that bungeecord will compress streams even spigot disable compress

**Comment by md-5** [comment]
That screenshot is meaningless, the compressor always has to be set up in the pipeline to handle the protocol.

BungeeCord will respect the network_compression_threshold in its config.yml, and Spigot will respect network-compression-threshold in server.properties.

**Comment by caoli5288** [comment]
@md-5 Yes
But,
Event spigot set network_compression_threshold to 0
bungeecord compress packet which sent to spigot if config.yml's kept > 0. Isn't it? :)

**Comment by Janmm14** [comment]
@caoli5288 
Compression threshold of 0 will compress all packets. To disable you need -1, which will then remove the packet compressor and packetdecompressor:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java#L133

Here the compressaion threshold for user <-> bungee is set:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L501

Here compression threshold for bungee <-> server is set:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L473

**Comment by caoli5288** [comment]
@Janmm14 Yes.
It's shared one config option. and compress level set to -1(default to 6 in zlib).
I think all of these should be configurable(threshold in user side, spigot server side and it's compress level).

**Comment by Janmm14** [comment]
@caoli5288
I am not talking about zlib compression level, but the compression threshold.

The code I linked shows that the compression threshold for the "server" channel is set based on the recieved SetCompression packet.

As you apparantly are not experienced enough with java and/or bungee code, I suggest taking a further look at it.

Bungee does everything correct.

**Comment by Janmm14** [comment]
>The compressor what "bungee <-> player" and "bungee <-> spigot" shared same threshold options in config.yml. what I said at first.

This is wrong. I proved with my code excerpts that compression threshold of "bungee <-> spigot" is set by spigot and correctly applied by bungee.

**Comment by caoli5288** [comment]
@Janmm14 THx, but I still want bungeecord manage it just by edit config.yml and greload
not very a lot server.properties and restart server

**Comment by Janmm14** [comment]
@caoli5288 This would violate the protocol specifications and likely there are also sanity checks present in vanilla server which are then also present in spigot which would disconnect in case the compression threshold is not honored correctly.

**Comment by sachk** [comment]
What's the current status on this? I'd really like an option to set the zlib compression level in the config.

**Comment by Janmm14** [comment]
Read my last comment.

Its also possivle to use tool commanss like sed with **/server.properties on linux to change compression level
