### ISSUE TITLE
BungeeCord error Protocol.

### ISSUE THREAD

**Issue by naio75** [SpigotMC/BungeeCord#2452]
Hello I have an error when I try to go on my waiter Survival 1.12. Thus it shows me an error: http://www.noelshack.com/2018-27-7-1531076679-help.png

My waiter is of base of the version 1.8 in 1.12.2 to go to the lobby and when I want to go on survival 1.12 his does not walk and display the error :/

What's to be done? Thank you for your answers ^^ :D

**Comment by naio75** [comment]
(I am french ^^')

**Comment by Black-Hole** [comment]
For help configuring your server and your plugins please use the Spigot forums. This issue tracker is not for support.
