### ISSUE TITLE
Bungee cord Please help

### ISSUE THREAD

**Issue by TheSavageDJ** [SpigotMC/BungeeCord#2454]
08.07 22:19:26 [Multicraft] Received start command
08.07 22:19:26 [Multicraft] Loading server properties
08.07 22:19:26 [Multicraft] Starting server!
08.07 22:19:26 [Multicraft] Loaded config for "BungeeCord"
08.07 22:19:26 [Multicraft] Updating eula.txt file
08.07 22:19:27 [Server] INFO Using mbed TLS based native cipher.
08.07 22:19:27 [Server] INFO Using zlib based native compressor.
08.07 22:19:27 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:730715e:1321
08.07 22:19:27 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
08.07 22:19:27 [Server] INFO Epoll is working, utilising it!
08.07 22:19:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
08.07 22:19:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
08.07 22:19:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
08.07 22:19:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
08.07 22:19:27 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
08.07 22:19:27 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
08.07 22:19:27 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:730715e:1321 by SpigotMC
08.07 22:19:27 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:730715e:1321 by SpigotMC
08.07 22:19:27 [Server] INFO Loaded plugin SlashServer version 3 by Bloodsplat
08.07 22:19:27 [Server] INFO Loaded plugin BungeeReport version 1.0 by Inkzzz
08.07 22:43:21 [Multicraft] Received stop command
08.07 22:43:21 [Multicraft] Stopping server!
08.07 22:44:14 [Multicraft] Received stop command
08.07 22:44:22 [Multicraft] Terminating server via signal
08.07 22:44:22 [Multicraft] Server shut down (terminating)
08.07 22:44:22 [Multicraft] Looks like a crash, check the server console. Return value: 143
08.07 22:44:22 [Multicraft] Server stopped
08.07 22:47:10 [Multicraft] Received start command
08.07 22:47:10 [Multicraft] Loading server properties
08.07 22:47:10 [Multicraft] Starting server!
08.07 22:47:10 [Multicraft] Loaded config for "BungeeCord"
08.07 22:47:10 [Multicraft] Updating eula.txt file
08.07 22:47:10 [Server] INFO Using mbed TLS based native cipher.
08.07 22:47:10 [Server] INFO Using zlib based native compressor.
08.07 22:47:10 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.12-SNAPSHOT:730715e:1321
08.07 22:47:11 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
08.07 22:47:11 [Server] INFO Epoll is working, utilising it!
08.07 22:47:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
08.07 22:47:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
08.07 22:47:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
08.07 22:47:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
08.07 22:47:11 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
08.07 22:47:11 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
08.07 22:47:11 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:730715e:1321 by SpigotMC
08.07 22:47:11 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:730715e:1321 by SpigotMC
08.07 22:47:11 [Server] INFO Loaded plugin SlashServer version 3 by Bloodsplat
08.07 22:47:11 [Server] INFO Loaded plugin ViaVersion version 1.3.0 by _MylesC, Matsv

**Comment by md-5** [comment]
Please use the forums for support.
ViaVersion is not supported and multicraft may be causing issues

**Comment by TheSavageDJ** [comment]
Could i have the link to forums?

**Comment by md-5** [comment]
spigotmc.org
