### ISSUE TITLE
TextComponent loses its color when in another line

### ISSUE THREAD

**Issue by DanielAlves123** [SpigotMC/BungeeCord#2459]
When you send TextComponent to player and the message is long enough to be splitted to other line, the other one will lose color code and will be white.

**Comment by Black-Hole** [comment]
That's a vanilla issue. Text component don't support multi line texts with legacy color codes.
To work around this issue don't use color codes in text components but instead formatting like .color()

For help doing so please use the community support of the Spigot forums.

**Comment by md-5** [comment]
Feel like we should start throwing exceptions when legacy and components are mixed. Should never ever be done.

**Comment by Mystiflow** [comment]
@md-5 I think that would break action bars, they need legacy colors to show colors at all
