### ISSUE TITLE
IOBE - #1326

### ISSUE THREAD

**Issue by JamieSinn** [SpigotMC/BungeeCord#2463]
https://pastebin.com/raw/GzXSSgu1

What causes this? Updating to 1329 now.

**Comment by Janmm14** [comment]
first guess: invalid data sent

**Comment by JamieSinn** [comment]
Yeah, that's my assumption too. Likely a hacked client or something weird.

**Comment by JamieSinn** [comment]
Haven't seen recently. Closing as it was likely a hacked client.
