### ISSUE TITLE
WARNING: Illegal reflective access by org.yaml.snakeyaml.introspector.PropertyUtils (file:/C:/Servers/bungee/BungeeCord.jar

### ISSUE THREAD

**Issue by Quirkylee** [SpigotMC/BungeeCord#2465]
I am running java 10 and got this error:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.yaml.snakeyaml.introspector.PropertyUtils (file:/C:/Servers/bungee/BungeeCord.jar) to method java.beans.FeatureDescriptor.isTransient()
WARNING: Please consider reporting this to the maintainers of org.yaml.snakeyaml.introspector.PropertyUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by md-5** [comment]
It's a warning in a third party library we use.
Bungee cannot fix it (and it doesn't affect anything)

**Comment by Mystiflow** [comment]
This is fixed in SnakeYAML 1.20 and later

**Comment by md-5** [comment]
Almost guaranteed it will just be replaced by another warning, but SnakeYaml needed an updated anyway
