### ISSUE TITLE
error login in with 1.13-pre7

### ISSUE THREAD

**Issue by thunderlight411** [SpigotMC/BungeeCord#2468]
i have added a spigot-1.13-pre7 as a test server in my network.
and added the server in the configuration in the priorities list as i have done before.

when i join with 1.12.2 everything is working fine.
but when i'm trying to join with 1.13-Pre7 i got the following error messages [https://i.imgur.com/WE71hs8.png](https://i.imgur.com/WE71hs8.png)

i have tried to disable all the addons to test if that makes a difference but 
i cannot find any information on the spigot servers self ( no information in logfiles) except on the bungeecord.

BungeeCord Config : https://pastebin.com/m2mVQVE2
BungeeCord Log : https://pastebin.com/tUGqCvjN

why i switch the priorities list for 1.13-pre7 first and 1.12.2 server second i got the same issue.
exept that 1.13-pre7 is working well but got the error with a 1.12.2 client.

i hope that this can be fixed so we can use both versions in the network.

**Comment by md-5** [comment]
This is fixed in pre9

https://bugs.mojang.com/browse/MC-131822
