### ISSUE TITLE
Vanilla 1.13 Not working with Bungeecord latest

### ISSUE THREAD

**Issue by Lvnvceo** [SpigotMC/BungeeCord#2470]
I tried setting up a minecraft server running 1.13 locally with my own machines. I setup everything and then when I connect to it from the lobby servers. It gives me that error in bungeecord.

https://pastebin.com/1MhhL3q1

**Comment by lululombard** [comment]
Yes, because it doesn't support 1.13 right now. You might give a shot at ViaVersion dev builds. https://ci.viaversion.com/job/ViaVersion-DEV/

**Comment by nilsbrychzy** [comment]
#2471
