### ISSUE TITLE
/glist bungeecord crashes

### ISSUE THREAD

**Issue by TheBigDude5** [SpigotMC/BungeeCord#2475]
Hello. I havent been on my server for like a day didnt touch anything it was working fine a week ago. I had not touched anything in bungeecord at all. and now when I type/glist It crashes bungeecord not sure why any help will be great! thank you

**Comment by i9hdkill** [comment]
Hi,
we can't help you without the actual bungeelog or error.

Please create a topic here as I am sure this isn't a actual bug in bungee:
https://www.spigotmc.org/forums/bungeecord-help.70/

This tracker is only for actual bugs

**Comment by TheBigDude5** [comment]
It doesnt say anything in console about an error
