### ISSUE TITLE
Fishing Rod not rendering after server switch.

### ISSUE THREAD

**Issue by KingHorse2015** [SpigotMC/BungeeCord#2477]
Today I installed the a new version of bungeecord to support 1.13. 

My hub server is 1.12.2 spigot with viaversion
My survival server is 1.13 spigot, no plugins

But if I start at the hub server and switch to the survival server and want to try a fishing rod. The only thing that happens is the sounds it makes. not lead, bob, or fishing that come.
But when I log off at the survival server, and reconnect I can use the fishing rod without problems.

I tested the following things:
Normal vanilla server 1.13 - No bungee: Ok
Spigot server 1.13 - No bungee: Ok
Spigot server 1.13 - Bungee direct connect: Ok
Spigot server 1.13 - Bungee indirect connect: Not working. (Switching back and forward doesnt change it)

**Comment by ForceUpdate1** [comment]
Hello, i have the same problem. Have you try it without viaversion on the hub server

**Comment by KingHorse2015** [comment]
Thanks for the tip. I changed it, but what the fishing rod works, but the line is not rendered.
![2018-07-22_16 29 13](https://user-images.githubusercontent.com/15171668/43046677-a1447768-8dcc-11e8-935b-b0e2d627b42a.png)
