### ISSUE TITLE
No tab completes for BungeeCord commands (1.13)

### ISSUE THREAD

**Issue by ME1312** [SpigotMC/BungeeCord#2479]
BungeeCord commands are not declared for 1.13 players, so there's no tab completion for bungeecord  commands.

**Comment by SimonOrJ** [comment]
I want to add that BungeeCord commands were not declared in the previous versions as well.  I tried looking into this on [my fork](https://github.com/SpigotMC/BungeeCord/compare/master...SimonOrJ:master) for 1.13, but I didn't know what the proper way to add `com.mojang.brigadier` into the repository is

**Comment by ME1312** [comment]
I'm only suggesting that the commands be declared in a similar fashion to Spigot 1.13 at this time (possibly through intercepting and adding to the packet).

Is that enough to cause legal issues?

**Comment by Selebrator** [comment]
As far as I can tell brigadier is open source. You can download the source here: https://libraries.minecraft.net/com/mojang/brigadier/0.1.27/brigadier-0.1.27-sources.jar

**Comment by md-5** [comment]
Source available != open source.

**Comment by Janmm14** [comment]
I hope its true
https://twitter.com/timmyRSde/status/1023483575142965249

**Comment by SagenKoder** [comment]
I temporarily fixed this issue with no tabcomplete in bungee by coding dummy commands in spigot that handle the tabcomplete.

Example:

https://github.com/BlueLapiz/BlueLapizSource/blob/master/modules/BlueLapiz-Core/src/net/bluelapiz/core/command/DummyEvidenceCommand.java

**Comment by Kaan2106** [comment]
Any updates / fixes avaiable?

**Comment by KennyTV** [comment]
I dont know if this adds any new information, but even suggestions added during the TabComplete event are just ignored. Really hoping for a fix, if there is one

**Comment by KennyTV** [comment]
@md-5 its actually been made public today https://twitter.com/Dinnerbone/status/1044870699465216001
https://github.com/Mojang/brigadier

**Comment by Phreag** [comment]
Having this issue as well.
Looking forward to a fix :)

**Comment by Phreag** [comment]
push :P

**Comment by md-5** [comment]
Right, I've been working on this, but its a hideously complex system.

Current status is that BungeeCord commands which don't exist on the server are injected, but not much else. Close to 1000 lines of admittedly pretty messy code just to get this far.

![2018-12-19_16 33 00](https://user-images.githubusercontent.com/1007849/50200824-c15e8980-03ab-11e9-89aa-bab61c4a9d7d.png)

Once tab completion is working it will be pushed under a config option for testing.
