### ISSUE TITLE
BungeeCord resulting in 1.13 Entity display Error?

### ISSUE THREAD

**Issue by Mgazul** [SpigotMC/BungeeCord#2481]
BungeeCord-1338
Spigot：git-Spigot-ed1cec9-1c7adf7 (MC: 1.13)
plugins: No plugins
error：
1.When I throw a fishing rod, the fishing line and the hook are invisible.
2.When I ride anything, I can't see the state myself, but other players can see that I have already taken the ride, and holding the shift can still leave the mount.
3.Elytra and fireworks rockets are not working properly.

I tried to build a spigot server separately. The above problem does not exist. When I connect to BungeeCord, the problem occurs.

**Comment by md-5** [comment]
https://github.com/SpigotMC/BungeeCord/issues/2477
