### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Ironic8b498** [SpigotMC/BungeeCord#2485]
Bungeecord 1341
spigot 1.13 

I get this message when I try to log into my test server on the network

Internal Exception: io.handler.codec.DecoderException: com.google.gson.JsonSytaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 2 path $

**Comment by md-5** [comment]
Needs more information.
e.g. full stack traces, logs, affect maps, reproduction without plugins, etc.

I don't know how you expect me to do anything based off the information in this ticket - spigot 1.13 is not even a version.

**Comment by Ironic8b498** [comment]
bungee plugin?
or spigot?

**Comment by md-5** [comment]
Probably bungee.

In any case, you need to reproduce this on a completely clean setup, or if it is an issue with your world, then you need to attach that world.

**Comment by Ironic8b498** [comment]
you was right, I had crash course on how to read the stack reports, bungeetablistplus was causing the issue, they have fix it already.
