### ISSUE TITLE
Bungeecord Config Error 

### ISSUE THREAD

**Issue by TheCoolCat92** [SpigotMC/BungeeCord#2488]
Bungeecord Config: https://pastebin.com/ztizc4EH

Bungeecord Console: https://pastebin.com/nQWBybiK

**Fix Would Be Really Appriciated!**

**Comment by SimonOrJ** [comment]
Lines 22 and 26 are not indented properly. They should be in line with two spaces, not one.

```
19:20:48 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
...
19:20:48 [SEVERE] Caused by: while parsing a block mapping
 in 'reader', line 1, column 1:
    forge_support: true
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 22, column 2:
     factions:
     ^
```

YAML files are space-sensitive, and wrong indentation will cause error like what you see.  As this is not a bug, use the spigot forums next time.

**Comment by Janmm14** [comment]
@TheCoolCat92
_**You apparantly don't even bother reading he first line, where it says that it is not a bug and a configuration issue.**_ This is really sad.

**Comment by TheCoolCat92** [comment]
Thank You I Reset My Config And Used A Yaml Parser With The Old One <3
