### ISSUE TITLE
Spawning mobs on forge?

### ISSUE THREAD

**Issue by Ironic8b498** [SpigotMC/BungeeCord#2491]
When I spawn a Dino in JurassiCraft-1.12.2-2.1.12 this is my error https://hastebin.com/detefaviyi.md

Can you please explain whats at fault and how to fix, I will forward your answer to the developers of JurassiCraft.

**Comment by ApocalypsjeNL** [comment]
The mod modified the MC protocol, so BungesCord doesn't understand it

**Comment by Janmm14** [comment]
BungeeCord currently cannot support custom meta information sent via meta channels. Plugin-related communication should be done through the plugin message packet.
