### ISSUE TITLE
Bungeecord 1.8 1.13 issue

### ISSUE THREAD

**Issue by UnNamedAndre** [SpigotMC/BungeeCord#2492]
i have the last version on bungee and viaversion installed on it.(bungee) but with 1.13 if a player joins the server, on bungee’s console appears this:
https://pastebin.com/89mTisSX

and players see this: https://prntscr.com/kcgogy

**Comment by md-5** [comment]
Viaversion is not supported

**Comment by UnNamedAndre** [comment]
what i have to use to allow players join from 1.8.X to 1.13.X?

**Comment by UnNamedAndre** [comment]
i can use it only on bungee, on spigotservers i can’t cause i have 1.12+ spigot version and protocolsupport..

**Comment by md-5** [comment]
We only support single version servers - issues like this are generally caused by ViaVersion etc
