### ISSUE TITLE
[Idea] - Adding an event listener for when a bungee-connected server goes online and offline.

### ISSUE THREAD

**Issue by TheFlash787** [SpigotMC/BungeeCord#2493]
Hey!

I feel that having an event that listens for when a server goes offline and online would really help refine the API as developers can accurately detect when a server changes state and can use it in upcoming plugins/systems. I am currently running 1.12 and using a ping detection every X minutes is very inaccurate and does not cut it unfortunately.

I am unable to produce a PR for this however would definitely like to see this implemented very soon.

Thank you.

**Comment by md-5** [comment]
How would this work?
Bungee itself would just have to ping the server...

**Comment by TheFlash787** [comment]
Maybe theres some way for Bungee to have more interaction with the servers? (deeper connectivity). This is nothing concrete, no PRs. Just an idea. That's all.

**Comment by md-5** [comment]
No, bungee should work essentially with an unmodified server.
If you want to build up communication with the servers then you need a message queue.

I'm closing this because its outside of the scope of the project to do more than ping every X minutes.
