### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by LoXR** [SpigotMC/BungeeCord#2499]
When players connect (also in bot attacks) this error pops up: https://pastebin.com/BzbDdycH

BungeeCord: Build #1344

**Comment by Janmm14** [comment]
are you sure a player attemtped to connectand no bot in that error?

**Comment by LoXR** [comment]
I can admit, that was during a bott attack. Will send another one when a player joins.

**Comment by LoXR** [comment]
Normal players: https://pastebin.com/vNied7Fk

**Comment by md-5** [comment]
Are you using ViaVersion or ProtocolSupport or similar?

**Comment by md-5** [comment]
I see "INFO Injected Player" in your logs which is concerning and suggests a plugin similar to the above.
Please reproduce without such plugins.

**Comment by Leymooo** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L139

This error will always trigerred when any tcp packet will be sent. like http.
```
java.lang.IllegalArgumentException: Unexpected packet received during login process!
4554202f726f626f74732e74787420485454502f312e310d0a486f73743a206c75636b796d632e72753a32353536350d0a436f6e6e656374696f6e3a204b6565
```
![image](https://user-images.githubusercontent.com/8667294/43456610-d28fe260-94cc-11e8-8549-a8e5f31bdfcf.png)

**Comment by Janmm14** [comment]
Then report it to viaversion. This is no bungeecord issue. @LoXR
