### ISSUE TITLE
BungeeCord with HAProxy... Is that possible ?

### ISSUE THREAD

**Issue by CallMeGhosty** [SpigotMC/BungeeCord#2500]
I want to use a HAProxy to check which lobby is the most available when a player connects through the BungeeCord. I tried a lot of ways ( changing bungee's config.yml, changing etc/haproxy/haproxy.cfg from the ubuntu server ), but everytime I tried to connect it kicked me for "Disconnected" and nothing showing in the logs.

Currently, I am running:

1 HAProxy -->
- on a virtual machine ( at least trying to =]] )

1 BungeeCord Proxy --> 
- 1 single plugin ( BungeeAuthMeBridge ),
- 0 modules
- Only edited the [config.yml](https://pastebin.com/rqNQZTJp)
- Running on port 25565

2 Lobbies -->
- They are exactly the same, excepting the port being different
- [Spigot 1.12.2](https://yivesmirror.com/grab/spigot/spigot-1.12.2-R0.1-SNAPSHOT-b1648.jar)
- 3 plugins ( ServerSelectorX, AuthMe & AuthMeBridge )
- The first lobby is running on port 25567
- The second one is running on port 25569.

1 Gamemode --> 
- Survival in BungeeCord's config.yml
- It's just an fresh, automatically generated world
- No plugins
- I named it Survival because I wanted to test ServerSelectorX.

**Note: All servers / proxies are running on localhost!**

I don't know what should I put in haproxy.cfg, I looked on the internet, but there's no haproxy.cfg ( at least an explanation about it ) for Minecraft Servers... Don't understand me wrong, I know how to configure Minecraft Servers, but HAProxy gives me headaches..

So I just need a haproxy.cfg and maybe some things changed in bungee's config.yml ( like proxy_protocol ).

Have a nice day.

**Comment by md-5** [comment]
This is a bug tracker, not support forum.

HAproxy sounds like the wrong tool to use here anyway, you need a bungee lobby rotator plugin
