### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by fikawka** [SpigotMC/BungeeCord#2504]
Hello, one person is crashing the server (BungeeCord) on one server (not mine but the same person scrashed the same server) recorded the video on which you can see how the server is crashing

https://www.youtube.com/watch?v=grHLEinF3JE

**Comment by Black-Hole** [comment]
The quality of the video is that bad that all you can see is some lag counter counting up.

Please descripe the issue with more details like log files of your BungeeCord server, used version of BungeeCord and the Spigot servers, plugins used on BungeeCord and Spigot.

**Comment by fikawka** [comment]
PaperSpigot 1.8.8 BungeeCord 1.13

**Comment by Leymooo** [comment]
Log files? Crash reports? Any errors?
