### ISSUE TITLE
Server is online mode!

### ISSUE THREAD

**Issue by ICBPlayz** [SpigotMC/BungeeCord#2505]
Hello, I have a bungeecord server using spigot but every time I try to join it says "Exception Connecting:RuntimeException : Server is online mode! @ net.md_5.bungee.ServerConnector:291" I have seen loads of threads about this but none of them have helped.

BungeeCord config: https://pastebin.com/pMZKSy9s
Server.properties: https://pastebin.com/ckKQR53f
Spigot.yml: https://pastebin.com/4BNgL2ke
Bukkit.yml: https://pastebin.com/MYVYw2Ej

**Comment by md-5** [comment]
address: localhost:25565
  host: 0.0.0.0:25565

You're connecting bungee to itself...
You need to fix your config

**Comment by ICBPlayz** [comment]
Didn't work

**Comment by Black-Hole** [comment]
Please use the Spigot forums for support.
