### ISSUE TITLE
Update Trove to 3.1?

### ISSUE THREAD

**Issue by Mystiflow** [SpigotMC/BungeeCord#2506]
Trove hasn't had a major release published to mvnrepository since 2012.

Just recently, however, the author has pushed an update with various commits since then:

https://mvnrepository.com/artifact/net.sf.trove4j/core/3.1.0
https://bitbucket.org/trove4j/trove/issues/64/31-release

Could an update be considered?

**Comment by md-5** [comment]
First update in 6 years?
Might be worth waiting a bit, I don't think there's any killer issues with the current version.

**Comment by md-5** [comment]
378aaadb687d4ffb06bfb31c95de6f42d8e95481
