### ISSUE TITLE
PreLoginEvent Connection UUID always null

### ISSUE THREAD

**Issue by pffffffff** [SpigotMC/BungeeCord#2510]
I'm trying to get the player's UUID in the PreLoginEvent and it's always null. The build I'm using is 1348. The BungeeCord is set to online mode.

**Comment by Janmm14** [comment]
That is intended and completely normal.

**Comment by pffffffff** [comment]
Then why is it available to use? How am I meant to get their UUID?

**Comment by Janmm14** [comment]
@pffffffff In the `LoginEvent`
