### ISSUE TITLE
InetSocketAddress.getAddress is null in DownstreamBridge at ServerIP PMC command

### ISSUE THREAD

**Issue by Foorack** [SpigotMC/BungeeCord#2513]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L438

InetAddress.getAddress() returns null

**Comment by Janmm14** [comment]
Although it won't change anything probably I suggest you to show the actual stack trace

**Comment by Janmm14** [comment]
That position of the downstream bridge doesn't create fullblown crashes.

**Comment by md-5** [comment]
Please actually try and write a proper bug report, rather than just say "its null"
