### ISSUE TITLE
ChatEvent does not block commands if event.isCanceled(true);

### ISSUE THREAD

**Issue by BoomEaro** [SpigotMC/BungeeCord#2517]
For example, this code does not block the command, that is, the event is blocked, but the command is still sent:

	@EventHandler(priority = 64)
	public void onChatEvent(ChatEvent e) {
		if (e.isCancelled() == true) {
			return;
		}
		if (e.isCommand() == true) {
			if (e.getMessage().equals("/test1")) {
				e.setCancelled(true);
				ProxyServer.getInstance().getLogger().info("Event is canceled: " + e.isCancelled());
			}
		}
		else {
			if (e.getMessage().equals("test2")) {
				e.setCancelled(true);
				ProxyServer.getInstance().getLogger().info("Event is canceled: " + e.isCancelled());
			}
		}
         }
Latest version BungeeCord.
As a result, it turns out that the command is sent, and the message is not. The only way to block a command is to set an empty message.

So it is conceived or is it a bug?

**Comment by Paulomart** [comment]
I think another plugin is interfering with the event. Have you only one plugin installed?

**Comment by Janmm14** [comment]
Another plugin might use the chat event with a lower priority, lower priority gets executed earlier.

Apart fro mthat your code stile is a little unusual.

**Comment by BoomEaro** [comment]
Yes, you are right, another plugin (CmdBlock), for some reason always sets the canceling of the event to be false. I do not know why I forgot to take into account that I have several more plugins :)
Thanks for the help :)

p.s I'm new to Java.
