### ISSUE TITLE
Plugin Messaging is failing

### ISSUE THREAD

**Issue by L4BORG** [SpigotMC/BungeeCord#2526]
https://github.com/parallelblock/NuVotifier/issues/96

I'm assuming it's because data is sent too fast? Or too often?

serverInfo.sendData(channelName, data.getBytes(StandardCharsets.UTF_8), false)

would even return true, but no data ever comes to spigot server, sometimes restarting spigot server helps other times it doesn't...

**Comment by L4BORG** [comment]
Latest BungeeCord and NuVotifier, but I've tested many old versions (of Bungee and NuVotifier) and it didn't help, the issue is preset for at least a few months now...

**Comment by md-5** [comment]
"NuVotifier" not a valid channel name for 1.13 servers.

Must be namespace:key format

**Comment by L4BORG** [comment]
The issue is also present with lower case channel name for example "nuvotifier" or "votifier".

**Comment by L4BORG** [comment]
Also I'm not sure if you read the whole issue but the problem is plugin messaging would work... then after some time it would randomly stop working.

**Comment by md-5** [comment]
>The issue is also present with lower case channel name for example "nuvotifier" or "votifier".

Still not valid.

Needs to be "votifier:vote" or something to that effect

**Comment by L4BORG** [comment]
I see, apparently I missed that. Will fix and test again, thanks!
