### ISSUE TITLE
Could not connect to a default of fallback server

### ISSUE THREAD

**Issue by XxMCcraftxX** [SpigotMC/BungeeCord#2528]
Every time when I try to join my Bungeecord server it says: **Could not connect to a default of fallback server**… 
![2018-09-15_15 43 51](https://user-images.githubusercontent.com/43296387/45586906-50b45680-b8fe-11e8-8b89-54c5b4da0d30.png)
I have no idea what I've done wrong and how to fix this. Here's my 
[Config.zip](https://github.com/SpigotMC/BungeeCord/files/2385734/Config.zip)
config.yml
I had to do it in a ZIP file. If you know how to fix this, please let me know =D

**Comment by Mystiflow** [comment]
Put your config.yml on pastebin.com and post the link here. But you should really be posting this on forums anyway at spigotmc.org

**Comment by XxMCcraftxX** [comment]
I cant login to pastebin
:(

**Comment by Mystiflow** [comment]
You don't need to?...
gist.github.com then?
