### ISSUE TITLE
Failing to connect to one server when using local ip, but another works fine.

### ISSUE THREAD

**Issue by dimwit105** [SpigotMC/BungeeCord#2531]
I have multiple servers running on VMs, with bungeecord to connect them all.

Currently there are two servers, when configured like this:
`servers:
  lobby:
    motd: '&1Welcome to the Hub!'
    address: 75.187.181.176:30000
    restricted: false
  factions:
    motd: '&1Welcome to Factions!'
    address: 192.168.0.130:30001
    restricted: false`

players connect to the lobby no problem, and can switch to the factions server (which is on the same network) without issue.

However, when configured like this
`servers:
  lobby:
    motd: '&1Welcome to the Hub!'
    address: 192.168.0.129:30000
    restricted: false
  factions:
    motd: '&1Welcome to Factions!'
    address: 192.168.0.130:30001
    restricted: false`

Players will fail to connect to the lobby, but successfully connect to factions.

Both servers are identical clones, being freshly copied off a template, running the latest version of spigot.

The first time this happened, bungee complained about outdated clients to the lobby, but after some attempted troubleshooting on my end, it simply sends them to factions without an error message.

**Comment by md-5** [comment]
This is likely a configuration issue and not a bug. Please try using the forums for support.
