### ISSUE TITLE
Unsure if Bungee's doing or not.

### ISSUE THREAD

**Issue by bigbluu722** [SpigotMC/BungeeCord#2536]
Hey there, having an issue connecting to my server as of recent but I believe it's the doing of bungee as every time someone logs in, this is thrown in the bungee console: 

`[<username] disconnected with: Authentication required. `

Not sure how to really deal with it as I haven't found anything on google or the spigotmc forums on the issue and it leads me to believe it's bungee related due to the fact players logging in don't even make it to the hub server before being kicked so the only trace of them attempting to login is thru bungee. Any help on the situation would be appreciated.

BungeCord Version: Build #1358

-V

**Comment by Janmm14** [comment]
Does it happen to yourself?
Maybe the players tried joining with cracked minecraft, maybe you have prevent_proxy_connections on.

**Comment by bigbluu722** [comment]
It's any player that attempts to join overall whether cracked or premium on online or offline. Prevent proxy connections is also off so I don't believe that's the issue. 
-V

**Comment by md-5** [comment]
This message is not from BungeeCord

https://github.com/SpigotMC/BungeeCord/search?q=Authentication+required&unscoped_q=Authentication+required

It is likely from a security type plugin

**Comment by bigbluu722** [comment]
We don't have any security plugins aside from authme though, and it only happens when we're running things thru bungee. 
-V

**Comment by Janmm14** [comment]
Its still not from bungee.
