### ISSUE TITLE
Backup Server (Limbo)

### ISSUE THREAD

**Issue by Dancbeunny98** [SpigotMC/BungeeCord#2541]
I want it to be like this

I have a Bungee server bundle (Auth, Lobby, and other servers) I want to make sure that if any server is turned off, people transfer people to a dedicated server, and from there they will continue to play where they want through the authorization server...
_____________________________________
Help pls...)))

**Comment by Fejm** [comment]
Please use forums to get help: https://www.spigotmc.org/forums/bungeecord-help.70/

**Comment by Dancbeunny98** [comment]
They could not help me. I will try again and again! Thank..

**Comment by md-5** [comment]
I'm not sure what you're asking for .
Bungee will transfer people back to the fallback server if it dies, and a plugin like movemenow can do that if they're kicked also
