### ISSUE TITLE
Another Bungee Plugin Messaging Channel Problem

### ISSUE THREAD

**Issue by vincygit** [SpigotMC/BungeeCord#2545]
Hi, I'm here to talk about a bug found on the Bukkit / Bungee Plugin Messaging Channel, I discovered this bug a couple of months ago with a friend while we were studying the operation of the Messaging Channel.
In a nutshell I found that: using an old build of bungeecord (> 1000) you can use the DataOutputStream to send messages to plugins on spigot even passing through another bungeecord proxy.

How it works \/
LocalBungee OLD BUILD with AuthmeBridge > Target Bungee> Target Spigot with AuthmeBridge.

Example:
```
  ByteArrayOutputStream stm = new ByteArrayOutputStream();

    DataOutputStream out = new DataOutputStream(stm);

    out.writeUTF("PluginName");

    out.writeUTF("AutoLogin");

    out.writeUTF(player.getName());
```

Now I have taken authme bridge as an example, but also other plugins have this problem.

**Credits: Me, ParadoxLegit.**

**Comment by Black-Hole** [comment]
Running multi level BungeeCord isn't supported. So it's not a bug.

**Comment by vincygit** [comment]
> Running multi level BungeeCord isn't supported. So it's not a bug.

I know, but using an old build of Bungeecord you can send messages to a bungeecord who uses AuthmeBridge or some other plugin who need a bungeecord hook.

Old bungeecord builds doesn't have the "You cannot proxy to it self", so you can connect a bungee to another bungee proxy.

**Comment by md-5** [comment]
yeah, no bungee bug that I can see here
