### ISSUE TITLE
Entity map reweite error

### ISSUE THREAD

**Issue by Starmixcraft** [SpigotMC/BungeeCord#2564]
On 1.13 protocoll if a scoreboard team is register and has a set team color the bungeecord throws this error: https://hastebin.com/egiwolofuz.bash

after the error you are disconneted

**Comment by Black-Hole** [comment]
Plugin issue. The namespace com.flowpowered.nbt.stream doesn't belong to BungeeCord.

**Comment by Janmm14** [comment]
The is related to fishing hooks and entity metadata.
Completely unrelated to the entity map.

**Comment by Fejm** [comment]
> The is related to fishing hooks and entity metadata.
> Completely unrelated to the entity map.

What? https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap_1_13.java#L152

**Comment by md-5** [comment]
1) your paste is not loading, please put errors in the actual issue. Especially when using sites like hastebin that delete them after a couple of days

2) how to reproduce? I’m totally skeptical of the team thing. Also Viaversion etc are unsupported
