### ISSUE TITLE
how fix this help ..

### ISSUE THREAD

**Issue by cuervito** [SpigotMC/BungeeCord#2565]
https://pastebin.com/idEcftHD

**Comment by md-5** [comment]
Version?
Plugins?
Happens without plugins?

**Comment by md-5** [comment]
Outdated, line 176 cannot error like this
https://github.com/SpigotMC/BungeeCord/blob/afef0ec1fed04f2ecea9df5134cfac7505c341a1/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L176

**Comment by Janmm14** [comment]
You are using some outdated version of bungeecord. The stack trace does not align to the current code.
Either state your version (/bungee output) or upate to latest bungee and wait for the issue to appear again, if it appears again at all.
