### ISSUE TITLE
BadPacketException Issue

### ISSUE THREAD

**Issue by Manicraft1001** [SpigotMC/BungeeCord#2571]
**Problem Desciption**
When i try to connect from our lobby (1.8.9 Spigot Server) trogh our Bungeecord on the 1.13.2 Server, occurs this error: https://prnt.sc/m1nfjb
Errors in the Bungee console: https://prnt.sc/m1ngqk

**Servers**
Lobby Server: None (should be reachable with 1.8.0 to 1.13.2)
BungeeCord: ViaVersion 1.8.0 - 1.13.2 (Version 1.6.0)
Game Server: None (Should be only 1.13.2), No ViaVer or ViaBack

Issue with Bungeecord or an Plugin of us?

**Comment by Black-Hole** [comment]
As stated in many other issues: BungeeCord offers no support for protocol hacks like ViaVersion. So you have to ask them how to fix your problem.

**Comment by Manicraft1001** [comment]
The Result of the ViaVersion Support was to update on the newest version. In my version (one of the lastest versions) was a bug in a class of bungge, so my issue is closed.
