### ISSUE TITLE
[Request] Check if a server is marked as restricted

### ISSUE THREAD

**Issue by Artuto** [SpigotMC/BungeeCord#2572]
Hi. I'd like to request an addition to the API to see if a server is marked as restricted. I know of the existence of `ServerInfo#canAccess`, however, I'm making a command for an embedded Discord bot that has a list of players of every server, and i want to remove players in any of those restricted servers.

Something like `ServerInfo#isRestricted` might work.

**Comment by md-5** [comment]
Added

**Comment by Artuto** [comment]
Thanks!
