### ISSUE TITLE
Seeking some professional advice about Bungee server and adding new plugins!

### ISSUE THREAD

**Issue by EvadeMc** [SpigotMC/BungeeCord#2585]
I need some nice and professional Plugins for a Bungee Cord hub and for factions, kitpvp, prison and more all I need is just some help.Its my first time making a network :P 

and i really don't know how the whole bungee works i got multi-craft with file-zilla help me out please?

i also have via versions and the one for connecting 1.8.9-1.13

and I've chosen (https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/) for my perms haven't touched t yet

**Comment by Janmm14** [comment]
These type of questions are more suited inside the https://spigotmc.org forums.
