### ISSUE TITLE
TabCompleteResponseEvent without function

### ISSUE THREAD

**Issue by JOO200** [SpigotMC/BungeeCord#2586]
I want to modify the TabCompletion from a spigot server at the BungeeCord server. Like "replace the suggestion `%players%` with all connected players on BungeeCord.

I have a clean setup with:
- BungeeCord: BungeeCord-Bootstrap:1.13-SNAPSHOT:7496b0a:1392 by md_5
  - Simple plugin with 2 listeners: TabCompleteEvent and TabCompleteResponseEvent

- Spigot Server: CraftBukkit version git-Spigot-f56e2e7-1a64d4a (MC 1.13.2)
  - Simple plugin with listener: TabCompleteEvent.

(Both server jar-files compiled/downlaoded today)

I can modify the suggestion lists on the spigot server (add some random stuff).
The BungeeCord server fires the TabCompleteEvent (empty list, no plugin changed something in BungeeCord). The TabCompleteResponseEvent doesn't get fired.

**Comment by md-5** [comment]
This event is not implemented on 1.13: https://github.com/SpigotMC/BungeeCord/blob/7496b0a2c8b7be45c5414b87abde4a1e9b995948/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L502

Maybe you could add it?

**Comment by JOO200** [comment]
I will try to add it in a few days.

Is it okay to modify the TabCompletionResponseEvent to use the Suggestions element from brigadier?

**Comment by md-5** [comment]
Should generally be whatever is best for the API, rather than what makes the easiest implementation

**Comment by Kealper** [comment]
Is TabCompleteEvent for 1.13 clients confirmed working? On BungeeCord build 1396 which should already have the proposed fix in it, TabCompleteEvent doesn't seem to be fired at all for 1.13 clients, but works fine for 1.12 clients. Tested on a completely fresh install of BungeeCord build 1396 with a Minecraft 1.13.2 client/server with only the one plugin loaded, and the event still doesn't appear to fire at all.

**Comment by JOO200** [comment]
You need to use a command for tab completion now.
`/? ` should fire the events.

**Comment by Kealper** [comment]
Well that's quite unfortunate, as this plugin is meant to take regular tab completions and enable BungeeCord-wide player name tabbing in chat and commands. So is this functionality just a thing of the past for BungeeCord plugins now? I can achieve this functionality with server-side plugins as well but it means much more work will be involved to implement it lol.

**Comment by JOO200** [comment]
The TabCompleteEvent from spigot doesn't work too. This is new with Minecraft's Brigadier.
I guess you have to modify the player list from your client. But I don't know how exactly.

**Comment by Kealper** [comment]
Thanks for the heads-up about it just being Brigadier-specific, I'll have to figure something out for the functionality I'm needing.

**Comment by md-5** [comment]
It's impossible to make it work for non commands without modding the client.

**Comment by Janmm14** [comment]
* in 1.13+

**Comment by fjeddy** [comment]
Update the docs to reflect this change.
