### ISSUE TITLE
iptables bungeecord

### ISSUE THREAD

**Issue by StayMM** [SpigotMC/BungeeCord#2587]
Hi everyone,

I noticed that nobody touched this topic. 
For a long time my bungeecord server is attacked in various ways. Currently, I use:
```
iptables -A INPUT -p tcp --dport 25565 -m state --state NEW -m recent --set
iptables -A INPUT -p tcp --dport 25565 -m state --state NEW -m recent --update --seconds 10 --hitcount 4 -j DROP
```

How do you protect bungeecord from attacks? Thank you for any tips.

**Comment by Janmm14** [comment]
This type of question is better suited inside the https://spigotmc.org forums.

**Comment by StayMM** [comment]
You're right, but I think that during the attack people will first check github.
