### ISSUE TITLE
Additional bungeecord protection

### ISSUE THREAD

**Issue by StayMM** [SpigotMC/BungeeCord#2588]
Hey,

Could you make the bungeecord execute iptables commands? connection_throttle and connection_throttle_limit is not enough. I think it would be better to block it from the system level.

I know that this function will be used by a small percentage of the community but I think that many servers that are attacked with bad packets would be grateful.

Thank you.

**Comment by kamcio96** [comment]
edit your start.sh
```
paste your iptables rules
java -jar BungeeCord.jar
paste your iptable rules with -D flag
```
