### ISSUE TITLE
Connection throttle doesn't work with haproxy

### ISSUE THREAD

**Issue by StayMM** [SpigotMC/BungeeCord#2590]
Hello, after set haproxy nobody can't connect to server, everything works after set `connection_throttle_limit: 9999999`
```
        retries 3
        mode tcp
        timeout connect 200ms
        timeout client 2000ms
        timeout server 2000ms
 
 
listen minecraft
        bind :25565
        mode tcp
        balance leastconn
        option log-health-checks
        option srvtcpka
        default-server inter 10s fall 1 rise 10
        option tcp-check
        server minecraft1 127.0.0.1:25577 check-send-proxy send-proxy-v2
```

**Comment by md-5** [comment]
Well yeah... connection throttle is designed to be the very first thing bungee does. It is a "first line" defense against spam.

If you are using haproxy (which is an advanced configuration) then it is expected that you disable the throttle and let haproxy or iptables handle it.

Not a bug imo.

You could argue that the throttle should be moved after the haproxy sends its IP forwarding info, but I would say whats the point of that, you may as well just disable the throttle as you have done (though the proper way to do this is set the connection_throttle value negative)

**Comment by StayMM** [comment]
Ok, thank you for your answer. How should I set iptables to be an alternative to connection throotle?

**Comment by StayMM** [comment]
Ok, thank you for your answer @md-5 . How should I set iptables to be an alternative to connection throotle?

**Comment by StayMM** [comment]
```
/sbin/iptables -A INPUT -i eth0 -p tcp --dport 25565 -m state --state NEW -m recent --set
/sbin/iptables -A INPUT -i eth0 -p tcp --dport 25565 -m state --state NEW -m recent --update --seconds 5 --hitcount 3 -j DROP

/sbin/iptables -A INPUT -i eth0:1 -p tcp --dport 25565 -m state --state NEW -m recent --set
/sbin/iptables -A INPUT -i eth0:1 -p tcp --dport 25565 -m state --state NEW -m recent --update --seconds 5 --hitcount 3 -j DROP
```
I have two networks. How can I set this up to 3 connections for 5 seconds, separately for each interface? I want to create:
3 connections / 5s for eth0, 3 connections / 5s for eth0:1

for now it works like that: 3 connections / 5s for eth:0 and eth0:1

**Comment by Janmm14** [comment]
If i understand the documentation correctly, you can let the module recent use different lists with `--name <name>` option.

**Comment by StayMM** [comment]
Works great, thank you.
