### ISSUE TITLE
1396 console connection spam.

### ISSUE THREAD

**Issue by andrewkm** [SpigotMC/BungeeCord#2596]
Updated from 1393 to 1396 due to the "/" crash bug.
Crash bug is fixed, but now bungee console is going nuts:
https://i.imgur.com/3MbmZ4v.gifv

Thoughts?

Happens for a few seconds, then stops, then again, etc etc.
If I downgrade to 1393, this doesn't occur.

PS: No bots are logging into the server and doesn't seem like an attack?
(Unless it's some really shitty bot attacking another server, while having me added to their clients server list, thus refreshing me a bunch of times). <- total guess?

**Comment by Janmm14** [comment]
@andrewkm I checked a couple IPs (6) form that screen (with whatismyipaddress.com ) and they seem to come from datacenter providers and/or form ips recently marked as "forum spam source".

This seems to be some type of attack.

**Comment by andrewkm** [comment]
Thanks @Janmm14 <3
Hmm, @md-5 you added connection throttle again? Is it advised to enable it again?
https://github.com/SpigotMC/BungeeCord/commit/5ef5dd2c098b69908a04a4ca2dc06824ec2e75c1

**Comment by md-5** [comment]
Bungee already has a throttle, but if there's lots of IPs then obviously its effect will be limited.
That being said I don't see a bug here, just coincidental timing.

**Comment by Janmm14** [comment]
@andrewkm The connection throttle in bugeecord is active again since April 2016
