### ISSUE TITLE
Not all players are showing

### ISSUE THREAD

**Issue by Luysita** [SpigotMC/BungeeCord#2600]
Hello,

Bungeecord is not showing players on all servers, it's only showing from the first priority server. Not sure what I am doing wrong.

Bungeeconfig: https://pastebin.com/XgX9V1GX

**Comment by Janmm14** [comment]
That is normal if you habe ping passthroigh enabled.

**Comment by Luysita** [comment]
Doing that removed the players from showing in website/statistic websites. How can I put them back?

**Comment by md-5** [comment]
You would need a plugin to show the appropriate amount of players.
BungeeCord does not do it by default as it is not appropriate to show 1000+ players in the client.

**Comment by Luysita** [comment]
Alright thanks.
