### ISSUE TITLE
Missing messages

### ISSUE THREAD

**Issue by PixelNotFound** [SpigotMC/BungeeCord#2608]
There are messages missing in messages.properties. For example /find and /send :( Please add all messages.
https://gyazo.com/1cdf6584b9c1db8e2abb6edf18746f1c

**Comment by MrIvanPlays** [comment]
After some research I've found that missing translations have `/send`, `/alert`, `/alertraw`, `/find`, `/server` . I could PR a fix, but will @md-5 accept it or we will stay 1+ year with no progress
