### ISSUE TITLE
inject_commands

### ISSUE THREAD

**Issue by x1p** [SpigotMC/BungeeCord#2609]
Issue:
Build 1397 injects commands so tab-complete works even though `inject_commands` is set to `false`

Consequence:
This reveals unwanted staff commands which are not meant to be revealed for players who don't have anything to do with that.

Suggestion:
Please fix or implement a function to turn auto complete off completely or, better yet, only perform it for those who have permission to see the bungee commands.

**Comment by md-5** [comment]
>Please fix or implement a function to turn auto complete off completely or, better yet, only perform it for those who have permission to see the bungee commands.

This is already the case.
Your staff commands aren’t defining permissions then.
Furthermore they would’ve been visible on 1.12 and older also.

**Comment by x1p** [comment]
I know, but I can't force them to hurry up

**Comment by md-5** [comment]
>    Spigot hasnt included it yet in their api. We cant block injection commands in 1.13 so this still cant be done. Its not possible for anyone yet. Till MD_5 decides to add it in the Spigot Api we cant block it.

The Spigot API includes functionality to block commands....

**Comment by SimonOrJ** [comment]
I'm confused, is this an issue on the Spigot server level or the BungeeCord layer?

The Spigot API to block commands is in [PlayerCommandSendEvent](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerCommandSendEvent.html), introduced in 1.13.  Your devs seem to be behind in their time.

**Comment by x1p** [comment]
The problem is with the bungee commands that are forced to players.

**Comment by SimonOrJ** [comment]
If the said staff commands are written by your devs, the best solution is to use the second constructor of [Command](https://ci.md-5.net/job/BungeeCord/ws/api/target/apidocs/net/md_5/bungee/api/plugin/Command.html):

```java
public class SomeCommand extends Command {
    public SomeCommand() {
        super("command","permission.node");
    }
    // ...
}
```

Ideally, they should've done this the first time they wrote the staff commands... If you have the source and know how to compile plugins, you can do this on sensitive commands yourself as a hotfix until your devs become available.
