### ISSUE TITLE
Client out of date message not showing

### ISSUE THREAD

**Issue by wardpieters** [SpigotMC/BungeeCord#2610]
Since build 1397 BungeeCord doesn't show the Client out of date message anymore, https://prnt.sc/mv8nih.

I've tried this with MC 1.7.10 and it keeps pinging. In the console it says "Bad packet ID, are mods in use!? Unsupported protocol version 5", https://prnt.sc/mv8nv5.

Using build 1396 solved the issue. If you need more information about my configuration just let me know.

**Comment by md-5** [comment]
Thanks, its fixed.
