### ISSUE TITLE
Javalin fails on BungeeCord

### ISSUE THREAD

**Issue by ChimpGamer** [SpigotMC/BungeeCord#2614]
I've been struggling with this issue for quite a while so today I decided to create an issue here.
My problem is that BungeeCord doesn't seem to like Javalin as it uses Jetty.

Here is the log of BungeeCord: https://pastebin.com/n6H7NrgP
Here is the log without BungeeCord: https://pastebin.com/m7rDnyez

I've made a repo on Github with the code I used to run these tests: https://github.com/ChimpGamer/JavalinTest

I hope someone can help me with this issue because I really need this.

**Comment by md-5** [comment]
Looks to me like its defaulting to the system and not current classloader.
Not really a bungee issue, I suggest you look how to make it use the correct classloader (or open a bug there to use the current classloader).
The forums are also available for support.

Fwiw I use Jetty in my plugin MineStats
