### ISSUE TITLE
Multiple Problems

### ISSUE THREAD

**Issue by RedbearPlayz** [SpigotMC/BungeeCord#2616]
I will get this error saying  Could not connect to a deafult or fallback server, please try again later. Maybe later ill get that its in online mode if i mess around with it more.
I've use bungeecord before and it worked perfectly. but now im hosting it on shockbyte. I've used their tutorials didn't work. Ill post my configs in the links below
BungeeCord Config: https://pastebin.com/AwpJZnJw
Server Config: https://pastebin.com/UsR5ikLH
Then i know i have bungeecord enabled becuase ill try to connect to it and it wont work.

**Comment by Janmm14** [comment]
General support for bungeecord is given on spigotmc.org forums, NOT here in the issues.

in server.properties set the port to 25569
