### ISSUE TITLE
InitialHandler - encountered exception io.netty.util.internal.OutOfDirectMemoryError

### ISSUE THREAD

**Issue by peakyyy** [SpigotMC/BungeeCord#2617]
hi
error: https://pastebin.com/Gyvni7mF
version: latest from https://ci.md-5.net/job/BungeeCord/
plugins: BungeeTabListPlus-2.8.9, Litebans, BungeeMotd
when: 5-10 minutes after i started server I got errors and players were kicked.
config: https://pastebin.com/dCXxswaY

**Comment by peakyyy** [comment]
I tried added more memory -Xms12G -Xmx14G, didn't help

**Comment by md-5** [comment]
Please reproduce without plugins.
I've never seen Bungee use 9GB of memory in 5 minutes.... The recommended memory is *half* a gigabyte
