### ISSUE TITLE
Anyone of you have an idea how to fix the portforward error message? for people joining my server

### ISSUE THREAD

**Issue by DominatorACR** [SpigotMC/BungeeCord#2618]
Thanks!
Server Properties:
https://pastebin.com/2JNbQnMh
BungeeCord Config:
https://pastebin.com/fezPtfVj
Spigot.yml:
https://pastebin.com/4LUZEJm4
Please help me i've been trying to find help for days! :(

I use Ngrok to players to join my server since my router doesn't have the PortForward but that isn't the problem here.

**Comment by md-5** [comment]
You haven't even said what the error is...
Please use the forums (spigotmc.org) for support

**Comment by DominatorACR** [comment]
@md-5 there updated it

**Comment by md-5** [comment]
> If you wish to use PortForward please enable in the config

That's not a bungeecord message. It must be from a plugin.

 Please use the forums (spigotmc.org) for support
