### ISSUE TITLE
Kicked with IP Forwarding Error

### ISSUE THREAD

**Issue by Irrelavant** [SpigotMC/BungeeCord#2632]
So, I'm running 5 servers on the same IP with different ports including the bungee server. 

I can connect to the bungee server which redirects me to the hub and I can /server to every other server connected to the bungee.

I just can't connect to a server directly using the actual IP with its port because I get kicked for IP Forwarding. What can I do to fix this?

Bungee config:
https://pastebin.com/6bfxCv7y

*Note: all other servers have bungeecord: true and online-mode: false

**Comment by i9hdkill** [comment]
If you added that server to bungee, this is intended behaviour. Letting people connect through the direct ip:port breaks stuff very badly. You can use forcehosts to forward players directly to that server.

Ask here if you need more help reagrding that or check the wiki
https://www.spigotmc.org/forums/bungeecord-help.70/

**Comment by Irrelavant** [comment]
So for forced hosts, I just put the IP with the different port and set it to the right server and it should work?

**Comment by i9hdkill** [comment]
No, you need a subdomain pointing at the same A record as your main server domain.

See here. Scroll down to "forced-hosts"
https://www.spigotmc.org/wiki/bungeecord-configuration-guide/

**Comment by Irrelavant** [comment]
so for example if I have something like uhc1.server.net I could put down 

uhc1.server.net: uhc1

?

If so, thank you!

**Comment by i9hdkill** [comment]
Thats correct

**Comment by Irrelavant** [comment]
Alright, thanks again!

**Comment by Minecraftsim** [comment]
my think still doesnt work
