### ISSUE TITLE
Bundle kotlin-stdlib with BungeeCord

### ISSUE THREAD

**Issue by hazae41** [SpigotMC/BungeeCord#2634]
A lot of plugins are now using Kotlin, it would be cool if bungeecord would include kotlin-stdlib to avoid that plugins bundle it and to prevent classpath conflict between plugins using different versions of Kotlin.

**Comment by md-5** [comment]
Not happening.
It also just creates the new issue that we can't change the Kotlin version without potentially disrupting plugins.
Not to mention I'm pretty sure plugins can bundle their own lib without conflicts.

**Comment by hazae41** [comment]
Plugins can shade and relocate their own lib, but they can't communicate.
And bundling kotlin-stdlib for each plugin is costly in storage.
Changing the Kotlin version for plugins developers is not hard, they just have to change it in the gradle/maven config and rebuild the plugin. It is not as difficult as changing the Minecraft version.

**Comment by Black-Hole** [comment]
@hazae41 How about you create a dependancy plugin together with some other Kotlin developers?

**Comment by hazae41** [comment]
That is what I was doing before, but there is everytime a server admin that forget to install it
Having to install 3 dependencies before using a plugin is not the best experience.

**Comment by caoli5288** [comment]
What does a lot mean? 1% or 5%？

**Comment by Janmm14** [comment]
Why you ignore the version clash problems?

**Comment by hazae41** [comment]
The version clash problem would be fixed since all plugins will use the same Kotlin version (the Kotlin version provided by Bungeecord) instead of their own

**Comment by MrIvanPlays** [comment]
@hazae41 as far as i can see the bungeecord plugins section in spigot, only you are using the kotlin language to create your plugins.

**Comment by hazae41** [comment]
Glowstone has done it 3 years ago https://github.com/GlowstoneMC/Glowstone/pull/303

**Comment by MrIvanPlays** [comment]
> Glowstone has done it 3 years ago [GlowstoneMC/Glowstone#303](https://github.com/GlowstoneMC/Glowstone/pull/303)

Is that a proxy? Should we care about that? The answer on these 2 questions is no.
