### ISSUE TITLE
Forced hosts Lobby server total player count

### ISSUE THREAD

**Issue by icedmoca** [SpigotMC/BungeeCord#2636]
I need my bungee cord to display the total amount of people on the network.
`Server list:
1. Bungeecord proxy running 25565 - mc.example.net
2. Lobby server
3. Game server 1 - 1.example.net
4. Game server 2 - 2.example.net
5. Game server 3 - 3.example.net
6. Game server 4 - 4.example.net
7. Building server - build.example.net`
As you can tell all of those are forced hosts except the mc.example.net
Top picture force default server set to true, then bottom picture set force default server to false.
[https://imgur.com/a/U8tLTch](https://imgur.com/a/U8tLTch)

See, it looks like its working when I have force default server set to false but the thing is, when a player joins mc.example.net it will take them to the last server they were on. 

I need mc.example.net to take them to the lobby but still having mc.example.net display the total amount of people on the network.

**Comment by md-5** [comment]
Please use the forums for support.
It sounds like you enabled ping passthrough or something
