### ISSUE TITLE
I have this error.

### ISSUE THREAD

**Issue by skittduge** [SpigotMC/BungeeCord#2638]
Its nothing with the console, its clean as it should be... but when i try to join lobby i get this error 
![Posnetek zaslona (94)](https://user-images.githubusercontent.com/50554345/57586206-fe5e2080-74f2-11e9-9c58-60faf5721b7e.png)

**Comment by md-5** [comment]
The server its trying to connect to is down...

**Comment by skittduge** [comment]
the server is trying what?

**Comment by i9hdkill** [comment]
You are trying to connect to a server that is offline. You can get help here
https://www.spigotmc.org/forums/bungeecord-help.70/

**Comment by skittduge** [comment]
Thanke you
