### ISSUE TITLE
QuietException

### ISSUE THREAD

**Issue by cdmvirt** [SpigotMC/BungeeCord#2641]
bungeecord lastest 1.14.1

[SEVERE] [/178.154.171.18:56982] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4554202f726f626f74732e7478742048

**Comment by Black-Hole** [comment]
This translates to "ET /robots.txt H", so the client is just sending junk data.

**Comment by Janmm14** [comment]
The client is likely a crawler / robot / search engine.
