### ISSUE TITLE
Bungeecord becomes unresponsive to any connections or commands

### ISSUE THREAD

**Issue by TechieBlort** [SpigotMC/BungeeCord#2644]
A few days/weeks of the server being online and working for Bungeecord, our server randomly stops responding to connections and or console commands.
Build version is 1408 (according to Jenkins).
I have tried some older version of Bungeecord and some have done it as well. This has been going on for months now and every time I turn around it just breaks. There are no errors in the console as far as I can see and I have double checked the logs and end up empty there too.

**Comment by md-5** [comment]
Get a thread dump with jstack

**Comment by TechieBlort** [comment]
@md-5  how would I go about doing that? (Sorry I haven't actually done that or thought about it).

**Comment by TechieBlort** [comment]
I should probably also mention that it's on a Hosting Company. I don't locally host it.

**Comment by Janmm14** [comment]
If you don'T have a vserver and host bungeecord otherwise, ask the support of your hosting company friendly if htey could create a jstack thread dump of your bungeecord for you. It should take their support, if its good, at max 5 minutes.

**Comment by TechieBlort** [comment]
After talking to support with the company they said they couldn't provide the information requested.
