### ISSUE TITLE
bungee could not connect to your first priority server

### ISSUE THREAD

**Issue by MoseRattoe** [SpigotMC/BungeeCord#2650]
Im running bungee cord with Hun in priority but when i leave from other servers (no hub) and rejoin bungee didn't connect me to hub it connect last server i left. i want connect to hub but it not connect . when i stop other server and rejoin it connect me to hub and it says: Cloud not conncet to target server. you moved to fallback server. please help

**Comment by Janmm14** [comment]
This question is not suited for this issue tracker. The issue tracker is meant mainly for "bugs" and not configuration-questions.

Next time please use https://spigotmc.org forums for such questions first.

Set `force_default_server` to true.

**Comment by MoseRattoe** [comment]
thanks
