### ISSUE TITLE
Failed to download modules with Java 11

### ISSUE THREAD

**Issue by TopMaax** [SpigotMC/BungeeCord#2651]
Hey,

I downloaded the latest BungeeCord build 1413 and run it with Java 11 but the download of the modules fails. On the other hand when I use Java 8 it downloads all modules without any errors.
I do not think that this is system specific but anyway my system is Debian 9.9 with openjdk-11-jre and Debian 9.9 with openjdk-8-jre.

**Example error:** Failed to download: SSLException : Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty @ sun.security.ssl.Alert:133

**Pastebin with the complete log:** https://pastebin.com/3D5GJS9H

**Comment by Black-Hole** [comment]
It seems you have to read about how to setup root certificates for Java 11 in Debian.

**Comment by i9hdkill** [comment]
You can google that issue and you will find a solution in 5 seconds. It‘s basically an issue between old/new java packages from that distro. It should be fixed in Deb 10. For now, grab one of the workarounds from google. But it‘s not a bungee bug
