### ISSUE TITLE
BungeeCord Forced Hosts issue

### ISSUE THREAD

**Issue by Denschen** [SpigotMC/BungeeCord#2657]
Hello,

i have a little problem with the "forced_hosts" option in Bungeecord. I have listed all my spigot servers in the config.yml under forced_hosts. The domains match the DNS records from the hoster and the ports are the same as in the server.properties file of the spigot servers.
When i now connect via a domain to the spigot server only this will be displayed: _"If you wish to use ip forwarding please enable it in your bungeecord config as well"._ Although "ip_forward" is true in the bungeecord config.yml. The ports are also not blocked by the firewall.

In addition, the MOTD is taken from the server.properties file and not from the Bungeecord config.yml

As an example I take the server "Test1" with the adress: "localhost:1169" and the domain test-1.denschen.de

**Bungeecord config.yml: https://pastebin.com/Kz1AhSBU (online-mode=true)
server.properties: https://pastebin.com/3DFWD1rT (online-mode=false) (server-port=1169)
spigot.yml: https://pastebin.com/YnFAi1wv (bungeecord: true)**

Bungeecord Build: Bungeecord #1414 Latest Build
Spigot Build: Spigot 1.8.8

I have already looked at many threads but no one really helped me. I hope one have a solution.

Best regards

Dennis

**Comment by md-5** [comment]
>via a domain to the spigot server only this will be displayed:

That's not how it works.
Your domains must all be pointing to Bungee.

Please use the forums for support, this is not a bug.

Additionally if you can see that message you have not firewalled your server properly and it is vulnerable to hacking

**Comment by Janmm14** [comment]
To prevent your spigot servers getting hacked by someone setting up their own bungee with a simple name&uuid-changer plugin, see https://spigotmc.org/wiki/firewall-guide
