### ISSUE TITLE
Source Probelm

### ISSUE THREAD

**Issue by WatchAndyTW** [SpigotMC/BungeeCord#2658]
I need to edit something in the bungee cord source. But I got some problem. It have lots of error that I can't export. And I don't know where is the API. Can anyone help?

**Comment by Janmm14** [comment]
Such a question should bebetter suited inside the spigotmc.org forums.

Otherwise you have to make sure you tell your IDE to import BungeeCord as maven project.

**Comment by WatchAndyTW** [comment]
Thanks for reply. I will ask it at spigot forum.
