### ISSUE TITLE
HAProxy: Can not resolve source IP

### ISSUE THREAD

**Issue by WOo0W** [SpigotMC/BungeeCord#2659]
BC build: 1414
HAProxy version: 1.9.8
I have a BC server, listening on 172.28.84.37:25577
I use 2 HAProxy servers, one is running on the same server of BC, which **can** resolve the source IP of players.
But when I connect to another HAProxy server which is connected with the BC server through VPN, it can not resolve the source IP of players. In /ip command, it shows the IP of HAProxy server.

On local, OK:
```
defaults
        retries 3
        mode tcp
        timeout connect 10000ms
        timeout client 10000ms
        timeout server 10000ms


listen minecraft
        bind :31101
        mode tcp
        balance leastconn
        option srvtcpka
        default-server inter 10s fall 1 rise 10
        option tcp-check
        server minecraft1 172.28.84.37:25577  check-send-proxy send-proxy-v2
```

On the server behind VPN, can not resolve players' IP:
```
defaults
        retries 3
        mode tcp
        timeout connect 10000ms
        timeout client 10000ms
        timeout server 10000ms


listen minecraft
        bind :23019
        mode tcp
        balance leastconn
        option srvtcpka
        default-server inter 10s fall 1 rise 10
        option tcp-check
        server minecraft1 172.28.84.37:25577  check-send-proxy send-proxy-v2
```

**Comment by WOo0W** [comment]
The reason is that I use a proxy on the HAProxy server to connect to the BC.

**Comment by Paulomart** [comment]
@WOo0W You might want to look at the [Proxy Protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). You must enable it in bungee and haproxy.
