### ISSUE TITLE
My freind cant connect to his own server on the same network but I can.

### ISSUE THREAD

**Issue by minebro1325** [SpigotMC/BungeeCord#2662]
Were are using portminer btw so that i can access it.

**Comment by Black-Hole** [comment]
For support you should use the Spigot forums.

**Comment by minebro1325** [comment]
this a issue tho

**Comment by Janmm14** [comment]
This is not a problem of bungeecord itself. 

This is a problem with your network setup and/or the ip he uses to connect and/or the firewall. (And theoretically it could also be a wrong setting in bungeecord config, but still)

Thats why this place is not the right one, but the spigotmc.org forums.
