### ISSUE TITLE
cant ping past bungeecord

### ISSUE THREAD

**Issue by SilentRoses** [SpigotMC/BungeeCord#2666]
I've been attempting to ping servers via my bungee but i can't

https://api.minetools.eu/ping/mc.farnetworks.org/25565

IP: mc.farnetworks.org

Ports:
  Bungee:
    address: localhost:25565
  OPSkyblock:
    address: localhost:25575
  Factions:
    address: localhost:25585
  MegaCreative:
    address: localhost:25595
  FarTowny:
    address: localhost:25605
  MiniGames:
    address: localhost:25610
  Hub:
    address: localhost:25570
  SMP:
    address: localhost:25580
  FarPrison:
    address: localhost:25640
  FarVAndP:
    address: localhost:25645
  Builder:
    address: localhost:25590

Please help as i can only ping the bungee's port. The servers firewall doesn't block port forwarding as checked quite a few times. We've also checked the default port and its 100% open. 

Regards phoebe

**Comment by md-5** [comment]
If you *could* ping those servers then your servers are vulnerable to hacking.
The point of BungeeCord is that all requests go via BungeeCord and not towards individual servers.
Please use the forums at spigotmc.org for help configuring your setup.
