### ISSUE TITLE
Port Forwarding Server BungeeCord

### ISSUE THREAD

**Issue by ItsTrapX** [SpigotMC/BungeeCord#2668]
Hello guys I need help with port forwarding my server every time I port forward it. It doesnt work other peoples cant connect to my server ip address. If you can help me leave a comment here or talk to me on discord _0Dope0_#4901 I would appreciate it if you could help me :) Thanks!!!

**Comment by Janmm14** [comment]
Or ask on spigotmc.org forums because this is not the place for this kind of questions
