### ISSUE TITLE
BungeeCord port forwarding

### ISSUE THREAD

**Issue by ItsTrapX** [SpigotMC/BungeeCord#2672]
I need help with port forwarding a bungeecord server. Should I only port forward the bungeecord or everything.

Service Name | Remote IP Address | Protocol | External Port | Internal Port | Internal IP Addres|

and for the server ip should I put my ipv4 or my public ip

**Comment by Janmm14** [comment]
Such questions are better suited for the spigotmc.org forums, thos is meant for possible actual bugs inside bungeecord.

You only should and have to port forward the tcp port you set bungee to.
