### ISSUE TITLE
server is online mode error

### ISSUE THREAD

**Issue by ChinaYingXi** [SpigotMC/BungeeCord#2673]
Please note that I know that in normal terms it is necessary to turn off online-mode in server.properties, but I can't close it on the child server for some reason, so I would like to ask if I can use BungeeCord if the child server online-mode remains true. Connect it

**Comment by Black-Hole** [comment]
Please use the forums at https://www.spigotmc.org/ for help configuring your server and your plugins for your use case.

**Comment by ChinaYingXi** [comment]
> Please use the forums at https://www.spigotmc.org/ for help configuring your server and your plugins for your use case.

I searched for a day in spigot and couldn't find the content I needed completely, but I already sent a post in spigot

**Comment by md-5** [comment]
>so I would like to ask if I can use BungeeCord if the child server online-mode remains true. 

no
