### ISSUE TITLE
Bungee Crashes every 10 to 20 minutes.

### ISSUE THREAD

**Issue by kiritodragneel** [SpigotMC/BungeeCord#2682]
So not sure what to put here really, I am running the latest build of bungee, Build #1419
however every 20mintues or so it will crash, no logs, no reports, nothing in console, it will just kick everyone and restart.

I don't know how to fix this or what to do. any suggestions

**Comment by Janmm14** [comment]
maybe some hs_err_pid files?

**Comment by kiritodragneel** [comment]
Hello thanks for quick reply.

So we have no plugins enabled we disabled all after the first few times.
We have 0 errors, no err_pid nothing :( 

We do not have commands enabled, however when this started happening we decoupled the main server and privated all the others so no one is on any of the bungee servers or even trying to connect, yet it still happens. 

I am not really sure what info to give you asd there is none, however if someone is willing to add me on discord, I can give them temp access to console/files etc..... to see what they can find

**Comment by kiritodragneel** [comment]
UPDATE: To attempt to see if it was config error, I setup a second clean server no changes AT ALL just default on latest build, it still crashed every 10mins ish

**Comment by Janmm14** [comment]
do you host on a VPS (virtual private server) or do you have just a multicraft panel/ftp?

**Comment by kiritodragneel** [comment]
I have an Akliz.net server.
they have their own panel.

**Comment by md-5** [comment]
You should contact them then.

The only way bungee can crash with nothing is if the host server kills it.
I'd place bets on cheap host with OOM killer.
