### ISSUE TITLE
unable to connect

### ISSUE THREAD

**Issue by eoltw** [SpigotMC/BungeeCord#2685]
Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

The latest version#1419

connection_throttle_limit: 3
online_mode: false
log_commands: false
network_compression_threshold: -1
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: login
  ping_passthrough: false
  priorities:
  - login
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: false
connection_throttle: 4000
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
forge_support: false
stats: 702534c8-df5a-4a79-b7d7-f7968ed3161f
disabled_commands:
- disabledcommandhere
timeout: 30000
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  login:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 175.182.9.45:66
    restricted: false
player_limit: -1

**Comment by supertassu** [comment]
For support, please use https://www.spigotmc.org/forums/bungeecord-help.70/.

Hint: The port in `175.182.9.45:66` seems weird, did you mean `25566`?

**Comment by eoltw** [comment]
> 如需支持，請使用https://www.spigotmc.org/forums/bungeecord-help.70/。
> 
> 提示：港口`175.182.9.45:66`似乎很奇怪，你的意思是`25566`？

Hall prot
