### ISSUE TITLE
Error during Handshake: Error decoding packet class Handshake with contents

### ISSUE THREAD

**Issue by dieterblancke** [SpigotMC/BungeeCord#2686]
I'm getting the following error (it's being spammed like crazy): https://paste.dbsoftwares.eu/hozosakemi.bash

I know it's a "fake" handshake packet that is being sent on purpose, in this case it's basically a sort of a "bot" attack or "ddos" or whatever you want to call it, and it floods our console (hundreds of these in seconds) to crash our network.

I'm just wondering if there is a plugin or something that helps us to limit this / bypass these errors to at least not make the BungeeCord crash.

(we also set IPTables connection limit per IP, might help aswell)

For if anyone wonders, this is being done with a crashing client called "hProxy" (the person who crashed our server with it also made a video: https://youtu.be/pcVRICY9GMY but that is a Spigot crash we managed to fix)

(the person who is crashing it said he will stop, but obviously I want to fix this for the future, the jar that sent the invalid packets seems to be this (but decompiling the crashcommand class doesn't work): https://github.com/Out69/CMCrasher)

**Comment by Janmm14** [comment]
You are currently using Waterfall, so I suggest creating this issue on Waterfall's Github.

**Comment by didjee2** [comment]
> 
> 
> You are currently using Waterfall, so I suggest creating this issue on Waterfall's Github.

It happened on BungeeCord aswell, we just tried Waterfall :P
I'm mainly just wondering if there is a way to validate/block these packets (or at least the huge spam in the console)
