### ISSUE TITLE
Remove "§" symbol into proxy.log and change for "?"

### ISSUE THREAD

**Issue by matahombres** [SpigotMC/BungeeCord#2693]
LuckPerms example:

<pre>07:10:10 [INFO] ?b       ?3 __    
07:10:10 [INFO] ?b  |    ?3|__)   ?2LuckPerms ?bv4.4.7
07:10:10 [INFO] ?b  |___ ?3|      ?8Running on Bungee - BungeeCord</pre>

I am starting the server in a "screen" command on a web server with linux user web in mode root
Server web: apache

The command it's:
<code>"cd ".$dir." ; sudo -S screen -UmdS Bungee java -Xms1G -Xmx3G -jar BungeeCord.jar"</code>

In linux terminal working but in web show ? instead of §

**Comment by md-5** [comment]
This is an issue with whatever web panel you are using.

**Comment by matahombres** [comment]
Yes, and I would like to know what can cause this. If you can have any idea about it

**Comment by matahombres** [comment]
Solved. the solved it's encode UTF-8
