### ISSUE TITLE
ProxyPingEvent and ChatEvent warnings

### ISSUE THREAD

**Issue by Mattyb0i** [SpigotMC/BungeeCord#2695]
Hey.

Every seven minutes, I get two warnings. One of my warnings is ChatEvent - https://pastebin.com/gV7Ch1wL and my other warning is ProxyPingEvent - https://pastebin.com/C9tGEhYY

I can't figure out how to fix it and I have no idea what makes the warning.

My BungeeCord version: git:BungeeCord-Bootstrap:1.14-SNAPSHOT:9e76966:1420
I only have one plugin in my BungeeCord plugins folder and that is Skungee

Regards Mathias

**Comment by md-5** [comment]
Well Skungee is lagging those events - contact the author
