### ISSUE TITLE
Should bungeecord think about a code reformat?

### ISSUE THREAD

**Issue by KlaroYT** [SpigotMC/BungeeCord#2701]
At the moment it is a fact that Bungeecord runs fully functional and largely error-free. However, it is also a fact that one notices that in some places the code is based on "old" code. Also the further development is not easy at the moment. Furthermore, it is difficult for me as a developer to work on the basis of the API. Of course, the API contains many useful methods, events etc, but you should think about a restructuring or BungeeCord 2.0. Of course it's not easy to remove methods from the API, as you should always be user-friendly, but adding methods, or changing the way the method is ultimately executed, shouldn't be a problem.

BungeeCord is a project that simplifies all our lives and is the basis for any server network. Therefore it is important to me that bungeeCord remains sustainable.

I hope that this is understandable to all readers and I am of course happy if a discussion would arise or we as a community could implement this idea.

Best regards 
_Klaro

P.S: I come from germany, please do not annoy about the spelling / grammar :)

**Comment by Janmm14** [comment]
So go ahead and write what you dont like yourself.

**Comment by md-5** [comment]
Yeah sorry I don't understand this.
You say that the code is "old" with the assumption that it could somehow be improved. Bungee is already a rewrite of a rewrite of a rewrite, its not really clear how it could be further improved. In addition having a stable API is a major drawcard (as it is for Bukkit). If you have specific recommendations, feel free to list them; but simply saying it should be rewritten without saying what specifically should be different is not helpful.
