### ISSUE TITLE
Can you help me

### ISSUE THREAD

**Issue by thetopthailand** [SpigotMC/BungeeCord#2703]
The player's IP address does not appear on general servers.

But it instead shows on bungeecord

I want it to be shown on the server as well. How do I fix it?

servers:
lobby:
motd: '&1Just another BungeeCord - Forced Host'
address: localhost:1
restricted: false
player_limit: -1

https://www.spigotmc.org/attachments/upload_2019-10-5_15-34-27-png.460431/

**Comment by md-5** [comment]
Enable IP forwarding like the instructions say.
Please use the forums for support.

**Comment by thetopthailand** [comment]
> เปิดใช้งานการส่งต่อ IP ตามคำแนะนำ
> โปรดใช้ฟอรัมเพื่อรับการสนับสนุน

I solved it. Thank you very much.

**Comment by thetopthailand** [comment]
> Enable IP forwarding like the instructions say.
> Please use the forums for support.

I solved it. Thank you very much.
