### ISSUE TITLE
False positive: "Warning, this build is outdated" when I *am* using the latest build available.

### ISSUE THREAD

**Issue by credomane** [SpigotMC/BungeeCord#2705]
Today I was working with a friend to setup and play around with bungeecord and we keep getting the message about this version is outdated and will not be supported. We are using the latest build though. Looking at the source it seems that bungeecord is assuming there will always be a newer build released within the last 8 weeks. 

As of a few hours ago, it would seem, that this internal 8 week "timer" expired and even the latest build considered itself to be out of date.

I'm not against this timer and the reason for the warning I am against the forced 10 second delay. Just provide an option such as "skip-outdated-delay=xyz" where xyz changes automatically with each release. Make it the short hash of the git build, perhaps? That way bungeecord users will have to conscientiously decide to "ignore" the warning for each outdated build.

The warning will still appear every start up but the 10 second delay would be skip-able.

**Comment by md-5** [comment]
1) Apologies for this, a new build has been released 
2) There is already an option to skip the delay
3) The release cadence will be monitored if the delay needs to be increased further
