### ISSUE TITLE
Add mixin

### ISSUE THREAD

**Issue by DeepRobin** [SpigotMC/BungeeCord#2706]
[Mixin](https://github.com/SpongePowered/Mixin) is a powerful injection library and useful for implementing or injecting into packets, own protocols, non-accessable code in bungee, etc.

**Comment by Paulomart** [comment]
Just bundle it yourself.

**Comment by md-5** [comment]
Yeah, no.
The point of having an API is so you don't do this, plus as said above we're not in the business of bundling every library that some developer may find useful.
