### ISSUE TITLE
BungeeCord issue cannot connect

### ISSUE THREAD

**Issue by polo002** [SpigotMC/BungeeCord#2708]
**Issue:**
Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException

> 16:31:29 [INFO] [Polo002] <-> InitialHandler has connected
> 16:31:34 [INFO] [Polo002] disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
> 16:31:35 [INFO] [Polo002] -> UpstreamBridge has disconnected

forge_support: false
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25565
  motd: '&aWaddup'
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: Survival
  ping_passthrough: false
  priorities:
  - Hub
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 1
  tab_size: 60
  force_default_server: true
connection_throttle: 4000
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: 2df0de43-9fe3-4219-b543-1c67849484b7
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  Hub:
    motd: '&1Hub'
    address: 172.18.0.1:25585
    restricted: false
  KitPvP:
    motd: '&1KitPvP'
    address: 172.18.0.1:25595
    restricted: false
player_limit: -1

**Comment by md-5** [comment]
Your server IP is not reachable, please use the forums for support
