### ISSUE TITLE
/send message

### ISSUE THREAD

**Issue by joeridukker** [SpigotMC/BungeeCord#2718]
Whenver someone uses /send <name> <server> It puts this gold text in chat:
Summoned to Someserver by CONSOLE. I really would like to change/hide this message but not even my messagefilter plugin can do this. I saw the message is hard coded. Could you maybe tell me in which file this message is coded so I can remove it?

Also why is this message not configurable like the other message in the mesages.properties file

**Comment by MrIvanPlays** [comment]
It isn't hardcoded. You get [this](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/resources/messages.properties) file and put it where bungee is being located. Then you can modify everything.

**Comment by joeridukker** [comment]
Do I put the file in the jar folder, or in the main root of the server?

Op ma 2 dec. 2019 om 16:07 schreef MrIvanPlays <notifications@github.com>:

**Comment by Janmm14** [comment]
Copy that whole file, make your modifications and put it in the same folder as bungeecord.jar
