### ISSUE TITLE
Port issues

### ISSUE THREAD

**Issue by CraftalotReloaded** [SpigotMC/BungeeCord#2726]
Whenever i tell bungee to listen on a port for a server it prevents servers from launching on these ports as it binds to them so i'm at a total loss as to how i should get around this.

**Comment by md-5** [comment]
Yes, you need to put your servers on other ports.
Please read the instructions and use the forums for support.

**Comment by CraftalotReloaded** [comment]
There is a lack of documentation, what's the difference between servers and listeners
