### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by CraftalotReloaded** [SpigotMC/BungeeCord#2727]
There is a huge lack of documentation so i have a few questions:
What's the difference between servers and listeners, what am i listening for when i already told it where to find my servers.
Secondly, is the bungeecord server the lobby or does it need a separate server to be a lobby.
And at last, do the other servers also need bungee

**Comment by Janmm14** [comment]
Please use the spigotmc.org forums for general support and usage questions..
