### ISSUE TITLE
Ensure ViaVersion support on Java 9+

### ISSUE THREAD

**Issue by KennyTV** [SpigotMC/BungeeCord#2730]
**[ViaVersion](https://www.spigotmc.org/resources/viaversion.19254/)** is a Spigot/Bungee plugin allowing newer client version to connect to older servers. This works perfectly fine on all given versions, but Java's changed to reflection security in 9 make it impossible (as war as we know?) to override the final modifier, and thus we cannot inject into [Bungee's pipeline.](https://github.com/SpigotMC/BungeeCord/blob/af10f82d14ef4f052b5179cff2bd94603ddb8cb1/proxy/src/main/java/net/md_5/bungee/netty/PipelineUtils.java#L49) ([ViaVersion injection](https://github.com/ViaVersion/ViaVersion/blob/47819180c492f10e5df0dbe85dd884f7f59cddbd/bungee/src/main/java/us/myles/ViaVersion/bungee/platform/BungeeViaInjector.java#L21)).

To the question: Could you make that field non-final or somehow changeable through implementation? It'd make Via usable on Java 9+ again, and it's not like any random dev will (be able to) overwrite that and not noticing that they shouldn't do that 👀

**Comment by md-5** [comment]
1) Its Java 12+
2) No, I think this is silly. What happens if $OTHER_PLUGIN needs to change a final field? Should we just not have final fields across the codebase in case some plugin might want to reflect it (which is completely unsupported anyway).

**Comment by KennyTV** [comment]
Well, it was worth a try 👀
