### ISSUE TITLE
ip forward err thing

### ISSUE THREAD

**Issue by Minecraftsim** [SpigotMC/BungeeCord#2733]
when i start my bungee server it gives me a message that says bacicly use ip forward even though i am

**Comment by Minecraftsim** [comment]
i meant when i join my bungee server

**Comment by Minecraftsim** [comment]
when i go into the server it gives me a message saying i dont have ip forward on even though it is on true

**Comment by Janmm14** [comment]
First, please use spigotmc.org forums for further support questions.

It is **important** that you **firewall your spigot servers** if you want to use ip forwarding, so only bungeecord can connect to your spigot servers: https://spigotmc.org/wiki/firewall-guide

Did you enable it also in your bungeecord confg?
