### ISSUE TITLE
HELP: Disconnected with: IllegalArgumentException : Team  already exists in this scoreboard @ com.google.common.base.Preconditions:191

### ISSUE THREAD

**Issue by lukaplayz** [SpigotMC/BungeeCord#2735]
Ok, so I upgraded my server from 1.14.4 to 1.15 and this error popped up when I tried to join my server, through bungeecord. Here is the error from the bungeecord console, https://pastebin.com/fAbgftNt
So after that, I searched up if anyone had an issue about it, and I followed their instructions and etc. and nothing worked. So I hope somebody could help me with this one. I will be active on GitHub btw.

Thanks

**Comment by lukaplayz** [comment]
I fixed it by myself already now

**Comment by mercurialmusic** [comment]
How did you fix it? I'm getting the same now.

**Comment by lukaplayz** [comment]
If you have nametagedit in your plugins folder delete it.Or try to delete other plugins one by 1 one to see one of the corrupted plugins.

**Comment by mercurialmusic** [comment]
Yup. I do. Thanks!
