### ISSUE TITLE
Ip Forward Problems

### ISSUE THREAD

**Issue by Minecraftsim** [SpigotMC/BungeeCord#2736]
everything is correct but it says when i join If you wish to use IP forwarding, please enable it in your BungeeCord config as well! but i found a warning messege on my bungee cord start.command because im on mac here is what the warning message said Epoll is not working, falling back to NIO: ExceptionInInitializerError : null @ io.netty.channel.epoll.Epoll:39
please help

**Comment by Black-Hole** [comment]
Please use the Spigot forums for community support.

**Comment by Janmm14** [comment]
As this is no bug in bungeecord but a configuration issue, the spigotmc.org forums are a better point to ask sich questions.

The warning message is unrelated.

So in your bungeecord config - did you enable ip forwarding in there?
