### ISSUE TITLE
SEVERE Exception in thread "main" 

### ISSUE THREAD

**Issue by 0H4rl3qu1n0** [SpigotMC/BungeeCord#2737]
As this log isn't very long i'm just gonna paste it here

26.12 11:00:48 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
26.12 11:00:48 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
26.12 11:00:48 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:263)
26.12 11:00:48 [Server] SEVERE at net.md_5.bungee.conf.Configuration.load(Configuration.java:92)
26.12 11:00:48 [Server] SEVERE at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:200)
26.12 11:00:48 [Server] SEVERE java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Map
26.12 11:00:48 [Server] SEVERE Exception in thread "main" 

Everytime i start it this error comes up ^^

Config:
https://pastebin.com/JcDxrTgt

Help Please.

**Comment by Janmm14** [comment]
Configuration error.

Forced hosts may not contain ports.

servers section may not contain a `-` on every line

**Comment by md-5** [comment]
Nice job cutting out the part of the error that said this is a config issue not a bug :)
