### ISSUE TITLE
BungeeCord doesnt release resources after pinging offline servers

### ISSUE THREAD

**Issue by Mystiflow** [SpigotMC/BungeeCord#2738]
If PingHandler encounters an exception (unable to ping the server because it is offline), the channel is never closed.

I could reproduce this by setting the following options in my config: 'ping-passthrough:true', 'force-default-server:true' and, setting the highest priority server as as offline server. After doing this, pinging the server from the Minecraft client can cause the exception method inside PingHandler to run and after this a connection between the proxy and the server is remained open and never closed.

Fortunately this is the only code used by Bungee utilizing the ping handler but there is no safeguards for custom plugins repeated calls of ServerInfo#ping to an offline server.
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L248-L250

This can be fixed by adding 'channel.close' at end of exception method in PingHandler class,
alternatively adding ChannelFutureListener.CLOSE_ON_FAILURE to the initial connection inside BungeeServerInfo#ping but the former fix is preferable

**Comment by md-5** [comment]
Are you sure about this?
You can see a close call here: https://github.com/SpigotMC/BungeeCord/blob/7ed4c41d3968534b0f74233bfca4e70ed20a996e/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java#L174

**Comment by md-5** [comment]
>If PingHandler encounters an exception (unable to ping the server because it is offline), the channel is never closed.

And in this case (connection refused) the channel is never opened.

>PingHandler to run and after this a connection between the proxy and the server is remained open and never closed.

How did you confirm this, because I cannot replicate.

**Comment by Mystiflow** [comment]
Yeah. You're right I missed the call in HandlerBoss.

The docs for Bootstrap#connect say 'Connect a Channel to the remote peer'. I overlooked that connection refused would have an effect as my Netty eduction is limited

**Comment by md-5** [comment]
>Does this also close the Channel underlying the ChannelContextHandler? Such as ctx.channel.close

Yes, it should be the same thing.

>. I overlooked that connection refused would have an effect as my Netty eduction is limited. 

Well I mean the same is true for traditional Java sockets -- if the socket doesn't connect there is nothing to close.

> The code seems to go throwing through to the exception method as when I did this earlier with my given setup an error showed on console

Yeah it logs this explicitly: `bungee.getLogger().log( Level.WARNING, "Error pinging remote server", error );`
