### ISSUE TITLE
Logging if log ping is disabled?

### ISSUE THREAD

**Issue by ShortByte** [SpigotMC/BungeeCord#2742]
Hey,

is it correct that if "LogPings" is disabled, logging will still occur when "RequestedProtocol" is set to 2?

![chrome_Qce3qlGQWl](https://user-images.githubusercontent.com/10292289/71747369-c3d53980-2e6f-11ea-8735-7e37b58148aa.png)

**Comment by Janmm14** [comment]
Yes,requested protocl 2 means it is no server list ping, but a join attempt
