### ISSUE TITLE
About agent connection bungeeorder

### ISSUE THREAD

**Issue by mcqwy** [SpigotMC/BungeeCord#2744]
Hello,
Because my side is dynamic IP
I wrote myself a little agent
I forward netty data to bungeeorder
But all the addresses connected to bungeeorder are 127.0.0.1
How can I change the source address?
I hope you can help me, thank you

**Comment by md-5** [comment]
You would need to use the PROXY protocol in your agent (after enabling it in Bungee).

Just use HAProxy instead of writing a custom thing
