### ISSUE TITLE
BungeeCord with Skript (Skungee)

### ISSUE THREAD

**Issue by Th3darkcatYT** [SpigotMC/BungeeCord#2745]
Hello, I need your help.. 

Today, I'm looking to create a command that will perform a player unban on all servers and display a message to staff members who have a permission for example here I would use the word : Test

command /unban:
   trigger: 
      loop all bungeecord players: 
        set {_player} to loop-value parsed as offline player 
        if {_player} has permission "test": 
          send "This message is an example" to bungeecord player "%{_player}%"

But the problem appears when the other players of the staff who are on one of the other servers that are linked to all server indicate that the player is disconnected which has the effect of not displaying the message for them : This message is an example

Skript with Skungee

**Comment by md-5** [comment]
Please use the forums for help with plugins, this is a bug tracker
