### ISSUE TITLE
You are already connected to this proxy!

### ISSUE THREAD

**Issue by SweepingLoutus** [SpigotMC/BungeeCord#2754]
So, I discovered a weird could you say bug? When you have two clients open which are the same and on the same account and have the first one join via the Bungeecord ip which we will call A and let it connect to the hub. Then if you connect with the second one which we call B to the same ip it will disconnect A and allow B to join but B will be bugged? As in for the user they will appear as a Steve skin but for other people, they will see them as invis and not in tab if connected before B joining. But if they join after B joining they will see them in tab and in their normal skin. If B connects to any other server from the hub it will fix their skin etc...

So my question is this a bug or me being incompetent at setting a server up if so how can I fix it? Also, should I be concerned about this or leave it as is?

**Comment by md-5** [comment]
Cannot reproduce, user and skin appear fine.
Make sure you are up to date (Spigot and Bungee) and if the issue still persists, try without plugins
