### ISSUE TITLE
Players Get Kicked For Trying To Connect To An Offline Server.

### ISSUE THREAD

**Issue by VanillaChan6571** [SpigotMC/BungeeCord#2756]
I am using BungeeCord `#1448`
https://pastebin.com/s1usxgA1

Use the command /server <offline server name>

It give you a massive error in console and kicks the player. for
`IndexOutOfBoundsException : Tag type id 101 is out of bounds! @com.flowpowered.nbt.TagType:107`

Tried it on a clean install and this still occurs.

**Comment by md-5** [comment]
Need more info about your server. Is it modded? What do you mean by offline, its clearly not down

**Comment by VanillaChan6571** [comment]
Server is Paper. If the someone tries to connect to an offline server within the lobby example Survival but its down. They just get kicked.

**Comment by md-5** [comment]
Only Spigot and Vanilla are supported, the server is probably sending invalid data.

**Comment by VanillaChan6571** [comment]
> Only Spigot and Vanilla are supported, the server is probably sending invalid data.

I have installed the latest verison of spigot Jenkins build 2569 from buildtools.jar and this issue still occurs

**Comment by md-5** [comment]
There could be corrupted data, it could be a plugin.

Need to be able to reproduce it on my end, an error showing corrupted data by itself doesn't help fix it since I don't know what caused it in the first place.

**Comment by VanillaChan6571** [comment]
> There could be corrupted data, it could be a plugin.

I have done a clean install with no plugins. It seems it just bungee-cord.

**Comment by VanillaChan6571** [comment]
I have updated this. Using spigot 1.15.1 I am unable to connect to an online or offline server just give the error above. So its just not offline servers but using /server <name> does kick you and not transfer you.
