### ISSUE TITLE
I got kicked after trying to join a server in the network that is offline

### ISSUE THREAD

**Issue by derMiepz** [SpigotMC/BungeeCord#2759]
I joined my lobby and accidentally tried to switch to a server that is offline. After I noticed my mistake (took too long to switch servers), I tried join the right server again but I got kicked. I was able to join again without problem. No crash etc. This never happened before (the network is up for a few weeks already) so I'm not sure if it's a problem caused by us or BungeeCord itself (maybe because we updated to 1.15.2 yesterday?) 

I got two different error messages. The very first one I'm unable to reproduce, but the second one now happens every time when trying to switch to the mentioned offline server.

You will get this exact message in chat right before the kick (corresponds to second output):
![image](https://user-images.githubusercontent.com/45405525/73045307-aba07b00-3e6d-11ea-94c8-f8584c760819.png)

First output: https://hastebin.com/fukokafexe.bash
Second output: https://hastebin.com/umutecoder.pl

**Comment by md-5** [comment]
I will look at the first error, but the second one is likely caused by an issue with your server (bad plugins, corrupt data) and is not a bug with Bungee unless you can make and upload a clean server install that shows the same issue.

**Comment by derMiepz** [comment]
Thanks for your fast reply! One thing I noticed is that it only happens with one specific server see https://streamable.com/y0uqn

**Comment by md-5** [comment]
Regarding the first issue, I suspect you are running ViaVersion, ProtocolSupport or similar which is not supported.

**Comment by derMiepz** [comment]
Welp that was easy. Totally forgot to report the plugins that we're using ^^" It seems like ViaVersion (ViaVersion-2.2.3.jar) was causing both issues because restarting all servers didn't fix it when it was still on them.
- Removed the plugin from all servers including BungeeCord
- Restarted the servers
- Everything works as expected (no kick when server is offline)
 Thanks again <3
