### ISSUE TITLE
kicks with a timeout if set in the config timeout: -1

### ISSUE THREAD

**Issue by lokha** [SpigotMC/BungeeCord#2762]
I used to be in config.yml
```yaml
timeout: -1
```

but after the update, it started to kick from the server after join after 40 seconds

I analyzed, this is due to a change in the DownstreamBridge code, namely in the commit:    
`polo1k* 24.01.2020 4:13 #2710: Store queue of pending keepalives`

https://github.com/SpigotMC/BungeeCord/commit/eeb374798b10786bb87175796b55bed0275d56c7

I don’t know how to fix this correctly, so I’m just reporting

**Comment by md-5** [comment]
I really wouldn't suggest not having a timeout, that really opens you up to certain types of attacks.

Can you explain what you are trying to do?

**Comment by lokha** [comment]
@md-5 

I'm not trying to do anything.

one of the admins set -1, this value has been in the config for several years

if the -1 behavior is not provided and you do not recommend it, then make protection against a fool or at least warning at startup

I only informed, because I considered it necessary.

**Comment by md-5** [comment]
>if the -1 behavior is not provided and you do not recommend it, then make protection against a fool or at least warning at startup

Yeah probably will.

Default is 30000, I would leave it at that.

**Comment by lokha** [comment]
everything suits me, I already use 30,000 and do not observe problems.

close issue at your discretion. all the best

**Comment by md-5** [comment]
It should now work with -1, but not recommended. Thanks.
