### ISSUE TITLE
Possibility to nuke bungeecord with bad data packets

### ISSUE THREAD

**Issue by MorkaZ** [SpigotMC/BungeeCord#2764]
Hi, please add some code to make bungee not fire events when packets are invalid. My network is currently under this type of attack.  
Here is sample of console output:  
https://paste.enginehub.org/GEsDDla2
And sometimes it throws this exception:  
https://paste.enginehub.org/z08V-bmH (here is attacker's IP)

**Comment by md-5** [comment]
>19:45:47 [INFO] [SkinsRestorer] Not applying skin to  (invalid username).
>19:45:47 [WARNING] Event PreLoginEvent(cancelled=false, cancelReasonComponents=null, connection=[] <-> InitialHandler) took 287 612 398ns to process!

No, SkinsRestorerer is lagging your server

In any case #2743

**Comment by MorkaZ** [comment]
I will delete this plugin and wait for another attack. By the way - those bad packets are firing preloginevent? It should be like this?

**Comment by MorkaZ** [comment]
It was not skinrestorer. CPU usage jumps a lot even without this plugin. One difference is that there is no skinrestorer related lines in logs.

**Comment by md-5** [comment]
My own testing shows BungeeCord can withstand several thousand requests per second and function normally.

Unless you disabled the connection throttle this means that you need to be attacked with tens of thousands of IP addresses. If tens of thousands of IP addresses are attacking you that is a DDoS and Bungee can't stop that.

**Comment by MorkaZ** [comment]
It was from one IP and yes, it was thousands of requests (proxy log got filled in few seconds). When I block one then another is attacking after some time until I will not drop it with iptables :/

**Comment by Janmm14** [comment]
What are your connection throttle settings in config.yml?

**Comment by MorkaZ** [comment]
`connection_throttle: -1`

**Comment by Janmm14** [comment]
@MorkaZ 
That is your problem. The connection throttle in bungeecord should not be -1.
Only on your spigot servers it should be -1.
I suggest that you remove that line out of your bungeecord config so it will use the default value instead.

**Comment by MorkaZ** [comment]
@Janmm14 This option is per client? I mean, if 50 players will try to join almost in one moment it will allow them all to join or it will allow only 1 client per 4000ms?

**Comment by Black-Hole** [comment]
The trottle is per ip address. To control how the number of allowed parallel connections per ip address use connection_throttle_limit

**Comment by MorkaZ** [comment]
This configuration
`connection_throttle: 1000`
`connection_throttle-limit: 50`
Means that 1 IP can connect every 1s and there is limit of 50 connections per 1s?

**Comment by Janmm14** [comment]
@MorkaZ 
No! Both options are per-IP-Address.
