### ISSUE TITLE
After switching servers, guardian beams targeting yourself are no longer visible

### ISSUE THREAD

**Issue by Brokkonaut** [SpigotMC/BungeeCord#2769]
Directly after joining a bungee network, all guardian beams are visible, but after switching to a different server in the network, guardian beams targeting yourself are no longer visible. It is still possible to view guardian beams targeting other players/mobs.

After disconnecting + reconnecting it works as expected until the next server switch.

Bungeecoord: build 1​47​7 (for 1.15.2)
Spigot: 1.15.2

**Comment by Janmm14** [comment]
I guess some entity id rewriting might be missing here.

**Comment by md-5** [comment]
Fixed for all versions except 1.8
