### ISSUE TITLE
JsonConfiguration

### ISSUE THREAD

**Issue by MrIvanPlays** [SpigotMC/BungeeCord#2771]
I see gson always pretty printing ([this](https://github.com/SpigotMC/BungeeCord/blob/master/config/src/main/java/net/md_5/bungee/config/JsonConfiguration.java#L28)) 

What if I want to create a storage of something, but want to use this implementation, but I don't want it pretty printed in order to keep the file easy to read for computers and the file to be small in size?

**Comment by md-5** [comment]
Yaml also pretty prints as well. It's a configuration API.

**Comment by MrIvanPlays** [comment]
> Yaml also pretty prints as well. It's a configuration API.

I'm not using yaml as a storage. And I don't think yaml is designed for storing data. 
I'm asking about gson.

**Comment by Janmm14** [comment]
Then don't use configuration api.
