### ISSUE TITLE
getDataFolder() is returning NPE

### ISSUE THREAD

**Issue by KarmaConfigs** [SpigotMC/BungeeCord#2772]
I'm trying to get the plugin folder, I also tried with new File(getPluginsFolder(), pluginName) but it's the same

**Comment by TheMolkaPL** [comment]
It's not even possible...

https://github.com/SpigotMC/BungeeCord/blob/a52ea50006ef8d1fb2388a25d4a5986f197bdb8a/api/src/main/java/net/md_5/bungee/api/plugin/Plugin.java#L53-L62
https://github.com/SpigotMC/BungeeCord/blob/a52ea50006ef8d1fb2388a25d4a5986f197bdb8a/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L149-L150

**Comment by KarmaConfigs** [comment]
> It's not even possible...
> 
> https://github.com/SpigotMC/BungeeCord/blob/a52ea50006ef8d1fb2388a25d4a5986f197bdb8a/api/src/main/java/net/md_5/bungee/api/plugin/Plugin.java#L53-L62
> 
> 
> https://github.com/SpigotMC/BungeeCord/blob/a52ea50006ef8d1fb2388a25d4a5986f197bdb8a/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L149-L150

Well, for some reason, it's happening, even If I use the same method that in the api

**Comment by md-5** [comment]
Please include the exact errors/stack traces.

**Comment by md-5** [comment]
https://www.spigotmc.org/threads/getdatafolder-is-returning-null.417548/#post-3689610
