### ISSUE TITLE
Commit #f41b1fc causing linkage errors

### ISSUE THREAD

**Issue by Dot-Rar** [SpigotMC/BungeeCord#2775]
Commit causing issue: https://github.com/SpigotMC/BungeeCord/commit/f41b1fc82131842409fed2df1c702cda36b06bd2

I have identified that this commit causes linkage errors in what seems to be most plugins that depend on another plugin.

Examples:

- https://hasteb.in/gikocuyo.css
- https://hasteb.in/hiyukaqo.css

The issues only occur when running build [1480](https://ci.md-5.net/job/BungeeCord/1480/), which is the build in which this commit is first present. Running build 1479, the previous build from the 14th of Feb in which this commit is not present allows the server to start smoothly without any linkage errors.

**Comment by ninja-** [comment]
I had the same issue with paperspigot 1.8

**Comment by md-5** [comment]
Should be fixed, apologies
