### ISSUE TITLE
Issue with config file encoding.

### ISSUE THREAD

**Issue by ginyai** [SpigotMC/BungeeCord#2777]
A YAML config file is loaded with Unicode, and saved with the default encoding.
So if my JVM default encoding is not Unicode, the config cannot be loaded again after saving.

reading code 
https://github.com/SpigotMC/BungeeCord/blob/c2cc33c6d74ceddaf55cb8960ac305920cc41e90/proxy/src/main/java/net/md_5/bungee/conf/YamlConfig.java#L63-L72

The snakeyaml uses a UnicodeReader reading the input stream.

https://bitbucket.org/asomov/snakeyaml/src/958c911ba3e29074ba24113f18df14205fc2682a/src/main/java/org/yaml/snakeyaml/Yaml.java#lines-451:453

**Comment by md-5** [comment]
BungeeCord saves all configs with UTF-8.
UnicodeReader loads UTF-8 or UTF-16.

--> Bungee can always load configs it saves
--> " So if my JVM default encoding is not Unicode, the config cannot be loaded again after saving." is not correct. Do you have a test case to the contrary?

Bukkit loads and saves all configs with UTF-8.

--> In Minecraft UTF-8 is the only valid encoding to use pretty much anywhere.

What encoding are you using? Do you have a test case? Why do you need to save your config in an encoding other than UTF-8 or UTF-16?

**Comment by md-5** [comment]
Nevermind you are talking about Bungee's config.yml, not the config API.

Bungee will now save its own config file in UTF-8 as well.
