### ISSUE TITLE
Arbitrary plugin enable order

### ISSUE THREAD

**Issue by Rsl1122** [SpigotMC/BungeeCord#2780]
## Describe the issue

I was [reported an issue](https://github.com/plan-player-analytics/Plan/issues/1335) where another plugin starts after my plugin, even though the plugin is a dependency.

Looking into the issue, the issue starts occurring when 7 plugins are present, but does not occur with 6 plugins. This says that the plugin enable order is arbitrary as it is affected by the number of plugins or plugin names that are present.

Looking at the code, `PluginManager` uses dependencies to determine the load order, but enable order is arbitrary because ~~a HashMap does not have an order (or rather it is ordered by the buckets).~~
- [Where plugins are enabled](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/PluginManager.java#L246)

## Possible solution

The loaded plugins could be stored in a queue when loaded and enabled in the same order they were loaded in. After the enable the queue would be empty.
- [Where the line would be added](https://github.com/SpigotMC/BungeeCord/blob/master/api/src/main/java/net/md_5/bungee/api/plugin/PluginManager.java#L330)

I can open a PR if necessary. I think that this kind of change would not break existing behavior as it is appears random to users.

**Comment by md-5** [comment]
No your analysis is wrong, plugins is a LinkedHashMap which has order: https://github.com/SpigotMC/BungeeCord/blob/6ad26cc8fad8d264d176c404cd3931153eb5753d/api/src/main/java/net/md_5/bungee/api/plugin/PluginManager.java#L51

**Comment by Rsl1122** [comment]
Hmm, where could the issue lie?
Here is a gist with the enable logs one for a "good" enable and one for a "bad" one
https://gist.github.com/Rsl1122/ddd76ccd9d56236c3e8e7b4774be2e07

**Comment by md-5** [comment]
That log file is not from BungeeCord.

**Comment by Rsl1122** [comment]
My apologies.

Here is the same issue using latest BungeeCord build instead of Waterfall
https://gist.github.com/Rsl1122/b44222898a12784263bc2ca9b973ac0f

**Comment by Janmm14** [comment]
#2781
