### ISSUE TITLE
Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

### ISSUE THREAD

**Issue by owlman5126** [SpigotMC/BungeeCord#2784]
Bungee log
00:15:00 [INFO] [Cats18] disconnected with: ?cCould not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException
--
00:15:01 [INFO] [Cats18] -> UpstreamBridge has disconnected

**Comment by Janmm14** [comment]
Usually this indicates a problem outside of bungeecord's scope.

**Comment by owlman5126** [comment]
I am hosting on mineOS and I have 2 servers running, first my bunee than a hub server. If that helps

**Comment by owlman5126** [comment]
`forge_support: false
connection_throttle_limit: 3
timeout: 30000
online_mode: true
log_commands: false
listeners:
- query_port: 25565
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    Hub: Hub
  ping_passthrough: false
  priorities:
  - Hub
  bind_local_address: true
  host: 192.168.1.201:25565
  max_players: 10
  tab_size: 10
  force_default_server: false
connection_throttle: 4000
groups:
  md_5:
  - admin
log_pings: true
ip_forward: true
prevent_proxy_connections: false
network_compression_threshold: 256
disabled_commands:
- disabledcommandhere
stats: 294846ab-0f5e-4677-b882-626d38647dcf
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
servers:
  Hub:
    motd: '&1BlockeyNet'
    address: 192.168.1.201:25567
    restricted: false
  survival:
    motd: '&1BlockeyNet'
    address: 192.168.1.201:25566
    restricted: false
player_limit: -1
`

**Comment by owlman5126** [comment]
I had my IP set up wrong thanks for the help janmm24
