### ISSUE TITLE
Support TCP port forwarding

### ISSUE THREAD

**Issue by Yuii-guoguo** [SpigotMC/BungeeCord#2791]
I have two servers. I want to use another server as the connection server, but the port cannot be forwarded, so I hope to support port forwarding instead of setting up two bungeecords

**Comment by md-5** [comment]
It is unclear what you are asking.
Port forwarding is functionality unrelated to BungeeCord

**Comment by Yuii-guoguo** [comment]
> It is unclear what you are asking.
> Port forwarding is functionality unrelated to BungeeCord

When I use port forwarding, bungeecord shows that the connection is abnormal

**Comment by SAMXPS** [comment]
What exaclty are you trying to do?

Do you have a server connected with a public IP and another behind a NAT router that you want to be linked with?
