### ISSUE TITLE
Create instances of plugin classes in JUnit environment

### ISSUE THREAD

**Issue by BrainStone** [SpigotMC/BungeeCord#2800]
In the 1.15 update creating plugin instances requires that the plugin class has been loaded with a PluginClassloader. That however proves to be difficult.

Is there a simple way to initialize one's own plugin class in a JUnit environment or do I have to resort to reflections?

**Comment by md-5** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/test/java/net/md_5/bungee/api/plugin/DummyPlugin.java
