### ISSUE TITLE
My BungeeCord Server and Spigot server are not working.

### ISSUE THREAD

**Issue by rokplays** [SpigotMC/BungeeCord#2803]
Hello,
I have recently been setting up my bungeecord server. It has not been working but I have found the problem but don't know how to fix it. When I join my BungeeCord server it says this: 

https://pastebin.com/CgwQK367

So I looked in the spigot logs and found that for some reason my spigot sever was saying it had failed to initialize a channel. Logs:

https://pastebin.com/9XUvf89b

This is all I know. Thanks.

**Comment by Black-Hole** [comment]
It's seems you're using an incompatible version of ProtocolLib. Anyway, this is no BungeeCord issue.

**Comment by rokplays** [comment]
thanks it was
