### ISSUE TITLE
bungeecord startup error

### ISSUE THREAD

**Issue by Raredombo** [SpigotMC/BungeeCord#2804]
hi guys when i start my server it just keep on going till here

04.04 00:49:03 [Multicraft] Received start command
04.04 00:49:03 [Multicraft] Loading server properties
04.04 00:49:03 [Multicraft] Starting server!
04.04 00:49:04 [Multicraft] Loaded config for "BungeeCord 1.8-1.15.2 (8-3-2020)"
04.04 00:49:04 [Server] INFO Using mbed TLS based native cipher.
04.04 00:49:04 [Server] INFO Using zlib based native compressor.
04.04 00:49:04 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.15-SNAPSHOT:6ad26cc:1486
04.04 00:49:04 [Server] INFO Not on Windows, attempting to use enhanced EpollEventLoop
04.04 00:49:04 [Server] INFO Epoll is working, utilising it!
04.04 00:49:04 [Server] INFO Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
04.04 00:49:04 [Server] INFO Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
04.04 00:49:04 [Server] INFO Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
04.04 00:49:04 [Server] INFO Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
04.04 00:49:04 [Server] INFO Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
04.04 00:49:04 [Server] INFO Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
04.04 00:49:04 [Server] INFO Loaded plugin reconnect_yaml version git:reconnect_yaml:1.15-SNAPSHOT:6ad26cc:1486 by SpigotMC
04.04 00:49:04 [Server] INFO Loaded plugin cmd_find version git:cmd_find:1.15-SNAPSHOT:6ad26cc:1486 by SpigotMC
04.04 00:49:04 [Server] INFO Loaded plugin cmd_server version git:cmd_server:1.15-SNAPSHOT:6ad26cc:1486 by SpigotMC
04.04 00:49:04 [Server] INFO Loaded plugin cmd_alert version git:cmd_alert:1.15-SNAPSHOT:6ad26cc:1486 by SpigotMC
04.04 00:49:04 [Server] INFO Loaded plugin cmd_send version git:cmd_send:1.15-SNAPSHOT:6ad26cc:1486 by SpigotMC
04.04 00:49:04 [Server] INFO Loaded plugin cmd_list version git:cmd_list:1.15-SNAPSHOT:6ad26cc:1486 by SpigotMC
04.04 00:49:04 [Server] SEVERE Exception in thread "main" 
04.04 00:49:04 [Server] SEVERE java.lang.NullPointerException
04.04 00:49:04 [Server] SEVERE at net.md_5.bungee.conf.YamlConfig.get(YamlConfig.java:120)
04.04 00:49:04 [Server] SEVERE at net.md_5.bungee.conf.YamlConfig.getServers(YamlConfig.java:218)
04.04 00:49:04 [Server] SEVERE at net.md_5.bungee.conf.Configuration.load(Configuration.java:106)
04.04 00:49:04 [Server] SEVERE at net.md_5.bungee.BungeeCord.start(BungeeCord.java:267)
04.04 00:49:04 [Server] SEVERE at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
04.04 00:49:04 [Server] SEVERE at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

can anyone help me?

my config

prevent_proxy_connections: false
listeners:
- query_port: 25577
  motd: '&dDaySilver'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 116.202.194.57:25574
  max_players: 100
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.find
  - bungeecord.command.send
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  daysilvertv:
  - admin
  PeterThresh:
  - admin
  Creed Altair:
  - admin
  MrLogicsz:
  - admin
  Raredombo:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: cb88daa7-b030-4749-b82a-e58e31dd5b6c
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&dSilverCraft'
    address: 116.202.194.57:25575
    restricted: false
  Creative:
    motd: '&dSilverCraft'
    address: 116.202.194.57:25576
    restricted: false
  Survival: null
  motd: '&dSilverCraft'
  address: 116.202.194.57:25577
  restricted: false

**Comment by Janmm14** [comment]
Please use spigotmc.org forums for further support. The error is about your configuration, because you wrote "null" in there.
