### ISSUE TITLE
io.netty.channel.unix.Errors$NativeIoException

### ISSUE THREAD

**Issue by RimuruChan** [SpigotMC/BungeeCord#2805]
## Error
disconnected with: Could not connect to a default or fallback server, please try again later: io.netty.channel.unix.Errors$NativeIoException

**Comment by Janmm14** [comment]
Definiteoy not a code issue.
Your spigot server is not reachable or refuses to let people join or your bungeecord configuration is flawed.


Usually this type of consumer problems should be discussed in the spigotmc.org forums, the issues on github are more meant for stuff that is wrong inside bungeecord itself.

**Comment by RimuruChan** [comment]
> 确定不是代码问题。
> 您的插头服务器无法访问或拒绝让其他人加入，或者您的Bungeecord配置有缺陷。
> 
> 通常，此类消费者问题应在spigotmc.org论坛中进行讨论，github上的问题更多是针对在bungeecord本身内部错误的内容造成的。

but, this error only ou

> Definiteoy not a code issue.
> Your spigot server is not reachable or refuses to let people join or your bungeecord configuration is flawed.
> 
> Usually this type of consumer problems should be discussed in the spigotmc.org forums, the issues on github are more meant for stuff that is wrong inside bungeecord itself.

but this error only appeared on linux :/

**Comment by RimuruChan** [comment]
go #2807
