### ISSUE TITLE
InitialHandler - encountered exception

### ISSUE THREAD

**Issue by Muffin2Go** [SpigotMC/BungeeCord#2813]
Hey,

lately I ran into the problem, that my Bungeecord can't be pinged in the server list anymore.. you can join normally but it would always say "Can't connect to server" in the server list.

So I looked up my Bungeecord logs and found this error:

https://pastebin.com/34y4Z0c3

However this error obviously always occurs when someone is trying to ping the Proxy.

Thanks in advance

Muffin2Go

**Comment by md-5** [comment]
You broke your config by removing all default servers

**Comment by Muffin2Go** [comment]
Peinlich ... Habe zwar nicht direkt den default server entfernt aber dein Tipp hat mir auf die Sprünge geholfen. dachte schon es lag an der Firewall... 

Danke für die schnelle Antwort und danke für Bungeecord <3
