### ISSUE TITLE
Scoreboard malformed JSON

### ISSUE THREAD

**Issue by bestronsuper** [SpigotMC/BungeeCord#2818]
When followed the Guide from https://www.spigotmc.org/wiki/scoreboard-not-api/
there is no compiling issue, but when performed on the Server following Internal Exception occurs:
Internal Exception: io.netty.handler.codec.DecoderException: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenien(true) to accept malformed JSON at line 1 column 1 path $

following Code is Used (also occurs when used as command:
`ProxiedPlayer p = event.getPlayer();
ScoreboardObjective objective = new ScoreboardObjective("test", "Test", HealthDisplay.INTEGER, (byte) 0);
p.unsafe().sendPacket(objective);
ScoreboardScore score = new ScoreboardScore("test", (byte) 0, "test", 0);
p.unsafe().sendPacket(score);
ScoreboardDisplay display = new ScoreboardDisplay((byte) 1, "test");
p.unsafe().sendPacket(display);`

**Comment by md-5** [comment]
Unfortunately this is a bug tracker and use of packets is not API
