### ISSUE TITLE
I can´t remove Bungeecord

### ISSUE THREAD

**Issue by liampettersson** [SpigotMC/BungeeCord#2826]
Hi! I recently wanted to delete my entire server. I use bungecord and i cant delete it. It sais that it´s running. I made a new server to play survival with some friends, but bungeecord picks it up and i cant join it. It connects to bungeecord. How to I remove bungeecord entierly. please help!!!

**Comment by md-5** [comment]
Stop it with /end ir restart your pc, this isnt a bungee issue
