### ISSUE TITLE
ForceHost

### ISSUE THREAD

**Issue by Steev93** [SpigotMC/BungeeCord#2827]
Getting this when trying to direct connect:
http://prntscr.com/s70y2a

Suggestions?

`server_connect_timeout: 5000
listeners:
- query_port: 2101
  motd: '&1 &3        &f&lCloud&3&lLand&7 &8 &6⭄ &e The Hub Network  &6⥺ '
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    hub.cloud-land.net: Hub
    sky.cloud-land.net: Skyblock
    skyblock.cloud-land.net: Skyblock
    hardcore.cloud-land.net: Hardcore
    survival.cloud-land.net: Survival
    rpg.cloud-land.net: RPG
  ping_passthrough: false
  priorities:
  - Hub
  bind_local_address: true
  host: 0.0.0.0:2101
  max_players: 200
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  steev_93:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 0f496b33-403f-xxxx-xxxx-cef9059ba21a
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  Hub:
    motd: '...'
    address: 103.212.xxx.xx:2104
    restricted: false
  Hardcore:
    motd: '...'
    address: 103.212.xxx.xx:2102
    restricted: false
  Skyblock:
    motd: '...'
    address: 103.212.xxx.xx:2103
    restricted: false
  RPG:
    motd: '...'
    address: 103.212.xxx.xx:2120
    restricted: false
  Survival:
    motd: '...'
    address: 103.212.xxx.xx:2100
    restricted: false
`

**Comment by Janmm14** [comment]
Please use https://spigotmc.org forums for support regarding configuration problems.

**Comment by Steev93** [comment]
> Please use https://spigotmc.org forums for support regarding configuration problems.

I have... It's all correct...

**Comment by Janmm14** [comment]
no

**Comment by Steev93** [comment]
> no

Then are you tell me what I have done wrong here...? This is for support?

**Comment by Janmm14** [comment]
Please use https://spigotmc.org forums for support regarding configuration problems.
