### ISSUE TITLE
Outdated and useless usage of flow-nbt

### ISSUE THREAD

**Issue by xxDark** [SpigotMC/BungeeCord#2834]
BungeeCord uses library for NBT that was not updated in ages (**6** years, lmao), and it does not support long arrays.

**Comment by xxDark** [comment]
https://github.com/SpongePowered/nbt/blob/develop/src/main/java/com/flowpowered/nbt/TagType.java#L42
https://wiki.vg/NBT#Specification

**Comment by md-5** [comment]
Long arrays aren’t sent anywhere bungee reads data from

**Comment by xxDark** [comment]
> 
> 
> Long arrays aren’t sent anywhere bungee reads data from

Hacked clients do.

**Comment by Leymooo** [comment]
> > Long arrays aren’t sent anywhere bungee reads data from
> 
> Hacked clients can send trash data.

Yes, players in creative can create a ItemStack with long arrays on spigot 1.12+ servers (long arrays was added in 1.12, but firstly used in 1.13)
