### ISSUE TITLE
Bungeecord take too long to connect after pinged

### ISSUE THREAD

**Issue by NearToDepression** [SpigotMC/BungeeCord#2837]
I have a bungeecord network and it takes too long to connect after clicking the "Connect" button. All my servers are on the same dedicated server.

bungeecord plugins:
https://pastebin.com/h6wU0UTh

Login server plugins:
https://pastebin.com/siNLvVe4

Bungeecord logs:
https://pastebin.com/bMedE9Tq

Bungeecord settings:
https://pastebin.com/St5VCCdy

For other info just ask

**Comment by Janmm14** [comment]
This is a bungee plugin issue. A plugin takes more than 5 seconds to process the login.
Please use spigotmc.org forums for support.

I suspect the antivpn plugin.
