### ISSUE TITLE
When sending plugin message through custom channel, PluginMessageEvent fires to all online players

### ISSUE THREAD

**Issue by nosooqua** [SpigotMC/BungeeCord#2838]
Hello. I am using Waterdog latest build (it is Waterfall fork), but this issue is also relevant in BungeeCord. Maybe there is bug in my Plugin, but I can't see where. When player join to server, fires PlayerJoinEvent, that call function (with 20 ticks delay) to send plugin message to proxy server.
If server is empty - this works fine. But when I join from another Minecraft client, proxy receive 2 plugin messages - for first joined player and for second (my another Minecraft client).

![image](https://user-images.githubusercontent.com/35642108/82344624-f5a10400-99fc-11ea-82ee-d7e4821b6f52.png)
On the screenshot: red line - message that I expect. Event over second red line - duplicate message from first red line.

Code on proxy side: https://pastebin.com/mZWbHmU3
Code on Paper side: https://pastebin.com/UPBiCCcQ

Waterdog proxy combines two servers: lobby for Bedrock edition running on Nukkit and lobby for Java edition running on latest build Paper.
I use almost same code for Nukkit and Paper versions. The differences are that in Spigot/Paper there is a PluginMessageListener, and in Nukkit I listen to DataPacketReceiveEvent for  ScriptCustomEventPacket. This perfectly works with Waterdog/Nukkit, but doesn't work for Waterdog/Paper.
I think, there is no issue in Waterdog, because, as I said earlier, this issue also relevant in BungeeCord and Waterfall too.
Proxy version: 
![image](https://user-images.githubusercontent.com/35642108/82342663-90e4aa00-99fa-11ea-818b-43ea10bf5da2.png)
Server version:
![image](https://user-images.githubusercontent.com/35642108/82342705-9e9a2f80-99fa-11ea-8d36-c084aeec4ad4.png)

**Comment by Mystiflow** [comment]
I think changing p.getServer().sendPluginMessage to just p.sendPluginMessage should do the trick because Server#sendPluginMessage sends the message through every online player https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/src/main/java/org/bukkit/craftbukkit/CraftServer.java#1523

**Comment by nosooqua** [comment]
It is actually made a trick :) Thank you so much
