### ISSUE TITLE
Not allowing me to connect

### ISSUE THREAD

**Issue by ohCr8sh** [SpigotMC/BungeeCord#2840]
I get an error of Could not connect to a default or fallback server, please try again later: io.netty.channel.ConnectTimeoutException
https://pastebin.com/ZFcL3B0J config.yml file
https://pastebin.com/cgXVyyAP Server properties file

**Comment by Fejm** [comment]
> address: 2.2.2.2:25565

> server-ip=216.172.108.179

...

Please use https://spigotmc.org forums for support regarding configuration problems.
