### ISSUE TITLE
Error occured while contacting login servers, are they down ?

### ISSUE THREAD

**Issue by K1Mst** [SpigotMC/BungeeCord#2842]
Hi, today i tried to connect to my server and i got an error on my bungee. I tried to restart my VPS and everything but the same error appears everytime.
![Screenshot_18](https://user-images.githubusercontent.com/51858718/83019565-77111b80-a027-11ea-926e-802daf1f2340.png)
![Screenshot_19](https://user-images.githubusercontent.com/51858718/83019568-77a9b200-a027-11ea-936d-6a827c4391c4.png)

**Comment by MrIvanPlays** [comment]
There are some problems currently with sessionserver.mojang.com 
That's why you can't.

**Comment by K1Mst** [comment]
Yes thanks !
