### ISSUE TITLE
[Feature Request]: Allow reading "ip-forward" from handshake

### ISSUE THREAD

**Issue by bundabrg** [SpigotMC/BungeeCord#2843]
It would be nice if BungeeCord could itself read the sending host from the handshake instead of just chopping it off an saving it as additional data.

Pros:
  * When running Bungeecord behind another proxy like GeyserMC we can get the forwarded IP without needing to run extra plugins.
  * Allows nesting Bungeecord (this has other issues but is a side effect)

Cons:
  * Has security implications that one could fake the IP by directly connecting and sending it in the handshake. This would obviously require only trusting it from specific hosts (like localhost) otherwise saving it as extradata as per normal.

**Comment by md-5** [comment]
Bungee already supports IP forwarding via the PROXY protocol.
It's not a goal (or practically sensible) to run in some other configuration.

**Comment by bundabrg** [comment]
I assume this is the PROXY protocol used by haproxy? That sounds great, I'll close the issue.

**Comment by md-5** [comment]
Yes
