### ISSUE TITLE
Changes not saving when compiling custom BungeeCord jar

### ISSUE THREAD

**Issue by PretendingToCode** [SpigotMC/BungeeCord#2845]
I'm not sure what I'm doing wrong, but every so often my changes refuse to update after I compile BungeeCord-master.  I'm running the command 'mvn install -Dcheckstyle.skip' to compile.  It looked like my changes weren't being applied, so I added a println to test my hunch.  Sure enough, even after a successful build, nothing was logged in the console.  I suspect that somehow the compiler assumes no changes were made to the proxy directory, so here is a log of that section of the compilation process.

[INFO] ---------------------< net.md-5:bungeecord-proxy >----------------------
[INFO] Building BungeeCord-Proxy 1.15-SNAPSHOT                          [10/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- scriptus:0.3.2:describe (default) @ bungeecord-proxy ---
[WARNING] Failed to get HEAD commit hash: java.lang.IllegalArgumentException:One of setGitDir or setWorkTree must be called.
[INFO] Set property "describe" to "git:BungeeCord-Proxy:1.15-SNAPSHOT:unknown:unknown"
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ bungeecord-proxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ bungeecord-proxy ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 74 source files to C:\Users\User\Desktop\anti-host-spoof\BungeeCord-master\proxy\target\classes
[WARNING] /C:/Users/User/Desktop/anti-host-spoof/BungeeCord-master/proxy/src/main/java/net/md_5/bungee/conf/Configuration.java: Some input files use or override a deprecated API.
[WARNING] /C:/Users/User/Desktop/anti-host-spoof/BungeeCord-master/proxy/src/main/java/net/md_5/bungee/conf/Configuration.java: Recompile with -Xlint:deprecation for details.
[WARNING] /C:/Users/User/Desktop/anti-host-spoof/BungeeCord-master/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java: Some input files use unchecked or unsafe operations.
[WARNING] /C:/Users/User/Desktop/anti-host-spoof/BungeeCord-master/proxy/src/main/java/net/md_5/bungee/netty/ChannelWrapper.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.0:check (default) @ bungeecord-proxy ---
[INFO]
[INFO] --- animal-sniffer-maven-plugin:1.18:check (default) @ bungeecord-proxy ---
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java18:1.0
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ bungeecord-proxy ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\User\Desktop\anti-host-spoof\BungeeCord-master\proxy\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ bungeecord-proxy ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ bungeecord-proxy ---
[INFO] Surefire report directory: C:\Users\User\Desktop\anti-host-spoof\BungeeCord-master\proxy\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running net.md_5.bungee.scheduler.SchedulerTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.565 sec
Running net.md_5.bungee.ThrottleTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.096 sec
Running net.md_5.bungee.util.BoundedArrayListTest
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.006 sec

Results :

Tests run: 13, Failures: 0, Errors: 0, Skipped: 0

[INFO]
[INFO] --- maven-jar-plugin:2.4:jar (default-jar) @ bungeecord-proxy ---
[INFO] Building jar: C:\Users\User\Desktop\anti-host-spoof\BungeeCord-master\proxy\target\bungeecord-proxy-1.15-SNAPSHOT.jar
[INFO]
[INFO] --- maven-install-plugin:2.4:install (default-install) @ bungeecord-proxy ---
[INFO] Installing C:\Users\User\Desktop\anti-host-spoof\BungeeCord-master\proxy\target\bungeecord-proxy-1.15-SNAPSHOT.jar to C:\Users\User\.m2\repository\net\md-5\bungeecord-proxy\1.15-SNAPSHOT\bungeecord-proxy-1.15-SNAPSHOT.jar
[INFO] Installing C:\Users\User\Desktop\anti-host-spoof\BungeeCord-master\proxy\pom.xml to C:\Users\User\.m2\repository\net\md-5\bungeecord-proxy\1.15-SNAPSHOT\bungeecord-proxy-1.15-SNAPSHOT.pom

**Comment by md-5** [comment]
You're not recompiling the bootstrap which is the final jar.
Please use the forums for support, this is a bug tracker.
