### ISSUE TITLE
[Discussion] 1.16 Chat Color

### ISSUE THREAD

**Issue by AL1L** [SpigotMC/BungeeCord#2853]
How will the BungeeCord Chat API handle the new full RGB colors and fonts added in [20w17a](https://www.minecraft.net/en-us/article/minecraft-snapshot-20w17a) for [Minecraft 1.16](https://www.minecraft.net/en-us/article/the-nether-update-has-date-)?

I was thinking of having 
```java
public void setColor(String color) { /* set and validate color */ }
// and
public void setFont(String font) { /* set font */ }
```
and that seems pretty straight forward, but how do we deal with plugins converting strings into BaseComponents? 

We could easily leave it up to the plugins to design their own system for custom colors, or for some plugin to create their own standard, but why not have a method in the Chat API to do this? Some possibilities are `&{#00ffff}I am yellow` or `&#00ffffI am yellow`. I'm a fan of the first one, but there could be better options out there. So then let's assume we did have that, then how do we make it work with `ChatColor` do we make it a class, how does that affect compatibility? I'm sure there's a way to do this that everyone is happy with and makes it easy to create new things with these colors.

Then once all that is sorted out the problem comes with version support, should there be a method for pre-1.16 and one for 1.16+? Or do we just ignore this and not let server owners and plugin developers use Minecraft to its fullest.

As far as I know I couldn't find any issue on this and dont know if this has already been worked out or not by you guys.

**Comment by Mystiflow** [comment]
Within ChatColor class, I think it be worth deprecating the methods that use the older '&#' system. Then making a LegacyCode->Hex# mapping to not break plugins and existing configs depending on that. 
And support from a method e.g. fromLegacyText to support the newer Hex codes. 
Then when deserialising BaseComponents, check if they're using the older color ("light_blue", etc) system and if they are convert it to a hex code before serialising it again.

**Comment by Janmm14** [comment]
I suggest using java.awt.Color for the api

**Comment by md-5** [comment]
> Some possibilities are &{#00ffff}I am yellow or &#00ffffI am yellow.

I wasn't planning on making the internal representation human friendly tbh --- the system there is for parsing _legacy_ text not human friendly text, I don't see a particular reason why you couldn't just put the json format in your configuration files if you wanted to allow the users to customize beyond the existing 15 colours.

**Comment by Janmm14** [comment]
Json is not user friendly and after all these years of json chat around, the other way is still preferred.

I think adding a custom format with §#aabbcc (will be &#aabbcc when plugins use convert method), is a good idea to not require all bungee and bukkit plugins (as bungee-chat-api is also in spigot) to update to be able to use those new features.

**Comment by Paulomart** [comment]
> I wasn't planning on making the internal representation human friendly tbh

You can be 100% certain, if there is no api, all plugins will implement some way for the conversion and we will end up with 20 different notations. 
That is not great for the ecosystem and will lead to confusion.

I think adding an api in bungee and spigot is the way to go.

**Comment by md-5** [comment]
The current internal format for your example is `§x§a§a§b§b§c§c` yes its long, but its (mostly) transparent to previous usage of chatcolors in that it won't leak hex if the server doesn't support it (and also it doesn't require adding escape codes to the format as well)

>You can be 100% certain, if there is no api, all plugins will implement some way for the conversion and we will end up with 20 different notations.

Well I'm arguing json should be the preferred notation (or else otherwise the internal notation described above if you really want it)

**Comment by Paulomart** [comment]
> The current internal format for your example is §x§a§a§b§b§c§c yes its long, but its (mostly) transparent to previous usage of chatcolors in that it won't leak hex if the server doesn't support it (and also it doesn't require adding escape codes to the format as well)

Oh great, I didnt notice that there is a way to represent that using the `§` syntax. I gussed that mojang added hex support **only** for json text.

> Well I'm arguing json should be the preferred notation (or else otherwise the internal notation described above if you really want it)

You are correct, it definitely should be. But defacto most people use the old syntax: But since there is a way to represent hex colors in there, I dont see the need of a syntax like `&#{aabbcc}`.

**Comment by md-5** [comment]
>Oh great, I didnt notice that there is a way to represent that using the § syntax. I gussed that mojang added hex support only for json text.

Its my own invention, not in Vanilla unfortunately.

**Comment by Mystiflow** [comment]
What if instead of ```§x§a§a§b§b§c§c``` as a backwards compat fallback for Hex and Legacy:

Calculate the RGB values of all 15 ChatColors and store them, then when a color is required; if it's a 1.16 client just send them the Hex but if not round the code to the closest RGB ChatColor of the 15?

**Comment by Janmm14** [comment]
https://minecraft.gamepedia.com/Formatting_codes#Color_codes

**Comment by AL1L** [comment]
> The current internal format for your example is `§x§a§a§b§b§c§c` yes its long, but its (mostly) transparent to previous usage of chatcolors in that it won't leak hex if the server doesn't support it (and also it doesn't require adding escape codes to the format as well)

This makes a lot of since actually, and is probably what will have to be used to have backwards compatibility. Maybe we do just leave the "prettier" hex formatting up to other plugins, or some utility library will implement it.

> Well I'm arguing json should be the preferred notation (or else otherwise the internal notation described above if you really want it)

as @Paulomart said, it really isn't human friendly and I doubt plugins will adopt it in their configs in favor of the legacy formatting

**Comment by winnipeg21** [comment]
> Some possibilities are &{#00ffff}I am yellow or &#00ffffI am yellow

I like the &{#000} type format or maybe $#000000. Tho keeping it with & would make more sense

**Comment by Black-Hole** [comment]
Looking at the current implementation in BC 1.16-R0.1 I am wondering if the change from an enum to a class is necessary for the ChatColor class.
I see the alternative to make each BaseComponent hold a ChatColor and a Color and make the call to setColor clear out the other. Some methods like getFullColor and getFullColorRaw could return Color.

**Comment by md-5** [comment]
> I see the alternative to make each BaseComponent hold a ChatColor and a Color and make the call to setColor clear out the other. Some methods like getFullColor and getFullColorRaw could return Color.

It's an option, but I'm not sure of the benefit of having two different methods for every colour operation

**Comment by Janmm14** [comment]
it'd be the way to go to preserve full backwards compatibility

**Comment by AL1L** [comment]
So it seems as if there's a complex way of RGB support in the Chat API and plugins are currently implementing their own way of doing colors. I was hoping to come up with some kinda of standard and that might happen down the line when people start copying major plugins like Essentials so that discussion can happen else where. Thanks for the chat everyone :D
