### ISSUE TITLE
IP forward

### ISSUE THREAD

**Issue by VAnkata19** [SpigotMC/BungeeCord#2855]
why when i use bungeecord and do all the steps right the server says Please enable Ip forward in the config aswell when i set the ip forward to true it did the same error

**Comment by Janmm14** [comment]
use spigotmc.org forums for support. this is no bug

**Comment by VAnkata19** [comment]
olk


На чт, 18.06.2020 г. в 16:30 Janmm14 <notifications@github.com> написа:
