### ISSUE TITLE
Unexpected login packet while connecting to bungee server using 1.16 Bungeecord

### ISSUE THREAD

**Issue by eliasvh** [SpigotMC/BungeeCord#2859]
I get this error when trying to connect to a bungee server using 1.16:
```
17:41:11 [SEVERE] [vhwastaken] <-> ServerConnector [survival] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
1ac7017b227472616e736c617465223a
```
![image](https://user-images.githubusercontent.com/66268877/85467472-46b29380-b579-11ea-964e-28cb8fc27893.png)
Is there anything that would explain this?
Also, I'm trying to connect to a Vanilla minecraft server that is 1.16 :)
Plus, I am using the latest versions of ViaVersion/Backwards to allow the ability to connect to the hub using 1.16.

**Comment by md-5** [comment]
I've only tested Spigot not Vanilla, but for vanilla make sure you havent enabled IP forwarding in bungee

**Comment by eliasvh** [comment]
Looks like I had ip-forward set to true.
It works now, thank you!
