### ISSUE TITLE
 Where can I find a 1.16 server with Bungee API?

### ISSUE THREAD

**Issue by huangsijun17** [SpigotMC/BungeeCord#2860]
SPIGOT Vanilla Bukkit CraftBukkit Akarin PaperMC, none of them are version 1.16.

Use 1.16 Original Server？

**Comment by Janmm14** [comment]
this is no bug in bungeecord.
wait until one of the servers mentioned update to 1.16, bungee itself also works with vanilla servers, although ip, skin and uuid are wrong

**Comment by huangsijun17** [comment]
> this is no bug in bungeecord.
> wait until one of the servers mentioned update to 1.16, bungee itself also works with vanilla servers, although ip, skin and uuid are wrong

I just want to know which server BungeeCord used to test 1.16. Then download it.

**Comment by Janmm14** [comment]
md_5 uses his unpublished spigot 1.16
