### ISSUE TITLE
BungeeCord-Chat Does Not Support New Style Hover Event

### ISSUE THREAD

**Issue by md-5** [SpigotMC/BungeeCord#2866]
Contributions welcome

**Comment by Mystiflow** [comment]
Could you assign this to me?

**Comment by MrIvanPlays** [comment]
#2851

**Comment by diogotcorreia** [comment]
@md-5
Is this going to be on Spigot as well?
My plugin is throwing errors on 1.16 because `ComponentSerializer` throws a NullPointerException when it encounters a hover with `contents`.

**Comment by md-5** [comment]
Yes it will be eventually once its confirmed working properly
