### ISSUE TITLE
Team already exist error in console!

### ISSUE THREAD

**Issue by Dariusztmt** [SpigotMC/BungeeCord#2869]
With new version of BungeeCord engine when I change servers I got error in BungeeCord server console like team already in use. As far as I see there is nothing contains with any plugins, only with BungeeCord.jar engine. If this problem is global (not for me only), I will be glad if that be fixed.

Error from console: https://pastebin.com/fds90zK3

**Comment by md-5** [comment]
This was already fixed, update
