### ISSUE TITLE
ChatColor (HEX) doesn't appear correctly in the ActionBar

### ISSUE THREAD

**Issue by ASangarin** [SpigotMC/BungeeCord#2871]
HEX colors are not showing properly when using  `player.spigot()#sendMessage(ChatMessageType, BaseComponent[])` to display an actionbar. It seems it's applying the color code from the last char in the hex string. (#FFFFF4 = §4), however using the vanilla title command with json text displays the colors properly. I've also tried using `ChatColor#of(String)` and `TextComponent#fromLegacyText(String)` but with the same issue.

Tested on git-Spigot-16d7899-4ff609e, 1.16.1-R0.1-SNAPSHOT

Here's an image of two calls using the same TextComponent but one sends to ActionBar and the other to the chat.
![The Issue](https://i.imgur.com/iTPbZWY.png)

**Comment by Janmm14** [comment]
I suggest showing the source string or how you built the BaseComponent[]

**Comment by md-5** [comment]
Does this affect bungee? If no its not a bungee issue

**Comment by md-5** [comment]
https://hub.spigotmc.org/jira/browse/SPIGOT-5851

**Comment by ASangarin** [comment]
> Does this affect bungee? If no its not a bungee issue

Want me to open it as an issue on the spigot jira?
just thought it belonged here since the BaseComponent (and ChatColor) things are from Bungee.



> I suggest that you show us the source string or how you built the BaseComponent[]
```
TextComponent text = new TextComponent();
text.setColor(ChatColor.of("#CC8400"));
player.spigot().sendMessage(ChatMessageType.ACTION_BAR, text); //Displays wrong colors
player.spigot().sendMessage(text); //Displays correct colors
```

**Comment by ASangarin** [comment]
Thanks for making the issue, closing this now then!
