### ISSUE TITLE
Move server configuration to another file

### ISSUE THREAD

**Issue by SrLeojaco** [SpigotMC/BungeeCord#2880]
Hello everyone.

Actual problem:

> As today, in order to configure servers (not only ips, also adding or deleting them) you have to edit the **config.yml** file. This is fine when you have **one or two** bungeecord servers.
> 
> When you have **more bungees** you have to **edit each config.yml because the bungee port is also defined on that file so YOU CAN'T JUST REPLACE THE FILE**.
> 

Helpfull and easy solution:

> If the servers configuration was on another file like **servers.yml** we could easily replace the file with the new changes without having to edit individually each config.yml file.

**Comment by Paulomart** [comment]
You can write a plugin that loads additional servers from any source you want: Database, YML File, Blockchain, Binary Encoded Radio Signals and so on.

No reason to change the config.

**Comment by SrLeojaco** [comment]
> You can write a plugin that loads additional servers from any source you want: Database, YML File, Blockchain, Binary Encoded Radio Signals and so on.
> 
> No reason to change the config.

I would do if this is not implemented, but i think that this will be usefull and practical for more people and will be beneficial for everyone, so that's why i'm suggesting this to improve rather than doing by myself for myself

**Comment by md-5** [comment]
`cat config.template.yml servers.yml > config.yml && java -jar BungeeCord.jar`

**Comment by SrLeojaco** [comment]
> `cat config.template.yml servers.yml > config.yml && java -jar BungeeCord.jar`

Forgot to thank you. This will do the job perfectly ^^
