### ISSUE TITLE
ItemTag Enchantment is outdated. Who the hell thought of using an int for Enchantment id? It should be a NamespacedKey / String

### ISSUE THREAD

**Issue by yannicklamprecht** [SpigotMC/BungeeCord#2891]
https://github.com/SpigotMC/BungeeCord/blob/4794fccfb8e83f7562a5a18c46f1e90ec0e5f459/chat/src/main/java/net/md_5/bungee/api/chat/ItemTag.java#L50

**Comment by Mystiflow** [comment]
It doesn't matter, nothing is done with the NBT string used in the unit test it's just to check the JSON parsing works. The enchantment object is becoming obsolete in an upcoming PR.
