### ISSUE TITLE
[1.16] Pre-1.16 Shulker Boxes Crash Players

### ISSUE THREAD

**Issue by J0schlZ** [SpigotMC/BungeeCord#2895]
https://github.com/PaperMC/Paper/issues

I found out that this issue does only happen if i connect via BungeeCord or Waterfall (i tested both) to my servers.
If i connect directly to the Servers, the issue doesn't  exist.

There is a problem with inventories containing shulker boxes created before 1.16.
If you open them your client is instantly disconnecting.

**Comment by md-5** [comment]
You need to provide more info and reproduce with Vanilla or Spigot.

**Comment by J0schlZ** [comment]
I reproduced it with Spigot....
