### ISSUE TITLE
[1.16] Pre-1.16 Shulker Boxes Crash Players

### ISSUE THREAD

**Issue by J0schlZ** [SpigotMC/BungeeCord#2896]
What behaviour is expected:
Players to be able to use Shulker Boxes from 1.15.2.

What behaviour is observed:
If a player had a Shulker box with NBT data in an inventory [either theirs or in a chest] from 1.15.2, as soon as that inventory is loaded after the 1.16 upgrade the player will crash.
No errors in console other than the player disconnecting.
**And this only happens if i connect via Bungeecord
In a direct connection the issue doesn't come up.**

Steps/models to reproduce:
Load up a 1.15.2 **Spigot** server
Get a Shulker Box that has some form of NBT data [some of these are empty so even placing and breaking one should do]
Place that shuker box in a chest/hopper/your inventory
Upgrade the server to a Spigot 1.16 build
**Connect to the server via Bungeecord**

-- If the Shulker Box is in a container, when you open it you will crash out of the server
-- If the Shulker Box is in your inventory, you will be unable to join the server as you will instantly crash out of it

**Comment by md-5** [comment]
Cannot reproduce
![image](https://user-images.githubusercontent.com/1007849/86854253-6ad6ae80-c0fb-11ea-8e00-6c8470d6687d.png)

**Comment by J0schlZ** [comment]
Thank you.
