### ISSUE TITLE
Chat on Hover or Click

### ISSUE THREAD

**Issue by MenschenToaster** [SpigotMC/BungeeCord#2904]
When I do a ChatColor custom java RGB Color and send it everything works.
But when I do this:

`
TextComponent linesString = new TextComponent(lines + " " + JoinMeAddon.PREFIX);

TextComponent joinString = new TextComponent("§a§nKlicke um den Server zu betreten§8!");

 joinString.setHoverEvent(new HoverEvent(HoverEvent.Action.SHOW_TEXT, (new ComponentBuilder("§7Verbindet dich mit §a" + server + "§8!")).create()));

joinString.setClickEvent(new ClickEvent(ClickEvent.Action.RUN_COMMAND, "/joinme " + uuid));

linesString.addExtra(joinString);

current.sendMessage(linesString);
`

it doesn't send the custom color correctly...
I don't know if the hover, click thing ore the extra option is the problem but it is somewhere in there...
Sadly I don't have the time to check this right now.

**Comment by Janmm14** [comment]
You are using the API incorrect. https://www.spigotmc.org/wiki/the-chat-component-api/#common-pitfalls

Use ComponentBuilder instead.

If you want to do it the hard way with explicit TextComponents, use TextComponent.setColor(), TextComponenet.setStyle() etc.
