### ISSUE TITLE
Cannot compile BungeeCord using JDK 14

### ISSUE THREAD

**Issue by Mystiflow** [SpigotMC/BungeeCord#2912]
JDK has a version 'JDK 14.0.2 GA'. When compiling using this, it fails with this error (```Target option 6 is no longer supported. Use 7 or later.```) in the bootstrap module.

This can be fixed by changing maven source and target from 1.6 to 1.7:
https://github.com/SpigotMC/BungeeCord/blob/94c4fcbad7cd6f16b31de291ddec0d254d997550/bootstrap/pom.xml#L19-L25

It's not usable by plugins so it won't affect developers and the other modules have at least Java 1.7 so I don't think there's an issue there either.

**Comment by md-5** [comment]
The two supported versions are 8 and 11, the LTS Javas

**Comment by Mystiflow** [comment]
I'll switch to JDK 11 but there's no harm in updating source/target to 7 anyway right?;- and would be in preparation for JDK 15 down the year

**Comment by Janmm14** [comment]
The loader is in Java 1.6 to give users an error message to update to Java 8.
I am sure that practically nobody has Java 6 as default java installation in 2020, we should be ok to update it to Java 7 when next LTS comes out.
