### ISSUE TITLE
KeyBinds.SWAP_HANDS changed in 1.16

### ISSUE THREAD

**Issue by Joeywp** [SpigotMC/BungeeCord#2917]
The new value in 1.16 is "key.swapOffhand" whereas the [current one uses "key.swapHands"](https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/Keybinds.java#L36) and thus doesn't work in 1.16

**Comment by md-5** [comment]
Is there any particular reason you need these translations on Bungee?
When running on Spigot bungeecord-chat will use the translations for the current spigot version you have.

**Comment by Joeywp** [comment]
Oops I reported it to the wrong repository, I actually need it in Spigot where it's wrong too

**Comment by md-5** [comment]
It shouldn't be wrong in spigot, spigot uses the mojang translations

**Comment by md-5** [comment]
Oh keybinds not translations :|
