### ISSUE TITLE
Hackers able to log into end-server while the bungee network is in online mode...

### ISSUE THREAD

**Issue by Camillo82** [SpigotMC/BungeeCord#2924]
Hello,
I have that problem recently. 
The intention is to have premium-only bungee server.
I have online mode true in bungee and of course online mode false set in all end-servers, for bungee to work. IP forwarding in bungee is also true.
Normal players, non-premium or premium, are not able to connect to end-servers, even if they know the IP of end-servers.
They get the message of IP forwarding and not able to connect.
However, recently some hacker is able to connect to the end-servers with non-premium account and then hack into admin premium account... How is that even possible? Is there any way to solve it? Please help.

**Comment by Leymooo** [comment]
`How is that even possible?`
Very simple. They use own bungeecord instance to connect to your backend servers. You should configure firewall to block any connections to backend servers if source ip is not your BungeeCord ip.

**Comment by FurmigaHumana** [comment]
There is literaly a big warning about this in the front page...

[Security Warning](https://github.com/SpigotMC/BungeeCord#security-warning)

**Comment by Camillo82** [comment]
OMG, that is so terrible... I was sure that bungeecord can handle it itself...
Now I have to learn how to do all of this, I'm running my network on external hosing, not my own machine.
Thank you for yout response.

**Comment by Camillo82** [comment]
I've installed BungeeGuard
https://www.spigotmc.org/resources/bungeeguard.79601/
I hope this will solve the problem effectively :)
Thanks again for the tips.
I was a bit dumb I missed that Security Warning in the front page...
Best regards,
KP
