### ISSUE TITLE
Can't join bungee servers on modified clients

### ISSUE THREAD

**Issue by DumbGameMaker** [SpigotMC/BungeeCord#2934]
If you try to join a bungeecord server on 1.16 (and maybe 1.15) using a client like BLC or Optifine, the server will ignore you when you try to connect. The vanilla client will login fine, but modified clients and NetCat (not an mc client) just times out. The clients just say `Timed out` and NetCat errors out saying `nc: connect to xxx.xxx.xx.xxx port 25565 (tcp) failed: Connection refused.`

**Comment by Janmm14** [comment]
And what does bungeecord log say?

**Comment by DumbGameMaker** [comment]
no idea, i dont have a bungee server

**Comment by DumbGameMaker** [comment]
and it doesnt always happen when I try to reproduce it

**Comment by Janmm14** [comment]
connection might get refused if you attempt to connect too often per timeframe. otherwise bungeecord log is required to be able to identify the problem if there is any.

**Comment by DumbGameMaker** [comment]
So I don't know what the issue is, but the optifine 1.16.2 PRE4 release notes says it fixed it
