### ISSUE TITLE
could not connect to a default or fallback server please try again later: io.netty.channel.AbstractChannel$AnnonatedConnectException

### ISSUE THREAD

**Issue by morphin06** [SpigotMC/BungeeCord#2937]
I have problem with bungeecord. yesterday we can still connect one of our spigot server thru bungee, after i reset my spigot server, and placed they same config with bungee of course and spigot server , after that we can't connect now.https://prnt.sc/twvpnc .

I remove all the plugins from spigot maybe there something wrong, and still they same.
I tried to remove other spigot servers in bungee config.yml and place only the this server affected to force it to load. and still got they same issue https://prnt.sc/twwsb7
I search everything in internet nothing seems any solutions. maybe.
Thats why i came here maybe you guys can help me..

Here is the bungeecord config: https://pastebin.com/Fxrb77Kg

Spigot server config:
Bungeecord: true
Online-mode:false

**Comment by Cheos137** [comment]
Do only some servers work or none of them?
And do you have the ports configured correctly in your spigot servers?
