### ISSUE TITLE
Remove Delombok

### ISSUE THREAD

**Issue by nseveryns** [SpigotMC/BungeeCord#2938]
Truthfully I have no clue what it is but it's making it nearly impossible to compile sources out of the box

**Comment by md-5** [comment]
This is a meaningless report, try to actually explain your issue. Clearly the sources can be compiled. Delombok is not even activated by default.

**Comment by Janmm14** [comment]
it is very easy to compile from source if you use maven.
i think delombok is there for javadoc generation
