### ISSUE TITLE
Problems with 1.16+ json parsing

### ISSUE THREAD

**Issue by iperrealistico** [SpigotMC/BungeeCord#2946]
Hello, when my server is under bungeecord (build no. 1530) i have some serious problems with the new 1.16 json format. From time to time (can't really tell when/why) i get kicked from the server for receiving messages in chat that contain special colors or special attributes. Usually coreprotect's messages kick me out of the server. I spoke with them on discord they told me that this is a bungee chat api issue. Also doing /plugins kicks me out of the server for the string being too long!

![image](https://user-images.githubusercontent.com/25549272/90883468-26068e80-e3ae-11ea-8034-d2c66224dd92.png)

![image](https://user-images.githubusercontent.com/25549272/90883442-18510900-e3ae-11ea-8d6b-974322ee6e81.png)

**Comment by Leonardo-Fiori** [comment]
It's easier than that for me, just discovered a realible way to get this error:

![image](https://user-images.githubusercontent.com/25549272/91549293-011e9800-e927-11ea-999b-1389de461ce7.png)

i just need to write //fill red_banner -

(try with WG 7.0.4 snapshot)

If you need additional details just ask, don't know what I should provide! :) Currently, it's happening consistently on my server. Every time i send that command.

**Comment by Leonardo-Fiori** [comment]
Removed every possible plugin from Bungee. I still get the OverFlowPacketException when i do /pl on the server

![image](https://user-images.githubusercontent.com/25549272/91834697-af3c8180-ec48-11ea-9c07-a27cc14e6cc2.png)

**Comment by Leonardo-Fiori** [comment]
Updated, and the OverflowPacketException is gone.
But i still get the JsonParseException!

This one is caused by a text sent by BanManager

![image](https://user-images.githubusercontent.com/25549272/92330150-06898a00-f06d-11ea-941c-16d6fbc5501e.png)

**Comment by ch99q** [comment]
The chat protocol for the client is here: https://wiki.vg/Chat

As shown in the example in the client, to combine multiple `Strings/ChatComponents` it should look like `{"extra":[...components]}` not `{"value": [...components]}`

I can't be sure about this, but it was just something I noticed when looking at the JSON strings. (Hope it helps)
