### ISSUE TITLE
Add event to send messages to a player after clicking on a text

### ISSUE THREAD

**Issue by ItzKiwiSap** [SpigotMC/BungeeCord#2954]
Hi,

I really would like to have the update that I can send a message to a player after the player clicked on a text.

So for example, I have created a TextComponent with a COPY_TO_CLIPBOARD ClickEvent, but I can't send a message with "Text is copied to clipboard" to the player when the player clicks on the message and the text is copied to their clipboard.

- Itz_KiwiSap_

**Comment by Janmm14** [comment]
This is not possible as the client does not send whether the user clicked on "copy to clipboard" as there is only one lcick event possible on a certain message.
