### ISSUE TITLE
Players are invisible in Spigot & Paper 1.16.3 using Bungeecord #1534

### ISSUE THREAD

**Issue by TheCanadian529** [SpigotMC/BungeeCord#2959]
So recently I've noticed that players seem to be invisible on my server's.

I'm using Bungeecord #1534 haven't added any new plugins to it either nor changed any config files. 
My Lobby/Survival is on paper 1.16.3 I also changed back to Spigot 1.16.3 and same issue happened. 

Bungeecord has online = true
All servers have bungeecord = true as well.

I'm not too sure if this is a configuration issue but I haven't changed it since like 1.16.1 when I could see players. Or a bungeecord issue.

Does anyone have an information if this is going to get fixed any time soon?

**Comment by md-5** [comment]
1. #2942 
2. Paper is not supported
