### ISSUE TITLE
ip_forward doesn't forward the player IP in server list ping

### ISSUE THREAD

**Issue by EnderTobe** [SpigotMC/BungeeCord#2960]
**How to reproduce:**

- Install Spigot, install BungeeCoord

- Set ip_forward = true in config.yml of BungeeCord

- Set bungeecord = true in spigot.yml of Spigot

- Add the Spigot Server to the forced_hosts in BungeeCord config.yml, so that all Server List Pings get redirected to the Spigot Server

- Install a Plugin that shows the destination IP of the request. I use CommandHelper with this snippet:

`bind('server_ping', null, null, @e){
    console(@e['ip'])
}`

Add Spigot Server to Serverlist in MC, refresh and see your IP: 
[15:02:13 INFO]: CommandHelper: **89.1.210.219**

Add BungeeCord to Serverlist in MC, refresh and see only the BungeeCord IP: 
[15:02:31 INFO]: CommandHelper: **127.0.0.1**

**Conclusion:**

The "ip_forward" only works when the player connects, not when the player requests the MOTD in the Server List. This makes it impossible for plugin developers to make custom MOTDs based on Spigots player-knowledge, like showing online friends and amount of unread messages.

I have tried many different things, unfortunately my Java and BungeeCord experience is not big enough to handle that problem by myself.

**Comment by EnderTobe** [comment]
Added to Forums: https://www.spigotmc.org/threads/bungeecord-ping-ip-passthrough.463310/

Seems like noone has an answer. I'm searching by myself, could it be that ip_forward is an extra-information that only can be transmitted in the protocol when the player is connecting? And the ping-ip is what Spigot gets from the IP-stack?

**Comment by Janmm14** [comment]
Yes. IP forwarding only works for join attempts. Also its additionally forwarding the player uuid and skin data through the same measures.

**Comment by EnderTobe** [comment]
Okay, thank you so much!!
