### ISSUE TITLE
What the heck do I portforward?

### ISSUE THREAD

**Issue by snaildos** [SpigotMC/BungeeCord#2982]
Right now I portforwarded all my servers including bungee. Is that not right? Should I not do that? Should the backend servers not be portforwarded? Please reply. Thanks :)

**Comment by Janmm14** [comment]
Please use spigotmc.org forums for such questions in the future. And only portforward your bungee.

**Comment by snaildos** [comment]
I am sorry; this was a answer I needed fast. This all makes sense now. Thank you!
