### ISSUE TITLE
Add option to remove (or implement CURRENT minecraft 1.16) string size limit on chat strings (JSON Overflow Issue)

### ISSUE THREAD

**Issue by sxphirus** [SpigotMC/BungeeCord#2983]
**Issue**
I've been working on a project recently with JSON chat messages, and have came across this issue: `overflow in packet detected! Cannot receive string longer than Short.MAX_VALUE (got 34711 characters).`
I believe this is caused by "legacy" support for older versions of Minecraft which didn't allow larger chat sizes. This limit has since changed.

**To reproduce this easily** 

_What I expect_
- Create a Spigot server with Venturechat installed ( i imagine this would work with a large tellraw aswell )  (currently with no proxy).
- Use https://paste.ee/p/byO1w within "hover_prefix:"
- Send chat message
- ![homertest](https://user-images.githubusercontent.com/7299223/97801748-cc84d080-1c36-11eb-876e-63d621a9dfcb.png)

_What happens when using bungee_
- Introduce server to Bungee proxy
- Attempt to send same chat message
![image](https://user-images.githubusercontent.com/7299223/97801809-56349e00-1c37-11eb-84dd-af230d2c00a5.png)
`overflow in packet detected! Cannot receive string longer than Short.MAX_VALUE (got 34711 characters)`

**Comment by Black-Hole** [comment]
The net.minecraft.server.PacketDataSerializer class limits JSON text to 262144 bytes since at least version 1.7.2. So I think it's safe for BungeeCord to enforce the same limit.

**Comment by sxphirus** [comment]
> The net.minecraft.server.PacketDataSerializer class limits JSON text to 262144 bytes since at least version 1.7.2. So I think it's safe for BungeeCord to enforce the same limit.

yes, iirc they like dividing this number through by 4, (bytes to character conversion) so that could potentially be a new limit
only issue is this would mean dropping legacy support? maybe have a config opt for toggling this

**Comment by ZeuosEtherus** [comment]
I"m not sure if it's the same issue, but I get kicked from my server attempting to run **/pl**, and I get a similar message:

DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than Short.MAX_VALUE (got 39212 characters) @ io.netty.handler.codec.MessageToMessageDecoder:98

**Comment by sxphirus** [comment]
> 
> 
> I"m not sure if it's the same issue, but I get kicked from my server attempting to run **/pl**, and I get a similar message:
> 
> DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than Short.MAX_VALUE (got 39212 characters) @ io.netty.handler.codec.MessageToMessageDecoder:98

yes, this is indeed the same issue although was fixed in more recent versions of spigot,
this was caused by the hover text on each plugin in the list showing the version & author iirc.

**Comment by Janmm14** [comment]
This problem was fixed in https://github.com/SpigotMC/BungeeCord/commit/ab9153ddc37dc05162c7d00d70c725556cc2c3ea
