### ISSUE TITLE
Bungee randomly kicks players & stops responding, but it is alive 

### ISSUE THREAD

**Issue by earl348** [SpigotMC/BungeeCord#2984]
Hello,
I have problem with my BungeeCord it looks similar to this issue https://github.com/SpigotMC/BungeeCord/issues/2062.
I've made thread dump by jstack -l  <pid>

There are a lot of waiting threads from PartyAndFriends.
Could it be cause of my issue?

I suspect too it could be RedisBungee or PlayerBalancer, could you tell me more about it dump?

[jstack.txt](https://github.com/SpigotMC/BungeeCord/files/5471662/jstack.txt)

**Comment by Janmm14** [comment]
It seems like your redis server is unable to process all the requests. It looks to me like redisbungee is waiting on answers.

Mostly your playerbalancer plugin is waiting on redis answers and therefore the connections are not handled further anymore.

**Comment by earl348** [comment]
Any ideas?
[dump11-02-1.txt](https://github.com/SpigotMC/BungeeCord/files/5475226/dump11-02-1.txt)

**Comment by Janmm14** [comment]
Please stop using this issue tracker for definitely plugin-only-related problems.
Use spigotmc forums for that and at best ask a developer to check if your redis instance is overloaded.
That jstack shows a similar state, plugins are using redisbungee and redisbungee is waiting on redis for answers.
