### ISSUE TITLE
Ip fowarding for Spigot BungeeCord not working Minecraft

### ISSUE THREAD

**Issue by WilliamKral** [SpigotMC/BungeeCord#2991]

**Comment by WilliamKral** [comment]
My spigot server, including BungeeCord whenever I try to join my server it says when I join from my localhost that its connection refused, But I have a separate mc server with it. It works fine with Bungee it's just whenever I join it. It says to edit config and turn on IP forwarding which i did do?

**Comment by Janmm14** [comment]
For problems regarding configuration please consult spigotmc.org forums.

**Comment by WilliamKral** [comment]
Okay, thanks.
