### ISSUE TITLE
Outdated server! I'm still on {0}

### ISSUE THREAD

**Issue by Norbik1004** [SpigotMC/BungeeCord#2999]
I installed bungeecord and when I try to join the server with 1.16.2, 1.16.3 and 1.16.4 (I only tried these versions) it says **Outdated server! I'm still on {0}** How can I fix this?

**Comment by Janmm14** [comment]
What bungee version do you have? And what spigot version do you have?
Generally bungeecord supports 1.16 so this is definitely a setup problem.

**Comment by Norbik1004** [comment]
I downloaded the newest bungee and it works now. I used one from my hosting's auto download.
