### ISSUE TITLE
ChatColor#getByChar will return null when passing 'x'

### ISSUE THREAD

**Issue by RoinujNosde** [SpigotMC/BungeeCord#3010]
That will break code that uses getByChar and parses hex colors.
For example:
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/browse/src/main/java/org/bukkit/util/ChatPaginator.java#89

**Comment by md-5** [comment]
The linked code doesn't use bungeecord....

**Comment by md-5** [comment]
Also its expected getByChar would return null in this case, what else could it possibly return?

**Comment by RoinujNosde** [comment]
> Also its expected getByChar would return null in this case, what else could it possibly return?

An object whose toString would return the color symbol + 'x'.

> The linked code doesn't use bungeecord....

That's true.
Should I report that on spigot then?

**Comment by md-5** [comment]
But x isn't a colour.

Would you expect getByChar('y') to return something? In the code you linked it couldn't even since ChatColor is an enum

**Comment by RoinujNosde** [comment]
Is 'r' a color?

> In the code you linked it couldn't even since ChatColor is an enum

What do you mean? Just adding a new enum would do.

**Comment by md-5** [comment]
>What do you mean? Just adding a new enum would do.

It doesn't make sense though. What would you have? ChatColor.Y_COLOR, that does what?
What should ChatColor.getByChar('😃') return?

**Comment by RoinujNosde** [comment]
It would be there only for compatibility.

But maybe this is #wordWrap's problem. It should now handle 'x' when parsing.

**Comment by Janmm14** [comment]
You should get confused with spigots addition of bungeecord-chat and what vanilla / craftbukkit provide.
