### ISSUE TITLE
Bungee fails to connect to Forge server with Unexpected packet on 1.16.4 and silently fails on 1.12.2

### ISSUE THREAD

**Issue by diademiemi** [SpigotMC/BungeeCord#3017]
I have tested a few scenarios. My issue originated when I tried to connect to a Forge (RLCraft) server running 1.12.2 through Bungeecord and a Lobby (1.16.4 Tuinity) running ViaVersion and ViaBackwards. This silently fails with no error.
```
[DiaDemiEmi] <-> ServerConnector [Co-Op2] has connected
[DiaDemiEmi] <-> ServerConnector [Co-Op2] has disconnected
```
When setting the server as highest priority, it does show 
`[DiaDemiEmi] disconnected with: ReadTimeoutException : null`

I then tried just vanilla 1.12.2 to see if it would work properly then, it did so this is not strictly an issue with ViaBackwards. This is also shown because I created a fresh 1.16.4 Forge server with no mods, it is set to the highest priority. I attempted to connect to it with Forge 1.16.4 also without mods, it did not connect but did give the following error.
```
[DiaDemiEmi] <-> ServerConnector [ForgeTest] has connected
[DiaDemiEmi] <-> ServerConnector [ForgeTest] - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!
19c7017b227472616e736c617465223a
[DiaDemiEmi] disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!
19c7017b227472616e736c617465223a
[DiaDemiEmi] -> UpstreamBridge has disconnected
[DiaDemiEmi] <-> ServerConnector [ForgeTest] has disconnected
```
In both of these scenarios, the Forge server behind the proxy does not seem to receive any data, there is nothing in the logs of the back-end servers, so this seems to be purely an issue in how Bungee processes Forge clients. 
I do not know if the first and second scenarios are related but they both are Forge not being able to connect. 

Here is a snippit of relevant config.yml options
```
remote_ping_cache: -1
network_compression_threshold: 256
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: false
online_mode: true
forge_support: true
```
`online-mode` is set to`false` on all back-end servers.

**Comment by embeddedt** [comment]
I stumbled across this problem as well. Apparently Forge 1.12 will just silently reject handshake packets if they have BungeeCord information in them.

To fix it you have two options:

* Disable `ip_forward` in the BungeeCord config and keep the Forge server in offline mode.
* Use SpongeForge or another mod which can process BungeeCord IP forwarding packets.

**Comment by diademiemi** [comment]
This resolved the issue I was having! Just now I have a different issue but I think it's unrelated. Thank you!
