### ISSUE TITLE
I have an Error and i dont know how to fix it 

### ISSUE THREAD

**Issue by ScreeperHD** [SpigotMC/BungeeCord#3022]
FO] Using mbed TLS based native cipher.
18:16:01 [INFO] Using zlib based native compressor.
18:16:01 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.16-R0.5-SNAPSHOT:9f6a798:1543
18:16:01 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
18:16:01 [INFO] Epoll is working, utilising it!
18:16:01 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
18:16:01 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
18:16:01 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
18:16:01 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
18:16:01 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
18:16:01 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
18:16:01 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
18:16:01 [INFO] Loaded plugin cmd_find version git:cmd_find:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
18:16:01 [INFO] Loaded plugin cmd_server version git:cmd_server:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
18:16:01 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
18:16:01 [INFO] Loaded plugin cmd_send version git:cmd_send:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
18:16:01 [INFO] Loaded plugin cmd_list version git:cmd_list:1.16-R0.5-SNAPSHOT:9f6a798:1543 by SpigotMC
18:16:01 [SEVERE] Exception in thread "main"
18:16:01 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
18:16:01 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
18:16:01 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:71)
18:16:01 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
18:16:01 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
18:16:01 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
18:16:01 [SEVERE] Caused by: while parsing a block mapping
 in 'reader', line 21, column 3:
      Lobby:
      ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 25, column 4:
       CityBuild:
       ^

18:16:01 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:572)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
18:16:01 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:411)
18:16:01 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
18:16:01 [SEVERE]     ... 4 more

**Comment by Janmm14** [comment]
Your configuration is invalid just like the error says.
Please consult spigotmc.org forums for further help regarding usage of bungeecord and general support.
