### ISSUE TITLE
Sending message through Message Channel twicing received packet.

### ISSUE THREAD

**Issue by IM-IgniteDEV** [SpigotMC/BungeeCord#3023]
Hi, I've been doing many tests on two separate machines. One setup of 3 servers + waterfall, 2nd one that I'm going to show you there is BungeeCord + 3 servers.

There's 1 player on server1 and two players on server2, and server 3 is empty.

When I send a packet in ChatEvent on server1 it is sent once (according to logs). Server2 receive this packet twice. And Server3 does not receive packets because it does not contains any players.

![image](https://user-images.githubusercontent.com/31209154/105118886-86ba0480-5acf-11eb-998c-60d2c4081f00.png)
![image](https://user-images.githubusercontent.com/31209154/105118906-90dc0300-5acf-11eb-99c0-53fa9240b834.png)

![image](https://user-images.githubusercontent.com/31209154/105118915-946f8a00-5acf-11eb-84cf-77e2c0741b32.png)
![image](https://user-images.githubusercontent.com/31209154/105118927-99ccd480-5acf-11eb-9a1c-410dca3f2e97.png)

![image](https://user-images.githubusercontent.com/31209154/105118938-a05b4c00-5acf-11eb-8a12-855f85776a26.png)
![image](https://user-images.githubusercontent.com/31209154/105118943-a3563c80-5acf-11eb-9833-d1bb6bdecf6a.png)

No idea what's wrong, I've been going through bungee code about this part and it seems correct.

**Comment by IM-IgniteDEV** [comment]
Cleaner screenshot 
![image](https://user-images.githubusercontent.com/31209154/105119491-bd444f00-5ad0-11eb-8ba7-4b9077a68403.png)

**Comment by Janmm14** [comment]
It might be that you have the plugin twice in plugins folder or that you accidentally registered the listener twice.

Also make sure that you don't have the same server multiple times in your bungee config.

**Comment by IM-IgniteDEV** [comment]
Everything is correct.

**Comment by IM-IgniteDEV** [comment]
To Clarify:

![image](https://user-images.githubusercontent.com/31209154/105186945-86068a00-5b32-11eb-80cf-3553b901fe43.png)

![image](https://user-images.githubusercontent.com/31209154/105186972-8d2d9800-5b32-11eb-866e-f1e5effd99e9.png)

![image](https://user-images.githubusercontent.com/31209154/105187060-a1719500-5b32-11eb-9ddb-d7369b90b7c9.png)

Bungee config:

`listeners:
- query_port: 25565
  motd: Ignite Test Server
  tab_list: GLOBAL_PING
  query_enabled: true
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - server1
  bind_local_address: true
  host: 172.27.218.149:25565
  max_players: 100
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default: []
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
stats: d3d0c1b5-8c59-4989-9a51-2d76de6d8503
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
prevent_proxy_connections: true
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  server1:
    motd: Server 1
    address: 172.27.218.149:25001
    restricted: false
  server2:
    motd: Server 2
    address: 172.27.218.149:25002
    restricted: false
  server3:
    motd: Server 3
    address: 172.27.218.149:25590
    restricted: false
`

(this is a local IP address)

**Comment by IM-IgniteDEV** [comment]
Quick note:

I've tested this with a totally 3 servers and 4 accounts;

Server1:

1 player

Server2:

2 players

Server3:

1 player


When a packet is sent from Server1 or Server3, players on Server2, are receiving one packet.

When a packet is sent from Server2 to Server1 and Server3 players are receiving packet * player count on Server2.

**Comment by Leymooo** [comment]
> ![image](https://user-images.githubusercontent.com/31209154/105118927-99ccd480-5acf-11eb-9a1c-410dca3f2e97.png)

In this screenshot you use `Bukkit.getSender().sendPluginMessage`, it sends plugin messages from each player on server. (so if you have 3 players online, 3 plugin messages will be send)

> ![image](https://user-images.githubusercontent.com/31209154/105186945-86068a00-5b32-11eb-80cf-3553b901fe43.png)

In this screenshot you use `player.sendPluginMessage`, which is correct.

>When a packet is sent from Server1 or Server3, players on Server2, are receiving one packet.
>When a packet is sent from Server2 to Server1 and Server3 players are receiving packet * player count on Server2.

I think your issue was using `Bukkit.getSender().sendPluginMessage` instead of `player.sendMessage` and you fix it but maybe you forgot upload fixed version to `Server2` or restart this server.

**Comment by IM-IgniteDEV** [comment]
Looks like a good example of miscommunication, I was wrong informed on the PaperMC discord server, someone told me that the Bukkit.getServer().sendPluginMessage is the one that is not using a queue. Noone told me that he was wrong. 

I was about to looks through the implementation of both methods today after spending the whole day yesterday looking for issues on bungee src. 

This is NOT well documented, I have never seen any comment according to that.

I really thank you @Leymooo 🥇
