### ISSUE TITLE
Bungeecord problem

### ISSUE THREAD

**Issue by IDreamAboutYou** [SpigotMC/BungeeCord#3025]
I have feeling this is not right place for support, but I'm going to ask anyway( Is there support line/discord where I can ask these things? ).

I'd like to make my bungecord server multiplayer server that other players can join outside of my network. And I'd like to use my domain for it too. I've tried to configure this for days and I haven't found solution for that.

**Comment by Janmm14** [comment]
spigotmc.org forums is your place to go
