### ISSUE TITLE
Connection errors with the newest BungeeCord.

### ISSUE THREAD

**Issue by Pixiio** [SpigotMC/BungeeCord#303]
Hello,

We are having some issues with the newest version of BungeeCord (#387). People are unable to connect to our server, but sometimes some people make it to the server. The problem is then that they are unable to join any other server.

Getting this kind of errors:  IOException: Connection reset by peer
Alot of people have it with the newest BungeeCord, link: http://www.spigotmc.org/threads/1-5-1-bungeecord.392/page-54

Thanks

**Comment by MrFrostmaul** [comment]
I got same error, randomly started and my connection throttle on the proxy and all servers are set -1
