### ISSUE TITLE
Bungeecord issues

### ISSUE THREAD

**Issue by ISlipperyCedder** [SpigotMC/BungeeCord#3030]
I keep getting this error 
05:37:49 [INFO] [ISlipperyCedder] <-> ServerConnector [hub] has connected
>
05:37:49 [INFO] [BungeeChat] JOIN > hub > ISlipperyCedder: ISlipperyCedder has joined the network!
>
05:37:58 [INFO] [ISlipperyCedder] disconnected with: DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 112)) @ io.netty.handler.codec.MessageToMessageDecoder:98
>
05:37:58 [INFO] [BungeeChat] LEAVE > hub > ISlipperyCedder: ISlipperyCedder has left the network!

How do I fix it?

I also get this error
corrupteframeexception : emptypacket! @ net.md_5.bungee.protocol.Varient21FrameDecoder:45

**Comment by ISlipperyCedder** [comment]
Te server is 1.16.4 and I am joining on an 1.16.4 client

**Comment by fikawka** [comment]
@ISlipperyCedder Are you joining on 100% not modifier 1.16.4 client?
