### ISSUE TITLE
Forced Hosts

### ISSUE THREAD

**Issue by NightCrafter1** [SpigotMC/BungeeCord#3031]
Hello I need some help with my forced host!

I know this is related to  #1532 but I have done the same things and it has not worked
Please help!
Bungee Configuration: https://drive.google.com/file/d/1RzdkZW2UNUlI0bOI3gh56ykR9duU5eLh/view?usp=sharing

Cloudflare Config: 
![Capture of cloudflare](https://user-images.githubusercontent.com/64771089/105803539-6ddab300-5fe9-11eb-9950-3e0b0e4d0480.PNG)

It may also help if I let you know that I am also hosting a website with this domain.
If I need to provide any more information let me know.

**Comment by NightCrafter1** [comment]
here is a direct copy and paste of the bungee config

`server_connect_timeout: 5000
listeners:
- query_port: 25577
  motd: '&2&lReSpected Gamers'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    ikea.bamboozledmc.xyz: ikea
  ping_passthrough: false
  priorities:
  - hub
  - fallback
  bind_local_address: true
  host: 0.0.0.0:25565
  max_players: 20
  tab_size: 60
  force_default_server: true
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 5
prevent_proxy_connections: false
timeout: 30000
player_limit: 20
ip_forward: true
groups:
  BamBoozled_MC:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 7b60bbb1-b915-4160-bc65-194af6d6e11f
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  hub:
    motd: '&2&lReSpected Gamers'
    address: localhost:25566
    restricted: false
  fallback:
    motd: '&2&lReSpected Gamers'
    address: localhost:25564
    restricted: false
  vanilla-survival:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25567
    restricted: false
  ikea:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25580
    restricted: false
  pvp:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25568
    restricted: false
`

**Comment by Janmm14** [comment]
You can't use cloudflare proxy for minecraft traffic.

**Comment by NightCrafter1** [comment]
What do you mean?

**Comment by NightCrafter1** [comment]
> You can't use cloudflare proxy for minecraft traffic.

Well um, I some how figured out how to...
its working now so thanks for the help. and acknowledging me :p

**Comment by rileycalhoun** [comment]
How did you get this to work? Currently having trouble as well.

**Comment by Janmm14** [comment]
> How did you get this to work? Currently having trouble as well.

Please use spigotmc forums.
