### ISSUE TITLE
ip forward doesn't forward player's UUID

### ISSUE THREAD

**Issue by ClayCoffee** [SpigotMC/BungeeCord#3032]
I used a premium account to login the server(ip-forward: true). The ip forwards correctly. But the uuid displays in the subserver(bungeecord: true) is the offline one.

But when I set online-mode to true in the BungeeCord config, the uuid forwards correctly.

Sorry for my bad english :(

Bungeecord b1545 with PaperSpigot 1.15.2 b379

**Comment by Janmm14** [comment]
When you disable online mode in bungeecord, mojang is not asked on login and therefore all players get a different UUID which generated based on the name and not retrieved from mojang.

This is no bungeecord issue, it works as intended.
I suggest using a plugin like FastLogin.

For further help regarding setup of bungeecord please consult https://spigotmc.org forums.
