### ISSUE TITLE
BungeeCord api causing issues

### ISSUE THREAD

**Issue by KarmaConfigs** [SpigotMC/BungeeCord#3033]
Hi, I'm a plugin developer and the BungeeCord api is causing issues.

Why?

I'm using

```xml
<dependency>
    <groupId>net.md-5</groupId>
    <artifactId>bungeecord-api</artifactId>
    <version>1.16-R0.4-SNAPSHOT</version>
    <type>jar</type>
    <scope>provided</scope>
</dependency>
<dependency>
    <groupId>net.md-5</groupId>
    <artifactId>bungeecord-api</artifactId>
    <version>1.16-R0.4-SNAPSHOT</version>
    <type>javadoc</type>
    <scope>provided</scope>
</dependency>
```

And it works perfectly on vanilla BungeeCord, but some forks like Travertine or FlameCord, give errors with methods like

#PendingConnection.getSocketAddress ( NoSuchMethodError )

The problem is that BungeeCord 1.16-4 says that method exists, but in this api repository, it doesn't, making forks like Travertine build it without it.

**Comment by md-5** [comment]
>And it works perfectly on vanilla BungeeCord,

Well then it isn't an issue with BungeeCord

**Comment by KarmaConfigs** [comment]
But with its API, could you update the api in this repository so forks like Travertine and FlameCord won't give errors?

**Comment by md-5** [comment]
I'm not sure what you mean, the API in the repository is the API BungeeCord provides.
If forks are providing a different API, that's their issue.

**Comment by KarmaConfigs** [comment]
I think you didn't understand what's happening.

This API repo says PendingConnection doesn't has a method called getSocketAddress, but when using maven dependency of bungeecord 1.16-04, it says it exists.

( LoginEvent )
LoginEvent.getConnection().getSocketAddress()

**Comment by md-5** [comment]
It absolutely does, I just checked myself.

**Comment by KarmaConfigs** [comment]
What can I do to avoid that error?

Or do I have to wait for an update?

**Comment by KarmaConfigs** [comment]
![error](https://user-images.githubusercontent.com/54160333/106213378-d6ce5080-61cc-11eb-9d0e-7ad620975df6.png)

This is using latest BungeeCord release, with latest BungeeCord API

**Comment by Black-Hole** [comment]
The issue tracker for travertine is located at https://github.com/PaperMC/Travertine/issues

**Comment by KarmaConfigs** [comment]
> The issue tracker for travertine is located at https://github.com/PaperMC/Travertine/issues

As I said, the screenshot is using BungeeCord, not Travertine

**Comment by md-5** [comment]
Your screenshot literally shows `git-Travertine` in it

**Comment by KarmaConfigs** [comment]
I'll talk with the user who is reporting the issue, maybe this is an error

![discord](https://user-images.githubusercontent.com/54160333/106215306-efd90080-61d0-11eb-9026-4aae1e562958.png)

**Comment by KarmaConfigs** [comment]
You were right @md-5 

Sorry for disturbing you
