### ISSUE TITLE
could not BIND

### ISSUE THREAD

**Issue by YepMc** [SpigotMC/BungeeCord#3038]
server_connect_timeout: 5000
remote_ping_cache: -1
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: firesmpreal.apexmc.co:25880
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
ip_forward: false
remote_ping_timeout: 5000
prevent_proxy_connections: false
groups:
  md_5:
  - admin
connection_throttle: 4000
stats: 97b20226-52a9-4dbd-80b9-831f02652e9d
connection_throttle_limit: 3
log_pings: true
ALSO THE SERVER GETS STUCK ON LISTENING ON "21:09:32 [INFO] Listening on /0.0.0.0:25577"

**Comment by YepMc** [comment]
it makes no sense

**Comment by Janmm14** [comment]
Configuration problem. Ask for help in spigotmc.org forums for those.
