### ISSUE TITLE
Error this error keeps spamming console

### ISSUE THREAD

**Issue by OGTrey** [SpigotMC/BungeeCord#3044]
Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@75459c75, id=1, owner=net.sxlver.serverselectorbungee.ServerSelectorBungee@4879f0f2, task=net.sxlver.serverselectorbungee.ServerSelectorBungee$1@41813449, delay=5000, period=1000, running=true) encountered an exception

**Comment by md-5** [comment]
>net.sxlver.serverselectorbungee.ServerSelectorBungee

Issue with this plugin
