### ISSUE TITLE
Please update bungeecord.

### ISSUE THREAD

**Issue by AToska21** [SpigotMC/BungeeCord#3046]
From what i've heard, the sessionserver.mojang.com has been changed to session.minecraft.net. It is either down, or it is no longer responding.

Error: [SEVERE] Error authenticating ShortyShift with minecraft.net

I hope a update will fix the problem.

**Comment by md-5** [comment]
I don't believe it has; session.minecraft.net is the OLD session server, the new one is sessionserver.mojang.com and appears to currently work for me

**Comment by AToska21** [comment]
It still exists, and I think both should be tried to be used before it errors out.

**Comment by md-5** [comment]
Vanilla does not try both afaik
