### ISSUE TITLE
Keep players online when Bungee restarts?

### ISSUE THREAD

**Issue by tycrek** [SpigotMC/BungeeCord#3048]
Apologies if this is the wrong place to ask but I couldn't find anything for it in my searches.

Is there a way that I can keep players connected to target servers while the Bungee proxy is restarting? It would help minimize downtime for the users. Our target servers are not Spigot or Paper but rather are purely protocol based using [MCProtocolLib](https://github.com/Steveice10/MCProtocolLib)

**Comment by Paulomart** [comment]
You could kill the proxies listeners and restart another instance in the background. I believe there was a plug-in for that at some point. 

Or you setup a haProxy in front and do some custom routing.

**Comment by md-5** [comment]
Technologically impossible.

**Comment by Gandalf1783** [comment]
@tycrek you can have HAProxy to drain the proxies. Meaning, on stop, you would drain the proxies, wait until no players are online, then restart the proxies.
