### ISSUE TITLE
Memory leak related to scoreboards

### ISSUE THREAD

**Issue by Pjooo** [SpigotMC/BungeeCord#3049]
Hi,
I've had issues with memory and GC for last couple of days, and finally did Heap Dump. Results are in link below. It seems that bungee is capturing some scoreboard data, and not clearing it. 

Test was during night with ~80 players online.
Dump was made on newest version of bungeecord.
Java 11 Oracle.

To test if it's not my fault I tried:
- Removing all bungee plugins
- Removing Quickboard (because leak seems to be scoreboard related)
None of it helped.

Startup flags: `java -Xms10G -Xmx10G -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -jar bungee.jar`
However issue appears also with simple xms xmx without additional flags.

Here is heapdump: https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMS8wMy82Ly0taGVhcC0yMDIxLTAzLTA2XzAxLjE0LjE1LnppcC0wLTE4LTU5Lmpzb24=

**Comment by md-5** [comment]
Your issues with GC are from allocating 10 gb of ram when bungee needs about 0.5gb.

Bungee is not leaking scoreboards, you can see there are only 60 or so of them and they are all strong reachable from the 60 odd players online.

Probably I would guess you have a plugin on the server not deleting teams. Bungee has team deletion code fine, eg, https://github.com/SpigotMC/BungeeCord/blob/a7c6edeb638f0a2ba4fb051f2b0be5a6e226c955/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L204
