### ISSUE TITLE
Server Icon 

### ISSUE THREAD

**Issue by nolesnetworkPrincee** [SpigotMC/BungeeCord#3050]
I have an issue with my server icon. I use the correct dimensions and it does load and show on the server list but once you restart multiple times it becomes either a white screen or a default server icon.

![image](https://user-images.githubusercontent.com/73405092/110212680-4824b180-7ea5-11eb-92ba-eb71b3c50301.png)
![image](https://user-images.githubusercontent.com/73405092/110212694-5bd01800-7ea5-11eb-9632-2949a4ca6492.png)

**Comment by Black-Hole** [comment]
Please use the community support of the Spigot forums for help configuring your server and your plugins.
