### ISSUE TITLE
Fallback server not working

### ISSUE THREAD

**Issue by OllieJW** [SpigotMC/BungeeCord#3052]
I am not being sent to the hub on a restart

`prevent_proxy_connections: false
listeners:
- query_port: 25577
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  ping_passthrough: false
  priorities:
  - hub
  - survival
  bind_local_address: true
  host: 51.255.208.51:25565
  max_players: 250
  tab_size: 60
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: hub
  motd: '&1Another Bungee server'
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  OJWMine:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 20f87feb-91d7-435e-b958-afb3309ab9d5
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  hub:
    address: 104.223.80.142:25649
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
  survival:
    address: 66.248.194.82:25570
    restricted: false
    motd: '&1Just another BungeeCord - Forced Host'
`

**Comment by Janmm14** [comment]
@OllieJW delete the edit history of your post

**Comment by OllieJW** [comment]
> @OllieJW delete the edit history of your post

Doesnt let me
