### ISSUE TITLE
Can't connect to bungeecord after database crash

### ISSUE THREAD

**Issue by zopn333** [SpigotMC/BungeeCord#3056]
The server where database located has its disk full, after I solved this problem, I can't connect to bungeecord anymore. It just say "Can't connect to server", but I never changed address. And there's no error log on console. Can you figure out where the problem is?

**Comment by zopn333** [comment]
My bungeecord is on a server, and database is on another server.

**Comment by Janmm14** [comment]
Please use https://spigotmc.org forums for problems of this kind. This is not a forum.
