### ISSUE TITLE
How to make that bungee doesnt care about Scoreboards

### ISSUE THREAD

**Issue by OfflinePing** [SpigotMC/BungeeCord#3059]
Hey,
I got a plugin wich updates scoreboard alot, is there any way to disable that im getting kicked because of 
`IllegalArgumentException : Team BgbeSvKIzCjzERUg already exists in this scoreboard @ com.google.common.base.Preconditions:191`

**Comment by md-5** [comment]
Your plugin is broken

**Comment by OfflinePing** [comment]
that only happend after i installed bungeecord
(maybe Skript with Skore and TileManager says something to you)
