### ISSUE TITLE
Online mode bugged

### ISSUE THREAD

**Issue by Tervium** [SpigotMC/BungeeCord#3065]
Hello,I think I've found a bug, I've puchase Minecraft, install correctly BungeeCord and 2 server spigot, but when I attempt to connect to the server, BungeeCord return to me an error "Exception Connecting:QuietException : Server is online mode!".
If anyone have resolve this bug, he or she can anwser to this issue.
Bye.

PS: Sorry for my orthography, I'm 15 years old and I'm French.

**Comment by md-5** [comment]
No, bungee requires the backend servers to be offline mode
