### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by kingelectrixgyt** [SpigotMC/BungeeCord#3070]
10:27:06 [SEVERE] Exception in thread "main"
10:27:06 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
10:27:06 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
10:27:06 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:71)
10:27:06 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
10:27:06 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
10:27:06 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
10:27:06 [SEVERE] Caused by: while parsing a block mapping
 in 'reader', line 1, column 1:
    groups:
    ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 35, column 3:
      skyblock:
      ^

10:27:06 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
10:27:06 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
10:27:06 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
10:27:06 [SEVERE]     ... 4 more

[config.zip](https://github.com/SpigotMC/BungeeCord/files/6329411/config.zip)

**Comment by Janmm14** [comment]
> Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error **or see https://www.spigotmc.org/ for help**.

-> This is the wrong place to ask for help.

**Comment by kingelectrixgyt** [comment]
> > Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error **or see https://www.spigotmc.org/ for help**.
> 
> -> This is the wrong place to ask for help.

What do you mean? where should I ask then?

**Comment by Rabbit0w0** [comment]
If you have solved this problem then close this issue, if not, I will post a solution.

**Comment by Rabbit0w0** [comment]
On line 3, edit it to 

- admin

And fix your indentation
