### ISSUE TITLE
bungee not working 

### ISSUE THREAD

**Issue by Dhyanpatelhaker** [SpigotMC/BungeeCord#3071]
hi i dont know thats heppening can you help its showing

[SEVERE] Exception in thread "main" 
07:51:59 [SEVERE] java.lang.RuntimeException: Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see https://www.spigotmc.org/ for help.
07:51:59 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:73)
07:51:59 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:71)
07:51:59 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:272)
07:51:59 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
07:51:59 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
07:51:59 [SEVERE] Caused by: while parsing a block mapping
 in 'reader', line 21, column 2:
     Hub:
     ^
expected <block end>, but found '<block mapping start>'
 in 'reader', line 25, column 3:
      bedwars:
      ^

07:51:59 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
07:51:59 [SEVERE]     at org.yaml.snakeyaml.Yaml.load(Yaml.java:429)
07:51:59 [SEVERE]     at net.md_5.bungee.conf.YamlConfig.load(YamlConfig.java:70)
07:51:59 [SEVERE]     ... 4 more

help me

**Comment by Janmm14** [comment]
> Invalid configuration encountered - this is a configuration error and NOT a bug! Please attempt to fix the error or see **_https://www.spigotmc.org/ for help_**.
