### ISSUE TITLE
Waterfall error message "No client connected for pending server!"

### ISSUE THREAD

**Issue by IPv5** [SpigotMC/BungeeCord#3074]
I am getting an error of:
"No client connected for pending server!"
Quite often for players joining the lobby. I am using Waterfall with Forge support enabled. The lobby server uses Viaversion and ViaBackwards + VieRewind to enable older versions of MC to connect. I can't find much on what this error message means.

**Comment by md-5** [comment]
This is a Bungeecord issue tracker
