### ISSUE TITLE
ip forwarding bug?

### ISSUE THREAD

**Issue by Megapluto8** [SpigotMC/BungeeCord#3075]
So i just got a domain name that is hooked up to my bungee cord server using srv.
But when i try to join i get the error message saying 'if you wish to use ip forwarding please enable it in your bungeecord config as wel' even though i already enabled it on the bungee cord and paper server does anyone know how to solve this?

**Comment by Janmm14** [comment]
IP forwarding is a stable feature which does not randomly break.

**You did not properly set up bungeecord and spigot.**

1. BungeeCord should run on port 25565 or on the port configured in your SRV record.
2. Spigot servers should run on other ports
3. This is important to security:  The kick "If you wish to use IP forwarding, please enable it in your BungeeCord config as well!" does not protect your Spigot servers.
**You need to restrict access to these servers for example with a firewall (please see [firewall guide](https://www.spigotmc.org/wiki/firewall-guide/)).**
_When you attempt connect to the spigot server with its port directly and not through bungeecord, you have to make sure that you either do not reach it (timeout/connection refused) or that you get kicked by some IPWhitelist plugin.
4. When you are running a server older than 1.16.5 and you are not using a system firewall, consider installing the plugin [FakeMessageFix](https://www.spigotmc.org/resources/fakemessagefix.91779/).

Further help will be given by the community in [SpigotMC Forums](https://spigotmc.org). This is the wrong place.

**Comment by Chuanwise** [comment]
If I really need to disable `ip_forward`, how can I do? I met `If you wish to use IP forwarding, please enable it in your BungeeCord config as well!`.

**Comment by Janmm14** [comment]
@Chuanwise Please use spigotmc.org forums for questions and configuration help.
