### ISSUE TITLE
io.netty.util.IllegalReferenceCountException

### ISSUE THREAD

**Issue by 96DarkCode96** [SpigotMC/BungeeCord#3081]
Hello guys! I'm trying to make a custom bungeecord, because I need to remove some messages and add some cool stuff. Now, if I connect to my bungeecord, everything is working, but it isn't able to send me to my spigot server. I add a line to see the full error. Error doesn't crash bungeecord, but only disconnect player. Is here somebody, who knows why is this error happening and how to repair it ? Thanks. 96DarkCode96

Info:
io.netty:netty-all:4.1.58.Final   <- io.netty dependency
https://pastebin.com/J17cNngv  <- Error
https://pastebin.com/85UMLMXU <- Config

**Comment by md-5** [comment]
We can't support bugs you've introduced yourself lol

**Comment by Janmm14** [comment]
For help in coding questions you can use spigotmc.org forums.
