### ISSUE TITLE
Extending YamlConfiguration

### ISSUE THREAD

**Issue by bigstartoto** [SpigotMC/BungeeCord#3085]
I'm trying to make a plugin which wrap around YamlConfiguration for my custom configuration format. but I can't extends it because it have `@NoArgsConstructor(access = AccessLevel.PACKAGE)`.

`'YamlConfiguration()' is not public in 'net.md_5.bungee.config.YamlConfiguration'. Cannot be accessed from outside package (package-private)`
The spigot YamlConfiguration does not contains AccessLevel.

Any workaround? or I need to just use Reflection?

**Comment by Janmm14** [comment]
If you have a custom configuration format, you should not extend `YamlConfiguration`, but `ConfigurationProvider`.

**Comment by bigstartoto** [comment]
Ah, got it working with another format. Thanks.
Can I also know why `@NoArgsConstructor(access = AccessLevel.PACKAGE)` is there but not in Bukkit/Spigot. I know it's not the same thing but it is pretty similar.

Example If I still want to use Yaml format and how can I extends it?
