### ISSUE TITLE
Decoder Exception

### ISSUE THREAD

**Issue by imperialedge** [SpigotMC/BungeeCord#3094]
Hello! this is imperialedge and i would like some help on this matter.So whenever i try to log into my newly made bungee server it gives me a error ;-
[IMPERIALEDGE] disconnected with: DecoderException : net.md_5.bungee.protocol.OverflowPacketException: Cannot receive string longer than 256 (got 342 characters) @ io.netty.handler.codec.MessageToMessageDecoder:98

I am getting this error both in my mc and my server console.

Thanks in advance !

**Comment by imperialedge** [comment]
This is my config.yml

server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: true
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:36428
  max_players: 30
  motd: '&1Another Bungee server'
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 36428
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: true
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: c4b9cabb-93e9-4bce-93ab-4b18642e6f3e
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: free1.idley.gg:36426
    motd: '&1Just another BungeeCord - Forced Host'
    restricted: false

**Comment by Janmm14** [comment]
@imperialedge 
Use Bungeecord Build 1567 until this issue is fixed: https://ci.md-5.net/job/BungeeCord/1567/

@md-5 
That strict string length limit may only apply if direction is not TO_CLIENT:
https://github.com/SpigotMC/BungeeCord/blob/master/protocol/src/main/java/net/md_5/bungee/protocol/packet/Chat.java#L40-L52

**Comment by imperialedge** [comment]
Thanks for responding so fast!

**Comment by md-5** [comment]
Apologies, fixed
