### ISSUE TITLE
Teleporting Issue

### ISSUE THREAD

**Issue by coco0325** [SpigotMC/BungeeCord#3103]
https://github.com/PaperMC/Waterfall/issues/652
https://github.com/masagameplay/MaSuiteWarps/issues/15

BungeeCord might changed something that broke the cross server teleportation.

**Comment by md-5** [comment]
Linking two other issues it not a bug report.
It's not even clear to me what 'Players only be sent to the target server but not target location after cross server teleport.' is meant to mean or how it is a bug --- bungeecord only sends people to target servers, there is no way to send people to a specific location without a plugin on the target server doing that.

**Comment by coco0325** [comment]
The plugin is broken after I upgrade BungeeCord to a newer version, I think there must be something changed and caused this.

**Comment by Janmm14** [comment]
Then please find the last bungeecord build it worked / the firstit doesn't work anymore.
