### ISSUE TITLE
netty issues

### ISSUE THREAD

**Issue by Ironic8b498** [SpigotMC/BungeeCord#3106]
last known working version for me was 1558, just tried 1576 and I get this https://paste.helpch.at/qayazifuxa.makefile

**Comment by md-5** [comment]
What exactly is the issue? You have your log level set to FINE which is showing heaps of debug information. I don't see any actual errors.

**Comment by Ironic8b498** [comment]
everything seems to work, how would I change the fine log level?

**Comment by md-5** [comment]
FINE isn't the default for bungee, so you must have a panel or start up script changing it
