### ISSUE TITLE
stdin proxy command

### ISSUE THREAD

**Issue by quequiere** [SpigotMC/BungeeCord#3110]
Hi, I need to send command to bungee proxy instance via 'stdin' directly to my java instance.
The problem is that bungee proxy use 'jline' and this one is not linked with 'stdin'

Do you have a solution to that problem ?

**Comment by quequiere** [comment]
`while ( bungee.isRunning && ( line = bungee.getConsoleReader().readLine( ">" ) ) != null )
            {
                if ( !bungee.getPluginManager().dispatchCommand( ConsoleCommandSender.getInstance(), line ) )
                {
                    bungee.getConsole().sendMessage( new ComponentBuilder( "Command not found" ).color( ChatColor.RED ).create() );
                }
            }`

My problem is here, console reader should be linked to stdin too :(

**Comment by Janmm14** [comment]
The `ConsoleReader` of jline is (by default) linked to `FileDescriptor.in`.

Could be that you don't send to stdin correctly.

**Comment by quequiere** [comment]
The problem is that I need to send my command from a NodeJS program directly to the JAVA instance :S That's why I need to use stdin :(

**Comment by Janmm14** [comment]
Can you try starting BungeeCord with `-Djline.terminal=jline.UnsupportedTerminal`

**Comment by quequiere** [comment]
> Can you try starting BungeeCord with `-Djline.terminal=jline.UnsupportedTerminal`

Yeah ! Worked Thx you !!!! Maybe we can add this issue in bungee readme ;)
