### ISSUE TITLE
[performance] JDK14LoggerAdapter class creates many exceptions

### ISSUE THREAD

**Issue by lokha** [SpigotMC/BungeeCord#3112]
this is a record place for the number of exceptions:  
![image](https://user-images.githubusercontent.com/32991511/121730632-9ecf0680-caf8-11eb-95bd-e2eedec72133.png)

**Comment by Janmm14** [comment]
Exceptions in BungeeCord can happen because of wrong data input. High exception amount is no issue in itself.
The JDK14Loggeradapter IS certainly not throwing exceptions.
If you want certain exceptions to be looked at, post exceptions and not some useless overview.

**Comment by lokha** [comment]
my screenshot shows a stack that demonstrates the source of exceptions

**Comment by lokha** [comment]
these exceptions have no message. all that is is their quantity and source is the method - `org.slf4j.impl.JDK14LoggerAdapter.fillCallerData(String, LogRecord)`

**Comment by lokha** [comment]
I am not saying that these exceptions are outside the scope of this method. I'm just talking about the fact of their occurrence and their large number.

**Comment by Janmm14** [comment]
@lokha
Can you please just open your bungeecord log file and look which exceptions are actually spammed?

The source cannot be `org.slf4j.impl.JDK14LoggerAdapter.fillCallerData(String, LogRecord)`. That method, even the whole class is NEVER calling `new Throwable()`.

**Comment by Janmm14** [comment]
The method `org.slf4j.impl.JDK14LoggerAdapter.fillCallerData(String, LogRecord)` is NOT throwing exceptions. The method is just creating exceptions to get the stack trace.

**Comment by lokha** [comment]
> The method `org.slf4j.impl.JDK14LoggerAdapter.fillCallerData(String, LogRecord)` is NOT `throw`ing exceptions. The method is just creating exceptions to get the stack trace.

yes, that's right. there are no exceptions in the console.

a large number of exceptions can affect performance. it doesn't matter if these exceptions are published to the console or not

however, if it was intended to do so, then it is your right

**Comment by md-5** [comment]
What plugin do you have that is using slf4j, bungee doesn't use it by default at all

**Comment by lokha** [comment]
my own https://github.com/lokha/spigot-logger-for-bungee
