### ISSUE TITLE
[performance] PacketDecompressor -> out.add( in.slice().retain() ); allocates a lot of memory

### ISSUE THREAD

**Issue by lokha** [SpigotMC/BungeeCord#3113]
I measured bungeecord performance on my server with a profiler
and found that the largest memory allocation location is:

https://github.com/SpigotMC/BungeeCord/blob/b7935d4b1437bd03e8063df584cbf917894bfdd3/proxy/src/main/java/net/md_5/bungee/compress/PacketDecompressor.java#L34

25% of all bungeecord memory is allocated at this point in the code:  
![image](https://user-images.githubusercontent.com/32991511/121770501-4f2d2100-cb72-11eb-988d-7e5754c7c5c3.png)

I looked at the code and thought that maybe there is a way to simplify the code

from:
```
out.add( in.slice().retain() );
in.skipBytes( in.readableBytes() );
```

to:
```
out.add( in.retain() );
```

i tested this change, bungeecord doesn't break from it.
however I am not that good at netty to be sure that this is a good solution.

**Comment by md-5** [comment]
I'm not sure this is right, a slice does not do any memory allocation and also I would expect your code to break bungee....

**Comment by md-5** [comment]
Ok looking closely I think your fix is valid but I'm still confused/surprised at what your memory allocator is showing given slice isn't meant to affect memory allocation: 
```Returns a slice of this buffer's sub-region. Modifying the content of the returned buffer or this buffer affects each other's content while they maintain separate indexes and marks.```

**Comment by lokha** [comment]
during the work of the profiler on the bungeecord there were about 500 online

most likely this code is called very often:  
```
out.add( in.slice().retain() );
in.skipBytes( in.readableBytes() );
```

method `slice` create objects of type `io.netty.buffer.AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf`

**Comment by md-5** [comment]
>  it is only about these objects, not the internal byte array. they themselves allocate memory. 48 bytes for each object

Ah I see.

Thanks, I've pushed your suggestion. Please let us know if you find anything else!
