### ISSUE TITLE
i cant join my bungee server

### ISSUE THREAD

**Issue by byTimleo** [SpigotMC/BungeeCord#3119]
[Bungee-1]13:10:36 [WARNING] A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@12ff6d28

[Bungee-1]java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')

[Bungee-1] at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:531)

[Bungee-1] at net.md_5.bungee.UserConnection.init(UserConnection.java:164)

[Bungee-1] at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:530)

[Bungee-1] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)

[Bungee-1] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)

[Bungee-1] at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)

[Bungee-1] at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)

[Bungee-1] at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)

[Bungee-1] at java.base/java.lang.Thread.run(Thread.java:830)

**Comment by Janmm14** [comment]
Config section permissions is invalid.

For further help regarding configuration problems please use https://spigotmc.org forums

**Comment by byTimleo** [comment]
Hey, and can you say how i can fix this?

Von: ***@***.***>
Gesendet: Dienstag, 15. Juni 2021 20:00
An: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Betreff: Re: [SpigotMC/BungeeCord] i cant join my bungee server (#3119)


Config section permissions is invalid.

For further help regarding configuration problems please use https://spigotmc.org forums

**Comment by Rabbit0w0** [comment]
Post your config
