### ISSUE TITLE
Kotlin coroutine and threads problem

### ISSUE THREAD

**Issue by Luluno01** [SpigotMC/BungeeCord#3122]
Hi, I am using Kotlin to write plugins for a while. I noticed that [creating threads is discouraged](https://www.spigotmc.org/wiki/common-development-pitfalls-bungeecord/#creating-new-threads). Here is the problem: if this means Kotlin coroutine is also discouraged?

**Comment by md-5** [comment]
From the page you linked:
```
If the (external) API offers the ability to provide an Executor or ExecutorService, provide it your Plugin.getExecutorService().
```

Which apparently is possible with Kotlin using .asCoroutineDispatcher

**Comment by Luluno01** [comment]
Thanks for your reply. The `getExecutorService` method is, however, marked as "deprecated". Any plan to remove deprecated annotation or provide alternative solution?

**Comment by Janmm14** [comment]
Just use it. The method is probably deprecated just to discourage devs to use it directly.

**Comment by Luluno01** [comment]
> Just use it. The method is probably deprecated just to discourage devs to use it directly.

Sounds "probably" fine lol. Thanks!
