### ISSUE TITLE
Exception when running bungeecord

### ISSUE THREAD

**Issue by BrennoMaturino1** [SpigotMC/BungeeCord#3127]
Whenever i try to run bungeecord i get the error

class java.lang.String cannot be cast to class java.util.Collection (java.lang.String and java.util.Collection are in module java.base of loader 'bootstrap')
[config.txt](https://github.com/SpigotMC/BungeeCord/files/6689147/config.txt)

**Comment by Janmm14** [comment]
Misformatted configuration. Yaml is sensitive to spaces.
Lines 11 - 12 need to be 
```yaml
  - queue
  - main
```
