### ISSUE TITLE
Possible IPV6?

### ISSUE THREAD

**Issue by Widayn** [SpigotMC/BungeeCord#3132]
When I tried to use IPV6 address on my config.
12:15:07 [严重] Caused by: while parsing a flow node
 in 'reader', line 14, column 10:
      host: [::]:25565
             ^
expected the node content, but found ':'
 in 'reader', line 14, column 10:
      host: [::]:25565

**Comment by Janmm14** [comment]
Put it in quotes, e.g. `"[::]:25565"`
