### ISSUE TITLE
Netty renamed leakDetection property

### ISSUE THREAD

**Issue by Janmm14** [SpigotMC/BungeeCord#3138]
It is now `-Dio.netty.leakDetection.level`, before it was `io.netty.leakDetectionLevel`
The code in https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/BungeeCord.java#L259-L262 should be edited to either check for both flags or only the new one.

See https://netty.io/wiki/reference-counted-objects.html#leak-detection-levels

**Comment by MrIvanPlays** [comment]
netty already checks the old flag, but puts priority to the new one. this should be mentioned too
