### ISSUE TITLE
Other players are not rendered

### ISSUE THREAD

**Issue by Nether2046** [SpigotMC/BungeeCord#3143]
Before the upgrade, other players were being rendered, but after the upgrade, players other than myself are no longer being rendered. (This happens not on the main server, but on Second-server)
Bungeecord's Online-mode is true.
All plugins are compatible with 1.17, and Bungeecord is not interfered by plugins.

## Version
Spigot 1.17
BungeeCord #1591

**Comment by md-5** [comment]
Cannot reproduce. Is ip forwarding enabled?
