### ISSUE TITLE
If player dies inside spigot server and kept on death screen the player will get kicked with disconnected with: ReadTimeoutException : null

### ISSUE THREAD

**Issue by ham1255** [SpigotMC/BungeeCord#3146]
as title says here is a video: [click here](https://www.youtube.com/watch?v=oL6cLLf1VwI)

# what i have tried so far:
1. disable all plugins on proxy(bungeecord) and spigot servers
2. check if am running any proxy forks (waterfall) if i do switch it to bungeecord, same goes to spigot too.
3. created fresh and running test setup proxy setup with test spigot server
# what console shows when disconnected:
```
19:01:50 [INFO] [Ham1255] <-> ServerConnector [test1] has connected
19:02:00 [WARNING] [Ham1255] <-> DownstreamBridge <-> [test1] - read timed out
19:02:00 [INFO] [Ham1255] disconnected with: ReadTimeoutException : null
19:02:00 [INFO] [Ham1255] -> UpstreamBridge has disconnected
19:02:00 [INFO] [Ham1255] <-> DownstreamBridge <-> [test1] has disconnected
```
## Bungeecord version: [#1593](https://ci.md-5.net/job/BungeeCord/1593/)
not sure if if this bungeecord issue or spigot since spigot server logs says when kick happens
```
[19:22:04] [Server thread/INFO]: Ham1255 fell out of the world
[19:22:04] [Server thread/INFO]: Killed Ham1255
[19:22:15] [Server thread/INFO]: Ham1255 lost connection: Disconnected
[19:22:15] [Server thread/INFO]: Ham1255 left the game
```
one of spigot forks output
```
[19:01:50 INFO]: Ham1255[/127.0.0.1:49543] logged in with entity id 1 at ([test]222.00844959612, 72.0, -243.72180147943428)
[19:02:00 INFO]: Ham1255 lost connection: Disconnected
[19:02:00 INFO]: Ham1255 left the game
```
which is pretty normal.

I don't know what is wrong if this issue on my side please tell me.

**Comment by Outfluencer** [comment]
witch minecraft version was the client?

**Comment by ham1255** [comment]
First verdion i treied was 1.17
Then later 1.16 but issue seem to happen when 1.17 support added

**Comment by Janmm14** [comment]
First, please showe your bungeecord config timeout value.

There was a change to Timeout behaviour in that timeframe between 1.16 and 1.17, which was required to fix an attack vector.
Can you please check with Bungeecord [1557](https://ci.md-5.net/job/BungeeCord/1557/) an [1558](https://ci.md-5.net/job/BungeeCord/1558/) to see if hte issue was introduced with BungeeCord 1558?

**Comment by ham1255** [comment]
its default value:

timeout: 30000

and issue seems to be stoped after using 1557

**Comment by ham1255** [comment]
# Update:
after some research to fix this, since i am using linux as my main os, I told myself let me try windows. so i ran windows suddenly the issue went away on windows. but returning to linux issue was there. so hmmm i think i might have problem with my installtion.
so i got another device. and ubuntu iso ready to install and when install finished and tested the issue was there.
so hmm i told myself, it could something else. and went to the shell and i wrote
```
apt-get update && apt-get upgrade 
```
and issue was solved! I think it could some program had effect with networking?

**Comment by Janmm14** [comment]
@ham1255 you can close it yourself
