### ISSUE TITLE
Move /ip to it's own module

### ISSUE THREAD

**Issue by bigfinfrank** [SpigotMC/BungeeCord#3149]
It seems that /ip isn't contained within any module (I've removed all modules from modules.yml yet /ip remains functional) and is a part of BungeeCord itself. Would it be possible for this to be moved to it's own module instead of being built into BungeeCord so that it can be removed?

**Comment by Janmm14** [comment]
I suggest using config option disabled_commands

**Comment by bigfinfrank** [comment]
> 
> 
> I suggest using config option disabled_commands

Don't know how I missed that, thanks!
