### ISSUE TITLE
Update dependencies to support java 16

### ISSUE THREAD

**Issue by Sneakometer** [SpigotMC/BungeeCord#3155]
Hey, i'm developing for Bungeecord/Waterfall and noticed that gson does not work properly when using Java 16.
When trying to parse objects that contain instances of the java.time.LocalDate class an exception is thrown:

`java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.time.LocalDate java.time.LocalDateTime.date accessible: module java.base does not "opens java.time" to unnamed module @2a79781f`

I suspect the cause to be some outdated GSON or GUAVA library bundled with BungeeCord.
Thanks for help.

**Comment by md-5** [comment]
Updating will not fix this issue 
https://github.com/google/gson/issues/1807
