### ISSUE TITLE
Players invisible 1.17.1

### ISSUE THREAD

**Issue by Bobby99as** [SpigotMC/BungeeCord#3159]
After playing the game for a while people just started going invisible after restarting the proxy it did not fix. Now If I bypass the proxy and have people join the main game it doesn't happen

**Comment by Anarchist-byte** [comment]
I have this problem too.

**Comment by l8c4s** [comment]
Hey , I have same problem... Do you know what is it today?

**Comment by l8c4s** [comment]
Hello! this bug is not because is not same ip , it's because in spigot.jar you don't activate bungeecord


bungeecord=true (false per default)

**Comment by H3xX4** [comment]
it's in the spigot.yml, just that no one is confused, but other than that, l8c4s was right.
