### ISSUE TITLE
BungeeCord can't get kick message from subserver.

### ISSUE THREAD

**Issue by FBioCS1** [SpigotMC/BungeeCord#3160]
BungeeCord version: #1595
Running paper 1.16.5 #762, Java 16

## Issue: When a player is refused by the subserver for some reason
( for example, refused by Authme, for using an illegal username),
The subserver's console can display the right message. 
![unknown](https://user-images.githubusercontent.com/73772910/125947191-d2b72c25-9144-4870-ad4c-e415dd22d4ee.png)

but waterfall can't get the right reason for "lost connection". It just displays "could not connect to a default or fallback server".
![unknown](https://user-images.githubusercontent.com/73772910/125947429-e031fae3-2d77-4524-9991-6c65c1094e15.png)

This caused my players to be unable to know the specific reason why they were disconnected. Everyone thought that the server had not been started yet.
I have developed a plug-in to verify some user information, and use the disallow method ( I have also tried player.kick method) to deny players who do not meet the requirements to enter. Waterfall also cannot obtain this information. Only the console of the subserver can correctly output the reason for the disconnection.

**Comment by md-5** [comment]
This is neither a waterfall nor paper bug tracker

**Comment by Janmm14** [comment]
above he wrote the bungeecord version he used. could just be that he usually uses waterfall and accidentally wrote waterfall later on

**Comment by FBioCS1** [comment]
This issue is solved, it's caused by a Bungee Plugin named BungeeKick which can teleport players back to the lobby when a server is closed or crashed. It doesn't support Java16 or is no longer a cooperator with newer versions of Bungee I think.
