### ISSUE TITLE
I don't know why is this happening when enter a no premium user

### ISSUE THREAD

**Issue by Aitooor** [SpigotMC/BungeeCord#3167]
EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.TitleTimes in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

**Comment by Krunkor** [comment]
EncoderException : java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.TitleTimes in phase GAME with direction TO_CLIENT @ io.netty.handler.codec.MessageToByteEncoder:125

**Comment by Janmm14** [comment]
My guess its a bungee plugin problem
