### ISSUE TITLE
TCPShield / ProtocolLib Issue

### ISSUE THREAD

**Issue by Unboxin** [SpigotMC/BungeeCord#3171]
There's an issue on my server which wont let players connect and it only happens when I have ProtocolLib And TCPShield both enabled ( Server works perfectly when I remove any one or both of those plugins ) 
This is basically the error: https://pastebin.com/jzbfVBMk
Plugins I use are :
`LuckPerms, WorldEdit, PlaceholderAPI, ColorMOTD, BuycraftX, Votifier, KiteBoard, VoteParty, ProtocolLib, WorldGuard, Multiverse-Core, Gatekeeper, ChatReaction, SkinsRestorer, DeluxeTags, Vouchers, Vulcan, TCPShield, EnchantPlus, StaffChat, Vault, InstantVoid, LPC, SimpleSit, PluginHider, FastLogin, CombatTagPlus, EnderPearlCoolDown, Essentials, EpicRename, HolographicDisplays, ActionHealth, PlayerPoints, AuctionHouse, ajLeaderboards, EssentialsChat, BattleLevels, TAB, PlayerVaults, SuperVanish, Bounty, EssentialsSpawn, BLP, AuthMe, SpecializedCrates, LiteBans`
Server is 1.8 and cracked

**Comment by md-5** [comment]
If it's caused by plugins how is it a bungee issue?
