### ISSUE TITLE
Copy server

### ISSUE THREAD

**Issue by Timtaran** [SpigotMC/BungeeCord#3172]
Hello, for start, I'm Russian and I bad in English.

So I have 3 free mc servers, I want to connect this servers to create 1 server with synchronize world and maybe players. I want do it because at random time one of 3 server fall down.

Can I do it with BungeeCore(I dont see questions like this in Internet)

**Comment by Janmm14** [comment]
Bungeecord does not synchronize anything. You'd need someone to create a separate spigot plugin for that.

Better solution would be to fix the server so its not going down. You could use Bungeecord with a fallback server and use a bungee plugin to make players get kicked to fallback and can wait ingame while the main server restarts.

**Comment by Timtaran** [comment]
Ok, thanks for answer.
