### ISSUE TITLE
After the player lose connection, may not be able to join the server and cannot be kicked out

### ISSUE THREAD

**Issue by MeowRay** [SpigotMC/BungeeCord#3179]
![image](https://user-images.githubusercontent.com/29674595/130390063-76d93d04-9470-48bd-8243-1cd50e0f3925.png)
I can't confirm the reproduction conditions
Rejoining the server will be kicked out because the player already exists on the server

**Comment by nseveryns** [comment]
That doesn't look default. I'm fairly sure md5 and the other contributors are not going to be able to replicate this. Try doing a full restart, remove plugins, and check console for error messages if you want a fully accurate debug.

**Comment by MeowRay** [comment]
> That doesn't look default. I'm fairly sure md5 and the other contributors are not going to be able to replicate this. Try doing a full restart, remove plugins, and check console for error messages if you want a fully accurate debug.

![image](https://user-images.githubusercontent.com/29674595/130411829-50ce6161-0487-4518-a2be-6facb7303e0c.png)
![image](https://user-images.githubusercontent.com/29674595/130411840-c7f8e09d-f6cd-4a0c-ae8e-039359b0c9c8.png)
isConnected is false but the player still exists on the server

**Comment by nseveryns** [comment]
Logs @MeowRay please

**Comment by MeowRay** [comment]
[https://github.com/SpigotMC/BungeeCord/issues/3177](url)Suggestion
