### ISSUE TITLE
Players are invisible when server has not the same IP as proxy

### ISSUE THREAD

**Issue by titivermeesch** [SpigotMC/BungeeCord#3182]
I have 2 dedicated servers:

1 holds Bungeecord and a few other servers (IP 1)
1 just holds an empty server without any plugins for testing purposes (IP 2)

I can correctly connect to the second server and back, everything works fine there, but nobody sees each other, we are all invisible.

```
bind_local_address: false (but issue remains when true)
ip_forward: true
online_mode: true
```

What am I missing?

Could be related to #2942

**Comment by l8c4s** [comment]
Hello! this bug is not because is not same ip , it's because in spigot.jar you don't activate bungeecord

bungeecord=true (false per default)

**Comment by titivermeesch** [comment]
Apparently that server didn't have it yet. Thanks
