### ISSUE TITLE
You are already connected to this server!

### ISSUE THREAD

**Issue by WorkWolf2** [SpigotMC/BungeeCord#3184]
i am creating a bungeecord server. I can easily connect to the Hub, but I cannot connect to the other servers: You already connected to this Server! Is there any way to fix?

**Comment by Janmm14** [comment]
You did not set up the ip addresses and ports of your other servers correctly.

**Comment by KneesDev** [comment]
Nope, I'm experiencing the same issue. Everything is setup properly. Hub and survival works but LNET01 server doesn't

**Comment by Janmm14** [comment]
> Nope, I'm experiencing the same issue. Everything is setup properly. Hub and survival works but LNET01 server doesn't

Thousands of servers are using bungeecord. I tell you, I am positive this is a configuration fault, not a problem of bungee.
Feel free to send your config files, maybe in a discord dm if you dont want it public and I take a short look.

**Comment by KneesDev** [comment]
Here's the BungeeCord configuration. Note that 2 out of 3 servers function and they share a very similar, almost exact, server.properties - spigot.yml and paper.yml configuration, with only IPs, ports, and other server-related information changing.

I've uploaded the config on Pastebin.com and you can find it [here](https://pastebin.com/AFjEwHSn).

**Comment by Janmm14** [comment]
> Here's the BungeeCord configuration. Note that 2 out of 3 servers function and they share a very similar, almost exact, server.properties - spigot.yml and paper.yml configuration, with only IPs, ports, and other server-related information changing.
> 
> I've uploaded the config on Pastebin.com and you can find it [here](https://pastebin.com/AFjEwHSn).

As your bungee and spigot servers run on the same machine, put in `127.0.0.1` as IP for the servers instead of `143.x.x.x`.

Also you did not follow the [firewall guide](https://www.spigotmc.org/wiki/firewall-guide). Set `server-ip=127.0.0.1` in `server.properties` files of your spigot servers.

Also I am unable to join your server neither with 1.19.4 nor 1.20.1 client claiming I didnt use a client inside 1.10-1.20 range.

**Comment by KneesDev** [comment]
Oh, that was you joining. Also you should've been able to join since there's ViaVersion installed.

**Comment by KneesDev** [comment]
> As your bungee and spigot servers run on the same machine, put in `127.0.0.1` as IP for the servers instead of `143.x.x.x`.
> 
> Also you did not follow the [firewall guide](https://www.spigotmc.org/wiki/firewall-guide). Set `server-ip=127.0.0.1` in `server.properties` files of your spigot servers.

I'm using Pterodactyl so I have to use the public IP

**Comment by KneesDev** [comment]
Yup, when using 127.0.0.1 on both server-ip and servers in bungee config it connects me to a fallback server.

**Comment by Janmm14** [comment]
If you are using pterodactyl, you should follow their recommendations: https://pterodactyl.io/community/games/minecraft.html#configuring-a-server-network-bungeecord-waterfall-hexacord-etc

**Comment by KneesDev** [comment]
Do you think I haven't followed their "recommendations"?

**Comment by Janmm14** [comment]
> Do you think I haven't followed their "recommendations"?

It seems you didn't even read it

**Comment by KneesDev** [comment]
> It seems you didn't even read it

I did read it. I had already setup the firewall properly. If I didn't read the docs, explain how the lobby and survival servers work and work with BungeeCord.

Anyways, what am I supposed to do to have this fixed? Firewall properly setup, 2 out of 3 servers work, same configuration for all servers. It just doesn't make sense.
