### ISSUE TITLE
Why do servers have to be set to offline mode?

### ISSUE THREAD

**Issue by sh0tx420** [SpigotMC/BungeeCord#3194]
Everyone suggests that the minecraft servers should set online-mode to false in server.properties and true in the bungeecord configuration, but nobody has ever explained why. Can someone elaborate exactly why we **have** to set our servers to offline mode in order for them to work?

EDIT: Also setting online-mode to false in server.properties causes the player data to wipe unless i switch it back to true for some reason

**Comment by Janmm14** [comment]
First of all, this does not belong into an ISSUE. Next time please ask such things in https://spigotmc.org forums.

Bungeecord does not and cannot act like an authenticated minecraft client. (If it could, that would be a huge security issue, as servers could impersonate their players on other servers)
That is why bungeecord connects with online-mode false.

However bungeecord added ip_forwarding mode, which forwards player uuid and ip address in a custom format to the target server.

For vanilla there are probably mods by some third-party which can decode this data, so it will not wipe player data, but decode uuid and ip correctly.

For spigot, one can go into spigot.yml and enable bungeecord mode to decode that extra data.

## Security warning if bungeecord support enabled
You need to make sure that nobody can directly connect to your backend minecraft servers or they can impersonate everyone.
See: https://github.com/SpigotMC/BungeeCord#security-warning
And for detailed information on fix possibilities: https://www.spigotmc.org/wiki/firewall-guide/
