### ISSUE TITLE
Support Nginx IP forward headers

### ISSUE THREAD

**Issue by weihao** [SpigotMC/BungeeCord#3212]
passing `X-Real-IP` and `X-Forwarded-For` to bungeecord will cause a broken pipe and header. Can we support Nginx TCP proxy forward Client IP?

**Comment by Janmm14** [comment]
`X-Real-IP` and `X-Forwarded-For` are http headers. Not sure what you want with those in ther minecraft protocol.

Instead of Nginx, use HAProxy. The proxy protocol is supported by bungeecord if you enable it and it is a software MEANT for the use case.

**Comment by md-5** [comment]
Sorry what? HTTP headers?

Bungee supports the standard proxy protocol which is definitely supported by HAProxy and seems nginx too with the correct option: https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_protocol

**Comment by weihao** [comment]
> Sorry what? HTTP headers?
> 
> Bungee supports the standard proxy protocol which is definitely supported by HAProxy and seems nginx too with the correct option: https://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_protocol

Sorry I didn't state this clearly in the original post.

> Can we support Nginx TCP proxy forward Client IP?

what i meant was the support for [ngx_stream_realip_module](http://nginx.org/en/docs/stream/ngx_stream_realip_module.html)

Nginx has `stream` for TCP connections

**Comment by md-5** [comment]
Yes, bungee supports that with the proxy protocol option in config.yml
