### ISSUE TITLE
Bungeecord on newest w/ 1.18 does not allow client access

### ISSUE THREAD

**Issue by CraftingMagic-Skyy** [SpigotMC/BungeeCord#3217]
![bungee1](https://user-images.githubusercontent.com/69261008/144091906-36b5c140-5c40-4fbb-915c-c5e145042155.png)
![bungee2](https://user-images.githubusercontent.com/69261008/144091940-956e69dc-6f2d-4d8e-b996-3465027c031b.png)
[bungeelog.txt](https://github.com/SpigotMC/BungeeCord/files/7627392/bungeelog.txt)

Bungeecord updated with newest version from not even an hour ago

clients cannot connect still (See images and log added)

**Comment by p1xmedia** [comment]
Same error ... not Compatible

**Comment by md-5** [comment]
Your log shows 1.17 modules. What version exactly are you running?

**Comment by CraftingMagic-Skyy** [comment]
https://ci.md-5.net/job/BungeeCord/ - #1616 version

**Comment by md-5** [comment]
Works fine for me, post your FULL log

**Comment by CraftingMagic-Skyy** [comment]
That BungeeLog was the entire startup from start to finished loading... I even triple checked I had the latest from the Jenkins and heres another from start to full loaded log:
[bungeelog.txt](https://github.com/SpigotMC/BungeeCord/files/7629046/bungeelog.txt)

**Comment by md-5** [comment]
30.11 21:36:45 [Server] INFO Enabled BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:98afd54:**1615**


See how it says '1615' and 1.18 support was added in '1616'

**Comment by CraftingMagic-Skyy** [comment]
Hmmm ok its weird then, on Jenkins, if I get BungeeCord.jar from under "Last Successful Artifacts" it will work
But if for some reason someone clicks on "Last build (#1616), 5 hr 42 min ago" it will give them 1615....

Regardless its working now....

**Comment by Janmm14** [comment]
> Hmmm ok its weird then, on Jenkins, if I get BungeeCord.jar from under "Last Successful Artifacts" it will work But if for some reason someone clicks on "Last build (#1616), 5 hr 42 min ago" it will give them 1615....
> 
> Regardless its working now....

Maybe some cloudflare cache problem
