### ISSUE TITLE
Spectator menu teleporting is not working

### ISSUE THREAD

**Issue by xIGBClutchIx** [SpigotMC/BungeeCord#3223]
Unable to use the spectator teleport to player menu when the server is behind Bungeecord.

I assume we will need an entity map for 1.18/1.18.1 like [here](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap_1_16.java#L172)
That check also has if IP forwarding is disabled but I have it enabled in the config: `ip_forward: true`.

Bungeecord version: git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:1ad8150:1619

**Comment by md-5** [comment]
There is an entity map https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/entitymap/EntityMap_1_16_2.java#L19

**Comment by xIGBClutchIx** [comment]
Ah wow looked through most of them but that one. Glad that was fixed though, thanks!
