### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by BOSCUBE** [SpigotMC/BungeeCord#3224]
i can't set up my bungeecord server, don't know if I'm doing something wrong or not as I followed my hosting tutorial,i added my logs from console, a screenshot as well as my config.yml and serverproperties file

![error](https://user-images.githubusercontent.com/96257760/146421892-6240760d-e459-4dcb-afd0-ae98dacaed5d.png)
[console.txt](https://github.com/SpigotMC/BungeeCord/files/7729376/console.txt)
[config.txt](https://github.com/SpigotMC/BungeeCord/files/7729389/config.txt)
[serverproperties.txt](https://github.com/SpigotMC/BungeeCord/files/7729395/serverproperties.txt)

**Comment by Janmm14** [comment]
Please use https://spigotmc.org forums for usage help.

**Comment by mitchngwen** [comment]
Yeah! don't ask the developer for help. What are you thinking?!
