### ISSUE TITLE
Players getting kicked

### ISSUE THREAD

**Issue by Thefluffypvper1** [SpigotMC/BungeeCord#3227]
I am having an issue with bungeecord where my players are randomly getting kicked to default server (hub) and i don't know the root cores of it

**Comment by Janmm14** [comment]
https://spigotmc.org is the better place for general troubleshooting.

**Comment by xIsm4** [comment]
> I am having an issue with bungeecord where my players are randomly getting kicked to default server (hub) and i don't know the root cores of it

Well, any type of logs?

**Comment by Thefluffypvper1** [comment]
> > I am having an issue with bungeecord where my players are randomly getting kicked to default server (hub) and i don't know the root cores of it
> 
> Well, any type of logs?

There are no error logs just saids player has disconnected

**Comment by xIsm4** [comment]
> > > I am having an issue with bungeecord where my players are randomly getting kicked to default server (hub) and i don't know the root cores of it
> > 
> > 
> > Well, any type of logs?
> 
> There are no error logs just saids player has disconnected

Well that can be caused by a lot of things i could help u trougth discord: xIsm4 $avage#9127
