### ISSUE TITLE
Could not connect to the default or fallback server %reason%

### ISSUE THREAD

**Issue by Reelx69** [SpigotMC/BungeeCord#3230]
As i said in the title i cant connect to a server that hooked in Bungeecord for unknown reason!

Please i need help i tried to delete the server and remake it !
![IMG_٢٠٢١١٢٢٥_١٢٥١٠٩](https://user-images.githubusercontent.com/96651565/147383746-eb9a85bf-4a66-4e12-9b46-b6bc6c042e24.jpg)

**Comment by Janmm14** [comment]
Either invalid entry in messages.properties of bungeecord

or the server actually kicks with the reason %reason%
