### ISSUE TITLE
Having this weird issue randomly where it doesnt let me in

### ISSUE THREAD

**Issue by vishyvishal14** [SpigotMC/BungeeCord#3232]
https://paste.gg/p/anonymous/deded8d4f64d4c29847b53d3291a546a
Its same at the bungee too
this is waterfall but this happened with plain bungeecoord

**Comment by Janmm14** [comment]
well it looks like bungee wanted to disconnect you and it encountered a problem while doing so

**Comment by md-5** [comment]
It would not be 'the same' with bungee
