### ISSUE TITLE
Why not better compression algorithm?

### ISSUE THREAD

**Issue by andreasdc** [SpigotMC/BungeeCord#3236]
LZ4 or libdeflate are faster algorithms than zlib, why shouldn't they be used in BungeeCord? I think it would help a lot in performance and general speed.

**Comment by Janmm14** [comment]
@andreasdc 
First its nice that you want things to improve, but we cannot change the compr.ession algorithm, because we have to use the one what the minecraft client and server expect.

**Comment by andreasdc** [comment]
> @andreasdc First its nice that you want things to improve, but we cannot change the compression algorithm, because we have to use the one the minecraft client and server expect.

You are joking, right? Mojang will never stop shocking me haha
Is there maybe a way to bypass that? Why do they want exact algorithm?
Velocity uses libdeflate.

**Comment by Janmm14** [comment]
@andreasdc
I am sorry. I was not paying that much attention to the names you wrote in your first post.
We use Cloudflare's implementation of zlib compression currently, which is already quite optimized.

Cloudflare's mplementation was chosen because https://github.com/SpigotMC/BungeeCord/pull/3114#issuecomment-865216596 said that using libdeflate would require some code restructuring and in the end md_5 decided to use cloudflare's zlib in https://github.com/SpigotMC/BungeeCord/commit/da27924a49dad2a168eaa2cea49f1e751741d5fa

I don't think he wants to spent time on changing the zlib implementation again so soon, so feel free to create a PR.

http://www.htslib.org/benchmarks/zlib.html suggests that libdeflate is not as good as cloudflare's zlib in reducing file size during compression, so that might be another point why cloudflare's zlib was chosen.

**Comment by andreasdc** [comment]
> @andreasdc I am sorry. I was not paying that much attention to the names you wrote in your first post. We use Cloudflare's implementation of zlib compression currently, which is already quite optimized.
> 
> Cloudflare's mplementation was chosen because [#3114 (comment)](https://github.com/SpigotMC/BungeeCord/pull/3114#issuecomment-865216596) said that using libdeflate would require some code restructuring and in the end md_5 decided to use cloudflare's zlib in [da27924](https://github.com/SpigotMC/BungeeCord/commit/da27924a49dad2a168eaa2cea49f1e751741d5fa)
> 
> I don't think he wants to spent time on changing the zlib implementation again so soon, so feel free to create a PR.
> 
> http://www.htslib.org/benchmarks/zlib.html suggests that libdeflate is not as good as cloudflare's zlib in reducing file size during compression, so that might be another point why cloudflare's zlib was chosen.

So other algorithms can be used. Why not use LZ4 then?
I don't see where in that benchmark zlib is better. 

Of course it would require some work, but I think it's doable and worthy change.

**Comment by Janmm14** [comment]
@andreasdc
I am no sure about lz4. Is lz4 a zlib compression implementation?
All what I wrote about in my last post were different implementations of the zlib compression. libdeflate is also zlib compression.

It has to be zlib in the end.

**Comment by caoli5288** [comment]
> @andreasdc I am no sure about lz4. Is lz4 a zlib compression implementation? All what I wrote about in my last post were different implementations of the zlib compression. libdeflate is also zlib compression.
> 
> It has to be zlib in the end.

LZ4 is not compatible to libz so it impossible

**Comment by md-5** [comment]
> Why not use LZ4 then?

Because the Minecraft client doesn't support it....

**Comment by andreasdc** [comment]
> > Why not use LZ4 then?
> 
> Because the Minecraft client doesn't support it....

There is libdeflate then?

**Comment by xIsm4** [comment]
> > > Why not use LZ4 then?
> > 
> > 
> > Because the Minecraft client doesn't support it....
> 
> There is libdeflate then?

As they said they are using Cloudfare's zlib (Witch means that haves better performance) and recoding for so low changes it's not that smart.

**Comment by andreasdc** [comment]
> > > > Why not use LZ4 then?
> > > 
> > > 
> > > Because the Minecraft client doesn't support it....
> > 
> > 
> > There is libdeflate then?
> 
> As they said they are using Cloudfare's zlib (Witch means that haves better performance) and waste time for a very small change isn't that smart.

Yup, up to 30-40% better performance on compression.
As I see there is something like igzip (Intel(R) Intelligent Storage Acceleration Library), which has even better performance.

It should be benchmarked of course, but I need to point that you share useless opinions in many projects.

**Comment by xIsm4** [comment]
> > > > > Why not use LZ4 then?
> > > > 
> > > > 
> > > > Because the Minecraft client doesn't support it....
> > > 
> > > 
> > > There is libdeflate then?
> > 
> > 
> > As they said they are using Cloudfare's zlib (Witch means that haves better performance) and waste time for a very small change isn't that smart.
> 
> Yup, up to 30-40% better performance on compression. As I see there is something like igzip (Intel(R) Intelligent Storage Acceleration Library), which has even better performance.
> 
> It should be benchmarked of course, but I need to point that you share useless opinions in many projects.

Is not an opinion, your requests sucks (with sorry investigate first about something).
You did 3 times a bad suggestion due or doesn't work good, or just isn't a good repository for it good luck!

**Comment by andreasdc** [comment]
> > > > > > Why not use LZ4 then?
> > > > > 
> > > > > 
> > > > > Because the Minecraft client doesn't support it....
> > > > 
> > > > 
> > > > There is libdeflate then?
> > > 
> > > 
> > > As they said they are using Cloudfare's zlib (Witch means that haves better performance) and waste time for a very small change isn't that smart.
> > 
> > 
> > Yup, up to 30-40% better performance on compression. As I see there is something like igzip (Intel(R) Intelligent Storage Acceleration Library), which has even better performance.
> > It should be benchmarked of course, but I need to point that you share useless opinions in many projects.
> 
> Is not an opinion, your requests sucks (with sorry investigate first about something). You did 3 times a bad suggestion due or doesn't work good, or just isn't a good repository for it good luck!

Keep hating and doing absolutely nothing useful.

**Comment by xIsm4** [comment]
> As they said they are using Cloudfare's zlib (Witch means that haves better performance) and waste time for a very small change isn't that smart.

Im not hating, probly you are? Anyways this isn't the side for see that.
I just said the truth, investigate a bit if would work or if the repo its built for that before doing that. 
Good luck again!
