### ISSUE TITLE
ServerConnect disconnection bug

### ISSUE THREAD

**Issue by rootxls** [SpigotMC/BungeeCord#3237]
Hey,

I have a problem when sending player to another server, my code was working until now.
So I tried it with a 2nd Proxy instance, and it's working.
But, with the 1st instance, even if i remove all plugins except mine, and with the same config files for the Proxy on both instances, it doesn't work on the 1st instance, but works on the 2nd.
I already looked for older issues, I found one talking about network-compression-threshold.
So, I synchronized, 1st instance of BungeeCord & Spigot servers value, but it didn't changed anything.
I am sure that this issue isn't coming from any of my spigot plugins.

Here is the debug i made:

`
[13:44:35 INFO]: DEBUG: SERVER CONNECT EVENT (REASON: PLUGIN)
[13:44:35 INFO]: DEBUG: SERVER DISCONNECT EVENT
`

I am currently running the latest version of BungeeCord.

**Comment by Janmm14** [comment]
It would be a far better idea to report this to flamecord.
Especially mystic problems like these should never be directly sent to the main project when you are using a fork of a fork.

**Comment by rootxls** [comment]
Yes, but I tried with the original version of BungeeCord and the problem was still there so I deduced that the problem was with BungeeCord, so I opened an issue here. I will open one there as well.

**Comment by rootxls** [comment]
I will open one on FlameCord*

**Comment by Janmm14** [comment]
> Yes, but I tried with the original version of BungeeCord and the problem was still there so I deduced that the problem was with BungeeCord, so I opened an issue here. I will open one there as well.

Then you should not write that you are using FlameCord when the problem also happens with original bungeecord.

**Comment by rootxls** [comment]
That's true sorry for that mistake, but then we are back to where we started...
