### ISSUE TITLE
Could not Connect.....

### ISSUE THREAD

**Issue by Erazes** [SpigotMC/BungeeCord#3239]
I add a new sever in to the Bungeesystem. I repeated exactly what I did with the other servers. Every time I go to the newly added server this message comes up in the chat:

Could not Connect ro a Default or Fallbeck server, please try again later: io.netty.chennel.AbstractChannelAnnotatedConnectException

But there is no error in the console.

All other servers works fine. Only this one does not want to connect. it runs on 1.18.1

**Comment by MinoaBaccus** [comment]
same issue here

**Comment by md-5** [comment]
The server you have configured is not reachable by bungee
