### ISSUE TITLE
Could not connect to a default or fallback server, please try again later: io.netty.channel.AbstractChannel$AnnotatedConnectException

### ISSUE THREAD

**Issue by MinoaBaccus** [SpigotMC/BungeeCord#3242]
I'm new to BungeeCord, and I am trying to connect 2 servers together (hosted on the same Device). 

My config.yml for Bungee: https://pastebin.com/raw/f1hE7r2p

Screenshot of error: https://imgur.com/a/65mxnmB

**Comment by MinoaBaccus** [comment]
Also in the screenshot the **IP ping is TCP Shield AND NOT MY IP**

**Comment by Janmm14** [comment]
You need tcpshield plugin on bungee
