### ISSUE TITLE
Query Port RESET every restart 

### ISSUE THREAD

**Issue by SuryaRajgor** [SpigotMC/BungeeCord#3245]
hello i set query port to 25566 or any its reset to 25565 after restart and if i enable query in config its got error unable to bind its already in use (because 25565 is server port)

![image](https://user-images.githubusercontent.com/9131487/151575486-fddc848c-47a7-4353-8454-f4ab5a6540e7.png)

**Comment by Janmm14** [comment]
If it resets you failed to set it correctly in the first place.

**Comment by SuryaRajgor** [comment]
![image](https://user-images.githubusercontent.com/9131487/151614614-a540c1de-5905-467e-8693-77b67db2ddaf.png)

**Comment by SuryaRajgor** [comment]
https://imgur.com/a/PIzcWAW

**Comment by Janmm14** [comment]
Must be a problem of the panel you use to start bungeecord.

Bungeecord simply has no logic to change the defined query port.

For further help ask your hosting provider or create a thread on spigotmc.org forums.

**Comment by md-5** [comment]
Also since query is UDP it can be on the same port as the server
