### ISSUE TITLE
Unknown or incomplete command when using forged client

### ISSUE THREAD

**Issue by wtnpmt** [SpigotMC/BungeeCord#3246]
I have commit the same issue to forge (https://github.com/MinecraftForge/MinecraftForge/issues/8435)
They pined it "not us".
so im here.

**Comment by Janmm14** [comment]
Forge support of bungeecord is limited to old forge.
It is also unmaintained and might contain bugs.

**Comment by wtnpmt** [comment]
The bug happened when i use my forge installed client join vanilla server in bungeecord without any mod.i dont know why it happend. Maybe we will never join a "bungeed" server with a client installed forge.

**Comment by jmartin127** [comment]
This is broken for me as well.  Works fine with vanilla minecraft.

**Comment by Cheos137** [comment]
As mentioned by the forge team in https://github.com/MinecraftForge/MinecraftForge/issues/8438 this issue is the sole fault of bungeecord. bungeecord uses the brigardier format to send commands to the client, but uses legacy (pre-1.13) command registration and does not mark commands as executable, thus causing this issue.

**Comment by Cheos137** [comment]
With a recent version of forge implementing client-side commands, commands not marked as executable are now ignored on the client, thus said commands are no longer working.

**Comment by Janmm14** [comment]
> As mentioned by the forge team in [MinecraftForge/MinecraftForge#8438](https://github.com/MinecraftForge/MinecraftForge/issues/8438) this issue is the sole fault of bungeecord. bungeecord uses the brigardier format to send commands to the client, but uses legacy (pre-1.13) command registration and does not mark commands as executable, thus causing this issue.

It is the fault of forge, as it does not behave like vanilla clients anymore. Vanilla clients still send commands they do not find to the server afaik.

**Comment by md-5** [comment]
Brigadier was only added in 1.13 wasn't it? How can there be legacy brigadier registration? Bungee injects its own commands here: https://github.com/SpigotMC/BungeeCord/blob/9c95d4ba43ba84d10e8bb7d7c92d7e6c5f161ed2/proxy/src/main/java/net/md_5/bungee/connection/DownstreamBridge.java#L657

Are you experiencing this issue with commands provided by bungee (eg /bungee).
