### ISSUE TITLE
Message editing

### ISSUE THREAD

**Issue by paj1s** [SpigotMC/BungeeCord#3248]
Will it ever be possible to edit bungeecord messages as well as modules messages? I know bungeecord messages can be modified in the jar folder but the cmd_server has some messages i want to modify too.

**Comment by md-5** [comment]
You don't need to edit the jar, you can just copy the messages file to your proxy directory.
All the cmd_server messages are in there too.

**Comment by paj1s** [comment]
I have a message saying "Your connection to server: <server> was interrupted" where i can find this message?

**Comment by md-5** [comment]
BungeeCord does not have such a message

**Comment by paj1s** [comment]
It must be the cmd_server, i have removed every plugin which could cause this message but this thing will always redownload itself, it says, Your connection to <survival (my server)> was interrupted. You have been connected to: lobby i just want to edit this and there is no possible way there's something else causing this message.

**Comment by Janmm14** [comment]
No. The default bungeecord messages do not contain "interrupted".
Maybe you are looking for the message `server_went_down`?

**Comment by paj1s** [comment]
i don't know, this message appears when player tries to connect to a server which is not turned on or tries to connect to a server where he is not whitelisted. But there really isn't anything else what can be causing this message.

**Comment by Janmm14** [comment]
`fallback_lobby` or `connect_kick` maybe?

**Comment by paj1s** [comment]
I have edited all messages in bungeecord.jar that's why i thought this message is from cmd_server, i have searched on the internet and few other people had the same "problem" also blaming it on the cmd_server. Idk where else this message could come from.

**Comment by Janmm14** [comment]
> I have edited all messages in bungeecord.jar that's why i thought this message is from cmd_server, i have searched on the internet and few other people had the same "problem" also blaming it on the cmd_server. Idk where else this message could come from.

That just means that there are more people not understanding that you have to remove the corresponding line from modules.yml to not redownload the module.

**Comment by paj1s** [comment]
Ikr i even, removed the entire yml file, still the module was redownloaded, but i do want the module i just want to be able to modify the message.

**Comment by Janmm14** [comment]
The module does not contain any hardcoded message.
Removing modules.yml should just regenerate the file.

**Comment by paj1s** [comment]
ok, just please can you tell me where this message could come from?

**Comment by Janmm14** [comment]
Can you show (a screenshot of) the complete message please?

**Comment by paj1s** [comment]
![2022-02-06_17 29 30](https://user-images.githubusercontent.com/77814199/152690990-67ceb8a0-a96a-4362-a5ec-c31f7ecd573a.png)
It show this message and right after it the message "You are already on this server" which i managed to modify.

**Comment by Janmm14** [comment]
> ![2022-02-06_17 29 30](https://user-images.githubusercontent.com/77814199/152690990-67ceb8a0-a96a-4362-a5ec-c31f7ecd573a.png) It show this message and right after it the message "You are already on this server" which i managed to modify.

That looks like you already modified that message with "interrupted". The message key for that is `server_went_down`.
But the default message does not contain "interrupted".

See here (line 20) what the original message is: https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/resources/messages.properties#L20

**Comment by paj1s** [comment]
It couldn't be server_went_down i already edited all messages in messages.properties, i would know if i wrote this.
