### ISSUE TITLE
Teams not deleted on server switch

### ISSUE THREAD

**Issue by Raraph84** [SpigotMC/BungeeCord#3249]
Hi !
I have a simple question :
Why doesn't bungeecord delete teams on players when they switch servers?
It's a bug or is it done like that ?
Have a good day

**Comment by md-5** [comment]
It does: https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L273

What issue exactly are you having?
