### ISSUE TITLE
TabCompleteEvent not being called when using on '/'

### ISSUE THREAD

**Issue by Szczurowsky** [SpigotMC/BungeeCord#3251]
Code to reproduce:

**Listener:**
```java
@EventHandler(priority= EventPriority.LOWEST)
    public void onTab(TabCompleteEvent event) {
        System.out.println("called");
        event.setCancelled(true);
    }
```

When trying to complete '/' event is not being called. When completing bungee command argument event is called.

**Comment by Szczurowsky** [comment]
I forgot to mention that I use latest bungee and spigot.

**Comment by md-5** [comment]
This is impossible since 1.13 (brigadier).
The tab completion of the initial command (not arguments) is client side
