### ISSUE TITLE
Cant join my server even do i set ip forward to true in the bungeecord config.

### ISSUE THREAD

**Issue by TechnoKraken** [SpigotMC/BungeeCord#3254]
i cant join my servers any help is appreciated

![Minecraft Screenshot 2022 02 16 - 20 30 54 44](https://user-images.githubusercontent.com/95041888/154342580-f69d7570-c9ba-4c00-b706-a174e20d0589.png)

**Comment by Janmm14** [comment]
Please use spigotmc.org forums for help and make sure you connect with bungee's ip and port.

**Comment by TechnoKraken** [comment]
okay

**Comment by TechnoKraken** [comment]
but where do i ask them for help cant find a support page

**Comment by TechnoKraken** [comment]
i think i found the error
