### ISSUE TITLE
Bungeecord shows to everyone ip behind backend servers if there aren't online

### ISSUE THREAD

**Issue by BeastPsycho** [SpigotMC/BungeeCord#3258]
since you added more information to connection issue messages, i guess this is a probably security leak if there is not a option to set custom message to server admin for bungee
![Captura de pantalla (40)](https://user-images.githubusercontent.com/8921248/156342000-4d380ce6-1638-486b-a62b-809e9bfb555b.png)

**Comment by md-5** [comment]
You can configure it: https://github.com/SpigotMC/BungeeCord/blob/7e47490e7053d110a33a3c86b025af91bd803388/proxy/src/main/resources/messages.properties#L8

What's the security issue more specifically? Such addresses should be internal / firewalls?

**Comment by Janmm14** [comment]
Maybe some servers only host bungee on a ddos-secure machine or use for example tcpshield. Getting to know backend IPs - even if properly firewalled - might be enough to launch a ddos.

**Comment by BeastPsycho** [comment]
i see it before comment thanks, well. not everybody can setup a firewall properly, i think backend servers ip local or not must be secret as ever has been

**Comment by Janmm14** [comment]
> i see it before comment thanks, well. not everybody can setup a firewall properly, i think backend servers ip local or not must be secret as ever has been

Hiding IP because of unfirewalled backend servers is not the right reason. You promote security by obscurity here while better solutions existfor this problem.

When ports are firewalled, scanning does not help you to find out backend IPs. And you cannot randomly ddos different IPs to find out the backend server IP.

**Comment by Janmm14** [comment]
> The fact that measures can only be taken in the source code is undesirable. If possible, we would like to have a separate file that can be changed. This problem is not a firewall issue, but is placed when the server is dropped as well, and causes major problems when BungeeCord is used as a reverse proxy. ![image](https://user-images.githubusercontent.com/54328546/156615412-3da993fb-ee76-4fc2-b5f3-6183b6369902.png)

Wrong. Measures can be taken in messages.properties file. Extract it from the jar and place it in the same folder as the jar, then edit the message.

Also bungeecord is always used as a reverse proxy. It IS a reverse proxy.
And about what problems are legitimate reasons to hide IP addresses was already spoken above.

**Comment by yululiYT** [comment]
> Wrong. Measures can be taken in messages.properties file. Extract it from the jar and place it in the same folder as the jar, then edit the message.
> 
> Also bungeecord is always used as a reverse proxy. It IS a reverse proxy. And about what problems are legitimate reasons to hide IP addresses was already spoken above.

The problem is that IPs are visible by default.
The default setting should be off to change the configuration.

**Comment by yululiYT** [comment]
And conversely, is it necessary to display the IP throughout? If you do, you can only do this for users configured in the PERMISSION.

**Comment by Hiyuuu** [comment]
I consider this problem to be very serious too. To hide IP address then, It need to reconfigure the server software after every update. 

As an alternative, It can display the server name instead of display the IP address of the server that cannot be connected

**Comment by Janmm14** [comment]
> I consider this problem to be very serious too. To hide IP address then, It need to reconfigure the server software after every update.
> 
> As an alternative, It can display the server name instead of display the IP address of the server that cannot be connected

No, you do not have to reconfigure every update. As I said, you can put the message.properties file just in the same folder as the bungee jar and bungee will use that instead of the default one in the jar.

**Comment by md-5** [comment]
At the very least we then need a different message for the console. More information was required in the message because of users blaming config issues on bungeecord and bungee not giving them enough information to effectively solve it.

**Comment by itsfergydanny** [comment]
Just ran into this today and I have to agree with others. This should definitely be in the console and not in-game, not a lot of people are behind VLANs or in situations where all the backend ips are as secure as the proxy itself.

**Comment by Toshimichi0915** [comment]
In my opinion we can add ProxiedPlayer#connect(ServerInfo, Callback&lt;ConnectResult&gt; callback) to make plugins handle the situation and send messages to the player depending on the result.

```java
@RequiredArgsConstructor
@Getter
public class ConnectResult {
  private final Exception exception;
  private final ConnectResultType type;
}
```

```java
public enum ConnectResultType {
  SUCCESSFUL, ERROR, KICKED
}
```

**Comment by Ryzanite** [comment]
> Just ran into this today and I have to agree with others. This should definitely be in the console and not in-game, not a lot of people are behind VLANs or in situations where all the backend ips are as secure as the proxy itself.

Yep agreed, honestly I don't know why it exposes your backend server IPs.

I'm home-hosting some servers and I'm using an external host as a Proxy with DDoS protection. I noticed this issue when I tried connected to the proxy and my hub was down. I was a bit concerned when I saw my IP.

FYI: I know what I'm doing; I have a dedicated server at home.

**Comment by Janmm14** [comment]
> > Just ran into this today and I have to agree with others. This should definitely be in the console and not in-game, not a lot of people are behind VLANs or in situations where all the backend ips are as secure as the proxy itself.
> 
> Yep agreed, honestly I don't know why it exposes your backend server IPs.
> 
> I'm home-hosting some servers and I'm using an external host as a Proxy with DDoS protection. I noticed this issue when I tried connected to the proxy and my hub was down. I was a bit concerned when I saw my IP.
> 
> FYI: I know what I'm doing; I have a dedicated server at home.

Currently it only shows the ip to people in the "admin" group of your bungee.

**Comment by Toshimichi0915** [comment]
To be honest, it's better to let plugins decide how errors should be handled, instead of sending messages to admin players.

**Comment by md-5** [comment]
Bungee needs to operate usefully without plugins. It can't rely on plugins to send error messages.

**Comment by Toshimichi0915** [comment]
for built-in commands like /server it's totally fine to send error message to everyone or admins only because we can just disable the command easily.

However, if a player is transferred to another server by a Bungeecord plugin, it's really nice to let plugins deal with an error themselves

**Comment by Toshimichi0915** [comment]
Well if this solution is better than the current solution, I might send a PR to implement this feature.

Can I hear thoughts of this feature?

**Comment by Janmm14** [comment]
You could add a boolean option to ServerConnectRequest which will prevent bungee from sending messages to the player directly.
