### ISSUE TITLE
Player disconnects with no error when sending scoreboard objective packet

### ISSUE THREAD

**Issue by OminousOne** [SpigotMC/BungeeCord#3260]
I have no idea what is going on. When I send the player the ScoreboardObjective packet they just disconnect without any error or anything. The only thing the console shows is player disconnected no other information is given.

Here is the function to create the scoreboard and send the packet. This is called by a command. (Kotlin)
```kotlin
fun createScoreboard(player: ProxiedPlayer) {
    val objective = ScoreboardObjective("test", "Test", ScoreboardObjective.HealthDisplay.INTEGER, 0)
    player.unsafe().sendPacket(objective)
}

**Comment by Janmm14** [comment]
ScoreboardObject packet is correctly implemented in bungeecord.

Please use https://www.spigotmc.org forums for further help. When you post on spigotmc.org forums, you should include client logs, client version, server version and at which point you call this function (which event).
You might also want to consider leaving all the scoreboard stuff to the spigot servers like many other servers do.

**Comment by OminousOne** [comment]
Ok, thanks for the help!
