### ISSUE TITLE
InitialHandler Packet Overflow

### ISSUE THREAD

**Issue by OFlexan** [SpigotMC/BungeeCord#3275]
When I start BungeeCord everything works fine, but when I login it rejects me and in the logs it says:
`HH:MM:SS [WARNING] [/IP:PORT] <-> InitialHandler - overflow in packet detected! Cannot receive string longer than 1020 (got 1406 bytes)`
Latest BungeeCord and server version

**Comment by Janmm14** [comment]
Could it be that your server address is very, very long?

**Comment by OFlexan** [comment]
> Could it be that your server address is very, very long?

Well the address is about 20 characters long. Why would that have impact exactly?

**Comment by Janmm14** [comment]
No 20 chars is normal, we speak about more than 255 chars somewhere

**Comment by OFlexan** [comment]
> No 20 chars is normal, we speak about more than 255 chars somewhere

No idea where that could be. Is there like any Java option I can use to debug it?

**Comment by Janmm14** [comment]
any plugins? client mod?

**Comment by OFlexan** [comment]
> any plugins? client mod?

ViaVersion as plugin, vanilla 1.18.2 MC client

**Comment by Janmm14** [comment]
Could it be that the target server of your bungee is your bungee itself?

**Comment by OFlexan** [comment]
A long time later, but I found out what the server address field in the handshake packet actually looks like. It includes the actual server ip, the client ip and skin data. Is there a way for bungeecord to ignore the other things after the space?

**Comment by OFlexan** [comment]
> Could it be that the target server of your bungee is your bungee itself or another bungee?

No, the target server is a 1.17 server.

**Comment by Janmm14** [comment]
> @OFlexan 
> A long time later, but I found out what the server address field in the handshake packet actually looks like. It includes the actual server ip, the client ip and skin data. Is there a way for bungeecord to ignore the other things after the space?

The handshake packet from the connecting client does NOT contain client ip or skin data. It only contains client ip and skin data if it originates from a(nother) bungeecord with enabled ip-forwarding.

You may not set a bungee as target of another bungee. If it would not cause a packet overflow, bungee has a dedicated check to prevent that from happening.

**Comment by OFlexan** [comment]
Ohh I see what you mean now. Thanks for your help.
