### ISSUE TITLE
(SOLVED) ReadTimeoutException : null ERROR 

### ISSUE THREAD

**Issue by sussybukaa** [SpigotMC/BungeeCord#3278]
14:34:27 [WARNING] [2B_nxy] -> UpstreamBridge - read timed out
14:34:27 [INFO] [2B_nxy] disconnected with: ReadTimeoutException : null
14:34:27 [INFO] [2B_nxy] -> UpstreamBridge has disconnected

letme give you a brief
so... i own a cracked network
and me and other pple who own minecraft accounts are able to join with no issue
but when cracked users try to join
they get this error

my bungeeconfigs-
https://pastebin.com/3qjv1PfR

please feel free to give your suggestions here

**Comment by sussybukaa** [comment]
Any help would be appreciated..

**Comment by xIsm4** [comment]
> 14:34:27 [WARNING] [2B_nxy] -> UpstreamBridge - read timed out 14:34:27 [INFO] [2B_nxy] disconnected with: ReadTimeoutException : null 14:34:27 [INFO] [2B_nxy] -> UpstreamBridge has disconnected
> 
> letme give you a brief so... i own a cracked network and me and other pple who own minecraft accounts are able to join with no issue but when cracked users try to join they get this error
> 
> my bungeeconfigs- https://pastebin.com/3qjv1PfR
> 
> please feel free to give your suggestions here

That's not a BungeeCord issue, obvuisly is some plugin of your backend giving that issue of readTimeOut.

**Comment by sussybukaa** [comment]
> > 14:34:27 [WARNING] [2B_nxy] -> UpstreamBridge - read timed out 14:34:27 [INFO] [2B_nxy] disconnected with: ReadTimeoutException : null 14:34:27 [INFO] [2B_nxy] -> UpstreamBridge has disconnected
> > letme give you a brief so... i own a cracked network and me and other pple who own minecraft accounts are able to join with no issue but when cracked users try to join they get this error
> > my bungeeconfigs- https://pastebin.com/3qjv1PfR
> > please feel free to give your suggestions here
> 
> That's not a BungeeCord issue, obvuisly is some plugin of your backend giving that issue of readTimeOut.

so... is it a plugin in the spigot servers or in bungeecord btw?

**Comment by xIsm4** [comment]
> > > 14:34:27 [WARNING] [2B_nxy] -> UpstreamBridge - read timed out 14:34:27 [INFO] [2B_nxy] disconnected with: ReadTimeoutException : null 14:34:27 [INFO] [2B_nxy] -> UpstreamBridge has disconnected
> > > letme give you a brief so... i own a cracked network and me and other pple who own minecraft accounts are able to join with no issue but when cracked users try to join they get this error
> > > my bungeeconfigs- https://pastebin.com/3qjv1PfR
> > > please feel free to give your suggestions here
> > 
> > 
> > That's not a BungeeCord issue, obvuisly is some plugin of your backend giving that issue of readTimeOut.
> 
> so... is it a plugin in the spigot servers or in bungeecord btw?

Yep

**Comment by sussybukaa** [comment]
> > > > 14:34:27 [WARNING] [2B_nxy] -> UpstreamBridge - read timed out 14:34:27 [INFO] [2B_nxy] disconnected with: ReadTimeoutException : null 14:34:27 [INFO] [2B_nxy] -> UpstreamBridge has disconnected
> > > > letme give you a brief so... i own a cracked network and me and other pple who own minecraft accounts are able to join with no issue but when cracked users try to join they get this error
> > > > my bungeeconfigs- https://pastebin.com/3qjv1PfR
> > > > please feel free to give your suggestions here
> > > 
> > > 
> > > That's not a BungeeCord issue, obvuisly is some plugin of your backend giving that issue of readTimeOut.
> > 
> > 
> > so... is it a plugin in the spigot servers or in bungeecord btw?
> 
> Yep

Okay it worked.....the solution was just to delete all plugins (not plugin files) then add each plugin one-by-one  to check which plugin was causing that error....trust me it works

**Comment by xIsm4** [comment]
> > > > > 14:34:27 [WARNING] [2B_nxy] -> UpstreamBridge - read timed out 14:34:27 [INFO] [2B_nxy] disconnected with: ReadTimeoutException : null 14:34:27 [INFO] [2B_nxy] -> UpstreamBridge has disconnected
> > > > > letme give you a brief so... i own a cracked network and me and other pple who own minecraft accounts are able to join with no issue but when cracked users try to join they get this error
> > > > > my bungeeconfigs- https://pastebin.com/3qjv1PfR
> > > > > please feel free to give your suggestions here
> > > > 
> > > > 
> > > > That's not a BungeeCord issue, obvuisly is some plugin of your backend giving that issue of readTimeOut.
> > > 
> > > 
> > > so... is it a plugin in the spigot servers or in bungeecord btw?
> > 
> > 
> > Yep
> 
> Okay it worked.....the solution was just to delete all plugins (not plugin files) then add each plugin one-by-one to check which plugin was causing that error....trust me it works

Cool, you should close btw this.
