### ISSUE TITLE
[Security] Remote hosts IP leaking.

### ISSUE THREAD

**Issue by Leymooo** [SpigotMC/BungeeCord#3285]
This change https://github.com/SpigotMC/BungeeCord/commit/eae9d45c8a4142541dfda7f6322784d148d4b027#diff-d1f4e21d9feddd3e2db9439700861e3d969f1557d308e4228a559f99e2d6414aR375 causes ip leaking. 

![image](https://user-images.githubusercontent.com/8667294/162498062-bdb1d1dc-8516-4964-b114-63908a7c77c9.png)
(russian translate of this message https://github.com/SpigotMC/BungeeCord/commit/eae9d45c8a4142541dfda7f6322784d148d4b027#diff-e3c459195e522edc2472a358e173e1857d8c11ea08e67a64f1e6d21967e80583R8)

**Comment by Janmm14** [comment]
Duplicate of #3258
