### ISSUE TITLE
Bungeecord on linux aarch64: UpstreamBridge unable to receive TCP FIN on MinecraftClient disconnect

### ISSUE THREAD

**Issue by isjerryxiao** [SpigotMC/BungeeCord#3286]
## Problem
I'm running a bungeecord instance on linux aarch64 (nixos unstable). The proxy works except there is one problem: clients connect to the proxy won't be able to disconnect normally. The UpstreamBridge continues to run after client disconnected until the TCP connection times out. Upon further investigation it seems that this code is never called on client disconnection, while it should have been. https://github.com/SpigotMC/BungeeCord/blob/978e68fc74f6cc257348d6984c53099c1841d46c/proxy/src/main/java/net/md_5/bungee/netty/HandlerBoss.java#L55  
Strangely I ran the "echo" example of netty on the same aarch64 machine and channelInactive works flawlessly. Also InitialHandler is able to disconnect cleanly. At this point I'm not quite sure if it's a netty problem or a bungeecord problem.

## Notes
This problem seems to be only reproducible on aarch64 machines. Copy the same folder to a x86_64 machine and Bungeecord runs without problems. I tried qemu-user-aarch64 as well and it also disconnects properly without timing out. However on my aarch64 server I tried several different kernels (and different userspaces, like archlinuxarm), all of which are still broken.

**Comment by md-5** [comment]
Disable epoll / native transport

**Comment by isjerryxiao** [comment]
Epoll on aarch64 is already broken. https://github.com/SpigotMC/BungeeCord/blob/862bb2ac72fbabafb40935f9b7eb44a6faea061a/proxy/pom.xml#L49)

**Comment by isjerryxiao** [comment]
```
11:44:06 [INFO] Using standard Java JCE cipher.
11:44:06 [INFO] Using standard Java compressor.
11:44:06 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:862bb2a:1636
11:44:06 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
11:44:06 [WARNING] Epoll is not working, falling back to NIO: UnsatisfiedLinkError : could not load a native library: netty_transport_native_epoll_aarch_64 @ 
io.netty.util.internal.NativeLibraryLoader:217
```

**Comment by isjerryxiao** [comment]
I did get epoll to work but that doesn't seem to affect the problem in any ways.

**Comment by isjerryxiao** [comment]
Also I did stumble upon https://github.com/SpigotMC/BungeeCord/issues/1717, tried `-Dnet.md_5.bungee.native.disable=true`, also tried reverting that fix, didn't work either.

**Comment by md-5** [comment]
Well this is gonna be a Netty/java bug, bungee is not architecture dependant in this way

**Comment by Janmm14** [comment]
@isjerryxiao maybe try different jvm / java version

**Comment by isjerryxiao** [comment]
I did try openjdk17 and openjdk11, same behavior. The problem is, on aarch64 you don't have much jvm to choose from.

**Comment by isjerryxiao** [comment]
I did some pcap, it seems that sometimes the fin is completely missing. I guess there's something like a broken firewall somewhere in the network (x86_64 tests are done with loopback addresses so they are not affected). Sorry for the bug report and thank you all for your time.
