### ISSUE TITLE
Can't Able to join 

### ISSUE THREAD

**Issue by SujalBro** [SpigotMC/BungeeCord#3291]
Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?

**Comment by xIsm4** [comment]
> Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?

Read the error (You did not configure rigthly your address/port or firewall)

**Comment by SujalBro** [comment]
> > Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?
> 
> Read the error (You did not configure rigthly your address/port or firewall)

All Configuration Is Perfect

**Comment by xIsm4** [comment]
> > > Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?
> > 
> > 
> > Read the error (You did not configure rigthly your address/port or firewall)
> 
> All Configuration Is Perfect

No is not, or would not trow that error.

**Comment by SujalBro** [comment]
> > > > Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?
> > > 
> > > 
> > > Read the error (You did not configure rigthly your address/port or firewall)
> > 
> > 
> > All Configuration Is Perfect
> 
> No is not, or would not trow that error.

All is perfect I think I'm using wrong IP address

**Comment by xIsm4** [comment]
> > > > > Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?
> > > > 
> > > > 
> > > > Read the error (You did not configure rigthly your address/port or firewall)
> > > 
> > > 
> > > All Configuration Is Perfect
> > 
> > 
> > No is not, or would not trow that error.
> 
> All is perfect I think I'm using wrong IP address

Then, is an config mistake just fix it.

**Comment by SujalBro** [comment]
> > > > > > Could Not Connect To Default Or Fallback Server Incorrectly Configured address/port/firewall?
> > > > > 
> > > > > 
> > > > > Read the error (You did not configure rigthly your address/port or firewall)
> > > > 
> > > > 
> > > > All Configuration Is Perfect
> > > 
> > > 
> > > No is not, or would not trow that error.
> > 
> > 
> > All is perfect I think I'm using wrong IP address
> 
> Then, is an config mistake just fix it.

Sorry He Is Not Replying My Message I think he is busy when he will give me config.yml I will give u

**Comment by NoJokeFNA** [comment]
This is not really a discussion place for simple misconfiguration. Please visit the spigot Mc website for that kind of stuff.

**Comment by md-5** [comment]
This is why the error message should show the IP >.>
