### ISSUE TITLE
Setting up config on spigot server?? Help??

### ISSUE THREAD

**Issue by MuddyMue** [SpigotMC/BungeeCord#3292]
Hi, I'm still very new to coding and am helping a friend run their minecraft server. We're trying to make a new server (for an origins plugin), but I can't seem to get the config set up right? Whenever I change anything, it'll cycle through 'you're already connected to this proxy', 'firewall not set up properly', or the server just won't load at all.

Here's the code that we have for it so far. The only thing I've changed is the online mode to false. I should also note that I haven't installed any plugins yet. Everything is still brand new with this server.

server_connect_timeout: 5000
listeners:
- bind_local_address: true
  force_default_server: false
  forced_hosts:
    pvp.md-5.net: pvp
  host: 0.0.0.0:25565
  max_players: 1
  motd: '&1Another Bungee server'
  ping_passthrough: false
  priorities:
  - lobby
  proxy_protocol: false
  query_enabled: false
  query_port: 25565
  tab_list: GLOBAL_PING
  tab_size: 60
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  default:
  - bungeecord.command.server
  - bungeecord.command.list
log_pings: true
connection_throttle_limit: 3
prevent_proxy_connections: false
timeout: 30000
player_limit: -1
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 41b26b3e-06b6-4768-8ed1-32703b3759c5
online_mode: false
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    address: localhost:25565
    motd: '&1Just another BungeeCord - Forced Host'
    restricted: false

Any help would be greatly appreciated! Even if its a noob mistake I've made

**Comment by Janmm14** [comment]
Please use https://www.spigotmc.org forums for help. This is a bug tracker.
