### ISSUE TITLE
Nullability annotations for config

### ISSUE THREAD

**Issue by Derkades** [SpigotMC/BungeeCord#3293]
Would you accept a PR for the bungeecord configuration library to add nullability annotations? It would help resolve warnings when using it in projects with a system like checker framework in place.

**Comment by xIsm4** [comment]
> Would you accept a PR for the bungeecord configuration library to add nullability annotations? It would help resolve warnings when using it in projects with a system like checker framework in place.

Cool idea, but i think that you should just pr and ask there.

**Comment by md-5** [comment]
https://github.com/SpigotMC/BungeeCord/pull/2914

Sure, but it needs to be complete and tested like in Spigot.
