### ISSUE TITLE
Method became inaccessible when trying to use inner class as a listener

### ISSUE THREAD

**Issue by MrIvanPlays** [SpigotMC/BungeeCord#3294]
```java
    this.getProxy()
        .getPluginManager()
        .registerListener(
            this,
            new Listener() {

              @EventHandler(priority = EventPriority.LOWEST)
              public void onDisconnect(PlayerDisconnectEvent event) {
                // ...
              }

              @EventHandler
              public void onChat(ChatEvent event) {
                // ...
              }
            });
```
this results in a "method became inaccessible" exception thrown in the console.
BungeeCord version: git:BungeeCord-Bootstrap:1.18-R0.1-SNAPSHOT:862bb2a:1636

I consider that as a bug since doing this in spigot doesn't result in a exception (atleast for me)

**Comment by Janmm14** [comment]
Afaik inner classes have private class access. bungee-event does not call setAccessible(true), so it fails.

Move to named, public (static) inner classes if you don't want to have the listener in a new file.

**Comment by MrIvanPlays** [comment]
i know it is much simpler but why doesn't bungee call setAccessible??

**Comment by Janmm14** [comment]
Because it wants the methods to be public.

Also IvanCord would be unable to call the method as it has no way of calling non-public methods (or methods in non-public classes).
