### ISSUE TITLE
Who to block /server

### ISSUE THREAD

**Issue by Pachecon22** [SpigotMC/BungeeCord#3300]
How can I block that when someone joins with my nick and puts /server and thus the auth is skipped, how do I do it

**Comment by Janmm14** [comment]
Use auth plugin which supports bungeecord via an additional plugin on bungeecord.

**Comment by wolfdev1** [comment]
This is not the right place, ask those kinds of questions in the Spigot forum, but this is solved with a permission manager like LuckPerms :D

**Comment by andriycraft** [comment]
> How can I block that when someone joins with my nick and puts /server and thus the auth is skipped, how do I do it

```
disabled_commands:
- server
```
Put this in your config.yml

**Comment by Janmm14** [comment]
> > How can I block that when someone joins with my nick and puts /server and thus the auth is skipped, how do I do it
> 
> ```
> disabled_commands:
> - server
> ```
> 
> Put this in your config.yml

Look at the date and hte previous answers. You are encouraging bad behaviour.
