### ISSUE TITLE
Bungeecord kicks users if this error happens

### ISSUE THREAD

**Issue by darkwolfie37** [SpigotMC/BungeeCord#3311]
![image](https://user-images.githubusercontent.com/79094301/172451206-2e460338-cdec-480a-918e-ba851b95e252.png)

**Comment by darkwolfie37** [comment]
Is this caused by StaffPlusPlus?

**Comment by ScriptJunkieDev** [comment]
remove it and see if the error still happens?

**Comment by McPlayHD** [comment]
> @md-5 what is considered a direct message? My plugin uses ProxiedPlayer sendMessage during join and is causing this error.

I can confirm.
Trying to do the following will result in players getting disconnected when joining with 1.18.2.
```java
TextComponent text = new TextComponent("abc");
player.sendMessage(text);
```
It will not result in a disconnect when using version 1.8.x though.

**Comment by darkwolfie37** [comment]
> > @md-5 what is considered a direct message? My plugin uses ProxiedPlayer sendMessage during join and is causing this error.
> 
> I can confirm. Trying to do the following will result in players getting disconnected when joining with 1.18.2.
> 
> ```java
> TextComponent text = new TextComponent("abc");
> player.sendMessage(text);
> ```
> 
> _(I have [ViaVersion](https://github.com/ViaVersion/ViaVersion) installed and I can join the server but as soon as I send the message I get disconnected)_ It will not result in a disconnect when using version 1.8.x though.

IS this a bungeecord issue or not @md-5

**Comment by ScriptJunkieDev** [comment]
We did that already bud. Thanks for the input though.

**Comment by md-5** [comment]
>I can confirm. Trying to do the following will result in players getting disconnected when joining with 1.18.2.

The following where?
