### ISSUE TITLE
Cannot connect with 1.19 clients

### ISSUE THREAD

**Issue by ducitymp** [SpigotMC/BungeeCord#3312]
When trying to connect with a 1.19 client, we get kicked again. See screenshot below.
![Schermafbeelding 2022-06-07 om 13 22 53](https://user-images.githubusercontent.com/17803190/172455233-63957086-baa4-4e25-91ea-41d3ae76bd7b.png)

**Comment by l3nnartt** [comment]
Check https://github.com/ViaVersion/ViaVersion/issues/2918
