### ISSUE TITLE
Unexpected packet/connection issues.

### ISSUE THREAD

**Issue by elkoyofficial** [SpigotMC/BungeeCord#3314]
Players are struggling to connect on the latest version of bungeecord;

encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during server login process!

and

![image](https://user-images.githubusercontent.com/63325580/172485261-f08a3cab-44c8-4659-b580-928088f74ee6.png)

**Comment by md-5** [comment]
Duplicate #3312 #3313
