### ISSUE TITLE
System Messages shown in action bar

### ISSUE THREAD

**Issue by PancakeCatsss** [SpigotMC/BungeeCord#3321]
Using the latest Bungeecord system messages are shown in the action bar on 1.19 clients

Bungeecord build #1644

**Comment by Janmm14** [comment]
In #3318 md-5 said that he did check this very system working without problem.

**Comment by md-5** [comment]
No they aren't.
![2022-06-08_22 44 58](https://user-images.githubusercontent.com/1007849/172619528-f079e8bf-f3b1-4116-84e8-73fae3cca6f2.png)

**Comment by Packsolite** [comment]
This is NOT fixed, even in latest commit ff5727c5ef9c0b56ad35f9816ae6bd660b622cf0

**Comment by Janmm14** [comment]
> This is NOT fixed, even in latest commit [ff5727c](https://github.com/SpigotMC/BungeeCord/commit/ff5727c5ef9c0b56ad35f9816ae6bd660b622cf0)

Did you check without bungeecord? Maybe the problem is because you did not bother updating your spigot 1.19 server?

**Comment by Packsolite** [comment]
> Did you check without bungeecord? Maybe the problem is because you did not bother updating your spigot 1.19 server?

This can't be a spigot issue, it's affecting messages sent by the proxy to the player. Just execute `/glist` with an 1.19 client.

**Comment by md-5** [comment]
Then explain my screenshot showing it working fine

**Comment by Packsolite** [comment]
> Then explain my screenshot showing it working fine

Either our communication messed up and this is misunderstood or there is some serious witchcraft going on.
Can you please verify again, that you are running on the latest commit and executing a command (like `/glist`)?

I really don't know what i am doing wrong here else...

![image](https://user-images.githubusercontent.com/102829507/172733818-66c3ddfe-d442-4f97-bed7-2db1417e99b3.png)

**Comment by PancakeCatsss** [comment]
> > Then explain my screenshot showing it working fine
> 
> Either our communication messed up and this is misunderstood or there is some serious witchcraft going on. Can you please verify again, that you are running on the latest commit and executing a command (like `/glist`)?
> 
> I really don't know what i am doing wrong here else...
> 
> ![image](https://user-images.githubusercontent.com/102829507/172733818-66c3ddfe-d442-4f97-bed7-2db1417e99b3.png)

If you're using ViaVersion install it on the proxy side instead of each server, that fixed the issue for me.

**Comment by Gerrygames** [comment]
The current code only works for the vanilla chat type registry. ViaVersion uses a minimal chat type registry (only containing system and game_info). The proper fix for this issue is to get the chat type id from the registry sent in the join game packet instead of using hardcoded ids.

**Comment by md-5** [comment]
Otoh there's no way that I'm aware of to remove the defaults, even with a datapack and so viaversion is wrong. There's then also the further issue of mixing vanilla servers with viaversion servers, which viaversion would then break since the registry is sent in the join game

**Comment by Gerrygames** [comment]
Haven't checked it, but I think for >=1.16 the join game packet is sent for every server switch instead of the respawn packet. Dimensions, biomes and chat types can change between servers. So all registries have to be updated for the client via a join game packet.
