### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by Matias126400** [SpigotMC/BungeeCord#3322]
Could not connect to a default or fallback server.

**Comment by Matias126400** [comment]
How i fix it?

**Comment by Janmm14** [comment]
Make sure the targrt server is online. For general usage help, please use **https://www.spigotmc.org forums**.

Additionally we do not like to poke around for every bit of extra information, so when you post about this problem **_in said forum_**, provide details like log excerpt, bungee config, bungee version, client version, server version and what else might be special.

**Comment by Matias126400** [comment]
The servers are on and the error appears

**Comment by Janmm14** [comment]
**_Please use https://www.spigotmc.org/ forums!_**
Because there is no such problem inside BungeeCord itself and this is a BungeeCord issue tracker and no User Help Forum.
