### ISSUE TITLE
1.19 Crashes opening a certain viliagar menu. 

### ISSUE THREAD

**Issue by darkwolfie37** [SpigotMC/BungeeCord#3325]
![image](https://user-images.githubusercontent.com/79094301/172840801-de169c88-02bc-4183-90b0-56ed9c0410f6.png)

**Comment by darkwolfie37** [comment]
1.19 only

**Comment by l3nnartt** [comment]
Do you use Viaversion?
If yes, check https://github.com/ViaVersion/ViaVersion/commit/7ab0c41be6fcf0c3cea0231a20a46973975bedf8

**Comment by darkwolfie37** [comment]
Thanks!
