### ISSUE TITLE
1.19 Actionbar instead of normal message

### ISSUE THREAD

**Issue by neziw** [SpigotMC/BungeeCord#3333]
Each message sent by the bungeecord module or bungeecord plugin is displayed as an actionbar instead of the normal message. This applies to the latest version of BungeeCord and only the 1.19 client. This problem does not occur on lower versions.

**Comment by Creper132** [comment]
i have this same issue

**Comment by bob7l** [comment]
Update Spigot/ViaVersion

**Comment by neziw** [comment]
I have 1.18.2 server and one on 1.8 so I can't update they to 1.19 due to some reasons. I have latest ViaVersion

**Comment by Janmm14** [comment]
@neziw You need at least ViaVerison dev build #614 https://ci.viaversion.com/job/ViaVersion/

**Comment by neziw** [comment]
Thx
