### ISSUE TITLE
Bungeecord With Mohist

### ISSUE THREAD

**Issue by Smurfboi007** [SpigotMC/BungeeCord#3335]
This is the error that shows up when trying to connect to the Mohist server from another server from the Bungeecord network: 
"**The server you were previously on went down, you have been connected to a fallback server**"

(When I connect I use the right mod packs and version of forge)

My main servers are running 1.18.2 this one is 1.12.2. (Using Via Version and Via Backwards)

Works when directly connecting to the Mohist server but not through Bungeecord.

Here is the error on the proxy: https://pastebin.com/dMegDXch

**Comment by Janmm14** [comment]
bungee is picky about scoreboards. a server you were online before did use the same scoreboard name `tm-sb-0`

**Comment by Smurfboi007** [comment]
Aaah, What should I do about it? Remove the scoreboard?

**Comment by Smurfboi007** [comment]
Fixed the thing with the scoreboard here is the new error: https://pastebin.com/0fBsrhGF

**Comment by md-5** [comment]
Youre not running bungeecord
