### ISSUE TITLE
Empty Packet

### ISSUE THREAD

**Issue by Marioc4raft** [SpigotMC/BungeeCord#3354]
### Bungeecord version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:587fb37:1653

### Server version

git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)

### Client version

Spigot 1.8.9

### Bungeecord plugins

AdvancedBan
BungeeChatFilter
BungeeHub
BungeeStaff
BuycraftX
HopeCommander
Luckperms
SkinsRestorer

### The bug

The bug is when i try to join the lobby spigot server, when i connect to lobby, i get kicked to the login server (fallback) like if the server crashed, but the Spigot is working. I tried to join disabling BungeeCord mode on the Spigot server and it works perfectly.

### Log output (links)

DownstreamBridge <-> [lobby] - corrupted frame: Empty Packet!

### Checking

- [x] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
Could be a SkinsRestorer problem, bungeecord mode on spigot does recieve skin data from bungee which skinsrestorer alters. Maybe SkinsRestorer sends invalid data causing this error or the error is caused by the server sending invalid data as result of recieving invalid data.

**Comment by Marioc4raft** [comment]
Same issue

**Comment by Marioc4raft** [comment]
I removed all the plugins and still the same issue
