### ISSUE TITLE
MOTD reset to what defined in subserver when subserver close (IMPORTENT BUG!)

### ISSUE THREAD

**Issue by orjacob555** [SpigotMC/BungeeCord#3363]
### Bungeecord version

1656

### Server version

1.19.1

### Client version

1.19.1

### Bungeecord plugins

nothing

### The bug

For some reason, when the sub server closes but the Bungeecord is still on, the bungeecord takes the MOTD of the sub server from the file server.properties and set him to the player when he kicked, but after a refresh, the MOTD went back to what was set in bungeecord.
video that explain the bug: https://www.youtube.com/watch?v=63HkJSNtfrI&ab_channel=L.P.C2

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
I don't understand how this could happen. In the moment you're shutting down the server it would not send any motd response that bungeecord could redirect to you :/

**Comment by Outfluencer** [comment]
i have seen the video

**Comment by Janmm14** [comment]
My guess: OS/JIT/JVM bug. maybe only occurring with localhost tcp buffer optimizations.

**Comment by md-5** [comment]
Post your bungee config

**Comment by orjacob555** [comment]
I reset already the config and the only thing that i changed is the ip and the port of ther server and sub server.

config.yml:
enforce_secure_profile: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 192.168.1.245:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
remote_ping_cache: -1
network_compression_threshold: 256
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
log_pings: true
connection_throttle_limit: 3
server_connect_timeout: 5000
timeout: 30000
player_limit: -1
prevent_proxy_connections: false
ip_forward: false
groups:
  md_5:
  - admin
remote_ping_timeout: 5000
connection_throttle: 4000
log_commands: false
stats: 1351014d-64b6-404d-a5a2-381519b637f8
online_mode: true
forge_support: false
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: 192.168.1.245:25565
    restricted: false

**Comment by md-5** [comment]
Right, well without ping passthrough its impossible for bungee to take the motd of a subserver

**Comment by orjacob555** [comment]
ohh ok thanks!

**Comment by orjacob555** [comment]
no, i turn it on and it still happend.
  ping_passthrough: true

**Comment by orjacob555** [comment]
> Right, well without ping passthrough its impossible for bungee to take the motd of a subserver


no, i turn it on and it still happend.
ping_passthrough: true

**Comment by orjacob555** [comment]
can you reopen?

**Comment by orjacob555** [comment]
@md-5 
can you reopen?

**Comment by Janmm14** [comment]
The behaviour you have seems to definitely not happen due to wrong bungeecord code, so there will not be a reopen.

**Comment by orjacob555** [comment]
so from where is the problem? if my server and sub server runs without plugins? @Janmm14

**Comment by Janmm14** [comment]
> so from where is the problem? if my server and sub server runs without plugins? @Janmm14

see my previous reply. for debugging that bungeecord issues is not the right place.

**Comment by orjacob555** [comment]
so where i need to talk about that? @Janmm14

**Comment by Outfluencer** [comment]
i thinkits something in netty or the jvm

**Comment by Brokkonaut** [comment]
I think that it might be this new packet: https://wiki.vg/Protocol#Server_Data
It is send from the server when the player has joined and replaces the motd/icon of the server and the motd and icon are not refreshed after a disconnect form the server. So i think the bungee should maybe intercept this packet and replace it with the proper motd and icon.

**Comment by orjacob555** [comment]
I LOVE YOU! @Brokkonaut

**Comment by Outfluencer** [comment]
> I think that it might be this new packet: https://wiki.vg/Protocol#Server_Data It is send from the server when the player has joined and replaces the motd/icon of the server and the motd and icon are not refreshed after a disconnect form the server. So i think the bungee should maybe intercept this packet and replace it with the proper motd and icon.

Thank you, the new Server_Data was the issue
