### ISSUE TITLE
Automatic hexadecimal to decimal conversion inside config.yml

### ISSUE THREAD

**Issue by voltration** [SpigotMC/BungeeCord#3370]
### Bungeecord version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:78ca16d:1656

### Server version

1.19

### Client version

1.19

### Bungeecord plugins

Not related

### The bug

Inside config.yml there will be a section where you can apply ranks to players, however if this players name is hexadecimal it will be converted to decimal when starting the server.

Before the boot:
```
groups:
  0x766f6c74:
  - admin
 ```
  
  After the boot:
```
groups:
  1987013748:
  - admin
  ```

While this isnt a critical bug, it sucks for those who have hexadecimal as their name.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Put it in quote marks

**Comment by voltration** [comment]
> Put it in quote marks

What should I put in quote marks?

**Comment by md-5** [comment]
The username
