### ISSUE TITLE
BungeeCord could do a better job at handling normal java.util.logging.Logger usage.

### ISSUE THREAD

**Issue by floge07** [SpigotMC/BungeeCord#3374]
### Bungeecord version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:6963156:1658

### Server version

git-PaperSpigot-445 (MC: 1.8.8)

### Client version

1.8.9

### Bungeecord plugins

No point in listing because they are private

### The bug

Currently every usage of the java.util.logging.Logger causes unwanted log bahaviour.

If you do the following:
```
Logger logger = Logger.getLogger(getClass().getName());

logger.info("test info log");
```

You get the following output:
```
15:39:09 [SEVERE] Aug 14, 2022 3:39:09 PM full.package.path.class methodName
INFO: test info log
```

What's happening here is:
1. The logrecord gets propagated to the root logger
2. There, the default ConsoleHandler writes it to the err stream with the default format
3. BungeeCord forwards the err stream into its own logger with Level.SEVERE

So it would be great, if BungeeCord could behave similiar to bukkit/spigot in this regard.

What is bukkit doing?
- It somehow forwards these 'external' logs into the bukkit logger and can handle the actual logrecord and not just a string from the err stream and can show the correct level
- Additionally it then applies the normal format. ([10:43:48 INFO]: test info log)

Why is this needed?
If your project gets complex enough to have an external base project that is used in standalone services, spigot and bungeecord plugins, it has to use its own logging without knowing what platform its used on.
The java logging stuff is pretty great in that regard because of the whole hierarchy and log propagation to the parent.
So the application just has to configure the root logger and everything is working automagically ^^.

What is the solution?
To remove the default ConsoleHandler from the root logger and add a Handler that just forwards it to the "BungeeCord" main logger. It works for me when doing that on onLoad of my plugin. Not sure if it would break stuff for anyone else.

I'll look into hopefully opening a PR for this.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
You are using a custom Logger so you need to configure it yourself, this is the way the default Java Logger looks like

**Comment by floge07** [comment]
Yeah... I tested a bit more with the logging stuff and it seems I was being misled by spigot where the logging format was applied automagically. 

**But** there is still a problem with BungeeCord adding this weird prefix.

```
Logger logger = Logger.getLogger(getClass().getName());
logger.setUseParentHandlers(false);

logger.log(Level.INFO, "default: test info log");

ConsoleHandler handler = new ConsoleHandler();
handler.setFormatter(new SimpleFormatter() {
    @Override
    public synchronized String format(LogRecord lr) {
        return "[" + lr.getLevel().getLocalizedName() + "] " + lr.getMessage();
    }
});
logger.addHandler(handler);

logger.log(Level.INFO, "with handler: test info log");
```

Which causes the output:
```
10:15:36 [SEVERE] [INFO] with handler: test info log
```
Notice how the fist log is not printed at all and the second one gets the [SEVERE] prefix from somewhere.
BungeeCord is doing something here that doesn't make sense to me.

**Comment by Janmm14** [comment]
> Yeah... I tested a bit more with the logging stuff and it seems I was being misled by spigot where the logging format was applied automagically.
> 
> **But** there is still a problem with BungeeCord adding this weird prefix.
> 
> ```
> Logger logger = Logger.getLogger(getClass().getName());
> logger.setUseParentHandlers(false);
> 
> logger.log(Level.INFO, "default: test info log");
> 
> ConsoleHandler handler = new ConsoleHandler();
> handler.setFormatter(new SimpleFormatter() {
>     @Override
>     public synchronized String format(LogRecord lr) {
>         return "[" + lr.getLevel().getLocalizedName() + "] " + lr.getMessage();
>     }
> });
> logger.addHandler(handler);
> 
> logger.log(Level.INFO, "with handler: test info log");
> ```
> 
> Which causes the output:
> 
> ```
> 10:15:36 [SEVERE] [INFO] with handler: test info log
> ```
> 
> Notice how the fist log is not printed at all and the second one gets the [SEVERE] prefix from somewhere. BungeeCord is doing something here that doesn't make sense to me.

Thats quite normal behaviour there, you set use parent handlers to false!

**Comment by floge07** [comment]
Sorry but how is this normal bahaviour?
I add no handlers and disable the parent handlers, and we see no log. Good, confirmation that the logger should be clean.
Then I add a console-handler with my simple formatter, and suddenly again there is this prefix. As if bungeecord is modifying the output stream itself.

**Comment by Janmm14** [comment]
@floge07

BungeeCord overrides System.out and System.err. The ConsoleHandler from default java uses System.err to print all messages (see javadoc).
You should set the parent of your logger to `plugin.getLogger()`, that should work fine (the plugin logger sets its parent to the proxy's logger).

If you have better understanding of java log stuff, maybe you can update the relevant code in the log package or in the proxy's BungeeCord class.
It feels like bungee should do something with the global logger or so, so Logger.getLogger is handled better.

**Comment by floge07** [comment]
@Janmm14 
Don't misunderstand. I'm not trying to do any fancy over engineered logging stuff here.
I just had this basic problem of having external projects that use java.utils.logging.Logger everywhere.

I'm not doing anything in these projects to actually log that stuff, thats the job of the application using it.
And on spigot it just worked. It logged it with its format and the correct level.
But with the same setup, BungeeCord logged it with the default format and with Level.SEVERE no matter the actualy level.

So after some digging through the BungeeCord and Spigot code, I reached this workaround:

I now added this in the onLoad of a plugin:
```
Logger rootLogger = Logger.getLogger("");
Logger bungeeLogger = ProxyServer.getInstance().getLogger();

bungeeLogger.setUseParentHandlers(false);

for (Handler handler : rootLogger.getHandlers()) {
	rootLogger.removeHandler(handler);
}
rootLogger.addHandler(new Handler() {
	@Override
	public void publish(LogRecord record) {
		ProxyServer.getInstance().getLogger().log(record);
	}
	@Override
	public void flush() {
	}
	@Override
	public void close() throws SecurityException {
	}
});
```
So to explain this code:
I get the root logger and remove all handlers (which is just the ConsoleHandler by default), then I add a new handler that just calls the BungeeCord main logger.
Also I disable that the BungeeCord logger propagates the logrecord to its parent (which is the root-logger).

In effect this causes every log that is logged by a logger that is not a child of the BungeeCord logger, to be forwarded to the BungeeCord logger when it reaches the root. As if you just directly used ProxyServer.getInstance().getLogger().log().

So what are the opinions on this whole problem?
Is the current behaviour considered a bug? Something to improve?
I could look into how to add this into Bungeecord itself and open a Pullrequest.

**Comment by Janmm14** [comment]
@floge07 Logging on spigot is handling compeltely different. On spigot the system ses logging libraries mojang uses. While for bungee we have this simple logging mechanism.

> But with the same setup, BungeeCord logged it with the default format and with Level.SEVERE no matter the actualy level.

I thought I had explained this one already. Stuff goes to the global logger, which seems to use jre's ConsoleHandler which logs to System.err
And all System.err is redirected by bungee to error log level.

**Comment by floge07** [comment]
@Janmm14 
> I thought I had explained this one already. Stuff goes to the global logger, which seems to use jre's ConsoleHandler which logs to System.err . And all System.err is redirected by bungee to error log level. I'm not trying to justify, jsut to explain.

Yes and I solved the problem by removing the ConsoleHandler from the root logger (btw there is a root logger "" and a global logger "global", which is a child of "") (https://stackoverflow.com/q/49182080)

I looked at how it was done in craftbuckkit
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/browse/nms-patches/net/minecraft/server/dedicated/DedicatedServer.patch#93
There the default handlers from the root logger (well they called the logger variable 'global' ^^) are removed and that ForwardLogHandler is added. I'm doing basically the same.

Guess I'll just open a PR where I add a similar ForwardLogHandler and see how it is accepted. If there are some thoughts about whether it will break something or everything...

Also, I'm going to rewrite my issue description, I know a lot more about the problem now...

**Comment by floge07** [comment]
@Outfluencer Is there any document on how to build bungeecord locally? I want to test the changes before committing.

**Comment by Janmm14** [comment]
> @Outfluencer Is there any document on how to build bungeecord locally? I want to test the changes before committing.

Use maven. Use file in bootstrap/target/ folder

**Comment by Outfluencer** [comment]
hm i am using maven packege if you easily want to test changes i would recomment to load the bungeecord project in intellij and start the bootstrap. it will automaticly do all for you and run it with your code modifications

**Comment by floge07** [comment]
This took a while but there is now a pullrequest (Didn't know GitHub has this web vscode feature and the commits there are automatically signed... Also didn't know in general that you can sign commits before that error message in the pullrequest) 
https://github.com/SpigotMC/BungeeCord/pull/3389

**Comment by Janmm14** [comment]
md-5 would take care of signing commits of pr's ifthey are not yet

**Comment by floge07** [comment]
Ugh....

So what do I do with the PR now? Just wait?
Also, its saying "First-time contributors need a maintainer to approve running workflows"

**Comment by Janmm14** [comment]
Yeah, you just have to wait.

The thing

> "First-time contributors need a maintainer to approve running workflows"

Is one of multiple ways github introduced to prevent their free actions to be abused for cryptocurrency mining

**Comment by Janmm14** [comment]
@floge07 I know and I am feeling you (couple of my PRs still open&waiting). BungeeCord is apparantly still at a really low priority for md_5.

Thats why I [wrote](https://github.com/SpigotMC/BungeeCord/issues/3374#issuecomment-1215708357) :
> Maybe you could try a simple PR, don't overengineer it (until md_5 seems interested in it).
