### ISSUE TITLE
Exit from the bungee cord.

### ISSUE THREAD

**Issue by Mamenekr** [SpigotMC/BungeeCord#3375]
### Feature description

since PlayerDisconectEvent - Does not work properly and ServerDisconectEvent does not indicate that the player has left the server, I would like to ask you to add an event that would indicate that the player has left.

### Goal of the feature

An event that will be triggered when a player exits the game with the type of exit (after a successful entry or before it.).

### Unfitting alternatives

PlayerDisconectEvent - Doesn't work when the player exits the game, no trigger.

ServerDisconectEvent - I didn't find a way to find out if the player left the server (I have to enter the bungee cord server) tried to return the ip address but it returns the address of the lobby.

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by md-5** [comment]
I don't understand what you want and why the existing events don't work

**Comment by Mamenekr** [comment]
I need to know when the player left the bungee cord.
PlayerDisconectEvent Doesn't work because the event is not handled.
And with the help of ServerDisconectEvent it is impossible to understand whether the player left the bungee cord.

**Comment by Janmm14** [comment]
Then there should not be a new event as bandaid fix.
Instead you should submit a bug report with details under which circumstances a player leaves bungeecord and the PlayerDisconnectEvent is not called.

**Comment by Mamenekr** [comment]
Okay, I'll do that.
Thanks a lot!

**Comment by Janmm14** [comment]
ServerDisconnectEvent does have a way to get the player: https://janmm14.de/static/bungeecord-api/net/md_5/bungee/api/event/ServerDisconnectEvent.html#getPlayer()
