### ISSUE TITLE
Allow Accented Characters for certain players

### ISSUE THREAD

**Issue by nnnnt21** [SpigotMC/BungeeCord#3379]
### Feature description

Related to https://github.com/SpigotMC/BungeeCord/pull/3256 and https://github.com/SpigotMC/BungeeCord/pull/3093

Some players want to join my server using usernames with accented characters. This used to work before the newer validation. 
å é ö are the characters

Examples of these accounts:
https://namemc.com/profile/Seng%C3%A5ngaren.1
https://namemc.com/profile/S%C3%A9boutron.1
https://namemc.com/profile/Schokobr%C3%B6tchen.1

### Goal of the feature

To allow more characters on the server

### Unfitting alternatives

Changing the name would be unethical to force our players

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by Outfluencer** [comment]
It's very interesting that such rare usernames are used on your server could i get to know the server domain?

**Comment by Outfluencer** [comment]
Funniest part of it is that mojang don't allow this usernames itself at the latest minecraft version

**Comment by nnnnt21** [comment]
> Funniest part of it is that mojang don't allow this usernames itself at the latest minecraft version

Yeah latest version seems to have broken it, luckily 1.8 reigns supreme

**Comment by Outfluencer** [comment]
I reported this issue all names have been deleted cause of my report i think.
So this is not necessary nomore

https://bugs.mojang.com/browse/MC-255284
