### ISSUE TITLE
Use zstd instead of zlib

### ISSUE THREAD

**Issue by Shineeeeeuh** [SpigotMC/BungeeCord#3385]
### Feature description

For people who don't know zstd : zstd is a compression algorithm created by Facebook and it has the particularity of having a compress and decompress speed more faster than zlib.

If you want more info: it's here https://github.com/facebook/zstd

==================================================================================

So we could use zstd instead of zlib.

### Goal of the feature

The goal of this feature could make the server more faster and optimize.

### Unfitting alternatives

I never find a proxy that include zstd

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by md-5** [comment]
We can't use zstd as Minecraft doesn't use it.... If we used zstd then you would need a modded client
