### ISSUE TITLE
Bad Packet 

### ISSUE THREAD

**Issue by Skyw0lf07** [SpigotMC/BungeeCord#3403]
### Bungeecord version

Bungee Cord version git: BungeeCord-Bootstrap: 1.19-RO  .1-SNAPSHOT: 2d369e8:1664 by md_5

### Bungeecord plugins

This is a problem of Bungeecord itself. The only thing that it is worth mentioning is that I have Nuvotifier installed and using Flamecord

### The bug

When someone votes, I get this error in Bungeecord console. I have no mods, only plugins 

![IMG_20221122_065522](https://user-images.githubusercontent.com/81262586/203248784-d2d65fd1-6673-419b-b787-b23b306877f3.jpg)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
>Nuvotifier installed and using Flamecord

So plugins and not bungeecord

**Comment by Skyw0lf07** [comment]
-_-
I opened an issue in the nuvotifier GitHub and they told me that it was Bungeecord. I agree. The plugin doesn't give this type of error

**Comment by Janmm14** [comment]
The source ip in question is from a minecraft server list.
It is likely trying to ping your server (get motd aka server list text) but fails miserably at it.

**Comment by Skyw0lf07** [comment]
Hmmm, I doubt it because it happens with all voting sites. Not just one specifically.

**Comment by Janmm14** [comment]
> Hmmm, I doubt it because it happens with all voting sites. Not just one specifically.

But you can see your server just fine in your mc client's server list?
