### ISSUE TITLE
1.19.3 Quiet Exception Packet

### ISSUE THREAD

**Issue by mnfu** [SpigotMC/BungeeCord#3407]
### Bungeecord version

Build #1671

### Server version

Paper 1.19.2 Build #207

### Client version

1.19.3

### Bungeecord plugins

Geyser
Floodgate

### The bug

Not able to connect; quiet packet exception
Confirmed by separate parties to also be the case on a completely barebones 1.19.3 bungeecord setup (with paper)

![530DF5CF-20C2-4446-A197-D345BC5F62CE](https://user-images.githubusercontent.com/95727104/206248170-56c1b2e5-7fd1-4325-96ca-2636b2c8c8ee.jpeg)

### Log output (links)

i do not have them at the moment, but I will upload some in the comments later. Just trying to let you know asap.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
- Not using supported server software
- Ticked all check boxes
- Neglected to mention important server plugins (1.19.2 server version suggests must be using some compatibility plugin)

Almost certainly a ViaVersion issue - sending features packet at incorrect time (pre login).

Please reopen with further info using a supported server version (spigot 1.19.3 + 1.19.3 client or spigot 1.19.2 + 1.19.2 client)
