### ISSUE TITLE
disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!

### ISSUE THREAD

**Issue by nuttapillar** [SpigotMC/BungeeCord#3409]
### Bungeecord version

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:e717676:1672 by md_5

### Server version

Current: git-Purpur-1858 (MC: 1.19.2)*

### Client version

1.19

### Bungeecord plugins

Bungeeguard, geyser, floodgate, minimotd universal, serverswitcher.

### The bug

Players couldn't get in using 1.19.3, despite me updating viaversion plugin. So I decided to update bungeecord and purpur to latets. Now most players cant join, and are getting "disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!"

### Log output (links)

https://gist.github.com/nuttapillar/4e1996435fe093faeb5c97fddddaf49d

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by xIsm4** [comment]
> ### Bungeecord version
> This server is running BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:e717676:1672 by md_5
> 
> ### Server version
> Current: git-Purpur-1858 (MC: 1.19.2)*
> 
> ### Client version
> 1.19
> 
> ### Bungeecord plugins
> Bungeeguard, geyser, floodgate, minimotd universal, serverswitcher.
> 
> ### The bug
> Players couldn't get in using 1.19.3, despite me updating viaversion plugin. So I decided to update bungeecord and purpur to latets. Now most players cant join, and are getting "disconnected with: Exception Connecting:QuietException : Unexpected packet received during server login process!"
> 
> ### Log output (links)
> https://gist.github.com/nuttapillar/4e1996435fe093faeb5c97fddddaf49d
> 
> ### Checking
> * [x]  I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
> * [x]  I think this is **not** an issue with a bungeecord plugin.
> * [ ]  I have not read these checkboxes and therefore I just ticked them all.
> * [x]  This is not a question or plugin creation help request.

Do not use ViaVersion in the proxy. BungeeCord is already a multi-protocol software. The only thing it will cause and more now are problems.

**Comment by nuttapillar** [comment]
Viaversion isnt on my proxy server. it's only on the end servers.

**Comment by nuttapillar** [comment]
I'm not using 1.19.3 though, so im not sure how that's relevant to my case.

**Comment by nuttapillar** [comment]
Also, i tried running without viaversion on the backend server, and then i couldnt even get in, because bedrock has autoupdated, and the server isnt on 1.19.3 yet.

**Comment by nuttapillar** [comment]
Seems to be fixed now. I got a link from the viaversion discord to an even newer dev build, which seemed to fix the issue.
