### ISSUE TITLE
Global tab not working

### ISSUE THREAD

**Issue by Melo810** [SpigotMC/BungeeCord#3413]
### Bungeecord version

git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:511017a:1670 by md_5

### Server version

bungee

### Client version

1.19.1

### Bungeecord plugins

BungeeGuard, LuckPerms, Masuitechat, masuitecore, masuitehomes, masuitewarps, masuiteteleports, premiumvanish, ultracustomizer, ultraEconomy, Animated tab (tablist).

### The bug

Hello, we have a problem with the tab. We have 3 servers and we would like to link the tab to see all the players connected. But since we updated all the bungee plugins to version 1.19.1 the tab doesn't work anymore. However in the config we have tab_llist: Global_PING.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Bungee has only supported per server tab for years, there's no way it worked before unless it was a plugin
