### ISSUE TITLE
Lower version (below 1.19.2) unable to connect

### ISSUE THREAD

**Issue by fadfhkdfga** [SpigotMC/BungeeCord#3414]
### Bungeecord version

BungeeCord 1672

### Server version

git-Paper-388 (MC: 1.18.2)

### Client version

1.18.2

### Bungeecord plugins

floodgate-bungee-73.jar
Geyser-BungeeCord-1236.jar
HubMagic-0.2.6.jar
NuVotifier-2.7.3.jar
SlashServer-3.0.jar
TAB-3.1.5.jar

### The bug

When using the bungee code version 1672, users of the lower version (1.19.2 or lower) cannot connect to the server.
Previously, I was using the 1670 version.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Cannot reproduce.
![image](https://user-images.githubusercontent.com/1007849/208268506-7d0e8edd-c412-4fb6-afb5-4b52c6bf504b.png)
