### ISSUE TITLE
Error in console while connecting

### ISSUE THREAD

**Issue by Floodo** [SpigotMC/BungeeCord#3420]
### Bungeecord version

BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:a5b6eb6:1674 by md_5

### Server version

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba)

### Client version

1.12.2

### Bungeecord plugins

BungeeCord
Geyser-Bungeecord
BungeeGuard

### The bug

I was connecting to me bungeecord servers all the time, no problem .... but one of mine server (modded 1.12), when I wrote /home [nameOfTheHome] i was kicked out of the servers completely. After that I want to join to server again (MINE2Gether). Thats okay. Then I want to connect to my modded server (modes). Than it all happend... From bungee console, it says that that it disconnected me from MINE2Gether, and want to connect to modes...but it didnt, because of some error. So it want me to sent back to MINE2Gether, and somehow, "I was on the server" (but didn't), so it disconnected me from server completely. 

I have also ViaVersion and ViaBackwards.

### Log output (links)

```
https://gist.github.com/Floodo/0ef769bf9ec536afe6c4d65087741d12
https://gist.github.com/Floodo/a137f0d462a789d351b19d9f4913e21f
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
First error looks like modded client/server, wh8ch is not supported by bungeecord at all. Try to use Waterfall.

Second error is nothing bungee can fix.

**Comment by Floodo** [comment]
I started Waterfall (instead of BungeeCord), and the same error. So I enabled "disable_entity_metadata_rewrite", and it works!! :) .... probably problem with entities names or something like that. Thank you!! :))
