### ISSUE TITLE
In Bungee Code, even if the groups function is activated in the tab list config item, access is not possibl

### ISSUE THREAD

**Issue by adam8014** [SpigotMC/BungeeCord#3421]
### Bungeecord version

1.19-R0.1-SNAPSHOT:f8e0bcc:1675 by md_5

### Server version

paper 1.19.3.368

### Client version

1.19.3

### Bungeecord plugins

BungeeMultipleLobbysTeleporter 6.0.0
LuckPerms-Bungee-5.4.55
TabList-bungee-v2.3.2

### The bug

An error occurs in the bungee code even if you activate the group nickname in TabList-bungee-v2.3.2

TabList-bungee config
tablist-groups:
  enabled: false

![1](https://user-images.githubusercontent.com/65481743/210465881-f66fe4be-1713-47f4-85b7-64ef86ff1dc2.png)

### Log output (links)

https://paste.gg/p/anonymous/6a69c347b2064029adbbb5e118b06a03/files/5af5fb39248d483e8b7432991694f83e/raw

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
This is an issue with the tab plugin not supporting 1.19.3
