### ISSUE TITLE
Unknown Error...

### ISSUE THREAD

**Issue by SpartianKing** [SpigotMC/BungeeCord#3436]
### Bungeecord version

#1679

### Server version

Paper

### Client version

1.19.3

### Bungeecord plugins

None

### The bug

I don't know what is going on.... It just was working then it died!

### Log output (links)

01:40:20 [INFO] Using mbed TLS based native cipher.
01:40:20 [INFO] Using zlib based native compressor.
01:40:20 [INFO] Enabled BungeeCord version git:BungeeCord-Bootstrap:1.19-R0.1-SNAPSHOT:19424ab:1678
01:40:20 [INFO] Not on Windows, attempting to use enhanced EpollEventLoop
01:40:20 [INFO] Epoll is working, utilising it!
01:40:20 [INFO] Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())

01:40:20 [INFO] Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())

01:40:20 [INFO] Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())

01:40:20 [INFO] Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())

01:40:20 [INFO] Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())

01:40:20 [INFO] Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())

01:40:20 [INFO] Attempting to update plugin from ModuleVersion(build=1679, git=1b6d845) to ModuleVersion(build=1678, git=19424ab)

01:40:20 [INFO] Attempting to Jenkins download module cmd_alert v1678

01:40:21 [INFO] Download complete

01:40:21 [INFO] Attempting to update plugin from ModuleVersion(build=1679, git=1b6d845) to ModuleVersion(build=1678, git=19424ab)

01:40:21 [INFO] Attempting to Jenkins download module cmd_find v1678

01:40:21 [INFO] Download complete

01:40:21 [INFO] Attempting to update plugin from ModuleVersion(build=1679, git=1b6d845) to ModuleVersion(build=1678, git=19424ab)

01:40:21 [INFO] Attempting to Jenkins download module cmd_list v1678

01:40:21 [INFO] Download complete

01:40:21 [INFO] Attempting to update plugin from ModuleVersion(build=1679, git=1b6d845) to ModuleVersion(build=1678, git=19424ab)

01:40:21 [INFO] Attempting to Jenkins download module cmd_send v1678

01:40:21 [INFO] Download complete

01:40:21 [INFO] Attempting to update plugin from ModuleVersion(build=1679, git=1b6d845) to ModuleVersion(build=1678, git=19424ab)

01:40:21 [INFO] Attempting to Jenkins download module cmd_server v1678

01:40:21 [INFO] Download complete

01:40:21 [INFO] Attempting to update plugin from ModuleVersion(build=1679, git=1b6d845) to ModuleVersion(build=1678, git=19424ab)

01:40:21 [INFO] Attempting to Jenkins download module reconnect_yaml v1678

01:40:21 [INFO] Download complete

01:40:21 [INFO] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:19424ab:1678 by SpigotMC
01:40:21 [INFO] Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:19424ab:1678 by SpigotMC
01:40:21 [INFO] Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:19424ab:1678 by SpigotMC
01:40:21 [INFO] Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:19424ab:1678 by SpigotMC
01:40:21 [INFO] Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:19424ab:1678 by SpigotMC
01:40:21 [INFO] Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:19424ab:1678 by SpigotMC
01:40:21 [SEVERE] Exception in thread "main"
01:40:21 [SEVERE] java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getWidth()" because "image" is null

01:40:21 [SEVERE]     at net.md_5.bungee.api.Favicon.create(Favicon.java:63)

01:40:21 [SEVERE]     at net.md_5.bungee.conf.Configuration.load(Configuration.java:82)

01:40:21 [SEVERE]     at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282)

01:40:21 [SEVERE]     at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)

01:40:21 [SEVERE]     at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
your server icon image is invalid
