### ISSUE TITLE
Bungeecord plugin development

### ISSUE THREAD

**Issue by DeadlySinFredo** [SpigotMC/BungeeCord#3449]
### Bungeecord version

Newest

### Server version

-

### Client version

1.19.3

### Bungeecord plugins

-

### The bug

Hello first of all, I'm trying to program bungeecord plugins like I did back then by adding the bungeecord jar and writing "extends plugin" in the main class and then pressing import, but then an import comes up, but it's displayed in red and I click nothing can access to program with the bungeecord jar. can you help me?

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
So why should we answer you here after you
1. used the wrong button on this [page](https://github.com/SpigotMC/BungeeCord/issues/new/choose)
2. lied about the last checkbox

Use [spigotmc.org](https://www.spigotmc.org) forums for help with user errors.
