### ISSUE TITLE
Offline players cannot join

### ISSUE THREAD

**Issue by PostMars** [SpigotMC/BungeeCord#3462]
### Bungeecord version

nullcordx 1.19.4

### Server version

git-Paper-519 (MC: 1.19.4)

### Client version

1.16.5

### Bungeecord plugins

AdvancedBan-Bundle-2.3.0-RELEASE
LuckPerms-Bungee-5.4.36
SkinsRestorer
NullCordX-Bridge

### The bug

![B@6D_YT3B V7D{@~(QB@L3J](https://user-images.githubusercontent.com/132077609/235172205-9e4f2849-18f8-44a3-b743-951da5da44fc.png)
![0VZY6KZR}RMXBYS7O_@U99Y](https://user-images.githubusercontent.com/132077609/235173057-b7d4a201-cb80-439a-832a-e32523128799.png)

### Log output (links)

[latest.log](https://github.com/SpigotMC/BungeeCord/files/11354335/latest.log)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
Not read all the checkboxes, also nullcordx 1.19.4 is not bungeecord
