### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by linsaftw** [SpigotMC/BungeeCord#3473]
### Feature description

Support 1.20 protocol.

### Goal of the feature

Support 1.20 clients.

### Unfitting alternatives

ViaVersion, due to it's performance drawbacks.

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by p0t4t0sandwich** [comment]
> ViaVersion, due to it's performance drawbacks.

The performance isn't really even the problem, Via themselves recommend that you *do not* run Via on the proxy server
