### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bratik17078** [SpigotMC/BungeeCord#3477]
### Bungeecord version

idk

### Bungeecord plugins

nothing

### The bug

11:23:53 [INFO] [/93.126.91.103:48097] <-> InitialHandler has connected
11:23:54 [INFO] [Bratik17078] disconnected with: Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? io.netty.channel.AbstractChannel$AnnotatedConnectException
11:23:54 [INFO] [Bratik17078] -> UpstreamBridge has disconnected
how to fix that?

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
_**Incorrectly configured address/port/firewall?**_
