### ISSUE TITLE
 Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? 

### ISSUE THREAD

**Issue by wtfashu09** [SpigotMC/BungeeCord#3485]
### Bungeecord version

bungeecord-1.20

### Server version

This server is running Paper version git-Paper-17 (MC: 1.20) (Implementing API version 1.20-R0.1-SNAPSHOT) (Git: c287e92)

### Client version

1.19.4

### Bungeecord plugins

BungeeGaurd, Via Version, Via Backwards, VIa Rewind

### The bug

 Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? 

### Log output (links)

[16:03:37 INFO]: [wtfashu09] disconnected with: Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? 
[16:03:37 INFO]: [/223.xxx.xxx.x:00000|wtfashu09] -> UpstreamBridge has disconnected

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
> Incorrectly configured address/port/firewall?

The things **in the error message** are the cause for the problem and **not BungeeCord**.
Please be aware that pterodactyl does come with a firewall by default.
