### ISSUE TITLE
Send player to another server

### ISSUE THREAD

**Issue by tmdakm** [SpigotMC/BungeeCord#3487]
### Feature description

I wish the BungeeCord API could send players to a server not in the BungeeCord group and be able to pass the player's authentic information.

### Goal of the feature

send players to another server and be able to pass player's authentic information.

### Unfitting alternatives

I can't find any way to solve it, so there is no other plan

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by Outfluencer** [comment]
This is not possible in any way for a proxy as other servers needs to verify the sessions with the mojang auth servers.

**Comment by Janmm14** [comment]
If this would be technically possible, any server would be able to impersonate all their players on other servers.

Apart from that impossibility, I do not see legitimate use cases where this would be required.
