### ISSUE TITLE
Unable to send a custom bungeecord message via a specific player

### ISSUE THREAD

**Issue by LyFl0w** [SpigotMC/BungeeCord#3498]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.1-SNAPSHOT:2d6d89d:1721

### Server version

i used Paper (git-Paper-96 (MC: 1.20.1))

### Client version

1.20.1

### Bungeecord plugins

QuillCraftBungee

### The bug

this code does not work : 
![Capture d’écran 2023-08-03 144706](https://github.com/SpigotMC/BungeeCord/assets/91786781/db390980-36b8-4adb-9dcf-38a3302d705e)
but replacing the ProxiedPlayer with a ServerInfo works, but the player for the request is a totally random player, which is annoying. It's technically possible to do without it, but it can sometimes be a pain i thinks.
Or you could remove the ability to send a custom message from a player. 

Someone had already discovered the bug before me : https://www.spigotmc.org/threads/solved-proxied-player-senddata-help.38126/

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
player.sendData sends data to the player, not to the server.
registering channel is not required for bungee-server communication.

I suggest continue using player.getServer().sendData, but without delay and send the player name along with it, then let the server cache the info for like a minute to be consumed when the player joins.
When no player is online on the server yet, bungee puts the message into a packet queue for the server.

I would let the spigot request the information from the bungee in asyncprejoinevent.
