### ISSUE TITLE
SelectorComponent parity update

### ISSUE THREAD

**Issue by BradBot1** [SpigotMC/BungeeCord#3512]
### Feature description

The selector component is missing the feature to modify it's separator:

https://github.com/SpigotMC/BungeeCord/blob/master/chat/src/main/java/net/md_5/bungee/api/chat/SelectorComponent.java

Despite (as below shows) the NMS implementation supporting it

![image](https://github.com/SpigotMC/BungeeCord/assets/45739045/993f71cc-58fb-437e-816e-04dbb5a2326b)

### Goal of the feature

To have full parity with the [JSON text api](https://minecraft.fandom.com/wiki/Raw_JSON_text_format#Scoreboard_Value)

### Unfitting alternatives

Utilising NMS (on spigot) or sending packets defeats the point of the component api

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by Janmm14** [comment]
The `@Getter` and `@Setter` annotations on the class generate a getter and setter method for the separator field.

The `@AllArgsConstructor` annotation generates a constructor taking a separator string and sets the field separator.
