### ISSUE TITLE
Login with Viaversion and Client 1.20.2 not possible

### ISSUE THREAD

**Issue by Leahcimkrob** [SpigotMC/BungeeCord#3521]
### Bungeecord version

BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:0509303:1738

### Server version

git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)

### Client version

1.20.2

### Bungeecord plugins

BetterSecurity, BungeeChat, BungeePluginManagerPlus, BungeeSpy, BungeeTokens, CensorReloaded, CMIB, CraftingStore, DSGVO, ExceptionAnnouncer, floodgate, Geyser-BungeeCord, LiteBans, LuckPerms, Maintenance, MarriageMaster, NoVPN, NuVotifier, RankGift, RankUpgrade, spark, TAB, UltimateAutoRestartPassthrough, ViaBackwards, ViaVersion, cmd_alert, cmd_find, cmd_kick, cmd_list, cmd_send, cmd_server, reconnect_yaml.

### The bug

When I try to access the server with version 1.20.2 I get the message connection aborted

### Log output (links)

```
https://gist.github.com/Leahcimkrob/24be0fad486b65a4c4ddb858eb24cfb2
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
ViaVersion is not a supported plugin

**Comment by Leahcimkrob** [comment]
You asked me to create a new ticket and then this?

**Comment by md-5** [comment]
Then I saw you had viaversion

**Comment by Leahcimkrob** [comment]
I hate this wrangling of authority. You say, Via's problem, Via says it's your business and I as a dev who would like to use your crap is the idiot. If there are problems, just try to solve them together and not just blame each other. It would help everyone in the MC world.

**Comment by md-5** [comment]
If the developers think there's a problem then they can be specific about it

**Comment by md-5** [comment]
That is an issue with the Tab plugin

**Comment by Leahcimkrob** [comment]
Thank you,
