### ISSUE TITLE
Failure on Java 21

### ISSUE THREAD

**Issue by SlimeDog** [SpigotMC/BungeeCord#3522]
### Bungeecord version

1739

### Server version

N/A

### Client version

N/A

### Bungeecord plugins

N/A

### The bug

BungeeCord 1739 runs fine on Java 17.0.6. Running it on Java 21 produces [hs_err file](https://whitedog.straight8.com/drops/bungee/hs_err_pid12508.log).

### Log output (links)

No log created

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by bob7l** [comment]
The error is related to the G1 garbage collector. Allocate more memory (1-2GB) and see if the issue persists.

**Comment by SlimeDog** [comment]
Here is my start command
`java -Xms512M -Xmx512M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -Djava.security.manager=allow -Dfile-encoding=UTF-8 -jar bungee.jar nogui`

`-Xmx3G` produced the same error with Java 21. What else should I try?

**Comment by andrew121410** [comment]
Yeah, I get the same error started happening after https://github.com/SpigotMC/BungeeCord/commit/f486a251f3b41788f8f9e97eab5293e91f51b96e was pushed. 

I have allocated 4GB to BungeeCord.

I didn't report because didn't have a computer at the time, and just forgot lol

**Comment by md-5** [comment]
Looks like a netty issue, I've downgraded it

**Comment by SlimeDog** [comment]
Confirmed fixed with BungeeCord-1.20-1740. Thanks.
