### ISSUE TITLE
1.20.2 player kicking at PostLoginEvent is broken

### ISSUE THREAD

**Issue by Outfluencer** [SpigotMC/BungeeCord#3525]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:497c687:1741

### Server version

3882-Spigot-17ca32d-452fcb5 (MC: 1.20.2)

### Client version

1.20.2

### Bungeecord plugins

Server System of my Server (test server: raynight.eu:25577)

### The bug

API is broken, i am using the PostLoginEvent to kick the player if he dont have permission to join via specific domain.
Works great for all clients but 1.20.2

I am using only api methods. Here is the code:

```@EventHandler(priority = EventPriority.HIGHEST)
    public void login(PostLoginEvent event) {
        if(event.getPlayer().hasPermission("maintenance")) return;

        InetSocketAddress address = event.getPlayer().getPendingConnection().getVirtualHost();
        if(address == null || map == null || map.isEmpty()) return;
        String domain = address.getHostName().toLowerCase(Locale.ROOT);

        for (Map.Entry<String, MotdJson> entry : map.entrySet()) {
            if(domain.contains(entry.getKey())) {
                MotdJson motd = entry.getValue();
                if(motd.maintenance) {
                    event.getPlayer().disconnect( Joiner.on( "\n" ).join( motd.maintenance_text ) );
                }
                return;
            }
        }
    }
```

### Checking

- [x] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
What about it is broken? What exactly is the issue?

**Comment by Outfluencer** [comment]
The issue is that the client cant read the kick packet and shows an exception with the raw string and not the component of the kick packet

**Comment by bob7l** [comment]
Reproduced, kicking someone during the config stage will produce this client-side error:
[https://i.gyazo.com/d1aef4b745e3e9cb91b66e02a9713a89.png](url)

I also checked the string being sent to the client and confirmed it's `{"text":"asd"}`

I also confirmed that kicking during the GAME, or LOGIN state works perfectly. 

So this is either a client bug, or maybe the client is expecting certain data in the CONFIG stage before being able to properly kick a player. I can test that later if need be, just busy at this very moment.

**Comment by md-5** [comment]
Thanks! There's a kick packet in the config stage, so it should be able to be done, but I wouldn't put it past an issue in either the client or bungee with switching protocols.

**Comment by bob7l** [comment]
> Thanks! There's a kick packet in the config stage, so it should be able to be done, but I wouldn't put it past an issue in either the client or bungee with switching protocols.

It seems to have been fixed..? Not sure if Mojang just pushed a hotfix or what, but the issue is no longer reproducible under the same exact variable.

**Comment by bob7l** [comment]
>bungee with switching protocols.

Yup, that's what it is. Setting the encode protocol of the user to CONFIGURATION before sending the kick packet fixes it.

https://i.gyazo.com/671e8b334fe4877dbde4953051fa2c54.png

Not sure what the intention was with setting the encode protocol after the finish2(), so I assume it's a simple mistake?
