### ISSUE TITLE
Switching between servers causes a decoding error [1.20.2]

### ISSUE THREAD

**Issue by BoomEaro** [SpigotMC/BungeeCord#3527]
### Bungeecord version

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:f3397b3:unknown by md_5

### Server version

This server is running CraftBukkit version 3890-Spigot-a0f3d48-df3738a (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)

### Client version

1.20.2

### Bungeecord plugins

None

### The bug

Switching between servers causes packet decoding error, if you perform some actions at this moment, for example, moving intensively (sending player position packet).
There are no plugins on any instance of spigot and bungeecord.

I have been able to replicate this whenever a client falls from an elevated position or frequently sends packets to Upstream. For example by teleporting to a huge height (/tp ~ 10000 ~).
And also at the moment I am testing on a server that is far away from me and has a ping of more than 100 ms, perhaps for this reason it is difficult to repeat in local server.

(I apologize for not creating this ticket earlier, as I thought it was the same problem: https://github.com/SpigotMC/BungeeCord/issues/3523)

### Log output (links)

One of this exceptions occurs on BungeeCord:
BungeeCord NPE on getProtocol() getting: https://pastebin.com/VmMq14hC
BungeeCord 'Cannot get ID for packet class': https://pastebin.com/X6TeX3Rz

Spigot: https://pastebin.com/M7uvqCFd

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by BoomEaro** [comment]
I also manage to repeat this every time the player is in a boat, since the client is sending about ~60 packets per second at this moment.
I modified the exception printing to show a complete error with Upstream and Downstream: https://pastebin.com/sW7grXw1

**Comment by Outfluencer** [comment]
Reads Configuration start packet in config state but it should be in Login state

**Comment by bob7l** [comment]
I was able to reproduce it. Getting errors on the Spigot like bad packet id (Movement ids), etc. So the spigot is still in CONFIG stage (I assume), and is being forwarded normal GAME state packets. 

Reason for this is because we're sending `StartConfiguration` then instantly swapping the user's `DownstreamBridge` to that of the server who is still in the CONFIG stage. The player will only be in CONFIG stage once that packet reaches them, so all the packets they send before receiving it will be forwarded to our newly assigned `DownstreamBridge` resulting in tons of random downstream decoder errors.

**Comment by BoomEaro** [comment]
> I was able to reproduce it. Getting errors on the Spigot like bad packet id (Movement ids), etc. So the spigot is still in CONFIG stage (I assume), and is being forwarded normal GAME state packets.
> 
> Reason for this is because we're sending `StartConfiguration` then instantly swapping the user's `DownstreamBridge` to that of the server who is still in the CONFIG stage. The player will only be in CONFIG stage once that packet reaches them, so all the packets they send before receiving it will be forwarded to our newly assigned `DownstreamBridge` resulting in tons of random downstream decoder errors.

Seems like one solution in my opinion is to try to replace Downstream when receiving Configuration Acknowledged (or StartConfiguration class)

**Comment by bob7l** [comment]
> Seems like one solution in my opinion is to try to replace Downstream when receiving Configuration Acknowledged (or StartConfiguration class, for some reason they have the same name)
Yeah something like that. Off the top of my head, could make a custom UpstreamBridge that continues to forward non-config packets to the currently connected server. Then forward all the CONFIG stage packets to the new downstream and maybe call the rest of the cutThrough function once the config stage is fully done.

That would solve more issues, like SeverSwitchEvent being called while plugins assume the player is in GAME state. 

But I believe I read somewhere Md_5 was trying to avoid executing the ServerSwitchEvent after the config stage. Don't remember

**Comment by md-5** [comment]
Isn't the fix just to discard packets from a different game state?

Everything else should fall into place because sending the StartConfiguration only changes the encoder; and receiving StartConfiguration changes the decoder.

> Yeah something like that. Off the top of my head, could make a custom UpstreamBridge that continues to forward non-config packets to the currently connected server. Then, once the config request is acknowledged, forward all the CONFIG stage packets to the new downstream and maybe call the rest of the cutThrough function once the config stage is fully done.

I think this would be much more difficult to do properly and break plugins in different ways.

>  I modified the exception printing to show a complete error with Upstream and Downstream: https://pastebin.com/sW7grXw1

Thanks, I was going to push this. The utility of errors without stack traces is basically 0 so the change to remove them should be reverted in master

**Comment by md-5** [comment]
I was able to reproduce using the teleport example and fake latency: `sudo tc qdisc add dev lo root handle 1:0 netem delay 100msec` (remove with `sudo tc qdisc del dev lo root`)

The above commit (3cb7a12738bcfc1b2b071634f2d10950f8d3c9e8) fixes it in my test case.

Let me know how you go.
