### ISSUE TITLE
Bug Skin Bungeecord

### ISSUE THREAD

**Issue by Link0Darck** [SpigotMC/BungeeCord#3538]
### Bungeecord version

This server is running BungeeCord version git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:f3397b3:1745 by md_5

### Server version

This server is running CraftBukkit version 3893-Spigot-a0f3d48-251af0d (MC: 1.20.2) (Implementing API version 1.20.2-R0.1-SNAPSHOT)

### Client version

1.20.2

### Bungeecord plugins

![Capture d'écran 2023-09-28 121048](https://github.com/SpigotMC/BungeeCord/assets/28543376/a0142dd5-4728-4cc5-8140-f153dd83532d)

### The bug

Good morning,
I've asked the question several times but I haven't really received an answer, so I turn to GitHub.
To explain the problem I went from version 1.20.1 (everything works) to 1.20.2 then the problem is as if Steve's skin is deactivated and there is only Alex and that makes me its when I share a Bungeecord if it is on a Spigot server it goes without problem

Frequently asked questions and answers:
1. I am in online mode (no crack)
2. everything is configured correctly (ip forward, ect...)
3. I regularly update everything but nothing changes
4. I don't use (viaversion, skinrestorer, geyser)

Thank you for your help in advance

Screenshot for proof and nickname `Link_Darck` [skin links
![2023-09-23_17 18 36](https://github.com/SpigotMC/BungeeCord/assets/28543376/7dff7119-030b-4b2e-a95e-761ac1e0d59b)
](https://minecraft.tools/fr/skin.php?skin=Link_Darck)

### Log output (links)

NOTHING

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Luccboy** [comment]
Hi, I guess this is the same issue as explained here: https://github.com/SpigotMC/BungeeCord/issues/3533
It looks like there's already a PR to fix this, so there should be a solution soon.
