### ISSUE TITLE
Random writes in config?

### ISSUE THREAD

**Issue by KweezyCode** [SpigotMC/BungeeCord#3548]
### Bungeecord version

latest

### Bungeecord plugins

built-in plugins 

### The bug

![изображение](https://github.com/SpigotMC/BungeeCord/assets/36813920/21bb5788-2f74-4ba1-81b9-a4c9d89a7eb6)

It happens every time i start bungeecord. I am using git to save server configs, but bungeecord shuffles strings so it is totally unusable. I think writing to disk unchanged config is unneeded.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
#2013

**Comment by KweezyCode** [comment]
no fix since 2016? you are joking...

**Comment by KweezyCode** [comment]
closing as duplicate
