### ISSUE TITLE
Can't switch server

### ISSUE THREAD

**Issue by EpicJosch** [SpigotMC/BungeeCord#3550]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:a7dbbc2:1756

### Server version

git-Paper-196 (MC: 1.20.1)

### Client version

1.20.1

### Bungeecord plugins

- ABPS.jar
- BungeeOnlineTime.jar
- CMIB-1.0.2.2.jar
- EJBanSystem.jar
- EpicJoschNetzwerkHUBPlugin.jar
- floodgate-bungee.jar
- LuckPerms-Bungee-5.4.102.jar
- movemenow-1.2-17.jar
- nuvotifier.jar
- XConomy-Bukkit-2.25.1.jar

### The bug

When i switch server with /hub for example then sometimes i get disconnected from the network. The error message is in the Log output section

I also testet with NO PLUGINS on the proxy but still same issue.

I guess this error is because the client sends Playing Packets (PlayerMovePosPacket) in the config phase and bungeecord cant handle it. Can't you just block packets that are not supposed to be received during config phase from bungee instead of kicking off network?

### Log output (links)

```
18:39:11 [INFO] .Rotkauz executed command: /hub
18:39:11 [INFO] [.Rotkauz] <-> ServerConnector [lobby] has connected
18:39:11 [INFO] [.Rotkauz] <-> DownstreamBridge <-> [citybuild] has disconnected
18:39:11 [WARNING] [.Rotkauz] -> UpstreamBridge - could not decode packet! io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 160))
18:39:11 [INFO] [.Rotkauz] disconnected with: DecoderException : java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 160)) @ io.netty.handler.codec.MessageToMessageDecoder:98
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by MattTheTekie** [comment]
I have the same issue

**Comment by Kas-tle** [comment]
This is our bug (Geyser). Please disregard. Apologies.
