### ISSUE TITLE
Error : Already exists in this scoreboard

### ISSUE THREAD

**Issue by xyfwdy** [SpigotMC/BungeeCord#3564]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:0925c06:1772

### Server version

 git-Paper-291 (MC: 1.20.2)

### Client version

1.20.2

### Bungeecord plugins

Nothing

### The bug

Players cannot connect to the server for the first time

### Log output (links)

https://gist.github.com/xyfwdy/5814f7e283e17be6bb13cae588e330e0

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
bad plugin on spigot. Especially as first connection is failing.

**Comment by xyfwdy** [comment]
> bad plugin on spigot. Especially as first connection is failing.

Thanks!
