### ISSUE TITLE
java.util.NoSuchElementException: packet_handler

### ISSUE THREAD

**Issue by DarkDimka** [SpigotMC/BungeeCord#3575]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.2-SNAPSHOT:1a80773:1779 by md_5

### Server version

3870-Spigot-d2eba2c-78796c9 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT)

### Client version

1.20.1 (fabric)

### Bungeecord plugins

AdvancedNMotd-9.2.0 
mcAuth-bungee-1.7.12
PL-Hide-1.5.21 
SkinsRestorer 
ViaBackwards-4.9.0
ViaVersion-4.9.3-SNAPSHOT

### The bug

An error occurs when switching from the lobby to another server/regime java.util.NoSuchElementException: packet_handler:
![image](https://github.com/SpigotMC/BungeeCord/assets/153770079/358c0c9d-ddf1-4c19-bcbd-e1f5f167b20d)

### Log output (links)

```
<script src="https://gist.github.com/DarkDimka/96c77d0bb8b49e8ce9a2f1635f3a9be4.js"></script>
log in regime 
```
<script src="https://gist.github.com/DarkDimka/b56ff74f5598ed6225154d3f95fa5240.js"></script>
log in BungeeCord
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by DarkDimka** [comment]
So I need to remove Viaversion from BungeeCord or regime?

**Comment by md-5** [comment]
Both

**Comment by Janmm14** [comment]
If any issues occurr while you are using Via plugins, you can report them to viaversion. I would highly suggest that IF you decide to use them, use them NOT on bungee.
