### ISSUE TITLE
BungeeCord corrupts component from 1.20.4 downstream

### ISSUE THREAD

**Issue by brickmonster** [SpigotMC/BungeeCord#3584]
### Bungeecord version

b711e40:1782

### Server version

Paper 1.20.4 v336

### Client version

1.20.4

### Bungeecord plugins

None

### The bug

(This bug does not happen when connected directly to the downstream server).

When downstream sends a component as the tab list display name of player, the client receives the wrong data.
It may happen in other packets, I didn't check those yet. Chat packets are unaffected.

These are the json representations:

Downstream sends: {"text":"","extra":[**"hello"**,{"text":"there","color":"#ff0000"},{"text":"friend","font":"minecraft:default"}]}

BungeeCord reads (in readBaseComponent): {"extra":[**{"":"hello"}**,{"color":"#ff0000","text":"there"},{"font":"minecraft:default","text":"friend"}],"text":""}

BungeeCord writes (in writeBaseComponent): {"extra":[**{"text":""}**,{"color":"#ff0000","text":"there"},{"font":"minecraft:default","text":"friend"}],"text":""}

Without BungeeCord the client displays "hellotherefriend" with "there" in red.
With BungeeCord the client displays "therefriend" with "there" in red.

This seems due to 1.20.3 servers writing unstyled text components as plain strings without a wrapping compound tag.

Let me know if you need more information.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Steps to reproduce?

**Comment by brickmonster** [comment]
Here's a plugin: https://github.com/brickmonster/bungee-components/releases/tag/release

**Comment by md-5** [comment]
That's not a Spigot plugin. On Spigot, `        player.setPlayerListName( ChatColor.BOLD + "TEST " + ChatColor.RED + " red " + ChatColor.BLUE + " blue " + ChatColor.RESET + player.getName() );` works fine for me.

**Comment by brickmonster** [comment]
You have to go through the component codepath.

**Comment by md-5** [comment]
Please provide a Spigot plugin

**Comment by brickmonster** [comment]
Does spigot have an API for setting the player list name with a component? I thought only the sendMessage API had a component parameter.

**Comment by brickmonster** [comment]
Built locally, can confirm the fix. Thanks a lot! :)
