### ISSUE TITLE
Forced hosts placeholder

### ISSUE THREAD

**Issue by chelminski** [SpigotMC/BungeeCord#3589]
### Feature description

Placeholder which would return the value of the host from which the player joined.

E.g.
Placeholder: %bungeecord_forced_host%
Value: s1.exapmle.com

### Goal of the feature

Depending on which host the user connected from, I could apply different actions to him. In my case specifically, it's about the names of the worlds. This feature has a lot of potential and could be used in many ways.

### Unfitting alternatives

none

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by Janmm14** [comment]
i think this would be better suited in a simple bungee plugin. proxiedplayer.getpendingconnection.getvirtualhost should allow plugins to see what the player typed in to connect to the bungee.

**Comment by md-5** [comment]
What do you mean placeholder? Placeholder for what?

**Comment by chelminski** [comment]
> What do you mean placeholder? Placeholder for what?

Placeholder showing what host the user connected to when using the forced hosts function.

**Comment by md-5** [comment]
Placeholder for what? PAPI? That's a plugin not bungee issue
