### ISSUE TITLE
Personalized Messages

### ISSUE THREAD

**Issue by joaopinto14** [SpigotMC/BungeeCord#3595]
### Feature description

Add a file with all messages that can be displayed on the console or in the game that are issued by BungeeCord.
They could even make a language where the user selects the language in the config or simply place a file with written messages that would be displayed in errors or information, etc., but that the user can modify.
By this I refer to the "messages.properties" file that exists within the bungee jar

### Goal of the feature

With this functionality, everyone can customize and translate into the language they prefer.

### Unfitting alternatives

Edit the "messages.properties" file every time a new version comes out

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by Outfluencer** [comment]
You can paste the message.properties file to your file system bungeecord will load the file on the filesystem first and afterwards the internal so you only need to edit it onece
