### ISSUE TITLE
Bedrock Kicks over bungeecord-chat

### ISSUE THREAD

**Issue by GalleyRP** [SpigotMC/BungeeCord#3603]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:a1cd694:1790

### Server version

1.20.1

### Client version

1.20.51 Bedrock

### Bungeecord plugins

Ajqueue, Nlogin, Geyser-Bungeecord, NChat, Floodgate, LuckPerms, BungeeGuard, MyCommand

### The bug

![image](https://github.com/SpigotMC/BungeeCord/assets/154942862/4ca170c4-5b7c-484c-ab0e-b2fb528225bc)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Bungeecord doesn't support bedrock. This is a geyser issue.
