### ISSUE TITLE
Allow setting custom server brand to show to clients

### ISSUE THREAD

**Issue by mrjasonn** [SpigotMC/BungeeCord#3605]
### Feature description

This would actually be very useful, as server admins would actually want to hide some info. If just the backend server supports this (e.g. Spigot), then the BungeeCord part can't be hidden and would be easier to just set on proxy.

### Goal of the feature

The goal of the feature is to let server admins actually hide some info and also have some nice custom branding.

### Unfitting alternatives

It would be easier for people to configure

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by Outfluencer** [comment]
I think this is against the nature of brands
