### ISSUE TITLE
Player Invisible to others in 1.20.4

### ISSUE THREAD

**Issue by BlissfulAlloy79** [SpigotMC/BungeeCord#3606]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:a1cd694:1790

### Server version

Vanilla Server (Fabric) 1.20.4

### Client version

1.20.4

### Bungeecord plugins

No plugins

### The bug

Minecraft server:
Vanilla minecraft server with Fabric mod loader

Config:
`online-mode=false`
`enforce-secure-profile=false`
(the rest remains unchanged)

Server Mod:
NoChatReports-FABRIC
> (As bungeecord cannot work with vanilla server after 1.20 due to `Invalid signature for profile public key. Try restarting your game.` Using NoChatReports can prevent this problem)

Bungeecord setup is clean, no plugin installed

Bungee Config:
`enforce_secure_profile: false`
`online_mode: true`
`ip_forward: false` (disabled otherwise player cannot join)
(except `servers:`, the rest remains unchanged)

Reproduce:
Player join the server via bungeecord, they cannot see each other

The issue cannot be reproduced with the exactly same setup in 1.20.1, so I guess it should be a version related problem

Remarks:
Player that joined directly to the server without bungeecord can see other player, including those joined via bungeecord

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
This could be #3604

Is there not a bungeecord mob for frabric?

**Comment by Outfluencer** [comment]
Yes #3604 fixes this

**Comment by BlissfulAlloy79** [comment]
tysm! ❤️
