### ISSUE TITLE
ClickEvent doesn't work properly.

### ISSUE THREAD

**Issue by schemil053** [SpigotMC/BungeeCord#3607]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:a1cd694:1790

### Server version

git-Paper-351

### Client version

1.20.4

### Bungeecord plugins

Plugins (17): reconnect_yaml, LuckPerms, VulcanBungee, BungeeDebugMarkerKitBungee, BungeeBanMySQL, cmd_list, SchemilCloud, cmd_find, BungeeWebMFASystem, Joinme, PlugManBungee, BungeeChatLink, cmd_server, BotSentry, cmd_alert, cmd_send, BungeeServerManager

### The bug

Hello,
I got an issue while trying to send a player a message.

Example code to reproduce:

       if(sender instanceof ProxiedPlayer) {
            TextComponent component = new TextComponent("§aKlicke zum vorschlagen.");
            component.setClickEvent(new ClickEvent(ClickEvent.Action.SUGGEST_COMMAND, "testus"));
            sender.sendMessage(component);
        }
I use vanilla 1.20.4 as my client and the latest BungeeCord-Version. I tried to use ClickEvent.Action.COPY_TO_CLIPBOARD, and this doesn't work too.

Does anybody know how to fix this?

### Log output (links)

```
16:37:39 [INFORMATION] [schemil053] -> UpstreamBridge has disconnected
16:37:39 [INFORMATION] [schemil053] <-> DownstreamBridge <-> [EXTLobby-2] has disconnected
```

Client-Logs:

`[16:37:39] [Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode: No key value in MapLike[{action:"suggest_command"}] {clickEvent:{action:"suggest_command"},text:"§aKlicke zum vorschlagen."}
`

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Cannot reproduce. The json in your client log does not match bungee. Remove all plugins and used Spigot.

**Comment by schemil053** [comment]
After a restart, it can only be reproduced by adding the value null as parameter for the click event.
