### ISSUE TITLE
HAProxy 2.0+ Proxy Protocol Spam - InitialHandler - NativeIoException: recvAddress(..) failed: Connection reset by peer

### ISSUE THREAD

**Issue by Imptovskii** [SpigotMC/BungeeCord#3608]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:c69acf7:1791

### Server version

This server is running Pufferfish version git-Pufferfish-22 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 42ef3dc on HEAD)

### Client version

HAProxy

### Bungeecord plugins

AuthMeBungee, LuckPerms, 2LS Antibot, PistonMOTD, SkinsRestorer

### The bug

There is no such problem with HAProxy 1.8. When using a version higher than 2.0, a problem with constant warning spam begins. HAProxy 1.8 is currently EOL

Currently installed version 2.6.12 from the Debian 12 repositories.

HAProxy CFG:
```
listen minecraft
        bind :25565
        mode tcp
        option tcp-check
        balance roundrobin
        server minecraft1 1.1.1.1:11111 check-send-proxy check send-proxy-v2
        server minecraft2 2.2.2.2:22222 check-send-proxy check send-proxy-v2 backup
```

### Log output (links)

```
15:34:51 [WARNING] [/1.1.1.1:11111] <-> InitialHandler - NativeIoException: recvAddress(..) failed: Connection reset by peer
15:34:52 [WARNING] [/2.2.2.2:22222] <-> InitialHandler - NativeIoException: recvAddress(..) failed: Connection reset by peer
15:34:53 [WARNING] [/3.3.3.3:33333] <-> InitialHandler - NativeIoException: recvAddress(..) failed: Connection reset by peer
```
![1](https://github.com/SpigotMC/BungeeCord/assets/82046704/b1d63e77-67d4-47c0-ab3b-846bab02fce4)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
What is check-send-proxy?
Is your configuration the same for each version?
What if you disable the proxy protocol?

**Comment by Imptovskii** [comment]
> What is check-send-proxy? Is your configuration the same for each version? What if you disable the proxy protocol?

[check-send-proxy](https://docs.haproxy.org/2.6/configuration.html#5.2-check-send-proxy)

This option forces emission of a PROXY protocol line with outgoing health
checks, regardless of whether the server uses send-proxy or not for the
normal traffic. By default, the PROXY protocol is enabled for health checks
if it is already enabled for normal traffic and if no "[port](https://docs.haproxy.org/2.6/configuration.html#port)" nor "[addr](https://docs.haproxy.org/2.6/configuration.html#addr)"
directive is present. However, if such a directive is present, the
"[check-send-proxy](https://docs.haproxy.org/2.6/configuration.html#check-send-proxy)" option needs to be used to force the use of the
protocol. See also the "[send-proxy](https://docs.haproxy.org/2.6/configuration.html#send-proxy)" option for more information.

**Is your configuration the same for each version?**
Yes

What if you disable the proxy protocol?
`InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 0a0d0a000d0a515549540a2000`

**Comment by md-5** [comment]
What if you disable the proxy protocol?

**Comment by md-5** [comment]
> What if you disable the proxy protocol?

You need to disable it on both bungee and haproxy

**Comment by Imptovskii** [comment]
> You need to disable it on both bungee and haproxy

```
listen minecraft-testing
        bind :25575
        mode tcp
        option tcp-check
        balance roundrobin
        server minecraft1 1.1.1.1:11111 check
```
I made another test section. Disabled the proxy protocol. Configured basic TCP balancing. And there are no errors. But the real IP of the client is not forwarded, and this is a problem.
