### ISSUE TITLE
UTF-8 isn't working

### ISSUE THREAD

**Issue by joaopinto14** [SpigotMC/BungeeCord#3619]
### Bungeecord version

git:BungeeCord-Bootstrap:1.20-R0.3-SNAPSHOT:3e9a7e4:1800

### Bungeecord plugins

None

### The bug

I'm having a problem with the accents in "messages.properties"

It looks like UTF-8 isn't working

### Log output (links)

![Captura de ecrã de 2024-02-22 18-11-11](https://github.com/SpigotMC/BungeeCord/assets/61939916/c08370bb-7a20-4091-9462-7792f3da7894)

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
just dont use utf8
use unicode with \u

**Comment by Outfluencer** [comment]
but it should use utf8 if no other encoding is set with -Dfile.encoding

you could try add -Dfile.encoding=UTF-8
