### ISSUE TITLE
All methods are deprecated in PreLoginEvent

### ISSUE THREAD

**Issue by andreasdc** [SpigotMC/BungeeCord#3626]
### Feature description

Every method is deprecated there:
use single component methods instead
or
use component methods instead
Is it broken or do I check something wrong?
https://github.com/SpigotMC/BungeeCord/blob/7606d4437b3cb13a42c834fd42dc8066a9380e5e/api/src/main/java/net/md_5/bungee/api/event/PreLoginEvent.java#L49

### Goal of the feature

No deprecated methods.

### Unfitting alternatives

-

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by md-5** [comment]
They're not - check your ide

**Comment by andreasdc** [comment]
> They're not - check your ide

Huh?
![image](https://github.com/SpigotMC/BungeeCord/assets/82218780/4c67af32-c65b-40f6-a652-ece3537cc5eb)

**Comment by Janmm14** [comment]
@andreasdc 
Bungee makes use of Lombok annotation code generator. The PreLoginEvent has the `@Data` annotation which (besides other things) causes creation of getter- and setter-methods of all fields of the event.

For example the `getReason()` method referenced inside your screenshot is nowhere explixitely defined.

With "check your IDE" he meant checking from inside a plugin which references bungeecord-api.

I have bungee-api javadocs online which contains also lombok-generated methods:
https://janmm14.de/static/bungeecord-api/net/md_5/bungee/api/event/PreLoginEvent.html
You can see there as well that not every method of the PreLoginEvent is deprecated.

**Comment by andreasdc** [comment]
> @andreasdc Bungee makes use of [Lombok annotation code generator](https://projectlombok.org/). The PreLoginEvent has the `@Data` annotation which (besides other things) causes creation of getter- and setter-methods of all fields of the event.
> 
> For example the `getReason()` method referenced inside your screenshot is nowhere explixitely defined.
> 
> With "check your IDE" he meant checking from inside a plugin which references bungeecord-api, because then it'd check against the compiled bungeecord-api.
> 
> I have bungee-api javadocs online which contains also lombok-generated methods: https://janmm14.de/static/bungeecord-api/net/md_5/bungee/api/event/PreLoginEvent.html You can see there as well that not every method of the PreLoginEvent is deprecated.

Oh right, so I should use getReason() and setReason() and these old methods are just for the compability, right?

**Comment by Janmm14** [comment]
> Oh right, so I should use getReason() and setReason() and these old methods are just for the compability, right?

Correct!
