### ISSUE TITLE
Connecting Forge servers

### ISSUE THREAD

**Issue by Wo1fWEB** [SpigotMC/BungeeCord#3649]
### Feature description

Dear BungeeCord mod developer!

I would like to draw your attention to the issue of connecting servers running on the Forge platform to your wonderful tool. This point is extremely important for many server owners who want to combine their game worlds into a single whole.

### Goal of the feature

We, as part of the Minecraft community, are committed to improving the gaming experience for our players. Integrating servers using Forge with BungeeCord opens up enormous opportunities for us to create unique game scenarios, expanding the functionality and diversity of the game world.

Of course, we understand that the integration process can be complex and requires specific knowledge. However, we believe in your professionalism and the unique skills that you have shown in creating BungeeCord. Therefore, we ask you to consider adding support for Forge-based servers.

### Unfitting alternatives

Thank you for your work and attention to our appeal. We hope for a positive response and are ready to support you in all your endeavors.

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by md-5** [comment]
config.yml -> forge_support: true

**Comment by Wo1fWEB** [comment]
Yes, but when switching it gives an incompatibility error

**Comment by md-5** [comment]
That's not evident in your ticket
