### ISSUE TITLE
Could not connect to a default or fallback server. Incorrectly configured address/port/firewall

### ISSUE THREAD

**Issue by Krakenskulls1** [SpigotMC/BungeeCord#3671]
### Bungeecord version

idk

### Server version

1.8.8

### Client version

1.8.8

### Bungeecord plugins

Login security
simple homes (1)
simple tpa (1)
worldedit-bukkit

### The bug

When i try to login to my server it says: <Could not connect to a default or fallback server. Incorrectly configured address/port/firewall> can anyone tell me what this means IM DUMB!!!
Video i used: https://www.youtube.com/watch?v=LofD2BXNQ8Q
Github i used: https://github.com/IsmaelTechProxy/server-test
my github: https://github.com/Krakenskulls1/StarAnarchy

P.S I NEED HELP STAT

### Log output (links)

```
Could not connect to a default or fallback server. Incorrectly configured address/port/firewall
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [x] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Krakenskulls1** [comment]
I fixed my issue but  now its saying "IM not registered" how do i fix that???

**Comment by Krakenskulls1** [comment]
bruhhhh

**Comment by Janmm14** [comment]
This is no general purpose help forum. place. "IM not registered" is not a message bungeecord produces as far as I know. I suggest you go to spigotmc or papermc forums or figure stuff out yourself.

Additionally next time, make sure which check boxes you tick ;) Next time you might agree to have first first newborn taken away.

**Comment by Krakenskulls1** [comment]
> This is no general purpose help forum. place. "IM not registered" is not a message bungeecord produces as far as I know. I suggest you go to spigotmc or papermc forums or figure stuff out yourself.
> 
> Additionally next time, make sure which check boxes you tick ;) Next time you might agree to have your first newborn taken away.

Ok XD
