### ISSUE TITLE
"Your not registerd" How do i fix this?

### ISSUE THREAD

**Issue by Krakenskulls1** [SpigotMC/BungeeCord#3672]
### Bungeecord version

1.8.8

### Server version

u23

### Client version

1.8.8

### Bungeecord plugins

bstats
LoginSecurity
PluginMetrics
SimpleHomes
SimpleTPA
WorldEdit

### The bug

Ok, so when i try to enter my server i gat a error saying"You are not Registered on this server" how do i fix this???
my codespace: 

### Log output (links)

```
You are not Registered on this server
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
1) That message is not from bungee
2) Refer to "checking" section above
