### ISSUE TITLE
Bungeecord error for last version

### ISSUE THREAD

**Issue by Areanydd** [SpigotMC/BungeeCord#3673]
### Bungeecord version

Last build #1836 (i can t see now because i changed until i solve this problem)

### Server version

1.20.1 and 1.20.4 too

### Client version

1.20.1, 1.20.4, 1.20.5

### Bungeecord plugins

![Screenshot 2024-04-25 195930](https://github.com/SpigotMC/BungeeCord/assets/25862359/32aea2e5-a1ce-4b06-ba73-540ac06076f4)

### The bug

hi, from the last builds of bungeecord, i have this errors https://paste.md-5.net/qomuremiyu.cs (when some players try to join with every version but not every player) https://paste.md-5.net/focofafese.css (when player with 1.20.5 try to join)

### Log output (links)

ERROR 1:
[19:29:59] [Server thread/INFO]: Cristian lost connection: Invalid signature for profile public key.
Try restarting your game.

ERROR 2:
[18:41:11 INFO]: [Areanydd] disconnected with: Exception Connecting: DecoderException : io.netty.util.IllegalReferenceCountException: refCnt: 0, decrement: 1 @ io.netty.handler.codec.MessageToMessageDecoder:98

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by bob7l** [comment]
I would test with no plugins first. You've got a lot of protocol level plugins like Protolize which might not be compatible with 1.20.5 yet.
