### ISSUE TITLE
Invalid signature for profile public key

### ISSUE THREAD

**Issue by homerek111** [SpigotMC/BungeeCord#3674]
### Bungeecord version

newest

### Server version

newest paper

### Client version

1.20.1

### Bungeecord plugins

Antibot
BoostedAudio
CleanMOTD
epicguard-bungee
FastLoginBungee
LuckPermsBungee
SkinsRestorer
TCPShield
VulcanBungee

### The bug

Newest bungeecord is causing "Invalid signature for profile public key." error when player joins servers on 1.20 versions (on 1.19.2 there is no issue as i tested)

### Log output (links)

```
[03:02:12 INFO]: _homerek lost connection: Invalid signature for profile public key.
Try restarting your game.```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Cannot reproduce, and you haven't tested without plugins and on Spigot.

**Comment by Xayanix** [comment]
@homerek111 problem is related to FastLogin it needs to be updated

**Comment by homerek111** [comment]
> @homerek111 problem is related to FastLogin it needs to be updated

@Xayanix updated to the newest devbuild from https://ci.codemc.io/job/Games647/job/FastLogin/ and this issue still occures :/ It must be caused by bungeecord (flamecord dev told me that it is some issue in bungeecord...)

**Comment by md-5** [comment]
If it only occurs with a plugin why do you think it is an issue with Bungee?

**Comment by homerek111** [comment]
> If it only occurs with a plugin why do you think it is an issue with Bungee?

oh... sorry, you are right - i just tested it without FastLogin and indeed error does not happen anymore...
The problem for me is that using the latest dev build didn't fix the issue as @Xayanix recommended :/
