### ISSUE TITLE
Can't connect to servers - invalid signature key

### ISSUE THREAD

**Issue by Xayanix** [SpigotMC/BungeeCord#3675]
### Bungeecord version

#1838

### Server version

1.20.1

### Client version

1.20.1

### Bungeecord plugins

None, just my own

### The bug

![image](https://github.com/SpigotMC/BungeeCord/assets/12672902/bd146433-c147-4c8d-9d08-28ba952e4fd3)

This happens only on 1.20.5 update, downgrading to 1.20.4 build fixes problem

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Xayanix** [comment]
[00:51:34] [Server thread/INFO]: UnixejPL lost connection: Invalid signature for profile public key.
Try restarting your game.

**Comment by md-5** [comment]
Which is the first build with the issue?

**Comment by Xayanix** [comment]
Uh, thats difficult for testing for me (poor internet connection, would take ages if i test all builds :( ).
But i switched back to Waterfall #572 aka 1.20.4 and it works well

**Comment by md-5** [comment]
You can test builds by half.

As it stands there are no reproduction steps in this issue and no identified version with the issue -> closed

**Comment by Xayanix** [comment]
You broke it at #1827 with https://github.com/SpigotMC/BungeeCord/commit/1be25b6c74ec2be4b15adf8ca53a0497f01e2afe .

**Comment by md-5** [comment]
cc/ @Outfluencer

**Comment by md-5** [comment]
> You broke it at #1827 with [1be25b6](https://github.com/SpigotMC/BungeeCord/commit/1be25b6c74ec2be4b15adf8ca53a0497f01e2afe) .

Thanks. Do you have IP forwarding enabled? Is your bungee online or offline?

**Comment by Xayanix** [comment]
ip forwarding: enabled
bungee online mode depends, i have online for players with premium minecraft and offline to cracked usernames

**Comment by Outfluencer** [comment]
What players are affected? cracked or premium or both?

**Comment by Outfluencer** [comment]
I tested cracked and premium again, i can't reproduce

**Comment by md-5** [comment]
Could be whatever plugin they have to allow both cracked and premium.

Does the issue exist without plugins?

**Comment by Xayanix** [comment]
I tested it and indeed, premium login plugins no longer work on BungeeCord builds above #1827.
Looks like replacing online mode UUID to offline UUID causes the problem.

**Comment by Xayanix** [comment]
Fixed it by altering rewriteId field too.

![image](https://github.com/SpigotMC/BungeeCord/assets/12672902/66f90c0c-676b-4c79-bd0c-75d52430df4e)

**Comment by Outfluencer** [comment]
🙃

**Comment by Jcodeerd** [comment]
> Fixed it by altering rewriteId field too.
@Xayanix  Which file did you change this in?

**Comment by Xayanix** [comment]
As you can see on InitialHandler
