### ISSUE TITLE
HAProxy layer 7 health-check not possible anymore

### ISSUE THREAD

**Issue by Packsolite** [SpigotMC/BungeeCord#3689]
### Bungeecord version

52ab21b1ffcde905bad2a65e98d82424b72826c4

### Server version

any

### Client version

any

### Bungeecord plugins

any

### The bug

So this commit broke the HAProxy Layer 7 check:
https://github.com/SpigotMC/BungeeCord/commit/6e1751733f6b3dafe824dcd7f00d5ed86572ba37

Before  this commit, we could use a legacy proxy ping to make sure a Bungee instance is up & healthy:
```
 check-send-proxy check
        option tcp-check
        tcp-check send-binary fe
        tcp-check expect binary ff
```

This no longer seems possible, as the proxy now closes the connection, resulting in HAProxy marking the server as offline.
![image](https://github.com/SpigotMC/BungeeCord/assets/102829507/64988822-1b41-4133-bf6d-f679c8c354fa)

### Log output (links)

none

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
are you checking by legacy pings?

**Comment by Packsolite** [comment]
> are you checking by legacy pings?

As clearly stated in the issue report, yes.

**Comment by Outfluencer** [comment]
why is that needed, i think the connection accept threads are the same as the one handling the legacy ping, if one  works the other should also

**Comment by Packsolite** [comment]
> why is that needed, i think the connection accept threads are the same as the one handling the legacy ping, if one works the other should also
> 

One could argue that it's a "cleaner" solution to not just check if the layer 4 tcp connection is accepted, but if you can actually stream useful data from it. This way you could even use the response as a factor for load balacing and stuff.
I don't see a reason why you would change it from the previous behaviour...

**Comment by Outfluencer** [comment]
because of this
https://github.com/SpigotMC/BungeeCord/issues/3608

**Comment by Packsolite** [comment]
> because of this #3608

If you send a legacy ping there is no log entry at all. You could also do a handshake and gracefully close the connection from HAProxy.
This seems like a dirty solution to me.

**Comment by Outfluencer** [comment]
done

**Comment by Packsolite** [comment]
Any updates on this? Would be nice to have this resolved for the 1.21 release.

**Comment by Outfluencer** [comment]
I created a pr, that i think fixes this issue. You need to wait for md_5 to review it and maybe merge it.

**Comment by Packsolite** [comment]
> Should be fixed now @Packsolite please try it with the latest build
Can confirm working again. Thanks for the quick fix!
![image](https://github.com/SpigotMC/BungeeCord/assets/102829507/cd6b4d2f-17db-480c-8769-f7a6cd9a90e8)
