### ISSUE TITLE
Help me please!

### ISSUE THREAD

**Issue by MGMistary** [SpigotMC/BungeeCord#3708]
### Feature description

Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? io.netty.channel.AbstractChannel$AnnotatedConnectException

I do not know what to do

### Goal of the feature

ва

### Unfitting alternatives

ыа

### Checking

- [X] This is not a question or plugin creation help request.
- [X] This is a **feature or improvement request**.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] I did not use this form to report a bug.

**Comment by md-5** [comment]
> Incorrectly configured address/port/firewall? 

Your configured server is not reachable
