### ISSUE TITLE
Help me please! / Помоги мне пожалуйста!

### ISSUE THREAD

**Issue by MGMistary** [SpigotMC/BungeeCord#3709]
### Bungeecord version

rrwa

### Server version

1.20.1

### Client version

asfg

### Bungeecord plugins

wfffawf

### The bug

Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? io.netty.channel.AbstractChannel$AnnotatedConnectException

I do not know what to do / Я не знаю что делать

### Log output (links)

fdw

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [X] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
## Creating a new issue after your first one (#3708) was closed is ***not*** ok.
<sub>Use https://www.spigotmc.org forums for general help like configuration.</sub>
