### ISSUE TITLE
Error when I'm trying to connect to a server

### ISSUE THREAD

**Issue by akk1to** [SpigotMC/BungeeCord#3725]
### Bungeecord version

BungeeCord-Bootstrap:1.21-R0.1-SNAPSHOT:8b195d1:1852

### Server version

PandaSpigot version git-PandaSpigot-122 (MC: 1.8.8)

### Client version

1.8.9

### Bungeecord plugins

Antibot
BungeeGuard
IPWhitelist
LeeesBungeeQueue
xCord

### The bug

Hello Github. I'm trying to setup a connection from proxy server to my bedwars server. When I'm trying to join into the server through the proxy, it keep send back this error. Please anyone can you help me? I need to fix this bug real quick

### Log output (links)

```
14:00:39 [INFO] [DreamsDragon_YTB] <-> ServerConnector [bed] has connected
14:00:39 [INFO] [DreamsDragon_YTB] <-> DownstreamBridge <-> [auth] has disconnected
14:00:39 [WARNING] [DreamsDragon_YTB] <-> DownstreamBridge <-> [bed] - could not decode packet! java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 196, widx: 384, cap: 512))
14:00:39 [INFO] [DreamsDragon_YTB] <-> DownstreamBridge <-> [bed] has disconnected
14:00:39 [INFO] [DreamsDragon_YTB] <-> ServerConnector [auth] has connected
```

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [x] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Janmm14** [comment]
this is not a general software problem. general connecting works fine. to work through your personal cofiguration(-like) issues, pelase use spigotmc forums.
in general: try without plugins, watch spigot console as well etc.
i will not respond here further.

i can also **not** reproduce this issue using latest bungee and 1.8.9 client and spigot 1.8.8
