### ISSUE TITLE
UpStreambridge is discnnected

### ISSUE THREAD

**Issue by EagAnarchy** [SpigotMC/BungeeCord#3740]
### Bungeecord version

Unknown

### Server version

1.2.6

### Client version

1.8

### Bungeecord plugins

EaglerXbungee

### The bug

Im trying to make a MC server but I end up getting this message:
<details>
<summary>Terminal Message</summary>
<br>
23:58:27 [INFO] [EaglercraftXBungee] [/[0:0:0:0:0:0:0:1%0]:40814]: Connected via websocket
23:58:27 [INFO] [EaglercraftXBungee] [/[0:0:0:0:0:0:0:1%0]:40814]: Origin header is https://eaglercraft.com
23:58:27 [INFO] [EaglercraftXBungee] [/[0:0:0:0:0:0:0:1%0]:40814]: Logged in as 'TexFR'
23:58:27 [INFO] [TexFR] -> UpstreamBridge has connected
23:58:27 [INFO] [TexFR] disconnected with: Could not connect to a default or fallback server. Incorrectly configured address/port/firewall? io.netty.channel.AbstractChannel$AnnotatedConnectException
23:58:27 [INFO] [TexFR] -> UpstreamBridge has disconnected
</details>

And when I join the server it says:
![image](https://github.com/user-attachments/assets/32b6139d-87cf-49ac-ab15-3339f83b60b7)

Pls help

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
Unknown and 1.2.6 are both invalid versions

**Comment by EagAnarchy** [comment]
wdym

**Comment by Outfluencer** [comment]
Bungeecord version
Unknown

Server version
1.2.6

**Comment by EagAnarchy** [comment]
my Minecraft version is 1.8 but how do I find the bungee cord version?

**Comment by Outfluencer** [comment]
i think you just need to configure the backend server in your config.yml

**Comment by EagAnarchy** [comment]
alright

**Comment by EagAnarchy** [comment]
which config do I configure: 
server_connect_timeout: 5000
enforce_secure_profile: false
remote_ping_cache: -1
forge_support: false
player_limit: -1
permissions:
  default:
  - bungeecord.command.server
  - bungeecord.command.list
  admin:
  - bungeecord.command.alert
  - bungeecord.command.end
  - bungeecord.command.ip
  - bungeecord.command.reload
  - bungeecord.command.kick
  - bungeecord.command.send
  - bungeecord.command.find
timeout: 30000
log_commands: false
network_compression_threshold: 256
online_mode: true
disabled_commands:
- disabledcommandhere
servers:
  lobby:
    motd: '&1Just another BungeeCord - Forced Host'
    address: localhost:25565
    restricted: false
listeners:
- query_port: 25577
  motd: '&1Another Bungee server'
  tab_list: GLOBAL_PING
  query_enabled: false
  proxy_protocol: false
  forced_hosts:
    pvp.md-5.net: pvp
  ping_passthrough: false
  priorities:
  - lobby
  bind_local_address: true
  host: 0.0.0.0:25577
  max_players: 1
  tab_size: 60
  force_default_server: false
ip_forward: false
remote_ping_timeout: 5000
reject_transfers: false
prevent_proxy_connections: false
groups:
  md_5:
  - admin
connection_throttle: 4000
stats: 1d72a24e-9d6e-4719-ab5b-7b186ff7fd95
connection_throttle_limit: 3
log_pings: true

**Comment by Outfluencer** [comment]
https://www.spigotmc.org/wiki/bungeecord-configuration-guide/

**Comment by EagAnarchy** [comment]
i messed around with the config.yml and the same thing happened
