### ISSUE TITLE
Online mode server hangs on encrypting rather than sensible error message

### ISSUE THREAD

**Issue by md-5** [SpigotMC/BungeeCord#3741]
### Bungeecord version

1.21

### Server version

1.21.2

### Client version

1.21.2

### Bungeecord plugins

N/A

### The bug

Online mode server hangs on encrypting rather than sensible error message

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by md-5** [comment]
Might be an issue with #3737, need to investigate further

**Comment by Outfluencer** [comment]
I tested on windows and on linux arm with natives.
Both works fine for me. (tested on latest bungee on snapshot 24w37a, i only updated the snapshot protocol version)

**Comment by Outfluencer** [comment]
i know that if you misscounfigure ip forwarding that you will be in an infinit loggin screen because the backend disconnects you but the bungee does not

**Comment by Outfluencer** [comment]
https://github.com/SpigotMC/BungeeCord/pull/3743 could be a solution to these problem

**Comment by md-5** [comment]
#3743
