### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by thomAdastaylpor** [SpigotMC/BungeeCord#3745]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.com to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by Janmm14** [comment]
do not click link. do not do what the page wants you to do. its malware

**Comment by Outfluencer** [comment]
Yes its likely iplogger or maleware  or something please report this guy

**Comment by NekosAreKawaii** [comment]
![image](https://github.com/user-attachments/assets/78f46e9d-45ce-46ea-838f-ea783c403c50)
nice malware
