### ISSUE TITLE
Joining whitelisted server kicks you with "Unexpected disconnect during server login, did you forget to enable BungeeCord / IP forwarding on your server?"

### ISSUE THREAD

**Issue by andreasdc** [SpigotMC/BungeeCord#3753]
### Bungeecord version

latest

### Bungeecord plugins

0-

### The bug

Connecting to a whitelisted server disconnects you from the proxy. Whitelist is blocking the player on bukkit side in AsyncPreLoginEvent.

### Checking

- [X] I am using BungeeCord and **not a fork**. Issues with forks should not be reported here.
- [X] I think this is **not** an issue with a bungeecord plugin.
- [ ] I have not read these checkboxes and therefore I just ticked them all.
- [X] This is not a question or plugin creation help request.

**Comment by Outfluencer** [comment]
whats the issue? "Connecting to a whitelisted server disconnects you from the proxy." seems right to me

**Comment by andreasdc** [comment]
> whats the issue? "Connecting to a whitelisted server disconnects you from the proxy." seems right to me

It shouldn't kick you from the proxy. I'm talking about connecting to from 1 server to 2nd server which is whitelisted.

**Comment by Janmm14** [comment]
Before, a kick during attempted server switch - after having an established connection - would just display in chat.

**Comment by andreasdc** [comment]
> Before, a kick during attempted server switch - after having an established connection - would just display in chat.

Exactly.
