### ISSUE TITLE
Bad packet errors

### ISSUE THREAD

**Issue by cuddylier** [SpigotMC/BungeeCord#549]
Hi

Ever since I moved back to bungee within the last week my players have been plagued with bad packet, bad compressed data and Gzip random kick messages.

I read through a few of the issues from the past and I'm getting the same bad packet errors all the past reports have had.

I'm using spigot 1071 on all the servers in my network and bungeecord build: 610.

My player count peaks at around 800 daily.

**Comment by turtlehunter** [comment]
We got users with this issue 3 times in 2 days in #minecrafthelp

This is a paste that we made from one user. It includes a full Wireshark capture, a screenshot and a dxdiag. That occured on mineplex.com, but we got 2 reports from hypixel.

http://paste.ubuntu.com/10419174/

**Comment by md-5** [comment]
We don't support either of those two networks as they use custom hacked together versions of our software.
