### ISSUE TITLE
Everyone Has The Same IP!

### ISSUE THREAD

**Issue by TheRealBoawsome** [SpigotMC/BungeeCord#571]
Hello, So I Got Bungee Running. I Also Have AuthMe, But Everyone Has The Same IP. Why Is That?

**Comment by willypro7** [comment]
> Debido a la forma en que funciona bungeecord, todas las conexiones deben pasar a través del servidor de bungeecord a cada servidor de Minecraft. Esto da como resultado que cada usuario tenga la misma ip. Esto no es un error, cierre el problema.

falso. configure en spigot.yml bungeecord = true y ya
