### ISSUE TITLE
Could not connect to default server, please try again later: java.net.ConnectException

### ISSUE THREAD

**Issue by robharding** [SpigotMC/BungeeCord#634]
I have tried everything, my bungee wont connect to my server.

Bungee Console: http://pastebin.com/YJywmLTp
Bungee Config: http://pastebin.com/7z18d2Pc
Server Config: http://pastebin.com/Bg7wRdkD
does anyone know why this is happening?

**Comment by MoseRattoe** [comment]
Hi. When i Left My bungee cord server (in pvp server no in hub) After Rejoin it Not Connect to Hub Server It Connect To Last Server i Was Leave

**Comment by MoseRattoe** [comment]
it says( Cloud Not Connect To Target Server. You Moved To fallback Server

**Comment by Janmm14** [comment]
@MoseRattoe dont dig up 6 year old issues please. Also this is not a fault in bungeecord, go to spigtomc.org forums for help why bungee could not connect to your first priority server.
