### ISSUE TITLE
Where I can download BungeeCord 1.7.2?

### ISSUE THREAD

**Issue by ander2300** [SpigotMC/BungeeCord#681]
Where I can download BungeeCord 1.7.2?

**Comment by bignose956** [comment]
This is the closest thing I could find
http://ci.md-5.net/job/BungeeCord/1100/

**Comment by Janmm14** [comment]
@bignose956 this issue is 3 years old...

**Comment by bignose956** [comment]
Do you think I care?? Its still a current issue!
