### ISSUE TITLE
IllegalArgumentException : Team ... already exists in this scoreboard

### ISSUE THREAD

**Issue by mickare** [SpigotMC/BungeeCord#816]
We have many, I mean realy MANY, players disconnecting / beeing kicked from the server while changing from one server to another.

http://imageshack.com/a/img11/951/i2mz.png

Main problem is that all our servers use scoreboards.
I don't want to clear the scoreboards manually from a player before pushing him to another server.

Problem is that BungeeCord doesn't clear the old scoreboard, when the Server Connection is changed.
The new Bukkit server doesnt know that the players scoreboard has the team "X", but the proxy does!

So if I register a new Team "X", the BungeeCord has an IllegalArgumentException.

Please answer if this is a bug, or if this is a feature.
If so, i have to write a BungeeCord Plugin that solves my problem.

Regards,
Michael

********\* BungeeCord Version *********
787

********\* Console Log *********
http://pastebin.com/uvD1AhwW

**Comment by MentosPL** [comment]
Fix is needed i have the same problem. Spigot 1.12.2 + FeatherBoard + Bungeecord/Hexacord/Waterfall.

i have no idea what to do.

**Comment by TheMolkaPL** [comment]
Try to reproduce it without the FeatherBoard plugin. Also only __BungeeCord__ is supported here, please report forks in their respective repositories.

**Comment by MentosPL** [comment]
i have removed FeatherBoard, i have error:
Team acollide already exists in this scoreboard @ com.google.common.base.Preconditions:191

**Comment by i9hdkill** [comment]
In your case another plugin that adds scoreboards, probably an anti-collide plugin causes this.
Open a thread here for further help, as this isn't a BungeeCord bug.
https://www.spigotmc.org/forums/spigot-plugin-help.42/

**Comment by TheMolkaPL** [comment]
@MentosPL Try to reproduce it without ANY plugins. Please give us the stack trace (error message).

**Comment by mickare** [comment]
If you are wondering how we solved it back in the days ... * cough * ... 4 years ago.
We simply removed the scoreboard from the player before moving him.

**Comment by MentosPL** [comment]
I'm using BackToTheRoots (anti collide plugin)

**Comment by Zafiro93** [comment]
Solution:
1. Stop the server.
2. Delete file scoreboard.dat inside world/data/ where world is your main world.
3. Start the server.

**Comment by T4B999** [comment]
> Solution:
> 
> 1. Stop the server.
> 2. Delete file scoreboard.dat inside world/data/ where world is your main world.
> 3. Start the server.

<3

**Comment by DevSnx** [comment]
> Solution:
> 
> 1. Stop the server.
> 2. Delete file scoreboard.dat inside world/data/ where world is your main world.
> 3. Start the server.

not working..

**Comment by legendcuzican13** [comment]
also having the same problem
