### ISSUE TITLE
Bungee Server in Server List Keeps on pinging and says its outdated.

### ISSUE THREAD

**Issue by darkllama23** [SpigotMC/BungeeCord#826]
When I first setup my bungee server, it was working fine, when you refreshed the serverlist it showed the correct amount of players and the motd right away. But out of now where it hangs on "Pinging" for at least 20 seconds until it says the motd and "1.7.2 (Mouse Hover: "The Server is out of date" - even tough I have the same minecraft version)" I can still connect to the server at anytime without problems, but other players and server lists thinks the server list is down. At first I thought it was a bug with the current build (#783), so I updated it to the lastest build (#800) but same results, so I also tought it was doing this because one of our servers on our network is down, so I removed that server from the config and same result.

**Comment by VictoryAndGlory** [comment]
Well, after 4 years I'm here with a solution. Compress your server icon. You may use compresspng.com to compress your server icon online.
