### ISSUE TITLE
Bungee can not connect to Forge/MCPC in 1.7

### ISSUE THREAD

**Issue by mindforger** [SpigotMC/BungeeCord#899]
Using Bungee #847 and MCPC 1.7 B74 i can not connect via Bungee to the MCPC 

i got stuck during login and get a netty redtimeout and on the mcpc i only get "user disconnected", no more errors or warnings or any logs

as already said in IRC i asked for forge support and got told there were some changes that may have not been considered in bungee implementation. 

I am sorry that i can not provide more details, but i really hope it will be availabe again soon.

**Comment by camogirl183** [comment]
I want to play Mineplex on my mac but it says I have to enable something in my BungeeCord config.  I don't even know if I have BungeeCord at all!  Can someone help me!?!?!?

**Comment by Janmm14** [comment]
@camogirl183 Please do not post below another issue. And that what you said, seems to be an issue with mineplex. So post it to them. If you are using the forge client, try out the vanilla client.

**Comment by theosaris** [comment]
https://dl.dropboxusercontent.com/u/28705212/BungeeCord-Fml.jar Where can I find this download?
I'm wanting to connect a Spigot 1.7.10 and a Mineforge 1.7.10 server via BungeeCord, no luck at the moment just get the handshake issue.

00:50:23 [INFO] [theosaris] <-> ServerConnector has connected
00:50:23 [INFO] [theosaris] <-> ServerConnector has disconnected

**Comment by xion87** [comment]
same issue here
12:07:41 [INFO] [Malachiel] <-> ServerConnector [pixelmon] has connected
12:07:41 [INFO] [Malachiel] <-> ServerConnector [pixelmon] has disconnected

**Comment by Janmm14** [comment]
@xion87 Please look at the date. Try using latest bungeecord version.

**Comment by xion87** [comment]
i already tried, i am using 1.8+forge pixelmon into lastest bungeecord

**Comment by nevercast** [comment]
@md-5 Can you confirm that 1.7.* support was removed from later builds, thus forge would be affected?

**Comment by md-5** [comment]
Yes Bungee only supports 1.8 / 1.9 / 1.9.4
