### ISSUE TITLE
Edit messages without modifying JAR

### ISSUE THREAD

**Issue by vemacs** [SpigotMC/BungeeCord#901]
It would be nice if we could put `messages.properties` in the server root to edit messages. I've committed [an attempt at this](https://github.com/vemacs/BungeeCord/commit/d3ff61e39f607530f3547b2f8a2b105772aaba2f), but it doesn't work for some reason.

Editing messages currently requires [modifying the JAR](http://www.spigotmc.org/threads/customisable-messages.9469/#post-92069).

**Comment by TheJayZ** [comment]
I want this so bad

**Comment by Janmm14** [comment]
use https://github.com/WaterfallMC/Waterfall or https://github.com/minotopiame/FlexPipe

**Comment by md-5** [comment]
9dfad87eeb6a52cf2e73a4e3c349fdec303b98f5
