### ISSUE TITLE
IP Forward Problems

### ISSUE THREAD

**Issue by swagygamer** [SpigotMC/BungeeCord#996]
well today i have wanted to do some kind of things on my server and i wanted to get the real IPs for my server with bungeecord so i set up ip_forward: true and bungeecord: true in both of the configs ( spigot.yml & config.yml ) So um.. I have no plugins such as IPWhitelist, i have no plugin related to bungeecord on my Spigot server, well i have Bungeesuite but that dosen't make any problem i think.. Since when i remove it it's the same. Only bungeesuite on my Bungeecord server also. So.. I found out something wierd... Might be interesting. So here is what happens.
- IP_Forward: True ( Bungeecord ), BungeeCord: True ( Spigot ) & Online_Mode: True ( Bungeecord )
- I run both of the servers
- No problem in running them.
- I HAVE EVERYTHING UPDATED TO THE LAST VERSION.
- When i try to connect from the Bungeecord to the server, it just dcs me. No error or anything. Now when i connect from the server ip directly, it says 'If you wish to use IP Forwarding, please enable it in your bungeecord config as well!'
- I have done everything correctly.
- Just saying, when i have ip_forward and bungeecord false everything works, but anyways.
- Now, i test again with Online_Mode: false in the bungeecord config.yml with nothing else changed...
- It Works...

So.. I don't want my server crack, can you please help me right away, i need help fastly.

PC: iMac
OS: OS X Mavericks

**Comment by Minecraftsim** [comment]
same
